"""Phase 15 Canonical Integration Core Data Aggregator"""

from scripts.integrations.int_data_part1 import INTEGRATIONS, EXTERNAL_SYSTEMS
from scripts.integrations.int_data_part2 import INTEGRATION_INTERFACES, DATA_MAPPINGS
from scripts.integrations.int_data_part3 import INTEGRATION_ERRORS, INTEGRATION_MONITORING, INTEGRATION_SECURITY
from scripts.integrations.int_data_part4 import (
    INTEGRATION_TESTS, INTEGRATION_DEPENDENCIES, RETRY_POLICIES,
    RECONCILIATION_POLICIES, INTEGRATION_ENVIRONMENTS
)

__all__ = [
    "INTEGRATIONS",
    "EXTERNAL_SYSTEMS",
    "INTEGRATION_INTERFACES",
    "DATA_MAPPINGS",
    "INTEGRATION_ERRORS",
    "INTEGRATION_MONITORING",
    "INTEGRATION_SECURITY",
    "INTEGRATION_TESTS",
    "INTEGRATION_DEPENDENCIES",
    "RETRY_POLICIES",
    "RECONCILIATION_POLICIES",
    "INTEGRATION_ENVIRONMENTS",
]