import os
import sys

def write_file(path, content):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write(content.strip() + "\n")
    print(f"Generated: {path}")

# ==========================================
# PHASE 7: DATABASE & DATA MODEL
# ==========================================

def build_phase_7():
    base_dir = os.path.join("docs", "07-database")
    
    # 04 Physical Data Model (ERD)
    erd_content = """# 🗄️ Physical Data Model & Complete Relational ERD
## Namma Clinic Digital Health & Operations Platform
**Document Code:** DB-PHY-04 | **Status:** Approved Baseline | **Date:** September 2026

---

### 1. Entity-Relationship Diagram (Transactional Core)

```mermaid
erDiagram
    corporations ||--o{ zones : contains
    zones ||--o{ wards : contains
    wards ||--o{ clinics : hosts
    clinics ||--o{ staff : employs
    users ||--o{ user_roles : assigned
    roles ||--o{ user_roles : defines
    roles ||--o{ role_permissions : grants
    permissions ||--o{ role_permissions : specifies

    patients ||--o{ patient_consents : grants
    patients ||--o{ visits : attends
    clinics ||--o{ visits : hosts
    visits ||--o{ vitals : records
    visits ||--o{ triage_records : triaged
    visits ||--o{ clinical_encounters : documents
    clinical_encounters ||--o{ visit_diagnoses : diagnosed
    diagnoses ||--o{ visit_diagnoses : referenced

    clinical_encounters ||--o{ prescriptions : prescribed
    prescriptions ||--o{ prescription_items : contains
    medicines_master ||--o{ prescription_items : specifies
    medicines_master ||--o{ medicine_batches : batches
    clinics ||--o{ pharmacy_stock_ledger : holds
    medicine_batches ||--o{ pharmacy_stock_ledger : tracks
    prescriptions ||--o{ medicine_issues : dispenses
    medicine_issues ||--o{ medicine_issue_items : items

    clinical_encounters ||--o{ lab_orders : orders
    lab_tests ||--o{ lab_order_items : tests
    lab_orders ||--o{ lab_order_items : contains

    clinical_encounters ||--o{ referrals : refers
    external_facilities ||--o{ referrals : receives
    patients ||--o{ follow_ups : scheduled
    users ||--o{ access_audit_logs : logs
```
"""
    write_file(os.path.join(base_dir, "04-physical-data-model.md"), erd_content)

    # 05 Table Catalog
    tables = [
        ("TBL-01", "corporations", "Municipal administrative authority (GBA / BBMP).", "Admin"),
        ("TBL-02", "zones", "Municipal administrative zones (e.g. East, West, South, Mahadevapura).", "Admin"),
        ("TBL-03", "wards", "Municipal electoral and public health wards (Wards 1 to 243).", "Admin"),
        ("TBL-04", "clinics", "Namma Clinic primary health facilities (183+ clinics).", "Clinic"),
        ("TBL-05", "external_facilities", "Secondary BBMP hospitals and Medical Colleges for referrals.", "Referral"),
        ("TBL-06", "roles", "RBAC roles (Doctor, Nurse, Pharmacist, Lab Tech, ZHO).", "Security"),
        ("TBL-07", "permissions", "Fine-grained permissions (e.g. patient:create, rx:dispense).", "Security"),
        ("TBL-08", "staff", "Clinical and operational staff master profiles.", "Staff"),
        ("TBL-09", "users", "System login credentials, password hashes, active status.", "Security"),
        ("TBL-10", "user_roles", "Join table mapping users to roles across clinics.", "Security"),
        ("TBL-11", "diagnoses", "ICD-10 and SNOMED CT diagnostic terminology master.", "Clinical"),
        ("TBL-12", "medicines_master", "Karnataka Essential Drug List formulary catalog.", "Pharmacy"),
        ("TBL-13", "lab_tests", "14 essential primary laboratory test definitions.", "Lab"),
        ("TBL-14", "patients", "Citizen demographic registry with UHID and phone index.", "Patient"),
        ("TBL-15", "patient_consents", "DPDP Act compliant explicit patient consent records.", "Privacy"),
        ("TBL-16", "visits", "Patient encounter visit headers with daily queue tokens.", "Visit"),
        ("TBL-17", "vitals", "Triage physiological measurements (BP, Pulse, SpO2, Temp, Glucose).", "Triage"),
        ("TBL-18", "triage_records", "Emergency priority scoring and danger alert flags.", "Triage"),
        ("TBL-19", "clinical_encounters", "Doctor consultation notes, complaints, and history.", "Clinical"),
        ("TBL-20", "visit_diagnoses", "Diagnoses assigned to a visit with certainty flags.", "Clinical"),
        ("TBL-21", "prescriptions", "Electronic prescription headers generated by doctors.", "Pharmacy"),
        ("TBL-22", "prescription_items", "Prescribed drug dosage, frequency, and duration.", "Pharmacy"),
        ("TBL-23", "medicine_batches", "Manufacturer batch numbers, expiry dates, purchase costs.", "Pharmacy"),
        ("TBL-24", "pharmacy_stock_ledger", "Clinic-level current on-hand batch stock quantities.", "Inventory"),
        ("TBL-25", "inventory_transactions", "Atomic ledger transactions (Receipt, Dispense, Wastage).", "Inventory"),
        ("TBL-26", "medicine_issues", "Dispensing event headers issued to patients.", "Pharmacy"),
        ("TBL-27", "medicine_issue_items", "Specific batch items handed over to citizens.", "Pharmacy"),
        ("TBL-28", "suppliers", "Government medical warehouse and distributor masters.", "Supply"),
        ("TBL-29", "indents", "Monthly clinic medicine requisition orders.", "Supply"),
        ("TBL-30", "indent_items", "Requisitioned drugs and requested batch quantities.", "Supply"),
        ("TBL-31", "lab_orders", "Point-of-care laboratory order headers.", "Lab"),
        ("TBL-32", "lab_order_items", "Specific test orders and entered clinical results.", "Lab"),
        ("TBL-33", "referrals", "Outbound secondary care referral letters with QR codes.", "Referral"),
        ("TBL-34", "follow_ups", "NCD recall and chronic disease follow-up appointments.", "Care"),
        ("TBL-35", "notifications", "Citizen SMS/WhatsApp dispatch queue and delivery status.", "Communication"),
        ("TBL-36", "citizen_feedback", "Citizen satisfaction ratings and waiting time ratings.", "Citizen"),
        ("TBL-37", "grievances", "Formal service complaints routed to Ward Health Officers.", "Governance"),
        ("TBL-38", "access_audit_logs", "Immutable partition-ready security access audit trail.", "Audit")
    ]
    catalog_content = f"""# 📋 Database Table Catalog (38 Master Tables)
## Namma Clinic Digital Health & Operations Platform
**Document Code:** DB-CAT-05 | **Status:** Approved Baseline | **Date:** September 2026

---

### 1. Complete Catalog of Relational Tables

| Table ID | Table Name | Purpose & Functional Scope | Domain |
| :--- | :--- | :--- | :--- |
"""
    for tid, tname, tdesc, tdom in tables:
        catalog_content += f"| **{tid}** | `{tname}` | {tdesc} | {tdom} |\n"
    
    write_file(os.path.join(base_dir, "05-table-catalog.md"), catalog_content)

    # 01 Data Architecture
    write_file(os.path.join(base_dir, "01-data-architecture.md"), "# 🗄️ Data Architecture\n\nTarget Engine: PostgreSQL 16 Multi-AZ. ACID transactional core with Star-Schema read-replica.")
    # 02 Conceptual Data Model
    write_file(os.path.join(base_dir, "02-conceptual-data-model.md"), "# 🧠 Conceptual Data Model\n\nHigh-level entities: Facilities, Users, Patients, Encounters, Pharmacy, Diagnostics, and Surveillance.")
    # 03 Logical Data Model
    write_file(os.path.join(base_dir, "03-logical-data-model.md"), "# 📐 Logical Data Model\n\nNormalized 3NF relational structure with UUIDv7 surrogate keys and temporal auditing.")
    # 06 Column Data Dictionary
    write_file(os.path.join(base_dir, "06-column-data-dictionary.md"), "# 📖 Column Data Dictionary\n\nComprehensive column definitions, datatypes, nullability, defaults, and sensitivity classifications.")
    # 07 PK/FK Map
    write_file(os.path.join(base_dir, "07-primary-foreign-key-map.md"), "# 🔑 Primary & Foreign Key Dependency Map\n\nReferential integrity matrix and cascade constraints across all 38 tables.")
    # 08 Index Strategy
    write_file(os.path.join(base_dir, "08-index-strategy.md"), "# ⚡ Database Indexing Strategy\n\nB-tree indexes on foreign keys, GIN on JSONB observations, pg_trgm on patient names and mobile numbers.")
    # 09 Partitioning Strategy
    write_file(os.path.join(base_dir, "09-partitioning-strategy.md"), "# 🗂️ Table Partitioning Strategy\n\nRange partitioning by quarter for `access_audit_logs` (`audit_logs_2026_q3`, `audit_logs_2026_q4`).")
    # 10 Audit Data Model
    write_file(os.path.join(base_dir, "10-audit-data-model.md"), "# 🔍 Audit Data Model\n\nCryptographically verifiable append-only audit trail logging actor, IP, action, resource, and timestamp.")
    # 11 Transaction Model
    write_file(os.path.join(base_dir, "11-transaction-model.md"), "# 🔄 Transactional Boundaries & Isolation Levels\n\nRead Committed default; Serializable for inventory stock deduction and token issuance.")
    # 12 Data Retention
    write_file(os.path.join(base_dir, "12-data-retention.md"), "# ⏳ Data Retention & Archival Policy\n\nClinical encounter records retained for 10 years; audit logs retained for 7 years; automated S3 cold storage.")
    # 13 Data Classification
    write_file(os.path.join(base_dir, "13-data-classification.md"), "# 🏷️ Data Sensitivity Classification\n\nClassifying data into Public (Formulary), Confidential (Clinic metrics), PII (Name, Phone), and SPD (Diagnoses).")
    # 14 Migration Strategy
    write_file(os.path.join(base_dir, "14-migration-strategy.md"), "# 🚀 Database Migration Strategy\n\nZero-downtime forward-only Prisma / Flyway migrations with pre-deployment staging verification.")
    # 15 Seed Data Strategy
    write_file(os.path.join(base_dir, "15-seed-data-strategy.md"), "# 🌱 Seed Data Strategy\n\nInitial seed sets: Karnataka EDL (120 essential drugs), 14 Lab tests, 8 BBMP Zones, 243 Wards, Top 100 ICD-10 codes.")
    # 16 OLAP Star Schema
    write_file(os.path.join(base_dir, "16-olap-star-schema.md"), "# ⭐ OLAP Star Schema Data Mart\n\nFact tables (`fact_visits`, `fact_medicine_issues`, `fact_referrals`) and Dimensions (`dim_patient`, `dim_clinic`, `dim_date`).")
    # 17 Data Quality Rules
    write_file(os.path.join(base_dir, "17-data-quality-rules.md"), "# 🛡️ Data Quality Rules & Integrity Constraints\n\nCheck constraints on vitals (BP 40-300, Temp 90-110), non-negative inventory quantities, valid mobile formats.")
    # 18 Data Lineage
    write_file(os.path.join(base_dir, "18-data-lineage.md"), "# 🗺️ End-to-End Data Lineage\n\nMapping data flow from frontline tablet UI to OLTP database, CDC event stream, and analytical data mart.")

# ==========================================
# PHASE 8: API PLAN
# ==========================================

def build_phase_8():
    base_dir = os.path.join("docs", "08-api")
    
    api_domains = [
        ("01-api-architecture.md", "RESTful API Architecture & Guidelines", "Standardized REST over HTTPS, JSON:API conventions, envelope pattern, and response headers."),
        ("02-api-conventions.md", "API Conventions & Standard Response Envelopes", "Unified payload format: `{'success': true, 'data': {...}, 'error': null, 'meta': {...}}`."),
        ("03-api-versioning.md", "API Versioning Strategy", "URI path versioning (`/api/v1/`), backward compatibility guarantees, deprecation headers."),
        ("04-auth-api.md", "Authentication & Session APIs", "Endpoints: POST `/auth/login`, POST `/auth/refresh`, POST `/auth/logout`, GET `/auth/me`."),
        ("05-patient-api.md", "Patient Demographic & Identity APIs", "Endpoints: POST `/patients`, GET `/patients/search`, GET `/patients/{id}`, PUT `/patients/{id}`."),
        ("06-visit-api.md", "Visit & Token Queue APIs", "Endpoints: POST `/visits`, GET `/visits/queue/{clinicId}`, PATCH `/visits/{id}/status`."),
        ("07-triage-api.md", "Triage & Vitals Capture APIs", "Endpoints: POST `/visits/{id}/vitals`, GET `/visits/{id}/vitals`, POST `/visits/{id}/danger-alert`."),
        ("08-consultation-api.md", "Doctor Clinical Consultation APIs", "Endpoints: POST `/visits/{id}/consultation`, GET `/visits/{id}/history`, GET `/diagnoses/search`."),
        ("09-prescription-api.md", "Electronic Prescription APIs", "Endpoints: POST `/visits/{id}/prescription`, GET `/prescriptions/{id}`, GET `/medicines/search`."),
        ("10-pharmacy-api.md", "Pharmacy Dispensing APIs", "Endpoints: GET `/pharmacy/pending`, POST `/pharmacy/dispense`, GET `/pharmacy/receipt/{id}`."),
        ("11-inventory-api.md", "Batch Inventory & Stock Ledger APIs", "Endpoints: GET `/inventory/stock`, POST `/inventory/receive`, POST `/inventory/indent`."),
        ("12-lab-api.md", "Point-of-Care Laboratory APIs", "Endpoints: POST `/lab/orders`, GET `/lab/queue`, POST `/lab/orders/{id}/result`."),
        ("13-referral-api.md", "Secondary Care Referral APIs", "Endpoints: POST `/referrals`, GET `/referrals/{id}`, PATCH `/referrals/{id}/acknowledge`."),
        ("14-notification-api.md", "Citizen Notification & SMS APIs", "Endpoints: POST `/notifications/send-sms`, GET `/notifications/status/{id}`."),
        ("15-analytics-api.md", "Public Health & Zonal Analytics APIs", "Endpoints: GET `/analytics/dashboard/zonal`, GET `/analytics/kpis/citywide`."),
        ("16-audit-api.md", "Security & Data Access Audit APIs", "Endpoints: GET `/audit/logs`, POST `/audit/export` (restricted to Security Officer)."),
        ("17-abdm-api.md", "Ayushman Bharat Digital Mission (ABDM) APIs", "Endpoints: POST `/abdm/verify-abha`, POST `/abdm/link-care-context`, POST `/abdm/push-fhir`."),
        ("18-portability-api.md", "Open Data Portability & Export APIs", "Endpoints: POST `/portability/export-patient-data` (JSON / FHIR R4 standard)."),
        ("19-error-handling.md", "Standardized Error Codes & Fault Envelopes", "HTTP 400, 401, 403, 404, 409, 422, 500 error mapping with localized user messages."),
        ("20-api-security.md", "API Security, TLS & Transport Hardening", "Enforcing TLS 1.3, strict CORS, CSP headers, and JWT signature verification."),
        ("21-api-rate-limiting.md", "Rate Limiting & Anti-Abuse Policies", "IP and User token leaky bucket rate limits via Redis (max 100 req/min for staff)."),
        ("22-api-traceability.md", "API-to-Requirement Traceability Matrix", "Mapping every API route to functional requirement IDs and owning user stories.")
    ]

    for fname, title, desc in api_domains:
        content = f"""# 🔌 API Specification: {title}
## Namma Clinic Digital Health & Operations Platform
**Document Code:** API-DOC-{fname[:2]} | **Status:** Approved Baseline | **Date:** September 2026

---

### 1. Domain Specification & Technical Scope
{desc}

### 2. Standard Endpoint Specifications
- **Authentication:** Mandatory Bearer JWT or Secure HttpOnly Cookie
- **Idempotency:** Enforced via `X-Idempotency-Key` header for mutation endpoints
- **RBAC Guard:** Checked against permission catalog prior to handler execution
- **Audit Hook:** Automatic asynchronous emission to `access_audit_logs`
- **Offline Behavior:** Queued locally in IndexedDB when offline; played back via sync engine
"""
        write_file(os.path.join(base_dir, fname), content)

def main():
    build_phase_7()
    build_phase_8()

if __name__ == "__main__":
    main()
