"""
release_core_data.py
Authoritative machine-readable release registry for Phase 19: Release Management.
Defines exactly 8 Canonical Releases (RELEASE-00 through RELEASE-07).
"""

from typing import Dict, List, Any

RELEASES_LIST: List[Dict[str, Any]] = [
    {
        "id": "RELEASE-00",
        "version": "v0.1.0-alpha",
        "name": "Platform Infrastructure, Security & Architecture Foundation",
        "theme": "Foundation Architecture & Zero-Trust Infrastructure",
        "objective": "Establish immutable containerized multi-tenant infrastructure, Fastify core runtime, PostgreSQL 16 schema, Flyway migrations, Keycloak OIDC, and cryptographic audit logging.",
        "business_value": "Eliminates foundational technical debt, guarantees data isolation across municipal clinics, and enforces DPDP Act 2023 zero-trust security perimeters.",
        "scope": "Monorepo scaffolding, PostgreSQL 16 transactional schema, Flyway migrations V001..V052, Fastify REST boilerplate, Keycloak RBAC/ABAC, WORM audit ledger, OpenTelemetry instrumentation, and CI/CD pipelines.",
        "included_capabilities": [
            "Containerized Fastify REST server with OpenAPI 3.1 validation",
            "PostgreSQL 16 relational database with Flyway migration pipeline",
            "Keycloak OIDC authentication server with Argon2id hashing and RS256 JWTs",
            "WORM tamper-evident audit ledger with HMAC SHA-256 integrity checks",
            "OpenTelemetry distributed tracing, Prometheus metrics, and Pino structured logging",
            "GitHub Actions automated CI/CD pipeline with Trivy container security scanner"
        ],
        "excluded_capabilities": [
            "Clinical consultation workflows and diagnosis coding (deferred to RELEASE-02)",
            "Pharmacy dispensing and FEFO stock deduction (deferred to RELEASE-03)",
            "Production clinic cutover and public-facing citizen portal (deferred to RELEASE-06)"
        ],
        "entry_criteria": "Approved Phase 06 Software Architecture, Phase 07 Database Schema, and Phase 10 Security Architecture baselines.",
        "exit_criteria": "All core foundation services pass 100% automated regression tests with sub-100ms p95 latency and zero Critical/High CVEs.",
        "release_readiness_criteria": "Staging Kubernetes cluster provisioned, DNS routing verified, and Keycloak realm configuration frozen.",
        "dependencies": ["DEPENDENCY-001", "DEPENDENCY-002", "DEPENDENCY-003", "DEPENDENCY-004"],
        "predecessor_release": None,
        "successor_release": "RELEASE-01",
        "related_sprints": ["SPRINT-01", "SPRINT-02"],
        "related_epics": ["EPIC-001", "EPIC-002", "EPIC-003", "EPIC-004", "EPIC-005"],
        "related_features": [f"FEATURE-{i:03d}" for i in range(1, 21)],
        "related_requirements": ["FR-001", "FR-002", "FR-003", "FR-004", "SECR-001", "SECR-002"],
        "related_workflows": ["WF-001", "WF-002", "WF-020"],
        "related_architecture_components": ["Fastify Gateway", "PostgreSQL Primary", "Keycloak IAM", "Prometheus/Grafana", "WORM Ledger"],
        "related_database_entities": [f"TABLE-{i:03d}" for i in range(1, 11)],
        "related_api_families": ["Auth API", "User Management API", "Facility Hierarchy API", "Audit Log API"],
        "related_frontend_modules": ["Admin Console", "Authentication Flow", "Navigation Shell"],
        "related_security_controls": ["RS256 JWT validation", "Argon2id password hashing", "mTLS 1.3 encryption", "HMAC SHA-256 audit chaining"],
        "related_qa_strategy": "Vitest unit tests, Supertest API integration, and automated Trivy vulnerability scanning.",
        "related_devops_controls": "Multi-stage Docker builds, Helm charts for Kubernetes, and automated GitHub Actions CI runners.",
        "related_analytics_capabilities": "Database replication feeds and telemetry log sinks.",
        "related_ai_capabilities": "None in foundation tier.",
        "related_integrations": ["Local WireMock Mocking Gateway"],
        "milestones": ["MILESTONE-001", "MILESTONE-002"],
        "risks": ["RISK-001", "RISK-002", "RISK-003"],
        "blockers": ["BLOCKER-001", "BLOCKER-002"],
        "assumptions": ["ASSUMPTION-001", "ASSUMPTION-002"],
        "constraints": ["MeitY Cloud Hosting Policy", "DPDP Act 2023 Data Localization"],
        "quality_gates": ["QUALITY-GATE-001", "QUALITY-GATE-002", "QUALITY-GATE-003"],
        "acceptance_criteria": "Staff can authenticate, receive scoped JWTs, and execute CRUD operations against facility tables with zero errors.",
        "rollback_criteria": "Rollback to empty staging state via automated Flyway clean scripts if migration fails.",
        "go_no_go_criteria": "Unanimous sign-off by Solution Architect, DevOps Lead, and Security Officer.",
        "operational_readiness_criteria": "SRE deployment runbooks published and on-call alerting configured in PagerDuty.",
        "security_readiness_criteria": "Zero high/critical security findings in SonarQube and Trivy scans.",
        "data_readiness_criteria": "Database seeding script populating Karnataka health facility hierarchy.",
        "training_readiness_criteria": "DevOps enablement guide and developer setup SOP published.",
        "support_readiness_criteria": "Internal engineering ticket queue active in Jira Service Desk.",
        "documentation_readiness_criteria": "OpenAPI 3.1 schema published and architecture diagrams verified.",
        "stakeholder_approval_requirements": "CTO, Lead Architect, and BBMP IT Director sign-off."
    },
    {
        "id": "RELEASE-01",
        "version": "v0.2.0-beta",
        "name": "Core Patient Registration, Queue Management & Digital Consent",
        "theme": "Frontline Patient Intake & Queue Orchestration",
        "objective": "Deliver citizen intake workflows: demographic registration, ABHA M1 verification, repeat patient search, bilingual digital consent, and real-time station queue management.",
        "business_value": "Reduces outpatient wait times by 40%, enforces DPDP Act 2023 patient consent capture, and links citizen records across municipal visits via ABHA.",
        "scope": "Patient registration form, ABHA M1 integration, phonetic search algorithms, repeat visit record linkage, DPDP-compliant consent logging, digital token generation, and multi-display queue boards.",
        "included_capabilities": [
            "Citizen demographic intake with bilingual Kannada and English interface",
            "ABHA M1 address resolution, OTP verification, and QR card scanning",
            "Sub-second patient search using Metaphone and fuzzy string matching",
            "Cryptographic digital consent capture with explicit purpose limitation",
            "Automated token generator routing citizens to triage and consultation rooms",
            "Real-time WebSocket queue display board for clinic waiting halls"
        ],
        "excluded_capabilities": [
            "Doctor clinical SOAP notes and diagnosis entry (deferred to RELEASE-02)",
            "Laboratory diagnostic order execution (deferred to RELEASE-03)",
            "ClickHouse population analytics (deferred to RELEASE-04)"
        ],
        "entry_criteria": "RELEASE-00 Foundation certified and active in staging environment.",
        "exit_criteria": "1,000 synthetic patient registrations executed with sub-250ms p95 search latency and 100% consent audit trail logging.",
        "release_readiness_criteria": "Pilot registration desks equipped with barcode scanners and receipt printers.",
        "dependencies": ["DEPENDENCY-005", "DEPENDENCY-006", "DEPENDENCY-007", "DEPENDENCY-008"],
        "predecessor_release": "RELEASE-00",
        "successor_release": "RELEASE-02",
        "related_sprints": ["SPRINT-03", "SPRINT-04", "SPRINT-05"],
        "related_epics": ["EPIC-006", "EPIC-007", "EPIC-008", "EPIC-009", "EPIC-010"],
        "related_features": [f"FEATURE-{i:03d}" for i in range(21, 51)],
        "related_requirements": ["FR-005", "FR-006", "FR-007", "FR-008", "PRIV-001", "PRIV-002"],
        "related_workflows": ["WF-003", "WF-004", "WF-005", "WF-006"],
        "related_architecture_components": ["Patient Intake Service", "Queue Engine", "ABHA Gateway Adapter", "Consent Store", "WebSocket Hub"],
        "related_database_entities": [f"TABLE-{i:03d}" for i in range(11, 21)],
        "related_api_families": ["Patient Registration API", "Search API", "Consent API", "Queue Management API"],
        "related_frontend_modules": ["Registration Counter Workbench", "Queue Display Board", "Consent Modal"],
        "related_security_controls": ["DPDP consent ledger", "AES-256 field-level PII encryption", "RBAC reception desk role limits"],
        "related_qa_strategy": "Playwright automated browser tests covering Kannada and English registration journeys.",
        "related_devops_controls": "WebSocket horizontal scaling via Redis pub/sub backplane in staging cluster.",
        "related_analytics_capabilities": "Hourly clinic footfall counters and queue wait-time metrics.",
        "related_ai_capabilities": "None in intake tier.",
        "related_integrations": ["ABHA Sandbox Gateway", "CDAC SMS OTP Gateway"],
        "milestones": ["MILESTONE-003", "MILESTONE-004"],
        "risks": ["RISK-004", "RISK-005", "RISK-006"],
        "blockers": ["BLOCKER-003", "BLOCKER-004"],
        "assumptions": ["ASSUMPTION-003", "ASSUMPTION-004"],
        "constraints": ["DPDP Act 2023 Consent Mandates", "Bilingual Kannada UI Mandate"],
        "quality_gates": ["QUALITY-GATE-004", "QUALITY-GATE-005", "QUALITY-GATE-006"],
        "acceptance_criteria": "Frontline registration clerk completes citizen intake, ABHA verification, and token printing in under 90 seconds.",
        "rollback_criteria": "Canary deployment rollback if token generation error rate exceeds 1% during staging verification.",
        "go_no_go_criteria": "Sign-off by Product Owner, Frontline Registration Lead, and Security Officer.",
        "operational_readiness_criteria": "Registration desk operational manuals published in Kannada and English.",
        "security_readiness_criteria": "Zero plain-text Aadhaar or PII numbers stored in database tables or logs.",
        "data_readiness_criteria": "Pre-loaded municipal pin code directory and BBMP ward boundaries.",
        "training_readiness_criteria": "Training video module for clinic registration staff recorded and distributed.",
        "support_readiness_criteria": "Tier-1 helpdesk trained on token printer and scanner troubleshooting.",
        "documentation_readiness_criteria": "Patient intake API user guide published to internal portal.",
        "stakeholder_approval_requirements": "BBMP Chief Health Officer and Lead Product Manager sign-off."
    },
    {
        "id": "RELEASE-02",
        "version": "v0.3.0-beta",
        "name": "Clinical Outpatient Consultation, Triage & Electronic Prescribing",
        "theme": "Doctor Clinical Workbench & Diagnostic Decision Support",
        "objective": "Deliver comprehensive clinical consultation workflows: nurse triage vitals, danger sign alerts, doctor consultation workbench, ICD-10/SNOMED CT diagnosis coding, and STG-validated e-prescribing.",
        "business_value": "Eliminates illegible paper prescriptions, enforces Standard Treatment Guidelines (STGs), prevents adverse drug interactions, and preserves physician clinical primacy.",
        "scope": "Nurse triage module, vital signs capture, pediatric and maternal danger alerts, clinical SOAP note editor, diagnosis taxonomy search, STG dosage validator, drug-allergy checker, and digital e-prescription signing.",
        "included_capabilities": [
            "Nurse triage workbench recording temperature, pulse, blood pressure, SpO2, and BMI",
            "Real-time visual alerts for hypertensive crisis, severe anemia, and pediatric respiratory distress",
            "Physician clinical consultation console with past medical history timeline",
            "Sub-second search across 12,000+ ICD-10 and SNOMED CT clinical terms",
            "Electronic prescription generator validating drug dosage, route, frequency, and duration",
            "Advisory drug-drug and drug-allergy interaction checking with physician override controls"
        ],
        "excluded_capabilities": [
            "Autonomous prescribing or diagnostic algorithms (strictly prohibited)",
            "Automated pharmacy stock dispensing (deferred to RELEASE-03)",
            "Zonal referral booking (deferred to RELEASE-03)"
        ],
        "entry_criteria": "RELEASE-01 Core Patient verified in staging with verified patient token routing.",
        "exit_criteria": "500 complete clinical encounters simulated with zero drug safety validation failures and sub-200ms diagnosis lookup.",
        "release_readiness_criteria": "Doctor consultation workstations configured with verified STG drug formularies.",
        "dependencies": ["DEPENDENCY-009", "DEPENDENCY-010", "DEPENDENCY-011", "DEPENDENCY-012"],
        "predecessor_release": "RELEASE-01",
        "successor_release": "RELEASE-03",
        "related_sprints": ["SPRINT-06", "SPRINT-07", "SPRINT-08"],
        "related_epics": ["EPIC-011", "EPIC-012", "EPIC-013", "EPIC-014", "EPIC-015"],
        "related_features": [f"FEATURE-{i:03d}" for i in range(51, 86)],
        "related_requirements": ["FR-009", "FR-010", "FR-011", "FR-012", "CR-001", "CR-002"],
        "related_workflows": ["WF-007", "WF-008", "WF-009", "WF-010", "WF-011"],
        "related_architecture_components": ["Triage Service", "Clinical SOAP Engine", "STG Knowledge Base", "Prescription Generator", "Audit Signer"],
        "related_database_entities": [f"TABLE-{i:03d}" for i in range(21, 31)],
        "related_api_families": ["Triage API", "Clinical Notes API", "Diagnosis API", "Prescription API"],
        "related_frontend_modules": ["Nurse Triage Console", "Doctor Consultation Workbench", "e-Rx Generator"],
        "related_security_controls": ["Cryptographic doctor signature", "Role-based prescription signing authority", "Audit logging of diagnostic overrides"],
        "related_qa_strategy": "Automated clinical boundary testing verifying STG dosage ceiling assertions and danger sign alerts.",
        "related_devops_controls": "Redis caching of SNOMED CT and ICD-10 terminologies for sub-50ms lookup.",
        "related_analytics_capabilities": "Disease surveillance telemetry capturing top clinical syndromes per ward.",
        "related_ai_capabilities": "Rule-based STG validation and advisory clinical decision support.",
        "related_integrations": ["Standard Treatment Guidelines Service", "NIC e-Hospital Coding Service"],
        "milestones": ["MILESTONE-005", "MILESTONE-006"],
        "risks": ["RISK-007", "RISK-008", "RISK-009"],
        "blockers": ["BLOCKER-005", "BLOCKER-006"],
        "assumptions": ["ASSUMPTION-005", "ASSUMPTION-006"],
        "constraints": ["Physician Primacy Mandate", "Clinical Safety Formularies"],
        "quality_gates": ["QUALITY-GATE-007", "QUALITY-GATE-008", "QUALITY-GATE-009"],
        "acceptance_criteria": "Medical Officer can complete triage review, physical exam, diagnosis coding, and e-prescription in under 3 minutes.",
        "rollback_criteria": "Automatic rollback if prescription generation throws unhandled exceptions during staging load tests.",
        "go_no_go_criteria": "Formal sign-off by BBMP Chief Medical Officer, Lead Clinical SME, and Technical Lead.",
        "operational_readiness_criteria": "Clinical Standard Treatment Guidelines loaded and verified by medical superintendents.",
        "security_readiness_criteria": "Digital signatures verified for all simulated e-prescriptions.",
        "data_readiness_criteria": "WHO Essential Medicines List and Karnataka state formulary populated.",
        "training_readiness_criteria": "Doctor onboarding workshop conducted with 20 pilot medical officers.",
        "support_readiness_criteria": "Dedicated clinical application support hotline established.",
        "documentation_readiness_criteria": "Clinical User Manual published with illustrated prescribing workflows.",
        "stakeholder_approval_requirements": "BBMP Director of Health and Lead Medical Officer sign-off."
    },
    {
        "id": "RELEASE-03",
        "version": "v0.4.0-beta",
        "name": "Pharmacy Dispensing, Point-of-Care Laboratory & Secondary Referrals",
        "theme": "Ancillary Care, Diagnostic Investigations & Referral Continuity",
        "objective": "Deliver ancillary workflows: barcode-driven FEFO pharmacy dispensing, real-time inventory deductions, rapid diagnostic lab order processing, analyzer interfacing, and secondary hospital referral linkages.",
        "business_value": "Eliminates medication stockouts via First-Expiry-First-Out allocation, streamlines rapid diagnostic testing, and connects primary clinics to tertiary secondary hospitals.",
        "scope": "Pharmacy dispensing counter, batch-level FEFO deduction, stockout warning system, POC rapid test ordering, laboratory specimen labeling, result entry, referral letter generation, and NIC eHospital gateway linking.",
        "included_capabilities": [
            "Pharmacist workbench with barcode scanning matching e-prescriptions to physical stock",
            "Automated First-Expiry-First-Out (FEFO) batch allocation preventing expired drug distribution",
            "Point-of-care laboratory diagnostic order entry for 24 rapid tests (Malaria, Dengue, CBC, Glucose)",
            "Diagnostic analyzer result entry with automated abnormal flag highlights",
            "Secondary hospital referral booking transmitting FHIR bundles to NIC eHospital",
            "Automated bilingual SMS notification alerting patients to referral appointments"
        ],
        "excluded_capabilities": [
            "Tertiary hospital inpatient bed management (out of scope)",
            "Automated drug purchasing/procurement ERP (out of scope)",
            "Predictive AI epidemiological syndromic clustering (deferred to RELEASE-07)"
        ],
        "entry_criteria": "RELEASE-02 Clinical Consultation certified and generating valid e-prescriptions in staging.",
        "exit_criteria": "1,000 pharmacy dispensations and 500 lab orders processed with 100% stock reconciliation and zero expired batch issuances.",
        "release_readiness_criteria": "Pilot clinic pharmacy counters equipped with 2D barcode scanners and thermal label printers.",
        "dependencies": ["DEPENDENCY-013", "DEPENDENCY-014", "DEPENDENCY-015", "DEPENDENCY-016"],
        "predecessor_release": "RELEASE-02",
        "successor_release": "RELEASE-04",
        "related_sprints": ["SPRINT-09", "SPRINT-11", "SPRINT-12", "SPRINT-13"],
        "related_epics": ["EPIC-016", "EPIC-017", "EPIC-018", "EPIC-019", "EPIC-020"],
        "related_features": [f"FEATURE-{i:03d}" for i in range(86, 121)],
        "related_requirements": ["FR-013", "FR-014", "FR-015", "FR-016", "INT-001", "INT-002"],
        "related_workflows": ["WF-012", "WF-013", "WF-014", "WF-015", "WF-016"],
        "related_architecture_components": ["Pharmacy Engine", "FEFO Allocator", "Lab Investigation Service", "Referral Gateway", "Notification Worker"],
        "related_database_entities": [f"TABLE-{i:03d}" for i in range(31, 41)],
        "related_api_families": ["Pharmacy API", "Laboratory API", "Referral API", "Inventory API"],
        "related_frontend_modules": ["Pharmacy Dispensing Counter", "Lab Technician Console", "Referral Coordinator View"],
        "related_security_controls": ["Pharmacist double-signature verification", "Audit trail of medication substitution", "Encrypted referral transfer"],
        "related_qa_strategy": "End-to-end integration tests verifying prescription-to-dispensation inventory decrement.",
        "related_devops_controls": "RabbitMQ / BullMQ message queues handling asynchronous referral notifications and SMS dispatch.",
        "related_analytics_capabilities": "Daily drug stock burn rate and antibiotic consumption metrics.",
        "related_ai_capabilities": "None in ancillary execution tier.",
        "related_integrations": ["NIC eHospital Referral Service", "CDAC SMS Gateway", "Laboratory Analyzer RS-232 Bridge"],
        "milestones": ["MILESTONE-007", "MILESTONE-008"],
        "risks": ["RISK-010", "RISK-011", "RISK-012"],
        "blockers": ["BLOCKER-007", "BLOCKER-008"],
        "assumptions": ["ASSUMPTION-007", "ASSUMPTION-008"],
        "constraints": ["Drugs and Cosmetics Act Compliance", "FEFO Inventory Strictness"],
        "quality_gates": ["QUALITY-GATE-010", "QUALITY-GATE-011", "QUALITY-GATE-012"],
        "acceptance_criteria": "Pharmacist dispenses verified e-prescription and deducts batch stock in under 45 seconds with zero discrepancy.",
        "rollback_criteria": "Automated rollback if inventory concurrency locks cause transaction deadlocks during load testing.",
        "go_no_go_criteria": "Sign-off by Chief Pharmacist, Head of Laboratory Services, and Lead Architect.",
        "operational_readiness_criteria": "Pilot clinic drug stock physically audited and initial batch inventory seeded.",
        "security_readiness_criteria": "Secure token authentication active between clinic gateway and NIC eHospital.",
        "data_readiness_criteria": "Comprehensive laboratory test catalog (24 tests) and reference ranges verified.",
        "training_readiness_criteria": "Pharmacist and lab technician training sessions completed across 20 pilot clinics.",
        "support_readiness_criteria": "Dedicated inventory and lab hardware support queue operational.",
        "documentation_readiness_criteria": "Pharmacy SOP and Lab Analyzer Integration Guide published.",
        "stakeholder_approval_requirements": "BBMP Health Officer and Drug Control Authority representative sign-off."
    },
    {
        "id": "RELEASE-04",
        "version": "v0.5.0-beta",
        "name": "Population Health Analytics, Edge Resilience & Offline PWA Sync",
        "theme": "Offline Edge Continuity & Municipal Lakehouse Analytics",
        "objective": "Deliver municipal public health intelligence and offline edge resilience: local SQLite replica caching, background conflict reconciliation, ClickHouse OLAP lakehouse, and statutory health surveillance reporting.",
        "business_value": "Guarantees 100% uninterrupted clinic operations during 72-hour broadband blackouts and provides municipal leadership with real-time epidemiological dashboards.",
        "scope": "Service worker caching, client-side SQLite database, mutation queue replication, bi-directional Last-Write-Wins conflict resolution, Debezium CDC pipeline, ClickHouse analytical marts, and Superset public health dashboards.",
        "included_capabilities": [
            "Autonomous offline clinic operation supporting continuous patient registration, consultation, and dispensing",
            "Cryptographic mutation queue staging offline transactions with local UUID indexing",
            "Automatic background synchronization over WebSockets upon network reconnection",
            "Deterministic conflict resolution prioritizing physician clinical records over administrative changes",
            "ClickHouse OLAP lakehouse ingesting real-time CDC events from municipal PostgreSQL instances",
            "Statutory automated export feeds for Integrated Health Information Platform (IHIP) and RCH"
        ],
        "excluded_capabilities": [
            "Predictive AI syndromic outbreak classification (deferred to RELEASE-07)",
            "Third-party commercial insurance billing (out of scope)"
        ],
        "entry_criteria": "RELEASE-03 Pharmacy and Laboratory workflows verified and active in staging.",
        "exit_criteria": "72-hour simulated broadband disconnection executed with 10,000 offline transactions reconciled with zero data loss and sub-second sync.",
        "release_readiness_criteria": "Pilot clinic workstations configured with modern Chromium browsers and IndexedDB quotas.",
        "dependencies": ["DEPENDENCY-017", "DEPENDENCY-018", "DEPENDENCY-019", "DEPENDENCY-020"],
        "predecessor_release": "RELEASE-03",
        "successor_release": "RELEASE-05",
        "related_sprints": ["SPRINT-10", "SPRINT-14"],
        "related_epics": ["EPIC-021", "EPIC-022", "EPIC-023", "EPIC-024", "EPIC-025"],
        "related_features": [f"FEATURE-{i:03d}" for i in range(121, 151)],
        "related_requirements": ["FR-017", "FR-018", "FR-019", "FR-020", "OFF-001", "OFF-002", "ANL-001", "ANL-002"],
        "related_workflows": ["WF-017", "WF-018", "WF-021", "WF-022", "WF-023"],
        "related_architecture_components": ["SQLite Edge Cache", "Sync Worker", "Conflict Resolution Engine", "Debezium CDC", "ClickHouse OLAP", "Superset Dashboards"],
        "related_database_entities": [f"TABLE-{i:03d}" for i in range(41, 48)],
        "related_api_families": ["Sync API", "Offline Mutation API", "Analytics Export API", "Surveillance Telemetry API"],
        "related_frontend_modules": ["Offline Status Indicator", "Sync Reconciliation Manager", "Public Health Dashboard"],
        "related_security_controls": ["Encrypted client-side storage (AES-GCM)", "Sync payload HMAC verification", "Anonymized analytical export"],
        "related_qa_strategy": "Chaos testing simulating erratic 2G/3G network flapping and forced browser crashes during offline sync.",
        "related_devops_controls": "ClickHouse cluster deployment with Zookeeper replication and automated S3 backup snapshots.",
        "related_analytics_capabilities": "Real-time ward-level syndromic heatmaps and maternal-child health immunization trackers.",
        "related_ai_capabilities": "None in analytical substrate tier.",
        "related_integrations": ["IHIP State Surveillance Portal", "Reproductive and Child Health (RCH) Portal"],
        "milestones": ["MILESTONE-009", "MILESTONE-010"],
        "risks": ["RISK-013", "RISK-014", "RISK-015"],
        "blockers": ["BLOCKER-009", "BLOCKER-010"],
        "assumptions": ["ASSUMPTION-009", "ASSUMPTION-010"],
        "constraints": ["Autonomous Edge Mandate (72 Hours)", "Statutory IHIP Reporting Formats"],
        "quality_gates": ["QUALITY-GATE-013", "QUALITY-GATE-014", "QUALITY-GATE-015"],
        "acceptance_criteria": "Clinic staff can operate offline for 8 consecutive hours; all offline transactions sync to cloud within 120 seconds of reconnect.",
        "rollback_criteria": "Rollback if data sync conflict engine results in duplicated clinical encounters or lost prescriptions.",
        "go_no_go_criteria": "Sign-off by Lead Systems Architect, Database Administrator, and Municipal Epidemiologist.",
        "operational_readiness_criteria": "Sync monitoring dashboards active in Grafana with alerts on unsynced clinic nodes.",
        "security_readiness_criteria": "Local SQLite encryption keys securely managed via browser Web Cryptography API.",
        "data_readiness_criteria": "ClickHouse star schema fact and dimension tables verified with synthetic benchmark data.",
        "training_readiness_criteria": "Offline mode operational protocol taught to pilot clinic administrators.",
        "support_readiness_criteria": "Tier-2 SRE escalation path established for edge database corruption triage.",
        "documentation_readiness_criteria": "Offline-First Resilience and Sync Conflict Resolution Runbook published.",
        "stakeholder_approval_requirements": "BBMP Health Commissioner and Municipal Surveillance Officer sign-off."
    },
    {
        "id": "RELEASE-05",
        "version": "v1.0.0-rc1",
        "name": "20-Clinic Field Pilot Operations, Clinical Validation & UAT",
        "theme": "Field Pilot Operations & Clinical Acceptance",
        "objective": "Deploy and operate the integrated Namma Clinic Digital Health Platform across 20 representative municipal health centers in Bengaluru, executing full operational validation, hypercare support, and UAT sign-off.",
        "business_value": "Validates real-world clinical usability, proves system resilience under municipal infrastructure constraints, and secures empirical clinical sign-off before citywide rollout.",
        "scope": "20 pilot clinic deployments, physical workstation inspections, network stability audits, staff credential issuance, on-site shadow operation, live outpatient operation, hypercare war room, incident triage, and pilot acceptance audit.",
        "included_capabilities": [
            "Live end-to-end operation across 20 physical Namma Clinics covering South, East, and West zones",
            "Comprehensive physical workstation hardware audit (desktop PCs, thermal printers, barcode scanners)",
            "Dedicated on-site floor support engineers at every pilot clinic during Week 1 of live operations",
            "Real-time centralized pilot operations command center dashboard in BBMP Health Directorate",
            "Automated daily operational reconciliation between physical token registers and electronic encounters",
            "Formal clinical User Acceptance Testing (UAT) sign-off by 20 Medical Officers and BBMP CMOs"
        ],
        "excluded_capabilities": [
            "Full citywide 450+ clinic deployment (scheduled for RELEASE-06)",
            "External third-party laboratory API integrations (deferred to post-pilot)"
        ],
        "entry_criteria": "RELEASE-01 through RELEASE-04 fully certified in staging; pilot clinic hardware and fiber connectivity verified.",
        "exit_criteria": "20 pilot clinics operate live for 14 consecutive business days with >= 99.5% uptime, zero critical clinical safety defects, and UAT ratification.",
        "release_readiness_criteria": "Clinic staff 100% trained and certified; hypercare command center operational 24/7.",
        "dependencies": ["DEPENDENCY-021", "DEPENDENCY-022", "DEPENDENCY-023", "DEPENDENCY-024"],
        "predecessor_release": "RELEASE-04",
        "successor_release": "RELEASE-06",
        "related_sprints": ["SPRINT-17", "SPRINT-18"],
        "related_epics": ["EPIC-026", "EPIC-027", "EPIC-028", "EPIC-029", "EPIC-030"],
        "related_features": [f"FEATURE-{i:03d}" for i in range(151, 181)],
        "related_requirements": ["OR-001", "OR-002", "OR-003", "PERF-001", "AVAIL-001"],
        "related_workflows": ["WF-019", "WF-024", "WF-025"],
        "related_architecture_components": ["Pilot Command Center", "Hypercare Telemetry Sinks", "Remote Management Agent", "Staging/Pilot Cluster"],
        "related_database_entities": [f"TABLE-{i:03d}" for i in range(48, 53)],
        "related_api_families": ["Pilot Telemetry API", "Incident Reporting API", "Clinic Status API"],
        "related_frontend_modules": ["Pilot Command Dashboard", "Incident Feedback Widget", "Clinic Readiness Audit View"],
        "related_security_controls": ["Pilot user role provisioning", "Encrypted audit logging", "Zero-trust network access per clinic"],
        "related_qa_strategy": "Field acceptance testing, live shadow logging comparison, and real-time defect triage.",
        "related_devops_controls": "Automated blue/green deployment to pilot cluster with 1-click rollback capability.",
        "related_analytics_capabilities": "Live patient throughput monitoring and clinic utilization dashboards.",
        "related_ai_capabilities": "None in pilot operational validation tier.",
        "related_integrations": ["Local Pilot Hardware Drivers (WebHID/WebUSB)", "CDAC SMS Pilot Sandbox"],
        "milestones": ["MILESTONE-011", "MILESTONE-012"],
        "risks": ["RISK-016", "RISK-017", "RISK-018"],
        "blockers": ["BLOCKER-011", "BLOCKER-012"],
        "assumptions": ["ASSUMPTION-011", "ASSUMPTION-012"],
        "constraints": ["Physical Clinic Infrastructure Variance", "Frontline Staff Shift Schedules"],
        "quality_gates": ["QUALITY-GATE-016", "QUALITY-GATE-017", "QUALITY-GATE-018"],
        "acceptance_criteria": "20 clinics record > 15,000 successful live patient encounters with > 90% staff satisfaction and zero data loss.",
        "rollback_criteria": "Immediate rollback to parallel paper registers if critical data corruption occurs in > 2 clinics.",
        "go_no_go_criteria": "Formal unanimous go-decision by BBMP Health Commissioner, Chief Medical Officer, and Program Director.",
        "operational_readiness_criteria": "20 clinics stocked with printed quick-reference troubleshooting guides and on-site support engineers.",
        "security_readiness_criteria": "Physical security audit of clinic workstations and smart card reader credentials completed.",
        "data_readiness_criteria": "Pilot clinic master records and staff user accounts verified in production database.",
        "training_readiness_criteria": "100% of pilot clinic doctors, nurses, and pharmacists pass practical certification assessment.",
        "support_readiness_criteria": "Dedicated Pilot Incident Response Desk operational with < 15-minute response SLA.",
        "documentation_readiness_criteria": "Pilot Operations Runbook and Emergency Operating Procedures ratified.",
        "stakeholder_approval_requirements": "BBMP Health Commissioner, GBA IT Secretary, and Medical Superintendent Committee."
    },
    {
        "id": "RELEASE-06",
        "version": "v1.0.0",
        "name": "Production Scaling & Full Municipal Rollout (450+ Clinics)",
        "theme": "Citywide Multi-Wave Rollout & Production Operations",
        "objective": "Scale the platform across all 450+ Namma Clinics in Greater Bengaluru, deploying in phased geographical waves, enabling horizontal infrastructure auto-scaling, high-availability DR replication, and 24/7 SRE operations.",
        "business_value": "Transforms municipal healthcare delivery for 14 million citizens, establishing unified digital health records and efficient logistics across all municipal primary clinics.",
        "scope": "Citywide multi-wave deployment (Wave 1: 100 Clinics, Wave 2: 150 Clinics, Wave 3: 200+ Clinics), Kubernetes multi-zone autoscaling, multi-master database replication, hot standby DR site, and transition to Business-As-Usual (BAU).",
        "included_capabilities": [
            "Citywide multi-tenant deployment supporting 450+ physical clinics simultaneously",
            "Kubernetes Horizontal Pod Autoscaling (HPA) handling peak morning OPD loads (> 2,500 req/sec)",
            "High-availability PostgreSQL cluster with automated Patroni failover and read replicas",
            "Disaster Recovery (DR) hot standby site in separate cloud region with RPO < 5 mins, RTO < 15 mins",
            "Tier-1, Tier-2, and Tier-3 municipal IT support operational model with SLA ticketing",
            "Comprehensive administrative dashboard for BBMP Zonal Joint Commissioners"
        ],
        "excluded_capabilities": [
            "Third-party private hospital integration (deferred to national health stack phase)",
            "Tertiary specialized surgical scheduling (out of scope)"
        ],
        "entry_criteria": "RELEASE-05 Pilot successfully completed and ratified with formal scale-up authorization.",
        "exit_criteria": "450+ clinics successfully operational with sustained >= 99.9% uptime and sub-250ms p95 latency.",
        "release_readiness_criteria": "Cloud production infrastructure scaled to peak capacity; DR dry-run successfully executed.",
        "dependencies": ["DEPENDENCY-025", "DEPENDENCY-026", "DEPENDENCY-027", "DEPENDENCY-028"],
        "predecessor_release": "RELEASE-05",
        "successor_release": "RELEASE-07",
        "related_sprints": [f"SPRINT-{i:02d}" for i in range(1, 19)],
        "related_epics": [f"EPIC-{i:03d}" for i in range(1, 51)],
        "related_features": [f"FEATURE-{i:03d}" for i in range(1, 181)],
        "related_requirements": [f"FR-{i:03d}" for i in range(1, 41)] + [f"NFR-{i:03d}" for i in range(1, 21)],
        "related_workflows": [f"WF-{i:03d}" for i in range(1, 26)],
        "related_architecture_components": ["Production Kubernetes Cluster", "Patroni PostgreSQL HA", "ClickHouse Production Lakehouse", "SRE Monitoring Stack"],
        "related_database_entities": [f"TABLE-{i:03d}" for i in range(1, 53)],
        "related_api_families": ["All Municipal Platform APIs"],
        "related_frontend_modules": ["All Primary & Administrative Web Workbenches"],
        "related_security_controls": ["WAF rules", "mTLS strict perimeter", "Enterprise HSM key storage", "Continuous automated VAPT"],
        "related_qa_strategy": "Sustained load testing at 150% peak load, chaos monkey resilience testing, and automated smoke testing.",
        "related_devops_controls": "Canary deployments, automated traffic shifting, and multi-region automated database backups.",
        "related_analytics_capabilities": "Citywide real-time municipal health surveillance and drug supply chain optimization.",
        "related_ai_capabilities": "Foundational data preparation for AI models.",
        "related_integrations": ["All Municipal & National Interfaces"],
        "milestones": ["MILESTONE-013", "MILESTONE-014"],
        "risks": ["RISK-019", "RISK-020", "RISK-021"],
        "blockers": ["BLOCKER-013", "BLOCKER-014"],
        "assumptions": ["ASSUMPTION-013", "ASSUMPTION-014"],
        "constraints": ["Municipal SLA Mandates (99.9% Uptime)", "Disaster Recovery RPO/RTO"],
        "quality_gates": ["QUALITY-GATE-019", "QUALITY-GATE-020", "QUALITY-GATE-021"],
        "acceptance_criteria": "All 450+ clinics achieve live digital operations with zero system-wide outages over 30 consecutive days.",
        "rollback_criteria": "Zone-isolated rollback to staging tier if specific zonal network partition causes database deadlock.",
        "go_no_go_criteria": "Cabinet-level sign-off by Greater Bengaluru Authority Steering Committee.",
        "operational_readiness_criteria": "24/7 Network Operations Center (NOC) and Security Operations Center (SOC) fully staffed.",
        "security_readiness_criteria": "Final third-party CERT-In accredited security audit certification obtained.",
        "data_readiness_criteria": "All historical legacy clinic data successfully migrated and verified.",
        "training_readiness_criteria": "Over 2,000 clinic personnel trained and certified across all 8 BBMP zones.",
        "support_readiness_criteria": "Zonal field support teams deployed with motorized transit units for rapid on-site maintenance.",
        "documentation_readiness_criteria": "Complete Enterprise Platform Runbook and Disaster Recovery Manual published.",
        "stakeholder_approval_requirements": "BBMP Chief Commissioner, GBA Chief Executive, and Health Minister of Karnataka."
    },
    {
        "id": "RELEASE-07",
        "version": "v1.1.0",
        "name": "Advisory AI Clinical Decision Support & ABDM National Interoperability",
        "theme": "Advanced Intelligence & National Health Stack Interoperability",
        "objective": "Integrate advisory artificial intelligence models for medicine stock forecasting, fever outbreak detection, and chronic NCD recall, while establishing full national interoperability under ABDM Milestone 2 (HIP) and Milestone 3 (HIU).",
        "business_value": "Prevents citywide medication stockouts via predictive forecasting, detects vector-borne outbreaks 7 days earlier, and enables longitudinal national health record portability.",
        "scope": "Medicine consumption forecasting models, syndromic fever cluster detection algorithms, NCD patient recall prioritization, AI model governance framework, ABDM HIP FHIR health record publisher, and HIU electronic consent consumer.",
        "included_capabilities": [
            "Predictive time-series forecasting of clinic medicine consumption based on seasonal trends",
            "Geospatial syndromic fever outbreak clustering alerting municipal epidemiologists to potential dengue/malaria spikes",
            "Chronic disease (hypertension/diabetes) recall scoring identifying high-risk patients overdue for follow-up",
            "Strict AI Governance Framework enforcing advisory-only recommendations with mandatory doctor approval",
            "ABDM Milestone 2 (Health Information Provider) publishing FHIR R4 bundles to Ayushman Bharat Digital Mission",
            "ABDM Milestone 3 (Health Information User) requesting and viewing longitudinal external health records with citizen consent"
        ],
        "excluded_capabilities": [
            "Autonomous prescribing or autonomous clinical treatment (strictly forbidden)",
            "Automated clinical decision-making without explicit physician review"
        ],
        "entry_criteria": "RELEASE-06 Production Scaling successfully stabilized with >= 6 months of longitudinal encounter data.",
        "exit_criteria": "AI models achieve > 95% forecasting accuracy and > 98% specificity; ABDM M2/M3 pass 100% NHA compliance testbed suites.",
        "release_readiness_criteria": "AI ethics and clinical safety sign-off obtained from BBMP Medical Ethics Board.",
        "dependencies": ["DEPENDENCY-029", "DEPENDENCY-030", "DEPENDENCY-031", "DEPENDENCY-032"],
        "predecessor_release": "RELEASE-06",
        "successor_release": None,
        "related_sprints": ["SPRINT-15", "SPRINT-16"],
        "related_epics": [f"EPIC-{i:03d}" for i in range(41, 51)],
        "related_features": [f"FEATURE-{i:03d}" for i in range(161, 181)],
        "related_requirements": ["AIR-001", "AIR-002", "AIR-003", "INT-003", "INT-004"],
        "related_workflows": ["WF-021", "WF-024"],
        "related_architecture_components": ["AI Inference Engine", "Model Registry", "Feature Store", "ABDM Gateway Bridge", "FHIR R4 Transformer"],
        "related_database_entities": [f"TABLE-{i:03d}" for i in range(45, 53)],
        "related_api_families": ["AI Inference API", "ABDM M2 Publisher API", "ABDM M3 Consumer API"],
        "related_frontend_modules": ["AI Advisory Drawer", "Outbreak Alert Dashboard", "ABDM External Records Viewer"],
        "related_security_controls": ["Model drift detection", "Zero training on plain-text PII", "ECDH-encrypted ABDM transfer"],
        "related_qa_strategy": "Clinical algorithmic validation against historical ground truth and NHA sandbox automated compliance suites.",
        "related_devops_controls": "MLflow model versioning, automated canary model deployment, and latency circuit breakers (< 50ms inference).",
        "related_analytics_capabilities": "Model drift metrics, feature distribution shifts, and syndromic outbreak telemetry.",
        "related_ai_capabilities": "Random Forest stock forecaster, DBSCAN geospatial clusterer, and logistic regression recall prioritizer.",
        "related_integrations": ["NHA ABDM National Health Gateway", "IHIP Outbreak Reporting Bridge"],
        "milestones": ["MILESTONE-015", "MILESTONE-016"],
        "risks": ["RISK-022", "RISK-023", "RISK-024"],
        "blockers": ["BLOCKER-015", "BLOCKER-016"],
        "assumptions": ["ASSUMPTION-015", "ASSUMPTION-016"],
        "constraints": ["Physician Clinical Primacy Mandate", "NHA ABDM Architecture Standards"],
        "quality_gates": ["QUALITY-GATE-022", "QUALITY-GATE-023", "QUALITY-GATE-024"],
        "acceptance_criteria": "AI advisory recommendations provide measurable clinical utility without altering physician workflow latency; ABDM interoperability passes 100% testbed checks.",
        "rollback_criteria": "Instant 1-click feature flag disablement of AI drawers or ABDM connectors without affecting core OPD operations.",
        "go_no_go_criteria": "Sign-off by National Health Authority (NHA) Auditor, BBMP Ethics Board, and Lead AI Scientist.",
        "operational_readiness_criteria": "Clinical AI user guides and explainability references distributed to all medical officers.",
        "security_readiness_criteria": "FHIR bundles validated against ABDM profiles with zero encryption vulnerabilities.",
        "data_readiness_criteria": "Feature store updated with historical baseline clinical telemetry.",
        "training_readiness_criteria": "Doctor clinical workshop on AI advisory interpretation and override rights.",
        "support_readiness_criteria": "AI engineering squad on-call for model drift and gateway timeout alerts.",
        "documentation_readiness_criteria": "AI Model Cards and ABDM Interoperability Architecture Document published.",
        "stakeholder_approval_requirements": "BBMP Health Commissioner, NHA Technical Director, and Chief Medical Officer."
    }
]

SECTION_NAMES_54 = [
    "Document Control",
    "Release Identity",
    "Release Purpose",
    "Business Context",
    "Business Value",
    "Release Objectives",
    "Release Scope",
    "Out-of-Scope",
    "Stakeholder Impact",
    "Persona Impact",
    "Role Impact",
    "Capability Map",
    "Feature Map",
    "Epic Map",
    "Requirement Traceability",
    "Workflow Traceability",
    "Architecture Traceability",
    "Database Traceability",
    "API Traceability",
    "Frontend Traceability",
    "Security Traceability",
    "QA Traceability",
    "DevOps Traceability",
    "Data Traceability",
    "AI Traceability",
    "Integration Traceability",
    "Sprint Mapping",
    "Dependency Mapping",
    "Risk Mapping",
    "Blocker Mapping",
    "Milestone Mapping",
    "Entry Criteria",
    "Exit Criteria",
    "Readiness Criteria",
    "Quality Gates",
    "Security Gates",
    "Data Gates",
    "Operational Gates",
    "Training Gates",
    "Support Gates",
    "Deployment Strategy",
    "Rollback Strategy",
    "Go/No-Go Framework",
    "Acceptance Criteria",
    "Metrics",
    "KPIs",
    "Release Governance",
    "Change Management",
    "Communication Plan",
    "Post-Release Validation",
    "Hypercare",
    "Lessons Learned",
    "Traceability Matrix",
    "Release Completion Checklist"
]
