#!/usr/bin/env python3
"""
domain_specs_d1.py
Domain 1: Core Foundation & Platform Administration
Modules: MODULE-001, MODULE-002, MODULE-003, MODULE-004, MODULE-026.
"""

D1_MODULES = [
    {
        "id": "MODULE-001",
        "code": "MOD-01",
        "domain_id": "DOMAIN-001",
        "name": "Staff Authentication & MFA Engine",
        "purpose": "Provide secure, cryptographically robust user authentication for municipal healthcare staff, enforcing multi-factor challenges and emergency offline scrypt-hashed PIN verification.",
        "business_problem": "Primary clinic workstations operate in high-turnover municipal settings where shared computers and network dropouts lead to password sharing, session hijacking, or lockout during critical clinic hours.",
        "business_outcome": "Zero unauthorized system intrusions, 100% auditable staff login events, and uninterrupted login capability during broadband failure via local public key signature verification.",
        "primary_users": ["Medical Officer", "Staff Nurse", "Pharmacist", "Lab Technician", "Registration Clerk"],
        "secondary_users": ["Zonal Health Officer", "System Administrator"],
        "roles": ["ROLE-002", "ROLE-003", "ROLE-004", "ROLE-005", "ROLE-006", "ROLE-030"],
        "submodules": [
            {"id": "SUBMODULE-001", "name": "Primary Credential Authentication", "desc": "Handles username, salted Argon2id/scrypt passwords, and session credential validation."},
            {"id": "SUBMODULE-002", "name": "Multi-Factor Verification", "desc": "Enforces TOTP authenticator app and SMS one-time passcode challenges."},
            {"id": "SUBMODULE-003", "name": "Offline Cryptographic PIN Fallback", "desc": "Validates cached local PINs using edge server secure enclaves during broadband severing."}
        ],
        "capabilities": [
            {"id": "CAPABILITY-001", "submodule_id": "SUBMODULE-001", "name": "Credential Verification", "desc": "Verifies staff credentials against central directory with rate-limiting."},
            {"id": "CAPABILITY-002", "submodule_id": "SUBMODULE-001", "name": "Session Token Minting", "desc": "Mints cryptographically signed JWT bearer tokens with 15-minute expiry."},
            {"id": "CAPABILITY-003", "submodule_id": "SUBMODULE-002", "name": "MFA Challenge Dispatch", "desc": "Generates and validates TOTP / SMS verification codes."},
            {"id": "CAPABILITY-004", "submodule_id": "SUBMODULE-002", "name": "Biometric Authentication Bridge", "desc": "Interfaces with Aadhaar/HPR biometric scanners for clinical staff verification."},
            {"id": "CAPABILITY-005", "submodule_id": "SUBMODULE-003", "name": "Local PIN Verification", "desc": "Authenticates personnel locally against edge-cached scrypt hashes."},
            {"id": "CAPABILITY-006", "submodule_id": "SUBMODULE-003", "name": "Session Inactivity Lockout", "desc": "Locks display screen after 15 minutes of inactivity with instant PIN unlock."}
        ],
        "requirements": ["BR-003", "FR-002", "NFR-002", "BRULE-002", "CR-002", "OR-002", "SECR-002", "PRIV-002", "PERF-002", "AVAIL-002", "OFF-002"],
        "workflows": ["WF-001", "WF-002"],
        "data_entities": ["StaffUser", "SessionToken", "AuthAuditRecord", "OfflinePinCache"],
        "planned_apis": ["PLANNED-API-001", "PLANNED-API-002"],
        "planned_ui": ["PLANNED-UI-001"],
        "integrations": ["HPR Gateway", "SMS Gateway", "Local Edge Vault"],
        "security_concerns": "Brute-force password guessing, credential stuffing, replay attacks, offline PIN tampering.",
        "privacy_concerns": "Staff biometric template protection, audit log pseudonymization.",
        "offline_behavior": "Switches to local edge cache within 500ms; validates cached scrypt PINs without cloud roundtrip.",
        "reporting_impact": "Emits login success/failure metrics to facility operations reports.",
        "analytics_impact": "Tracks staff shift start/end times and station occupancy.",
        "ai_impact": "Monitors anomalous login geolocations and concurrent active sessions.",
        "operational_impact": "Guarantees staff can unlock clinic workstations by 07:30 AM regardless of WAN status.",
        "failure_boundaries": "Edge server PIN cache acts as circuit-breaker if municipal cloud auth gateway times out.",
        "ownership": "Platform Security Engineering Team",
        "lifecycle_status": "Approved Baseline",
        "mvp_status": "CORE MVP",
        "release_target": "REL-00",
        "priority": "P0 - Critical",
        "dependencies": [],
        "risks": ["Municipal fiber cut during shift start", "Staff forgetting offline PINs"],
        "success_metrics": ["Authentication latency < 250ms (p95)", "Offline fallback transition < 500ms"],
        "kpis": ["100% login availability", "Zero unauthorized credential access breaches"],
        "acceptance_boundaries": "Must support up to 50 concurrent staff logins per facility edge node without degradation.",
        "out_of_scope": "Citizen patient portal login (handled in citizen mobile app)."
    },
    {
        "id": "MODULE-002",
        "code": "MOD-02",
        "domain_id": "DOMAIN-001",
        "name": "Role-Based Access Control (RBAC) & Entitlements",
        "purpose": "Enforce strict principle-of-least-privilege authorization boundaries, role hierarchies, and separation-of-duties across clinical, administrative, and pharmacy domains.",
        "business_problem": "Uncontrolled access privileges allow non-clinical staff to view sensitive patient diagnoses, unauthorized personnel to dispense narcotics, or clerks to alter medical notes.",
        "business_outcome": "100% compliance with DPDP Act 2023 access boundaries, preventing unauthorized data disclosure and clinical record tampering.",
        "primary_users": ["System Administrator", "Medical Officer", "Clinic Coordinator"],
        "secondary_users": ["All Clinic Staff"],
        "roles": ["ROLE-001", "ROLE-002", "ROLE-003", "ROLE-030"],
        "submodules": [
            {"id": "SUBMODULE-004", "name": "Role Hierarchy & Permissions Engine", "desc": "Maintains RBAC permission matrix and action-level authorization checks."},
            {"id": "SUBMODULE-005", "name": "Separation-of-Duties (SoD) Enforcer", "desc": "Blocks conflicting permissions such as prescribing and dispensing by the same user."},
            {"id": "SUBMODULE-006", "name": "Emergency Break-Glass Override", "desc": "Allows temporary emergency privilege elevation with mandatory peer audit logging."}
        ],
        "capabilities": [
            {"id": "CAPABILITY-007", "submodule_id": "SUBMODULE-004", "name": "Permission Evaluation", "desc": "Evaluates user permission claims against resource endpoint in < 15ms."},
            {"id": "CAPABILITY-008", "submodule_id": "SUBMODULE-004", "name": "Dynamic Role Assignment", "desc": "Assigns facility-scoped roles based on active administrative shift rosters."},
            {"id": "CAPABILITY-009", "submodule_id": "SUBMODULE-005", "name": "Conflict-of-Interest Prevention", "desc": "Prevents pharmacist from modifying prescriptions and doctors from dispensing."},
            {"id": "CAPABILITY-010", "submodule_id": "SUBMODULE-005", "name": "Maker-Checker Authorization", "desc": "Requires supervisory approval for financial waivers or controlled drug adjustments."},
            {"id": "CAPABILITY-011", "submodule_id": "SUBMODULE-006", "name": "Break-Glass Privilege Elevation", "desc": "Grants emergency access during cardiac arrest / trauma with alarm sound."},
            {"id": "CAPABILITY-012", "submodule_id": "SUBMODULE-006", "name": "Privilege Elevation Audit", "desc": "Dispatches high-priority alert to ZHO when break-glass is triggered."}
        ],
        "requirements": ["BR-003", "FR-002", "NFR-002", "SECR-002", "PRIV-002", "OR-002", "CR-002"],
        "workflows": ["WF-001", "WF-002", "WF-025"],
        "data_entities": ["RoleRecord", "PermissionClaim", "SoDRule", "BreakGlassAudit"],
        "planned_apis": ["PLANNED-API-003", "PLANNED-API-004"],
        "planned_ui": ["PLANNED-UI-002"],
        "integrations": ["Central Identity Provider", "WORM Audit Ledger"],
        "security_concerns": "Privilege escalation, unauthorized role assignment, abuse of break-glass override.",
        "privacy_concerns": "Unintended exposure of psychiatric, HIV, or reproductive health notes.",
        "offline_behavior": "Cached role permissions verified entirely against local SQLite policy cache.",
        "reporting_impact": "Quarterly RBAC compliance report for BBMP Information Security Officer.",
        "analytics_impact": "Audits frequency of administrative privilege usage.",
        "ai_impact": "Anomaly detection on atypical record access patterns.",
        "operational_impact": "Guarantees staff see only tools relevant to their station.",
        "failure_boundaries": "Fails safe: unresolvable role claim defaults to access denied.",
        "ownership": "Platform Security Engineering Team",
        "lifecycle_status": "Approved Baseline",
        "mvp_status": "CORE MVP",
        "release_target": "REL-00",
        "priority": "P0 - Critical",
        "dependencies": ["MODULE-001"],
        "risks": ["Overly restrictive permissions hindering urgent clinical care"],
        "success_metrics": ["Permission check latency < 15ms (p99)", "Zero privilege boundary leaks"],
        "kpis": ["100% compliance with DPDP data access mandates"],
        "acceptance_boundaries": "Must enforce all 30 project roles and prevent cross-role privilege leakage.",
        "out_of_scope": "Citizen identity authorization (handled via OTP consent)."
    },
    {
        "id": "MODULE-003",
        "code": "MOD-03",
        "domain_id": "DOMAIN-001",
        "name": "Healthcare Facility & Organizational Hierarchy",
        "purpose": "Manage municipal health facility metadata, master administrative zones (8 BBMP Zones), wards (198 Wards), room allocations, and clinic operating schedules.",
        "business_problem": "Lack of standardized facility hierarchy prevents accurate multi-facility data aggregation, zonal resource allocation, and patient catchment area mapping.",
        "business_outcome": "Standardized geographic and organizational hierarchy linking all 183 primary Namma Clinics to BBMP zonal and state health directories.",
        "primary_users": ["System Administrator", "Zonal Health Officer", "Chief Health Officer"],
        "secondary_users": ["Clinic Coordinator", "Medical Officer"],
        "roles": ["ROLE-001", "ROLE-002", "ROLE-030"],
        "submodules": [
            {"id": "SUBMODULE-007", "name": "Geographic & Municipal Hierarchy", "desc": "Manages City -> Zone -> Ward -> Facility geospatial and organizational trees."},
            {"id": "SUBMODULE-008", "name": "Facility Physical Layout & Rooms", "desc": "Configures consultation cubicles, triage desks, pharmacy counters, and labs."},
            {"id": "SUBMODULE-009", "name": "Clinic Operating Calendars & Shifts", "desc": "Maintains working hours (08:00 - 20:00), holiday calendars, and shift rosters."}
        ],
        "capabilities": [
            {"id": "CAPABILITY-013", "submodule_id": "SUBMODULE-007", "name": "Hierarchy Node Management", "desc": "Creates and maintains zonal and ward administrative health nodes."},
            {"id": "CAPABILITY-014", "submodule_id": "SUBMODULE-007", "name": "NIN / HFR Registry Linking", "desc": "Links local clinic ID to National Identification Number (NIN) and Health Facility Registry (HFR)."},
            {"id": "CAPABILITY-015", "submodule_id": "SUBMODULE-008", "name": "Station Terminal Mapping", "desc": "Maps physical terminal hardware MAC/IPs to specific clinic rooms and functions."},
            {"id": "CAPABILITY-016", "submodule_id": "SUBMODULE-008", "name": "Facility Capacity Configuration", "desc": "Configures waiting hall bench capacity and maximum hourly token velocity."},
            {"id": "CAPABILITY-017", "submodule_id": "SUBMODULE-009", "name": "Operating Hours Enforcement", "desc": "Controls automated morning clinic unlock and evening reconciliation windows."},
            {"id": "CAPABILITY-018", "submodule_id": "SUBMODULE-009", "name": "Special Camp Calendar", "desc": "Schedules weekly NCD screening, immunization, and antenatal care camps."}
        ],
        "requirements": ["BR-001", "FR-001", "NFR-001", "OR-001", "AVAIL-001", "INT-001"],
        "workflows": ["WF-001"],
        "data_entities": ["FacilityRecord", "ZoneWardMapping", "RoomStationConfig", "OperatingCalendar"],
        "planned_apis": ["PLANNED-API-005", "PLANNED-API-006"],
        "planned_ui": ["PLANNED-UI-003"],
        "integrations": ["BBMP Geographic GIS Portal", "National HFR Bridge"],
        "security_concerns": "Unauthorized modification of facility operating hours or room configurations.",
        "privacy_concerns": "Public disclosure of internal clinic phone numbers and staff rosters.",
        "offline_behavior": "Facility configuration baked into local edge node SQLite database during provisioning.",
        "reporting_impact": "Enables ward-level and zonal aggregation across all clinical reports.",
        "analytics_impact": "Powers municipal epidemiological maps by ward and health zone.",
        "ai_impact": "Provides geospatial boundaries for infectious disease cluster detection.",
        "operational_impact": "Eliminates confusion over physical room assignments and hardware mappings.",
        "failure_boundaries": "Static configuration: edge node operates autonomously even if central registry is unreachable.",
        "ownership": "Municipal Operations Architecture Team",
        "lifecycle_status": "Approved Baseline",
        "mvp_status": "CORE MVP",
        "release_target": "REL-00",
        "priority": "P0 - Critical",
        "dependencies": ["MODULE-001", "MODULE-002"],
        "risks": ["Delays in municipal ward reorganization mapping"],
        "success_metrics": ["100% facility coverage across all 8 BBMP zones", "Zero orphan facility records"],
        "kpis": ["Facility metadata sync latency < 1 minute"],
        "acceptance_boundaries": "Must model 183 clinics across 8 zones and 198 BBMP wards.",
        "out_of_scope": "Tertiary hospital internal ward beds (focuses on primary care clinics)."
    },
    {
        "id": "MODULE-004",
        "code": "MOD-04",
        "domain_id": "DOMAIN-001",
        "name": "Clinical & Administrative Staff Directory",
        "purpose": "Maintain authenticated clinical and administrative personnel profiles, professional registration credentials (KMC/KNC), digital signature keys, and shift scheduling.",
        "business_problem": "Staff transfers between clinics and reliance on paper rosters lead to delayed access provisioning, lack of accountability for clinical notes, and inability to verify medical licenses.",
        "business_outcome": "Verified staff registry linked to Karnataka Medical Council (KMC) registrations, ensuring only licensed practitioners sign prescriptions and diagnostic orders.",
        "primary_users": ["Clinic Coordinator", "System Administrator", "Medical Officer"],
        "secondary_users": ["Staff Nurse", "Pharmacist", "Lab Technician"],
        "roles": ["ROLE-002", "ROLE-003", "ROLE-030"],
        "submodules": [
            {"id": "SUBMODULE-010", "name": "Staff Professional Profile Directory", "desc": "Maintains staff bio, qualifications, KMC/KNC registration numbers, and contact details."},
            {"id": "SUBMODULE-011", "name": "Facility Roster & Shift Scheduling", "desc": "Schedules morning and evening shift duties and records biometric muster."},
            {"id": "SUBMODULE-012", "name": "Digital Signature & Key Registry", "desc": "Manages DSC / e-Sign public certificates for prescription and lab signoff."}
        ],
        "capabilities": [
            {"id": "CAPABILITY-019", "submodule_id": "SUBMODULE-010", "name": "Staff Onboarding & KYC", "desc": "Onboards clinic personnel with identity verification and license checks."},
            {"id": "CAPABILITY-020", "submodule_id": "SUBMODULE-010", "name": "Professional License Verification", "desc": "Cross-verifies KMC/KNC license validity against state councils."},
            {"id": "CAPABILITY-021", "submodule_id": "SUBMODULE-011", "name": "Duty Roster Generation", "desc": "Publishes weekly duty shifts for doctors, nurses, pharmacists, and lab techs."},
            {"id": "CAPABILITY-022", "submodule_id": "SUBMODULE-011", "name": "Biometric Attendance Linking", "desc": "Integrates morning staff muster with daily clinic unlock authorization."},
            {"id": "CAPABILITY-023", "submodule_id": "SUBMODULE-012", "name": "Digital Signature Enrollment", "desc": "Enrolls staff cryptographic e-sign certificates for legal document execution."},
            {"id": "CAPABILITY-024", "submodule_id": "SUBMODULE-012", "name": "Signature Revocation", "desc": "Instantly revokes signing credentials upon staff transfer or resignation."}
        ],
        "requirements": ["BR-003", "FR-002", "NFR-002", "OR-002", "SECR-002", "INT-002"],
        "workflows": ["WF-001", "WF-002"],
        "data_entities": ["StaffProfile", "LicenseRecord", "DutyRoster", "DigitalCertificate"],
        "planned_apis": ["PLANNED-API-007", "PLANNED-API-008"],
        "planned_ui": ["PLANNED-UI-004"],
        "integrations": ["HPR Healthcare Professional Registry", "Karnataka Medical Council API"],
        "security_concerns": "Impersonation of medical officers, forged digital signatures, unauthorized roster editing.",
        "privacy_concerns": "Staff personal phone numbers and home addresses kept confidential.",
        "offline_behavior": "Staff profile and public signature certificates cached locally for offline validation.",
        "reporting_impact": "Generates monthly staff attendance and duty fulfillment reports.",
        "analytics_impact": "Measures doctor-to-patient consultation ratios and staff utilization.",
        "ai_impact": "Optimizes shift scheduling based on historic patient footfall trends.",
        "operational_impact": "Enables seamless relief staff coverage when a doctor is on leave.",
        "failure_boundaries": "Cached active credentials permit shift operation during internet outage.",
        "ownership": "Municipal Health HR & Governance Team",
        "lifecycle_status": "Approved Baseline",
        "mvp_status": "CORE MVP",
        "release_target": "REL-00",
        "priority": "P0 - Critical",
        "dependencies": ["MODULE-001", "MODULE-002", "MODULE-003"],
        "risks": ["Delays in KMC API verification for newly hired doctors"],
        "success_metrics": ["Staff license verification completed in < 24h", "Zero unverified prescribers"],
        "kpis": ["100% compliant e-prescribing with valid medical registration numbers"],
        "acceptance_boundaries": "Must manage up to 2,000 health personnel across Greater Bengaluru.",
        "out_of_scope": "Municipal payroll calculation and pension administration."
    },
    {
        "id": "MODULE-026",
        "code": "MOD-26",
        "domain_id": "DOMAIN-001",
        "name": "Master System Administration & Feature Flagging",
        "purpose": "Provide centralized platform operations management, configuration tuning, tenant isolation, dynamic feature flagging, and system parameter management.",
        "business_problem": "Inability to dynamically enable or disable features across pilot clinics without full code redeployment slows down phased rollouts and increases release risk.",
        "business_outcome": "Dynamic runtime control enabling targeted clinic pilot rollouts, instant circuit-breaker feature disabling, and zero-downtime configuration updates.",
        "primary_users": ["System Administrator", "DevOps Engineer"],
        "secondary_users": ["Lead Technical Authority"],
        "roles": ["ROLE-029", "ROLE-030"],
        "submodules": [
            {"id": "SUBMODULE-013", "name": "Dynamic Feature Flag Management", "desc": "Controls canary feature rollouts by zone, facility tier, or clinic ID."},
            {"id": "SUBMODULE-014", "name": "System Configuration & Thresholds", "desc": "Manages operational thresholds, timeouts, cache TTLs, and queue capacities."},
            {"id": "SUBMODULE-015", "name": "Platform Maintenance & Migration Control", "desc": "Coordinates edge database schema migrations and scheduled maintenance windows."}
        ],
        "capabilities": [
            {"id": "CAPABILITY-025", "submodule_id": "SUBMODULE-013", "name": "Targeted Flag Activation", "desc": "Enables advanced modules (e.g., AI CDS, ABDM M3) for specific pilot clinics."},
            {"id": "CAPABILITY-026", "submodule_id": "SUBMODULE-013", "name": "Emergency Feature Killswitch", "desc": "Instantly disables misbehaving features across the entire municipal fleet in < 10s."},
            {"id": "CAPABILITY-027", "submodule_id": "SUBMODULE-014", "name": "System Parameter Tuning", "desc": "Tunes session timeouts, queue sizes, and sync intervals without service restart."},
            {"id": "CAPABILITY-028", "submodule_id": "SUBMODULE-014", "name": "Edge Configuration Distribution", "desc": "Pushes updated JSON configuration manifests to edge appliances via secure TLS."},
            {"id": "CAPABILITY-029", "submodule_id": "SUBMODULE-015", "name": "Edge Migration Orchestration", "desc": "Triggers automated SQLite schema migrations during night maintenance windows."},
            {"id": "CAPABILITY-030", "submodule_id": "SUBMODULE-015", "name": "Health Probe Monitoring", "desc": "Monitors liveness and readiness probes across all 183 clinic appliances."}
        ],
        "requirements": ["BR-050", "FR-080", "NFR-050", "OR-050", "SECR-050", "AVAIL-040", "PERF-040"],
        "workflows": ["WF-001", "WF-022"],
        "data_entities": ["FeatureFlag", "SystemConfigParameter", "MigrationLog", "EdgeHeartbeat"],
        "planned_apis": ["PLANNED-API-009", "PLANNED-API-010"],
        "planned_ui": ["PLANNED-UI-005"],
        "integrations": ["Prometheus Alertmanager", "Central GitOps Repository"],
        "security_concerns": "Unauthorized parameter alteration that weakens encryption or disables safety checks.",
        "privacy_concerns": "Configuration manifests must never contain secrets or encryption keys in plaintext.",
        "offline_behavior": "Edge appliances persist last-known valid configuration manifest locally.",
        "reporting_impact": "Generates monthly system configuration change audit logs.",
        "analytics_impact": "Correlates feature flag activations with clinical transaction throughput.",
        "ai_impact": "Gates experimental AI decision-support algorithms to authorized study clinics.",
        "operational_impact": "Enables phased, low-risk software deployment across the 183 facilities.",
        "failure_boundaries": "Corrupted configuration manifest triggers automatic rollback to previous version.",
        "ownership": "DevOps & Core Infrastructure Team",
        "lifecycle_status": "Approved Baseline",
        "mvp_status": "CORE MVP",
        "release_target": "REL-00",
        "priority": "P0 - Critical",
        "dependencies": ["MODULE-001", "MODULE-002", "MODULE-003"],
        "risks": ["Misconfigured flag disabling critical patient registration pathway"],
        "success_metrics": ["Flag propagation to all clinics in < 30s", "Zero unexpected service disruption"],
        "kpis": ["99.99% admin portal availability"],
        "acceptance_boundaries": "Must control feature flags independently for 183 clinics across 8 zones.",
        "out_of_scope": "Physical hardware procurement and OS kernel re-flashing."
    }
]
