#!/usr/bin/env python3
"""
domain_specs_d5.py
Domain 5: Care Continuity, Referrals & Community Outreach
Modules: MODULE-017, MODULE-018, MODULE-019, MODULE-028.
"""

D5_MODULES = [
    {
        "id": "MODULE-017",
        "code": "MOD-17",
        "domain_id": "DOMAIN-005",
        "name": "Secondary Referral & 108 Emergency EMS Transit",
        "purpose": "Facilitate structured electronic patient referrals to BBMP secondary general hospitals and tertiary medical colleges, generate SBAR handoff summaries, and integrate with 108 ambulance dispatch.",
        "business_problem": "Patients sent to higher centers with verbal instructions or lost paper slips face duplicate workups, delayed emergency triage, and no visibility on whether the patient reached the referral hospital.",
        "business_outcome": "Structured digital SBAR clinical handoffs, electronic hospital bed inquiry, direct automated 108 ambulance dispatch with CAD integration, and closed-loop referral tracking.",
        "primary_users": ["Medical Officer (Doctor)", "Staff Nurse"],
        "secondary_users": ["Referral Hospital Emergency MO", "108 Ambulance Dispatcher"],
        "roles": ["ROLE-002", "ROLE-003", "ROLE-011"],
        "submodules": [
            {"id": "SUBMODULE-058", "name": "Structured Clinical Referral Authoring", "desc": "Generates standardized SBAR (Situation, Background, Assessment, Recommendation) referral notes."},
            {"id": "SUBMODULE-059", "name": "108 Emergency EMS Dispatch Bridge", "desc": "Dispatches emergency ambulance request with GPS location and clinical acuity score."},
            {"id": "SUBMODULE-060", "name": "Closed-Loop Referral Tracking", "desc": "Tracks referral hospital arrival, admission outcome, and discharge summary reception."}
        ],
        "capabilities": [
            {"id": "CAPABILITY-115", "submodule_id": "SUBMODULE-058", "name": "SBAR Summary Generation", "desc": "Compiles vitals, diagnosis, emergency stabilization drugs given, and reason for transfer into 1-click PDF."},
            {"id": "CAPABILITY-116", "submodule_id": "SUBMODULE-058", "name": "Receiving Hospital Capacity Check", "desc": "Queries real-time bed and specialty availability (e.g. ICU, dialysis, pediatrics) at target facility."},
            {"id": "CAPABILITY-117", "submodule_id": "SUBMODULE-059", "name": "108 Ambulance CAD Integration", "desc": "Sends emergency pickup request to GVK-EMRI 108 Computer Aided Dispatch system."},
            {"id": "CAPABILITY-118", "submodule_id": "SUBMODULE-059", "name": "Ambulance ETA Telemetry", "desc": "Displays live GPS location and estimated arrival time of dispatched 108 ambulance on clinic console."},
            {"id": "CAPABILITY-119", "submodule_id": "SUBMODULE-060", "name": "Referral Handover Verification", "desc": "Receives electronic confirmation when patient is triaged at destination hospital emergency department."},
            {"id": "CAPABILITY-120", "submodule_id": "SUBMODULE-060", "name": "Post-Referral Counter-Referral Push", "desc": "Pulls counter-referral care plan back into primary clinic EMR upon patient discharge."}
        ],
        "requirements": ["BR-017", "FR-016", "NFR-016", "BRULE-016", "CR-016", "OR-016", "INT-016", "OFF-016"],
        "workflows": ["WF-001", "WF-010", "WF-011", "WF-016", "WF-025"],
        "data_entities": ["ReferralOrder", "SBARSummary", "AmbulanceDispatchRecord", "CounterReferralReport"],
        "planned_apis": ["PLANNED-API-039", "PLANNED-API-040"],
        "planned_ui": ["PLANNED-UI-021"],
        "integrations": ["108 GVK-EMRI CAD API", "BBMP Tertiary Hospital Bed Portal", "ABDM Referral Bridge"],
        "security_concerns": "Unauthorized interception of emergency transfer data, spoofed ambulance requests.",
        "privacy_concerns": "Emergency referral records share only necessary clinical data with destination facility.",
        "offline_behavior": "Generates printable SBAR emergency slip locally; dispatches SMS to 108 if cloud link is down.",
        "reporting_impact": "Powers monthly referral rate, indication, and transfer delay reports.",
        "analytics_impact": "Identifies primary clinics with disproportionately high referral volumes.",
        "ai_impact": "Assesses clinical referral appropriateness against standardized municipal care guidelines.",
        "operational_impact": "Saves critical minutes in acute myocardial infarction, stroke, and obstetric emergencies.",
        "failure_boundaries": "Network failure automatically switches to telephony voice dispatch via dedicated 108 hotline.",
        "ownership": "Referral & Emergency Care Product Team",
        "lifecycle_status": "Approved Baseline",
        "mvp_status": "CORE MVP",
        "release_target": "REL-01",
        "priority": "P0 - Critical",
        "dependencies": ["MODULE-001", "MODULE-002", "MODULE-005", "MODULE-009"],
        "risks": ["108 ambulance availability constraints during traffic peak hours"],
        "success_metrics": ["Emergency referral dispatch latency < 60s", "Closed-loop tracking completion >= 85%"],
        "kpis": ["100% emergency referrals accompanied by structured SBAR documentation"],
        "acceptance_boundaries": "Must connect to all 8 BBMP General Hospitals and 108 EMS command center.",
        "out_of_scope": "Inter-state air ambulance and international organ transplant transport."
    },
    {
        "id": "MODULE-018",
        "code": "MOD-18",
        "domain_id": "DOMAIN-005",
        "name": "NCD Longitudinal Follow-Up & Recall Management",
        "purpose": "Drive chronic disease management for hypertension, diabetes, asthma, and tuberculosis, generating scheduled visit recall queues, tracking medication adherence, and alerting ASHA community health workers.",
        "business_problem": "Over 60% of chronic disease patients drop out of follow-up care within 6 months, leading to preventable strokes, renal failure, and diabetic ketoacidosis emergencies.",
        "business_outcome": "Automated recall scheduling (30/60/90 days), automated SMS refill reminders in Kannada, ASHA field tracing worklists, and sustained chronic disease control rates (> 75%).",
        "primary_users": ["Staff Nurse", "Medical Officer (Doctor)", "ASHA Worker"],
        "secondary_users": ["Clinic Coordinator", "Citizen / Patient"],
        "roles": ["ROLE-002", "ROLE-003", "ROLE-008"],
        "submodules": [
            {"id": "SUBMODULE-061", "name": "Chronic Care Plan & Protocol Engine", "desc": "Configures standardized treatment targets (HbA1c < 7.0%, BP < 140/90 mmHg) and recall frequency."},
            {"id": "SUBMODULE-062", "name": "Automated Recall Calendar & Queue", "desc": "Maintains calendar of expected patient revisits and flags overdue dropouts."},
            {"id": "SUBMODULE-063", "name": "ASHA Community Tracing Worklist", "desc": "Generates localized ward-level overdue patient lists for home visits by ASHA workers."}
        ],
        "capabilities": [
            {"id": "CAPABILITY-121", "submodule_id": "SUBMODULE-061", "name": "NCD Target Protocol Tracking", "desc": "Tracks longitudinal systolic/diastolic BP, fasting blood sugar, and HbA1c curves over time."},
            {"id": "CAPABILITY-122", "submodule_id": "SUBMODULE-061", "name": "Medication Possession Ratio (MPR)", "desc": "Calculates patient pharmacy refill adherence score; alerts doctor if MPR < 80%."},
            {"id": "CAPABILITY-123", "submodule_id": "SUBMODULE-062", "name": "Automated 30-Day Refill Scheduling", "desc": "Schedules next follow-up date automatically during consultation based on dispensed drug supply."},
            {"id": "CAPABILITY-124", "submodule_id": "SUBMODULE-062", "name": "Overdue Defaulter Detector", "desc": "Identifies patients who have not returned within 7 days of scheduled refill date."},
            {"id": "CAPABILITY-125", "submodule_id": "SUBMODULE-063", "name": "ASHA Ward Tracing Export", "desc": "Pushes filtered list of defaulters in specific street/slum clusters to ASHA mobile app."},
            {"id": "CAPABILITY-126", "submodule_id": "SUBMODULE-063", "name": "Home Visit Adherence Verification", "desc": "Records outcome of ASHA home visit (patient traced, relocated, deceased, or resumed care)."}
        ],
        "requirements": ["BR-018", "FR-017", "NFR-017", "BRULE-017", "CR-017", "OR-017", "OFF-017", "REP-017"],
        "workflows": ["WF-001", "WF-005", "WF-011", "WF-017", "WF-018"],
        "data_entities": ["NCDCarePlan", "RecallAppointment", "DefaulterRecord", "ASHAHomeVisitLog"],
        "planned_apis": ["PLANNED-API-041", "PLANNED-API-042"],
        "planned_ui": ["PLANNED-UI-022"],
        "integrations": ["National NCD Portal", "State Nikshay TB Portal", "Citizen SMS Gateway"],
        "security_concerns": "Unauthorized disclosure of chronic patient registries to commercial pharmaceutical marketers.",
        "privacy_concerns": "ASHA worker field lists must respect patient dignity and avoid community stigmatization.",
        "offline_behavior": "Local edge server stores facility NCD registry and calculates recall queues offline.",
        "reporting_impact": "Generates monthly National Health Mission NCD screening and control rate indicators.",
        "analytics_impact": "Identifies geographic clusters with low chronic medication adherence.",
        "ai_impact": "Predicts patient dropout risk using historical visit attendance and distance from clinic.",
        "operational_impact": "Shifts clinic posture from passive episodic treatment to proactive longitudinal wellness.",
        "failure_boundaries": "Missed SMS alerts fall back to ASHA physical community follow-up visit.",
        "ownership": "Chronic Disease & Public Health Product Team",
        "lifecycle_status": "Approved Baseline",
        "mvp_status": "MVP-PLUS",
        "release_target": "REL-02",
        "priority": "P1 - High",
        "dependencies": ["MODULE-001", "MODULE-005", "MODULE-009", "MODULE-013"],
        "risks": ["Patients changing mobile numbers frequently, disrupting automated SMS outreach"],
        "success_metrics": ["Hypertension / Diabetes 12-month retention rate >= 70%", "Recall show-up rate >= 65%"],
        "kpis": [">= 75% of registered hypertensive patients achieve controlled blood pressure (< 140/90)"],
        "acceptance_boundaries": "Must manage active longitudinal cohorts of up to 5,000 NCD patients per clinic.",
        "out_of_scope": "Complex organ transplant immunosuppressive therapeutic drug monitoring."
    },
    {
        "id": "MODULE-019",
        "code": "MOD-19",
        "domain_id": "DOMAIN-005",
        "name": "Citizen Multichannel Notifications & Health Reminders",
        "purpose": "Dispatch transactional notifications, queuing status updates, appointment reminders, laboratory result readiness notices, and seasonal public health advisories via SMS and WhatsApp.",
        "business_problem": "Citizens wait unnecessarily in crowded waiting halls, miss follow-up dates, forget medication dosing, and remain unaware of municipal disease outbreaks and vaccination camps.",
        "business_outcome": "Timely, low-cost citizen communication in Kannada and English, reduced clinic waiting hall crowding, improved medication compliance, and rapid public health alert dissemination.",
        "primary_users": ["Citizen / Patient"],
        "secondary_users": ["Clinic Coordinator", "Staff Nurse", "System Administrator"],
        "roles": ["ROLE-006", "ROLE-007", "ROLE-030"],
        "submodules": [
            {"id": "SUBMODULE-064", "name": "Transactional SMS Notification Gateway", "desc": "Sends registration UHID, queue token, and lab completion alerts via DLT-approved templates."},
            {"id": "SUBMODULE-065", "name": "WhatsApp Citizen Health Service", "desc": "Enables interactive chatbot for token status queries, lab report downloads, and clinic location."},
            {"id": "SUBMODULE-066", "name": "Zonal Public Health Broadcast Engine", "desc": "Broadcasts targeted community advisories (e.g. Dengue prevention, vaccination drives)."}
        ],
        "capabilities": [
            {"id": "CAPABILITY-127", "submodule_id": "SUBMODULE-064", "name": "DLT-Compliant Bilingual SMS", "desc": "Dispatches localized transactional SMS via TRAI DLT-approved header `BBMPHC` in < 10s."},
            {"id": "CAPABILITY-128", "submodule_id": "SUBMODULE-064", "name": "Queue Delay Alert", "desc": "Alerts citizen on phone if their token is delayed by > 20 minutes due to an emergency resuscitation."},
            {"id": "CAPABILITY-129", "submodule_id": "SUBMODULE-065", "name": "Lab Report PDF Download via WhatsApp", "desc": "Allows citizen to securely download verified diagnostic report using secure 1-time PIN."},
            {"id": "CAPABILITY-130", "submodule_id": "SUBMODULE-065", "name": "Queue Position Bot", "desc": "Citizen messages token number; receives live waiting count ahead of them in real time."},
            {"id": "CAPABILITY-131", "submodule_id": "SUBMODULE-066", "name": "Targeted Ward Health Advisory", "desc": "Broadcasts monsoon mosquito prevention advice to citizens registered in specific flood-prone wards."},
            {"id": "CAPABILITY-132", "submodule_id": "SUBMODULE-066", "name": "Opt-Out Preference Management", "desc": "Allows citizens to manage notification preferences and opt out of non-critical broadcasts."}
        ],
        "requirements": ["BR-020", "FR-018", "NFR-018", "BRULE-018", "OR-018", "LOC-018", "PRIV-018", "INT-018"],
        "workflows": ["WF-001", "WF-007", "WF-015", "WF-017", "WF-018"],
        "data_entities": ["NotificationLog", "MessageTemplate", "CitizenOptPreference", "BroadcastCampaign"],
        "planned_apis": ["PLANNED-API-043", "PLANNED-API-044"],
        "planned_ui": ["PLANNED-UI-023"],
        "integrations": ["CDAC National Mobile Service Delivery Gateway (MSDG)", "Meta WhatsApp Cloud API"],
        "security_concerns": "Phishing via spoofed SMS headers, transmission of unencrypted clinical diagnosis text.",
        "privacy_concerns": "Strictly prevent SMS transmission of sensitive diagnosis names; use secure token links.",
        "offline_behavior": "Edge node queues outgoing SMS payloads in local SQLite table; dispatches automatically upon sync.",
        "reporting_impact": "Tracks message delivery success rates, bounce rates, and channel latency.",
        "analytics_impact": "Evaluates correlation between appointment reminder delivery and clinic revisit rates.",
        "ai_impact": "Optimizes notification send times based on historical citizen open rates.",
        "operational_impact": "Reduces front-desk inquiries and improves patient retention in public healthcare.",
        "failure_boundaries": "Notification gateway downtime never blocks core clinic registration or clinical care.",
        "ownership": "Citizen Engagement Product Team",
        "lifecycle_status": "Approved Baseline",
        "mvp_status": "CORE MVP",
        "release_target": "REL-01",
        "priority": "P1 - High",
        "dependencies": ["MODULE-001", "MODULE-005", "MODULE-007"],
        "risks": ["Telecom DLT template approval delays for new municipal health advisories"],
        "success_metrics": ["Transactional SMS delivery latency < 10s (p95)", "SMS delivery success rate >= 95%"],
        "kpis": ["Zero transmission of unencrypted clinical health diagnosis via SMS"],
        "acceptance_boundaries": "Must deliver up to 50,000 notifications daily across all BBMP clinics.",
        "out_of_scope": "Commercial third-party advertising and marketing promotional spam."
    },
    {
        "id": "MODULE-028",
        "code": "MOD-28",
        "domain_id": "DOMAIN-005",
        "name": "Facility Operations Helpdesk & Incident Dispatch",
        "purpose": "Provide clinic staff with an integrated operational helpdesk to log edge hardware faults (printer jams, UPS power failure, network cuts), dispatch field technician tickets, and track resolution SLAs.",
        "business_problem": "When clinic hardware fails (e.g. barcode scanner or thermal printer), staff have no ticketing system; calls to vendors are forgotten, causing stations to remain idle for days.",
        "business_outcome": "Integrated 1-click incident logging from any workstation, automatic field engineer dispatch, guaranteed 4-hour hardware repair SLA, and minimum downtime of clinical stations.",
        "primary_users": ["Clinic Coordinator", "Staff Nurse", "Pharmacist"],
        "secondary_users": ["Field IT Support Engineer", "System Administrator"],
        "roles": ["ROLE-002", "ROLE-003", "ROLE-004", "ROLE-028", "ROLE-030"],
        "submodules": [
            {"id": "SUBMODULE-067", "name": "Clinic Incident Ticketing Console", "desc": "Enables staff to log technical faults with 1-click diagnostic dumps and photos."},
            {"id": "SUBMODULE-068", "name": "Automated Technician Dispatch & Routing", "desc": "Routes tickets to zonal mobile field engineers based on geographic proximity."},
            {"id": "SUBMODULE-069", "name": "Hardware Asset Health & SLA Monitor", "desc": "Tracks hardware MTBF, warranty status, replacement inventory, and repair SLAs."}
        ],
        "capabilities": [
            {"id": "CAPABILITY-133", "submodule_id": "SUBMODULE-067", "name": "1-Click Diagnostic Dump", "desc": "Automatically bundles edge appliance system logs, device USB states, and errors into ticket."},
            {"id": "CAPABILITY-134", "submodule_id": "SUBMODULE-067", "name": "Peripheral Self-Test Wizard", "desc": "Guides nurse through guided diagnostic test for thermal printer, scanner, and LAN cable."},
            {"id": "CAPABILITY-135", "submodule_id": "SUBMODULE-068", "name": "Zonal Field Engineer Dispatch", "desc": "Dispatches ticket to assigned zonal technician mobile app with navigation coordinates."},
            {"id": "CAPABILITY-136", "submodule_id": "SUBMODULE-068", "name": "SLA Clock & Breach Escalation", "desc": "Escalates P0 hardware outages (edge server down) to IT Lead if not resolved in 4 hours."},
            {"id": "CAPABILITY-137", "submodule_id": "SUBMODULE-069", "name": "Hardware Asset Lifecycle Tracking", "desc": "Maintains serial numbers, installation dates, and maintenance logs for all facility devices."},
            {"id": "CAPABILITY-138", "submodule_id": "SUBMODULE-069", "name": "Preventive Maintenance Scheduler", "desc": "Schedules quarterly physical cleaning, thermal paste refresh, and battery UPS checks."}
        ],
        "requirements": ["BR-028", "FR-028", "NFR-028", "OR-028", "AVAIL-028", "PERF-028"],
        "workflows": ["WF-001", "WF-022"],
        "data_entities": ["IncidentTicket", "AssetInventoryRecord", "TechnicianDispatchLog", "PreventiveSchedule"],
        "planned_apis": ["PLANNED-API-045", "PLANNED-API-046"],
        "planned_ui": ["PLANNED-UI-024"],
        "integrations": ["Municipal IT Helpdesk Service", "SMS Alert Gateway"],
        "security_concerns": "Unauthorized hardware replacement without asset registration.",
        "privacy_concerns": "Incident dumps automatically scrub all patient personal health information.",
        "offline_behavior": "Logs incident locally; displays emergency phone hotlines if network is completely down.",
        "reporting_impact": "Powers monthly hardware availability, mean time to repair (MTTR), and vendor SLA reports.",
        "analytics_impact": "Identifies recurring failure patterns across specific hardware models or clinic zones.",
        "ai_impact": "Predicts hardware failure based on error log frequency and power voltage spikes.",
        "operational_impact": "Guarantees rapid resolution of technical blockers and maintains high staff morale.",
        "failure_boundaries": "Helpdesk service is strictly an operational support tool; never interrupts clinical workflows.",
        "ownership": "IT Field Operations & Support Team",
        "lifecycle_status": "Approved Baseline",
        "mvp_status": "MVP-PLUS",
        "release_target": "REL-02",
        "priority": "P2 - Medium",
        "dependencies": ["MODULE-001", "MODULE-003"],
        "risks": ["Vendor technician travel delays during severe Bengaluru traffic gridlock"],
        "success_metrics": ["P0 hardware outage MTTR <= 4.0 hours", "Helpdesk ticket creation latency < 30s"],
        "kpis": ["Overall facility IT hardware uptime >= 99.5%"],
        "acceptance_boundaries": "Must track operational incidents across all 183 clinics and 1,500+ client peripherals.",
        "out_of_scope": "Procurement tenders for new physical building construction and civil works."
    }
]
