#!/usr/bin/env python3
"""
domain_specs_d4.py
Domain 4: Pharmacy, Dispensing & Inventory Supply Chain
Modules: MODULE-013, MODULE-014, MODULE-015, MODULE-016.
"""

D4_MODULES = [
    {
        "id": "MODULE-013",
        "code": "MOD-13",
        "domain_id": "DOMAIN-004",
        "name": "Pharmacy Dispensing & 2D Barcode Verification",
        "purpose": "Drive outpatient pharmacy dispensing, verify e-prescriptions against physical medication packs using 2D barcode scanning, enforce First-Expiry First-Out (FEFO), and print bilingual dosage label envelopes.",
        "business_problem": "Pharmacists experience high peak volume; manual pack picking leads to wrong medication dispensing, wrong strength errors, expired drug issuance, and patient confusion over dosage instructions.",
        "business_outcome": "Zero wrong-drug dispensing errors, automated 2D barcode scan verification, automatic inventory ledger decrementation, and clear bilingual Kannada/English dosage labels printed on medicine envelopes.",
        "primary_users": ["Pharmacist"],
        "secondary_users": ["Citizen / Patient", "Medical Officer (Doctor)"],
        "roles": ["ROLE-002", "ROLE-004"],
        "submodules": [
            {"id": "SUBMODULE-046", "name": "Prescription Queue & Verification", "desc": "Receives signed e-prescriptions electronically from doctor consoles with priority indicators."},
            {"id": "SUBMODULE-047", "name": "2D Barcode & FEFO Batch Scan", "desc": "Scans physical blister pack DataMatrix/barcode; validates drug identity, batch number, and expiry."},
            {"id": "SUBMODULE-048", "name": "Bilingual Dosage Label Printing & Counseling", "desc": "Prints Kannada/English dosage instructions on envelope and logs citizen counseling completion."}
        ],
        "capabilities": [
            {"id": "CAPABILITY-091", "submodule_id": "SUBMODULE-046", "name": "Pharmacy Electronic Worklist", "desc": "Displays incoming e-prescriptions sorted by patient token and waiting duration."},
            {"id": "CAPABILITY-092", "submodule_id": "SUBMODULE-046", "name": "Partial Dispense & Substitute Handling", "desc": "Allows therapeutic equivalent substitution within approved formulary guidelines if stock is low."},
            {"id": "CAPABILITY-093", "submodule_id": "SUBMODULE-047", "name": "Barcode Scanner Hardware Interface", "desc": "Interfaces with handheld 2D USB/Bluetooth barcode scanner for sub-second pack validation."},
            {"id": "CAPABILITY-094", "submodule_id": "SUBMODULE-047", "name": "FEFO Expiry Enforcement", "desc": "Hard-blocks dispensing if scanned pack expires within 30 days or is older than available stock."},
            {"id": "CAPABILITY-095", "submodule_id": "SUBMODULE-048", "name": "Bilingual Label Generator", "desc": "Generates clear visual icons (Sun/Moon for Morning/Night) and Kannada instructions."},
            {"id": "CAPABILITY-096", "submodule_id": "SUBMODULE-048", "name": "Dispense Commit & Ledger Deduction", "desc": "Commits atomic transaction deducting exact quantity from local SQLite batch ledger."}
        ],
        "requirements": ["BR-013", "FR-012", "NFR-012", "BRULE-012", "CR-012", "OR-012", "LOC-012", "A11Y-012", "OFF-012"],
        "workflows": ["WF-001", "WF-012", "WF-013", "WF-014"],
        "data_entities": ["DispensingTransaction", "DispensedItem", "BarcodeScanAudit", "DosageLabel"],
        "planned_apis": ["PLANNED-API-031", "PLANNED-API-032"],
        "planned_ui": ["PLANNED-UI-017"],
        "integrations": ["Handheld 2D Barcode Scanner", "Label Thermal Printer", "Local SQLite Ledger"],
        "security_concerns": "Dispensing without prescription, diversion of controlled drugs, unauthorized inventory overrides.",
        "privacy_concerns": "Medicine envelopes must not display full diagnostic descriptions to protect patient privacy.",
        "offline_behavior": "Operates 100% offline on local edge server; updates local batch stock immediately.",
        "reporting_impact": "Powers daily drug consumption logs and government free-medicine fulfillment reports.",
        "analytics_impact": "Monitors stock depletion velocity and predicts stockout dates.",
        "ai_impact": "Identifies unusual surges in antibiotic or fever medication dispensing.",
        "operational_impact": "Reduces pharmacy queue bottleneck and eliminates handwriting misinterpretation.",
        "failure_boundaries": "Barcode scanner failure allows manual batch confirmation with mandatory double-check warning.",
        "ownership": "Pharmacy & Dispensing Product Team",
        "lifecycle_status": "Approved Baseline",
        "mvp_status": "CORE MVP",
        "release_target": "REL-01",
        "priority": "P0 - Critical",
        "dependencies": ["MODULE-001", "MODULE-002", "MODULE-011", "MODULE-014", "MODULE-016"],
        "risks": ["Manufacturer barcode print defects preventing optical scanning"],
        "success_metrics": ["Dispense transaction latency <= 90s per patient", "Zero wrong-medication dispensing errors"],
        "kpis": ["100% dispensed medications verified against e-prescriptions via barcode"],
        "acceptance_boundaries": "Must handle up to 300 pharmacy dispensing encounters daily.",
        "out_of_scope": "Commercial retail POS billing and cash register payments (100% free generic medicines)."
    },
    {
        "id": "MODULE-014",
        "code": "MOD-14",
        "domain_id": "DOMAIN-004",
        "name": "Real-Time Batch Inventory & FEFO Stock Ledger",
        "purpose": "Maintain perpetual local clinic stock balances partitioned by manufacturer, batch number, and expiry date, enforcing First-Expiry First-Out (FEFO) picking, quarantine locks, and physical stock count reconciliation.",
        "business_problem": "Lack of real-time inventory tracking leads to unexpected stockouts of essential anti-hypertensives/antibiotics, wastage of expired drugs, and unrecorded shrinkage.",
        "business_outcome": "Zero expired drug waste, real-time perpetual inventory accuracy (> 98%), automated buffer stock warning triggers, and auditable monthly physical count reconciliations.",
        "primary_users": ["Pharmacist", "Clinic Coordinator"],
        "secondary_users": ["Zonal Drug Inspector", "Zonal Health Officer"],
        "roles": ["ROLE-002", "ROLE-004", "ROLE-014"],
        "submodules": [
            {"id": "SUBMODULE-049", "name": "Batch-Level Stock Ledger", "desc": "Maintains quantity on hand, batch number, manufacturer, manufacturing date, and expiry date."},
            {"id": "SUBMODULE-050", "name": "FEFO Picking Engine & Expiry Warnings", "desc": "Guides pharmacist to earliest expiring batch and flags batches expiring within 90 days."},
            {"id": "SUBMODULE-051", "name": "Stock Audit & Shrinkage Reconciliation", "desc": "Facilitates monthly physical stock count entry and logs variance adjustments with justifications."}
        ],
        "capabilities": [
            {"id": "CAPABILITY-097", "submodule_id": "SUBMODULE-049", "name": "Perpetual Stock Balance Tracking", "desc": "Instantly increments on receipt and decrements on dispense within atomic SQLite transaction."},
            {"id": "CAPABILITY-098", "submodule_id": "SUBMODULE-049", "name": "Low Stock Threshold Alert", "desc": "Triggers visual warning when stock falls below 15-day buffer consumption level."},
            {"id": "CAPABILITY-099", "submodule_id": "SUBMODULE-050", "name": "Automated FEFO Shelf Guidance", "desc": "Directs pharmacist to specific shelf bin location of the earliest expiring drug batch."},
            {"id": "CAPABILITY-100", "submodule_id": "SUBMODULE-050", "name": "Expired Drug Quarantine Lock", "desc": "Automatically locks expired medication batches from appearing in the dispensing UI."},
            {"id": "CAPABILITY-101", "submodule_id": "SUBMODULE-051", "name": "Physical Stock Count Sheet", "desc": "Generates blind physical count verification sheet for monthly pharmacy audits."},
            {"id": "CAPABILITY-102", "submodule_id": "SUBMODULE-051", "name": "Variance Adjustment Signoff", "desc": "Enforces maker-checker approval between Pharmacist and MO for stock loss/damage adjustments."}
        ],
        "requirements": ["BR-014", "FR-013", "NFR-013", "BRULE-013", "CR-013", "OR-013", "OFF-013", "REP-013"],
        "workflows": ["WF-001", "WF-013", "WF-014", "WF-020"],
        "data_entities": ["BatchInventory", "StockMovementLedger", "PhysicalAuditRecord", "QuarantineBatch"],
        "planned_apis": ["PLANNED-API-033", "PLANNED-API-034"],
        "planned_ui": ["PLANNED-UI-018"],
        "integrations": ["Karnataka Drug Logistics & Warehousing Portal (Aushadha)", "Local SQLite Ledger"],
        "security_concerns": "Unauthorized inventory balance modification, falsification of physical audit counts.",
        "privacy_concerns": "Inventory ledger contains zero patient personal data.",
        "offline_behavior": "Perpetual ledger stored and managed locally on edge server; syncs to central Aushadha portal.",
        "reporting_impact": "Generates monthly drug consumption, wastage, and stock valuation reports.",
        "analytics_impact": "Calculates lead times, consumption velocity, and safety stock requirements.",
        "ai_impact": "Predicts seasonal surges in demand (e.g. anti-histamines in pollen season, ORS in summer).",
        "operational_impact": "Guarantees essential medicines are available on clinic shelves every morning.",
        "failure_boundaries": "Corrupted inventory record triggers automatic rollback from last verified WAL snapshot.",
        "ownership": "Pharmacy Supply Chain Product Team",
        "lifecycle_status": "Approved Baseline",
        "mvp_status": "CORE MVP",
        "release_target": "REL-01",
        "priority": "P0 - Critical",
        "dependencies": ["MODULE-001", "MODULE-002", "MODULE-003", "MODULE-016"],
        "risks": ["Discrepancies between physical packs and electronic count due to unrecorded breakages"],
        "success_metrics": ["Inventory ledger update latency < 50ms", "Physical-to-system stock accuracy >= 98%"],
        "kpis": ["Zero expired drugs dispensed to citizens", "Zero unrecorded drug stockout days"],
        "acceptance_boundaries": "Must track up to 500 distinct drug batches simultaneously per clinic.",
        "out_of_scope": "Central pharmaceutical manufacturing batch release and wholesale customs clearance."
    },
    {
        "id": "MODULE-015",
        "code": "MOD-15",
        "domain_id": "DOMAIN-004",
        "name": "Drug Indent Generation, Receiving & Cold-Chain Intake",
        "purpose": "Automate monthly and emergency drug indents to BBMP central medical stores, verify physical goods receipt against electronic delivery challans, and log cold-chain vaccine temperatures.",
        "business_problem": "Paper indents take weeks to process, leading to stockouts; received consignments are not cross-checked against purchase orders, and vaccine temperature spikes during transit go undetected.",
        "business_outcome": "Algorithmic indent recommendation based on consumption velocity, rapid barcode-based goods intake, and automated cold-chain temperature telemetry monitoring.",
        "primary_users": ["Pharmacist", "Clinic Coordinator"],
        "secondary_users": ["Zonal Health Officer", "Central Warehouse Manager"],
        "roles": ["ROLE-002", "ROLE-004", "ROLE-014"],
        "submodules": [
            {"id": "SUBMODULE-052", "name": "Algorithmic Indent Generator", "desc": "Calculates monthly reorder quantities based on average daily consumption and buffer targets."},
            {"id": "SUBMODULE-053", "name": "Consignment Receiving & Electronic Goods Inward", "desc": "Receives delivery challans, scans master carton barcodes, and logs batch details into inventory."},
            {"id": "SUBMODULE-054", "name": "Cold-Chain Temperature Telemetry Logger", "desc": "Tracks vaccine refrigerator temperature (2°C - 8°C) and flags thermal breach excursions."}
        ],
        "capabilities": [
            {"id": "CAPABILITY-103", "submodule_id": "SUBMODULE-052", "name": "Automated Reorder Quantity Formula", "desc": "Computes $Q_{\\text{order}} = (\\text{ADC} \\times 45) - \\text{StockOnShelf} - \\text{InTransit}$."},
            {"id": "CAPABILITY-104", "submodule_id": "SUBMODULE-052", "name": "Emergency Indent Escalation", "desc": "Dispatches urgent stock request to zonal buffer warehouse when critical medicine drops below 3 days."},
            {"id": "CAPABILITY-105", "submodule_id": "SUBMODULE-053", "name": "Electronic Delivery Challan Inward", "desc": "Imports central warehouse shipment manifest with pre-populated batch and expiry metadata."},
            {"id": "CAPABILITY-106", "submodule_id": "SUBMODULE-053", "name": "Carton Barcode Verification", "desc": "Scans GS1-128 carton barcodes to verify correct quantities and detect shipping discrepancies."},
            {"id": "CAPABILITY-107", "submodule_id": "SUBMODULE-054", "name": "IoT Temperature Sensor Bridge", "desc": "Polls Bluetooth / USB cold-chain data loggers inside vaccine ILR refrigerators."},
            {"id": "CAPABILITY-108", "submodule_id": "SUBMODULE-054", "name": "Thermal Breach SMS Alert", "desc": "Instantly alerts MO and Pharmacist via SMS if temperature breaches 8.0°C for > 30 minutes."}
        ],
        "requirements": ["BR-015", "FR-014", "NFR-014", "BRULE-014", "CR-014", "OR-014", "OFF-014", "INT-014"],
        "workflows": ["WF-001", "WF-014"],
        "data_entities": ["DrugIndent", "GoodsDeliveryChallan", "ConsignmentItem", "ColdChainTelemetryLog"],
        "planned_apis": ["PLANNED-API-035", "PLANNED-API-036"],
        "planned_ui": ["PLANNED-UI-019"],
        "integrations": ["Aushadha State Warehouse API", "eVIN Electronic Vaccine Intelligence Network"],
        "security_concerns": "Falsification of received quantities, interception of drug shipments.",
        "privacy_concerns": "Consignment manifests contain supplier and batch data; no citizen PHI involved.",
        "offline_behavior": "Allows receiving goods offline; buffers outward indent requests until WAN reconnects.",
        "reporting_impact": "Provides monthly stock replenishment cycle time and cold-chain compliance reports.",
        "analytics_impact": "Identifies recurring supply chain delivery delays from specific supplier depots.",
        "ai_impact": "Optimizes indent recommendations based on seasonal disease forecasts.",
        "operational_impact": "Eliminates stockout anxiety and guarantees vaccine potency.",
        "failure_boundaries": "Discrepant consignments quarantined with automated notification to zonal drug depot.",
        "ownership": "Supply Chain & Logistics Product Team",
        "lifecycle_status": "Approved Baseline",
        "mvp_status": "CORE MVP",
        "release_target": "REL-01",
        "priority": "P0 - Critical",
        "dependencies": ["MODULE-001", "MODULE-003", "MODULE-014", "MODULE-016"],
        "risks": ["Central warehouse out of stock for key anti-hypertensive formulations"],
        "success_metrics": ["Goods intake processing time < 15 minutes per shipment", "Zero unmonitored vaccine spoilage"],
        "kpis": ["100% adherence to 2°C - 8°C vaccine cold-chain standards"],
        "acceptance_boundaries": "Must process monthly indents of up to 120 line items per clinic.",
        "out_of_scope": "State-level international competitive bidding and pharmaceutical manufacturing tenders."
    },
    {
        "id": "MODULE-016",
        "code": "MOD-16",
        "domain_id": "DOMAIN-004",
        "name": "Essential Medicine List (EML) & Formulary Master",
        "purpose": "Maintain the standardized municipal Essential Medicine List (EML), brand-to-generic mappings, pharmacological classification (ATC/DDD), dosage forms, and therapeutic substitution rules.",
        "business_problem": "Clinics maintain inconsistent medicine catalogs with duplicate brand names, causing confusion in prescribing, non-standard unit of measurement conversions, and procurement chaos.",
        "business_outcome": "Centralized, authoritative 120-item generic formulary master synchronized across all 183 clinics, guaranteeing rational generic prescribing and consistent clinical terminology.",
        "primary_users": ["Chief Health Officer", "Zonal Health Officer", "Pharmacist"],
        "secondary_users": ["Medical Officer (Doctor)", "System Administrator"],
        "roles": ["ROLE-001", "ROLE-002", "ROLE-004", "ROLE-030"],
        "submodules": [
            {"id": "SUBMODULE-055", "name": "Formulary Master Catalog", "desc": "Maintains generic chemical names, strengths, dosage forms (tablet, syrup, ointment), and ATC codes."},
            {"id": "SUBMODULE-056", "name": "Brand-to-Generic Equivalence Index", "desc": "Maps commercial trade names to official generic chemical formulations."},
            {"id": "SUBMODULE-057", "name": "Therapeutic Substitution Guidelines", "desc": "Configures authorized clinical substitutes (e.g. Amlodipine 5mg for Nifedipine 10mg)."}
        ],
        "capabilities": [
            {"id": "CAPABILITY-109", "submodule_id": "SUBMODULE-055", "name": "Central Formulary Publishing", "desc": "Publishes versioned municipal EML master catalog from central BBMP health directory."},
            {"id": "CAPABILITY-110", "submodule_id": "SUBMODULE-055", "name": "Dosage Unit Standardization", "desc": "Enforces standardized packaging units (strips of 10, bottles of 100ml) across all modules."},
            {"id": "CAPABILITY-111", "submodule_id": "SUBMODULE-056", "name": "Brand Cross-Reference Search", "desc": "Enables doctors typing brand names (e.g. 'Calpol') to auto-select generic 'Paracetamol 500mg'."},
            {"id": "CAPABILITY-112", "submodule_id": "SUBMODULE-056", "name": "Controlled Drug Scheduling Flag", "desc": "Flags Schedule H / H1 / X controlled medications requiring special prescription logging."},
            {"id": "CAPABILITY-113", "submodule_id": "SUBMODULE-057", "name": "Approved Substitution Matrix", "desc": "Defines permissible generic substitutions when prescribed formulation is temporarily unavailable."},
            {"id": "CAPABILITY-114", "submodule_id": "SUBMODULE-057", "name": "Formulary Restriction Enforcer", "desc": "Restricts reserve antibiotics to Medical Officer prescription with mandatory rationale."}
        ],
        "requirements": ["BR-016", "FR-015", "NFR-015", "BRULE-015", "CR-015", "OR-015", "OFF-015"],
        "workflows": ["WF-001", "WF-011", "WF-012", "WF-013", "WF-014"],
        "data_entities": ["FormularyDrugItem", "BrandGenericMapping", "TherapeuticSubstituteRule", "DrugScheduleConfig"],
        "planned_apis": ["PLANNED-API-037", "PLANNED-API-038"],
        "planned_ui": ["PLANNED-UI-020"],
        "integrations": ["National List of Essential Medicines (NLEM)", "Aushadha Master Drug Directory"],
        "security_concerns": "Unauthorized insertion of unapproved brand drugs into master formulary.",
        "privacy_concerns": "Master formulary is open public health data; zero sensitive privacy concerns.",
        "offline_behavior": "Master formulary pre-packaged in local edge SQLite database; updates applied via versioned delta sync.",
        "reporting_impact": "Powers WHO rational drug prescribing indicator reports.",
        "analytics_impact": "Tracks adherence to municipal Essential Medicine List guidelines.",
        "ai_impact": "Provides pharmacological knowledge graph for clinical decision support engine.",
        "operational_impact": "Ensures uniform medication prescribing across the entire city.",
        "failure_boundaries": "Edge node enforces local cached formulary even if central publishing server is offline.",
        "ownership": "Pharmaceutical Governance Product Team",
        "lifecycle_status": "Approved Baseline",
        "mvp_status": "CORE MVP",
        "release_target": "REL-00",
        "priority": "P0 - Critical",
        "dependencies": ["MODULE-001", "MODULE-002", "MODULE-003"],
        "risks": ["Delays in state gazette notification of newly added essential drugs"],
        "success_metrics": ["Formulary sync to all clinics in < 60s", "100% generic prescribing compliance"],
        "kpis": ["Zero non-formulary commercial brand drugs dispensed"],
        "acceptance_boundaries": "Must model all 120 medications on the BBMP Namma Clinic Essential Drug List.",
        "out_of_scope": "Specialized tertiary hospital oncology/transplant immunosuppressive formulary."
    }
]
