#!/usr/bin/env python3
"""
domain_specs_d2.py
Domain 2: Frontline Intake & Citizen Operations
Modules: MODULE-005, MODULE-006, MODULE-007, MODULE-008, MODULE-020.
"""

D2_MODULES = [
    {
        "id": "MODULE-005",
        "code": "MOD-05",
        "domain_id": "DOMAIN-002",
        "name": "Patient Registration, Demographics & ABHA Minting",
        "purpose": "Drive citizen intake, capturing bilingual demographic records, deduplicating via phonetic algorithms, generating ABHA numbers and addresses, and issuing local provisional UHIDs.",
        "business_problem": "Manual paper intake creates duplicate records, delays patient queues, prevents longitudinal record linking, and causes demographic misspelling in bilingual Kannada/English environments.",
        "business_outcome": "Fast citizen registration (< 60s), zero duplicate identities, 100% ABHA generation for consenting citizens, and continuous operation during cloud dropouts via local provisional UHIDs.",
        "primary_users": ["Registration Clerk", "Staff Nurse", "ASHA Worker"],
        "secondary_users": ["Medical Officer", "Citizen / Patient"],
        "roles": ["ROLE-006", "ROLE-007", "ROLE-008"],
        "submodules": [
            {"id": "SUBMODULE-016", "name": "Bilingual Demographic Intake", "desc": "Captures citizen identity, age, gender, phone, and address in English and Kannada."},
            {"id": "SUBMODULE-017", "name": "ABHA Number & Address Creation", "desc": "Connects to ABDM / UIDAI bridge for OTP or biometric-based ABHA minting."},
            {"id": "SUBMODULE-018", "name": "Local UHID Minting & Deduplication", "desc": "Generates unique clinic UHIDs with hierarchical namespace prefixes and phonetic match checks."}
        ],
        "capabilities": [
            {"id": "CAPABILITY-031", "submodule_id": "SUBMODULE-016", "name": "Bilingual Intake UI", "desc": "Provides intuitive English/Kannada phonetic input keyboard."},
            {"id": "CAPABILITY-032", "submodule_id": "SUBMODULE-016", "name": "Vulnerable Citizen Flagging", "desc": "Flags pregnant women, elderly, pediatric, and disabled citizens for priority."},
            {"id": "CAPABILITY-033", "submodule_id": "SUBMODULE-017", "name": "Aadhaar OTP ABHA Bridge", "desc": "Dispatches Aadhaar OTP challenge to mint verified 14-digit ABHA ID."},
            {"id": "CAPABILITY-034", "submodule_id": "SUBMODULE-017", "name": "Demographic ABHA Creation", "desc": "Creates provisional ABHA for citizens without Aadhaar-linked mobile phone."},
            {"id": "CAPABILITY-035", "submodule_id": "SUBMODULE-018", "name": "Deterministic UHID Minting", "desc": "Issues offline-safe UHIDs (`BLR-WZ-NC-042-2026-000123`) using SQLite atomic sequence."},
            {"id": "CAPABILITY-036", "submodule_id": "SUBMODULE-018", "name": "Soundex / Double-Metaphone Matching", "desc": "Performs fast phonetic deduplication against local and zonal patient indexes."}
        ],
        "requirements": ["BR-004", "FR-003", "NFR-003", "BRULE-003", "CR-003", "OR-003", "SECR-003", "PRIV-003", "LOC-003", "A11Y-003", "OFF-003", "INT-003"],
        "workflows": ["WF-001", "WF-003", "WF-004", "WF-005"],
        "data_entities": ["PatientMaster", "ABHARecord", "UHIDMapping", "DeduplicationCandidate"],
        "planned_apis": ["PLANNED-API-011", "PLANNED-API-012"],
        "planned_ui": ["PLANNED-UI-006"],
        "integrations": ["ABDM M1 Gateway", "UIDAI OTP Bridge", "BBMP Citizen Data Hub"],
        "security_concerns": "Unauthorized demographic data exfiltration, Aadhaar number plaintext storage violations.",
        "privacy_concerns": "Aadhaar zeroization: strictly store only last 4 digits and hashed tokens.",
        "offline_behavior": "Operates autonomously; mints local provisional UHID; queues ABHA sync for later cloud reconnection.",
        "reporting_impact": "Powers daily outpatient footfall and demographic breakdown reports.",
        "analytics_impact": "Analyzes clinic catchment area reach and age-gender distribution.",
        "ai_impact": "Phonetic similarity algorithms detect duplicate registrations across naming variations.",
        "operational_impact": "Reduces front-desk citizen registration time from 8 minutes (paper) to under 60 seconds.",
        "failure_boundaries": "External ABDM gateway timeout immediately drops to local provisional registration without halting intake.",
        "ownership": "Citizen Intake Product Team",
        "lifecycle_status": "Approved Baseline",
        "mvp_status": "CORE MVP",
        "release_target": "REL-01",
        "priority": "P0 - Critical",
        "dependencies": ["MODULE-001", "MODULE-002", "MODULE-003"],
        "risks": ["UIDAI OTP delivery delays during high telecom congestion"],
        "success_metrics": ["Registration transaction latency < 60s (p95)", "Duplicate registration rate < 0.1%"],
        "kpis": ["100% registered citizens receive valid UHID", ">= 80% ABHA linking rate"],
        "acceptance_boundaries": "Must process up to 300 new citizen registrations per clinic day.",
        "out_of_scope": "Full electronic passport/visa verification for foreign nationals."
    },
    {
        "id": "MODULE-006",
        "code": "MOD-06",
        "domain_id": "DOMAIN-002",
        "name": "Informed Clinical Consent & DPDP Data Privacy",
        "purpose": "Capture, verify, and enforce electronic patient consent for medical examination, data sharing under the DPDP Act 2023, and ABDM health information exchange.",
        "business_problem": "Paper consent forms are frequently lost, non-standardized, lack auditable legal signatures, and fail to satisfy statutory digital personal data protection mandates.",
        "business_outcome": "Cryptographically verifiable, tamper-evident digital consent trail ensuring zero unauthorized clinical data disclosures and full citizen autonomy.",
        "primary_users": ["Registration Clerk", "Staff Nurse", "Medical Officer"],
        "secondary_users": ["Citizen / Patient", "Legal Officer"],
        "roles": ["ROLE-002", "ROLE-003", "ROLE-006", "ROLE-007"],
        "submodules": [
            {"id": "SUBMODULE-019", "name": "General Clinical Consent", "desc": "Captures consent for primary care examination, vital checks, and routine point-of-care lab tests."},
            {"id": "SUBMODULE-020", "name": "ABDM Health Data Sharing Consent", "desc": "Manages electronic consent artifacts for sharing records with external health facilities via ABDM."},
            {"id": "SUBMODULE-021", "name": "Guardian / Proxy & Emergency Consent", "desc": "Handles pediatric guardian consent, adult proxy authorizations, and medical emergency break-glass consent."}
        ],
        "capabilities": [
            {"id": "CAPABILITY-037", "submodule_id": "SUBMODULE-019", "name": "Bilingual Consent Presentation", "desc": "Presents consent clauses in clear Kannada and English on citizen-facing tablet or print slip."},
            {"id": "CAPABILITY-038", "submodule_id": "SUBMODULE-019", "name": "Digital Signature / Thumbprint Capture", "desc": "Captures electronic stylus signature, OTP confirmation, or biometric thumbprint."},
            {"id": "CAPABILITY-039", "submodule_id": "SUBMODULE-020", "name": "Granular Purpose-Based Consent", "desc": "Enables citizen to consent to specific data categories (e.g. general vs. sensitive mental health)."},
            {"id": "CAPABILITY-040", "submodule_id": "SUBMODULE-020", "name": "Consent Revocation Workflow", "desc": "Allows citizen to revoke previously granted digital consent with immediate effect."},
            {"id": "CAPABILITY-041", "submodule_id": "SUBMODULE-021", "name": "Guardian Relationship Verification", "desc": "Records parent/guardian Aadhaar and relationship proof for pediatric patients under 18."},
            {"id": "CAPABILITY-042", "submodule_id": "SUBMODULE-021", "name": "Implied Emergency Consent", "desc": "Invokes medical necessity doctrine for unconscious trauma patients with 2-clinician signoff."}
        ],
        "requirements": ["BR-005", "FR-004", "NFR-004", "BRULE-004", "CR-004", "OR-004", "SECR-004", "PRIV-004", "LOC-004"],
        "workflows": ["WF-001", "WF-006", "WF-024", "WF-025"],
        "data_entities": ["ConsentArtifact", "ConsentRevocationRecord", "ProxyAuthorization", "EmergencyConsentSignoff"],
        "planned_apis": ["PLANNED-API-013", "PLANNED-API-014"],
        "planned_ui": ["PLANNED-UI-007"],
        "integrations": ["ABDM Consent Manager", "UIDAI Biometric Auth", "WORM Ledger"],
        "security_concerns": "Forged signatures, unauthorized consent modification, stale consent reuse.",
        "privacy_concerns": "Ensuring citizens understand consent terms in their native language.",
        "offline_behavior": "Persists cryptographic consent artifact locally on edge node; verifies offline validity.",
        "reporting_impact": "Quarterly compliance audit report for State Data Protection Officer.",
        "analytics_impact": "Monitors consent acceptance vs. revocation rates across demographic segments.",
        "ai_impact": "Ensures AI models only access clinical data from citizens who opted into secondary research.",
        "operational_impact": "Eliminates physical paper consent archives while establishing solid legal protection.",
        "failure_boundaries": "Unsigned consent hard-blocks medical officer record access except in emergency break-glass mode.",
        "ownership": "Legal & Data Privacy Product Team",
        "lifecycle_status": "Approved Baseline",
        "mvp_status": "CORE MVP",
        "release_target": "REL-01",
        "priority": "P0 - Critical",
        "dependencies": ["MODULE-001", "MODULE-002", "MODULE-005"],
        "risks": ["Citizen hesitation to provide digital consent without physical paper explanation"],
        "success_metrics": ["Consent capture latency < 30s", "100% auditability of consent artifacts"],
        "kpis": ["Zero data protection non-compliance incidents"],
        "acceptance_boundaries": "Must handle up to 300 consent transactions daily per clinic.",
        "out_of_scope": "Organ donation / transplant consent agreements (specialized tertiary hospital workflows)."
    },
    {
        "id": "MODULE-007",
        "code": "MOD-07",
        "domain_id": "DOMAIN-002",
        "name": "Patient Token Generation & Station Routing",
        "purpose": "Mint daily sequential clinic tokens, apply priority stratification (emergency, pregnant, elderly), print thermal paper slips, and dispatch routing cues.",
        "business_problem": "Physical queue jumping, lack of priority for vulnerable citizens, lost paper tokens, and chaotic congregation at consultation room doors.",
        "business_outcome": "Orderly, transparent queue entry, prioritized service for vulnerable citizens, thermal slip printing with barcode, and real-time station assignment.",
        "primary_users": ["Registration Clerk", "Staff Nurse", "Citizen / Patient"],
        "secondary_users": ["Clinic Coordinator", "Security Guard"],
        "roles": ["ROLE-006", "ROLE-007"],
        "submodules": [
            {"id": "SUBMODULE-022", "name": "Sequential Token Generation", "desc": "Mints daily unique sequential numbers (`T-001`, `T-002`) reset at 07:30 AM."},
            {"id": "SUBMODULE-023", "name": "Priority Stratification & Tagging", "desc": "Tags tokens with priority tiers (`EMERGENCY-RED`, `PRIORITY-YELLOW`, `ROUTINE-GREEN`)."},
            {"id": "SUBMODULE-024", "name": "Thermal Slip Printing & Virtual SMS Slip", "desc": "Interfaces with ESC/POS thermal printers and dispatches SMS backup tokens."}
        ],
        "capabilities": [
            {"id": "CAPABILITY-043", "submodule_id": "SUBMODULE-022", "name": "Daily Token Counter", "desc": "Maintains atomic monotonic sequence per facility resetting every morning."},
            {"id": "CAPABILITY-044", "submodule_id": "SUBMODULE-022", "name": "Station Route Calculation", "desc": "Calculates routing destination (Triage -> Doctor Room 1/2 -> Lab -> Pharmacy)."},
            {"id": "CAPABILITY-045", "submodule_id": "SUBMODULE-023", "name": "Acuity-Based Insertion", "desc": "Inserts critical or emergency patients at top of queue ahead of routine tokens."},
            {"id": "CAPABILITY-046", "submodule_id": "SUBMODULE-023", "name": "Vulnerable Citizen Interleaving", "desc": "Interleaves elderly and pregnant citizens at a 2:1 ratio ahead of routine queue."},
            {"id": "CAPABILITY-047", "submodule_id": "SUBMODULE-024", "name": "ESC/POS Thermal Printing", "desc": "Prints 2-inch thermal token slip with QR code, patient name, and room assignment."},
            {"id": "CAPABILITY-048", "submodule_id": "SUBMODULE-024", "name": "Virtual SMS Token Fallback", "desc": "Dispatches SMS token notification if printer experiences paper jam or hardware fault."}
        ],
        "requirements": ["BR-006", "FR-005", "NFR-005", "BRULE-005", "CR-005", "OR-005", "PERF-005", "OFF-005"],
        "workflows": ["WF-001", "WF-007", "WF-008", "WF-010", "WF-025"],
        "data_entities": ["TokenRecord", "QueueRoutingEntry", "PrinterDeviceState", "PriorityTierMapping"],
        "planned_apis": ["PLANNED-API-015", "PLANNED-API-016"],
        "planned_ui": ["PLANNED-UI-008"],
        "integrations": ["Local USB / Network Thermal Printer", "SMS Gateway"],
        "security_concerns": "Token spoofing, physical token reuse from previous days.",
        "privacy_concerns": "Thermal slips mask patient phone number and demographic details.",
        "offline_behavior": "Operates 100% autonomously on local edge server without external network dependencies.",
        "reporting_impact": "Feeds hourly token issuance velocity into operational efficiency reports.",
        "analytics_impact": "Identifies peak clinic arrival hours (e.g. 08:30 - 10:30 AM).",
        "ai_impact": "Predicts daily clinic footfall based on day of week and local weather.",
        "operational_impact": "Eliminates queue disputes and physical crowding at front reception.",
        "failure_boundaries": "Printer jam automatically activates virtual on-screen and SMS token display.",
        "ownership": "Queue & Intake Engineering Team",
        "lifecycle_status": "Approved Baseline",
        "mvp_status": "CORE MVP",
        "release_target": "REL-01",
        "priority": "P0 - Critical",
        "dependencies": ["MODULE-003", "MODULE-005", "MODULE-006"],
        "risks": ["Thermal paper depletion during morning rush hour"],
        "success_metrics": ["Token minting and slip print latency < 2.0s (p95)", "Zero duplicate token numbers"],
        "kpis": ["100% of arriving citizens receive formal token"],
        "acceptance_boundaries": "Must support continuous token minting up to 400 tokens per clinic day.",
        "out_of_scope": "Paid VIP queue fast-tracking (strictly prohibited in public Namma Clinics)."
    },
    {
        "id": "MODULE-008",
        "code": "MOD-08",
        "domain_id": "DOMAIN-002",
        "name": "Dynamic Queue Orchestration & Display Boards",
        "purpose": "Manage multi-room clinic queue states (Waiting -> Triage -> Consultation -> Lab -> Pharmacy), drive waiting hall audio-visual display boards, and balance doctor workloads.",
        "business_problem": "Patients wander between rooms, doctors waste time physically calling patients, waiting halls are noisy and disorganized, and citizens cannot track their queue progress.",
        "business_outcome": "Automated audio-visual patient calling in Kannada and English, real-time waiting hall TV display updates, and balanced workload distribution across multiple consultation cubicles.",
        "primary_users": ["Staff Nurse", "Medical Officer", "Pharmacist", "Lab Technician"],
        "secondary_users": ["Citizen / Patient", "Clinic Coordinator"],
        "roles": ["ROLE-002", "ROLE-003", "ROLE-004", "ROLE-005"],
        "submodules": [
            {"id": "SUBMODULE-025", "name": "Multi-Station Queue State Machine", "desc": "Orchestrates token transitions across intake, vitals, consultation, lab, and pharmacy."},
            {"id": "SUBMODULE-026", "name": "Audio-Visual Calling Engine", "desc": "Drives waiting hall TV displays and synthesized bilingual voice announcements."},
            {"id": "SUBMODULE-027", "name": "Doctor Workload Balancer", "desc": "Dynamically routes next patient to available consultation cubicle based on consultation speed."}
        ],
        "capabilities": [
            {"id": "CAPABILITY-049", "submodule_id": "SUBMODULE-025", "name": "Next-Patient Call Action", "desc": "Doctor/nurse clicks 'Next' button; instantly advances queue and alerts citizen."},
            {"id": "CAPABILITY-050", "submodule_id": "SUBMODULE-025", "name": "No-Show & Recall Management", "desc": "Parks absent patients in recall buffer for 15 minutes before cancellation."},
            {"id": "CAPABILITY-051", "submodule_id": "SUBMODULE-026", "name": "HDMI Waiting Hall Display", "desc": "Renders high-contrast, responsive visual queue board on wall-mounted smart TV."},
            {"id": "CAPABILITY-052", "submodule_id": "SUBMODULE-026", "name": "Text-to-Speech Audio Chime", "desc": "Synthesizes acoustic bell and crystal-clear voice alert in Kannada and English."},
            {"id": "CAPABILITY-053", "submodule_id": "SUBMODULE-027", "name": "Dynamic Load Distribution", "desc": "Routes patients between Doctor 1 and Doctor 2 based on active consultation length."},
            {"id": "CAPABILITY-054", "submodule_id": "SUBMODULE-027", "name": "Queue Pausing & Resumption", "desc": "Allows doctors to pause queue for emergency resuscitation without losing queue state."}
        ],
        "requirements": ["BR-007", "FR-006", "NFR-006", "BRULE-006", "CR-006", "OR-006", "A11Y-006", "LOC-006", "OFF-006"],
        "workflows": ["WF-001", "WF-008", "WF-009", "WF-011", "WF-013"],
        "data_entities": ["QueueState", "CallingEvent", "DisplayBoardConfig", "NoShowAudit"],
        "planned_apis": ["PLANNED-API-017", "PLANNED-API-018"],
        "planned_ui": ["PLANNED-UI-009", "PLANNED-UI-010"],
        "integrations": ["Local Clinic Wi-Fi WebSocket Bus", "HDMI Display Output"],
        "security_concerns": "Unauthorized manipulation of queue positions, denial-of-service on audio chime.",
        "privacy_concerns": "Audio-visual calling displays token numbers and room numbers; avoids broadcasting full patient names.",
        "offline_behavior": "Queue state machine runs locally over local edge WebSocket mesh with zero cloud dependency.",
        "reporting_impact": "Measures wait times at each clinical station for operational optimization.",
        "analytics_impact": "Identifies transit bottlenecks (e.g. phlebotomy vs. doctor consultation).",
        "ai_impact": "Predicts waiting duration for arriving citizens based on active queue depth.",
        "operational_impact": "Creates quiet, professional waiting environment and reduces patient agitation.",
        "failure_boundaries": "If smart TV disconnects, staff client displays keep working and manual paper call is used.",
        "ownership": "Facility Operations Product Team",
        "lifecycle_status": "Approved Baseline",
        "mvp_status": "CORE MVP",
        "release_target": "REL-01",
        "priority": "P0 - Critical",
        "dependencies": ["MODULE-003", "MODULE-007"],
        "risks": ["Acoustic feedback or ambient noise in waiting hall drowning audio alerts"],
        "success_metrics": ["Queue transition latency < 100ms over local WebSocket", "TV board refresh < 200ms"],
        "kpis": ["Median outpatient waiting time <= 25.0 minutes"],
        "acceptance_boundaries": "Must orchestrate up to 5 concurrent station queues within a single facility.",
        "out_of_scope": "Online appointment booking for future weeks (walk-in priority primary clinics)."
    },
    {
        "id": "MODULE-020",
        "code": "MOD-20",
        "domain_id": "DOMAIN-002",
        "name": "Citizen Feedback, Grievance & Ombudsman Redressal",
        "purpose": "Capture citizen experience ratings, log operational complaints (staff behavior, medicine stockout, wait times), route tickets to ZHO, and track ombudsman resolution.",
        "business_problem": "Lack of citizen feedback channels leads to unresolved complaints, unrecorded medicine stockouts, and inability for municipal leadership to hold facilities accountable.",
        "business_outcome": "Transparent citizen grievance mechanism, automated SLA escalation for unresolved tickets, and real-time public sentiment monitoring across all 8 BBMP zones.",
        "primary_users": ["Citizen / Patient", "Clinic Coordinator", "Zonal Health Officer"],
        "secondary_users": ["Chief Health Officer", "System Administrator"],
        "roles": ["ROLE-001", "ROLE-002", "ROLE-007", "ROLE-020"],
        "submodules": [
            {"id": "SUBMODULE-028", "name": "Touchscreen Exit Survey Kiosk", "desc": "Captures 1-click smiley face satisfaction ratings and medicine receipt confirmation."},
            {"id": "SUBMODULE-029", "name": "Grievance Ticket Management", "desc": "Logs formal complaint tickets with severity, category, photographic evidence, and SLA."},
            {"id": "SUBMODULE-030", "name": "Ombudsman Escalation & Resolution", "desc": "Escalates overdue tickets to ZHO and tracks corrective action reports."}
        ],
        "capabilities": [
            {"id": "CAPABILITY-055", "submodule_id": "SUBMODULE-028", "name": "Kiosk Exit Rating", "desc": "Captures 5-level Likert satisfaction score at pharmacy exit counter."},
            {"id": "CAPABILITY-056", "submodule_id": "SUBMODULE-028", "name": "Medicine Receipt Confirmation", "desc": "Citizen confirms whether all prescribed medicines were dispensed free of charge."},
            {"id": "CAPABILITY-057", "submodule_id": "SUBMODULE-029", "name": "Multilingual Ticket Intake", "desc": "Logs grievance via QR code web portal, WhatsApp bot, or reception terminal in Kannada/English."},
            {"id": "CAPABILITY-058", "submodule_id": "SUBMODULE-029", "name": "Automated SLA Timer", "desc": "Assigns 48-hour resolution SLA for clinical complaints and 24-hour SLA for stockouts."},
            {"id": "CAPABILITY-059", "submodule_id": "SUBMODULE-030", "name": "Zonal Escalation Trigger", "desc": "Automatically alerts ZHO via SMS if clinic coordinator fails to resolve ticket in 48 hours."},
            {"id": "CAPABILITY-060", "submodule_id": "SUBMODULE-030", "name": "Citizen Resolution Feedback", "desc": "Sends SMS notification to citizen with resolution notes and appeal option."}
        ],
        "requirements": ["BR-019", "FR-019", "NFR-019", "BRULE-019", "OR-019", "LOC-019", "A11Y-019"],
        "workflows": ["WF-001", "WF-019"],
        "data_entities": ["GrievanceTicket", "SatisfactionRating", "SLAEscalationLog", "ResolutionAudit"],
        "planned_apis": ["PLANNED-API-019", "PLANNED-API-020"],
        "planned_ui": ["PLANNED-UI-011"],
        "integrations": ["BBMP Sahaaya 2.0 Civic Grievance Portal", "Citizen SMS / WhatsApp Gateway"],
        "security_concerns": "Anonymous spamming, retaliatory action against whistleblowing citizens.",
        "privacy_concerns": "Option for anonymous submission; citizen identity protected from clinic staff.",
        "offline_behavior": "Exit kiosk records satisfaction offline; queues tickets for cloud sync.",
        "reporting_impact": "Powers monthly zonal citizen satisfaction index and grievance resolution rates.",
        "analytics_impact": "Correlates low satisfaction scores with specific staff shifts or medicine stockouts.",
        "ai_impact": "NLP sentiment analysis clusters complaints by recurring facility operational themes.",
        "operational_impact": "Provides actionable citizen feedback directly to BBMP healthcare leadership.",
        "failure_boundaries": "Grievance logging failure never impedes clinical care or pharmacy dispensing.",
        "ownership": "Citizen Relations & Governance Team",
        "lifecycle_status": "Approved Baseline",
        "mvp_status": "MVP-PLUS",
        "release_target": "REL-02",
        "priority": "P2 - Medium",
        "dependencies": ["MODULE-003", "MODULE-005", "MODULE-013"],
        "risks": ["Clinic staff discouraging citizens from rating poorly"],
        "success_metrics": ["Grievance resolution rate >= 95% within SLA", "Average satisfaction score >= 4.2 / 5.0"],
        "kpis": ["Zero unacknowledged grievances older than 48 hours"],
        "acceptance_boundaries": "Must handle grievance tickets across all 183 clinics with BBMP Sahaaya integration.",
        "out_of_scope": "Legal litigation / court proceedings tracking (handled via BBMP Legal Cell)."
    }
]
