#!/usr/bin/env python3
"""
domain_specs_d3.py
Domain 3: Clinical Care & Diagnostic Orders
Modules: MODULE-009, MODULE-010, MODULE-011, MODULE-012, MODULE-029.
"""

D3_MODULES = [
    {
        "id": "MODULE-009",
        "code": "MOD-09",
        "domain_id": "DOMAIN-003",
        "name": "Doctor EMR Console & Clinical SOAP Encounter",
        "purpose": "Provide high-efficiency electronic medical record interface for primary care physicians, supporting structured SOAP documentation, longitudinal history review, vital sign telemetry, and clinical notes.",
        "business_problem": "Doctors face heavy outpatient footfall (40-60 patients per 4-hour shift); clunky EMR software slows down consultations, leading to doctors reverting to illegible handwritten paper slips.",
        "business_outcome": "High-velocity clinical documentation (< 3 minutes per routine encounter), comprehensive longitudinal record display, and 100% legibility of clinical observations.",
        "primary_users": ["Medical Officer (Doctor)"],
        "secondary_users": ["Staff Nurse", "Specialist Doctor (Tele-consult)"],
        "roles": ["ROLE-002", "ROLE-003"],
        "submodules": [
            {"id": "SUBMODULE-031", "name": "Longitudinal Patient Summary Dashboard", "desc": "Presents past episodes, chronic conditions, active medications, and vital sign trends."},
            {"id": "SUBMODULE-032", "name": "Structured SOAP Documentation Engine", "desc": "Captures Subjective complaints, Objective findings, Assessment, and Plan with 1-click templates."},
            {"id": "SUBMODULE-033", "name": "Clinical Encounter Signoff & Lock", "desc": "Cryptographically signs clinical note with doctor credentials and locks record against tampering."}
        ],
        "capabilities": [
            {"id": "CAPABILITY-061", "submodule_id": "SUBMODULE-031", "name": "Longitudinal History Viewer", "desc": "Displays chronologically sorted clinical timeline of previous visits across all BBMP clinics."},
            {"id": "CAPABILITY-062", "submodule_id": "SUBMODULE-031", "name": "Vitals Telemetry Banner", "desc": "Highlights nursing triage vitals with color-coded MEWS acuity indicator."},
            {"id": "CAPABILITY-063", "submodule_id": "SUBMODULE-032", "name": "Rapid Clinical Templates", "desc": "Provides 1-click clinical phrase templates for common conditions (URI, Hypertension, Diabetes)."},
            {"id": "CAPABILITY-064", "submodule_id": "SUBMODULE-032", "name": "Keyboard Shortcut Navigation", "desc": "Enables keyboard-only navigation (Tab, Enter, Hotkeys) for rapid documentation without mouse reliance."},
            {"id": "CAPABILITY-065", "submodule_id": "SUBMODULE-033", "name": "Cryptographic Note Locking", "desc": "Hashes clinical note and timestamps transaction; prevents retrospective altering of notes."},
            {"id": "CAPABILITY-066", "submodule_id": "SUBMODULE-033", "name": "Clinical Addendum Workflow", "desc": "Allows subsequent append-only addendum notes without modifying the original signed record."}
        ],
        "requirements": ["BR-009", "FR-008", "NFR-008", "BRULE-008", "CR-008", "OR-008", "PERF-008", "OFF-008"],
        "workflows": ["WF-001", "WF-009", "WF-010", "WF-011"],
        "data_entities": ["ClinicalEncounter", "SOAPNote", "PatientHistoryRecord", "AddendumEntry"],
        "planned_apis": ["PLANNED-API-021", "PLANNED-API-022"],
        "planned_ui": ["PLANNED-UI-012"],
        "integrations": ["Local Clinic SQLite Database", "National ABDM Health Record Gateway"],
        "security_concerns": "Unauthorized modification of past medical notes, unauthorized sharing of psychiatric notes.",
        "privacy_concerns": "Restricting sensitive reproductive and HIV diagnoses to treating physicians only.",
        "offline_behavior": "100% operational offline; reads local cached history; writes encounters to local encrypted WAL.",
        "reporting_impact": "Powers disease prevalence and outpatient morbidity reports.",
        "analytics_impact": "Tracks average consultation duration and clinical protocol compliance.",
        "ai_impact": "Extracts clinical entities for syndromic surveillance and outbreak detection.",
        "operational_impact": "Dramatically improves clinical encounter speed and diagnostic accuracy.",
        "failure_boundaries": "Encounter data buffered locally in memory and SQLite; zero data loss during power failure.",
        "ownership": "Clinical Informatics Product Team",
        "lifecycle_status": "Approved Baseline",
        "mvp_status": "CORE MVP",
        "release_target": "REL-01",
        "priority": "P0 - Critical",
        "dependencies": ["MODULE-001", "MODULE-002", "MODULE-005", "MODULE-006", "MODULE-008"],
        "risks": ["Physician resistance to typing during high-footfall shifts"],
        "success_metrics": ["Doctor encounter documentation completed in <= 180s (median)", "UI interaction latency < 100ms"],
        "kpis": ["100% legible electronic medical records generated across all consultations"],
        "acceptance_boundaries": "Must support 60 clinical consultations per doctor shift without performance drop.",
        "out_of_scope": "Inpatient ICU bed management and surgical operative notes."
    },
    {
        "id": "MODULE-010",
        "code": "MOD-10",
        "domain_id": "DOMAIN-003",
        "name": "ICD-10 & SNOMED CT Clinical Diagnosis Coding",
        "purpose": "Standardize clinical problem lists and diagnoses using International Classification of Diseases (ICD-10) and SNOMED CT terminology with fast predictive typeahead.",
        "business_problem": "Free-text diagnosis entry makes disease tracking impossible, leads to non-standard abbreviations, and prevents automated public health reporting to WHO / NHM.",
        "business_outcome": "Standardized, semantically interoperable clinical diagnostic coding enabling automated disease surveillance, accurate morbidity statistics, and ABDM FHIR bundle compatibility.",
        "primary_users": ["Medical Officer (Doctor)"],
        "secondary_users": ["Zonal Epidemiologist", "Public Health Officer"],
        "roles": ["ROLE-002", "ROLE-010"],
        "submodules": [
            {"id": "SUBMODULE-034", "name": "Predictive Typeahead Terminology Search", "desc": "Provides sub-50ms search across primary care curated subsets of ICD-10 and SNOMED CT."},
            {"id": "SUBMODULE-035", "name": "Primary vs. Secondary Diagnosis Classification", "desc": "Categorizes primary reason for visit, secondary chronic co-morbidities, and provisional tags."},
            {"id": "SUBMODULE-036", "name": "Notifiable Disease Surveillance Trigger", "desc": "Automatically flags statutory notifiable infectious diseases (Dengue, Cholera, Tuberculosis)."}
        ],
        "capabilities": [
            {"id": "CAPABILITY-067", "submodule_id": "SUBMODULE-034", "name": "Primary Care Curated Coding", "desc": "Prioritizes top 250 outpatient primary diagnoses for instant 2-keystroke selection."},
            {"id": "CAPABILITY-068", "submodule_id": "SUBMODULE-034", "name": "Synonym & Local Name Mapping", "desc": "Maps colloquial local terms (e.g. 'Motadodda Jwara') to correct ICD-10 / SNOMED concept."},
            {"id": "CAPABILITY-069", "submodule_id": "SUBMODULE-035", "name": "Chronic Condition Tagging", "desc": "Links diabetes, hypertension, and asthma to patient's permanent problem list."},
            {"id": "CAPABILITY-070", "submodule_id": "SUBMODULE-035", "name": "Provisional vs. Confirmed Status", "desc": "Allows doctors to flag diagnostic uncertainty pending laboratory confirmation."},
            {"id": "CAPABILITY-071", "submodule_id": "SUBMODULE-036", "name": "IDSP Notifiable Flagging", "desc": "Flags Integrated Disease Surveillance Programme (IDSP) Form S/P notifiable conditions."},
            {"id": "CAPABILITY-072", "submodule_id": "SUBMODULE-036", "name": "Outbreak Geographic Dispatch", "desc": "Dispatches anonymized infectious diagnosis alert to BBMP Zonal Epidemiologist."}
        ],
        "requirements": ["BR-010", "FR-009", "NFR-009", "CR-009", "OR-009", "INT-009", "REP-009"],
        "workflows": ["WF-001", "WF-011", "WF-021"],
        "data_entities": ["DiagnosisEntry", "TerminologyConcept", "NotifiableAlert", "ProblemList"],
        "planned_apis": ["PLANNED-API-023", "PLANNED-API-024"],
        "planned_ui": ["PLANNED-UI-013"],
        "integrations": ["National Health Terminology Server", "IDSP Reporting Portal"],
        "security_concerns": "Unauthorized modification of master terminology mappings.",
        "privacy_concerns": "Infectious disease notifications must strictly follow statutory public health reporting guidelines.",
        "offline_behavior": "Pre-indexed SQLite FTS5 terminology database enables full search offline without latency.",
        "reporting_impact": "Directly populates weekly IDSP surveillance returns and monthly morbidity summaries.",
        "analytics_impact": "Identifies ward-level outbreaks of waterborne and vector-borne infections.",
        "ai_impact": "Provides ground-truth diagnostic labels for clinical decision support models.",
        "operational_impact": "Ensures all diagnoses across 183 clinics speak a common medical data language.",
        "failure_boundaries": "Allows doctor free-text fallback if standard code cannot be found, queuing code for manual mapping.",
        "ownership": "Clinical Terminology Product Team",
        "lifecycle_status": "Approved Baseline",
        "mvp_status": "CORE MVP",
        "release_target": "REL-01",
        "priority": "P0 - Critical",
        "dependencies": ["MODULE-009"],
        "risks": ["Physicians selecting generic 'unspecified' codes to save time"],
        "success_metrics": ["Diagnosis search latency < 50ms (p95)", ">= 90% coded diagnosis adoption rate"],
        "kpis": ["Zero missed statutory disease notifications within 24 hours of clinical diagnosis"],
        "acceptance_boundaries": "Must index at least 15,000 ICD-10 and SNOMED CT primary care concepts.",
        "out_of_scope": "Specialized tertiary oncology / neurosurgery staging classification."
    },
    {
        "id": "MODULE-011",
        "code": "MOD-11",
        "domain_id": "DOMAIN-003",
        "name": "Electronic Prescription (e-Rx) & Drug Safety Engine",
        "purpose": "Generate legally compliant electronic prescriptions linked to clinic generic formulary, enforcing automated drug-drug interaction, allergy, and pediatric weight-based dosage safety checks.",
        "business_problem": "Handwritten prescriptions cause medication dispensing errors, adverse drug interactions, illegible dosages, and patient non-adherence due to unreadable instructions.",
        "business_outcome": "100% legible electronic prescriptions, zero severe drug-drug contraindication events, automated dosage validation, and instant electronic dispatch to the clinic pharmacy counter.",
        "primary_users": ["Medical Officer (Doctor)"],
        "secondary_users": ["Pharmacist", "Staff Nurse", "Citizen / Patient"],
        "roles": ["ROLE-002", "ROLE-004"],
        "submodules": [
            {"id": "SUBMODULE-037", "name": "Formulary-Linked e-Prescription Authoring", "desc": "Enables rapid generic medication selection with pre-set dosage, frequency, and duration."},
            {"id": "SUBMODULE-038", "name": "Automated Drug Safety & Interaction Engine", "desc": "Evaluates drug-drug interactions, known patient allergies, and contraindications in real time."},
            {"id": "SUBMODULE-039", "name": "Pediatric & Renal Dosage Calculator", "desc": "Calculates safe mg/kg pediatric doses and renal clearance adjustments based on patient vitals."}
        ],
        "capabilities": [
            {"id": "CAPABILITY-073", "submodule_id": "SUBMODULE-037", "name": "Generic Drug Selection", "desc": "Selects generic formulation (e.g. Paracetamol 500mg) linked to facility stock availability."},
            {"id": "CAPABILITY-074", "submodule_id": "SUBMODULE-037", "name": "Standard Sig Frequency Picker", "desc": "1-click selection of administration frequency (1-0-1 after food) with Kannada instructions."},
            {"id": "CAPABILITY-075", "submodule_id": "SUBMODULE-038", "name": "Drug-Drug Interaction Alert", "desc": "Flags severe and moderate pharmacokinetic interactions before doctor signs order."},
            {"id": "CAPABILITY-076", "submodule_id": "SUBMODULE-038", "name": "Allergy Cross-Check", "desc": "Hard-stops prescription if patient has documented allergy (e.g. Penicillin anaphylaxis)."},
            {"id": "CAPABILITY-077", "submodule_id": "SUBMODULE-039", "name": "Weight-Based Pediatric Dosing", "desc": "Multiplies triage weight (kg) by standard pediatric mg/kg guideline with safe maximum cap."},
            {"id": "CAPABILITY-078", "submodule_id": "SUBMODULE-039", "name": "Electronic Prescription Sign & Dispatch", "desc": "Signs prescription with doctor digital credentials and pushes instantly to pharmacy counter queue."}
        ],
        "requirements": ["BR-011", "FR-010", "NFR-010", "BRULE-010", "CR-010", "OR-010", "SECR-010", "LOC-010", "OFF-010"],
        "workflows": ["WF-001", "WF-011", "WF-012", "WF-013"],
        "data_entities": ["Prescription", "PrescriptionItem", "DrugInteractionRule", "AllergyWarningLog"],
        "planned_apis": ["PLANNED-API-025", "PLANNED-API-026"],
        "planned_ui": ["PLANNED-UI-014"],
        "integrations": ["Local Clinic Pharmacy Queue", "ABDM FHIR e-Prescription Service"],
        "security_concerns": "Prescription forgery, doctor credential theft, unauthorized prescription alteration.",
        "privacy_concerns": "Prescription records are legal medical documents protected by doctor-patient confidentiality.",
        "offline_behavior": "Drug safety rules evaluate completely on local edge SQLite database; zero cloud delay.",
        "reporting_impact": "Powers rational drug prescribing audits and antibiotic stewardship reports.",
        "analytics_impact": "Monitors top prescribed drugs and generic prescribing compliance rates.",
        "ai_impact": "Flags atypical dosage outliers compared to peer primary care clinical benchmarks.",
        "operational_impact": "Eliminates physical transit of paper prescriptions to pharmacy counter.",
        "failure_boundaries": "Doctor can override clinical warnings with mandatory documented justification.",
        "ownership": "Clinical Pharmacology Product Team",
        "lifecycle_status": "Approved Baseline",
        "mvp_status": "CORE MVP",
        "release_target": "REL-01",
        "priority": "P0 - Critical",
        "dependencies": ["MODULE-001", "MODULE-002", "MODULE-009", "MODULE-016"],
        "risks": ["Alert fatigue if drug safety warnings are configured with excessive sensitivity"],
        "success_metrics": ["Prescription authoring completed in <= 45s", "Drug safety evaluation latency < 50ms"],
        "kpis": ["Zero preventable severe drug interaction adverse events"],
        "acceptance_boundaries": "Must evaluate interactions across full 120-item Namma Clinic Essential Formulary.",
        "out_of_scope": "Chemotherapy / cytotoxic oncology regimen protocol management."
    },
    {
        "id": "MODULE-012",
        "code": "MOD-12",
        "domain_id": "DOMAIN-003",
        "name": "Point-of-Care Laboratory Testing & Diagnostic Orders",
        "purpose": "Orchestrate clinic point-of-care laboratory test orders (CBC, Blood Glucose, Urine Dipstick, Rapid Malaria, Dengue NS1), sample collection, instrument result capture, and panic value escalation.",
        "business_problem": "Paper lab order slips get lost, test results are delayed, critical panic values (e.g. severe anemia Hb < 6.0 g/dL) are not escalated to doctors immediately, and quality control logs are missing.",
        "business_outcome": "Rapid turnaround diagnostic testing (< 20 mins), automated result push to doctor EMR console, instantaneous audio-visual panic value alarms, and daily instrument calibration logs.",
        "primary_users": ["Lab Technician", "Medical Officer (Doctor)"],
        "secondary_users": ["Staff Nurse"],
        "roles": ["ROLE-002", "ROLE-005"],
        "submodules": [
            {"id": "SUBMODULE-040", "name": "Diagnostic Order Dispatch & Barcoding", "desc": "Receives electronic lab orders from doctor console and generates sample barcode labels."},
            {"id": "SUBMODULE-041", "name": "Result Entry & Instrument Interface", "desc": "Captures quantitative/qualitative test values manually or via serial/Bluetooth analyzer bridge."},
            {"id": "SUBMODULE-042", "name": "Critical Panic Value Alert Engine", "desc": "Identifies life-threatening lab values and triggers immediate flashing alert on doctor screen."}
        ],
        "capabilities": [
            {"id": "CAPABILITY-079", "submodule_id": "SUBMODULE-040", "name": "Electronic Order Queue", "desc": "Displays pending diagnostic orders on Lab Technician workstation queue in real time."},
            {"id": "CAPABILITY-080", "submodule_id": "SUBMODULE-040", "name": "Sample Barcode Labeling", "desc": "Generates 1D/2D barcode labels for blood tubes and urine specimen containers."},
            {"id": "CAPABILITY-081", "submodule_id": "SUBMODULE-041", "name": "Rapid Diagnostic Result Entry", "desc": "Enables 1-click entry for rapid test strips (HIV, Syphilis, Pregnancy, Malaria, Dengue)."},
            {"id": "CAPABILITY-082", "submodule_id": "SUBMODULE-041", "name": "POC Analyzer Serial Bridge", "desc": "Imports automated hematology / biochemistry analyzer readings via RS-232 / USB interface."},
            {"id": "CAPABILITY-083", "submodule_id": "SUBMODULE-042", "name": "Panic Value Threshold Detector", "desc": "Compares test result against age/gender biological panic boundaries (e.g. Glucose > 400 mg/dL)."},
            {"id": "CAPABILITY-084", "submodule_id": "SUBMODULE-042", "name": "Urgent Doctor Notification Push", "desc": "Pushes pop-up alert and audio chime to doctor console for immediate clinical intervention."}
        ],
        "requirements": ["BR-012", "FR-011", "NFR-011", "BRULE-011", "CR-011", "OR-011", "OFF-011", "INT-011"],
        "workflows": ["WF-001", "WF-011", "WF-015"],
        "data_entities": ["LabOrder", "SampleSpecimen", "DiagnosticResult", "PanicValueAlert"],
        "planned_apis": ["PLANNED-API-027", "PLANNED-API-028"],
        "planned_ui": ["PLANNED-UI-015"],
        "integrations": ["POC Analyzer Hardware Bridge", "WORM Audit Ledger", "ABDM Diagnostic Report Service"],
        "security_concerns": "Result tampering, unauthorized modification of verified lab reports.",
        "privacy_concerns": "HIV / Syphilis sensitive test results masked from non-clinical personnel.",
        "offline_behavior": "Operates fully offline on local edge network; analyzer bridge communicates locally.",
        "reporting_impact": "Generates daily laboratory workload log and test turnaround time reports.",
        "analytics_impact": "Tracks community positivity rates for Dengue, Malaria, and diabetes prevalence.",
        "ai_impact": "Flags inconsistent lab results compared to patient's previous historical baseline.",
        "operational_impact": "Empowers primary care doctors to make evidence-based treatment decisions on the same day.",
        "failure_boundaries": "Instrument communication failure permits manual numerical entry with technician signoff.",
        "ownership": "Diagnostic Laboratory Product Team",
        "lifecycle_status": "Approved Baseline",
        "mvp_status": "CORE MVP",
        "release_target": "REL-01",
        "priority": "P0 - Critical",
        "dependencies": ["MODULE-001", "MODULE-002", "MODULE-009"],
        "risks": ["Technician data entry transcription errors in manual entry mode"],
        "success_metrics": ["Point-of-care lab turnaround time <= 20 minutes (median)", "Panic value alert latency < 10s"],
        "kpis": ["100% of critical panic values verified and acknowledged by physician within 15 minutes"],
        "acceptance_boundaries": "Must support the standardized 24-test Namma Clinic diagnostic testing menu.",
        "out_of_scope": "Tertiary histopathology, cytogenetics, and MRI/CT diagnostic workflows."
    },
    {
        "id": "MODULE-029",
        "code": "MOD-29",
        "domain_id": "DOMAIN-003",
        "name": "Telemedicine & Specialist Tele-Consultation Bridge",
        "purpose": "Facilitate secure video and store-and-forward specialist tele-consultations (Cardiology, Dermatology, Psychiatry) between primary clinic medical officers and tertiary hospital specialists.",
        "business_problem": "Primary care clinics lack on-site medical specialists; patients must travel across Bengaluru to tertiary hospitals, incurring heavy out-of-pocket travel expenses and long wait times.",
        "business_outcome": "Direct specialist tele-consultation from the primary clinic cubicle, instant review of EMR notes and ECG traces, and reduced unnecessary secondary hospital referrals.",
        "primary_users": ["Medical Officer (Doctor)", "Specialist Consultant"],
        "secondary_users": ["Citizen / Patient", "Staff Nurse"],
        "roles": ["ROLE-002", "ROLE-012"],
        "submodules": [
            {"id": "SUBMODULE-043", "name": "Specialist Tele-Slot Scheduling", "desc": "Schedules tele-consultation appointments with panel specialists at BBMP tertiary hospitals."},
            {"id": "SUBMODULE-044", "name": "WebRTC Video & Digital Diagnostic Sharing", "desc": "Streams low-bandwidth encrypted video and shares real-time vitals and digital ECG tracings."},
            {"id": "SUBMODULE-045", "name": "Specialist Advisory Note & Endorsement", "desc": "Allows remote specialist to append recommendations directly to the primary clinic SOAP note."}
        ],
        "capabilities": [
            {"id": "CAPABILITY-085", "submodule_id": "SUBMODULE-043", "name": "Specialist Specialty Directory", "desc": "Displays availability roster of tele-specialists (Cardiology, OBGYN, Pediatrics, Dermatology)."},
            {"id": "CAPABILITY-086", "submodule_id": "SUBMODULE-043", "name": "Store-and-Forward Tele-Dermatology", "desc": "Uploads high-resolution skin lesion photographs with patient consent for asynchronous review."},
            {"id": "CAPABILITY-087", "submodule_id": "SUBMODULE-044", "name": "Low-Bandwidth Adaptive WebRTC", "desc": "Maintains clear video call over constrained 4G connections down to 256 kbps."},
            {"id": "CAPABILITY-088", "submodule_id": "SUBMODULE-044", "name": "Synchronized Clinical Note Viewer", "desc": "Specialist and primary doctor view patient EMR and vitals synchronously during call."},
            {"id": "CAPABILITY-089", "submodule_id": "SUBMODULE-045", "name": "Specialist e-Sign Endorsement", "desc": "Specialist digitally signs clinical recommendation and prescription modification."},
            {"id": "CAPABILITY-090", "submodule_id": "SUBMODULE-045", "name": "Tele-Consultation Compliance Audit", "desc": "Logs tele-encounter metadata conforming to National Medical Commission (NMC) Telemedicine Guidelines."}
        ],
        "requirements": ["BR-029", "FR-029", "NFR-029", "CR-029", "OR-029", "SECR-029", "INT-029"],
        "workflows": ["WF-001", "WF-011", "WF-016"],
        "data_entities": ["TeleconsultSession", "SpecialistRoster", "StoreAndForwardPackage", "TelemedicineAudit"],
        "planned_apis": ["PLANNED-API-029", "PLANNED-API-030"],
        "planned_ui": ["PLANNED-UI-016"],
        "integrations": ["e-Sanjeevani National Telemedicine Portal", "WebRTC SFU Gateway"],
        "security_concerns": "Intercepted video streams, unauthorized specialist impersonation, unencrypted image storage.",
        "privacy_concerns": "Explicit citizen consent required before initiating video consultation or photo upload.",
        "offline_behavior": "Requires WAN connectivity; store-and-forward packages buffered locally until link restores.",
        "reporting_impact": "Tracks tele-consultation completion rates and specialty utilization.",
        "analytics_impact": "Calculates avoided physical tertiary hospital referral percentages.",
        "ai_impact": "Pre-screens digital dermatological images for quality and lighting before upload.",
        "operational_impact": "Brings tertiary hospital specialist expertise directly to urban slum communities.",
        "failure_boundaries": "Video dropout automatically transitions session to high-priority store-and-forward mode.",
        "ownership": "Telemedicine & Specialist Care Product Team",
        "lifecycle_status": "Approved Baseline",
        "mvp_status": "POST-MVP",
        "release_target": "REL-03",
        "priority": "P2 - Medium",
        "dependencies": ["MODULE-001", "MODULE-002", "MODULE-006", "MODULE-009"],
        "risks": ["Bandwidth degradation causing choppy video during peak morning clinic hours"],
        "success_metrics": ["Tele-consultation connection success rate >= 98%", "Specialist review time < 24h"],
        "kpis": ["At least 30% reduction in physical outpatient referrals for chronic skin/cardiac conditions"],
        "acceptance_boundaries": "Must interface with BBMP tertiary referral hospitals and e-Sanjeevani API.",
        "out_of_scope": "Remote surgical robotics and acute ICU tele-monitoring."
    }
]
