"""devops_data_part2.py - Docker Images, Git Policies, PR Gates, Branching Rules, Secrets Management"""

DOCKER_IMAGES = [
    {'id': 'DOCKER-IMG-001', 'name': 'api-backend-v1', 'base_image': 'cgr.dev/chainguard/node:latest', 'stages': ['builder', 'pruner', 'production'], 'healthcheck': '/api/v1/health/liveness'},
    {'id': 'DOCKER-IMG-002', 'name': 'frontend-portal-v2', 'base_image': 'cgr.dev/chainguard/nginx:latest', 'stages': ['build-assets', 'runtime'], 'healthcheck': '/healthz'},
    {'id': 'DOCKER-IMG-003', 'name': 'clinic-sync-worker-v3', 'base_image': 'cgr.dev/chainguard/node:latest', 'stages': ['build-sync', 'runner'], 'healthcheck': '/sync/health'},
    {'id': 'DOCKER-IMG-004', 'name': 'db-migrator-v4', 'base_image': 'cgr.dev/chainguard/node:latest', 'stages': ['migration-build', 'runner'], 'healthcheck': '/status'},
    {'id': 'DOCKER-IMG-005', 'name': 'reporting-worker-v5', 'base_image': 'cgr.dev/chainguard/node:latest', 'stages': ['analytics-build', 'runner'], 'healthcheck': '/health'},
    {'id': 'DOCKER-IMG-006', 'name': 'api-backend-v6', 'base_image': 'cgr.dev/chainguard/node:latest', 'stages': ['builder', 'pruner', 'production'], 'healthcheck': '/api/v1/health/liveness'},
    {'id': 'DOCKER-IMG-007', 'name': 'frontend-portal-v7', 'base_image': 'cgr.dev/chainguard/nginx:latest', 'stages': ['build-assets', 'runtime'], 'healthcheck': '/healthz'},
    {'id': 'DOCKER-IMG-008', 'name': 'clinic-sync-worker-v8', 'base_image': 'cgr.dev/chainguard/node:latest', 'stages': ['build-sync', 'runner'], 'healthcheck': '/sync/health'},
    {'id': 'DOCKER-IMG-009', 'name': 'db-migrator-v9', 'base_image': 'cgr.dev/chainguard/node:latest', 'stages': ['migration-build', 'runner'], 'healthcheck': '/status'},
    {'id': 'DOCKER-IMG-010', 'name': 'reporting-worker-v10', 'base_image': 'cgr.dev/chainguard/node:latest', 'stages': ['analytics-build', 'runner'], 'healthcheck': '/health'},
    {'id': 'DOCKER-IMG-011', 'name': 'api-backend-v11', 'base_image': 'cgr.dev/chainguard/node:latest', 'stages': ['builder', 'pruner', 'production'], 'healthcheck': '/api/v1/health/liveness'},
    {'id': 'DOCKER-IMG-012', 'name': 'frontend-portal-v12', 'base_image': 'cgr.dev/chainguard/nginx:latest', 'stages': ['build-assets', 'runtime'], 'healthcheck': '/healthz'},
    {'id': 'DOCKER-IMG-013', 'name': 'clinic-sync-worker-v13', 'base_image': 'cgr.dev/chainguard/node:latest', 'stages': ['build-sync', 'runner'], 'healthcheck': '/sync/health'},
    {'id': 'DOCKER-IMG-014', 'name': 'db-migrator-v14', 'base_image': 'cgr.dev/chainguard/node:latest', 'stages': ['migration-build', 'runner'], 'healthcheck': '/status'},
    {'id': 'DOCKER-IMG-015', 'name': 'reporting-worker-v15', 'base_image': 'cgr.dev/chainguard/node:latest', 'stages': ['analytics-build', 'runner'], 'healthcheck': '/health'},
    {'id': 'DOCKER-IMG-016', 'name': 'api-backend-v16', 'base_image': 'cgr.dev/chainguard/node:latest', 'stages': ['builder', 'pruner', 'production'], 'healthcheck': '/api/v1/health/liveness'},
    {'id': 'DOCKER-IMG-017', 'name': 'frontend-portal-v17', 'base_image': 'cgr.dev/chainguard/nginx:latest', 'stages': ['build-assets', 'runtime'], 'healthcheck': '/healthz'},
    {'id': 'DOCKER-IMG-018', 'name': 'clinic-sync-worker-v18', 'base_image': 'cgr.dev/chainguard/node:latest', 'stages': ['build-sync', 'runner'], 'healthcheck': '/sync/health'},
    {'id': 'DOCKER-IMG-019', 'name': 'db-migrator-v19', 'base_image': 'cgr.dev/chainguard/node:latest', 'stages': ['migration-build', 'runner'], 'healthcheck': '/status'},
    {'id': 'DOCKER-IMG-020', 'name': 'reporting-worker-v20', 'base_image': 'cgr.dev/chainguard/node:latest', 'stages': ['analytics-build', 'runner'], 'healthcheck': '/health'},
    {'id': 'DOCKER-IMG-021', 'name': 'api-backend-v21', 'base_image': 'cgr.dev/chainguard/node:latest', 'stages': ['builder', 'pruner', 'production'], 'healthcheck': '/api/v1/health/liveness'},
    {'id': 'DOCKER-IMG-022', 'name': 'frontend-portal-v22', 'base_image': 'cgr.dev/chainguard/nginx:latest', 'stages': ['build-assets', 'runtime'], 'healthcheck': '/healthz'},
    {'id': 'DOCKER-IMG-023', 'name': 'clinic-sync-worker-v23', 'base_image': 'cgr.dev/chainguard/node:latest', 'stages': ['build-sync', 'runner'], 'healthcheck': '/sync/health'},
    {'id': 'DOCKER-IMG-024', 'name': 'db-migrator-v24', 'base_image': 'cgr.dev/chainguard/node:latest', 'stages': ['migration-build', 'runner'], 'healthcheck': '/status'},
    {'id': 'DOCKER-IMG-025', 'name': 'reporting-worker-v25', 'base_image': 'cgr.dev/chainguard/node:latest', 'stages': ['analytics-build', 'runner'], 'healthcheck': '/health'},
    {'id': 'DOCKER-IMG-026', 'name': 'api-backend-v26', 'base_image': 'cgr.dev/chainguard/node:latest', 'stages': ['builder', 'pruner', 'production'], 'healthcheck': '/api/v1/health/liveness'},
    {'id': 'DOCKER-IMG-027', 'name': 'frontend-portal-v27', 'base_image': 'cgr.dev/chainguard/nginx:latest', 'stages': ['build-assets', 'runtime'], 'healthcheck': '/healthz'},
    {'id': 'DOCKER-IMG-028', 'name': 'clinic-sync-worker-v28', 'base_image': 'cgr.dev/chainguard/node:latest', 'stages': ['build-sync', 'runner'], 'healthcheck': '/sync/health'},
    {'id': 'DOCKER-IMG-029', 'name': 'db-migrator-v29', 'base_image': 'cgr.dev/chainguard/node:latest', 'stages': ['migration-build', 'runner'], 'healthcheck': '/status'},
    {'id': 'DOCKER-IMG-030', 'name': 'reporting-worker-v30', 'base_image': 'cgr.dev/chainguard/node:latest', 'stages': ['analytics-build', 'runner'], 'healthcheck': '/health'},
]

GIT_POLICIES = [
    {'id': 'GIT-POL-001', 'title': 'Commit Message Convention #1', 'description': 'Enforce Conventional Commits (feat:, fix:, docs:, refactor:, test:) via commitlint.', 'enforcement': 'Commitlint hook'},
    {'id': 'GIT-POL-002', 'title': 'Signed GPG Commits #2', 'description': 'Mandatory cryptographic GPG/SSH commit signature on all branches.', 'enforcement': 'Branch protection rule'},
    {'id': 'GIT-POL-003', 'title': 'Linear Git History #3', 'description': 'Enforce squash-and-merge or rebase merge; zero merge bubble commits permitted.', 'enforcement': 'Repository settings'},
    {'id': 'GIT-POL-004', 'title': 'CODEOWNERS Enforced Review #4', 'description': 'Automatic assignment and mandatory approval from designated code owners.', 'enforcement': 'GitHub CODEOWNERS'},
    {'id': 'GIT-POL-005', 'title': 'Branch Protection Invariant #5', 'description': 'Direct pushes to develop, release/*, and main are strictly rejected.', 'enforcement': 'GitHub branch protection'},
    {'id': 'GIT-POL-006', 'title': 'Commit Message Convention #6', 'description': 'Enforce Conventional Commits (feat:, fix:, docs:, refactor:, test:) via commitlint.', 'enforcement': 'Commitlint hook'},
    {'id': 'GIT-POL-007', 'title': 'Signed GPG Commits #7', 'description': 'Mandatory cryptographic GPG/SSH commit signature on all branches.', 'enforcement': 'Branch protection rule'},
    {'id': 'GIT-POL-008', 'title': 'Linear Git History #8', 'description': 'Enforce squash-and-merge or rebase merge; zero merge bubble commits permitted.', 'enforcement': 'Repository settings'},
    {'id': 'GIT-POL-009', 'title': 'CODEOWNERS Enforced Review #9', 'description': 'Automatic assignment and mandatory approval from designated code owners.', 'enforcement': 'GitHub CODEOWNERS'},
    {'id': 'GIT-POL-010', 'title': 'Branch Protection Invariant #10', 'description': 'Direct pushes to develop, release/*, and main are strictly rejected.', 'enforcement': 'GitHub branch protection'},
    {'id': 'GIT-POL-011', 'title': 'Commit Message Convention #11', 'description': 'Enforce Conventional Commits (feat:, fix:, docs:, refactor:, test:) via commitlint.', 'enforcement': 'Commitlint hook'},
    {'id': 'GIT-POL-012', 'title': 'Signed GPG Commits #12', 'description': 'Mandatory cryptographic GPG/SSH commit signature on all branches.', 'enforcement': 'Branch protection rule'},
    {'id': 'GIT-POL-013', 'title': 'Linear Git History #13', 'description': 'Enforce squash-and-merge or rebase merge; zero merge bubble commits permitted.', 'enforcement': 'Repository settings'},
    {'id': 'GIT-POL-014', 'title': 'CODEOWNERS Enforced Review #14', 'description': 'Automatic assignment and mandatory approval from designated code owners.', 'enforcement': 'GitHub CODEOWNERS'},
    {'id': 'GIT-POL-015', 'title': 'Branch Protection Invariant #15', 'description': 'Direct pushes to develop, release/*, and main are strictly rejected.', 'enforcement': 'GitHub branch protection'},
    {'id': 'GIT-POL-016', 'title': 'Commit Message Convention #16', 'description': 'Enforce Conventional Commits (feat:, fix:, docs:, refactor:, test:) via commitlint.', 'enforcement': 'Commitlint hook'},
    {'id': 'GIT-POL-017', 'title': 'Signed GPG Commits #17', 'description': 'Mandatory cryptographic GPG/SSH commit signature on all branches.', 'enforcement': 'Branch protection rule'},
    {'id': 'GIT-POL-018', 'title': 'Linear Git History #18', 'description': 'Enforce squash-and-merge or rebase merge; zero merge bubble commits permitted.', 'enforcement': 'Repository settings'},
    {'id': 'GIT-POL-019', 'title': 'CODEOWNERS Enforced Review #19', 'description': 'Automatic assignment and mandatory approval from designated code owners.', 'enforcement': 'GitHub CODEOWNERS'},
    {'id': 'GIT-POL-020', 'title': 'Branch Protection Invariant #20', 'description': 'Direct pushes to develop, release/*, and main are strictly rejected.', 'enforcement': 'GitHub branch protection'},
    {'id': 'GIT-POL-021', 'title': 'Commit Message Convention #21', 'description': 'Enforce Conventional Commits (feat:, fix:, docs:, refactor:, test:) via commitlint.', 'enforcement': 'Commitlint hook'},
    {'id': 'GIT-POL-022', 'title': 'Signed GPG Commits #22', 'description': 'Mandatory cryptographic GPG/SSH commit signature on all branches.', 'enforcement': 'Branch protection rule'},
    {'id': 'GIT-POL-023', 'title': 'Linear Git History #23', 'description': 'Enforce squash-and-merge or rebase merge; zero merge bubble commits permitted.', 'enforcement': 'Repository settings'},
    {'id': 'GIT-POL-024', 'title': 'CODEOWNERS Enforced Review #24', 'description': 'Automatic assignment and mandatory approval from designated code owners.', 'enforcement': 'GitHub CODEOWNERS'},
    {'id': 'GIT-POL-025', 'title': 'Branch Protection Invariant #25', 'description': 'Direct pushes to develop, release/*, and main are strictly rejected.', 'enforcement': 'GitHub branch protection'},
    {'id': 'GIT-POL-026', 'title': 'Commit Message Convention #26', 'description': 'Enforce Conventional Commits (feat:, fix:, docs:, refactor:, test:) via commitlint.', 'enforcement': 'Commitlint hook'},
    {'id': 'GIT-POL-027', 'title': 'Signed GPG Commits #27', 'description': 'Mandatory cryptographic GPG/SSH commit signature on all branches.', 'enforcement': 'Branch protection rule'},
    {'id': 'GIT-POL-028', 'title': 'Linear Git History #28', 'description': 'Enforce squash-and-merge or rebase merge; zero merge bubble commits permitted.', 'enforcement': 'Repository settings'},
    {'id': 'GIT-POL-029', 'title': 'CODEOWNERS Enforced Review #29', 'description': 'Automatic assignment and mandatory approval from designated code owners.', 'enforcement': 'GitHub CODEOWNERS'},
    {'id': 'GIT-POL-030', 'title': 'Branch Protection Invariant #30', 'description': 'Direct pushes to develop, release/*, and main are strictly rejected.', 'enforcement': 'GitHub branch protection'},
    {'id': 'GIT-POL-031', 'title': 'Commit Message Convention #31', 'description': 'Enforce Conventional Commits (feat:, fix:, docs:, refactor:, test:) via commitlint.', 'enforcement': 'Commitlint hook'},
    {'id': 'GIT-POL-032', 'title': 'Signed GPG Commits #32', 'description': 'Mandatory cryptographic GPG/SSH commit signature on all branches.', 'enforcement': 'Branch protection rule'},
    {'id': 'GIT-POL-033', 'title': 'Linear Git History #33', 'description': 'Enforce squash-and-merge or rebase merge; zero merge bubble commits permitted.', 'enforcement': 'Repository settings'},
    {'id': 'GIT-POL-034', 'title': 'CODEOWNERS Enforced Review #34', 'description': 'Automatic assignment and mandatory approval from designated code owners.', 'enforcement': 'GitHub CODEOWNERS'},
    {'id': 'GIT-POL-035', 'title': 'Branch Protection Invariant #35', 'description': 'Direct pushes to develop, release/*, and main are strictly rejected.', 'enforcement': 'GitHub branch protection'},
    {'id': 'GIT-POL-036', 'title': 'Commit Message Convention #36', 'description': 'Enforce Conventional Commits (feat:, fix:, docs:, refactor:, test:) via commitlint.', 'enforcement': 'Commitlint hook'},
    {'id': 'GIT-POL-037', 'title': 'Signed GPG Commits #37', 'description': 'Mandatory cryptographic GPG/SSH commit signature on all branches.', 'enforcement': 'Branch protection rule'},
    {'id': 'GIT-POL-038', 'title': 'Linear Git History #38', 'description': 'Enforce squash-and-merge or rebase merge; zero merge bubble commits permitted.', 'enforcement': 'Repository settings'},
    {'id': 'GIT-POL-039', 'title': 'CODEOWNERS Enforced Review #39', 'description': 'Automatic assignment and mandatory approval from designated code owners.', 'enforcement': 'GitHub CODEOWNERS'},
    {'id': 'GIT-POL-040', 'title': 'Branch Protection Invariant #40', 'description': 'Direct pushes to develop, release/*, and main are strictly rejected.', 'enforcement': 'GitHub branch protection'},
]

PR_GATES = [
    {'id': 'PR-GATE-001', 'name': 'Two Peer Approvals #1', 'description': 'Minimum 2 approving reviews from senior engineers before merge eligibility.', 'validator': 'GitHub PR rule'},
    {'id': 'PR-GATE-002', 'name': '100% CI Check Suite Pass #2', 'description': 'All matrix test suites, lints, and contract tests must be 100% green.', 'validator': 'GitHub Actions Status'},
    {'id': 'PR-GATE-003', 'name': 'Zero Vulnerability Check #3', 'description': 'Trivy and Snyk scans must detect zero High or Critical vulnerabilities.', 'validator': 'Security Scanner'},
    {'id': 'PR-GATE-004', 'name': 'SonarQube Quality Gate #4', 'description': 'Code coverage must exceed 85% with zero new technical debt or security hotspots.', 'validator': 'SonarQube Quality Gate'},
    {'id': 'PR-GATE-005', 'name': 'Automated PR Checklist #5', 'description': 'PR template must have all statutory compliance and testing boxes checked.', 'validator': 'PR Template Guard'},
    {'id': 'PR-GATE-006', 'name': 'Two Peer Approvals #6', 'description': 'Minimum 2 approving reviews from senior engineers before merge eligibility.', 'validator': 'GitHub PR rule'},
    {'id': 'PR-GATE-007', 'name': '100% CI Check Suite Pass #7', 'description': 'All matrix test suites, lints, and contract tests must be 100% green.', 'validator': 'GitHub Actions Status'},
    {'id': 'PR-GATE-008', 'name': 'Zero Vulnerability Check #8', 'description': 'Trivy and Snyk scans must detect zero High or Critical vulnerabilities.', 'validator': 'Security Scanner'},
    {'id': 'PR-GATE-009', 'name': 'SonarQube Quality Gate #9', 'description': 'Code coverage must exceed 85% with zero new technical debt or security hotspots.', 'validator': 'SonarQube Quality Gate'},
    {'id': 'PR-GATE-010', 'name': 'Automated PR Checklist #10', 'description': 'PR template must have all statutory compliance and testing boxes checked.', 'validator': 'PR Template Guard'},
    {'id': 'PR-GATE-011', 'name': 'Two Peer Approvals #11', 'description': 'Minimum 2 approving reviews from senior engineers before merge eligibility.', 'validator': 'GitHub PR rule'},
    {'id': 'PR-GATE-012', 'name': '100% CI Check Suite Pass #12', 'description': 'All matrix test suites, lints, and contract tests must be 100% green.', 'validator': 'GitHub Actions Status'},
    {'id': 'PR-GATE-013', 'name': 'Zero Vulnerability Check #13', 'description': 'Trivy and Snyk scans must detect zero High or Critical vulnerabilities.', 'validator': 'Security Scanner'},
    {'id': 'PR-GATE-014', 'name': 'SonarQube Quality Gate #14', 'description': 'Code coverage must exceed 85% with zero new technical debt or security hotspots.', 'validator': 'SonarQube Quality Gate'},
    {'id': 'PR-GATE-015', 'name': 'Automated PR Checklist #15', 'description': 'PR template must have all statutory compliance and testing boxes checked.', 'validator': 'PR Template Guard'},
    {'id': 'PR-GATE-016', 'name': 'Two Peer Approvals #16', 'description': 'Minimum 2 approving reviews from senior engineers before merge eligibility.', 'validator': 'GitHub PR rule'},
    {'id': 'PR-GATE-017', 'name': '100% CI Check Suite Pass #17', 'description': 'All matrix test suites, lints, and contract tests must be 100% green.', 'validator': 'GitHub Actions Status'},
    {'id': 'PR-GATE-018', 'name': 'Zero Vulnerability Check #18', 'description': 'Trivy and Snyk scans must detect zero High or Critical vulnerabilities.', 'validator': 'Security Scanner'},
    {'id': 'PR-GATE-019', 'name': 'SonarQube Quality Gate #19', 'description': 'Code coverage must exceed 85% with zero new technical debt or security hotspots.', 'validator': 'SonarQube Quality Gate'},
    {'id': 'PR-GATE-020', 'name': 'Automated PR Checklist #20', 'description': 'PR template must have all statutory compliance and testing boxes checked.', 'validator': 'PR Template Guard'},
    {'id': 'PR-GATE-021', 'name': 'Two Peer Approvals #21', 'description': 'Minimum 2 approving reviews from senior engineers before merge eligibility.', 'validator': 'GitHub PR rule'},
    {'id': 'PR-GATE-022', 'name': '100% CI Check Suite Pass #22', 'description': 'All matrix test suites, lints, and contract tests must be 100% green.', 'validator': 'GitHub Actions Status'},
    {'id': 'PR-GATE-023', 'name': 'Zero Vulnerability Check #23', 'description': 'Trivy and Snyk scans must detect zero High or Critical vulnerabilities.', 'validator': 'Security Scanner'},
    {'id': 'PR-GATE-024', 'name': 'SonarQube Quality Gate #24', 'description': 'Code coverage must exceed 85% with zero new technical debt or security hotspots.', 'validator': 'SonarQube Quality Gate'},
    {'id': 'PR-GATE-025', 'name': 'Automated PR Checklist #25', 'description': 'PR template must have all statutory compliance and testing boxes checked.', 'validator': 'PR Template Guard'},
    {'id': 'PR-GATE-026', 'name': 'Two Peer Approvals #26', 'description': 'Minimum 2 approving reviews from senior engineers before merge eligibility.', 'validator': 'GitHub PR rule'},
    {'id': 'PR-GATE-027', 'name': '100% CI Check Suite Pass #27', 'description': 'All matrix test suites, lints, and contract tests must be 100% green.', 'validator': 'GitHub Actions Status'},
    {'id': 'PR-GATE-028', 'name': 'Zero Vulnerability Check #28', 'description': 'Trivy and Snyk scans must detect zero High or Critical vulnerabilities.', 'validator': 'Security Scanner'},
    {'id': 'PR-GATE-029', 'name': 'SonarQube Quality Gate #29', 'description': 'Code coverage must exceed 85% with zero new technical debt or security hotspots.', 'validator': 'SonarQube Quality Gate'},
    {'id': 'PR-GATE-030', 'name': 'Automated PR Checklist #30', 'description': 'PR template must have all statutory compliance and testing boxes checked.', 'validator': 'PR Template Guard'},
    {'id': 'PR-GATE-031', 'name': 'Two Peer Approvals #31', 'description': 'Minimum 2 approving reviews from senior engineers before merge eligibility.', 'validator': 'GitHub PR rule'},
    {'id': 'PR-GATE-032', 'name': '100% CI Check Suite Pass #32', 'description': 'All matrix test suites, lints, and contract tests must be 100% green.', 'validator': 'GitHub Actions Status'},
    {'id': 'PR-GATE-033', 'name': 'Zero Vulnerability Check #33', 'description': 'Trivy and Snyk scans must detect zero High or Critical vulnerabilities.', 'validator': 'Security Scanner'},
    {'id': 'PR-GATE-034', 'name': 'SonarQube Quality Gate #34', 'description': 'Code coverage must exceed 85% with zero new technical debt or security hotspots.', 'validator': 'SonarQube Quality Gate'},
    {'id': 'PR-GATE-035', 'name': 'Automated PR Checklist #35', 'description': 'PR template must have all statutory compliance and testing boxes checked.', 'validator': 'PR Template Guard'},
    {'id': 'PR-GATE-036', 'name': 'Two Peer Approvals #36', 'description': 'Minimum 2 approving reviews from senior engineers before merge eligibility.', 'validator': 'GitHub PR rule'},
    {'id': 'PR-GATE-037', 'name': '100% CI Check Suite Pass #37', 'description': 'All matrix test suites, lints, and contract tests must be 100% green.', 'validator': 'GitHub Actions Status'},
    {'id': 'PR-GATE-038', 'name': 'Zero Vulnerability Check #38', 'description': 'Trivy and Snyk scans must detect zero High or Critical vulnerabilities.', 'validator': 'Security Scanner'},
    {'id': 'PR-GATE-039', 'name': 'SonarQube Quality Gate #39', 'description': 'Code coverage must exceed 85% with zero new technical debt or security hotspots.', 'validator': 'SonarQube Quality Gate'},
    {'id': 'PR-GATE-040', 'name': 'Automated PR Checklist #40', 'description': 'PR template must have all statutory compliance and testing boxes checked.', 'validator': 'PR Template Guard'},
]

BRANCHING_RULES = [
    {'id': 'BRANCH-RULE-001', 'title': 'Short-Lived Feature Branches #1', 'rule': 'Feature branches must originate from `develop` and live less than 48 hours.', 'enforcement': 'Branch lifecycle policy'},
    {'id': 'BRANCH-RULE-002', 'title': 'Automated Stale Branch Reaper #2', 'rule': 'Merged and inactive branches (>14 days) are automatically deleted via scheduled action.', 'enforcement': 'Stale branch bot'},
    {'id': 'BRANCH-RULE-003', 'title': 'Release Candidate Branching #3', 'rule': 'Release branches `release/vX.Y.Z` branched from develop for final staging freeze.', 'enforcement': 'Release governance'},
    {'id': 'BRANCH-RULE-004', 'title': 'Emergency Hotfix Workflow #4', 'rule': '`hotfix/vX.Y.Z` branched directly from main tag, cherry-picked back to develop.', 'enforcement': 'Emergency change protocol'},
    {'id': 'BRANCH-RULE-005', 'title': 'Tagging Immutability #5', 'rule': 'Release tags `v*` are cryptographically signed and permanently locked from force update.', 'enforcement': 'Git ref protection'},
    {'id': 'BRANCH-RULE-006', 'title': 'Short-Lived Feature Branches #6', 'rule': 'Feature branches must originate from `develop` and live less than 48 hours.', 'enforcement': 'Branch lifecycle policy'},
    {'id': 'BRANCH-RULE-007', 'title': 'Automated Stale Branch Reaper #7', 'rule': 'Merged and inactive branches (>14 days) are automatically deleted via scheduled action.', 'enforcement': 'Stale branch bot'},
    {'id': 'BRANCH-RULE-008', 'title': 'Release Candidate Branching #8', 'rule': 'Release branches `release/vX.Y.Z` branched from develop for final staging freeze.', 'enforcement': 'Release governance'},
    {'id': 'BRANCH-RULE-009', 'title': 'Emergency Hotfix Workflow #9', 'rule': '`hotfix/vX.Y.Z` branched directly from main tag, cherry-picked back to develop.', 'enforcement': 'Emergency change protocol'},
    {'id': 'BRANCH-RULE-010', 'title': 'Tagging Immutability #10', 'rule': 'Release tags `v*` are cryptographically signed and permanently locked from force update.', 'enforcement': 'Git ref protection'},
    {'id': 'BRANCH-RULE-011', 'title': 'Short-Lived Feature Branches #11', 'rule': 'Feature branches must originate from `develop` and live less than 48 hours.', 'enforcement': 'Branch lifecycle policy'},
    {'id': 'BRANCH-RULE-012', 'title': 'Automated Stale Branch Reaper #12', 'rule': 'Merged and inactive branches (>14 days) are automatically deleted via scheduled action.', 'enforcement': 'Stale branch bot'},
    {'id': 'BRANCH-RULE-013', 'title': 'Release Candidate Branching #13', 'rule': 'Release branches `release/vX.Y.Z` branched from develop for final staging freeze.', 'enforcement': 'Release governance'},
    {'id': 'BRANCH-RULE-014', 'title': 'Emergency Hotfix Workflow #14', 'rule': '`hotfix/vX.Y.Z` branched directly from main tag, cherry-picked back to develop.', 'enforcement': 'Emergency change protocol'},
    {'id': 'BRANCH-RULE-015', 'title': 'Tagging Immutability #15', 'rule': 'Release tags `v*` are cryptographically signed and permanently locked from force update.', 'enforcement': 'Git ref protection'},
    {'id': 'BRANCH-RULE-016', 'title': 'Short-Lived Feature Branches #16', 'rule': 'Feature branches must originate from `develop` and live less than 48 hours.', 'enforcement': 'Branch lifecycle policy'},
    {'id': 'BRANCH-RULE-017', 'title': 'Automated Stale Branch Reaper #17', 'rule': 'Merged and inactive branches (>14 days) are automatically deleted via scheduled action.', 'enforcement': 'Stale branch bot'},
    {'id': 'BRANCH-RULE-018', 'title': 'Release Candidate Branching #18', 'rule': 'Release branches `release/vX.Y.Z` branched from develop for final staging freeze.', 'enforcement': 'Release governance'},
    {'id': 'BRANCH-RULE-019', 'title': 'Emergency Hotfix Workflow #19', 'rule': '`hotfix/vX.Y.Z` branched directly from main tag, cherry-picked back to develop.', 'enforcement': 'Emergency change protocol'},
    {'id': 'BRANCH-RULE-020', 'title': 'Tagging Immutability #20', 'rule': 'Release tags `v*` are cryptographically signed and permanently locked from force update.', 'enforcement': 'Git ref protection'},
    {'id': 'BRANCH-RULE-021', 'title': 'Short-Lived Feature Branches #21', 'rule': 'Feature branches must originate from `develop` and live less than 48 hours.', 'enforcement': 'Branch lifecycle policy'},
    {'id': 'BRANCH-RULE-022', 'title': 'Automated Stale Branch Reaper #22', 'rule': 'Merged and inactive branches (>14 days) are automatically deleted via scheduled action.', 'enforcement': 'Stale branch bot'},
    {'id': 'BRANCH-RULE-023', 'title': 'Release Candidate Branching #23', 'rule': 'Release branches `release/vX.Y.Z` branched from develop for final staging freeze.', 'enforcement': 'Release governance'},
    {'id': 'BRANCH-RULE-024', 'title': 'Emergency Hotfix Workflow #24', 'rule': '`hotfix/vX.Y.Z` branched directly from main tag, cherry-picked back to develop.', 'enforcement': 'Emergency change protocol'},
    {'id': 'BRANCH-RULE-025', 'title': 'Tagging Immutability #25', 'rule': 'Release tags `v*` are cryptographically signed and permanently locked from force update.', 'enforcement': 'Git ref protection'},
    {'id': 'BRANCH-RULE-026', 'title': 'Short-Lived Feature Branches #26', 'rule': 'Feature branches must originate from `develop` and live less than 48 hours.', 'enforcement': 'Branch lifecycle policy'},
    {'id': 'BRANCH-RULE-027', 'title': 'Automated Stale Branch Reaper #27', 'rule': 'Merged and inactive branches (>14 days) are automatically deleted via scheduled action.', 'enforcement': 'Stale branch bot'},
    {'id': 'BRANCH-RULE-028', 'title': 'Release Candidate Branching #28', 'rule': 'Release branches `release/vX.Y.Z` branched from develop for final staging freeze.', 'enforcement': 'Release governance'},
    {'id': 'BRANCH-RULE-029', 'title': 'Emergency Hotfix Workflow #29', 'rule': '`hotfix/vX.Y.Z` branched directly from main tag, cherry-picked back to develop.', 'enforcement': 'Emergency change protocol'},
    {'id': 'BRANCH-RULE-030', 'title': 'Tagging Immutability #30', 'rule': 'Release tags `v*` are cryptographically signed and permanently locked from force update.', 'enforcement': 'Git ref protection'},
]

SECRETS_MANAGEMENT = [
    {'id': 'SEC-MGMT-001', 'name': 'AWS Secrets Manager Dynamic Rotation #1', 'description': 'Database master credentials rotated automatically every 30 days via Lambda.', 'mechanism': 'Automated Lambda rotation'},
    {'id': 'SEC-MGMT-002', 'name': 'IAM Database Authentication #2', 'description': 'ECS Fargate tasks authenticate to PostgreSQL via short-lived AWS IAM tokens.', 'mechanism': 'IAM DB Auth'},
    {'id': 'SEC-MGMT-003', 'name': 'HashiCorp Vault KV Engine #3', 'description': 'Sensitive API keys stored in HashiCorp Vault KV-v2 with version history and audit log.', 'mechanism': 'Vault Token Lease'},
    {'id': 'SEC-MGMT-004', 'name': 'Envelope Encryption with KMS #4', 'description': 'Data encryption keys (DEK) wrapped with KMS Customer Master Key (CMK).', 'mechanism': 'AWS KMS Encrypt/Decrypt'},
    {'id': 'SEC-MGMT-005', 'name': 'Zero Secret in Source Code #5', 'description': 'Gitleaks CI pipeline immediately fails PRs containing detected secret patterns.', 'mechanism': 'CI Secret Scanner'},
    {'id': 'SEC-MGMT-006', 'name': 'AWS Secrets Manager Dynamic Rotation #6', 'description': 'Database master credentials rotated automatically every 30 days via Lambda.', 'mechanism': 'Automated Lambda rotation'},
    {'id': 'SEC-MGMT-007', 'name': 'IAM Database Authentication #7', 'description': 'ECS Fargate tasks authenticate to PostgreSQL via short-lived AWS IAM tokens.', 'mechanism': 'IAM DB Auth'},
    {'id': 'SEC-MGMT-008', 'name': 'HashiCorp Vault KV Engine #8', 'description': 'Sensitive API keys stored in HashiCorp Vault KV-v2 with version history and audit log.', 'mechanism': 'Vault Token Lease'},
    {'id': 'SEC-MGMT-009', 'name': 'Envelope Encryption with KMS #9', 'description': 'Data encryption keys (DEK) wrapped with KMS Customer Master Key (CMK).', 'mechanism': 'AWS KMS Encrypt/Decrypt'},
    {'id': 'SEC-MGMT-010', 'name': 'Zero Secret in Source Code #10', 'description': 'Gitleaks CI pipeline immediately fails PRs containing detected secret patterns.', 'mechanism': 'CI Secret Scanner'},
    {'id': 'SEC-MGMT-011', 'name': 'AWS Secrets Manager Dynamic Rotation #11', 'description': 'Database master credentials rotated automatically every 30 days via Lambda.', 'mechanism': 'Automated Lambda rotation'},
    {'id': 'SEC-MGMT-012', 'name': 'IAM Database Authentication #12', 'description': 'ECS Fargate tasks authenticate to PostgreSQL via short-lived AWS IAM tokens.', 'mechanism': 'IAM DB Auth'},
    {'id': 'SEC-MGMT-013', 'name': 'HashiCorp Vault KV Engine #13', 'description': 'Sensitive API keys stored in HashiCorp Vault KV-v2 with version history and audit log.', 'mechanism': 'Vault Token Lease'},
    {'id': 'SEC-MGMT-014', 'name': 'Envelope Encryption with KMS #14', 'description': 'Data encryption keys (DEK) wrapped with KMS Customer Master Key (CMK).', 'mechanism': 'AWS KMS Encrypt/Decrypt'},
    {'id': 'SEC-MGMT-015', 'name': 'Zero Secret in Source Code #15', 'description': 'Gitleaks CI pipeline immediately fails PRs containing detected secret patterns.', 'mechanism': 'CI Secret Scanner'},
    {'id': 'SEC-MGMT-016', 'name': 'AWS Secrets Manager Dynamic Rotation #16', 'description': 'Database master credentials rotated automatically every 30 days via Lambda.', 'mechanism': 'Automated Lambda rotation'},
    {'id': 'SEC-MGMT-017', 'name': 'IAM Database Authentication #17', 'description': 'ECS Fargate tasks authenticate to PostgreSQL via short-lived AWS IAM tokens.', 'mechanism': 'IAM DB Auth'},
    {'id': 'SEC-MGMT-018', 'name': 'HashiCorp Vault KV Engine #18', 'description': 'Sensitive API keys stored in HashiCorp Vault KV-v2 with version history and audit log.', 'mechanism': 'Vault Token Lease'},
    {'id': 'SEC-MGMT-019', 'name': 'Envelope Encryption with KMS #19', 'description': 'Data encryption keys (DEK) wrapped with KMS Customer Master Key (CMK).', 'mechanism': 'AWS KMS Encrypt/Decrypt'},
    {'id': 'SEC-MGMT-020', 'name': 'Zero Secret in Source Code #20', 'description': 'Gitleaks CI pipeline immediately fails PRs containing detected secret patterns.', 'mechanism': 'CI Secret Scanner'},
    {'id': 'SEC-MGMT-021', 'name': 'AWS Secrets Manager Dynamic Rotation #21', 'description': 'Database master credentials rotated automatically every 30 days via Lambda.', 'mechanism': 'Automated Lambda rotation'},
    {'id': 'SEC-MGMT-022', 'name': 'IAM Database Authentication #22', 'description': 'ECS Fargate tasks authenticate to PostgreSQL via short-lived AWS IAM tokens.', 'mechanism': 'IAM DB Auth'},
    {'id': 'SEC-MGMT-023', 'name': 'HashiCorp Vault KV Engine #23', 'description': 'Sensitive API keys stored in HashiCorp Vault KV-v2 with version history and audit log.', 'mechanism': 'Vault Token Lease'},
    {'id': 'SEC-MGMT-024', 'name': 'Envelope Encryption with KMS #24', 'description': 'Data encryption keys (DEK) wrapped with KMS Customer Master Key (CMK).', 'mechanism': 'AWS KMS Encrypt/Decrypt'},
    {'id': 'SEC-MGMT-025', 'name': 'Zero Secret in Source Code #25', 'description': 'Gitleaks CI pipeline immediately fails PRs containing detected secret patterns.', 'mechanism': 'CI Secret Scanner'},
    {'id': 'SEC-MGMT-026', 'name': 'AWS Secrets Manager Dynamic Rotation #26', 'description': 'Database master credentials rotated automatically every 30 days via Lambda.', 'mechanism': 'Automated Lambda rotation'},
    {'id': 'SEC-MGMT-027', 'name': 'IAM Database Authentication #27', 'description': 'ECS Fargate tasks authenticate to PostgreSQL via short-lived AWS IAM tokens.', 'mechanism': 'IAM DB Auth'},
    {'id': 'SEC-MGMT-028', 'name': 'HashiCorp Vault KV Engine #28', 'description': 'Sensitive API keys stored in HashiCorp Vault KV-v2 with version history and audit log.', 'mechanism': 'Vault Token Lease'},
    {'id': 'SEC-MGMT-029', 'name': 'Envelope Encryption with KMS #29', 'description': 'Data encryption keys (DEK) wrapped with KMS Customer Master Key (CMK).', 'mechanism': 'AWS KMS Encrypt/Decrypt'},
    {'id': 'SEC-MGMT-030', 'name': 'Zero Secret in Source Code #30', 'description': 'Gitleaks CI pipeline immediately fails PRs containing detected secret patterns.', 'mechanism': 'CI Secret Scanner'},
    {'id': 'SEC-MGMT-031', 'name': 'AWS Secrets Manager Dynamic Rotation #31', 'description': 'Database master credentials rotated automatically every 30 days via Lambda.', 'mechanism': 'Automated Lambda rotation'},
    {'id': 'SEC-MGMT-032', 'name': 'IAM Database Authentication #32', 'description': 'ECS Fargate tasks authenticate to PostgreSQL via short-lived AWS IAM tokens.', 'mechanism': 'IAM DB Auth'},
    {'id': 'SEC-MGMT-033', 'name': 'HashiCorp Vault KV Engine #33', 'description': 'Sensitive API keys stored in HashiCorp Vault KV-v2 with version history and audit log.', 'mechanism': 'Vault Token Lease'},
    {'id': 'SEC-MGMT-034', 'name': 'Envelope Encryption with KMS #34', 'description': 'Data encryption keys (DEK) wrapped with KMS Customer Master Key (CMK).', 'mechanism': 'AWS KMS Encrypt/Decrypt'},
    {'id': 'SEC-MGMT-035', 'name': 'Zero Secret in Source Code #35', 'description': 'Gitleaks CI pipeline immediately fails PRs containing detected secret patterns.', 'mechanism': 'CI Secret Scanner'},
    {'id': 'SEC-MGMT-036', 'name': 'AWS Secrets Manager Dynamic Rotation #36', 'description': 'Database master credentials rotated automatically every 30 days via Lambda.', 'mechanism': 'Automated Lambda rotation'},
    {'id': 'SEC-MGMT-037', 'name': 'IAM Database Authentication #37', 'description': 'ECS Fargate tasks authenticate to PostgreSQL via short-lived AWS IAM tokens.', 'mechanism': 'IAM DB Auth'},
    {'id': 'SEC-MGMT-038', 'name': 'HashiCorp Vault KV Engine #38', 'description': 'Sensitive API keys stored in HashiCorp Vault KV-v2 with version history and audit log.', 'mechanism': 'Vault Token Lease'},
    {'id': 'SEC-MGMT-039', 'name': 'Envelope Encryption with KMS #39', 'description': 'Data encryption keys (DEK) wrapped with KMS Customer Master Key (CMK).', 'mechanism': 'AWS KMS Encrypt/Decrypt'},
    {'id': 'SEC-MGMT-040', 'name': 'Zero Secret in Source Code #40', 'description': 'Gitleaks CI pipeline immediately fails PRs containing detected secret patterns.', 'mechanism': 'CI Secret Scanner'},
    {'id': 'SEC-MGMT-041', 'name': 'AWS Secrets Manager Dynamic Rotation #41', 'description': 'Database master credentials rotated automatically every 30 days via Lambda.', 'mechanism': 'Automated Lambda rotation'},
    {'id': 'SEC-MGMT-042', 'name': 'IAM Database Authentication #42', 'description': 'ECS Fargate tasks authenticate to PostgreSQL via short-lived AWS IAM tokens.', 'mechanism': 'IAM DB Auth'},
    {'id': 'SEC-MGMT-043', 'name': 'HashiCorp Vault KV Engine #43', 'description': 'Sensitive API keys stored in HashiCorp Vault KV-v2 with version history and audit log.', 'mechanism': 'Vault Token Lease'},
    {'id': 'SEC-MGMT-044', 'name': 'Envelope Encryption with KMS #44', 'description': 'Data encryption keys (DEK) wrapped with KMS Customer Master Key (CMK).', 'mechanism': 'AWS KMS Encrypt/Decrypt'},
    {'id': 'SEC-MGMT-045', 'name': 'Zero Secret in Source Code #45', 'description': 'Gitleaks CI pipeline immediately fails PRs containing detected secret patterns.', 'mechanism': 'CI Secret Scanner'},
    {'id': 'SEC-MGMT-046', 'name': 'AWS Secrets Manager Dynamic Rotation #46', 'description': 'Database master credentials rotated automatically every 30 days via Lambda.', 'mechanism': 'Automated Lambda rotation'},
    {'id': 'SEC-MGMT-047', 'name': 'IAM Database Authentication #47', 'description': 'ECS Fargate tasks authenticate to PostgreSQL via short-lived AWS IAM tokens.', 'mechanism': 'IAM DB Auth'},
    {'id': 'SEC-MGMT-048', 'name': 'HashiCorp Vault KV Engine #48', 'description': 'Sensitive API keys stored in HashiCorp Vault KV-v2 with version history and audit log.', 'mechanism': 'Vault Token Lease'},
    {'id': 'SEC-MGMT-049', 'name': 'Envelope Encryption with KMS #49', 'description': 'Data encryption keys (DEK) wrapped with KMS Customer Master Key (CMK).', 'mechanism': 'AWS KMS Encrypt/Decrypt'},
    {'id': 'SEC-MGMT-050', 'name': 'Zero Secret in Source Code #50', 'description': 'Gitleaks CI pipeline immediately fails PRs containing detected secret patterns.', 'mechanism': 'CI Secret Scanner'},
]
