"""
qa_data_part1.py
Canonical QA Registries Part 1: Strategies, Levels, Defects, Gates, Environments, Regression.
"""

TEST_STRATEGIES = [
    {'id': 'TEST-STRAT-001', 'title': 'Risk-Based Clinical Testing Charter', 'domain': 'Clinical Safety', 'description': 'Prioritizes clinical triage, vitals accuracy, and drug allergy contraindication alerts to eliminate patient safety hazards.'},
    {'id': 'TEST-STRAT-002', 'title': 'Shift-Left Automated Quality Gate Strategy', 'domain': 'Engineering', 'description': 'Enforces static analysis, type checking, security linting, and unit test execution on every developer commit.'},
    {'id': 'TEST-STRAT-003', 'title': 'Test Pyramid Layering & Coverage Strategy', 'domain': 'Architecture', 'description': 'Targets 70% unit test coverage, 20% integration/contract tests, and 10% end-to-end journey tests.'},
    {'id': 'TEST-STRAT-004', 'title': 'Zero-Trust Security & RBAC Enforcement Charter', 'domain': 'Security', 'description': 'Validates that no request is trusted implicitly; audits token signatures, contextual ABAC, and tenant barriers.'},
    {'id': 'TEST-STRAT-005', 'title': 'Autonomous Edge Offline Verification Framework', 'domain': 'Resilience', 'description': 'Verifies clinic workstation autonomy during total broadband outages, network flapping, and power cuts.'},
    {'id': 'TEST-STRAT-006', 'title': 'Bidirectional Eventual Consistency Sync Charter', 'domain': 'Data Sync', 'description': 'Ensures SQLite-to-Cloud replication idempotency, deterministic conflict resolution, and zero data loss.'},
    {'id': 'TEST-STRAT-007', 'title': 'ABDM Ecosystem Compliance & Interop Charter', 'domain': 'Integration', 'description': 'Validates National Health Authority (NHA) M1/M2/M3 standards, ABHA authentication, and FHIR R4 bundles.'},
    {'id': 'TEST-STRAT-008', 'title': 'Synthetic Test Data & PII Isolation Policy', 'domain': 'Governance', 'description': 'Mandates 100% synthetic clinical data; strictly prohibits production patient data extraction in QA environments.'},
    {'id': 'TEST-STRAT-009', 'title': 'Performance SLA & Peak OPD Load Charter', 'domain': 'Performance', 'description': 'Guarantees < 500ms p95 API response times and < 100ms offline local database response under 5,000 OPD peak load.'},
    {'id': 'TEST-STRAT-010', 'title': 'Accessibility & Universal Design (WCAG 2.1 AA)', 'domain': 'Inclusivity', 'description': 'Ensures barrier-free operation for healthcare workers via full keyboard nav, high contrast, and screen readers.'},
    {'id': 'TEST-STRAT-011', 'title': 'Kannada/English Bilingual Localization Charter', 'domain': 'Localization', 'description': 'Validates 100% translation fidelity, medical terminology accuracy, and zero UI truncation in Kannada.'},
    {'id': 'TEST-STRAT-012', 'title': 'Emergency Break-Glass Auditability Strategy', 'domain': 'Clinical', 'description': 'Verifies dual-witness emergency chart overrides, retrospective medical review, and tamper-proof logging.'},
    {'id': 'TEST-STRAT-013', 'title': 'Controlled Substance & Narcotic Audit Charter', 'domain': 'Pharmacy', 'description': 'Enforces 100% verification of double-signature drug dispensing, FEFO batch tracking, and inventory reconciliations.'},
    {'id': 'TEST-STRAT-014', 'title': 'Diagnostic Laboratory Analyzer Serial Bridge', 'domain': 'Laboratory', 'description': 'Verifies ASTM/HL7 serial interface protocols for automated lab machine results ingestion without human error.'},
    {'id': 'TEST-STRAT-015', 'title': 'Thermal Receipt Printer & Barcode Scanner Charter', 'domain': 'Peripherals', 'description': 'Verifies ESC/POS binary spooling, Kannada bitmap rendering, and 2D barcode scan latency < 150ms.'},
    {'id': 'TEST-STRAT-016', 'title': 'Disaster Recovery & Clean Backup Restore Strategy', 'domain': 'Resilience', 'description': 'Tests weekly automated restores from S3 Object Lock WORM backups into quarantined sandboxes.'},
    {'id': 'TEST-STRAT-017', 'title': 'Public Health Telemetry & Differential Privacy', 'domain': 'Analytics', 'description': 'Ensures ClickHouse reporting aggregations preserve citizen anonymity via strict Laplace noise bounds.'},
    {'id': 'TEST-STRAT-018', 'title': 'Cold-Chain IoT Vaccine Temperature Guardrails', 'domain': 'Supply Chain', 'description': 'Validates MQTT telemetry parsing, temperature breach alert dispatch, and vaccine batch quarantines.'},
    {'id': 'TEST-STRAT-019', 'title': 'Continuous Contract Testing (Pact / OpenAPI)', 'domain': 'Architecture', 'description': 'Validates API producer-consumer schemas continuously in CI to prevent microservice breaking changes.'},
    {'id': 'TEST-STRAT-020', 'title': 'Mutation Testing & Test Suite Resilience Charter', 'domain': 'Engineering', 'description': 'Applies mutation operators to verify that unit tests fail when defects are introduced into clinical business logic.'},
    {'id': 'TEST-STRAT-021', 'title': 'User Acceptance Testing (UAT) Clinical Council', 'domain': 'Governance', 'description': 'Establishes formal acceptance criteria and sign-off protocols by practicing BBMP doctors and nurses.'},
    {'id': 'TEST-STRAT-022', 'title': 'Phased Pilot Clinic Rollout & Shadow-Mode Run', 'domain': 'Deployment', 'description': 'Executes parallel runs across 5 pilot clinics to validate real-world operational ergonomics before city-wide launch.'},
    {'id': 'TEST-STRAT-023', 'title': 'Defect Containment & Release Blocking SLA Strategy', 'domain': 'Governance', 'description': 'Defines strict criteria where Severity-1 and Severity-2 defects immediately veto release candidates.'},
    {'id': 'TEST-STRAT-024', 'title': 'Field Nurse Android Tablet MDM Policy Charter', 'domain': 'Mobile', 'description': 'Verifies Knox kiosk mode, storage encryption, remote wipe, and battery preservation on field nurse tablets.'},
    {'id': 'TEST-STRAT-025', 'title': 'Statutory CERT-In & DPDP Act Compliance Audit', 'domain': 'Regulatory', 'description': 'Validates 6-hour cybersecurity incident reporting and DPDP Section 6 affirmative electronic consent flows.'},
]

TEST_LEVELS = [
    {'id': 'TEST-LEVEL-001', 'name': 'Unit Testing', 'owner': 'Developer', 'scope': 'Function / Class', 'description': 'Isolated logic verification for pure functions, clinical algorithms, and domain entities.'},
    {'id': 'TEST-LEVEL-002', 'name': 'Component Testing', 'owner': 'Frontend/Backend Dev', 'scope': 'UI Component / Subsystem', 'description': 'Verifies isolated React components and backend service modules in mock containers.'},
    {'id': 'TEST-LEVEL-003', 'name': 'Integration Testing', 'owner': 'Dev & QA', 'scope': 'Service Boundaries', 'description': 'Tests communication between microservices, Redis session caches, and PostgreSQL databases.'},
    {'id': 'TEST-LEVEL-004', 'name': 'Contract Testing', 'owner': 'QA Engineer', 'scope': 'API Schema Contracts', 'description': 'Validates API consumer and provider agreements via OpenAPI and Pact schemas.'},
    {'id': 'TEST-LEVEL-005', 'name': 'API Testing', 'owner': 'SDET', 'scope': 'REST & WebSocket Endpoints', 'description': 'Comprehensive testing of 341 endpoints for functional correctness, auth, and rate limits.'},
    {'id': 'TEST-LEVEL-006', 'name': 'System Testing', 'owner': 'QA Team', 'scope': 'Integrated Platform', 'description': 'End-to-end system testing in staging enclaves seeded with full synthetic clinical datasets.'},
    {'id': 'TEST-LEVEL-007', 'name': 'End-to-End (E2E) Testing', 'owner': 'QA Automation', 'scope': 'User Journeys', 'description': 'Full headless browser automation covering patient registration, triage, consultation, and dispensing.'},
    {'id': 'TEST-LEVEL-008', 'name': 'UI & Visual Regression', 'owner': 'Frontend QA', 'scope': 'Presentation Layer', 'description': 'Snapshot visual regression across 108 screens, responsive breakpoints, and dark mode.'},
    {'id': 'TEST-LEVEL-009', 'name': 'Performance & Scalability', 'owner': 'Performance SDET', 'scope': 'Infrastructure & APIs', 'description': 'Load, soak, stress, spike, and endurance testing simulating 5,000 concurrent clinic users.'},
    {'id': 'TEST-LEVEL-010', 'name': 'Security & VAPT', 'owner': 'SecOps / Red Team', 'scope': 'Attack Surfaces', 'description': 'OWASP Top 10, BOLA, JWT tampering, SQLi, and CERT-In compliance penetration testing.'},
    {'id': 'TEST-LEVEL-011', 'name': 'Accessibility (WCAG 2.1 AA)', 'owner': 'Accessibility QA', 'scope': 'User Interface', 'description': 'Automated axe-core audits and manual screen reader testing across all 108 screens.'},
    {'id': 'TEST-LEVEL-012', 'name': 'Localization (Kannada/English)', 'owner': 'L10n Specialist', 'scope': 'Locale Engine', 'description': 'Verifies translation completeness, script typography, dates, currency, and printed receipts.'},
    {'id': 'TEST-LEVEL-013', 'name': 'Offline & Resilience Testing', 'owner': 'QA & Edge Eng', 'scope': 'Clinic Mini-PC Edge', 'description': 'Simulates network disconnection, power cuts, packet drops, and local SQLite persistence.'},
    {'id': 'TEST-LEVEL-014', 'name': 'Data Quality & Migration', 'owner': 'Data QA', 'scope': 'Database & Pipelines', 'description': 'Validates schema migrations, referential integrity across 52 tables, and ClickHouse ETL.'},
    {'id': 'TEST-LEVEL-015', 'name': 'User Acceptance Testing (UAT)', 'owner': 'Clinical Stakeholders', 'scope': 'Workflows', 'description': 'Clinician sign-off testing in simulated clinic environments using staging hardware.'},
    {'id': 'TEST-LEVEL-016', 'name': 'Pilot Validation Testing', 'owner': 'Field Operations Lead', 'scope': 'Physical Clinics', 'description': 'Operational shadow-mode validation across 5 live pilot clinics in Bruhat Bengaluru Mahanagara.'},
]

DEFECT_REGISTRY = [
    {'id': 'DEFECT-001', 'title': 'Defect Taxonomy Classification 1', 'severity': 'S1-Blocker', 'priority': 'P0', 'resolution_sla': '2 Hours', 'escape_phase': 'Staging Quality Gate', 'root_cause': 'Logic Defect / Race Condition / Schema Drift', 'retest_required': True},
    {'id': 'DEFECT-002', 'title': 'Defect Taxonomy Classification 2', 'severity': 'S1-Blocker', 'priority': 'P0', 'resolution_sla': '2 Hours', 'escape_phase': 'Staging Quality Gate', 'root_cause': 'Logic Defect / Race Condition / Schema Drift', 'retest_required': True},
    {'id': 'DEFECT-003', 'title': 'Defect Taxonomy Classification 3', 'severity': 'S1-Blocker', 'priority': 'P0', 'resolution_sla': '2 Hours', 'escape_phase': 'Staging Quality Gate', 'root_cause': 'Logic Defect / Race Condition / Schema Drift', 'retest_required': True},
    {'id': 'DEFECT-004', 'title': 'Defect Taxonomy Classification 4', 'severity': 'S1-Blocker', 'priority': 'P0', 'resolution_sla': '2 Hours', 'escape_phase': 'Staging Quality Gate', 'root_cause': 'Logic Defect / Race Condition / Schema Drift', 'retest_required': True},
    {'id': 'DEFECT-005', 'title': 'Defect Taxonomy Classification 5', 'severity': 'S1-Blocker', 'priority': 'P0', 'resolution_sla': '2 Hours', 'escape_phase': 'Staging Quality Gate', 'root_cause': 'Logic Defect / Race Condition / Schema Drift', 'retest_required': True},
    {'id': 'DEFECT-006', 'title': 'Defect Taxonomy Classification 6', 'severity': 'S1-Blocker', 'priority': 'P0', 'resolution_sla': '2 Hours', 'escape_phase': 'Staging Quality Gate', 'root_cause': 'Logic Defect / Race Condition / Schema Drift', 'retest_required': True},
    {'id': 'DEFECT-007', 'title': 'Defect Taxonomy Classification 7', 'severity': 'S1-Blocker', 'priority': 'P0', 'resolution_sla': '2 Hours', 'escape_phase': 'Staging Quality Gate', 'root_cause': 'Logic Defect / Race Condition / Schema Drift', 'retest_required': True},
    {'id': 'DEFECT-008', 'title': 'Defect Taxonomy Classification 8', 'severity': 'S1-Blocker', 'priority': 'P0', 'resolution_sla': '2 Hours', 'escape_phase': 'Staging Quality Gate', 'root_cause': 'Logic Defect / Race Condition / Schema Drift', 'retest_required': True},
    {'id': 'DEFECT-009', 'title': 'Defect Taxonomy Classification 9', 'severity': 'S1-Blocker', 'priority': 'P0', 'resolution_sla': '2 Hours', 'escape_phase': 'Staging Quality Gate', 'root_cause': 'Logic Defect / Race Condition / Schema Drift', 'retest_required': True},
    {'id': 'DEFECT-010', 'title': 'Defect Taxonomy Classification 10', 'severity': 'S1-Blocker', 'priority': 'P0', 'resolution_sla': '2 Hours', 'escape_phase': 'Staging Quality Gate', 'root_cause': 'Logic Defect / Race Condition / Schema Drift', 'retest_required': True},
    {'id': 'DEFECT-011', 'title': 'Defect Taxonomy Classification 11', 'severity': 'S2-Critical', 'priority': 'P1', 'resolution_sla': '8 Hours', 'escape_phase': 'Staging Quality Gate', 'root_cause': 'Logic Defect / Race Condition / Schema Drift', 'retest_required': True},
    {'id': 'DEFECT-012', 'title': 'Defect Taxonomy Classification 12', 'severity': 'S2-Critical', 'priority': 'P1', 'resolution_sla': '8 Hours', 'escape_phase': 'Staging Quality Gate', 'root_cause': 'Logic Defect / Race Condition / Schema Drift', 'retest_required': True},
    {'id': 'DEFECT-013', 'title': 'Defect Taxonomy Classification 13', 'severity': 'S2-Critical', 'priority': 'P1', 'resolution_sla': '8 Hours', 'escape_phase': 'Staging Quality Gate', 'root_cause': 'Logic Defect / Race Condition / Schema Drift', 'retest_required': True},
    {'id': 'DEFECT-014', 'title': 'Defect Taxonomy Classification 14', 'severity': 'S2-Critical', 'priority': 'P1', 'resolution_sla': '8 Hours', 'escape_phase': 'Staging Quality Gate', 'root_cause': 'Logic Defect / Race Condition / Schema Drift', 'retest_required': True},
    {'id': 'DEFECT-015', 'title': 'Defect Taxonomy Classification 15', 'severity': 'S2-Critical', 'priority': 'P1', 'resolution_sla': '8 Hours', 'escape_phase': 'Staging Quality Gate', 'root_cause': 'Logic Defect / Race Condition / Schema Drift', 'retest_required': True},
    {'id': 'DEFECT-016', 'title': 'Defect Taxonomy Classification 16', 'severity': 'S2-Critical', 'priority': 'P1', 'resolution_sla': '8 Hours', 'escape_phase': 'Staging Quality Gate', 'root_cause': 'Logic Defect / Race Condition / Schema Drift', 'retest_required': True},
    {'id': 'DEFECT-017', 'title': 'Defect Taxonomy Classification 17', 'severity': 'S2-Critical', 'priority': 'P1', 'resolution_sla': '8 Hours', 'escape_phase': 'Staging Quality Gate', 'root_cause': 'Logic Defect / Race Condition / Schema Drift', 'retest_required': True},
    {'id': 'DEFECT-018', 'title': 'Defect Taxonomy Classification 18', 'severity': 'S2-Critical', 'priority': 'P1', 'resolution_sla': '8 Hours', 'escape_phase': 'Staging Quality Gate', 'root_cause': 'Logic Defect / Race Condition / Schema Drift', 'retest_required': True},
    {'id': 'DEFECT-019', 'title': 'Defect Taxonomy Classification 19', 'severity': 'S2-Critical', 'priority': 'P1', 'resolution_sla': '8 Hours', 'escape_phase': 'Staging Quality Gate', 'root_cause': 'Logic Defect / Race Condition / Schema Drift', 'retest_required': True},
    {'id': 'DEFECT-020', 'title': 'Defect Taxonomy Classification 20', 'severity': 'S2-Critical', 'priority': 'P1', 'resolution_sla': '8 Hours', 'escape_phase': 'Staging Quality Gate', 'root_cause': 'Logic Defect / Race Condition / Schema Drift', 'retest_required': True},
    {'id': 'DEFECT-021', 'title': 'Defect Taxonomy Classification 21', 'severity': 'S2-Critical', 'priority': 'P1', 'resolution_sla': '8 Hours', 'escape_phase': 'Staging Quality Gate', 'root_cause': 'Logic Defect / Race Condition / Schema Drift', 'retest_required': True},
    {'id': 'DEFECT-022', 'title': 'Defect Taxonomy Classification 22', 'severity': 'S2-Critical', 'priority': 'P1', 'resolution_sla': '8 Hours', 'escape_phase': 'Staging Quality Gate', 'root_cause': 'Logic Defect / Race Condition / Schema Drift', 'retest_required': True},
    {'id': 'DEFECT-023', 'title': 'Defect Taxonomy Classification 23', 'severity': 'S2-Critical', 'priority': 'P1', 'resolution_sla': '8 Hours', 'escape_phase': 'Staging Quality Gate', 'root_cause': 'Logic Defect / Race Condition / Schema Drift', 'retest_required': True},
    {'id': 'DEFECT-024', 'title': 'Defect Taxonomy Classification 24', 'severity': 'S2-Critical', 'priority': 'P1', 'resolution_sla': '8 Hours', 'escape_phase': 'Staging Quality Gate', 'root_cause': 'Logic Defect / Race Condition / Schema Drift', 'retest_required': True},
    {'id': 'DEFECT-025', 'title': 'Defect Taxonomy Classification 25', 'severity': 'S2-Critical', 'priority': 'P1', 'resolution_sla': '8 Hours', 'escape_phase': 'Staging Quality Gate', 'root_cause': 'Logic Defect / Race Condition / Schema Drift', 'retest_required': True},
    {'id': 'DEFECT-026', 'title': 'Defect Taxonomy Classification 26', 'severity': 'S3-Major', 'priority': 'P2', 'resolution_sla': '48 Hours', 'escape_phase': 'Staging Quality Gate', 'root_cause': 'Logic Defect / Race Condition / Schema Drift', 'retest_required': True},
    {'id': 'DEFECT-027', 'title': 'Defect Taxonomy Classification 27', 'severity': 'S3-Major', 'priority': 'P2', 'resolution_sla': '48 Hours', 'escape_phase': 'Staging Quality Gate', 'root_cause': 'Logic Defect / Race Condition / Schema Drift', 'retest_required': True},
    {'id': 'DEFECT-028', 'title': 'Defect Taxonomy Classification 28', 'severity': 'S3-Major', 'priority': 'P2', 'resolution_sla': '48 Hours', 'escape_phase': 'Staging Quality Gate', 'root_cause': 'Logic Defect / Race Condition / Schema Drift', 'retest_required': True},
    {'id': 'DEFECT-029', 'title': 'Defect Taxonomy Classification 29', 'severity': 'S3-Major', 'priority': 'P2', 'resolution_sla': '48 Hours', 'escape_phase': 'Staging Quality Gate', 'root_cause': 'Logic Defect / Race Condition / Schema Drift', 'retest_required': True},
    {'id': 'DEFECT-030', 'title': 'Defect Taxonomy Classification 30', 'severity': 'S3-Major', 'priority': 'P2', 'resolution_sla': '48 Hours', 'escape_phase': 'Staging Quality Gate', 'root_cause': 'Logic Defect / Race Condition / Schema Drift', 'retest_required': True},
    {'id': 'DEFECT-031', 'title': 'Defect Taxonomy Classification 31', 'severity': 'S3-Major', 'priority': 'P2', 'resolution_sla': '48 Hours', 'escape_phase': 'Staging Quality Gate', 'root_cause': 'Logic Defect / Race Condition / Schema Drift', 'retest_required': True},
    {'id': 'DEFECT-032', 'title': 'Defect Taxonomy Classification 32', 'severity': 'S3-Major', 'priority': 'P2', 'resolution_sla': '48 Hours', 'escape_phase': 'Staging Quality Gate', 'root_cause': 'Logic Defect / Race Condition / Schema Drift', 'retest_required': True},
    {'id': 'DEFECT-033', 'title': 'Defect Taxonomy Classification 33', 'severity': 'S3-Major', 'priority': 'P2', 'resolution_sla': '48 Hours', 'escape_phase': 'Staging Quality Gate', 'root_cause': 'Logic Defect / Race Condition / Schema Drift', 'retest_required': True},
    {'id': 'DEFECT-034', 'title': 'Defect Taxonomy Classification 34', 'severity': 'S3-Major', 'priority': 'P2', 'resolution_sla': '48 Hours', 'escape_phase': 'Staging Quality Gate', 'root_cause': 'Logic Defect / Race Condition / Schema Drift', 'retest_required': True},
    {'id': 'DEFECT-035', 'title': 'Defect Taxonomy Classification 35', 'severity': 'S3-Major', 'priority': 'P2', 'resolution_sla': '48 Hours', 'escape_phase': 'Staging Quality Gate', 'root_cause': 'Logic Defect / Race Condition / Schema Drift', 'retest_required': True},
    {'id': 'DEFECT-036', 'title': 'Defect Taxonomy Classification 36', 'severity': 'S3-Major', 'priority': 'P2', 'resolution_sla': '48 Hours', 'escape_phase': 'Staging Quality Gate', 'root_cause': 'Logic Defect / Race Condition / Schema Drift', 'retest_required': True},
    {'id': 'DEFECT-037', 'title': 'Defect Taxonomy Classification 37', 'severity': 'S3-Major', 'priority': 'P2', 'resolution_sla': '48 Hours', 'escape_phase': 'Staging Quality Gate', 'root_cause': 'Logic Defect / Race Condition / Schema Drift', 'retest_required': True},
    {'id': 'DEFECT-038', 'title': 'Defect Taxonomy Classification 38', 'severity': 'S3-Major', 'priority': 'P2', 'resolution_sla': '48 Hours', 'escape_phase': 'Staging Quality Gate', 'root_cause': 'Logic Defect / Race Condition / Schema Drift', 'retest_required': True},
    {'id': 'DEFECT-039', 'title': 'Defect Taxonomy Classification 39', 'severity': 'S3-Major', 'priority': 'P2', 'resolution_sla': '48 Hours', 'escape_phase': 'Staging Quality Gate', 'root_cause': 'Logic Defect / Race Condition / Schema Drift', 'retest_required': True},
    {'id': 'DEFECT-040', 'title': 'Defect Taxonomy Classification 40', 'severity': 'S3-Major', 'priority': 'P2', 'resolution_sla': '48 Hours', 'escape_phase': 'Staging Quality Gate', 'root_cause': 'Logic Defect / Race Condition / Schema Drift', 'retest_required': True},
    {'id': 'DEFECT-041', 'title': 'Defect Taxonomy Classification 41', 'severity': 'S4-Minor', 'priority': 'P3', 'resolution_sla': '5 Days', 'escape_phase': 'Staging Quality Gate', 'root_cause': 'Logic Defect / Race Condition / Schema Drift', 'retest_required': True},
    {'id': 'DEFECT-042', 'title': 'Defect Taxonomy Classification 42', 'severity': 'S4-Minor', 'priority': 'P3', 'resolution_sla': '5 Days', 'escape_phase': 'Staging Quality Gate', 'root_cause': 'Logic Defect / Race Condition / Schema Drift', 'retest_required': True},
    {'id': 'DEFECT-043', 'title': 'Defect Taxonomy Classification 43', 'severity': 'S4-Minor', 'priority': 'P3', 'resolution_sla': '5 Days', 'escape_phase': 'Staging Quality Gate', 'root_cause': 'Logic Defect / Race Condition / Schema Drift', 'retest_required': True},
    {'id': 'DEFECT-044', 'title': 'Defect Taxonomy Classification 44', 'severity': 'S4-Minor', 'priority': 'P3', 'resolution_sla': '5 Days', 'escape_phase': 'Staging Quality Gate', 'root_cause': 'Logic Defect / Race Condition / Schema Drift', 'retest_required': True},
    {'id': 'DEFECT-045', 'title': 'Defect Taxonomy Classification 45', 'severity': 'S4-Minor', 'priority': 'P3', 'resolution_sla': '5 Days', 'escape_phase': 'Staging Quality Gate', 'root_cause': 'Logic Defect / Race Condition / Schema Drift', 'retest_required': True},
    {'id': 'DEFECT-046', 'title': 'Defect Taxonomy Classification 46', 'severity': 'S4-Minor', 'priority': 'P3', 'resolution_sla': '5 Days', 'escape_phase': 'Staging Quality Gate', 'root_cause': 'Logic Defect / Race Condition / Schema Drift', 'retest_required': True},
    {'id': 'DEFECT-047', 'title': 'Defect Taxonomy Classification 47', 'severity': 'S4-Minor', 'priority': 'P3', 'resolution_sla': '5 Days', 'escape_phase': 'Staging Quality Gate', 'root_cause': 'Logic Defect / Race Condition / Schema Drift', 'retest_required': True},
    {'id': 'DEFECT-048', 'title': 'Defect Taxonomy Classification 48', 'severity': 'S4-Minor', 'priority': 'P3', 'resolution_sla': '5 Days', 'escape_phase': 'Staging Quality Gate', 'root_cause': 'Logic Defect / Race Condition / Schema Drift', 'retest_required': True},
    {'id': 'DEFECT-049', 'title': 'Defect Taxonomy Classification 49', 'severity': 'S4-Minor', 'priority': 'P3', 'resolution_sla': '5 Days', 'escape_phase': 'Staging Quality Gate', 'root_cause': 'Logic Defect / Race Condition / Schema Drift', 'retest_required': True},
    {'id': 'DEFECT-050', 'title': 'Defect Taxonomy Classification 50', 'severity': 'S4-Minor', 'priority': 'P3', 'resolution_sla': '5 Days', 'escape_phase': 'Staging Quality Gate', 'root_cause': 'Logic Defect / Race Condition / Schema Drift', 'retest_required': True},
]

QUALITY_GATES = [
    {'id': 'QG-001', 'title': 'Quality Gate Rule 1', 'environment': 'CI / Commit', 'decision_type': 'GO / NO-GO', 'enforcement': 'Strict Zero Bypass', 'threshold': '100% Pass Rate', 'automated': True},
    {'id': 'QG-002', 'title': 'Quality Gate Rule 2', 'environment': 'CI / Commit', 'decision_type': 'GO / NO-GO', 'enforcement': 'Strict Zero Bypass', 'threshold': '100% Pass Rate', 'automated': True},
    {'id': 'QG-003', 'title': 'Quality Gate Rule 3', 'environment': 'CI / Commit', 'decision_type': 'GO / NO-GO', 'enforcement': 'Strict Zero Bypass', 'threshold': '100% Pass Rate', 'automated': True},
    {'id': 'QG-004', 'title': 'Quality Gate Rule 4', 'environment': 'CI / Commit', 'decision_type': 'GO / NO-GO', 'enforcement': 'Strict Zero Bypass', 'threshold': '100% Pass Rate', 'automated': True},
    {'id': 'QG-005', 'title': 'Quality Gate Rule 5', 'environment': 'CI / Commit', 'decision_type': 'GO / NO-GO', 'enforcement': 'Strict Zero Bypass', 'threshold': '100% Pass Rate', 'automated': True},
    {'id': 'QG-006', 'title': 'Quality Gate Rule 6', 'environment': 'CI / Commit', 'decision_type': 'GO / NO-GO', 'enforcement': 'Strict Zero Bypass', 'threshold': '100% Pass Rate', 'automated': True},
    {'id': 'QG-007', 'title': 'Quality Gate Rule 7', 'environment': 'CI / Commit', 'decision_type': 'GO / NO-GO', 'enforcement': 'Strict Zero Bypass', 'threshold': '100% Pass Rate', 'automated': True},
    {'id': 'QG-008', 'title': 'Quality Gate Rule 8', 'environment': 'CI / Commit', 'decision_type': 'GO / NO-GO', 'enforcement': 'Strict Zero Bypass', 'threshold': '100% Pass Rate', 'automated': True},
    {'id': 'QG-009', 'title': 'Quality Gate Rule 9', 'environment': 'CI / Commit', 'decision_type': 'GO / NO-GO', 'enforcement': 'Strict Zero Bypass', 'threshold': '100% Pass Rate', 'automated': True},
    {'id': 'QG-010', 'title': 'Quality Gate Rule 10', 'environment': 'CI / Commit', 'decision_type': 'GO / NO-GO', 'enforcement': 'Strict Zero Bypass', 'threshold': '100% Pass Rate', 'automated': True},
    {'id': 'QG-011', 'title': 'Quality Gate Rule 11', 'environment': 'Nightly Build', 'decision_type': 'GO / NO-GO', 'enforcement': 'Strict Zero Bypass', 'threshold': '100% Pass Rate', 'automated': True},
    {'id': 'QG-012', 'title': 'Quality Gate Rule 12', 'environment': 'Nightly Build', 'decision_type': 'GO / NO-GO', 'enforcement': 'Strict Zero Bypass', 'threshold': '100% Pass Rate', 'automated': True},
    {'id': 'QG-013', 'title': 'Quality Gate Rule 13', 'environment': 'Nightly Build', 'decision_type': 'GO / NO-GO', 'enforcement': 'Strict Zero Bypass', 'threshold': '100% Pass Rate', 'automated': True},
    {'id': 'QG-014', 'title': 'Quality Gate Rule 14', 'environment': 'Nightly Build', 'decision_type': 'GO / NO-GO', 'enforcement': 'Strict Zero Bypass', 'threshold': '100% Pass Rate', 'automated': True},
    {'id': 'QG-015', 'title': 'Quality Gate Rule 15', 'environment': 'Nightly Build', 'decision_type': 'GO / NO-GO', 'enforcement': 'Strict Zero Bypass', 'threshold': '100% Pass Rate', 'automated': True},
    {'id': 'QG-016', 'title': 'Quality Gate Rule 16', 'environment': 'Nightly Build', 'decision_type': 'GO / NO-GO', 'enforcement': 'Strict Zero Bypass', 'threshold': '100% Pass Rate', 'automated': True},
    {'id': 'QG-017', 'title': 'Quality Gate Rule 17', 'environment': 'Nightly Build', 'decision_type': 'GO / NO-GO', 'enforcement': 'Strict Zero Bypass', 'threshold': '100% Pass Rate', 'automated': True},
    {'id': 'QG-018', 'title': 'Quality Gate Rule 18', 'environment': 'Nightly Build', 'decision_type': 'GO / NO-GO', 'enforcement': 'Strict Zero Bypass', 'threshold': '100% Pass Rate', 'automated': True},
    {'id': 'QG-019', 'title': 'Quality Gate Rule 19', 'environment': 'Nightly Build', 'decision_type': 'GO / NO-GO', 'enforcement': 'Strict Zero Bypass', 'threshold': '100% Pass Rate', 'automated': True},
    {'id': 'QG-020', 'title': 'Quality Gate Rule 20', 'environment': 'Nightly Build', 'decision_type': 'GO / NO-GO', 'enforcement': 'Strict Zero Bypass', 'threshold': '100% Pass Rate', 'automated': True},
    {'id': 'QG-021', 'title': 'Quality Gate Rule 21', 'environment': 'Staging Enclave', 'decision_type': 'GO / NO-GO', 'enforcement': 'Mandatory CISO / CMO Dual Signoff', 'threshold': '100% Pass Rate', 'automated': True},
    {'id': 'QG-022', 'title': 'Quality Gate Rule 22', 'environment': 'Staging Enclave', 'decision_type': 'GO / NO-GO', 'enforcement': 'Mandatory CISO / CMO Dual Signoff', 'threshold': '100% Pass Rate', 'automated': True},
    {'id': 'QG-023', 'title': 'Quality Gate Rule 23', 'environment': 'Staging Enclave', 'decision_type': 'GO / NO-GO', 'enforcement': 'Mandatory CISO / CMO Dual Signoff', 'threshold': '100% Pass Rate', 'automated': True},
    {'id': 'QG-024', 'title': 'Quality Gate Rule 24', 'environment': 'Staging Enclave', 'decision_type': 'GO / NO-GO', 'enforcement': 'Mandatory CISO / CMO Dual Signoff', 'threshold': '100% Pass Rate', 'automated': True},
    {'id': 'QG-025', 'title': 'Quality Gate Rule 25', 'environment': 'Staging Enclave', 'decision_type': 'GO / NO-GO', 'enforcement': 'Mandatory CISO / CMO Dual Signoff', 'threshold': '100% Pass Rate', 'automated': True},
    {'id': 'QG-026', 'title': 'Quality Gate Rule 26', 'environment': 'Staging Enclave', 'decision_type': 'GO / NO-GO', 'enforcement': 'Mandatory CISO / CMO Dual Signoff', 'threshold': '100% Pass Rate', 'automated': True},
    {'id': 'QG-027', 'title': 'Quality Gate Rule 27', 'environment': 'Staging Enclave', 'decision_type': 'GO / NO-GO', 'enforcement': 'Mandatory CISO / CMO Dual Signoff', 'threshold': '100% Pass Rate', 'automated': True},
    {'id': 'QG-028', 'title': 'Quality Gate Rule 28', 'environment': 'Staging Enclave', 'decision_type': 'GO / NO-GO', 'enforcement': 'Mandatory CISO / CMO Dual Signoff', 'threshold': '100% Pass Rate', 'automated': True},
    {'id': 'QG-029', 'title': 'Quality Gate Rule 29', 'environment': 'Staging Enclave', 'decision_type': 'GO / NO-GO', 'enforcement': 'Mandatory CISO / CMO Dual Signoff', 'threshold': '100% Pass Rate', 'automated': True},
    {'id': 'QG-030', 'title': 'Quality Gate Rule 30', 'environment': 'Staging Enclave', 'decision_type': 'GO / NO-GO', 'enforcement': 'Mandatory CISO / CMO Dual Signoff', 'threshold': '100% Pass Rate', 'automated': True},
    {'id': 'QG-031', 'title': 'Quality Gate Rule 31', 'environment': 'Release Candidate', 'decision_type': 'GO / NO-GO', 'enforcement': 'Mandatory CISO / CMO Dual Signoff', 'threshold': '100% Pass Rate', 'automated': True},
    {'id': 'QG-032', 'title': 'Quality Gate Rule 32', 'environment': 'Release Candidate', 'decision_type': 'GO / NO-GO', 'enforcement': 'Mandatory CISO / CMO Dual Signoff', 'threshold': '100% Pass Rate', 'automated': True},
    {'id': 'QG-033', 'title': 'Quality Gate Rule 33', 'environment': 'Release Candidate', 'decision_type': 'GO / NO-GO', 'enforcement': 'Mandatory CISO / CMO Dual Signoff', 'threshold': '100% Pass Rate', 'automated': True},
    {'id': 'QG-034', 'title': 'Quality Gate Rule 34', 'environment': 'Release Candidate', 'decision_type': 'GO / NO-GO', 'enforcement': 'Mandatory CISO / CMO Dual Signoff', 'threshold': '100% Pass Rate', 'automated': True},
    {'id': 'QG-035', 'title': 'Quality Gate Rule 35', 'environment': 'Release Candidate', 'decision_type': 'GO / NO-GO', 'enforcement': 'Mandatory CISO / CMO Dual Signoff', 'threshold': '100% Pass Rate', 'automated': True},
    {'id': 'QG-036', 'title': 'Quality Gate Rule 36', 'environment': 'Release Candidate', 'decision_type': 'GO / NO-GO', 'enforcement': 'Mandatory CISO / CMO Dual Signoff', 'threshold': '100% Pass Rate', 'automated': True},
    {'id': 'QG-037', 'title': 'Quality Gate Rule 37', 'environment': 'Release Candidate', 'decision_type': 'GO / NO-GO', 'enforcement': 'Mandatory CISO / CMO Dual Signoff', 'threshold': '100% Pass Rate', 'automated': True},
    {'id': 'QG-038', 'title': 'Quality Gate Rule 38', 'environment': 'Release Candidate', 'decision_type': 'GO / NO-GO', 'enforcement': 'Mandatory CISO / CMO Dual Signoff', 'threshold': '100% Pass Rate', 'automated': True},
    {'id': 'QG-039', 'title': 'Quality Gate Rule 39', 'environment': 'Release Candidate', 'decision_type': 'GO / NO-GO', 'enforcement': 'Mandatory CISO / CMO Dual Signoff', 'threshold': '100% Pass Rate', 'automated': True},
    {'id': 'QG-040', 'title': 'Quality Gate Rule 40', 'environment': 'Release Candidate', 'decision_type': 'GO / NO-GO', 'enforcement': 'Mandatory CISO / CMO Dual Signoff', 'threshold': '100% Pass Rate', 'automated': True},
]

ENVIRONMENT_CONFIGS = [
    {'id': 'ENV-001', 'name': 'Local Dev Docker', 'tier': 'Tier 1', 'isolation': 'VPC / Network Micro-segmented', 'data_strategy': 'Synthetic Masked Data Only'},
    {'id': 'ENV-002', 'name': 'Feature Branch Sandbox', 'tier': 'Tier 2', 'isolation': 'VPC / Network Micro-segmented', 'data_strategy': 'Synthetic Masked Data Only'},
    {'id': 'ENV-003', 'name': 'Microservice Integration', 'tier': 'Tier 3', 'isolation': 'VPC / Network Micro-segmented', 'data_strategy': 'Synthetic Masked Data Only'},
    {'id': 'ENV-004', 'name': 'QA Automated Testbed', 'tier': 'Tier 4', 'isolation': 'VPC / Network Micro-segmented', 'data_strategy': 'Synthetic Masked Data Only'},
    {'id': 'ENV-005', 'name': 'Staging Pre-Prod', 'tier': 'Tier 1', 'isolation': 'VPC / Network Micro-segmented', 'data_strategy': 'Synthetic Masked Data Only'},
    {'id': 'ENV-006', 'name': 'ABDM NHA Sandbox', 'tier': 'Tier 2', 'isolation': 'VPC / Network Micro-segmented', 'data_strategy': 'Synthetic Masked Data Only'},
    {'id': 'ENV-007', 'name': 'Performance Benchmark VPC', 'tier': 'Tier 3', 'isolation': 'VPC / Network Micro-segmented', 'data_strategy': 'Synthetic Masked Data Only'},
    {'id': 'ENV-008', 'name': 'Offline Clinic Hardware Rig', 'tier': 'Tier 4', 'isolation': 'VPC / Network Micro-segmented', 'data_strategy': 'Synthetic Masked Data Only'},
    {'id': 'ENV-009', 'name': 'UAT Clinician Lab', 'tier': 'Tier 1', 'isolation': 'VPC / Network Micro-segmented', 'data_strategy': 'Synthetic Masked Data Only'},
    {'id': 'ENV-010', 'name': 'Pilot Clinic Ward 12', 'tier': 'Tier 2', 'isolation': 'VPC / Network Micro-segmented', 'data_strategy': 'Synthetic Masked Data Only'},
    {'id': 'ENV-011', 'name': 'Pilot Clinic Ward 45', 'tier': 'Tier 3', 'isolation': 'VPC / Network Micro-segmented', 'data_strategy': 'Synthetic Masked Data Only'},
    {'id': 'ENV-012', 'name': 'Pilot Clinic Ward 88', 'tier': 'Tier 4', 'isolation': 'VPC / Network Micro-segmented', 'data_strategy': 'Synthetic Masked Data Only'},
    {'id': 'ENV-013', 'name': 'Pilot Clinic Ward 112', 'tier': 'Tier 1', 'isolation': 'VPC / Network Micro-segmented', 'data_strategy': 'Synthetic Masked Data Only'},
    {'id': 'ENV-014', 'name': 'Pilot Clinic Ward 150', 'tier': 'Tier 2', 'isolation': 'VPC / Network Micro-segmented', 'data_strategy': 'Synthetic Masked Data Only'},
    {'id': 'ENV-015', 'name': 'Disaster Recovery Standby', 'tier': 'Tier 3', 'isolation': 'VPC / Network Micro-segmented', 'data_strategy': 'Synthetic Masked Data Only'},
    {'id': 'ENV-016', 'name': 'Security Red Team Enclave', 'tier': 'Tier 4', 'isolation': 'VPC / Network Micro-segmented', 'data_strategy': 'Synthetic Masked Data Only'},
    {'id': 'ENV-017', 'name': 'Data Pipeline Staging', 'tier': 'Tier 1', 'isolation': 'VPC / Network Micro-segmented', 'data_strategy': 'Synthetic Masked Data Only'},
    {'id': 'ENV-018', 'name': 'Accessibility Lab', 'tier': 'Tier 2', 'isolation': 'VPC / Network Micro-segmented', 'data_strategy': 'Synthetic Masked Data Only'},
    {'id': 'ENV-019', 'name': 'Localization Staging', 'tier': 'Tier 3', 'isolation': 'VPC / Network Micro-segmented', 'data_strategy': 'Synthetic Masked Data Only'},
    {'id': 'ENV-020', 'name': 'Production Blue-Green', 'tier': 'Tier 4', 'isolation': 'VPC / Network Micro-segmented', 'data_strategy': 'Synthetic Masked Data Only'},
]

REGRESSION_SUITES = [
    {'id': 'REG-001', 'name': 'P0 Smoke Test Suite', 'cadence': 'Daily CI / Nightly', 'automated_pct': 95, 'blocker_threshold': 'Zero Failures Allowed'},
    {'id': 'REG-002', 'name': 'P1 Core Clinical Sanity', 'cadence': 'Daily CI / Nightly', 'automated_pct': 95, 'blocker_threshold': 'Zero Failures Allowed'},
    {'id': 'REG-003', 'name': 'Patient Registration & ABHA Reg', 'cadence': 'Daily CI / Nightly', 'automated_pct': 95, 'blocker_threshold': 'Zero Failures Allowed'},
    {'id': 'REG-004', 'name': 'Triage & Vitals Regression', 'cadence': 'Daily CI / Nightly', 'automated_pct': 95, 'blocker_threshold': 'Zero Failures Allowed'},
    {'id': 'REG-005', 'name': 'Doctor Consultation & Clinical Notes', 'cadence': 'Daily CI / Nightly', 'automated_pct': 95, 'blocker_threshold': 'Zero Failures Allowed'},
    {'id': 'REG-006', 'name': 'Prescription & Allergy Contraindications', 'cadence': 'Daily CI / Nightly', 'automated_pct': 95, 'blocker_threshold': 'Zero Failures Allowed'},
    {'id': 'REG-007', 'name': 'Pharmacy Dispensing & Inventory', 'cadence': 'Daily CI / Nightly', 'automated_pct': 95, 'blocker_threshold': 'Zero Failures Allowed'},
    {'id': 'REG-008', 'name': 'Lab Orders & PACS DICOM Bridge', 'cadence': 'Daily CI / Nightly', 'automated_pct': 95, 'blocker_threshold': 'Zero Failures Allowed'},
    {'id': 'REG-009', 'name': 'Referral Management Regression', 'cadence': 'Daily CI / Nightly', 'automated_pct': 95, 'blocker_threshold': 'Zero Failures Allowed'},
    {'id': 'REG-010', 'name': 'Offline Local Persistence Suite', 'cadence': 'Daily CI / Nightly', 'automated_pct': 95, 'blocker_threshold': 'Zero Failures Allowed'},
    {'id': 'REG-011', 'name': 'Sync Queue & Conflict Resolution', 'cadence': 'Daily CI / Nightly', 'automated_pct': 95, 'blocker_threshold': 'Zero Failures Allowed'},
    {'id': 'REG-012', 'name': 'ABDM M1/M2/M3 Federated Bridge', 'cadence': 'Daily CI / Nightly', 'automated_pct': 95, 'blocker_threshold': 'Zero Failures Allowed'},
    {'id': 'REG-013', 'name': 'RBAC & Role Transition Matrix', 'cadence': 'Daily CI / Nightly', 'automated_pct': 95, 'blocker_threshold': 'Zero Failures Allowed'},
    {'id': 'REG-014', 'name': 'Emergency Break-Glass Audit Suite', 'cadence': 'Daily CI / Nightly', 'automated_pct': 95, 'blocker_threshold': 'Zero Failures Allowed'},
    {'id': 'REG-015', 'name': 'Password & MFA Authentication', 'cadence': 'Daily CI / Nightly', 'automated_pct': 95, 'blocker_threshold': 'Zero Failures Allowed'},
    {'id': 'REG-016', 'name': 'API Contract Regression (OpenAPI)', 'cadence': 'Daily CI / Nightly', 'automated_pct': 95, 'blocker_threshold': 'Zero Failures Allowed'},
    {'id': 'REG-017', 'name': 'Database Schema Migration Integrity', 'cadence': 'Daily CI / Nightly', 'automated_pct': 95, 'blocker_threshold': 'Zero Failures Allowed'},
    {'id': 'REG-018', 'name': 'Thermal Receipt ESC/POS Spooling', 'cadence': 'Daily CI / Nightly', 'automated_pct': 95, 'blocker_threshold': 'Zero Failures Allowed'},
    {'id': 'REG-019', 'name': 'Barcode Scanner HID Input Suite', 'cadence': 'Daily CI / Nightly', 'automated_pct': 95, 'blocker_threshold': 'Zero Failures Allowed'},
    {'id': 'REG-020', 'name': 'WCAG 2.1 AA Accessibility Smoke', 'cadence': 'Daily CI / Nightly', 'automated_pct': 95, 'blocker_threshold': 'Zero Failures Allowed'},
    {'id': 'REG-021', 'name': 'Kannada Localization UI Regression', 'cadence': 'Daily CI / Nightly', 'automated_pct': 95, 'blocker_threshold': 'Zero Failures Allowed'},
    {'id': 'REG-022', 'name': 'Cold-Chain IoT Telemetry Guardrails', 'cadence': 'Daily CI / Nightly', 'automated_pct': 95, 'blocker_threshold': 'Zero Failures Allowed'},
    {'id': 'REG-023', 'name': 'High Concurrency OPD Spike Suite', 'cadence': 'Daily CI / Nightly', 'automated_pct': 95, 'blocker_threshold': 'Zero Failures Allowed'},
    {'id': 'REG-024', 'name': 'Soak & Memory Leak 24h Regression', 'cadence': 'Daily CI / Nightly', 'automated_pct': 95, 'blocker_threshold': 'Zero Failures Allowed'},
    {'id': 'REG-025', 'name': 'WORM Immutable Log Merkle Proofs', 'cadence': 'Daily CI / Nightly', 'automated_pct': 95, 'blocker_threshold': 'Zero Failures Allowed'},
    {'id': 'REG-026', 'name': 'Field Nurse Android Tablet MDM', 'cadence': 'Daily CI / Nightly', 'automated_pct': 95, 'blocker_threshold': 'Zero Failures Allowed'},
    {'id': 'REG-027', 'name': 'Cross-Clinic Transfer & Continuity', 'cadence': 'Daily CI / Nightly', 'automated_pct': 95, 'blocker_threshold': 'Zero Failures Allowed'},
    {'id': 'REG-028', 'name': 'Public Health Analytics Aggregations', 'cadence': 'Daily CI / Nightly', 'automated_pct': 95, 'blocker_threshold': 'Zero Failures Allowed'},
    {'id': 'REG-029', 'name': 'Citizen Portal Self-Service Reg', 'cadence': 'Daily CI / Nightly', 'automated_pct': 95, 'blocker_threshold': 'Zero Failures Allowed'},
    {'id': 'REG-030', 'name': 'Pre-Release Master Candidate Gate', 'cadence': 'Daily CI / Nightly', 'automated_pct': 95, 'blocker_threshold': 'Zero Failures Allowed'},
]
