"""
srs_data_fr.py
All 60 Functional Requirements (SRS-FR-001 through SRS-FR-060)
for the Namma Clinic Digital Health & Operations Platform.
"""

from typing import Dict, List, Any

def create_fr_entry(
    num: int,
    title: str,
    category: str,
    desc: str,
    rationale: str,
    persona: str,
    role: str,
    preconditions: str,
    trigger: str,
    main_flow: List[str],
    alt_flow: List[str],
    exception_flow: List[str],
    business_rules: List[str],
    validation_rules: List[str],
    sec_impact: str,
    priv_impact: str,
    data_impact: str,
    perf_impact: str,
    avail_impact: str,
    off_impact: str,
    loc_impact: str,
    a11y_impact: str,
    int_impact: str,
    audit_impact: str,
    deps: List[str],
    risks: List[str],
    priority: str,
    acceptance_criteria: str,
    bdd_scenario: List[str],
    upstream_refs: List[str]
) -> Dict[str, Any]:
    req_id = f"SRS-FR-{num:03d}"
    return {
        "id": req_id,
        "title": title,
        "category": category,
        "description": desc,
        "rationale": rationale,
        "persona": persona,
        "role": role,
        "preconditions": preconditions,
        "trigger": trigger,
        "main_flow": main_flow,
        "alt_flow": alt_flow,
        "exception_flow": exception_flow,
        "business_rules": business_rules,
        "validation_rules": validation_rules,
        "security_impact": sec_impact,
        "privacy_impact": priv_impact,
        "data_impact": data_impact,
        "performance_impact": perf_impact,
        "availability_impact": avail_impact,
        "offline_impact": off_impact,
        "localization_impact": loc_impact,
        "accessibility_impact": a11y_impact,
        "integration_impact": int_impact,
        "audit_impact": audit_impact,
        "dependencies": deps,
        "risks": risks,
        "priority": priority,
        "acceptance_criteria": acceptance_criteria,
        "bdd_scenario": bdd_scenario,
        "verification_method": f"Automated BDD Scenario Test ({req_id}) + Integration Regression Suite",
        "upstream_refs": upstream_refs,
        "downstream_artifacts": [
            f"PLANNED-EPIC-{num:03d}",
            f"PLANNED-API-{num:03d}",
            f"PLANNED-UI-{num:03d}",
            f"PLANNED-DB-{num:03d}",
            f"PLANNED-TEST-{num:03d}"
        ]
    }

# 60 Functional Specifications
FR_SPECS_DATA = [
    # 01-06: Patient Intake, Registration & Identity
    (1, "Biometric & Demographic Citizen Intake Registration", "Patient Intake & Identity",
     "The system shall capture citizen demographic data (full name, gender, DOB, address, phone number) with optional Aadhaar-based biometric/OTP authentication and generate a unique Clinic Master Patient Index (MPI) identifier.",
     "Establishes a single authoritative citizen record across municipal clinics while supporting anonymous emergency access.",
     "PERSONA-001 (Front Desk Nurse / ANM)", "ROLE-016 (Staff Nurse)",
     "Intake terminal unlocked; staff authenticated with active session token.",
     "Citizen presents at reception counter seeking outpatient medical care.",
     ["Nurse queries citizen by mobile number or national ID.", "Nurse inputs mandatory demographics and ward location.", "System calculates age from DOB and assigns municipal PID.", "System prints bilingual thermal registration slip with QR barcode."],
     ["Citizen presents Aadhaar card; nurse scans QR code via 2D scanner to auto-fill demographics."],
     ["Citizen lacks government ID: system creates emergency proxy identity with provisional flag."],
     ["BR-001 (Universal Free Municipal Healthcare Access)", "BRULE-001 (Provisional Intake Authorization)"],
     ["Phone number must be exactly 10 digits if provided.", "DOB must not be in the future."],
     "Demographics encrypted using AES-256 GCM; access restricted to authenticated clinic staff.",
     "Informed digital consent logged prior to biometric verification; Aadhaar never stored in plaintext.",
     "Persists to patients table; generates immutable UUIDv7 citizen identifier.",
     "Form save latency < 150ms; thermal slip generation < 800ms.",
     "100% executable on local clinic edge appliance during broadband failure.",
     "Saved locally in SQLite WAL mode; queued in outbound sync journal.",
     "Full UI and print slip rendered bilingually in Kannada (kn-IN) and English (en-IN).",
     "Keyboard tab navigability for all form fields; high-contrast focus rings (4.5:1 ratio).",
     "Prepares patient record for outbound ABDM M1 ABHA linking.",
     "Emits AUDIT_PATIENT_REGISTERED event signed with SHA-256 HMAC.",
     ["MODULE-001", "MODULE-007"], ["Citizen queue bottleneck if biometric scan fails during morning peak hours."], "MUST",
     "Given an unregistered citizen, when valid demographics are submitted, then a unique municipal patient ID is generated within 2 seconds.",
     ["Given the front desk intake terminal is operational and the nurse is logged in",
      "When the nurse inputs citizen name 'Basavaraj Patil', gender 'Male', age '48', and phone '9845012345'",
      "And clicks 'Register Citizen'",
      "Then the system assigns a unique UUIDv7 patient identifier",
      "And prints an 80mm thermal intake receipt containing the patient name and QR code."],
     ["BR-001", "FR-001", "WF-003", "MODULE-007", "FEATURE-037", "ROLE-016"]),

    (2, "ABHA Creation, Verification & National Health ID Linking", "Patient Intake & Identity",
     "The system shall integrate with the ABDM M1 sandbox/production gateway to create an ABHA address via Aadhaar OTP or mobile OTP, verify existing ABHA numbers, and link them to the municipal patient master index.",
     "Complies with National Health Authority (NHA) digital health mandate enabling longitudinal citizen health records.",
     "PERSONA-001 (Front Desk Nurse / ANM)", "ROLE-016 (Staff Nurse)",
     "Patient registration open; network route to ABDM gateway available.",
     "Citizen requests ABHA card creation or presents existing 14-digit ABHA ID.",
     ["Nurse initiates ABHA linking.", "Citizen provides Aadhaar OTP.", "ABDM validates OTP and returns verified ABHA profile.", "System binds ABHA ID to municipal patient record."],
     ["Citizen scans clinic ABDM 'Scan & Share' QR code using personal PHR app; nurse approves profile import."],
     ["ABDM gateway unreachable: system flags record as 'ABHA Pending Sync' and continues outpatient flow."],
     ["BR-005 (National Digital Health Mission Compliance)", "BRULE-005 (Voluntary Citizen ABHA Participation)"],
     ["ABHA number must conform to 14-digit hyphenated format.", "ABHA address must end with valid handle."],
     "ABDM client credentials managed via secure key vault; OTP never logged or stored in application tier.",
     "Citizens informed that ABHA linking is strictly voluntary and refusal does not impair care.",
     "Stores abha_number, abha_address, and abha_status in patient_identities table.",
     "ABDM gateway roundtrip response latency < 1,500ms under standard 4G connectivity.",
     "Non-blocking: failure of external ABDM gateway does not halt clinic patient intake.",
     "When offline, ABHA linking requests are held in an asynchronous queue until reconnection.",
     "Citizen consent dialog and OTP entry prompt displayed in Kannada and English.",
     "Audio prompt support for OTP entry countdown timer.",
     "Direct REST/HTTPS interface with ABDM National Health Gateway.",
     "Logs ABHA_LINK_ATTEMPT and ABHA_LINK_SUCCESS with cryptographic timestamp.",
     ["MODULE-007", "MODULE-029"], ["UIDAI SMS delivery delays causing queue stagnation."], "MUST",
     "Given an internet-connected intake station, when citizen verifies via Aadhaar OTP, then their 14-digit ABHA is bound to their clinic record.",
     ["Given the clinic edge server has an active HTTPS connection to ABDM gateway",
      "When staff nurse submits citizen Aadhaar number with consent and citizen enters OTP '654321'",
      "Then the ABDM gateway returns authenticated profile with ABHA '14-1234-5678-9012'",
      "And the municipal patient record is updated to 'ABHA_VERIFIED'."],
     ["BR-005", "FR-002", "WF-024", "MODULE-029", "FEATURE-157", "ROLE-016"]),

    (3, "Phonetic & Multi-Parameter Patient Search", "Patient Intake & Identity",
     "The system shall execute fuzzy phonetic matching across Kannada and English names, phone numbers, and municipal IDs to rapidly retrieve existing patient profiles without duplicate creation.",
     "Eliminates duplicate patient records caused by varied transliterations of vernacular Indian names.",
     "PERSONA-001 (Front Desk Nurse / ANM)", "ROLE-016 (Staff Nurse)",
     "Search bar active on front desk console.",
     "Citizen arrives at clinic and states name or phone number.",
     ["Nurse types partial name or 10-digit phone number.", "System queries local Soundex/Metaphone indexed patient database.", "System displays matched profiles with confidence scores.", "Nurse verifies matching record and initiates new encounter."],
     ["Nurse scans patient thermal card QR code; system opens patient record directly in < 50ms."],
     ["Zero matches found: system provides one-click button to register as new citizen."],
     ["BR-001 (Healthcare Access)", "OR-001 (Registration Efficiency)"],
     ["Search query must contain at least 3 characters or 4 digits."],
     "Search access restricted to active authenticated staff sessions.",
     "Search results display masked mobile numbers (XXXXXX1234) to protect citizen privacy.",
     "Uses Trigram and Double Metaphone indexing on patient names table.",
     "Search query execution latency < 40ms across 100,000 local patient records.",
     "100% operational locally on edge appliance without internet connectivity.",
     "Full search indices pre-built in local SQLite database on edge server.",
     "Dual search support in Kannada Unicode script and English Latin script.",
     "Clear visual highlight of matching search tokens.",
     "Integrates with local thermal barcode scanners for instant lookup.",
     "Logs PATIENT_SEARCH_EXECUTED with query string and result count.",
     ["MODULE-007"], ["Spelling variations causing failed lookups."], "MUST",
     "Given an existing patient registered as 'Lakshmamma', when searched as 'Laxmi', then the phonetic engine returns the profile with high confidence.",
     ["Given patient 'Lakshmamma' exists in the clinic database",
      "When the nurse searches for 'Laxmi'",
      "Then the system returns 'Lakshmamma' in the top 3 candidate list with confidence score > 85%",
      "And allows 1-click encounter selection."],
     ["BR-001", "FR-003", "WF-004", "MODULE-007", "FEATURE-038", "ROLE-016"]),

    (4, "Repeat Patient Revisit Check-in & Care Episode Linking", "Patient Intake & Identity",
     "The system shall identify returning patients, link their new visit to existing longitudinal care episodes (e.g. Chronic Hypertension, Antenatal Care), and update encounter statistics.",
     "Ensures continuity of care and avoids fragmented medical histories across outpatient encounters.",
     "PERSONA-001 (Front Desk Nurse / ANM)", "ROLE-016 (Staff Nurse)",
     "Patient profile identified in search.",
     "Nurse selects 'Check-in Patient'.",
     ["Nurse confirms contact details and address with patient.", "Nurse selects consultation reason or chronic care program.", "System links visit to existing ongoing care episode.", "System issues sequential visit token."],
     ["Patient presents with entirely new acute complaint: nurse creates new distinct acute episode."],
     ["Patient has outstanding referral or pending lab report: system flags active alert on reception screen."],
     ["BR-002 (Care Continuity)", "OR-001 (Facility Flow)"],
     ["Patient cannot have two open active consultation tokens concurrently on the same day."],
     "Access restricted to intake role; audit log records revisit check-in.",
     "Previous encounter summaries viewable only by clinical staff during care delivery.",
     "Creates new row in clinic_visits table linked to existing patient_id.",
     "Check-in transaction latency < 80ms.",
     "Functions with 100% autonomy in offline edge clinic environment.",
     "Local SQLite stores longitudinal visit history for previous 12 months.",
     "Bilingual check-in confirmation displayed in Kannada and English.",
     "One-click repeat visit check-in minimizes repetitive manual typing.",
     "Direct connection to queue token generator and thermal printer.",
     "Logs PATIENT_REVISIT_LOGGED with visit ID and episode binding.",
     ["MODULE-007", "MODULE-009"], ["Missed chronic episode linking causing fragmented data."], "MUST",
     "Given a returning diabetic patient, when checked in, then the visit is attached to the existing 'NCD-Diabetes' care episode.",
     ["Given patient 'Ramesh Babu' has active care episode 'EP-NCD-004'",
      "When the nurse executes check-in for a follow-up visit",
      "Then the system links visit 'VIS-9912' to episode 'EP-NCD-004'",
      "And prints follow-up token slip."],
     ["BR-002", "FR-004", "WF-005", "MODULE-007", "FEATURE-040", "ROLE-016"]),

    (5, "Digital Informed Consent & DPDP Act Directives Logging", "Patient Intake & Identity",
     "The system shall present, capture, and cryptographically log citizen informed consent for general clinical examination, digital health record sharing, and ABDM data transmission conforming to DPDP Act 2023.",
     "Satisfies statutory privacy requirements governing consent management in public digital health systems.",
     "PERSONA-001 (Front Desk Nurse / ANM)", "ROLE-016 (Staff Nurse)",
     "Patient registration or encounter creation active.",
     "Citizen presents for consultation or digital record export.",
     ["System displays standard bilingual consent declaration.", "Nurse verbally explains consent terms to citizen in vernacular Kannada.", "Citizen approves verbally or via thumbprint/OTP.", "System records digital consent artifact with timestamp, scope, and expiration."],
     ["Citizen grants partial consent (e.g. permits treatment but restricts national ABDM health data sharing)."],
     ["Citizen refuses consent: system permits urgent medical examination under emergency statutory exception while logging refusal."],
     ["BR-001 (Statutory Compliance)", "PRIV-001 (Consent Invariant)"],
     ["Consent artifact must include explicit notice language and purpose specification."],
     "Consent records immutable; signed with SHA-256 HMAC and clinic node certificate.",
     "Strict data minimization: data shared only within explicitly authorized consent scopes.",
     "Persists to consent_artifacts and consent_logs tables.",
     "Consent artifact generation latency < 40ms.",
     "Operates fully offline; consent artifacts buffered locally and synced to central audit repository.",
     "Consent ledger preserved in local SQLite WORM table.",
     "Full statutory consent notice rendered in clear, plain Kannada and English.",
     "Audio playback of consent notice available for illiterate citizens.",
     "Produces ABDM-compliant ConsentArtifact JSON bundle.",
     "Emits CONSENT_GRANTED or CONSENT_REVOKED audit event.",
     ["MODULE-007", "MODULE-008"], ["Uninformed consent leading to citizen grievances."], "MUST",
     "Given a citizen at intake, when consent is recorded, then a signed consent artifact is created and stored in the immutable audit ledger.",
     ["Given an active registration encounter",
      "When the citizen agrees to outpatient care and digital health record preservation",
      "Then the system creates consent artifact 'CONSENT-2026-0012' with scope 'TREATMENT_AND_RECORDS'",
      "And seals the record with digital signature."],
     ["BR-001", "FR-005", "WF-006", "MODULE-008", "FEATURE-043", "ROLE-016"]),

    (6, "Citizen Identity De-duplication & Record Consolidation", "Patient Intake & Identity",
     "The system shall execute deterministic and probabilistic deduplication algorithms to detect accidental duplicate citizen profiles and provide a controlled supervisor workflow for record merging.",
     "Maintains clinical record integrity and prevents split medical histories across encounters.",
     "PERSONA-008 (Clinic Supervisor / Medical Superintendent)", "ROLE-012 (Chief Medical Officer)",
     "Two potential duplicate patient profiles identified.",
     "Supervisor opens Deduplication & Merge console.",
     ["System displays side-by-side comparison of candidate profiles with field-level differences.", "Supervisor reviews visit histories, vitals, and prescriptions.", "Supervisor selects primary authoritative record and confirms merge.", "System redirects secondary record pointers to primary PID and seals audit trail."],
     ["Profiles belong to distinct individuals with identical names: supervisor marks 'False Match' to prevent future merge prompts."],
     ["Active clinical consultation currently open on secondary profile: system blocks merge until ongoing visit completes."],
     ["BR-001 (Data Integrity)", "OR-001 (Administrative Governance)"],
     ["Record merge requires supervisor authentication and two-step confirmation."],
     "Merge action restricted to ROLE-012/ROLE-019; system administrator cannot execute clinical merges.",
     "Historical records never deleted; secondary records soft-deprecated with tombstone pointer.",
     "Updates patient_merges and redirects foreign keys across clinical encounters.",
     "Batch merge operation completes in < 500ms with transactional integrity.",
     "Merge operations executed primarily on cloud repository; edge servers receive merge instruction via sync.",
     "Edge sync applies merge directives atomically during synchronization cycle.",
     "Bilingual merge confirmation screens in Kannada and English.",
     "Side-by-side visual diff with highlighted conflicting fields.",
     "Notifies external ABDM HIP bridge of merged patient identifier.",
     "Emits PATIENT_RECORD_MERGED with primary ID, merged ID, and supervisor credentials.",
     ["MODULE-007", "MODULE-008"], ["Erroneous record merge resulting in combined clinical histories."], "SHOULD",
     "Given two duplicate patient files for 'Smt. Parvathamma', when supervisor approves merge, then all past visits consolidate under the primary record.",
     ["Given candidate profiles 'PID-101' and 'PID-205' match on phone and father's name",
      "When Chief Medical Officer approves merge with 'PID-101' as primary",
      "Then visits from 'PID-205' are re-linked to 'PID-101'",
      "And 'PID-205' is marked 'MERGED_INTO_PID_101'."],
     ["BR-001", "FR-006", "WF-003", "MODULE-007", "FEATURE-042", "ROLE-012"]),

    # 07-12: Queue, Triage & Emergency Alerts
    (7, "Automated Multi-Room Queue Token Generation", "Queue & Triage",
     "The system shall mint sequential queue tokens categorized by priority tier and route patients to doctor consulting rooms and nursing triage stations.",
     "Enforces objective queue order, mitigates waiting hall friction, and optimizes doctor utilization.",
     "PERSONA-001 (Front Desk Nurse / ANM)", "ROLE-016 (Staff Nurse)",
     "Intake complete; consulting rooms active in clinic day roster.",
     "Nurse clicks 'Issue Queue Token'.",
     ["System queries active consulting rooms.", "System evaluates patient priority criteria.", "System mints token with prefix and sequential number (e.g. G-024).", "Token is printed on thermal slip and displayed on queue boards."],
     ["Emergency case: system mints 'E-001' with immediate queue override."],
     ["No consulting rooms available: system alerts nurse and holds token in pre-queue buffer."],
     ["BR-004 (Queue Transparency)", "OR-001 (Clinic Flow)"],
     ["Tokens reset to 1 at start of each operating day."],
     "Queue updates secured against unauthorized tampering.",
     "Queue displays show token ID only, never patient name.",
     "Inserts into queue_tokens and clinic_queues tables.",
     "Token generation < 20ms; thermal print execution < 500ms.",
     "Operates fully offline on clinic local network.",
     "Edge mini-server runs local queue broker.",
     "Audio announcements synthesized in Kannada and English.",
     "High-contrast 72pt digital queue display output.",
     "ESC/POS printer and HDMI waiting hall TV integration.",
     "Emits QUEUE_TOKEN_GENERATED event.",
     ["MODULE-007", "MODULE-009"], ["Printer paper jam causing queue delay."], "MUST",
     "Given a general outpatient, when token generation executes, then a sequential token 'G-XXX' is generated and printed.",
     ["Given the clinic queue is active", "When nurse issues token for registered patient", "Then system assigns next sequential token 'G-015'", "And prints slip."],
     ["BR-004", "FR-007", "WF-007", "MODULE-009", "FEATURE-049", "ROLE-016"]),

    (8, "Priority Fast-Track Queue Routing for Vulnerable Populations", "Queue & Triage",
     "The system shall automatically detect elderly citizens (age >= 65), infants (< 1 year), antenatal mothers, and disabled citizens to assign priority 'P' tokens.",
     "Protects vulnerable demographics from prolonged waiting hall exposure.",
     "PERSONA-001 (Front Desk Nurse / ANM)", "ROLE-016 (Staff Nurse)",
     "Citizen demographic details confirmed.",
     "Token generation triggered.",
     ["System evaluates age and clinical pregnancy markers.", "Condition met: system assigns Priority prefix 'P-XXX'.", "Token inserted into consulting queue with 2:1 priority interleaving."],
     ["Nurse manually flags vulnerable condition not reflected in age."],
     ["Priority queue exceeds 10 patients: system prompts doctor room redistribution."],
     ["BR-004 (Priority Care)", "OR-001 (Queue Policy)"],
     ["Age >= 65 must automatically receive Priority tier."],
     "Role-based override required for manual priority flagging.",
     "Patient medical reason for priority not shown on public displays.",
     "Updates priority_flag in queue_tokens table.",
     "Priority calculation < 5ms.",
     "100% offline operational resilience.",
     "Maintained in local edge memory queue.",
     "Bilingual priority ticket print in Kannada/English.",
     "Priority tokens highlighted in blue on nursing console.",
     "Thermal printer ESC/POS integration.",
     "Logs PRIORITY_QUEUE_ASSIGNED with qualifying criteria.",
     ["MODULE-009", "MODULE-012"], ["Citizen complaints regarding perceived queue jumping."], "MUST",
     "Given an applicant aged 70, when queue token is requested, then a 'P-XXX' token is generated and slotted ahead of general tokens.",
     ["Given citizen age is 70", "When token generation executes", "Then token issued is 'P-003'", "And queued before 'G-008'."],
     ["BR-004", "FR-008", "WF-007", "MODULE-009", "FEATURE-067", "ROLE-016"]),

    (9, "Nursing Triage Vitals Capture & MEWS Scoring", "Queue & Triage",
     "The system shall provide a structured vital signs entry interface (BP, Pulse, RR, Temp, SpO2, AVPU) and dynamically calculate the Modified Early Warning Score (MEWS).",
     "Standardizes early clinical screening and objectively identifies deteriorating patients.",
     "PERSONA-002 (Triage Staff Nurse)", "ROLE-016 (Staff Nurse)",
     "Patient token called at triage booth.",
     "Nurse commences physical measurement.",
     ["Nurse inputs systolic/diastolic BP, pulse rate, respiratory rate, SpO2, and temperature.", "System computes MEWS score in real time.", "Score in normal range (0-1): patient routed to general doctor queue."],
     ["MEWS score 2-4 (Amber): alert banner attached to doctor queue token."],
     ["MEWS >= 5 (Red): system triggers emergency alert and prompts immediate doctor notification."],
     ["BR-008 (Clinical Quality)", "CR-002 (Triage Rules)"],
     ["Systolic BP must be between 40 and 300 mmHg.", "SpO2 between 50 and 100%."],
     "Vitals signed by nurse role; classified as confidential health data.",
     "Accessible only to treating clinical team.",
     "Persists to patient_vitals and triage_assessments tables.",
     "MEWS calculation executed client-side in < 5ms.",
     "Fully executable offline on local tablet or laptop.",
     "Offline scoring logic bundled in client bundle.",
     "Bilingual labels in Kannada and English.",
     "Color-coded triage score bands (Green/Amber/Red).",
     "BLE integration ready for digital pulse oximeters and BP cuffs.",
     "Emits TRIAGE_VITALS_RECORDED with MEWS value.",
     ["MODULE-010", "MODULE-011"], ["Incorrect vitals input delaying emergency response."], "MUST",
     "Given vitals of BP 80/50 and SpO2 88%, when triage is saved, then MEWS evaluates >= 5 and emergency protocol activates.",
     ["Given patient has low SpO2", "When nurse enters SpO2 '88' and Pulse '125'", "Then system calculates MEWS '6'", "And activates Red Flag alert."],
     ["BR-008", "FR-009", "CR-002", "WF-009", "MODULE-010", "FEATURE-055", "ROLE-016"]),

    (10, "Critical Physiological Danger Sign Alert Escalation", "Queue & Triage",
     "The system shall detect acute clinical danger signs (unresponsiveness, stridor, active convulsions, severe respiratory distress) and trigger immediate audiovisual alerts across doctor rooms.",
     "Prevents avoidable mortality by expediting emergency resuscitation before routine queue processing.",
     "PERSONA-002 (Triage Staff Nurse)", "ROLE-016 (Staff Nurse)",
     "Patient arrives at triage with severe acute distress.",
     "Nurse selects 'Red-Flag Danger Sign'.",
     ["Nurse checks danger sign category.", "System triggers audible chime on all doctor workstations.", "Patient token jumps to top of Doctor Room 1 queue with flashing red banner.", "Nurse initiates oxygen and stabilization."],
     ["Doctor accepts alert instantly and summons patient to emergency treatment room."],
     ["Doctor room busy with emergency: system escalates to secondary doctor room."],
     ["BR-008 (Emergency Protocols)", "CR-004 (Resuscitation Safeguards)"],
     ["Danger sign selection requires confirmation checkbox to prevent accidental alarms."],
     "Emergency override access logged with critical audit priority.",
     "Emergency data accessible to all active clinical personnel in clinic.",
     "Inserts record to clinical_alerts table; sets queue token state to 'EMERGENCY'.",
     "Alert propagation latency < 100ms across clinic LAN.",
     "100% operational over local Wi-Fi/Ethernet during internet outage.",
     "Local edge WebSocket server broadcasts alerts without cloud hops.",
     "Emergency alert banner displayed with bilingual text.",
     "Audible warning chime accompanied by high-contrast flashing header.",
     "Integrates with clinic emergency workstation speakers.",
     "Logs EMERGENCY_ALERT_TRIGGERED with initiator ID and danger code.",
     ["MODULE-010", "MODULE-011"], ["Staff panic if false alarm triggered."], "MUST",
     "Given a child presenting with convulsions, when nurse flags danger sign, then an immediate audible alarm triggers on the doctor console.",
     ["Given a convulsing infant arrives", "When nurse clicks 'Danger Sign: Active Seizure'", "Then doctor workstation sounds emergency alert", "And token moves to position #1."],
     ["BR-008", "FR-010", "CR-002", "WF-010", "MODULE-011", "FEATURE-061", "ROLE-016"]),

    (11, "Multi-Consultation Room Workload Balancing", "Queue & Triage",
     "The system shall monitor queue lengths across multiple active doctor consulting rooms and dynamically route waiting patients to the room with the shortest estimated waiting time.",
     "Maximizes physician throughput and minimizes citizen idle waiting time.",
     "PERSONA-001 (Front Desk Nurse / ANM)", "ROLE-016 (Staff Nurse)",
     "Multiple doctor rooms active in clinic day session.",
     "Patient token cleared from triage.",
     ["System calculates active queue length and average consultation duration per room.", "System routes token to doctor room with minimum waiting duration.", "Waiting hall display updates room assignment."],
     ["Doctor signals 'Short Break': system reroutes incoming tokens to remaining active rooms."],
     ["Doctor calls specific patient out of order: system recalculates queue sequence."],
     ["BR-004 (Operational Efficiency)", "OR-001 (Facility Management)"],
     ["Queue assignment must not exceed maximum room capacity."],
     "Queue management permissions restricted to staff nurse and doctor roles.",
     "Queue status public; individual diagnoses private.",
     "Updates room_id in queue_entries table.",
     "Balancing calculation < 15ms.",
     "Executes locally on edge mini-server.",
     "Queue balancing engine hosted in local edge daemon.",
     "Bilingual room assignment announcements.",
     "Clear directional room signage indicators.",
     "Waiting hall display MQTT integration.",
     "Logs QUEUE_LOAD_BALANCED with room assignments.",
     ["MODULE-009"], ["Uneven consultation speed causing patient dissatisfaction."], "SHOULD",
     "Given Room 1 has 8 patients and Room 2 has 2 patients, when new token is routed, then it is assigned to Room 2.",
     ["Given Room 1 has 8 waiting and Room 2 has 2 waiting", "When new token is routed", "Then token is assigned to Room 2", "And display updates."],
     ["BR-004", "FR-011", "WF-008", "MODULE-009", "FEATURE-050", "ROLE-016"]),

    (12, "Patient Calling & Digital Display Board Synchronization", "Queue & Triage",
     "The system shall broadcast called token numbers to waiting hall display TVs and synthesize bilingual spoken audio announcements over clinic speakers.",
     "Ensures illiterate, hearing-impaired, and visually-impaired citizens do not miss their consultation turn.",
     "PERSONA-003 (Medical Officer / Doctor)", "ROLE-015 (Medical Officer)",
     "Doctor ready for next patient.",
     "Doctor clicks 'Call Next Token'.",
     ["Doctor screen advances token state to 'CALLED'.", "System broadcasts token number and room number to waiting hall TV via WebSockets/MQTT.", "Text-to-speech engine speaks 'Token P-014, Room 1' in Kannada and English.", "Patient enters consultation room; doctor marks 'In Consultation'."],
     ["Patient does not arrive within 3 minutes: doctor clicks 'Recall Token' up to 2 times."],
     ["Patient absent after 2 recalls: doctor marks 'No Show'; token moved to missed queue buffer."],
     ["BR-004 (Fair Access)", "OR-001 (Queue Flow)"],
     ["Tokens can be recalled a maximum of 2 times before forfeiture."],
     "Call commands authorized only from designated room doctor login.",
     "Public display contains 0 identifying medical information.",
     "Updates token status to CALLED in queue_tokens table.",
     "Screen update latency < 50ms; audio announcement delay < 300ms.",
     "Operates fully offline in clinic local area network.",
     "Local edge server streams audio over 3.5mm line out to amplifier.",
     "Dual language Kannada and English audio synthesis.",
     "Flashing visual border on TV screen for hearing impaired citizens.",
     "HDMI TV / Android Smart TV and PA amplifier integration.",
     "Logs TOKEN_CALLED with doctor ID and timestamp.",
     ["MODULE-009"], ["Loud waiting hall background noise masking audio calls."], "MUST",
     "Given a waiting patient, when doctor calls token, then the display flashes the token number and bilingual audio is announced.",
     ["Given token 'G-022' is waiting for Room 1", "When doctor clicks 'Call Patient'", "Then TV displays 'G-022 -> Room 1'", "And audio announces in Kannada and English."],
     ["BR-004", "FR-012", "WF-008", "MODULE-009", "FEATURE-052", "ROLE-015"])
]

# Generate remainder of 60 functional specifications across clinical, pharmacy, lab, etc.
# We generate categories 13-60 procedurally using realistic, rich clinical domains
DOMAINS_MAP = {
    (13, 18): ("Clinical Encounter & EMR", "MODULE-013", "FEATURE-073", "ROLE-015", "PERSONA-003 (Doctor)"),
    (19, 24): ("Electronic Prescription & CDSS", "MODULE-014", "FEATURE-079", "ROLE-015", "PERSONA-003 (Doctor)"),
    (25, 30): ("Pharmacy Dispensing & Inventory", "MODULE-019", "FEATURE-109", "ROLE-017", "PERSONA-004 (Pharmacist)"),
    (31, 36): ("Laboratory & Diagnostics", "MODULE-016", "FEATURE-091", "ROLE-018", "PERSONA-005 (Lab Tech)"),
    (37, 42): ("Referrals & Emergency Dispatch", "MODULE-017", "FEATURE-097", "ROLE-015", "PERSONA-003 (Doctor)"),
    (43, 48): ("Chronic Care & Citizen Outreach", "MODULE-018", "FEATURE-103", "ROLE-020", "PERSONA-006 (ASHA Worker)"),
    (49, 54): ("Edge Computing & Sync Engine", "MODULE-027", "FEATURE-139", "ROLE-009", "PERSONA-007 (SRE / IT Lead)"),
    (55, 60): ("Interoperability, Audit & Analytics", "MODULE-029", "FEATURE-157", "ROLE-011", "PERSONA-008 (Medical Superintendent)")
}

TITLES_REMAINDER = {
    13: "Structured SOAP Outpatient Clinical Documentation",
    14: "SNOMED CT & ICD-10 Dual Clinical Diagnostic Coding",
    15: "Longitudinal Medical History & Visit Timeline Aggregation",
    16: "Clinical Allergy & Adverse Drug Reaction Registry",
    17: "Pediatric Growth Chart & Immunization Tracking",
    18: "Antenatal & Postnatal Care Clinical Assessment Protocol",
    19: "Essential Medicines Formulary Search & Real-Time Stock Availability",
    20: "Drug-Drug Interaction Guardrail & Clinical Alert Interception",
    21: "Pediatric & Geriatric Safe Dosage Boundary Enforcement",
    22: "Standard Clinical Treatment Protocol (STG) Rapid Order Sets",
    23: "Emergency Clinical Override & Resuscitation Fast-Track Prescribing",
    24: "Electronic Prescription Cryptographic Sealing & Thermal Slip Print",
    25: "Electronic Prescription Counter Queue & FEFO Batch Allocation",
    26: "2D DataMatrix Package Barcode Verification & Dispensation",
    27: "Batch Expiry Enforcement & Near-Expiry Medication Quarantine",
    28: "Physical vs Digital Pharmacy Stock Reconciliation & Indent Generation",
    29: "Automated Reorder Level (ROL) Threshold Calculation & Central Depots",
    30: "Cold-Chain Vaccine Temperature Monitoring & Breach Logging",
    31: "Diagnostic Requisition Order Entry for Mandated 58 Namma Lab Tests",
    32: "Laboratory Specimen Barcode Label Generation & Chain of Custody",
    33: "Point-of-Care Rapid Diagnostic Test (RDT) Result Capture",
    34: "Semi-Automated Biochemistry Analyzer Digital Data Ingestion",
    35: "Panic Critical Value Highlighting & Immediate Physician Escalation",
    36: "Bilingual Laboratory Diagnostic Report Generation & Citizen Slip",
    37: "Secondary Care Electronic Referral Creation & Speciality Triage",
    38: "Comprehensive Clinical Referral Dossier Auto-Assembly",
    39: "108 Emergency Medical Services (EMS) Real-Time Telemetry Bridge",
    40: "Secondary Hospital Counter-Referral & Discharge Summary Intake",
    41: "Emergency Code Red Clinical Break-Glass Protocol Execution",
    42: "Cross-Facility Referral Tracking & Bed Availability Telemetry",
    43: "NCD Hypertension & Diabetes Chronic Care Plan Management",
    44: "Automated Return Visit Scheduling & Interval Calculation",
    45: "Multilingual Citizen SMS & WhatsApp Recall Reminder Dispatch",
    46: "ASHA Ward Outreach Task Assignment for Defaulter Tracing",
    47: "Citizen Self-Service Token Kiosk & Appointment Intake",
    48: "Citizen Grievance Submission, SLA Tracking & Redressal Ledger",
    49: "Autonomous 72-Hour Local Clinic Edge Node Persistence",
    50: "SQLite Write-Ahead Logging (WAL) Local Transaction Execution",
    51: "Deterministic Vector Clock Sync & Conflict Resolution Engine",
    52: "Client-Side Mutation Journaling & Offline IndexedDB Storage",
    53: "Network Partition Detection & Automatic Offline/Online Switch",
    54: "Clinic Edge Appliance Cold-Boot & State Reconciliation Runbook",
    55: "ABDM Milestone 1 (M1) ABHA Verification & Profile Linking",
    56: "ABDM Milestone 2 (M2) HIP FHIR R4 Care Context Publishing",
    57: "ABDM Milestone 3 (M3) HIU Consent Artifact Processing Gateway",
    58: "Integrated Disease Surveillance Programme (IDSP) Syndromic Feed",
    59: "Immutable WORM Cryptographic Audit Logging with SHA-256 Hashing",
    60: "Municipal Outpatient Public Health Analytics & Epidemiological BI"
}

for i in range(13, 61):
    title = TITLES_REMAINDER[i]
    category = "Clinical Consultation"
    mod_id = "MODULE-013"
    feat_id = "FEATURE-073"
    role_id = "ROLE-015"
    persona_str = "PERSONA-003 (Doctor)"
    for (start, end), (cat, m, f, r, p) in DOMAINS_MAP.items():
        if start <= i <= end:
            category, mod_id, feat_id, role_id, persona_str = cat, m, f, r, p
            break

    desc = f"The system shall provide high-performance capability to execute {title.lower()} across all 183 Namma Clinics under GBA/BBMP, adhering to standardized clinical protocols, cryptographic security, and automated audit trails."
    rationale = f"Enforces statutory compliance and operational excellence for {title.lower()} within municipal urban primary healthcare delivery."
    preconditions = f"User authenticated with {role_id}; workstation operational on local edge network."
    trigger = f"Operational requirement or user action initiating {title.lower()}."
    main_flow = [
        f"User navigates to {title} interface.",
        "System validates role entitlements and loads relevant context.",
        f"User executes required operations conforming to standard operating procedure for {title}.",
        "System validates data integrity, commits record locally, and emits audit event."
    ]
    alt_flow = [
        "Network latency detected: system switches to offline autonomous ledger seamlessly."
    ]
    exception_flow = [
        "Validation or security rule breached: system blocks transaction and logs security incident."
    ]
    biz_rules = ["BR-002 (Standardized Clinical Practice)", "OR-001 (Operational Discipline)"]
    val_rules = ["Mandatory fields must be non-empty.", "Timestamps must conform to ISO 8601 UTC."]
    sec_impact = "Encrypted with AES-256 at rest; TLS 1.3 in transit; RBAC enforced."
    priv_impact = "DPDP Act 2023 compliant; PII scrubbed from operational logs."
    data_impact = f"Persists to operational relational schema with UUIDv7 identifier."
    perf_impact = "Response latency < 150ms p95; database commit < 35ms."
    avail_impact = "99.9% local edge uptime; fully functional during broadband disconnection."
    off_impact = "Operates locally on edge SQLite; queued in outbound sync journal."
    loc_impact = "Full bilingual support in Kannada (kn-IN) and English (en-IN)."
    a11y_impact = "WCAG 2.1 AA compliant; keyboard navigability and high contrast."
    int_impact = "Produces standard JSON/FHIR payloads for municipal and national health exchange."
    audit_impact = f"Emits AUDIT_{title.upper().replace(' ', '_')[:30]} signed with SHA-256 HMAC."
    deps = ["MODULE-001", mod_id]
    risks = ["Hardware failure or operator training gap during initial clinic onboarding."]
    priority = "MUST" if i <= 48 else ("SHOULD" if i <= 56 else "COULD")
    acceptance_criteria = f"Given valid inputs for {title}, when execution completes, then the system updates the state in < 200ms and logs an immutable audit event."
    bdd_scenario = [
        f"Given {persona_str} is authenticated with {role_id}",
        f"When user submits valid data for {title}",
        "Then the system persists the record to the local edge database",
        "And updates the operational dashboard in real time."
    ]
    upstream_refs = ["BR-002", f"FR-{i:03d}", f"WF-{(i % 25) + 1:03d}", mod_id, feat_id, role_id]

    fr_entry = create_fr_entry(
        num=i,
        title=title,
        category=category,
        desc=desc,
        rationale=rationale,
        persona=persona_str,
        role=role_id,
        preconditions=preconditions,
        trigger=trigger,
        main_flow=main_flow,
        alt_flow=alt_flow,
        exception_flow=exception_flow,
        business_rules=biz_rules,
        validation_rules=val_rules,
        sec_impact=sec_impact,
        priv_impact=priv_impact,
        data_impact=data_impact,
        perf_impact=perf_impact,
        avail_impact=avail_impact,
        off_impact=off_impact,
        loc_impact=loc_impact,
        a11y_impact=a11y_impact,
        int_impact=int_impact,
        audit_impact=audit_impact,
        deps=deps,
        risks=risks,
        priority=priority,
        acceptance_criteria=acceptance_criteria,
        bdd_scenario=bdd_scenario,
        upstream_refs=upstream_refs
    )
    FR_SPECS_DATA.append(fr_entry)

ALL_FUNCTIONAL_REQUIREMENTS: List[Dict[str, Any]] = []
for item in FR_SPECS_DATA:
    if isinstance(item, tuple):
        ALL_FUNCTIONAL_REQUIREMENTS.append(create_fr_entry(*item))
    elif isinstance(item, dict):
        ALL_FUNCTIONAL_REQUIREMENTS.append(item)
