"""
gen_api_01_architecture.py
Generator for docs/08-api/01-api-architecture.md
Produces >= 2,200 substantive lines covering system API topology, gateways, lifecycles,
CQRS, resilience, health probes, and 9 mandatory Mermaid architecture diagrams.
"""

import sys
from pathlib import Path
PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from scripts.api.api_gen_common import write_api_doc, make_openapi_snippet, make_bdd_scenario
from scripts.api.api_core_data import API_ENDPOINTS, API_SCHEMAS, RATE_LIMIT_TIERS, API_DEPENDENCIES

def generate_doc():
    lines = []
    lines.append("# 🔌 API Specification: Enterprise API Architecture Blueprint")
    lines.append("## Namma Clinic Digital Health & Operations Platform")
    lines.append("**Document Code:** API-DOC-01 | **Status:** Authoritative Baseline | **Date:** September 2026")
    lines.append("> **Municipal Health Authority:** Greater Bengaluru Authority (GBA) / BBMP Health Department")
    lines.append("> **Compliance Framework:** National Digital Health Mission (ABDM), DPDP Act 2023, DISHA Guidelines")
    lines.append("> **Notice:** All code snippets contained herein are strictly **DOCUMENTATION-ONLY OPENAPI** or **DOCUMENTATION-ONLY EXAMPLE**. Zero application runtime code is executed in this phase.")
    lines.append("")
    lines.append("---")
    lines.append("")

    # 1. Executive Summary & Principles
    lines.append("## 1. Executive Summary & Core Architectural Principles")
    lines.append("")
    lines.append("The Namma Clinic API Architecture establishes the authoritative contract, protocol, and communication standards for interconnecting 183 primary healthcare clinics across the 8 municipal zones of Greater Bengaluru. The platform serves over 25,000 daily citizen outpatient visits, operating under a hybrid edge-cloud paradigm where frontline clinic operations must continue uninterrupted during wide-area network outages lasting up to 72 hours.")
    lines.append("")
    lines.append("### 1.1 Architectural Pillars")
    lines.append("The API tier is engineered around seven core principles:")
    lines.append("1. **Contract-First Development:** API contracts, schemas, and error definitions serve as the immutable technical contract between frontend touch-screen PWAs, edge mini-servers, cloud microservices, and external national registries (ABDM).")
    lines.append("2. **Resource-Oriented RESTful Semantics:** Uniform HTTP verbs, deterministic URI paths, standard status codes, and strict JSON:API envelopes govern all synchronous client-to-server interactions.")
    lines.append("3. **Command-Query Responsibility Segregation (CQRS):** Write operations (commands) are decoupled from high-throughput reporting and epidemiological surveillance queries, preserving transactional performance on primary relational databases while routing reads to optimized indexes or ClickHouse OLAP stores.")
    lines.append("4. **Zero-Trust Security & Least Privilege:** Every request is authenticated via RS256-signed JWTs, checked against fine-grained RBAC/ABAC policies, and verified against clinic facility context boundaries.")
    lines.append("5. **Autonomous Edge Resilience:** Clinic edge gateways expose identical local REST endpoints backed by SQLite WAL databases, enabling local intake, triage, consultation, and dispensing without internet connectivity.")
    lines.append("6. **Cryptographic WORM Auditability:** All state-changing mutations and sensitive citizen record reads emit immutable append-only audit events secured by HMAC SHA-256 hash chains complying with DPDP Act 2023 Section 8.")
    lines.append("7. **Standardized Observability:** Distributed request correlation IDs, W3C trace contexts, OpenTelemetry spans, and Prometheus RED metrics are uniformly propagated across all API boundaries.")
    lines.append("")

    # 2. System API Architecture Diagram
    lines.append("## 2. System API Architecture & System Context")
    lines.append("")
    lines.append("The API ecosystem spans four distinct network tiers: Clinic Frontline Edge Tier, Cloud Ingress Tier, Internal Core Domain Tier, and National/Municipal Integration Tier.")
    lines.append("")
    lines.append("```mermaid")
    lines.append("graph TB")
    lines.append("    subgraph FrontlineEdge[\"Clinic Frontline Workstation Tier\"]")
    lines.append("        UI1[\"Doctor Touchscreen PWA Shell\"]")
    lines.append("        UI2[\"Nurse / Triage PWA Tablet\"]")
    lines.append("        UI3[\"Pharmacy Dispensing PWA\"]")
    lines.append("        UI4[\"Front Desk Registration Kiosk\"]")
    lines.append("    end")
    lines.append("")
    lines.append("    subgraph EdgeMiniServer[\"Clinic Edge Appliance (Intel N100 Node)\"]")
    lines.append("        EdgeGW[\"Edge Local API Gateway\"]")
    lines.append("        EdgeSQLite[(\"Edge SQLite WAL Database\")]")
    lines.append("        EdgeSyncWorker[\"Edge Vector Clock Sync Worker\"]")
    lines.append("        EdgeMQTT[\"Local MQTT Queue Broker\"]")
    lines.append("    end")
    lines.append("")
    lines.append("    subgraph CloudIngress[\"Central Cloud Ingress Tier\"]")
    lines.append("        WAF[\"Cloud WAF & DDoS Shield\"]")
    lines.append("        CentralGW[\"Kong / Envoy Central API Gateway\"]")
    lines.append("        RedisCache[(\"Redis Cluster Token & Rate Cache\")]")
    lines.append("    end")
    lines.append("")
    lines.append("    subgraph CoreServices[\"Internal Microservice Domain Tier\"]")
    lines.append("        AuthSvc[\"IAM & Token Authority Service\"]")
    lines.append("        PatientSvc[\"Master Patient Index Service\"]")
    lines.append("        EncounterSvc[\"Clinical Consultation & EMR Service\"]")
    lines.append("        PharmSvc[\"Pharmacy & Stock Ledger Service\"]")
    lines.append("        AuditSvc[\"WORM Cryptographic Audit Service\"]")
    lines.append("    end")
    lines.append("")
    lines.append("    subgraph StorageTier[\"Cloud Persistence Tier\"]")
    lines.append("        CloudPG[(\"PostgreSQL 16 Multi-AZ Master\")]")
    lines.append("        ClickHouse[(\"ClickHouse Columnar Warehouse\")]")
    lines.append("    end")
    lines.append("")
    lines.append("    subgraph ExternalEcosystem[\"National & Municipal Integration Tier\"]")
    lines.append("        NHA[\"National Health Authority ABDM Grid\"]")
    lines.append("        BBMP[\"BBMP Municipal Command & Control Center\"]")
    lines.append("        SMS[\"CDAC / Telecom SMS Gateway\"]")
    lines.append("    end")
    lines.append("")
    lines.append("    UI1 --> EdgeGW")
    lines.append("    UI2 --> EdgeGW")
    lines.append("    UI3 --> EdgeGW")
    lines.append("    UI4 --> EdgeGW")
    lines.append("    EdgeGW --> EdgeSQLite")
    lines.append("    EdgeGW --> EdgeMQTT")
    lines.append("    EdgeSyncWorker -->|Bi-directional Sync| CentralGW")
    lines.append("    CentralGW --> WAF")
    lines.append("    CentralGW --> RedisCache")
    lines.append("    CentralGW --> AuthSvc")
    lines.append("    CentralGW --> PatientSvc")
    lines.append("    CentralGW --> EncounterSvc")
    lines.append("    CentralGW --> PharmSvc")
    lines.append("    CentralGW --> AuditSvc")
    lines.append("    AuthSvc --> CloudPG")
    lines.append("    PatientSvc --> CloudPG")
    lines.append("    EncounterSvc --> CloudPG")
    lines.append("    PharmSvc --> CloudPG")
    lines.append("    AuditSvc --> CloudPG")
    lines.append("    CoreServices --> ClickHouse")
    lines.append("    CoreServices --> NHA")
    lines.append("    CoreServices --> BBMP")
    lines.append("    CoreServices --> SMS")
    lines.append("```")
    lines.append("")

    # 3. API Gateway Architecture & Topology
    lines.append("## 3. Central Cloud API Gateway Topology")
    lines.append("")
    lines.append("The Central Cloud API Gateway acts as the unified reverse proxy, policy enforcement point (PEP), and traffic orchestrator for all external inbound traffic originating from clinic edge appliances, administrative consoles, and third-party integrations.")
    lines.append("")
    lines.append("```mermaid")
    lines.append("sequenceDiagram")
    lines.append("    autonumber")
    lines.append("    participant Client as Workstation PWA / Edge Gateway")
    lines.append("    participant WAF as Cloud WAF & DDoS Filter")
    lines.append("    participant Gateway as Central API Gateway")
    lines.append("    participant Redis as Redis Rate & Token Cache")
    lines.append("    participant Auth as IAM Auth Service")
    lines.append("    participant Service as Target Domain Microservice")
    lines.append("    participant Audit as WORM Audit Pipeline")
    lines.append("")
    lines.append("    Client->>WAF: HTTPS POST /api/v1/patients (TLS 1.3)")
    lines.append("    WAF->>Gateway: Forward Sanitized Ingress Request")
    lines.append("    Gateway->>Redis: Check Sliding-Window Rate Limit")
    lines.append("    alt Rate Limit Exceeded")
    lines.append("        Gateway-->>Client: HTTP 429 Too Many Requests (Retry-After)")
    lines.append("    else Quota Available")
    lines.append("        Gateway->>Gateway: Verify RS256 JWT Signature & Expiry")
    lines.append("        alt Invalid / Expired Token")
    lines.append("            Gateway-->>Client: HTTP 401 Unauthorized (ERR-AUTH-002)")
    lines.append("        else Valid Token")
    lines.append("            Gateway->>Gateway: Inject X-Correlation-ID & User Context")
    lines.append("            Gateway->>Service: Forward Authenticated Request (mTLS)")
    lines.append("            Service->>Service: Execute Domain Logic & DB Transaction")
    lines.append("            Service->>Audit: Async Publish Mutation Audit Log")
    lines.append("            Service-->>Gateway: Return HTTP 201 Created Payload")
    lines.append("            Gateway-->>Client: HTTP 201 Created (JSON:API Envelope)")
    lines.append("        end")
    lines.append("    end")
    lines.append("```")
    lines.append("")

    # 4. Request and Response Lifecycles
    lines.append("## 4. Comprehensive Request & Response Lifecycles")
    lines.append("")
    lines.append("Every HTTP transaction passing through the platform adheres to a deterministic 12-stage execution lifecycle:")
    lines.append("")
    lines.append("```mermaid")
    lines.append("stateDiagram-v2")
    lines.append("    [*] --> IngressTLS: 1. TLS 1.3 Handshake")
    lines.append("    IngressTLS --> HeaderSanitization: 2. Header & WAF Inspection")
    lines.append("    HeaderSanitization --> RateLimiter: 3. Token Bucket Rate Check")
    lines.append("    RateLimiter --> TokenValidation: 4. JWT Cryptographic Verification")
    lines.append("    TokenValidation --> FacilityContext: 5. Facility & Shift ABAC Guard")
    lines.append("    FacilityContext --> PayloadValidation: 6. JSON Schema Schema Validation")
    lines.append("    PayloadValidation --> IdempotencyCheck: 7. X-Idempotency-Key Deduplication")
    lines.append("    IdempotencyCheck --> BusinessRuleEngine: 8. Clinical & Business Rules")
    lines.append("    BusinessRuleEngine --> RelationalTransaction: 9. ACID PostgreSQL Transaction")
    lines.append("    RelationalTransaction --> AuditEmission: 10. Immutable WORM Audit Hook")
    lines.append("    AuditEmission --> ResponseEnvelope: 11. JSON:API Response Envelope Formatting")
    lines.append("    ResponseEnvelope --> [*]: 12. Client Delivery & Trace Completion")
    lines.append("```")
    lines.append("")

    # 5. Authentication & Authorization Lifecycle Diagrams
    lines.append("## 5. Authentication and Authorization Lifecycles")
    lines.append("")
    lines.append("Authentication validates who the actor is, while authorization enforces what the actor may execute in a specific clinic facility.")
    lines.append("")
    lines.append("### 5.1 Staff Authentication Flow")
    lines.append("```mermaid")
    lines.append("sequenceDiagram")
    lines.append("    autonumber")
    lines.append("    participant Staff as Clinic Doctor / Nurse")
    lines.append("    participant Terminal as Registered Tablet")
    lines.append("    participant AuthAPI as /api/v1/auth/login")
    lines.append("    participant Vault as HashiCorp Vault KMS")
    lines.append("    participant DB as Auth PostgreSQL")
    lines.append("")
    lines.append("    Staff->>Terminal: Enter Municipal ID & Password")
    lines.append("    Terminal->>AuthAPI: POST Credentials + Hardware Fingerprint")
    lines.append("    AuthAPI->>DB: Query User & Active Salt")
    lines.append("    AuthAPI->>AuthAPI: Compute Argon2id Hash Verification")
    lines.append("    alt Password Incorrect")
    lines.append("        AuthAPI->>DB: Increment Failed Counter (Lock at 5)")
    lines.append("        AuthAPI-->>Terminal: HTTP 401 Unauthorized (ERR-AUTH-001)")
    lines.append("    else Credentials Valid")
    lines.append("        AuthAPI->>Vault: Request RS256 Signature for Claims")
    lines.append("        Vault-->>AuthAPI: Return Signed JWT Access Token")
    lines.append("        AuthAPI->>DB: Insert User Session & Refresh Token")
    lines.append("        AuthAPI-->>Terminal: HTTP 200 OK (Access + Refresh Tokens)")
    lines.append("    end")
    lines.append("```")
    lines.append("")
    lines.append("### 5.2 Authorization Flow & ABAC Scoping")
    lines.append("```mermaid")
    lines.append("graph TD")
    lines.append("    Req[Incoming Ingress Request] --> Tkn[Extract JWT Bearer Token]")
    lines.append("    Tkn --> Sig[Verify RS256 Signature against JWKS]")
    lines.append("    Sig --> RoleCheck{Does User Role possess RBAC Permission?}")
    lines.append("    RoleCheck -->|No| Deny403[HTTP 403 Forbidden ERR-AUTH-006]")
    lines.append("    RoleCheck -->|Yes| FacCheck{Does Target Facility match User Facility Scope?}")
    lines.append("    FacCheck -->|No| Scope403[HTTP 403 Facility Scope Mismatch ERR-AUTH-007]")
    lines.append("    FacCheck -->|Yes| ShiftCheck{Is Staff Member actively Clocked-In to Shift?}")
    lines.append("    ShiftCheck -->|No| Shift403[HTTP 403 Shift Inactive]")
    lines.append("    ShiftCheck -->|Yes| ConsentCheck{Has Citizen granted Consent for this Record?}")
    lines.append("    ConsentCheck -->|No Consent| CheckBreakGlass{Is Break-Glass Emergency invoked?}")
    lines.append("    CheckBreakGlass -->|No| Consent403[HTTP 403 Privacy Restricted ERR-PATIENT-008]")
    lines.append("    CheckBreakGlass -->|Yes| AllowEmergency[Permit Access with Mandatory Audit]")
    lines.append("    ConsentCheck -->|Consent Valid| AllowStandard[Permit Standard Access]")
    lines.append("```")
    lines.append("")

    # 6. Synchronous, Asynchronous, and Integration Flows
    lines.append("## 6. Synchronous, Asynchronous, and External Integration Flows")
    lines.append("")
    lines.append("### 6.1 Synchronous Operational Command Flow")
    lines.append("Frontline clinical operations (vitals recording, prescribing, dispensing) require deterministic immediate consistency.")
    lines.append("")
    lines.append("```mermaid")
    lines.append("sequenceDiagram")
    lines.append("    autonumber")
    lines.append("    participant Doctor as Treating Physician")
    lines.append("    participant UI as Consultation PWA")
    lines.append("    participant API as /api/v1/prescriptions")
    lines.append("    participant CDSS as Formulary & CDSS Engine")
    lines.append("    participant DB as PostgreSQL Transaction")
    lines.append("")
    lines.append("    Doctor->>UI: Select Drugs & Finalize Prescription")
    lines.append("    UI->>API: POST /api/v1/prescriptions (Idempotency Key)")
    lines.append("    API->>CDSS: Evaluate Drug-Drug Interactions & Formulary")
    lines.append("    CDSS-->>API: Interactions Clear / Formulary Verified")
    lines.append("    API->>DB: BEGIN Transaction")
    lines.append("    API->>DB: Insert Prescription & Line Items")
    lines.append("    API->>DB: Commit Transaction")
    lines.append("    API-->>UI: HTTP 201 Created (Prescription ID)")
    lines.append("    UI-->>Doctor: Display Signed Prescription & Print Slip")
    lines.append("```")
    lines.append("")
    lines.append("### 6.2 Asynchronous Background Processing Flow")
    lines.append("Citizen notifications, data portability archives, and OLAP ETL feeds run via decoupled BullMQ background workers.")
    lines.append("")
    lines.append("```mermaid")
    lines.append("sequenceDiagram")
    lines.append("    autonumber")
    lines.append("    participant API as Prescription API")
    lines.append("    participant Queue as Redis BullMQ Job Queue")
    lines.append("    participant Worker as Notification Worker")
    lines.append("    participant Carrier as Telecom SMS Gateway (CDAC)")
    lines.append("    participant Citizen as Patient Mobile Phone")
    lines.append("")
    lines.append("    API->>Queue: Enqueue SMS Job (Patient ID, Regimen, Kannada)")
    lines.append("    API-->>API: Immediate Return to Clinician")
    lines.append("    Queue->>Worker: Consume Job from Notification Queue")
    lines.append("    Worker->>Worker: Render DLT Template in Kannada")
    lines.append("    Worker->>Carrier: POST /sms/send (HTTPS mTLS)")
    lines.append("    Carrier-->>Citizen: Deliver SMS Message")
    lines.append("    Carrier-->>Worker: HTTP 200 Delivery Receipt")
    lines.append("    Worker->>Queue: Acknowledge & Complete Job")
    lines.append("```")
    lines.append("")

    # 7. External Integration & Offline Sync Flow
    lines.append("## 7. External Integration & Autonomous Offline Synchronization")
    lines.append("")
    lines.append("### 7.1 ABDM Gateway Integration Architecture")
    lines.append("Integration with the Ayushman Bharat Digital Mission (ABDM) national grid facilitates health record sharing via FHIR R4 standard bundles.")
    lines.append("")
    lines.append("```mermaid")
    lines.append("sequenceDiagram")
    lines.append("    autonumber")
    lines.append("    participant Citizen as Citizen ABHA App")
    lines.append("    participant NHA as NHA ABDM Gateway")
    lines.append("    participant Bridge as Namma Clinic ABDM Bridge")
    lines.append("    participant DB as Clinic Encounters DB")
    lines.append("")
    lines.append("    Citizen->>NHA: Grant Consent to Share OPD Encounter")
    lines.append("    NHA->>Bridge: Webhook: POST /api/v1/abdm/consent/notification")
    lines.append("    Bridge-->>NHA: HTTP 202 Accepted (Correlation ID)")
    lines.append("    Bridge->>NHA: POST /v0.5/consents/fetch (Retrieve Artifact)")
    lines.append("    NHA-->>Bridge: Return Signed Consent Artifact")
    lines.append("    NHA->>Bridge: POST /api/v1/abdm/health-information/request")
    lines.append("    Bridge->>DB: Query Clinical Records for Patient")
    lines.append("    Bridge->>Bridge: Assemble FHIR R4 DiagnosticReport Bundle")
    lines.append("    Bridge->>NHA: POST /v0.5/health-information/notify (Encrypted Bundle)")
    lines.append("```")
    lines.append("")
    lines.append("### 7.2 Offline Edge Synchronization Flow")
    lines.append("When wide-area municipal network connectivity is severed, clinic edge nodes buffer mutations in an append-only journal and reconcile via vector clocks upon reconnection.")
    lines.append("")
    lines.append("```mermaid")
    lines.append("sequenceDiagram")
    lines.append("    autonumber")
    lines.append("    participant Tablet as Nurse Workstation Tablet")
    lines.append("    participant EdgeDB as Edge SQLite Mini-Server")
    lines.append("    participant SyncEngine as Edge Sync Agent")
    lines.append("    participant CloudAPI as Central Cloud Gateway")
    lines.append("    participant CloudDB as PostgreSQL Master")
    lines.append("")
    lines.append("    Note over Tablet,EdgeDB: WAN Network Offline (72-Hour Autonomous Edge Operation)")
    lines.append("    Tablet->>EdgeDB: POST /api/v1/triage (Insert Vitals into SQLite)")
    lines.append("    EdgeDB->>EdgeDB: Append Mutation to offline_mutation_log")
    lines.append("    Note over SyncEngine,CloudAPI: Municipal Network Restored")
    lines.append("    SyncEngine->>SyncEngine: Read Unreconciled Mutation Batch (Limit 100)")
    lines.append("    SyncEngine->>CloudAPI: POST /api/v1/system/sync/batch (Mutations + Vector Clock)")
    lines.append("    CloudAPI->>CloudDB: BEGIN Transaction")
    lines.append("    CloudAPI->>CloudDB: Execute Idempotent Upserts & Deduplication")
    lines.append("    CloudAPI->>CloudDB: Detect Conflicts (CRDT / Last-Write-Wins)")
    lines.append("    CloudAPI->>CloudDB: Commit Transaction")
    lines.append("    CloudAPI-->>SyncEngine: HTTP 200 OK (Reconciled IDs + Server Deltas)")
    lines.append("    SyncEngine->>EdgeDB: Mark Mutations Reconciled in Local Journal")
    lines.append("```")
    lines.append("")

    # 8. Health, Readiness, and Liveness Probe Standards
    lines.append("## 8. Platform Health, Readiness, and Dependency Probing Standards")
    lines.append("")
    lines.append("All microservices and edge gateways expose standardized health check endpoints conforming to Kubernetes probe specifications:")
    lines.append("- `/livez` (Liveness Probe): Verifies that process event loop is unblocked. Returns HTTP 200 OK immediately.")
    lines.append("- `/readyz` (Readiness Probe): Verifies that critical backing dependencies (PostgreSQL connection pool, Redis cache) are available and responsive.")
    lines.append("- `/healthz` (Comprehensive Health): Deep diagnostic inspection reporting database replication lag, disk space, and memory utilization.")
    lines.append("")
    lines.append("### 8.1 Readiness Probe Specification")
    snippet_lines = make_openapi_snippet("GET", "/readyz", "Kubernetes readiness dependency probe", ["SystemHealth"], resp_schema="HealthCheckReadinessResponse", status_codes=[200, 503])
    lines.extend(snippet_lines)
    lines.append("")

    # 9. BDD Architecture Acceptance Scenarios
    lines.append("## 9. Architectural Quality Acceptance Criteria (BDD)")
    lines.append("")
    bdd_1 = make_bdd_scenario(
        "Verify Edge Autonomous Operation during WAN Outage",
        ["a primary care Namma Clinic workstation operating under complete internet disconnect", "the local edge mini-server has an active SQLite WAL database"],
        "the staff nurse submits a vital signs triage assessment",
        ["the edge API gateway records the triage event in local SQLite", "a sequential token is assigned locally", "the mutation is queued in the local offline journal with a valid UUIDv7", "the user receives an HTTP 201 response within 200ms"]
    )
    lines.extend(bdd_1)
    lines.append("")

    bdd_2 = make_bdd_scenario(
        "Reject Ingress Request Exceeding Tier-01 Rate Limit",
        ["an anonymous client sending requests to /api/v1/auth/login", "the client has exceeded 10 requests within the rolling 60-second window"],
        "the client transmits an 11th login attempt",
        ["the API gateway intercepts the request prior to hitting the auth service", "returns HTTP 429 Too Many Requests", "includes standard Retry-After and RateLimit-Reset response headers", "records a rate limit security violation metric in Prometheus"]
    )
    lines.extend(bdd_2)
    lines.append("")

    # 10. Comprehensive Architecture Traceability Matrix
    lines.append("## 10. Comprehensive Architecture Traceability Matrix")
    lines.append("")
    lines.append("The following matrix maps architectural subsystems to upstream requirements, containers, database tables, and quality metrics:")
    lines.append("")
    lines.append("| Subsystem Code | Subsystem Name | Architecture Container | Primary Database Tables | Upstream Requirements | Verification Method |")
    lines.append("| :--- | :--- | :--- | :--- | :--- | :--- |")
    for ep in API_ENDPOINTS[:35]:
        tbls = ", ".join(ep["tables"]) if ep["tables"] else "system_configs"
        reqs = ", ".join(ep["upstream_reqs"])
        lines.append(f"| `{ep['id']}` | {ep['title']} | `{ep['container']}` | `{tbls}` | `{reqs}` | {ep['planned_test_id']} |")
    lines.append("")

    # 11. Endpoint Inventory Catalog
    lines.append("## 11. Architectural Endpoint Inventory Catalog")
    lines.append("")
    lines.append("Catalog of all 341 platform endpoints governed by this architectural baseline:")
    lines.append("")
    lines.append("| Endpoint ID | Method | Path | Domain | Role Context | Security Classification | Offline Support |")
    lines.append("| :--- | :--- | :--- | :--- | :--- | :--- | :--- |")
    for ep in API_ENDPOINTS:
        lines.append(f"| **{ep['id']}** | `{ep['method']}` | `{ep['path']}` | {ep['domain']} | `{ep['role']}` | `{ep['classification']}` | {ep['offline_support']} |")
    lines.append("")

    # 12. Detailed Subsystem Specifications & Deep Dive
    lines.append("## 12. Detailed Subsystem Architectural Deep-Dives")
    lines.append("")
    for i, ep in enumerate(API_ENDPOINTS[:25]):
        lines.append(f"### 12.{i+1} Subsystem Architecture: {ep['title']} (`{ep['id']}`)")
        lines.append(f"- **API Identifier:** `{ep['id']}`")
        lines.append(f"- **HTTP Route:** `{ep['method']} {ep['path']}`")
        lines.append(f"- **Functional Domain:** `{ep['domain']}`")
        lines.append(f"- **Authoritative Purpose:** {ep['purpose']}")
        lines.append(f"- **Assigned Container:** `{ep['container']}` | **Component:** `{ep['component']}`")
        lines.append(f"- **Database Persistence Target:** `{', '.join(ep['tables']) if ep['tables'] else 'In-Memory / Config'}`")
        lines.append(f"- **Security Classification:** `{ep['classification']}` | **Authentication:** `{ep['auth']}`")
        lines.append(f"- **RBAC Permission Token:** `{', '.join(ep['rbac_permissions']) if ep['rbac_permissions'] else 'Public / None'}`")
        lines.append(f"- **ABAC Scoping Rule:** {ep['abac_rules']}")
        lines.append(f"- **Rate Limit Policy:** {ep['rate_limit']}")
        lines.append(f"- **Idempotency Standard:** {ep['idempotency']}")
        lines.append(f"- **Execution Timeout:** {ep['timeout_ms']}ms")
        lines.append(f"- **Offline Autonomy Support:** {ep['offline_support']}")
        lines.append(f"- **WORM Audit Event:** `{ep['audit_event']}`")
        lines.append(f"- **Planned Verification Test:** `{ep['planned_test_id']}`")
        lines.append(f"- **Primary Error Codes:** `{', '.join(ep['error_ids'])}`")
        lines.append("")
        lines.append("#### Contract OpenAPI Specification")
        sub_snippet = make_openapi_snippet(ep["method"], ep["path"], ep["title"], [ep["domain"]], req_schema=ep["req_schema"], resp_schema=ep["resp_schema"], status_codes=ep["status_codes"])
        lines.extend(sub_snippet)
        lines.append("")

    # 13. Change Management & Review Log
    lines.append("## 13. Architecture Governance & Change Management Log")
    lines.append("")
    lines.append("| Revision | Date | Author / Role | Review Authority | Changes & Architectural Justification | Status |")
    lines.append("| :--- | :--- | :--- | :--- | :--- | :--- |")
    lines.append("| 1.0.0 | September 2026 | Chief Solution Architect | BBMP Health Directorate | Initial approved baseline establishing hybrid edge-cloud REST API architecture. | Approved |")
    lines.append("")

    content = "\n".join(lines)
    return write_api_doc("01-api-architecture.md", content)

if __name__ == "__main__":
    stats = generate_doc()
    print("Done 01-api-architecture.md:", stats)
