"""
db_audit_txns.py
Canonical definitions for:
- 30 Audit Entities & Events (AUDIT-ENTITY-001..030 & AUDIT-EVENT-001..030)
- 25 Critical Database Transaction Models (TXN-001 to TXN-025)
"""

import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parent.parent.parent))

from typing import List, Dict, Any

# -----------------------------------------------------------------------------
# 1. 30 AUDIT ENTITIES & EVENTS (AUDIT-ENTITY-001..030 & AUDIT-EVENT-001..030)
# -----------------------------------------------------------------------------
AUDIT_ENTITIES = [
    {"id": "AUDIT-ENTITY-001", "name": "UserAuthenticationCredential", "domain": "Identity & Access", "target_table": "user_credentials", "classification": "CLASS-005"},
    {"id": "AUDIT-ENTITY-002", "name": "UserSessionLifecycle", "domain": "Identity & Access", "target_table": "user_sessions", "classification": "CLASS-003"},
    {"id": "AUDIT-ENTITY-003", "name": "RbacRoleAssignment", "domain": "Role-Based Access Control", "target_table": "user_roles", "classification": "CLASS-002"},
    {"id": "AUDIT-ENTITY-004", "name": "FacilityOperationalState", "domain": "Facility Operations", "target_table": "facilities", "classification": "CLASS-001"},
    {"id": "AUDIT-ENTITY-005", "name": "SystemConfigurationParameter", "domain": "System Configuration", "target_table": "system_configs", "classification": "CLASS-002"},
    {"id": "AUDIT-ENTITY-006", "name": "PatientMasterDemographics", "domain": "Citizen Demographics", "target_table": "patients", "classification": "CLASS-004"},
    {"id": "AUDIT-ENTITY-007", "name": "PatientNationalIdentifierLinkage", "domain": "Citizen Demographics", "target_table": "patient_identifiers", "classification": "CLASS-004"},
    {"id": "AUDIT-ENTITY-008", "name": "CitizenConsentDirective", "domain": "Consent Management", "target_table": "consent_records", "classification": "CLASS-004"},
    {"id": "AUDIT-ENTITY-009", "name": "QueueTokenIssuance", "domain": "Queue Management", "target_table": "tokens", "classification": "CLASS-002"},
    {"id": "AUDIT-ENTITY-010", "name": "QueueStageMovement", "domain": "Queue Management", "target_table": "queue_entries", "classification": "CLASS-002"},
    {"id": "AUDIT-ENTITY-011", "name": "NurseTriageAcuityScore", "domain": "Clinical Triage", "target_table": "triage_assessments", "classification": "CLASS-003"},
    {"id": "AUDIT-ENTITY-012", "name": "PhysiologicalVitalsObservation", "domain": "Clinical Triage", "target_table": "patient_vitals", "classification": "CLASS-003"},
    {"id": "AUDIT-ENTITY-013", "name": "ClinicalDangerAlertTrigger", "domain": "Clinical Safety", "target_table": "danger_alerts", "classification": "CLASS-003"},
    {"id": "AUDIT-ENTITY-014", "name": "DoctorConsultationEncounter", "domain": "Clinical Consultation", "target_table": "clinical_encounters", "classification": "CLASS-003"},
    {"id": "AUDIT-ENTITY-015", "name": "ClinicalSoapNarrativeNote", "domain": "Clinical Consultation", "target_table": "clinical_notes", "classification": "CLASS-005"},
    {"id": "AUDIT-ENTITY-016", "name": "CodedDiagnosticFormulation", "domain": "Clinical Consultation", "target_table": "diagnoses", "classification": "CLASS-003"},
    {"id": "AUDIT-ENTITY-017", "name": "ElectronicPrescriptionIssuance", "domain": "Pharmacy & Prescribing", "target_table": "prescriptions", "classification": "CLASS-003"},
    {"id": "AUDIT-ENTITY-018", "name": "PrescriptionMedicationItem", "domain": "Pharmacy & Prescribing", "target_table": "prescription_items", "classification": "CLASS-003"},
    {"id": "AUDIT-ENTITY-019", "name": "DiagnosticLabOrderPlacement", "domain": "Diagnostic Services", "target_table": "lab_orders", "classification": "CLASS-003"},
    {"id": "AUDIT-ENTITY-020", "name": "PathologyLabResultVerification", "domain": "Diagnostic Services", "target_table": "lab_results", "classification": "CLASS-003"},
    {"id": "AUDIT-ENTITY-021", "name": "TeleconsultationSpecialistSession", "domain": "Telemedicine", "target_table": "teleconsultations", "classification": "CLASS-003"},
    {"id": "AUDIT-ENTITY-022", "name": "FormularyMasterCatalogChange", "domain": "Pharmaceutical Master", "target_table": "formulary_drugs", "classification": "CLASS-001"},
    {"id": "AUDIT-ENTITY-023", "name": "PharmaceuticalBatchInwardReceipt", "domain": "Inventory & Traceability", "target_table": "pharmacy_batches", "classification": "CLASS-002"},
    {"id": "AUDIT-ENTITY-024", "name": "MedicationDispensationHandover", "domain": "Pharmacy Operations", "target_table": "dispensations", "classification": "CLASS-003"},
    {"id": "AUDIT-ENTITY-025", "name": "DoubleEntryStockMovementAudit", "domain": "Inventory & Traceability", "target_table": "stock_movements", "classification": "CLASS-002"},
    {"id": "AUDIT-ENTITY-026", "name": "ClinicDrugIndentRequisition", "domain": "Supply Chain & Procurement", "target_table": "drug_indents", "classification": "CLASS-002"},
    {"id": "AUDIT-ENTITY-027", "name": "ColdChainThermalExcursionAlert", "domain": "Cold Chain & IoT", "target_table": "cold_chain_telemetry", "classification": "CLASS-002"},
    {"id": "AUDIT-ENTITY-028", "name": "HospitalReferralDossierTransfer", "domain": "Continuity of Care", "target_table": "referrals", "classification": "CLASS-003"},
    {"id": "AUDIT-ENTITY-029", "name": "SakalaCitizenGrievanceRecord", "domain": "Citizen Grievance & Feedback", "target_table": "grievances", "classification": "CLASS-002"},
    {"id": "AUDIT-ENTITY-030", "name": "EdgeOfflineMutationReconciliation", "domain": "Edge Offline Synchronization", "target_table": "offline_mutation_log", "classification": "CLASS-003"}
]

AUDIT_EVENTS = []
for idx, ae in enumerate(AUDIT_ENTITIES, start=1):
    ev_id = f"AUDIT-EVENT-{idx:03d}"
    AUDIT_EVENTS.append({
        "id": ev_id,
        "entity_id": ae["id"],
        "name": f"{ae['name']}.StateChange",
        "domain": ae["domain"],
        "target_table": ae["target_table"],
        "actor_type": "STAFF_CLINICAL" if "Clinical" in ae["domain"] else ("SYSTEM_DAEMON" if "Cold Chain" in ae["domain"] else "AUTHENTICATED_USER"),
        "action": "MUTATION_RECORDED",
        "resource_uri": f"/api/v1/{ae['target_table'].replace('_', '-')}/audit",
        "payload_captured": "JSONB diff with previous state hash, new state hash, and actor context",
        "pii_phi_implications": f"Subject to {ae['classification']} masking and encryption policies",
        "tamper_protection": "SHA-256 HMAC chained into immutable WORM audit ledger",
        "retention_rule": "RETENTION-006",
        "forensic_query": f"SELECT * FROM audit_events WHERE target_table = '{ae['target_table']}' AND event_timestamp BETWEEN $1 AND $2 ORDER BY event_timestamp DESC;"
    })

AUDIT_ENTITY_MAP = {e["id"]: e for e in AUDIT_ENTITIES}
AUDIT_EVENT_MAP = {e["id"]: e for e in AUDIT_EVENTS}

# -----------------------------------------------------------------------------
# 2. 25 DATABASE TRANSACTION MODELS (TXN-001 to TXN-025)
# -----------------------------------------------------------------------------
TRANSACTIONS = [
    {
        "id": "TXN-001",
        "name": "Staff Onboarding & Credential Initialization",
        "operation": "Atomic creation of staff user identity, Argon2id credentials, default facility assignment, and initial RBAC role mapping.",
        "tables": ["auth_users", "user_credentials", "user_roles", "staff_profiles", "audit_events"],
        "isolation": "SERIALIZABLE",
        "lock_strategy": "Pessimistic exclusive row lock on auth_users username/email unique constraint; transactional multi-table commit.",
        "ordering": "auth_users -> user_credentials -> staff_profiles -> user_roles -> audit_events",
        "idempotency": "Enforced via unique username/email blind index constraint and client-provided Idempotency-Key header.",
        "concurrency": "Low concurrent collision probability; serializable guarantees zero phantom role assignments.",
        "deadlock_risk": "Low. Fixed insertion sequence strictly enforced by user provisioning service.",
        "retry_behavior": "Exponential backoff: 3 retries (100ms, 250ms, 500ms) on serialization failure 40001.",
        "rollback_behavior": "Complete atomic rollback; zero orphaned credentials; security audit failure logged via isolated transaction.",
        "failure_scenarios": "Duplicate username conflict, invalid facility ID, weak password policy rejection.",
        "audit_event": "AUDIT-EVENT-001",
        "consistency": "Strict ACID consistency; no user exists without credentials and at least one facility role."
    },
    {
        "id": "TXN-002",
        "name": "User Session Authentication & Token Rotation",
        "operation": "Verification of Argon2id password hash, generation of cryptographic session record, invalidation of stale refresh tokens, and audit logging.",
        "tables": ["auth_users", "user_credentials", "user_sessions", "audit_events"],
        "isolation": "READ COMMITTED",
        "lock_strategy": "Row lock on user_credentials (SELECT FOR UPDATE) to update failed_login_count and lock state atomically.",
        "ordering": "auth_users -> user_credentials -> user_sessions -> audit_events",
        "idempotency": "Session generation creates new UUIDv7 session ID; refresh token reuse triggers immediate family revocation.",
        "concurrency": "High concurrency during morning staff shift login rush (08:30 - 09:15 IST).",
        "deadlock_risk": "Minimal. Lock is confined to single user row in user_credentials.",
        "retry_behavior": "2 retries with 50ms jitter on lock contention.",
        "rollback_behavior": "Failed login increments failed_login_count inside separate autonomous transaction.",
        "failure_scenarios": "Invalid password, account lockout threshold exceeded, expired credential.",
        "audit_event": "AUDIT-EVENT-002",
        "consistency": "ACID compliance; session is active only if credential checks pass."
    },
    {
        "id": "TXN-003",
        "name": "Patient Registration & Master Demographic Indexing",
        "operation": "Creation of master patient demographic profile, verification of national identifier tokens (ABHA/Aadhaar vault), contact details, and address records.",
        "tables": ["patients", "patient_identifiers", "patient_contacts", "patient_addresses", "audit_events"],
        "isolation": "READ COMMITTED",
        "lock_strategy": "Optimistic locking on existing patient record if updating; blind-index uniqueness check on phone and ABHA.",
        "ordering": "patients -> patient_identifiers -> patient_contacts -> patient_addresses -> audit_events",
        "idempotency": "Idempotent via deduplication hash of (phone_blind_index + dob + gender) and Idempotency-Key.",
        "concurrency": "High intake volume across 450 clinics; concurrent registrations operate on disjoint patient IDs.",
        "deadlock_risk": "Very low due to top-down hierarchical foreign key insertion order.",
        "retry_behavior": "3 retries with 100ms jitter on unique constraint race condition.",
        "rollback_behavior": "Atomic rollback on validation error; temporary registration discarded.",
        "failure_scenarios": "Duplicate active ABHA binding, invalid PIN code, malformed phone number.",
        "audit_event": "AUDIT-EVENT-006",
        "consistency": "Atomic consistency; patient cannot exist without at least one verified contact and address."
    },
    {
        "id": "TXN-004",
        "name": "Citizen DPDP Consent Execution & Artifact Ledgering",
        "operation": "Recording citizen explicit consent directives, scoping permitted clinical data uses, capturing OTP signature verification, and ledgering ABDM artifact.",
        "tables": ["consent_records", "abdm_artifacts", "audit_events"],
        "isolation": "REPEATABLE READ",
        "lock_strategy": "Shared lock on patient record; append-only insertion into consent_records.",
        "ordering": "consent_records -> abdm_artifacts -> audit_events",
        "idempotency": "Idempotent on (patient_id, consent_purpose, validity_start_time).",
        "concurrency": "Concurrent consent updates for same citizen serialized via patient_id lock.",
        "deadlock_risk": "None.",
        "retry_behavior": "3 retries with exponential backoff on serialization conflict.",
        "rollback_behavior": "Complete rollback; consent remains in previous state.",
        "failure_scenarios": "Expired OTP challenge token, patient identity mismatch, ABDM gateway timeout.",
        "audit_event": "AUDIT-EVENT-008",
        "consistency": "Strict ACID; clinical data sharing gated until consent transaction successfully commits."
    },
    {
        "id": "TXN-005",
        "name": "Daily Clinic Intake Token Generation",
        "operation": "Acquisition of clinic daily sequence lock, generation of sequential token number (e.g. A-042), and initial queue state creation.",
        "tables": ["tokens", "queue_entries", "audit_events"],
        "isolation": "READ COMMITTED",
        "lock_strategy": "Pessimistic PostgreSQL advisory lock on (facility_id, current_date) to guarantee gapless daily token sequence.",
        "ordering": "tokens -> queue_entries -> audit_events",
        "idempotency": "Idempotent per (facility_id, patient_id, current_date) preventing duplicate token issuance.",
        "concurrency": "High concurrency at clinic reception counter during morning peak (5-10 tokens/min/clinic).",
        "deadlock_risk": "Zero. Advisory lock key is ordered deterministically by facility_id.",
        "retry_behavior": "5 retries with 20ms jitter waiting for sequence lock release.",
        "rollback_behavior": "Atomic rollback releases advisory lock; sequence counter does not increment on failure.",
        "failure_scenarios": "Patient already holds active daily token, clinic closed status.",
        "audit_event": "AUDIT-EVENT-009",
        "consistency": "Sequential gapless ordering guaranteed per clinic per day."
    },
    {
        "id": "TXN-006",
        "name": "Queue Stage Movement & Consultation Station Handover",
        "operation": "Transitioning patient queue entry from TRIAGE to DOCTOR chamber, updating wait duration metrics, and broadcasting display screen update.",
        "tables": ["queue_entries", "facility_rooms", "audit_events"],
        "isolation": "READ COMMITTED",
        "lock_strategy": "Pessimistic row lock (SELECT FOR UPDATE) on specific queue_entries row.",
        "ordering": "queue_entries -> facility_rooms -> audit_events",
        "idempotency": "State machine transition guard: rejects transition if current state != expected previous state.",
        "concurrency": "Doctor station calling next patient while nurse completes triage.",
        "deadlock_risk": "Low. Single row lock on queue_entries.",
        "retry_behavior": "3 retries with 50ms backoff on lock contention.",
        "rollback_behavior": "Rollback preserves patient in current waiting queue stage.",
        "failure_scenarios": "Patient marked absent/left without being seen, chamber reassigned.",
        "audit_event": "AUDIT-EVENT-010",
        "consistency": "Exact state machine transition invariant: WAITING -> CALLED -> IN_PROGRESS -> COMPLETED."
    },
    {
        "id": "TXN-007",
        "name": "Nurse Triage Assessment & Vitals Recording",
        "operation": "Recording SATS triage category, pulse, blood pressure, SpO2, and evaluating danger alert thresholds atomically.",
        "tables": ["triage_assessments", "patient_vitals", "danger_alerts", "queue_entries", "audit_events"],
        "isolation": "READ COMMITTED",
        "lock_strategy": "Optimistic lock on queue_entries; append-only insertion on vitals and triage.",
        "ordering": "triage_assessments -> patient_vitals -> danger_alerts -> queue_entries -> audit_events",
        "idempotency": "Idempotent via (token_id, triage_stage) unique constraint.",
        "concurrency": "Single nurse operating on single patient triage intake session.",
        "deadlock_risk": "Low. Fixed table sequence.",
        "retry_behavior": "2 retries on database serialization error.",
        "rollback_behavior": "Complete rollback; vitals not saved if triage assessment fails validation.",
        "failure_scenarios": "Physiologically impossible vitals (e.g. Systolic BP < 30 or > 300), missing token.",
        "audit_event": "AUDIT-EVENT-011",
        "consistency": "Atomic consistency; if vitals exceed critical panic threshold, danger_alert record is guaranteed created in same transaction."
    },
    {
        "id": "TXN-008",
        "name": "Clinical Danger Alert Escalation & Notification Dispatch",
        "operation": "Automatic creation of critical clinical red flag alert, immediate doctor screen interruption flag, and SMS notification queueing.",
        "tables": ["danger_alerts", "notifications", "audit_events"],
        "isolation": "READ COMMITTED",
        "lock_strategy": "Append-only insert with immediate flush; no row locking on clinical records.",
        "ordering": "danger_alerts -> notifications -> audit_events",
        "idempotency": "De-duplicated within 5-minute window for same patient and danger rule.",
        "concurrency": "High priority emergency transaction executed asynchronously or synchronously during triage.",
        "deadlock_risk": "None.",
        "retry_behavior": "Immediate 3 retries on transient connection error.",
        "rollback_behavior": "Alert logged to fallback error queue if database commit fails.",
        "failure_scenarios": "SMS gateway outage (degrades gracefully to in-app alert).",
        "audit_event": "AUDIT-EVENT-013",
        "consistency": "Immediate persistence to enable doctor workstation WebSocket push notification."
    },
    {
        "id": "TXN-009",
        "name": "Doctor Clinical Consultation Sign-off & Order Generation",
        "operation": "Comprehensive consultation completion: writing SOAP clinical notes, ICD-10 diagnoses, encounter status update, and completing queue stage.",
        "tables": ["clinical_encounters", "clinical_notes", "diagnoses", "queue_entries", "audit_events"],
        "isolation": "READ COMMITTED",
        "lock_strategy": "Exclusive row lock on clinical_encounters (SELECT FOR UPDATE) to finalize status from IN_PROGRESS to SIGNED.",
        "ordering": "clinical_encounters -> clinical_notes -> diagnoses -> queue_entries -> audit_events",
        "idempotency": "Encounter status check ensures signed encounters cannot be re-signed or overwritten.",
        "concurrency": "Sole physician authoring encounter notes; zero concurrent doctor collision on same encounter.",
        "deadlock_risk": "Low. Consistent top-down table traversal.",
        "retry_behavior": "3 retries with 100ms exponential backoff.",
        "rollback_behavior": "Encounter remains in DRAFT state; unsaved notes returned to client for re-submission.",
        "failure_scenarios": "Invalid ICD-10 code, session expired during note writing, missing mandatory diagnosis.",
        "audit_event": "AUDIT-EVENT-014",
        "consistency": "Atomic clinical consultation; encounter cannot be marked SIGNED without at least one diagnosis and note."
    },
    {
        "id": "TXN-010",
        "name": "Electronic Prescription Issuance & Formulary Verification",
        "operation": "Generation of signed prescription header, insertion of validated drug line items, safety dosage verification, and pharmacy queue notification.",
        "tables": ["prescriptions", "prescription_items", "audit_events"],
        "isolation": "READ COMMITTED",
        "lock_strategy": "Shared read lock on formulary_drugs to verify active status and max dose limits.",
        "ordering": "prescriptions -> prescription_items -> audit_events",
        "idempotency": "Unique constraint on (encounter_id) ensures exactly one prescription header per consultation.",
        "concurrency": "Executed at conclusion of doctor consultation.",
        "deadlock_risk": "None.",
        "retry_behavior": "3 retries with 50ms backoff.",
        "rollback_behavior": "Prescription discarded atomically; doctor prompted to correct dosage violations.",
        "failure_scenarios": "Inactive formulary drug selected, prescribed dose exceeds lethal ceiling.",
        "audit_event": "AUDIT-EVENT-017",
        "consistency": "ACID compliance; prescription items must reference valid formulary entries."
    },
    {
        "id": "TXN-011",
        "name": "Diagnostic Laboratory Order Placement",
        "operation": "Creation of lab requisition order, test line items with LOINC codes, barcode requisition token generation, and sample collection queueing.",
        "tables": ["lab_orders", "lab_order_items", "queue_entries", "audit_events"],
        "isolation": "READ COMMITTED",
        "lock_strategy": "Append-only insertions into lab_orders and lab_order_items.",
        "ordering": "lab_orders -> lab_order_items -> queue_entries -> audit_events",
        "idempotency": "Idempotency-Key on order placement prevents duplicate lab requisitions.",
        "concurrency": "Ordered by physician during consultation.",
        "deadlock_risk": "None.",
        "retry_behavior": "3 retries on transient connection error.",
        "rollback_behavior": "Complete rollback; patient not queued for lab if order generation fails.",
        "failure_scenarios": "Test not supported at clinic diagnostic level, missing sample type.",
        "audit_event": "AUDIT-EVENT-019",
        "consistency": "Referential consistency; all lab items bound to active encounter."
    },
    {
        "id": "TXN-012",
        "name": "Diagnostic Laboratory Result Entry & Verification",
        "operation": "Entering observed lab values, checking biological panic thresholds, technician digital signature, and doctor result notification.",
        "tables": ["lab_order_items", "lab_results", "danger_alerts", "audit_events"],
        "isolation": "READ COMMITTED",
        "lock_strategy": "Pessimistic row lock on lab_order_items (SELECT FOR UPDATE) to update status to VERIFIED.",
        "ordering": "lab_order_items -> lab_results -> danger_alerts -> audit_events",
        "idempotency": "Unique constraint on order_item_id ensures single verified result per test item.",
        "concurrency": "Lab technician submitting batches of test results.",
        "deadlock_risk": "Low. Ordered by order_item_id.",
        "retry_behavior": "3 retries with 50ms backoff on lock contention.",
        "rollback_behavior": "Test remains in SAMPLE_COLLECTED state if result verification fails.",
        "failure_scenarios": "Negative value for strictly positive analyte, missing technician signature.",
        "audit_event": "AUDIT-EVENT-020",
        "consistency": "Atomic; panic lab values immediately trigger danger_alerts record."
    },
    {
        "id": "TXN-013",
        "name": "Teleconsultation Session Scheduling & Room Creation",
        "operation": "Booking WebRTC specialist room, linking clinical encounter, reserving specialist schedule slot, and citizen SMS notification.",
        "tables": ["teleconsultations", "notifications", "audit_events"],
        "isolation": "REPEATABLE READ",
        "lock_strategy": "Optimistic concurrency check on specialist calendar availability.",
        "ordering": "teleconsultations -> notifications -> audit_events",
        "idempotency": "Unique constraint on encounter_id in teleconsultations.",
        "concurrency": "Concurrent booking of specialist slots serialized at database level.",
        "deadlock_risk": "None.",
        "retry_behavior": "3 retries on serialization conflict.",
        "rollback_behavior": "Session room deleted; doctor notified of specialist unavailability.",
        "failure_scenarios": "Specialist schedule overlap, video bridge signaling failure.",
        "audit_event": "AUDIT-EVENT-021",
        "consistency": "ACID compliance; specialist cannot be double-booked for same time slice."
    },
    {
        "id": "TXN-014",
        "name": "Pharmaceutical Goods Inward Receipt & Batch Onboarding",
        "operation": "Receiving drug shipment from BBMP central warehouse, onboarding batch records, incrementing clinic stock, and writing stock movement ledger.",
        "tables": ["pharmacy_batches", "clinic_stock", "stock_movements", "audit_events"],
        "isolation": "READ COMMITTED",
        "lock_strategy": "Pessimistic row lock on clinic_stock (SELECT FOR UPDATE) or INSERT on conflict DO UPDATE.",
        "ordering": "pharmacy_batches -> clinic_stock -> stock_movements -> audit_events",
        "idempotency": "Idempotent on (warehouse_voucher_number, batch_number, facility_id).",
        "concurrency": "Pharmacist receiving stock delivery while clinic dispenses from existing batches.",
        "deadlock_risk": "Low. Controlled inward receipt transaction.",
        "retry_behavior": "3 retries with 100ms jitter.",
        "rollback_behavior": "Full rollback; stock balances unchanged if batch validation fails.",
        "failure_scenarios": "Batch expiration date in past, quantity received <= 0, unmatched formulary drug.",
        "audit_event": "AUDIT-EVENT-023",
        "consistency": "Double-entry accounting; stock_movements record must equal clinic_stock increment."
    },
    {
        "id": "TXN-015",
        "name": "Clinic Real-Time Stock Balance Reallocation",
        "operation": "Inter-store transfer, quarantine lock of recalled batch, or physical stock count adjustment reconciliation.",
        "tables": ["clinic_stock", "stock_movements", "audit_events"],
        "isolation": "SERIALIZABLE",
        "lock_strategy": "Pessimistic row lock (SELECT FOR UPDATE) on source and destination clinic_stock rows.",
        "ordering": "clinic_stock (ordered by id) -> stock_movements -> audit_events",
        "idempotency": "Voucher-based idempotency key prevents duplicate reconciliation postings.",
        "concurrency": "Periodic stock reconciliation performed after clinic operational hours.",
        "deadlock_risk": "Mitigated by sorting clinic_stock IDs before acquiring row locks.",
        "retry_behavior": "5 retries on serialization failure.",
        "rollback_behavior": "Stock quantities restored to pre-transaction levels.",
        "failure_scenarios": "Insufficient stock for deduction, invalid reconciliation reason.",
        "audit_event": "AUDIT-EVENT-025",
        "consistency": "Conservation of mass: total units in movement ledger must net to zero for transfers."
    },
    {
        "id": "TXN-016",
        "name": "Pharmacy Drug Dispensation & Double-Entry Stock Decrement",
        "operation": "Handing over prescribed medications to patient, verifying FEFO batch allocation, decrementing clinic stock, appending stock movements, and updating prescription status.",
        "tables": ["dispensations", "dispensation_items", "clinic_stock", "stock_movements", "prescriptions", "queue_entries", "audit_events"],
        "isolation": "READ COMMITTED",
        "lock_strategy": "Pessimistic row lock on clinic_stock rows (SELECT FOR UPDATE) ordered by batch_id to prevent deadlocks and prevent negative stock.",
        "ordering": "dispensations -> dispensation_items -> clinic_stock -> stock_movements -> prescriptions -> queue_entries -> audit_events",
        "idempotency": "Unique constraint on prescription_id in dispensations prevents double dispensing.",
        "concurrency": "Very high concurrency at pharmacy dispensing counters across all clinics.",
        "deadlock_risk": "Eliminated by strictly ordering clinic_stock row locks alphabetically by batch_id.",
        "retry_behavior": "3 retries with 50ms exponential backoff and jitter.",
        "rollback_behavior": "Complete rollback; zero stock deducted if any item fails stock availability check.",
        "failure_scenarios": "Stockout (quantity_on_hand < requested_quantity), expired batch selected, prescription cancelled.",
        "audit_event": "AUDIT-EVENT-024",
        "consistency": "Strict ACID invariant: clinic_stock quantity_on_hand MUST NEVER become negative (CHECK constraint quantity_on_hand >= 0)."
    },
    {
        "id": "TXN-017",
        "name": "Expired & Damaged Medication Quarantine & Disposal",
        "operation": "Deduction of expired drugs from active clinic inventory, transfer to disposal quarantine ledger, and regulatory reporting.",
        "tables": ["clinic_stock", "stock_movements", "audit_events"],
        "isolation": "READ COMMITTED",
        "lock_strategy": "Exclusive row lock on clinic_stock for affected expired batches.",
        "ordering": "clinic_stock -> stock_movements -> audit_events",
        "idempotency": "Disposal authorization voucher number used as idempotency key.",
        "concurrency": "Executed during monthly inventory audit.",
        "deadlock_risk": "None.",
        "retry_behavior": "3 retries with 100ms backoff.",
        "rollback_behavior": "Stock quantities restored if disposal audit recording fails.",
        "failure_scenarios": "Quantity disposed exceeds recorded balance.",
        "audit_event": "AUDIT-EVENT-025",
        "consistency": "Permanent double-entry audit trail; destroyed stock tracked for CAG review."
    },
    {
        "id": "TXN-018",
        "name": "Clinic Drug Indent Requisition Submission & Approval",
        "operation": "Generating periodic clinic drug requisition order to central warehouse, calculating AMC stock levels, and MOIC electronic sign-off.",
        "tables": ["drug_indents", "indent_items", "audit_events"],
        "isolation": "READ COMMITTED",
        "lock_strategy": "Append-only insert on indent header and items.",
        "ordering": "drug_indents -> indent_items -> audit_events",
        "idempotency": "Idempotency key derived from (facility_id, indent_cycle_month).",
        "concurrency": "Submitted monthly per clinic.",
        "deadlock_risk": "None.",
        "retry_behavior": "3 retries on network error.",
        "rollback_behavior": "Indent draft discarded if submission fails.",
        "failure_scenarios": "Zero items in indent, MOIC signature invalid.",
        "audit_event": "AUDIT-EVENT-026",
        "consistency": "ACID compliance; indent items bound to master formulary."
    },
    {
        "id": "TXN-019",
        "name": "Cold-Chain IoT Telemetry Stream Ingestion & Excursion Alert",
        "operation": "High-frequency ingestion of refrigerator sensor temperature readings, battery status, and evaluating thermal threshold breach.",
        "tables": ["cold_chain_telemetry", "danger_alerts", "audit_events"],
        "isolation": "READ COMMITTED",
        "lock_strategy": "Lock-free append-only partition insertion into cold_chain_telemetry.",
        "ordering": "cold_chain_telemetry -> danger_alerts -> audit_events",
        "idempotency": "Idempotent on (device_id, recorded_at) preventing duplicate sensor readings.",
        "concurrency": "Very high write throughput: 700,000 readings/day ingested via Kafka consumer pipeline.",
        "deadlock_risk": "Zero. Pure partitioned append.",
        "retry_behavior": "Kafka consumer offset retry on failure.",
        "rollback_behavior": "Sensor batch re-queued in Kafka dead letter queue if database unreachable.",
        "failure_scenarios": "Database disk pressure, invalid temperature sensor payload.",
        "audit_event": "AUDIT-EVENT-027",
        "consistency": "Guaranteed alert generation within 60 seconds of persistent thermal breach."
    },
    {
        "id": "TXN-020",
        "name": "Secondary Hospital Referral Dossier Creation",
        "operation": "Compiling clinical encounter summary, lab results, and provisional diagnosis into referral dossier, generating referral code, and alert dispatch.",
        "tables": ["referrals", "clinical_encounters", "notifications", "audit_events"],
        "isolation": "READ COMMITTED",
        "lock_strategy": "Shared read lock on clinical_encounters; append into referrals.",
        "ordering": "referrals -> clinical_encounters -> notifications -> audit_events",
        "idempotency": "Unique constraint on (encounter_id) for outbound referral.",
        "concurrency": "Created during patient disposition at end of consultation.",
        "deadlock_risk": "Low.",
        "retry_behavior": "3 retries with 50ms backoff.",
        "rollback_behavior": "Referral cancelled; doctor alerted to retry referral creation.",
        "failure_scenarios": "Invalid target hospital facility ID, missing referral reason.",
        "audit_event": "AUDIT-EVENT-028",
        "consistency": "Longitudinal integrity; referral strictly linked to verified patient."
    },
    {
        "id": "TXN-021",
        "name": "Specialist Counter-Referral Feedback Integration",
        "operation": "Receiving hospital specialist discharge summary, updating primary care referral status, and integrating findings into patient record.",
        "tables": ["referral_counter_notes", "referrals", "audit_events"],
        "isolation": "READ COMMITTED",
        "lock_strategy": "Pessimistic row lock on referrals (SELECT FOR UPDATE) to update status to COUNTER_REFERRED.",
        "ordering": "referral_counter_notes -> referrals -> audit_events",
        "idempotency": "Idempotency key based on secondary hospital discharge summary ID.",
        "concurrency": "Incoming asynchronous integration webhook from secondary hospital EMR.",
        "deadlock_risk": "None.",
        "retry_behavior": "5 retries on lock contention.",
        "rollback_behavior": "Feedback message held in integration queue for re-processing.",
        "failure_scenarios": "Referral number not found in primary care registry.",
        "audit_event": "AUDIT-EVENT-028",
        "consistency": "Closed-loop referral lifecycle guaranteed."
    },
    {
        "id": "TXN-022",
        "name": "NCD Longitudinal Episode Enrollment & Target Setting",
        "operation": "Enrolling patient into chronic hypertension/diabetes care registry, establishing clinical targets, and assigning care worker.",
        "tables": ["ncd_episodes", "follow_up_schedules", "audit_events"],
        "isolation": "READ COMMITTED",
        "lock_strategy": "Optimistic concurrency check on existing active NCD episodes for patient.",
        "ordering": "ncd_episodes -> follow_up_schedules -> audit_events",
        "idempotency": "Unique constraint on (patient_id, condition_category) where status = 'ACTIVE'.",
        "concurrency": "Enrolled during clinical encounter.",
        "deadlock_risk": "None.",
        "retry_behavior": "3 retries on serialization conflict.",
        "rollback_behavior": "Enrollment discarded if schedule generation fails.",
        "failure_scenarios": "Patient already enrolled in active episode for same chronic condition.",
        "audit_event": "AUDIT-EVENT-028",
        "consistency": "Chronic care continuity guaranteed with immediate follow-up schedule entry."
    },
    {
        "id": "TXN-023",
        "name": "Care Continuity Follow-up Scheduling & Auto-Reminder",
        "operation": "Booking scheduled review date, calculating reminder timeline, and queueing citizen SMS/WhatsApp dispatch triggers.",
        "tables": ["follow_up_schedules", "notifications", "audit_events"],
        "isolation": "READ COMMITTED",
        "lock_strategy": "Append-only insert on follow_up_schedules.",
        "ordering": "follow_up_schedules -> notifications -> audit_events",
        "idempotency": "Unique on (patient_id, scheduled_date, clinical_purpose).",
        "concurrency": "Discharge planning during doctor consultation.",
        "deadlock_risk": "None.",
        "retry_behavior": "3 retries on network blip.",
        "rollback_behavior": "Schedule cancelled if notification queueing fails.",
        "failure_scenarios": "Follow-up date in the past, inactive patient record.",
        "audit_event": "AUDIT-EVENT-028",
        "consistency": "ACID compliance; reminder message scheduled in exact alignment with clinic appointment."
    },
    {
        "id": "TXN-024",
        "name": "Citizen Communication Dispatch & Delivery Receipt Reconciliation",
        "operation": "Recording outbound message transmission, logging carrier message ID, and updating delivery receipt status on telecom webhook.",
        "tables": ["notifications", "audit_events"],
        "isolation": "READ COMMITTED",
        "lock_strategy": "Row lock on notifications (SELECT FOR UPDATE) on incoming delivery webhook.",
        "ordering": "notifications -> audit_events",
        "idempotency": "Telecom gateway message_id unique constraint.",
        "concurrency": "High volume asynchronous DLR webhooks processed by worker pool.",
        "deadlock_risk": "Minimal.",
        "retry_behavior": "3 retries with 50ms backoff.",
        "rollback_behavior": "Webhook retry triggered on database lock error.",
        "failure_scenarios": "Unknown message ID, malformed carrier webhook.",
        "audit_event": "AUDIT-EVENT-002",
        "consistency": "Monotonic delivery state updates (QUEUED -> SENT -> DELIVERED)."
    },
    {
        "id": "TXN-025",
        "name": "Edge Offline Mutation Journal Flush & Cloud Reconciliation",
        "operation": "Batch replaying edge mutations to central PostgreSQL, vector clock conflict evaluation, applying changes, and appending immutable WORM audit log.",
        "tables": ["offline_mutation_log", "audit_events"],
        "isolation": "REPEATABLE READ",
        "lock_strategy": "Advisory lock per edge facility_id to serialize cloud synchronization replay.",
        "ordering": "offline_mutation_log -> target domain tables -> audit_events",
        "idempotency": "Sequence number and edge transaction hash ensure idempotent replay; duplicate mutations ignored.",
        "concurrency": "Reconnection sync from 450 clinics operating concurrently.",
        "deadlock_risk": "Mitigated by facility-level advisory locks and deterministic replay sequence.",
        "retry_behavior": "5 retries with exponential backoff and jitter on conflict.",
        "rollback_behavior": "Failed batch preserved on edge; cloud rolls back to last valid sequence point.",
        "failure_scenarios": "Sync version conflict, schema version mismatch between edge and cloud.",
        "audit_event": "AUDIT-EVENT-030",
        "consistency": "Eventual consistency with guaranteed convergence via deterministic Last-Write-Wins / Doctor-Wins rule."
    }
]

TRANSACTION_MAP = {t["id"]: t for t in TRANSACTIONS}

if __name__ == "__main__":
    print(f"Loaded {len(AUDIT_ENTITIES)} Audit Entities (AUDIT-ENTITY-001..030).")
    print(f"Loaded {len(AUDIT_EVENTS)} Audit Events (AUDIT-EVENT-001..030).")
    print(f"Loaded {len(TRANSACTIONS)} Transaction Models (TXN-001..TXN-025).")
