"""
db_migrations_seeds.py
Canonical definitions for:
- 30 Migration Blueprints (MIG-001 to MIG-030)
- 15 Seed Datasets (SEED-001 to SEED-015)
"""

import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parent.parent.parent))

from typing import List, Dict, Any

# -----------------------------------------------------------------------------
# 1. 30 MIGRATION BLUEPRINTS (MIG-001 to MIG-030)
# -----------------------------------------------------------------------------
MIGRATIONS = [
    {
        "id": "MIG-001",
        "name": "Database Schema Namespace Initialization",
        "target_tables": ["identity", "intake", "clinical", "pharmacy", "continuity", "audit", "sync"],
        "type": "SCHEMA_INIT",
        "objective": "Establish isolated relational schemas to enforce modular domain boundaries and RBAC permissions.",
        "preconditions": "PostgreSQL 16+ cluster initialized with UTF-8 encoding and UTC timezone.",
        "dependencies": "None (Genesis Migration)",
        "preparation": "SET lock_timeout = '5s'; SET statement_timeout = '30s';",
        "expand": "CREATE SCHEMA IF NOT EXISTS identity; CREATE SCHEMA IF NOT EXISTS intake; CREATE SCHEMA IF NOT EXISTS clinical; CREATE SCHEMA IF NOT EXISTS pharmacy; CREATE SCHEMA IF NOT EXISTS continuity; CREATE SCHEMA IF NOT EXISTS audit; CREATE SCHEMA IF NOT EXISTS sync;",
        "backfill": "None required.",
        "validation": "SELECT schema_name FROM information_schema.schemata WHERE schema_name IN ('identity', 'intake', 'clinical', 'pharmacy', 'continuity', 'audit', 'sync');",
        "app_compat": "Search path configured to include all domain schemas.",
        "contract": "Revoke public schema creation rights.",
        "rollback": "DROP SCHEMA IF EXISTS identity CASCADE; (restricted in prod).",
        "monitoring": "Verify pg_namespace catalog entries.",
        "completion_criteria": "7 schemas created with restricted privileges."
    },
    {
        "id": "MIG-002",
        "name": "PostgreSQL Extensions & Cryptographic Functions Setup",
        "target_tables": ["pg_extension"],
        "type": "SCHEMA_INIT",
        "objective": "Enable required extensions: pgcrypto, uuid-ossp, pg_trgm, and btree_gist.",
        "preconditions": "Superuser / rds_superuser privileges.",
        "dependencies": "MIG-001",
        "preparation": "Verify extension availability in pg_available_extensions.",
        "expand": "CREATE EXTENSION IF NOT EXISTS \"pgcrypto\"; CREATE EXTENSION IF NOT EXISTS \"uuid-ossp\"; CREATE EXTENSION IF NOT EXISTS \"pg_trgm\"; CREATE EXTENSION IF NOT EXISTS \"btree_gist\";",
        "backfill": "None required.",
        "validation": "SELECT extname FROM pg_extension WHERE extname IN ('pgcrypto', 'uuid-ossp', 'pg_trgm', 'btree_gist');",
        "app_compat": "Native gen_random_uuid() enabled across all tables.",
        "contract": "None.",
        "rollback": "DROP EXTENSION IF EXISTS pg_trgm; DROP EXTENSION IF EXISTS btree_gist;",
        "monitoring": "Verify memory allocation for pg_trgm.",
        "completion_criteria": "All 4 extensions active and verified."
    },
    {
        "id": "MIG-003",
        "name": "Identity Domain Core Tables Provisioning",
        "target_tables": ["auth_users", "user_credentials", "roles", "permissions", "role_permissions", "user_roles"],
        "type": "TABLE_CREATION",
        "objective": "Create authentication and RBAC foundation tables with UUIDv7 primary keys.",
        "preconditions": "MIG-001 and MIG-002 completed.",
        "dependencies": "MIG-002",
        "preparation": "Ensure identity schema exists and lock timeout configured.",
        "expand": "Execute DDL for auth_users, user_credentials, roles, permissions, role_permissions, user_roles.",
        "backfill": "None (empty tables).",
        "validation": "SELECT table_name FROM information_schema.tables WHERE table_schema = 'identity';",
        "app_compat": "Backward compatible additive migration.",
        "contract": "None.",
        "rollback": "DROP TABLE IF EXISTS identity.user_roles, identity.role_permissions, identity.permissions, identity.roles, identity.user_credentials, identity.auth_users CASCADE;",
        "monitoring": "Check catalog table creation status.",
        "completion_criteria": "6 identity tables verified with constraints."
    },
    {
        "id": "MIG-004",
        "name": "Facility & Staff Organization Tables Setup",
        "target_tables": ["facilities", "facility_rooms", "staff_profiles", "staff_shifts", "system_configs"],
        "type": "TABLE_CREATION",
        "objective": "Provision physical clinic facilities, consultation rooms, staff profiles, and shifts.",
        "preconditions": "MIG-003 completed.",
        "dependencies": "MIG-003",
        "preparation": "Verify foreign key targets in identity.auth_users.",
        "expand": "Execute DDL for facilities, facility_rooms, staff_profiles, staff_shifts, system_configs.",
        "backfill": "None.",
        "validation": "Verify 5 tables in information_schema.",
        "app_compat": "Purely additive.",
        "contract": "None.",
        "rollback": "DROP TABLE IF EXISTS identity.system_configs, identity.staff_shifts, identity.staff_profiles, identity.facility_rooms, identity.facilities CASCADE;",
        "monitoring": "Monitor table lock duration during creation.",
        "completion_criteria": "5 facility/staff tables created."
    },
    {
        "id": "MIG-005",
        "name": "Citizen Demographics & Identification Tables Setup",
        "target_tables": ["patients", "patient_identifiers", "patient_contacts", "patient_addresses", "consent_records"],
        "type": "TABLE_CREATION",
        "objective": "Establish Master Patient Index (MPI) and DPDP consent tables.",
        "preconditions": "MIG-004 completed.",
        "dependencies": "MIG-004",
        "preparation": "Configure hash partition parameters for patients table.",
        "expand": "Create intake.patients (hash partitioned 16-ways), patient_identifiers, patient_contacts, patient_addresses, consent_records.",
        "backfill": "None.",
        "validation": "Check partition child tables: intake.patients_part_00 to intake.patients_part_15.",
        "app_compat": "Additive non-breaking.",
        "contract": "None.",
        "rollback": "DROP TABLE IF EXISTS intake.consent_records, intake.patient_addresses, intake.patient_contacts, intake.patient_identifiers, intake.patients CASCADE;",
        "monitoring": "Verify hash partition routing logic.",
        "completion_criteria": "Patients master table and 16 hash partitions created."
    },
    {
        "id": "MIG-006",
        "name": "Queue & Daily Intake Tokens Tables Setup",
        "target_tables": ["tokens", "queue_entries"],
        "type": "TABLE_CREATION",
        "objective": "Deploy sequential intake token generation and multi-stage workflow queue tables.",
        "preconditions": "MIG-005 completed.",
        "dependencies": "MIG-005",
        "preparation": "Setup range partitioning on tokens and queue_entries by month.",
        "expand": "Create intake.tokens and intake.queue_entries partitioned by created_at.",
        "backfill": "Pre-create current month and next 2 months partitions.",
        "validation": "Verify partition existence for current month.",
        "app_compat": "Additive non-breaking.",
        "contract": "None.",
        "rollback": "DROP TABLE IF EXISTS intake.queue_entries, intake.tokens CASCADE;",
        "monitoring": "Verify table space allocation for queue entries.",
        "completion_criteria": "Queue tables active with current partitions."
    },
    {
        "id": "MIG-007",
        "name": "Nursing Triage & Physiological Vitals Tables Setup",
        "target_tables": ["triage_assessments", "patient_vitals", "danger_alerts"],
        "type": "TABLE_CREATION",
        "objective": "Provision clinical triage scoring, longitudinal vitals tracking, and danger alert tables.",
        "preconditions": "MIG-006 completed.",
        "dependencies": "MIG-006",
        "preparation": "Configure quarterly range partitioning for patient_vitals and danger_alerts.",
        "expand": "Create intake.triage_assessments, intake.patient_vitals, intake.danger_alerts.",
        "backfill": "Create initial quarterly partitions.",
        "validation": "Check information_schema for triage tables.",
        "app_compat": "Additive.",
        "contract": "None.",
        "rollback": "DROP TABLE IF EXISTS intake.danger_alerts, intake.patient_vitals, intake.triage_assessments CASCADE;",
        "monitoring": "Check autovacuum settings for vitals partitions.",
        "completion_criteria": "Triage tables deployed with range partitioning."
    },
    {
        "id": "MIG-008",
        "name": "Clinical Consultation & Encounters Tables Setup",
        "target_tables": ["clinical_encounters", "clinical_notes", "diagnoses"],
        "type": "TABLE_CREATION",
        "objective": "Deploy doctor outpatient consultation encounters, SOAP notes, and coded diagnoses.",
        "preconditions": "MIG-007 completed.",
        "dependencies": "MIG-007",
        "preparation": "Setup monthly range partitioning for clinical_encounters and clinical_notes.",
        "expand": "Create clinical.clinical_encounters, clinical.clinical_notes, clinical.diagnoses.",
        "backfill": "Pre-create monthly encounter partitions.",
        "validation": "Verify encounter foreign key constraints against patients and auth_users.",
        "app_compat": "Additive non-breaking.",
        "contract": "None.",
        "rollback": "DROP TABLE IF EXISTS clinical.diagnoses, clinical.clinical_notes, clinical.clinical_encounters CASCADE;",
        "monitoring": "Verify index build on encounter_date.",
        "completion_criteria": "Clinical consultation schema initialized."
    },
    {
        "id": "MIG-009",
        "name": "Electronic Prescribing & Medication Items Tables Setup",
        "target_tables": ["prescriptions", "prescription_items"],
        "type": "TABLE_CREATION",
        "objective": "Deploy electronic prescription headers and line items.",
        "preconditions": "MIG-008 completed.",
        "dependencies": "MIG-008",
        "preparation": "Setup range partitions on prescribed_at.",
        "expand": "Create clinical.prescriptions and clinical.prescription_items partitioned by month.",
        "backfill": "Initialize current month partitions.",
        "validation": "Verify foreign key link from prescription_items to prescriptions.",
        "app_compat": "Additive.",
        "contract": "None.",
        "rollback": "DROP TABLE IF EXISTS clinical.prescription_items, clinical.prescriptions CASCADE;",
        "monitoring": "Monitor foreign key cascade constraint performance.",
        "completion_criteria": "Prescription tables active."
    },
    {
        "id": "MIG-010",
        "name": "Diagnostic Laboratory Investigation Tables Setup",
        "target_tables": ["lab_orders", "lab_order_items", "lab_results"],
        "type": "TABLE_CREATION",
        "objective": "Deploy laboratory diagnostic orders, requested test items, and verified observations.",
        "preconditions": "MIG-009 completed.",
        "dependencies": "MIG-009",
        "preparation": "Setup quarterly partitioning on lab_results.",
        "expand": "Create clinical.lab_orders, clinical.lab_order_items, clinical.lab_results.",
        "backfill": "Initialize current quarter partitions.",
        "validation": "Verify LOINC check constraints on lab_order_items.",
        "app_compat": "Additive.",
        "contract": "None.",
        "rollback": "DROP TABLE IF EXISTS clinical.lab_results, clinical.lab_order_items, clinical.lab_orders CASCADE;",
        "monitoring": "Check table stats on lab order creation.",
        "completion_criteria": "Diagnostic laboratory tables deployed."
    },
    {
        "id": "MIG-011",
        "name": "Teleconsultation Remote Specialist Tables Setup",
        "target_tables": ["teleconsultations"],
        "type": "TABLE_CREATION",
        "objective": "Provision doctor-to-specialist video consultation session tables.",
        "preconditions": "MIG-010 completed.",
        "dependencies": "MIG-010",
        "preparation": "Setup semi-annual range partitions.",
        "expand": "Create clinical.teleconsultations partitioned by session_start.",
        "backfill": "Initialize active partition.",
        "validation": "Verify encounter 1:1 foreign key linkage.",
        "app_compat": "Additive.",
        "contract": "None.",
        "rollback": "DROP TABLE IF EXISTS clinical.teleconsultations CASCADE;",
        "monitoring": "Check WebRTC room metadata column types.",
        "completion_criteria": "Teleconsultations table active."
    },
    {
        "id": "MIG-012",
        "name": "Pharmaceutical Formulary Master Tables Setup",
        "target_tables": ["formulary_drugs", "drug_categories"],
        "type": "TABLE_CREATION",
        "objective": "Establish master drug catalog and therapeutic categories.",
        "preconditions": "MIG-011 completed.",
        "dependencies": "MIG-011",
        "preparation": "Prepare ATC category check constraints.",
        "expand": "Create pharmacy.drug_categories and pharmacy.formulary_drugs.",
        "backfill": "None.",
        "validation": "Verify categories foreign key on formulary_drugs.",
        "app_compat": "Additive.",
        "contract": "None.",
        "rollback": "DROP TABLE IF EXISTS pharmacy.formulary_drugs, pharmacy.drug_categories CASCADE;",
        "monitoring": "Check B-tree index on generic drug name.",
        "completion_criteria": "Formulary master tables ready for seed data."
    },
    {
        "id": "MIG-013",
        "name": "Pharmacy Batch & Real-Time Clinic Inventory Tables Setup",
        "target_tables": ["pharmacy_batches", "clinic_stock"],
        "type": "TABLE_CREATION",
        "objective": "Deploy physical drug batches and per-clinic real-time inventory balances.",
        "preconditions": "MIG-012 completed.",
        "dependencies": "MIG-012",
        "preparation": "Enforce non-negative check constraint on quantity_on_hand.",
        "expand": "Create pharmacy.pharmacy_batches and pharmacy.clinic_stock.",
        "backfill": "None.",
        "validation": "Verify check constraint: quantity_on_hand >= 0.",
        "app_compat": "Additive.",
        "contract": "None.",
        "rollback": "DROP TABLE IF EXISTS pharmacy.clinic_stock, pharmacy.pharmacy_batches CASCADE;",
        "monitoring": "Check unique constraint on (facility_id, batch_id).",
        "completion_criteria": "Inventory tables deployed with strict non-negative constraints."
    },
    {
        "id": "MIG-014",
        "name": "Pharmacy Dispensation Event Tables Setup",
        "target_tables": ["dispensations", "dispensation_items"],
        "type": "TABLE_CREATION",
        "objective": "Deploy pharmacy dispensing headers and batch-allocated item tables.",
        "preconditions": "MIG-013 completed.",
        "dependencies": "MIG-013",
        "preparation": "Setup monthly range partitioning on dispensation_items.",
        "expand": "Create pharmacy.dispensations and pharmacy.dispensation_items.",
        "backfill": "Initialize current month partitions.",
        "validation": "Verify foreign keys to prescriptions and pharmacy_batches.",
        "app_compat": "Additive.",
        "contract": "None.",
        "rollback": "DROP TABLE IF EXISTS pharmacy.dispensation_items, pharmacy.dispensations CASCADE;",
        "monitoring": "Monitor write volume on dispensation_items.",
        "completion_criteria": "Dispensing tables deployed."
    },
    {
        "id": "MIG-015",
        "name": "Double-Entry Stock Movement Audit Ledger Table Setup",
        "target_tables": ["stock_movements"],
        "type": "TABLE_CREATION",
        "objective": "Deploy immutable inventory accounting ledger.",
        "preconditions": "MIG-014 completed.",
        "dependencies": "MIG-014",
        "preparation": "Setup quarterly range partitioning on movement_timestamp.",
        "expand": "Create pharmacy.stock_movements partitioned by movement_timestamp.",
        "backfill": "Pre-create quarterly partitions.",
        "validation": "Verify append-only permissions on pharmacy.stock_movements.",
        "app_compat": "Additive.",
        "contract": "None.",
        "rollback": "DROP TABLE IF EXISTS pharmacy.stock_movements CASCADE;",
        "monitoring": "Check BRIN index on movement_timestamp.",
        "completion_criteria": "Stock movements ledger initialized."
    },
    {
        "id": "MIG-016",
        "name": "Drug Indent & Requisition Workflow Tables Setup",
        "target_tables": ["drug_indents", "indent_items"],
        "type": "TABLE_CREATION",
        "objective": "Deploy electronic warehouse drug requisition and line item tables.",
        "preconditions": "MIG-015 completed.",
        "dependencies": "MIG-015",
        "preparation": "Configure status workflow checks.",
        "expand": "Create pharmacy.drug_indents and pharmacy.indent_items.",
        "backfill": "None.",
        "validation": "Verify foreign key link between indent_items and drug_indents.",
        "app_compat": "Additive.",
        "contract": "None.",
        "rollback": "DROP TABLE IF EXISTS pharmacy.indent_items, pharmacy.drug_indents CASCADE;",
        "monitoring": "Verify indent status indexing.",
        "completion_criteria": "Drug indent tables ready."
    },
    {
        "id": "MIG-017",
        "name": "Cold-Chain IoT Sensor & Telemetry Tables Setup",
        "target_tables": ["cold_chain_devices", "cold_chain_telemetry"],
        "type": "TABLE_CREATION",
        "objective": "Deploy vaccine refrigerator directory and high-frequency IoT temperature telemetry.",
        "preconditions": "MIG-016 completed.",
        "dependencies": "MIG-016",
        "preparation": "Setup monthly range partitioning on cold_chain_telemetry.",
        "expand": "Create pharmacy.cold_chain_devices and pharmacy.cold_chain_telemetry.",
        "backfill": "Initialize current month telemetry partition.",
        "validation": "Verify BRIN index creation on cold_chain_telemetry.recorded_at.",
        "app_compat": "Additive.",
        "contract": "None.",
        "rollback": "DROP TABLE IF EXISTS pharmacy.cold_chain_telemetry, pharmacy.cold_chain_devices CASCADE;",
        "monitoring": "Monitor IoT ingestion disk rate.",
        "completion_criteria": "Cold chain IoT tables active."
    },
    {
        "id": "MIG-018",
        "name": "Secondary Hospital Referral & Continuity Tables Setup",
        "target_tables": ["referrals", "referral_counter_notes"],
        "type": "TABLE_CREATION",
        "objective": "Deploy two-way hospital referral and specialist feedback tables.",
        "preconditions": "MIG-017 completed.",
        "dependencies": "MIG-017",
        "preparation": "Setup quarterly range partitioning on referrals.",
        "expand": "Create continuity.referrals and continuity.referral_counter_notes.",
        "backfill": "Initialize current quarter partition.",
        "validation": "Verify target_facility_id foreign key constraint.",
        "app_compat": "Additive.",
        "contract": "None.",
        "rollback": "DROP TABLE IF EXISTS continuity.referral_counter_notes, continuity.referrals CASCADE;",
        "monitoring": "Check referral index scan latency.",
        "completion_criteria": "Referral exchange tables active."
    },
    {
        "id": "MIG-019",
        "name": "NCD Longitudinal Care & Follow-up Scheduling Tables Setup",
        "target_tables": ["ncd_episodes", "follow_up_schedules"],
        "type": "TABLE_CREATION",
        "objective": "Deploy chronic disease management registries and scheduled appointment tables.",
        "preconditions": "MIG-018 completed.",
        "dependencies": "MIG-018",
        "preparation": "Setup monthly range partitioning on follow_up_schedules.",
        "expand": "Create continuity.ncd_episodes and continuity.follow_up_schedules.",
        "backfill": "Pre-create monthly follow-up schedule partitions.",
        "validation": "Verify unique active NCD episode per condition check.",
        "app_compat": "Additive.",
        "contract": "None.",
        "rollback": "DROP TABLE IF EXISTS continuity.follow_up_schedules, continuity.ncd_episodes CASCADE;",
        "monitoring": "Check scheduled date lookup performance.",
        "completion_criteria": "NCD continuity tables deployed."
    },
    {
        "id": "MIG-020",
        "name": "Citizen Notifications & Communication Log Table Setup",
        "target_tables": ["notifications"],
        "type": "TABLE_CREATION",
        "objective": "Deploy outbound SMS/WhatsApp communication dispatch tables.",
        "preconditions": "MIG-019 completed.",
        "dependencies": "MIG-019",
        "preparation": "Setup monthly range partitioning on created_at.",
        "expand": "Create continuity.notifications partitioned by created_at.",
        "backfill": "Initialize current month partition.",
        "validation": "Verify channel enum and DLR reference indexing.",
        "app_compat": "Additive.",
        "contract": "None.",
        "rollback": "DROP TABLE IF EXISTS continuity.notifications CASCADE;",
        "monitoring": "Monitor carrier delivery receipt updates.",
        "completion_criteria": "Notifications table active."
    },
    {
        "id": "MIG-021",
        "name": "Citizen Grievances & IT Helpdesk Tables Setup",
        "target_tables": ["grievances", "helpdesk_tickets"],
        "type": "TABLE_CREATION",
        "objective": "Deploy Sakala citizen complaints and facility IT support ticket tables.",
        "preconditions": "MIG-020 completed.",
        "dependencies": "MIG-020",
        "preparation": "Setup semi-annual range partitioning on grievances.",
        "expand": "Create continuity.grievances and continuity.helpdesk_tickets.",
        "backfill": "Initialize active partition.",
        "validation": "Verify facility_id foreign key on grievances.",
        "app_compat": "Additive.",
        "contract": "None.",
        "rollback": "DROP TABLE IF EXISTS continuity.helpdesk_tickets, continuity.grievances CASCADE;",
        "monitoring": "Verify SLA breach trigger function.",
        "completion_criteria": "Grievance and support tables active."
    },
    {
        "id": "MIG-022",
        "name": "Immutable Cryptographic WORM Audit Log Setup",
        "target_tables": ["audit_events"],
        "type": "TABLE_CREATION",
        "objective": "Deploy append-only tamper-evident audit ledger with SHA-256 HMAC hash chaining.",
        "preconditions": "MIG-021 completed.",
        "dependencies": "MIG-021",
        "preparation": "Setup monthly range partitioning on event_timestamp.",
        "expand": "Create audit.audit_events partitioned by event_timestamp with local BRIN indexes.",
        "backfill": "Initialize current month audit partition.",
        "validation": "Revoke UPDATE and DELETE privileges on audit.audit_events from all application roles.",
        "app_compat": "Additive.",
        "contract": "None.",
        "rollback": "Restricted by CISO policy (requires dual break-glass sign-off).",
        "monitoring": "Verify cryptographic hash chain continuity check.",
        "completion_criteria": "WORM audit table active with append-only permissions."
    },
    {
        "id": "MIG-023",
        "name": "Edge Offline Mutation Journal Table Setup",
        "target_tables": ["offline_mutation_log"],
        "type": "TABLE_CREATION",
        "objective": "Deploy edge mutation synchronization queue table.",
        "preconditions": "MIG-022 completed.",
        "dependencies": "MIG-022",
        "preparation": "Setup monthly range partitioning on created_at.",
        "expand": "Create sync.offline_mutation_log partitioned by created_at.",
        "backfill": "Initialize current month partition.",
        "validation": "Verify partial index on status = 'PENDING'.",
        "app_compat": "Additive.",
        "contract": "None.",
        "rollback": "DROP TABLE IF EXISTS sync.offline_mutation_log CASCADE;",
        "monitoring": "Check pending mutation queue depth.",
        "completion_criteria": "Edge offline mutation journal deployed."
    },
    {
        "id": "MIG-024",
        "name": "National Health Interoperability ABDM Artifacts Table Setup",
        "target_tables": ["abdm_artifacts"],
        "type": "TABLE_CREATION",
        "objective": "Deploy ABDM FHIR R4 clinical bundles and linking tokens table.",
        "preconditions": "MIG-023 completed.",
        "dependencies": "MIG-023",
        "preparation": "Setup quarterly range partitioning on created_at.",
        "expand": "Create sync.abdm_artifacts partitioned by created_at.",
        "backfill": "Initialize current quarter partition.",
        "validation": "Verify GIN index on fhir_bundle_json.",
        "app_compat": "Additive.",
        "contract": "None.",
        "rollback": "DROP TABLE IF EXISTS sync.abdm_artifacts CASCADE;",
        "monitoring": "Check FHIR bundle JSONB storage efficiency.",
        "completion_criteria": "ABDM artifacts table active."
    },
    {
        "id": "MIG-025",
        "name": "High-Throughput Foreign Key Indexes Creation",
        "target_tables": ["All 52 Tables"],
        "type": "INDEX_CREATION",
        "objective": "Build missing B-tree indexes on all foreign key columns concurrently to eliminate table locks.",
        "preconditions": "MIG-003 through MIG-024 completed; tables populated or empty.",
        "dependencies": "MIG-024",
        "preparation": "SET maintenance_work_mem = '1GB'; SET max_parallel_maintenance_workers = 4;",
        "expand": "Execute CREATE INDEX CONCURRENTLY on foreign key columns defined in REL-001 through REL-112.",
        "backfill": "None required (concurrent build scans existing rows).",
        "validation": "SELECT indexname FROM pg_indexes WHERE indexname LIKE 'idx_fk_%';",
        "app_compat": "Zero lock contention; application remains fully operational during index creation.",
        "contract": "None.",
        "rollback": "DROP INDEX CONCURRENTLY IF EXISTS <index_name>;",
        "monitoring": "Monitor pg_stat_progress_create_index.",
        "completion_criteria": "All FK columns indexed without table locking."
    },
    {
        "id": "MIG-026",
        "name": "Composite & Partial Query Acceleration Indexes Deployment",
        "target_tables": ["queue_entries", "tokens", "patients", "clinic_stock", "danger_alerts"],
        "type": "INDEX_CREATION",
        "objective": "Deploy performance indexes defined in INDEX-001 through INDEX-132.",
        "preconditions": "MIG-025 completed.",
        "dependencies": "MIG-025",
        "preparation": "Schedule execution during low-traffic maintenance window.",
        "expand": "Execute CREATE INDEX CONCURRENTLY for composite and partial indexes.",
        "backfill": "None.",
        "validation": "Verify idx_scan > 0 under test query workload.",
        "app_compat": "Non-blocking concurrent index build.",
        "contract": "None.",
        "rollback": "DROP INDEX CONCURRENTLY IF EXISTS <index_name>;",
        "monitoring": "Check index bloat via pgstattuple.",
        "completion_criteria": "132 indexes verified in pg_indexes."
    },
    {
        "id": "MIG-027",
        "name": "Zero-Downtime Column Addition: Patient Preferred Language",
        "target_tables": ["patients"],
        "type": "COLUMN_ADDITION",
        "objective": "Add preferred_language column to patients table with default 'kn' (Kannada) using expand/contract pattern.",
        "preconditions": "MIG-005 completed.",
        "dependencies": "MIG-005",
        "preparation": "Verify PostgreSQL version >= 11 (adds column with constant default without rewrite).",
        "expand": "ALTER TABLE intake.patients ADD COLUMN preferred_language VARCHAR(10) DEFAULT 'kn' NOT NULL;",
        "backfill": "Instantaneous metadata-only update in PostgreSQL 11+.",
        "validation": "SELECT preferred_language FROM intake.patients LIMIT 10;",
        "app_compat": "Application version N ignores column; version N+1 reads and writes column.",
        "contract": "Finalize code transition.",
        "rollback": "ALTER TABLE intake.patients DROP COLUMN IF EXISTS preferred_language;",
        "monitoring": "Confirm table rewrite did not occur (pg_class.relfilenode unchanged).",
        "completion_criteria": "Column added with 0 millisecond downtime."
    },
    {
        "id": "MIG-028",
        "name": "Zero-Downtime Column Type Widening: Facility Room Capacity",
        "target_tables": ["facility_rooms"],
        "type": "TYPE_CHANGE",
        "objective": "Widen capacity column from SMALLINT to INTEGER to support waiting hall expansion without locking.",
        "preconditions": "MIG-004 completed.",
        "dependencies": "MIG-004",
        "preparation": "SMALLINT to INTEGER is a binary-compatible type widening in PostgreSQL.",
        "expand": "ALTER TABLE identity.facility_rooms ALTER COLUMN max_capacity TYPE INTEGER;",
        "backfill": "None required (in-place catalog metadata update).",
        "validation": "SELECT data_type FROM information_schema.columns WHERE table_name = 'facility_rooms' AND column_name = 'max_capacity';",
        "app_compat": "Binary compatible; zero app impact.",
        "contract": "None.",
        "rollback": "Cannot narrow type without full table rewrite.",
        "monitoring": "Verify sub-millisecond execution.",
        "completion_criteria": "Column type widened successfully."
    },
    {
        "id": "MIG-029",
        "name": "Zero-Downtime Safe Constraint Addition: Drug Unit Price Positive",
        "target_tables": ["pharmacy_batches"],
        "type": "CONSTRAINT_CHANGE",
        "objective": "Add check constraint on pharmacy_batches.unit_cost >= 0 without blocking concurrent writes.",
        "preconditions": "MIG-013 completed.",
        "dependencies": "MIG-013",
        "preparation": "Two-phase constraint addition: ADD CONSTRAINT NOT VALID followed by VALIDATE CONSTRAINT.",
        "expand": "ALTER TABLE pharmacy.pharmacy_batches ADD CONSTRAINT chk_unit_cost_non_negative CHECK (unit_cost >= 0) NOT VALID;",
        "backfill": "ALTER TABLE pharmacy.pharmacy_batches VALIDATE CONSTRAINT chk_unit_cost_non_negative;",
        "validation": "SELECT convalidated FROM pg_constraint WHERE conname = 'chk_unit_cost_non_negative';",
        "app_compat": "Non-blocking validation; read lock only, writes proceed unaffected.",
        "contract": "Constraint enforced globally.",
        "rollback": "ALTER TABLE pharmacy.pharmacy_batches DROP CONSTRAINT IF EXISTS chk_unit_cost_non_negative;",
        "monitoring": "Check pg_stat_activity during validate constraint.",
        "completion_criteria": "Constraint active and validated with zero write blocking."
    },
    {
        "id": "MIG-030",
        "name": "Zero-Downtime Column Deprecation & Removal: Legacy Card Number",
        "target_tables": ["patients"],
        "type": "COLUMN_REMOVAL",
        "objective": "Safely retire legacy paper card number column following 3-stage expand/contract deprecation lifecycle.",
        "preconditions": "MIG-005 completed; application verified to no longer read legacy_card_number.",
        "dependencies": "MIG-005",
        "preparation": "Step 1: Deploy code version N that writes to legacy_card_number but does not read it. Step 2: Code N+1 stops writing. Step 3: Database removal.",
        "expand": "ALTER TABLE intake.patients ALTER COLUMN legacy_card_number DROP NOT NULL;",
        "backfill": "None.",
        "validation": "Verify application logs for zero references to legacy_card_number.",
        "app_compat": "Application version N+1 completely decoupled from column.",
        "contract": "ALTER TABLE intake.patients DROP COLUMN legacy_card_number;",
        "rollback": "Restore column from backup or additive migration if regression occurs.",
        "monitoring": "Check error rates post column removal.",
        "completion_criteria": "Column removed with zero application downtime."
    }
]

MIGRATION_MAP = {m["id"]: m for m in MIGRATIONS}

# -----------------------------------------------------------------------------
# 2. 15 SEED DATASETS (SEED-001 to SEED-015)
# -----------------------------------------------------------------------------
SEEDS = [
    {
        "id": "SEED-001",
        "name": "Standard Organizational RBAC Roles",
        "category": "PERMISSIONS",
        "target_table": "roles",
        "environment": "PRODUCTION_SAFE",
        "record_count": 30,
        "source_authority": "BBMP Health Administration Standard",
        "versioning": "v2024.1",
        "idempotency": "INSERT INTO identity.roles (id, code, name, ...) VALUES (...) ON CONFLICT (code) DO UPDATE SET ...",
        "execution_order": 1,
        "pii_presence": "NONE",
        "rollback_procedure": "DELETE FROM identity.roles WHERE is_system_standard = true AND code NOT IN ('ADMIN');"
    },
    {
        "id": "SEED-002",
        "name": "Fine-Grained System Permissions Matrix",
        "category": "PERMISSIONS",
        "target_table": "permissions",
        "environment": "PRODUCTION_SAFE",
        "record_count": 180,
        "source_authority": "Enterprise Security Architecture SECR-006",
        "versioning": "v2024.1",
        "idempotency": "INSERT INTO identity.permissions (code, ...) VALUES (...) ON CONFLICT (code) DO NOTHING",
        "execution_order": 2,
        "pii_presence": "NONE",
        "rollback_procedure": "DELETE FROM identity.permissions WHERE is_core = true;"
    },
    {
        "id": "SEED-003",
        "name": "Role-Permission Entitlement Mapping",
        "category": "PERMISSIONS",
        "target_table": "role_permissions",
        "environment": "PRODUCTION_SAFE",
        "record_count": 900,
        "source_authority": "BBMP Security Policy Matrix",
        "versioning": "v2024.1",
        "idempotency": "INSERT INTO identity.role_permissions (role_id, permission_id, ...) VALUES (...) ON CONFLICT (role_id, permission_id) DO NOTHING",
        "execution_order": 3,
        "pii_presence": "NONE",
        "rollback_procedure": "TRUNCATE identity.role_permissions;"
    },
    {
        "id": "SEED-004",
        "name": "BBMP Administrative Zones & Wards Directory",
        "category": "REFERENCE_DATA",
        "target_table": "facilities",
        "environment": "PRODUCTION_SAFE",
        "record_count": 243,
        "source_authority": "Karnataka Urban Development Department (UDD) & BBMP Ward Delimitation 2023",
        "versioning": "v2023.2",
        "idempotency": "INSERT INTO identity.facilities (facility_code, ...) VALUES (...) ON CONFLICT (facility_code) DO UPDATE SET ...",
        "execution_order": 4,
        "pii_presence": "NONE",
        "rollback_procedure": "UPDATE identity.facilities SET is_active = false WHERE facility_type = 'MUNICIPAL_WARD';"
    },
    {
        "id": "SEED-005",
        "name": "Namma Clinic & UPHC Commissioned Directory",
        "category": "MASTER_DATA",
        "target_table": "facilities",
        "environment": "PRODUCTION_SAFE",
        "record_count": 450,
        "source_authority": "BBMP Health Department Official Clinic Register",
        "versioning": "v2024.3",
        "idempotency": "INSERT INTO identity.facilities (...) VALUES (...) ON CONFLICT (facility_code) DO UPDATE ...",
        "execution_order": 5,
        "pii_presence": "NONE",
        "rollback_procedure": "DELETE FROM identity.facilities WHERE facility_code LIKE 'BLR-NC-%';"
    },
    {
        "id": "SEED-006",
        "name": "WHO ICD-10 Primary Care Diagnosis Taxonomy",
        "category": "CLINICAL_REFERENCE",
        "target_table": "diagnoses",
        "environment": "PRODUCTION_SAFE",
        "record_count": 2500,
        "source_authority": "World Health Organization ICD-10 Primary Care Subset",
        "versioning": "2019-Edition",
        "idempotency": "INSERT INTO clinical.diagnostic_codes (code, ...) VALUES (...) ON CONFLICT (code) DO NOTHING",
        "execution_order": 6,
        "pii_presence": "NONE",
        "rollback_procedure": "TRUNCATE clinical.diagnostic_codes;"
    },
    {
        "id": "SEED-007",
        "name": "National Essential Drugs List (NLEM) Formulary",
        "category": "FORMULARY",
        "target_table": "formulary_drugs",
        "environment": "PRODUCTION_SAFE",
        "record_count": 1200,
        "source_authority": "National List of Essential Medicines 2022 & Karnataka State Formulary",
        "versioning": "NLEM-2022",
        "idempotency": "INSERT INTO pharmacy.formulary_drugs (generic_name, ...) VALUES (...) ON CONFLICT (generic_name, strength, dosage_form) DO UPDATE ...",
        "execution_order": 7,
        "pii_presence": "NONE",
        "rollback_procedure": "DELETE FROM pharmacy.formulary_drugs WHERE is_nlem = true;"
    },
    {
        "id": "SEED-008",
        "name": "WHO ATC Therapeutic Classification Categories",
        "category": "FORMULARY",
        "target_table": "drug_categories",
        "environment": "PRODUCTION_SAFE",
        "record_count": 150,
        "source_authority": "WHO Collaborating Centre for Drug Statistics Methodology",
        "versioning": "ATC-2024",
        "idempotency": "INSERT INTO pharmacy.drug_categories (code, ...) VALUES (...) ON CONFLICT (code) DO UPDATE ...",
        "execution_order": 8,
        "pii_presence": "NONE",
        "rollback_procedure": "TRUNCATE pharmacy.drug_categories CASCADE;"
    },
    {
        "id": "SEED-009",
        "name": "Primary Care Diagnostic Lab Investigation Catalog (LOINC)",
        "category": "CLINICAL_REFERENCE",
        "target_table": "lab_order_items",
        "environment": "PRODUCTION_SAFE",
        "record_count": 65,
        "source_authority": "Regenstrief Institute LOINC Standard & National Health Mission Lab Manual",
        "versioning": "LOINC-2.76",
        "idempotency": "INSERT INTO clinical.lab_test_catalog (loinc_code, ...) VALUES (...) ON CONFLICT (loinc_code) DO UPDATE ...",
        "execution_order": 9,
        "pii_presence": "NONE",
        "rollback_procedure": "TRUNCATE clinical.lab_test_catalog;"
    },
    {
        "id": "SEED-010",
        "name": "South African Triage Scale (SATS) Acuity Protocols",
        "category": "CLINICAL_REFERENCE",
        "target_table": "triage_assessments",
        "environment": "PRODUCTION_SAFE",
        "record_count": 25,
        "source_authority": "South African Triage Group & Ministry of Health Emergency Protocols",
        "versioning": "SATS-v2",
        "idempotency": "INSERT INTO intake.triage_protocols (...) VALUES (...) ON CONFLICT (protocol_code) DO UPDATE ...",
        "execution_order": 10,
        "pii_presence": "NONE",
        "rollback_procedure": "TRUNCATE intake.triage_protocols;"
    },
    {
        "id": "SEED-011",
        "name": "Hierarchical Platform Configuration Defaults",
        "category": "CONFIGURATION",
        "target_table": "system_configs",
        "environment": "PRODUCTION_SAFE",
        "record_count": 120,
        "source_authority": "DevOps Engineering Baseline ARCH-CFG-01",
        "versioning": "v1.0.0",
        "idempotency": "INSERT INTO identity.system_configs (config_key, ...) VALUES (...) ON CONFLICT (facility_id, config_key) DO UPDATE ...",
        "execution_order": 11,
        "pii_presence": "NONE",
        "rollback_procedure": "DELETE FROM identity.system_configs WHERE is_system_default = true;"
    },
    {
        "id": "SEED-012",
        "name": "Vaccine Cold-Chain Approved Hardware Device Models",
        "category": "MASTER_DATA",
        "target_table": "cold_chain_devices",
        "environment": "PRODUCTION_SAFE",
        "record_count": 40,
        "source_authority": "WHO PQS (Performance, Quality and Safety) Equipment Catalogue",
        "versioning": "WHO-PQS-2023",
        "idempotency": "INSERT INTO pharmacy.cold_chain_device_models (...) VALUES (...) ON CONFLICT (model_code) DO NOTHING",
        "execution_order": 12,
        "pii_presence": "NONE",
        "rollback_procedure": "TRUNCATE pharmacy.cold_chain_device_models;"
    },
    {
        "id": "SEED-013",
        "name": "Karnataka Sakala Public Service Guarantee SLAs",
        "category": "REFERENCE_DATA",
        "target_table": "grievances",
        "environment": "PRODUCTION_SAFE",
        "record_count": 35,
        "source_authority": "Karnataka Sakala Services Act 2011",
        "versioning": "Sakala-2011-Rev4",
        "idempotency": "INSERT INTO continuity.grievance_sla_rules (...) VALUES (...) ON CONFLICT (service_code) DO UPDATE ...",
        "execution_order": 13,
        "pii_presence": "NONE",
        "rollback_procedure": "TRUNCATE continuity.grievance_sla_rules;"
    },
    {
        "id": "SEED-014",
        "name": "Synthetic Multi-Role Clinic Staff Profiles (Testing Only)",
        "category": "SYNTHETIC_DEV",
        "target_table": "auth_users",
        "environment": "DEVELOPMENT_ONLY",
        "record_count": 50,
        "source_authority": "Synthetic Faker Generator (Strictly non-real data)",
        "versioning": "dev-seed-v1",
        "idempotency": "INSERT INTO identity.auth_users (...) VALUES (...) ON CONFLICT (username) DO NOTHING",
        "execution_order": 14,
        "pii_presence": "NONE (100% Synthetic Dummy Names)",
        "rollback_procedure": "DELETE FROM identity.auth_users WHERE username LIKE 'dev_test_%';"
    },
    {
        "id": "SEED-015",
        "name": "Synthetic Patient Intake Cohort & Medical History (Testing Only)",
        "category": "SYNTHETIC_DEV",
        "target_table": "patients",
        "environment": "DEVELOPMENT_ONLY",
        "record_count": 200,
        "source_authority": "Synthetic Clinical Data Generator (Zero real patient PII)",
        "versioning": "dev-seed-v1",
        "idempotency": "INSERT INTO intake.patients (...) VALUES (...) ON CONFLICT (id) DO NOTHING",
        "execution_order": 15,
        "pii_presence": "NONE (100% Synthetic Dummy Patients)",
        "rollback_procedure": "DELETE FROM intake.patients WHERE is_synthetic_demo = true;"
    }
]

SEED_MAP = {s["id"]: s for s in SEEDS}

if __name__ == "__main__":
    print(f"Loaded {len(MIGRATIONS)} Migration Blueprints (MIG-001..MIG-030).")
    print(f"Loaded {len(SEEDS)} Seed Datasets (SEED-001..SEED-015).")
