"""
db_tables_entities.py
Canonical definitions for:
- 52 Relational Tables (TABLE-001 to TABLE-052)
- 52 Conceptual Entities (ENTITY-001 to ENTITY-052)
"""

TABLES = [
    # -------------------------------------------------------------------------
    # DOMAIN 1: IDENTITY & CORE GOVERNANCE (TABLE-001 to TABLE-012)
    # -------------------------------------------------------------------------
    {
        "id": "TABLE-001",
        "name": "auth_users",
        "schema": "identity",
        "domain": "Identity & Access",
        "business_purpose": "Master registry of all authenticated healthcare personnel, administrative staff, and system service accounts.",
        "owner": "Chief Information Security Officer (CISO)",
        "description": "Stores user credentials identity root, email, mobile phone, status (ACTIVE, SUSPENDED, DEACTIVATED), and global audit timestamps.",
        "lifecycle": "Created during staff onboarding; updated on credential/profile change; soft-deleted/deactivated on offboarding; retained 10 years per audit policy.",
        "estimated_volume": "5,000 staff accounts across 198 BBMP wards",
        "growth_rate": "15% annual turnover / expansion",
        "pk": "id",
        "pk_type": "UUIDv7",
        "partition_strategy": "None (Low volume, high read frequency)",
        "retention": "RETENTION-006",
        "classification": "CLASS-004",
        "audit_requirement": "Full row change capture with IP and actor tracking",
        "source_reqs": "FR-001, FR-002, SECR-001, SECR-004",
        "workflows": "WF-001, WF-002",
        "api_consumers": "Auth Service, Staff Management API, Admin Console",
        "reporting_consumers": "Staff Activity Dashboard, Security Audit Log",
        "analytics_consumers": "Clinician Utilization Model",
        "ai_consumers": "None",
        "sync_behavior": "Full bidirectional cloud-to-edge synchronization with role-based filtering",
        "backup_priority": "CRITICAL (RPO <= 5m, RTO <= 15m)",
        "recovery_priority": "Tier 1 (Core Identity)",
        "migration_sensitivity": "HIGH (Foreign key root for all operational tables)",
        "dq_rules": "DQ-001, DQ-002",
        "lineage_refs": "LINEAGE-001"
    },
    {
        "id": "TABLE-002",
        "name": "user_credentials",
        "schema": "identity",
        "domain": "Identity & Access",
        "business_purpose": "Cryptographic authentication secrets including Argon2id password hashes, MFA totp secrets, and failed login counters.",
        "owner": "Security Engineering Lead",
        "description": "Stores high-security credentials separated from user demographic profile to isolate cryptographic attack surface.",
        "lifecycle": "Created at user registration; modified on password rotation; purged on user erasure.",
        "estimated_volume": "5,000 records",
        "growth_rate": "Proportional to auth_users",
        "pk": "id",
        "pk_type": "UUIDv7",
        "partition_strategy": "None",
        "retention": "RETENTION-011",
        "classification": "CLASS-005",
        "audit_requirement": "Strict security audit; passwords never logged in plaintext",
        "source_reqs": "SECR-001, SECR-002, SECR-003",
        "workflows": "WF-001",
        "api_consumers": "Authentication Gateway",
        "reporting_consumers": "None",
        "analytics_consumers": "None",
        "ai_consumers": "None",
        "sync_behavior": "Edge-synchronized with salted hash derivation; offline auth enabled via local cache",
        "backup_priority": "CRITICAL",
        "recovery_priority": "Tier 1",
        "migration_sensitivity": "CRITICAL (Secrets require zero-exposure migration)",
        "dq_rules": "DQ-003, DQ-004",
        "lineage_refs": "LINEAGE-001"
    },
    {
        "id": "TABLE-003",
        "name": "user_sessions",
        "schema": "identity",
        "domain": "Identity & Access",
        "business_purpose": "Active and historical web/mobile authentication sessions, JWT refresh tokens, and device fingerprints.",
        "owner": "Security Operations Center (SOC)",
        "description": "Maintains session state, expiration timestamps, IP address geolocation, and revocation status.",
        "lifecycle": "Created on login; expired after 15 minutes of inactivity; purged after 1 year.",
        "estimated_volume": "500,000 annual sessions",
        "growth_rate": "1,500 new sessions per clinic day",
        "pk": "id",
        "pk_type": "UUIDv7",
        "partition_strategy": "Range partitioned by created_at (Monthly)",
        "retention": "RETENTION-011",
        "classification": "CLASS-003",
        "audit_requirement": "Revocation and concurrent login violations logged",
        "source_reqs": "SECR-004, SECR-005",
        "workflows": "WF-001",
        "api_consumers": "Session Validation Middleware",
        "reporting_consumers": "Security Compliance Monthly Report",
        "analytics_consumers": "Staff Workload Heatmap",
        "ai_consumers": "None",
        "sync_behavior": "Edge-local sessions propagated to cloud on connectivity restore",
        "backup_priority": "STANDARD (RPO <= 1h, RTO <= 4h)",
        "recovery_priority": "Tier 3",
        "migration_sensitivity": "LOW (Transient operational state)",
        "dq_rules": "DQ-005",
        "lineage_refs": "LINEAGE-002"
    },
    {
        "id": "TABLE-004",
        "name": "roles",
        "schema": "identity",
        "domain": "Role-Based Access Control",
        "business_purpose": "Master directory of standardized organizational roles (Doctor, Staff Nurse, Pharmacist, Lab Technician, Receptionist, MOIC).",
        "owner": "BBMP Health Administration",
        "description": "Defines canonical system roles, description, hierarchy level, and default operational permissions.",
        "lifecycle": "Static reference data; updated on institutional policy revisions.",
        "estimated_volume": "30 canonical roles",
        "growth_rate": "Static (< 2 updates/year)",
        "pk": "id",
        "pk_type": "UUIDv7",
        "partition_strategy": "None",
        "retention": "RETENTION-006",
        "classification": "CLASS-002",
        "audit_requirement": "Administrative changes require double sign-off",
        "source_reqs": "FR-002, SECR-006",
        "workflows": "WF-002",
        "api_consumers": "Authorization Engine, Admin Portal",
        "reporting_consumers": "Role Distribution Matrix",
        "analytics_consumers": "None",
        "ai_consumers": "None",
        "sync_behavior": "Global broadcast to all edge clinics",
        "backup_priority": "HIGH",
        "recovery_priority": "Tier 1",
        "migration_sensitivity": "MEDIUM",
        "dq_rules": "DQ-006",
        "lineage_refs": "LINEAGE-001"
    },
    {
        "id": "TABLE-005",
        "name": "permissions",
        "schema": "identity",
        "domain": "Role-Based Access Control",
        "business_purpose": "Fine-grained operational capabilities (e.g., prescribe_medication, dispense_drug, order_lab_test).",
        "owner": "System Architecture Team",
        "description": "Atomic system entitlements mapped to resource actions across REST and GraphQL endpoints.",
        "lifecycle": "System immutable code-linked definitions; updated during software releases.",
        "estimated_volume": "180 distinct permissions",
        "growth_rate": "Increases with new module releases",
        "pk": "id",
        "pk_type": "UUIDv7",
        "partition_strategy": "None",
        "retention": "RETENTION-006",
        "classification": "CLASS-002",
        "audit_requirement": "Changes tracked via code repository and database schema migration",
        "source_reqs": "SECR-006, SECR-007",
        "workflows": "WF-002",
        "api_consumers": "Policy Enforcement Point (PEP)",
        "reporting_consumers": "Access Control List Audit",
        "analytics_consumers": "None",
        "ai_consumers": "None",
        "sync_behavior": "Global edge broadcast",
        "backup_priority": "HIGH",
        "recovery_priority": "Tier 1",
        "migration_sensitivity": "MEDIUM",
        "dq_rules": "DQ-006",
        "lineage_refs": "LINEAGE-001"
    },
    {
        "id": "TABLE-006",
        "name": "role_permissions",
        "schema": "identity",
        "domain": "Role-Based Access Control",
        "business_purpose": "Many-to-many junction mapping system permissions to roles.",
        "owner": "BBMP Health Administration",
        "description": "Associates permissions to roles with grant timestamps, active status, and granter user ID.",
        "lifecycle": "Modified during role permission matrix updates.",
        "estimated_volume": "900 mapping records",
        "growth_rate": "Low",
        "pk": "id",
        "pk_type": "UUIDv7",
        "partition_strategy": "None",
        "retention": "RETENTION-006",
        "classification": "CLASS-002",
        "audit_requirement": "Audit logged on every grant/revoke",
        "source_reqs": "FR-002, SECR-006",
        "workflows": "WF-002",
        "api_consumers": "RBAC Enforcement Engine",
        "reporting_consumers": "Role Entitlement Report",
        "analytics_consumers": "None",
        "ai_consumers": "None",
        "sync_behavior": "Global edge broadcast",
        "backup_priority": "HIGH",
        "recovery_priority": "Tier 1",
        "migration_sensitivity": "HIGH",
        "dq_rules": "DQ-006",
        "lineage_refs": "LINEAGE-001"
    },
    {
        "id": "TABLE-007",
        "name": "user_roles",
        "schema": "identity",
        "domain": "Role-Based Access Control",
        "business_purpose": "Assignments of roles to users scoped by specific healthcare facility.",
        "owner": "BBMP District Health Officer",
        "description": "Links users to roles within a facility context, supporting multi-facility roaming doctors.",
        "lifecycle": "Created upon staff facility posting; revoked on transfer.",
        "estimated_volume": "8,000 assignments",
        "growth_rate": "20% annual transfer rate",
        "pk": "id",
        "pk_type": "UUIDv7",
        "partition_strategy": "None",
        "retention": "RETENTION-006",
        "classification": "CLASS-002",
        "audit_requirement": "All assignment transfers audited with authorizing government order",
        "source_reqs": "FR-002, SECR-006",
        "workflows": "WF-002",
        "api_consumers": "Authorization Service",
        "reporting_consumers": "Facility Staffing Register",
        "analytics_consumers": "Staff Allocation Optimization",
        "ai_consumers": "None",
        "sync_behavior": "Edge-filtered by facility ID",
        "backup_priority": "HIGH",
        "recovery_priority": "Tier 1",
        "migration_sensitivity": "HIGH",
        "dq_rules": "DQ-006",
        "lineage_refs": "LINEAGE-001"
    },
    {
        "id": "TABLE-008",
        "name": "facilities",
        "schema": "identity",
        "domain": "Facility Operations",
        "business_purpose": "Master directory of Namma Clinics, Urban Primary Health Centres (UPHCs), and referral hospitals.",
        "owner": "BBMP Health Commissioner",
        "description": "Stores clinic code, official name, ward number, zone, GPS latitude/longitude, operational hours, and ABDM facility ID (HFR).",
        "lifecycle": "Created on clinic commissioning; updated on infrastructure changes; deactivated on decommissioning.",
        "estimated_volume": "450 facilities across Greater Bengaluru",
        "growth_rate": "5% annual expansion",
        "pk": "id",
        "pk_type": "UUIDv7",
        "partition_strategy": "None",
        "retention": "RETENTION-006",
        "classification": "CLASS-001",
        "audit_requirement": "All status changes and GPS adjustments audited",
        "source_reqs": "FR-003, INT-001",
        "workflows": "WF-002",
        "api_consumers": "Facility Directory API, Public Portal, Citizen Mobile App",
        "reporting_consumers": "Ward-wise Clinic Coverage Map",
        "analytics_consumers": "Geographic Access Inequality Model",
        "ai_consumers": "Catchment Area Optimizer",
        "sync_behavior": "Global edge broadcast of master metadata",
        "backup_priority": "CRITICAL",
        "recovery_priority": "Tier 1",
        "migration_sensitivity": "HIGH",
        "dq_rules": "DQ-007",
        "lineage_refs": "LINEAGE-003"
    },
    {
        "id": "TABLE-009",
        "name": "facility_rooms",
        "schema": "identity",
        "domain": "Facility Operations",
        "business_purpose": "Internal physical chambers, consultation rooms, triage booths, pharmacy counters, and sample collection points within a clinic.",
        "owner": "Medical Officer In-Charge (MOIC)",
        "description": "Represents functional service points used for queue routing, token display displays, and IoT device association.",
        "lifecycle": "Configured during clinic setup; adjusted during clinic layout reorganization.",
        "estimated_volume": "3,000 rooms/stations across clinics",
        "growth_rate": "Low",
        "pk": "id",
        "pk_type": "UUIDv7",
        "partition_strategy": "None",
        "retention": "RETENTION-019",
        "classification": "CLASS-002",
        "audit_requirement": "Room reassignment tracked for token queue audit",
        "source_reqs": "FR-004, OR-001",
        "workflows": "WF-003, WF-004",
        "api_consumers": "Queue Management Engine, Token Display Screen System",
        "reporting_consumers": "Room Utilization Report",
        "analytics_consumers": "Clinic Bottleneck Analyzer",
        "ai_consumers": "None",
        "sync_behavior": "Edge-local clinic partition",
        "backup_priority": "MEDIUM",
        "recovery_priority": "Tier 2",
        "migration_sensitivity": "MEDIUM",
        "dq_rules": "DQ-007",
        "lineage_refs": "LINEAGE-003"
    },
    {
        "id": "TABLE-010",
        "name": "staff_profiles",
        "schema": "identity",
        "domain": "Human Resources",
        "business_purpose": "Professional credentialing, medical council registration number (KMC/NMC), qualifications, and contact details of clinical staff.",
        "owner": "BBMP Health Administration HR",
        "description": "Stores doctor registration numbers, nurse certification IDs, educational degrees, specialization, and official communication channels.",
        "lifecycle": "Created at hiring; updated on degree completion/promotion; retained 10 years post-resignation.",
        "estimated_volume": "6,000 staff profiles",
        "growth_rate": "10% annual increase",
        "pk": "id",
        "pk_type": "UUIDv7",
        "partition_strategy": "None",
        "retention": "RETENTION-006",
        "classification": "CLASS-004",
        "audit_requirement": "License verification status changes strictly logged",
        "source_reqs": "FR-002, SECR-001",
        "workflows": "WF-002",
        "api_consumers": "Doctor Prescription Header Generator, Teleconsultation Roster",
        "reporting_consumers": "Clinical Credentialing Compliance Report",
        "analytics_consumers": "Doctor Productivity Index",
        "ai_consumers": "None",
        "sync_behavior": "Edge-replicated for assigned clinic personnel",
        "backup_priority": "HIGH",
        "recovery_priority": "Tier 2",
        "migration_sensitivity": "HIGH",
        "dq_rules": "DQ-008",
        "lineage_refs": "LINEAGE-001"
    },
    {
        "id": "TABLE-011",
        "name": "staff_shifts",
        "schema": "identity",
        "domain": "Human Resources",
        "business_purpose": "Daily work duty rosters, shift allocations (Morning, Afternoon, Evening), and biometric attendance records.",
        "owner": "MOIC / Facility Administrator",
        "description": "Tracks planned vs actual doctor/nurse shifts, on-call status, leave absences, and biometric punch times.",
        "lifecycle": "Created weekly/monthly; marked completed at end of shift; archived after 3 years.",
        "estimated_volume": "1,200,000 shift records over 3 years",
        "growth_rate": "3,000 records/day across all clinics",
        "pk": "id",
        "pk_type": "UUIDv7",
        "partition_strategy": "Range partitioned by shift_date (Quarterly)",
        "retention": "RETENTION-002",
        "classification": "CLASS-002",
        "audit_requirement": "Manual attendance overrides require MOIC digital signature",
        "source_reqs": "OR-002, OR-003",
        "workflows": "WF-002",
        "api_consumers": "Duty Roster Service, Time & Attendance Sync",
        "reporting_consumers": "Staff Absenteeism & Punctuality Dashboard",
        "analytics_consumers": "Workforce Demand Forecast",
        "ai_consumers": "Automated Shift Scheduler",
        "sync_behavior": "Edge-local capture with cloud synchronization",
        "backup_priority": "STANDARD",
        "recovery_priority": "Tier 3",
        "migration_sensitivity": "MEDIUM",
        "dq_rules": "DQ-008",
        "lineage_refs": "LINEAGE-002"
    },
    {
        "id": "TABLE-012",
        "name": "system_configs",
        "schema": "identity",
        "domain": "System Configuration",
        "business_purpose": "Hierarchical dynamic platform configuration parameters, feature flags, and operational thresholds.",
        "owner": "Principal DevOps Architect",
        "description": "Key-value store scoped by GLOBAL, ZONE, or FACILITY, supporting dynamic threshold adjustments without deployment.",
        "lifecycle": "Modified during operational configuration; version controlled with rollback.",
        "estimated_volume": "1,500 configuration parameters",
        "growth_rate": "Low",
        "pk": "id",
        "pk_type": "UUIDv7",
        "partition_strategy": "None",
        "retention": "RETENTION-006",
        "classification": "CLASS-002",
        "audit_requirement": "Full history of config value transitions with authorizer ID",
        "source_reqs": "NFR-001, NFR-005",
        "workflows": "WF-002",
        "api_consumers": "All Microservices via Configuration Bus",
        "reporting_consumers": "System Audit Report",
        "analytics_consumers": "None",
        "ai_consumers": "None",
        "sync_behavior": "High-priority edge push via WebSocket / MQTT",
        "backup_priority": "CRITICAL",
        "recovery_priority": "Tier 1",
        "migration_sensitivity": "HIGH",
        "dq_rules": "DQ-009",
        "lineage_refs": "LINEAGE-003"
    },

    # -------------------------------------------------------------------------
    # DOMAIN 2: PATIENT INTAKE, QUEUE & TRIAGE (TABLE-013 to TABLE-022)
    # -------------------------------------------------------------------------
    {
        "id": "TABLE-013",
        "name": "patients",
        "schema": "intake",
        "domain": "Citizen Demographics",
        "business_purpose": "Master patient index (MPI) storing primary demographic information for all registered citizens.",
        "owner": "Chief Medical Officer (CMO)",
        "description": "Stores system UHID (Unique Health Identifier), full name, gender, date of birth, blood group, marital status, and registration facility.",
        "lifecycle": "Created at citizen registration; updated on demographic verification; retained permanently or statutory 10+ years.",
        "estimated_volume": "3,500,000 citizens registered across BBMP jurisdiction",
        "growth_rate": "8,000 new patients per day across all wards",
        "pk": "id",
        "pk_type": "UUIDv7",
        "partition_strategy": "Hash partitioned by id (16 partitions)",
        "retention": "RETENTION-001",
        "classification": "CLASS-004",
        "audit_requirement": "All demographic access and edits logged with DPDP purpose code",
        "source_reqs": "FR-005, FR-006, PRIV-001, PRIV-002",
        "workflows": "WF-003",
        "api_consumers": "Registration Portal, Doctor EMR, Pharmacy Dispenser, Citizen Portal",
        "reporting_consumers": "Demographic Census Dashboard, Age-Gender Pyramids",
        "analytics_consumers": "Epidemiological Risk Modeling",
        "ai_consumers": "Patient Re-identification Prevention Model",
        "sync_behavior": "Edge-cached on-demand with local offline registration capability",
        "backup_priority": "CRITICAL (RPO <= 5m, RTO <= 15m)",
        "recovery_priority": "Tier 1",
        "migration_sensitivity": "CRITICAL",
        "dq_rules": "DQ-010, DQ-011",
        "lineage_refs": "LINEAGE-004"
    },
    {
        "id": "TABLE-014",
        "name": "patient_identifiers",
        "schema": "intake",
        "domain": "Citizen Demographics",
        "business_purpose": "External identity linkages including ABHA Number, ABHA Address, Aadhaar Vault Reference, Ration Card, and Voter ID.",
        "owner": "Lead Integration Architect",
        "description": "Stores cryptographic tokenized references to national identity systems without persisting plaintext Aadhaar numbers.",
        "lifecycle": "Added during identity linking; updated on re-authentication; revoked on consent withdrawal.",
        "estimated_volume": "5,000,000 identifier records",
        "growth_rate": "10,000 per day",
        "pk": "id",
        "pk_type": "UUIDv7",
        "partition_strategy": "Hash partitioned by patient_id (16 partitions)",
        "retention": "RETENTION-005",
        "classification": "CLASS-004",
        "audit_requirement": "Identity search and verification logged to WORM ledger",
        "source_reqs": "FR-007, INT-002, PRIV-003",
        "workflows": "WF-003",
        "api_consumers": "ABDM M1/M2 Gateway, Citizen Verification Service",
        "reporting_consumers": "ABHA Seeding Progress Dashboard",
        "analytics_consumers": "Social Protection Benefit Cross-Match",
        "ai_consumers": "None",
        "sync_behavior": "Cloud-authoritative; blind-index queried by edge nodes",
        "backup_priority": "CRITICAL",
        "recovery_priority": "Tier 1",
        "migration_sensitivity": "CRITICAL",
        "dq_rules": "DQ-012",
        "lineage_refs": "LINEAGE-004"
    },
    {
        "id": "TABLE-015",
        "name": "patient_contacts",
        "schema": "intake",
        "domain": "Citizen Demographics",
        "business_purpose": "Phone numbers, email addresses, and emergency next-of-kin contact details.",
        "owner": "Patient Experience Officer",
        "description": "Stores primary and secondary mobile numbers with OTP verification status and emergency relationship codes.",
        "lifecycle": "Created at registration; updated on phone change; retained with patient profile.",
        "estimated_volume": "4,200,000 records",
        "growth_rate": "Proportional to patient intake",
        "pk": "id",
        "pk_type": "UUIDv7",
        "partition_strategy": "Hash partitioned by patient_id (16 partitions)",
        "retention": "RETENTION-001",
        "classification": "CLASS-004",
        "audit_requirement": "Contact updates audited; mobile numbers masked on non-privileged views",
        "source_reqs": "FR-005, PRIV-001",
        "workflows": "WF-003",
        "api_consumers": "SMS Gateway, WhatsApp Notification Dispatcher",
        "reporting_consumers": "Contact Reachability Statistics",
        "analytics_consumers": "Telemedicine Churn Predictor",
        "ai_consumers": "None",
        "sync_behavior": "Edge-replicated for registered clinic patients",
        "backup_priority": "HIGH",
        "recovery_priority": "Tier 2",
        "migration_sensitivity": "HIGH",
        "dq_rules": "DQ-013",
        "lineage_refs": "LINEAGE-004"
    },
    {
        "id": "TABLE-016",
        "name": "patient_addresses",
        "schema": "intake",
        "domain": "Citizen Demographics",
        "business_purpose": "Residential addresses mapped to BBMP municipal wards, zones, and postal pin codes.",
        "owner": "Urban Health Planner",
        "description": "Provides GIS geographic attributes, door number, street, ward name, zone identifier, and census block.",
        "lifecycle": "Created at registration; updated on citizen relocation; retained with patient profile.",
        "estimated_volume": "3,800,000 records",
        "growth_rate": "Proportional to patient intake",
        "pk": "id",
        "pk_type": "UUIDv7",
        "partition_strategy": "Hash partitioned by patient_id (16 partitions)",
        "retention": "RETENTION-001",
        "classification": "CLASS-004",
        "audit_requirement": "Ward changes audited for epidemiological tracking",
        "source_reqs": "FR-005, OR-004",
        "workflows": "WF-003",
        "api_consumers": "GIS Heatmap Service, Disease Surveillance System",
        "reporting_consumers": "Ward-wise Disease Outbreak Map",
        "analytics_consumers": "Geographic Disease Clustering Model",
        "ai_consumers": "Outbreak Early Warning Algorithm",
        "sync_behavior": "Edge-replicated for catchment area",
        "backup_priority": "HIGH",
        "recovery_priority": "Tier 2",
        "migration_sensitivity": "MEDIUM",
        "dq_rules": "DQ-014",
        "lineage_refs": "LINEAGE-004"
    },
    {
        "id": "TABLE-017",
        "name": "consent_records",
        "schema": "intake",
        "domain": "Consent Management",
        "business_purpose": "Explicit citizen consent artifacts compliant with DPDP Act 2023 and ABDM Consent Framework.",
        "owner": "Data Protection Officer (DPO)",
        "description": "Stores consent purpose, validity window, clinical data scopes granted, signature/OTP hash, and revocation status.",
        "lifecycle": "Created at consent grant; updated on scope modification; terminated on revocation; retained 7 years post-expiry.",
        "estimated_volume": "6,000,000 consent artifacts",
        "growth_rate": "15,000 records/day",
        "pk": "id",
        "pk_type": "UUIDv7",
        "partition_strategy": "Range partitioned by granted_at (Semi-annual)",
        "retention": "RETENTION-005",
        "classification": "CLASS-004",
        "audit_requirement": "Strict append-only immutable logging; revocations take immediate effect",
        "source_reqs": "FR-008, PRIV-004, PRIV-005",
        "workflows": "WF-003, WF-015",
        "api_consumers": "Policy Enforcement Point, ABDM Consent Manager",
        "reporting_consumers": "DPO Statutory Audit Log",
        "analytics_consumers": "Consent Opt-In Conversion Rate",
        "ai_consumers": "None",
        "sync_behavior": "Cloud-authoritative with edge-local validation cache",
        "backup_priority": "CRITICAL",
        "recovery_priority": "Tier 1",
        "migration_sensitivity": "CRITICAL",
        "dq_rules": "DQ-015",
        "lineage_refs": "LINEAGE-005"
    },
    {
        "id": "TABLE-018",
        "name": "tokens",
        "schema": "intake",
        "domain": "Queue Management",
        "business_purpose": "Daily sequential clinic intake tokens issued to patients upon physical arrival.",
        "owner": "Clinic Operations Lead",
        "description": "Maintains token sequence number (e.g., A-042), priority category (REGULAR, EMERGENCY, GERIATRIC, PREGNANT), and issue timestamp.",
        "lifecycle": "Issued daily; updated as patient advances through stages; archived after 90 days.",
        "estimated_volume": "15,000,000 tokens annually across 450 facilities",
        "growth_rate": "45,000 tokens/day",
        "pk": "id",
        "pk_type": "UUIDv7",
        "partition_strategy": "Range partitioned by issued_at (Monthly)",
        "retention": "RETENTION-007",
        "classification": "CLASS-002",
        "audit_requirement": "Token creation, priority overrides, and cancellations logged",
        "source_reqs": "FR-009, OR-005",
        "workflows": "WF-003, WF-004",
        "api_consumers": "Token Dispenser Kiosk, Reception Terminal, Display Monitors",
        "reporting_consumers": "Daily Patient Footfall Analytics",
        "analytics_consumers": "Peak Arrival Time Distribution",
        "ai_consumers": "Patient Flow Simulator",
        "sync_behavior": "Edge-local generation with asynchronous cloud telemetry rollup",
        "backup_priority": "HIGH",
        "recovery_priority": "Tier 2",
        "migration_sensitivity": "MEDIUM",
        "dq_rules": "DQ-016",
        "lineage_refs": "LINEAGE-006"
    },
    {
        "id": "TABLE-019",
        "name": "queue_entries",
        "schema": "intake",
        "domain": "Queue Management",
        "business_purpose": "Real-time state tracking of patient movement through service stages (TRIAGE, DOCTOR, LAB, PHARMACY).",
        "owner": "Clinic Operations Lead",
        "description": "Records stage entry time, call time, completion time, serving staff ID, room ID, and wait duration metrics.",
        "lifecycle": "Created upon stage transfer; updated on call/complete; retained 90 days for operational KPI calculation.",
        "estimated_volume": "45,000,000 queue transitions annually",
        "growth_rate": "135,000 transitions/day",
        "pk": "id",
        "pk_type": "UUIDv7",
        "partition_strategy": "Range partitioned by created_at (Monthly)",
        "retention": "RETENTION-007",
        "classification": "CLASS-002",
        "audit_requirement": "Stage bypasses and emergency pre-emptions audited",
        "source_reqs": "FR-009, FR-010, OR-006",
        "workflows": "WF-004",
        "api_consumers": "Doctor Queue UI, Nurse Triage Station, Pharmacy Dispensing Queue",
        "reporting_consumers": "Stage Bottleneck & Wait Time SLA Dashboard",
        "analytics_consumers": "Service Time Efficiency Model",
        "ai_consumers": "Dynamic Queue Balancing Recommender",
        "sync_behavior": "Edge-local state machine; batch-synced to cloud analytics",
        "backup_priority": "HIGH",
        "recovery_priority": "Tier 2",
        "migration_sensitivity": "MEDIUM",
        "dq_rules": "DQ-016",
        "lineage_refs": "LINEAGE-006"
    },
    {
        "id": "TABLE-020",
        "name": "triage_assessments",
        "schema": "intake",
        "domain": "Clinical Triage",
        "business_purpose": "Nurse triage evaluations capturing chief complaints, visual acuity, emergency signs, and triage priority score.",
        "owner": "Nursing Superintendent",
        "description": "Captures South African Triage Scale (SATS) / Emergency Severity Index (ESI) category (RED, YELLOW, GREEN) and presenting symptoms.",
        "lifecycle": "Created during nursing intake; finalized before doctor consultation; retained 10 years as clinical record.",
        "estimated_volume": "10,000,000 records",
        "growth_rate": "30,000 assessments/day",
        "pk": "id",
        "pk_type": "UUIDv7",
        "partition_strategy": "Range partitioned by assessed_at (Quarterly)",
        "retention": "RETENTION-001",
        "classification": "CLASS-003",
        "audit_requirement": "Nurse signature and acuity rating changes logged",
        "source_reqs": "FR-011, CR-001",
        "workflows": "WF-004",
        "api_consumers": "Nurse Station Tablet, Doctor EMR Alert Banner",
        "reporting_consumers": "Acuity Stratification Monthly Report",
        "analytics_consumers": "Emergency Escalation Predictor",
        "ai_consumers": "Early Deterioration Detection Model",
        "sync_behavior": "Edge-local creation; immediate high-priority cloud sync",
        "backup_priority": "CRITICAL",
        "recovery_priority": "Tier 1",
        "migration_sensitivity": "HIGH",
        "dq_rules": "DQ-017",
        "lineage_refs": "LINEAGE-007"
    },
    {
        "id": "TABLE-021",
        "name": "patient_vitals",
        "schema": "intake",
        "domain": "Clinical Triage",
        "business_purpose": "Physiological measurements: systolic/diastolic blood pressure, pulse rate, SpO2, respiratory rate, temperature, height, weight, BMI.",
        "owner": "Chief Medical Officer",
        "description": "Standardized longitudinal vitals observations supporting pediatric and adult reference percentile curves.",
        "lifecycle": "Captured during triage or doctor visit; immutable clinical observations; retained 10 years.",
        "estimated_volume": "25,000,000 vitals snapshots",
        "growth_rate": "75,000 readings/day",
        "pk": "id",
        "pk_type": "UUIDv7",
        "partition_strategy": "Range partitioned by recorded_at (Quarterly)",
        "retention": "RETENTION-001",
        "classification": "CLASS-003",
        "audit_requirement": "Clinical edits append correction log with reason",
        "source_reqs": "FR-011, CR-002",
        "workflows": "WF-004, WF-005",
        "api_consumers": "Doctor Consultation EMR, NCD Surveillance Module",
        "reporting_consumers": "Hypertension Screening Progress Dashboard",
        "analytics_consumers": "Population Cardio-Metabolic Risk Model",
        "ai_consumers": "Sepsis & Vital Decompensation Alert Model",
        "sync_behavior": "Edge-local storage with bidirectional sync",
        "backup_priority": "CRITICAL",
        "recovery_priority": "Tier 1",
        "migration_sensitivity": "HIGH",
        "dq_rules": "DQ-018",
        "lineage_refs": "LINEAGE-007"
    },
    {
        "id": "TABLE-022",
        "name": "danger_alerts",
        "schema": "intake",
        "domain": "Clinical Safety",
        "business_purpose": "Real-time clinical safety alerts: critical vitals, anaphylaxis history, severe maternal pre-eclampsia, and pediatric panic thresholds.",
        "owner": "Clinical Governance Committee",
        "description": "Stores alert severity (CRITICAL, WARNING), trigger rule ID, clinician acknowledgment status, and override justification.",
        "lifecycle": "Triggered automatically by vitals/triage engine; acknowledged by clinician; archived after 5 years.",
        "estimated_volume": "1,500,000 alerts",
        "growth_rate": "4,500 alerts/day",
        "pk": "id",
        "pk_type": "UUIDv7",
        "partition_strategy": "Range partitioned by triggered_at (Quarterly)",
        "retention": "RETENTION-001",
        "classification": "CLASS-003",
        "audit_requirement": "Physician acknowledgment timestamp and override reason mandatory",
        "source_reqs": "FR-012, CR-003",
        "workflows": "WF-004, WF-005",
        "api_consumers": "Doctor Clinical Workstation, Emergency Referral Notification",
        "reporting_consumers": "Clinical Safety Incident Dashboard",
        "analytics_consumers": "Panic Threshold Optimization Model",
        "ai_consumers": "Clinical Decision Support Feedback Loop",
        "sync_behavior": "Instant edge-to-cloud push with SMS alert escalation",
        "backup_priority": "CRITICAL",
        "recovery_priority": "Tier 1",
        "migration_sensitivity": "HIGH",
        "dq_rules": "DQ-019",
        "lineage_refs": "LINEAGE-007"
    },

    # -------------------------------------------------------------------------
    # DOMAIN 3: CLINICAL CONSULTATION & ORDERS (TABLE-023 to TABLE-031)
    # -------------------------------------------------------------------------
    {
        "id": "TABLE-023",
        "name": "clinical_encounters",
        "schema": "clinical",
        "domain": "Clinical Consultation",
        "business_purpose": "Master outpatient consultation record documenting doctor-patient interaction event.",
        "owner": "Chief Medical Officer",
        "description": "Links patient, treating doctor, facility, token, encounter type (OPD, TELEMEDICINE, HOME_VISIT), start/end time, and disposition status.",
        "lifecycle": "Initiated on doctor call; completed upon digital sign-off; retained 10 years per statutory rules.",
        "estimated_volume": "12,000,000 consultations",
        "growth_rate": "35,000 encounters/day across all Namma Clinics",
        "pk": "id",
        "pk_type": "UUIDv7",
        "partition_strategy": "Range partitioned by encounter_date (Monthly)",
        "retention": "RETENTION-001",
        "classification": "CLASS-003",
        "audit_requirement": "Doctor digital signature timestamped; changes post-closure strictly prohibited",
        "source_reqs": "FR-013, FR-014, CR-004",
        "workflows": "WF-005",
        "api_consumers": "Doctor Consultation EMR, FHIR Encounter Exporter, ABDM M3 Gateway",
        "reporting_consumers": "Monthly OPD Workload Report, HMIS Return",
        "analytics_consumers": "Doctor Workload & Consultation Duration Model",
        "ai_consumers": "Clinical NLP Summarizer",
        "sync_behavior": "Edge-local capture with cloud synchronization on sign-off",
        "backup_priority": "CRITICAL (RPO <= 5m, RTO <= 15m)",
        "recovery_priority": "Tier 1",
        "migration_sensitivity": "CRITICAL",
        "dq_rules": "DQ-020",
        "lineage_refs": "LINEAGE-008"
    },
    {
        "id": "TABLE-024",
        "name": "clinical_notes",
        "schema": "clinical",
        "domain": "Clinical Consultation",
        "business_purpose": "Detailed clinical narrative in structured SOAP format (Subjective history, Objective exam, Assessment, Plan).",
        "owner": "Medical Superintendent",
        "description": "Stores clinical findings, history of present illness, examination notes, and doctor confidential clinical remarks.",
        "lifecycle": "Created during encounter; locked upon signature; addendum notes supported with version linkage.",
        "estimated_volume": "12,000,000 records",
        "growth_rate": "35,000 notes/day",
        "pk": "id",
        "pk_type": "UUIDv7",
        "partition_strategy": "Range partitioned by created_at (Monthly)",
        "retention": "RETENTION-001",
        "classification": "CLASS-005",
        "audit_requirement": "Addendums require explicit justification; original text never overwritten",
        "source_reqs": "FR-014, PRIV-001",
        "workflows": "WF-005",
        "api_consumers": "Doctor Consultation Workstation, Referral Dossier Service",
        "reporting_consumers": "None (Protected PHI)",
        "analytics_consumers": "De-identified Symptom Frequency Index",
        "ai_consumers": "Clinical Decision Support Symptom Classifier",
        "sync_behavior": "Edge-local with encrypted cloud backup",
        "backup_priority": "CRITICAL",
        "recovery_priority": "Tier 1",
        "migration_sensitivity": "CRITICAL",
        "dq_rules": "DQ-021",
        "lineage_refs": "LINEAGE-008"
    },
    {
        "id": "TABLE-025",
        "name": "diagnoses",
        "schema": "clinical",
        "domain": "Clinical Consultation",
        "business_purpose": "Coded clinical diagnoses mapped to ICD-10 and SNOMED CT taxonomies.",
        "owner": "Directorate of Public Health",
        "description": "Stores diagnosis code, display term, diagnosis type (PRIMARY, SECONDARY, PROVISIONAL, CONFIRMED), and chronic condition flag.",
        "lifecycle": "Added during encounter; retained 10 years with encounter.",
        "estimated_volume": "18,000,000 diagnosis entries",
        "growth_rate": "50,000 diagnoses/day",
        "pk": "id",
        "pk_type": "UUIDv7",
        "partition_strategy": "Range partitioned by created_at (Quarterly)",
        "retention": "RETENTION-001",
        "classification": "CLASS-003",
        "audit_requirement": "Diagnostic changes post-encounter logged to medical audit ledger",
        "source_reqs": "FR-015, CR-005, INT-003",
        "workflows": "WF-005",
        "api_consumers": "Disease Surveillance System (IDSP), NCD Registry Module",
        "reporting_consumers": "Communicable Disease Outbreak Report, Top-10 Morbidity Dashboard",
        "analytics_consumers": "Epidemic Transmission Velocity Model",
        "ai_consumers": "Automated ICD-10 Coding Assistant",
        "sync_behavior": "Edge-captured; batched to cloud disease surveillance",
        "backup_priority": "CRITICAL",
        "recovery_priority": "Tier 1",
        "migration_sensitivity": "HIGH",
        "dq_rules": "DQ-022",
        "lineage_refs": "LINEAGE-009"
    },
    {
        "id": "TABLE-026",
        "name": "prescriptions",
        "schema": "clinical",
        "domain": "Pharmacy & Prescribing",
        "business_purpose": "Header record for electronic prescriptions issued by licensed doctors.",
        "owner": "Chief Medical Officer",
        "description": "Stores prescription number, doctor digital signature token, encounter linkage, clinical instructions, and dispensing status.",
        "lifecycle": "Issued by doctor; dispensed by pharmacy; archived after 5 years per drug regulations.",
        "estimated_volume": "11,000,000 prescriptions",
        "growth_rate": "32,000 prescriptions/day",
        "pk": "id",
        "pk_type": "UUIDv7",
        "partition_strategy": "Range partitioned by prescribed_at (Monthly)",
        "retention": "RETENTION-003",
        "classification": "CLASS-003",
        "audit_requirement": "Prescription issuance and cancellation cryptographically signed",
        "source_reqs": "FR-016, CR-006",
        "workflows": "WF-005, WF-006",
        "api_consumers": "Pharmacy Dispensing Portal, Citizen Health Locker, SMS Prescription Link",
        "reporting_consumers": "Prescribing Pattern Compliance Audit",
        "analytics_consumers": "Antibiotic Stewardship Surveillance Model",
        "ai_consumers": "Drug Interaction & Dosage Checker",
        "sync_behavior": "Immediate edge-to-edge clinic pharmacy sync; cloud archive",
        "backup_priority": "CRITICAL",
        "recovery_priority": "Tier 1",
        "migration_sensitivity": "CRITICAL",
        "dq_rules": "DQ-023",
        "lineage_refs": "LINEAGE-010"
    },
    {
        "id": "TABLE-027",
        "name": "prescription_items",
        "schema": "clinical",
        "domain": "Pharmacy & Prescribing",
        "business_purpose": "Line items for prescribed medications specifying drug, dosage form, strength, frequency, duration, and quantity.",
        "owner": "Chief Pharmacist",
        "description": "Detailed pharmacological orders linked to formulary_drugs, specifying instructions (e.g., 1 tablet after food twice daily for 5 days).",
        "lifecycle": "Created with prescription; updated with dispensed quantities at pharmacy; retained 5 years.",
        "estimated_volume": "35,000,000 line items",
        "growth_rate": "100,000 lines/day",
        "pk": "id",
        "pk_type": "UUIDv7",
        "partition_strategy": "Range partitioned by created_at (Monthly)",
        "retention": "RETENTION-003",
        "classification": "CLASS-003",
        "audit_requirement": "Dispensing quantity overrides and generic substitutions logged",
        "source_reqs": "FR-016, FR-017, CR-006",
        "workflows": "WF-005, WF-006",
        "api_consumers": "Pharmacy Stock Allocation Service, Dispensing Barcode Scanner",
        "reporting_consumers": "Drug Consumption Breakdown Report",
        "analytics_consumers": "Formulary Demand Forecasting Model",
        "ai_consumers": "Drug-Drug Interaction Detection Model",
        "sync_behavior": "Edge-local synchronization with pharmacy module",
        "backup_priority": "CRITICAL",
        "recovery_priority": "Tier 1",
        "migration_sensitivity": "CRITICAL",
        "dq_rules": "DQ-023",
        "lineage_refs": "LINEAGE-010"
    },
    {
        "id": "TABLE-028",
        "name": "lab_orders",
        "schema": "clinical",
        "domain": "Diagnostic Services",
        "business_purpose": "Header record for diagnostic laboratory investigation requests ordered during consultation.",
        "owner": "Head of Pathology / Diagnostic Services",
        "description": "Stores order number, encounter linkage, ordering physician ID, priority (ROUTINE, STAT), and specimen collection status.",
        "lifecycle": "Ordered by physician; sample collected by lab tech; results published; retained 10 years.",
        "estimated_volume": "4,500,000 lab orders",
        "growth_rate": "12,000 orders/day",
        "pk": "id",
        "pk_type": "UUIDv7",
        "partition_strategy": "Range partitioned by ordered_at (Quarterly)",
        "retention": "RETENTION-004",
        "classification": "CLASS-003",
        "audit_requirement": "Sample collection and result sign-off audited with staff timestamps",
        "source_reqs": "FR-018, CR-007",
        "workflows": "WF-005, WF-007",
        "api_consumers": "Lab Technician Workstation, Sample Collection Barcode System",
        "reporting_consumers": "Lab Turnaround Time (TAT) SLA Dashboard",
        "analytics_consumers": "Diagnostic Utilization Rate Model",
        "ai_consumers": "Lab Test Ordering Appropriateness Advisor",
        "sync_behavior": "Edge-local order creation with cloud routing to hub laboratories",
        "backup_priority": "HIGH",
        "recovery_priority": "Tier 2",
        "migration_sensitivity": "HIGH",
        "dq_rules": "DQ-024",
        "lineage_refs": "LINEAGE-011"
    },
    {
        "id": "TABLE-029",
        "name": "lab_order_items",
        "schema": "clinical",
        "domain": "Diagnostic Services",
        "business_purpose": "Individual diagnostic tests requested (e.g., Complete Blood Count, HbA1c, Dengue NS1 Ag, Urine Routine).",
        "owner": "Head of Pathology",
        "description": "Test codes mapped to LOINC standard, specimen requirement (Serum, Whole Blood, Urine), and status (PENDING, SAMPLE_COLLECTED, ANALYZED).",
        "lifecycle": "Created with order; transitioned during lab workflow; retained 10 years.",
        "estimated_volume": "12,000,000 items",
        "growth_rate": "35,000 test items/day",
        "pk": "id",
        "pk_type": "UUIDv7",
        "partition_strategy": "Range partitioned by created_at (Quarterly)",
        "retention": "RETENTION-004",
        "classification": "CLASS-003",
        "audit_requirement": "Test cancellations require technician reason code",
        "source_reqs": "FR-018, CR-007, INT-004",
        "workflows": "WF-007",
        "api_consumers": "Lab Analyzer Interface (ASTM/HL7), Lab Worklist UI",
        "reporting_consumers": "Test Volume & Reagent Consumption Report",
        "analytics_consumers": "Diagnostic Yield & Positivity Rates",
        "ai_consumers": "None",
        "sync_behavior": "Edge-local execution; cloud sync on completion",
        "backup_priority": "HIGH",
        "recovery_priority": "Tier 2",
        "migration_sensitivity": "HIGH",
        "dq_rules": "DQ-024",
        "lineage_refs": "LINEAGE-011"
    },
    {
        "id": "TABLE-030",
        "name": "lab_results",
        "schema": "clinical",
        "domain": "Diagnostic Services",
        "business_purpose": "Verified quantitative and qualitative laboratory test results, reference ranges, and critical panic value flags.",
        "owner": "Chief Pathologist",
        "description": "Stores numeric/text observation values, measurement units (mg/dL, g/dL), biological reference ranges, and panic status (LOW, NORMAL, HIGH, PANIC).",
        "lifecycle": "Entered by technician; verified by pathologist; immutable upon verification; retained 10 years.",
        "estimated_volume": "25,000,000 test observations",
        "growth_rate": "70,000 observations/day",
        "pk": "id",
        "pk_type": "UUIDv7",
        "partition_strategy": "Range partitioned by verified_at (Quarterly)",
        "retention": "RETENTION-004",
        "classification": "CLASS-003",
        "audit_requirement": "Panic value phone escalation to doctor mandatory logged with timestamp",
        "source_reqs": "FR-019, CR-007, CR-008",
        "workflows": "WF-007",
        "api_consumers": "Doctor EMR Results Viewer, Citizen Health Locker, ABDM Diagnostic Report",
        "reporting_consumers": "Critical Lab Values Compliance Report",
        "analytics_consumers": "Ward-level Diabetes & Anemia Prevalence Trends",
        "ai_consumers": "Automated Hematology Pattern Anomaly Detector",
        "sync_behavior": "Immediate cloud sync with doctor alert trigger",
        "backup_priority": "CRITICAL",
        "recovery_priority": "Tier 1",
        "migration_sensitivity": "CRITICAL",
        "dq_rules": "DQ-025",
        "lineage_refs": "LINEAGE-011"
    },
    {
        "id": "TABLE-031",
        "name": "teleconsultations",
        "schema": "clinical",
        "domain": "Telemedicine",
        "business_purpose": "Doctor-to-specialist teleconsultation sessions linking Namma Clinic medical officers with secondary/tertiary hospital specialists.",
        "owner": "Telemedicine Program Director",
        "description": "Maintains WebRTC room identifier, session duration, specialist physician ID, audio/video quality metrics, and joint consultation clinical summary.",
        "lifecycle": "Scheduled during clinic visit; completed upon call termination; retained 10 years per Telemedicine Practice Guidelines.",
        "estimated_volume": "350,000 teleconsultations",
        "growth_rate": "1,000 sessions/day",
        "pk": "id",
        "pk_type": "UUIDv7",
        "partition_strategy": "Range partitioned by session_start (Semi-annual)",
        "retention": "RETENTION-016",
        "classification": "CLASS-003",
        "audit_requirement": "Connection timestamps, specialist notes, and consent verified",
        "source_reqs": "FR-020, CR-009",
        "workflows": "WF-008",
        "api_consumers": "Teleconsultation Gateway, Video Signaling Server",
        "reporting_consumers": "Specialist Utilization & Telemedicine Reach Dashboard",
        "analytics_consumers": "Teleconsultation Resolution vs Referral Ratio",
        "ai_consumers": "Audio Transcription & Clinical Note Draft Generator",
        "sync_behavior": "Cloud-hosted WebRTC session metadata synced to clinic edge",
        "backup_priority": "HIGH",
        "recovery_priority": "Tier 2",
        "migration_sensitivity": "MEDIUM",
        "dq_rules": "DQ-026",
        "lineage_refs": "LINEAGE-012"
    },

    # -------------------------------------------------------------------------
    # DOMAIN 4: PHARMACY, INVENTORY & LOGISTICS (TABLE-032 to TABLE-042)
    # -------------------------------------------------------------------------
    {
        "id": "TABLE-032",
        "name": "formulary_drugs",
        "schema": "pharmacy",
        "domain": "Pharmaceutical Master",
        "business_purpose": "Master formulary of approved medications, generic names, dosage forms, therapeutic classes, and national drug codes.",
        "owner": "BBMP Essential Drugs Committee",
        "description": "Stores generic salt name, strength, dosage form (TABLET, SYRUP, INJECTION, OINTMENT), NLEM status, and maximum daily dose safety limits.",
        "lifecycle": "Managed by Central Formulary Committee; version-controlled annual revisions.",
        "estimated_volume": "1,200 approved drug formulations",
        "growth_rate": "Low (< 50 additions/year)",
        "pk": "id",
        "pk_type": "UUIDv7",
        "partition_strategy": "None",
        "retention": "RETENTION-009",
        "classification": "CLASS-001",
        "audit_requirement": "Formulary inclusions, deletions, and safety limit adjustments audited",
        "source_reqs": "FR-021, CR-010",
        "workflows": "WF-005, WF-006, WF-009",
        "api_consumers": "Doctor Prescription Auto-complete, Pharmacy Stock Manager",
        "reporting_consumers": "Essential Drug Formulary Availability Report",
        "analytics_consumers": "Drug Class Utilization Patterns",
        "ai_consumers": "Generic Substitution Engine",
        "sync_behavior": "Global edge broadcast to all clinic nodes",
        "backup_priority": "CRITICAL",
        "recovery_priority": "Tier 1",
        "migration_sensitivity": "HIGH",
        "dq_rules": "DQ-027",
        "lineage_refs": "LINEAGE-013"
    },
    {
        "id": "TABLE-033",
        "name": "drug_categories",
        "schema": "pharmacy",
        "domain": "Pharmaceutical Master",
        "business_purpose": "Therapeutic and anatomical classification categories (WHO ATC coding hierarchy).",
        "owner": "Clinical Pharmacology Advisor",
        "description": "Hierarchical categorization (e.g., Cardiovascular System -> Antihypertensives -> ACE Inhibitors) for reporting and safety rule enforcement.",
        "lifecycle": "Static master taxonomy; updated with formulary revisions.",
        "estimated_volume": "150 categories",
        "growth_rate": "Static",
        "pk": "id",
        "pk_type": "UUIDv7",
        "partition_strategy": "None",
        "retention": "RETENTION-009",
        "classification": "CLASS-001",
        "audit_requirement": "Taxonomy updates tracked via administrative audit",
        "source_reqs": "FR-021",
        "workflows": "WF-005, WF-009",
        "api_consumers": "Formulary Browser, Clinical Safety Engine",
        "reporting_consumers": "Therapeutic Category Expenditure Report",
        "analytics_consumers": "Category-level Consumption Forecasting",
        "ai_consumers": "None",
        "sync_behavior": "Global edge broadcast",
        "backup_priority": "HIGH",
        "recovery_priority": "Tier 1",
        "migration_sensitivity": "MEDIUM",
        "dq_rules": "DQ-027",
        "lineage_refs": "LINEAGE-013"
    },
    {
        "id": "TABLE-034",
        "name": "pharmacy_batches",
        "schema": "pharmacy",
        "domain": "Inventory & Traceability",
        "business_purpose": "Specific physical manufacturing batches of drugs received from central BBMP warehouse or state procurement agency.",
        "owner": "Central Procurement Officer",
        "description": "Stores manufacturer batch number, manufacture date, expiration date, unit procurement cost, quality testing certification, and recall flag.",
        "lifecycle": "Created upon warehouse goods receipt; expires based on manufacturer shelf life; retained 8 years for CAG audit.",
        "estimated_volume": "45,000 active and historical batches",
        "growth_rate": "8,000 new batches/year",
        "pk": "id",
        "pk_type": "UUIDv7",
        "partition_strategy": "None",
        "retention": "RETENTION-009",
        "classification": "CLASS-002",
        "audit_requirement": "Batch quality lock or recall immediately halts dispensing across all clinics",
        "source_reqs": "FR-022, CR-011",
        "workflows": "WF-006, WF-009",
        "api_consumers": "Pharmacy Dispensing UI, Warehouse Goods Inward Service",
        "reporting_consumers": "Batch Expiry Aging Dashboard, Quality Recall Status",
        "analytics_consumers": "Inventory Expiry Waste Prediction",
        "ai_consumers": "Batch Near-Expiry Redistribution Optimizer",
        "sync_behavior": "Replicated across facilities receiving shipment",
        "backup_priority": "HIGH",
        "recovery_priority": "Tier 2",
        "migration_sensitivity": "HIGH",
        "dq_rules": "DQ-028",
        "lineage_refs": "LINEAGE-014"
    },
    {
        "id": "TABLE-035",
        "name": "clinic_stock",
        "schema": "pharmacy",
        "domain": "Inventory & Traceability",
        "business_purpose": "Real-time stock balance of medications at each individual Namma Clinic pharmacy store.",
        "owner": "Clinic Pharmacist / MOIC",
        "description": "Maintains quantity on hand, reserved quantity, reorder threshold, maximum stock level, and storage bin location per batch.",
        "lifecycle": "Updated in real-time on every dispensation, inward receipt, and adjustment; active inventory ledger.",
        "estimated_volume": "250,000 stock balance records across 450 facilities",
        "growth_rate": "Proportional to facility and drug count",
        "pk": "id",
        "pk_type": "UUIDv7",
        "partition_strategy": "None",
        "retention": "RETENTION-009",
        "classification": "CLASS-002",
        "audit_requirement": "Discrepancy adjustments require physical stock count reconciliation and MOIC sign-off",
        "source_reqs": "FR-022, OR-007",
        "workflows": "WF-006, WF-009",
        "api_consumers": "Pharmacy Dispensing Point of Sale, Indent Generator",
        "reporting_consumers": "Real-time Clinic Stockout Warning Dashboard",
        "analytics_consumers": "Stock Depletion Velocity & Buffer Stock Model",
        "ai_consumers": "Automated Reorder Quantity Recommender",
        "sync_behavior": "Edge-local authoritative balance; continuous sync to cloud central inventory",
        "backup_priority": "CRITICAL",
        "recovery_priority": "Tier 1",
        "migration_sensitivity": "CRITICAL",
        "dq_rules": "DQ-029",
        "lineage_refs": "LINEAGE-014"
    },
    {
        "id": "TABLE-036",
        "name": "dispensations",
        "schema": "pharmacy",
        "domain": "Pharmacy Operations",
        "business_purpose": "Header record for the physical event of medication dispensing by a registered pharmacist.",
        "owner": "Chief Pharmacist",
        "description": "Records dispensation transaction number, prescription linkage, dispensing pharmacist ID, patient pickup timestamp, and counseling notes.",
        "lifecycle": "Created upon drug handover; immutable completed dispensation; retained 5 years.",
        "estimated_volume": "11,000,000 dispensations",
        "growth_rate": "32,000 dispensations/day",
        "pk": "id",
        "pk_type": "UUIDv7",
        "partition_strategy": "Range partitioned by dispensed_at (Monthly)",
        "retention": "RETENTION-003",
        "classification": "CLASS-003",
        "audit_requirement": "Pharmacist identity and timestamp locked on dispense completion",
        "source_reqs": "FR-023, CR-012",
        "workflows": "WF-006",
        "api_consumers": "Pharmacy Dispensing Workstation, Citizen Mobile Prescription Receipt",
        "reporting_consumers": "Pharmacy Daily Fulfillment SLA Report",
        "analytics_consumers": "Patient Medication Adherence Estimator",
        "ai_consumers": "None",
        "sync_behavior": "Edge-local capture with cloud synchronization",
        "backup_priority": "CRITICAL",
        "recovery_priority": "Tier 1",
        "migration_sensitivity": "HIGH",
        "dq_rules": "DQ-030",
        "lineage_refs": "LINEAGE-015"
    },
    {
        "id": "TABLE-037",
        "name": "dispensation_items",
        "schema": "pharmacy",
        "domain": "Pharmacy Operations",
        "business_purpose": "Detailed line items for dispensed medications linking specific batch numbers and quantities deducted from stock.",
        "owner": "Chief Pharmacist",
        "description": "Stores dispensed quantity, batch linkage, drug unit cost, expiry date at dispensation, and instructions given to citizen.",
        "lifecycle": "Created with dispensation; decrements clinic_stock; retained 5 years.",
        "estimated_volume": "33,000,000 items",
        "growth_rate": "95,000 items/day",
        "pk": "id",
        "pk_type": "UUIDv7",
        "partition_strategy": "Range partitioned by created_at (Monthly)",
        "retention": "RETENTION-003",
        "classification": "CLASS-003",
        "audit_requirement": "Batch deduction verified by cryptographic stock movement linkage",
        "source_reqs": "FR-023, CR-012",
        "workflows": "WF-006",
        "api_consumers": "Pharmacy Inventory Deductor, Barcode Dispense Validator",
        "reporting_consumers": "Monthly Drug Consumption Returns",
        "analytics_consumers": "Prescription vs Dispensation Discrepancy Rate",
        "ai_consumers": "Dispensation Error Anomaly Detector",
        "sync_behavior": "Edge-local capture with cloud rollup",
        "backup_priority": "CRITICAL",
        "recovery_priority": "Tier 1",
        "migration_sensitivity": "HIGH",
        "dq_rules": "DQ-030",
        "lineage_refs": "LINEAGE-015"
    },
    {
        "id": "TABLE-038",
        "name": "stock_movements",
        "schema": "pharmacy",
        "domain": "Inventory & Traceability",
        "business_purpose": "Double-entry immutable audit ledger for every change in drug stock (RECEIPT, DISPENSATION, TRANSFER_IN, TRANSFER_OUT, EXPIRY, DAMAGE).",
        "owner": "Chief Financial Officer (CFO) & Chief Pharmacist",
        "description": "Stores movement type, source facility, destination facility, batch ID, quantity change (+/-), running balance, and authorizing voucher.",
        "lifecycle": "Append-only immutable transaction log; retained 8 years for statutory municipal financial audits.",
        "estimated_volume": "40,000,000 movement records",
        "growth_rate": "120,000 transactions/day",
        "pk": "id",
        "pk_type": "UUIDv7",
        "partition_strategy": "Range partitioned by movement_timestamp (Quarterly)",
        "retention": "RETENTION-009",
        "classification": "CLASS-002",
        "audit_requirement": "Strict append-only ledger; running balance must equal previous balance + quantity change",
        "source_reqs": "FR-024, OR-008",
        "workflows": "WF-006, WF-009",
        "api_consumers": "Inventory Audit Service, Financial Reconciliation Pipeline",
        "reporting_consumers": "CAG Statutory Audit Ledger, Stock Shrinkage & Loss Report",
        "analytics_consumers": "Inter-Clinic Stock Transfer Optimization",
        "ai_consumers": "Inventory Leakage & Anomaly Detection Model",
        "sync_behavior": "Edge transactions sequenced and reconciled via cloud ledger",
        "backup_priority": "CRITICAL",
        "recovery_priority": "Tier 1",
        "migration_sensitivity": "CRITICAL",
        "dq_rules": "DQ-031",
        "lineage_refs": "LINEAGE-015"
    },
    {
        "id": "TABLE-039",
        "name": "drug_indents",
        "schema": "pharmacy",
        "domain": "Supply Chain & Procurement",
        "business_purpose": "Electronic drug requisition orders submitted by clinic pharmacists to the BBMP Central Medical Stores.",
        "owner": "Central Medical Stores Officer",
        "description": "Stores indent number, requisition date, approving MOIC ID, warehouse processing status (SUBMITTED, APPROVED, DISPATCHED, RECEIVED), and fulfillment dates.",
        "lifecycle": "Initiated by clinic; approved by MOIC; fulfilled by warehouse; retained 8 years.",
        "estimated_volume": "120,000 indents",
        "growth_rate": "3,000 indents/month across 450 clinics",
        "pk": "id",
        "pk_type": "UUIDv7",
        "partition_strategy": "None",
        "retention": "RETENTION-009",
        "classification": "CLASS-002",
        "audit_requirement": "Workflow approvals and delivery discrepancies audited",
        "source_reqs": "FR-025, OR-009",
        "workflows": "WF-009",
        "api_consumers": "Warehouse Management System (WMS), Clinic Indent Portal",
        "reporting_consumers": "Indent Fulfillment Lead Time Dashboard",
        "analytics_consumers": "Supply Chain Bottleneck Analysis",
        "ai_consumers": "Central Warehouse Dispatch Route Optimizer",
        "sync_behavior": "Cloud-authoritative workflow with edge notifications",
        "backup_priority": "HIGH",
        "recovery_priority": "Tier 2",
        "migration_sensitivity": "MEDIUM",
        "dq_rules": "DQ-032",
        "lineage_refs": "LINEAGE-016"
    },
    {
        "id": "TABLE-040",
        "name": "indent_items",
        "schema": "pharmacy",
        "domain": "Supply Chain & Procurement",
        "business_purpose": "Individual medication line items requested in an indent, requested quantity, approved quantity, and dispatched quantity.",
        "owner": "Central Medical Stores Officer",
        "description": "Tracks formulary_drugs linkage, current clinic stock at request time, average monthly consumption (AMC), and warehouse allocation.",
        "lifecycle": "Created with indent; updated during warehouse fulfillment; retained 8 years.",
        "estimated_volume": "1,500,000 indent items",
        "growth_rate": "35,000 items/month",
        "pk": "id",
        "pk_type": "UUIDv7",
        "partition_strategy": "None",
        "retention": "RETENTION-009",
        "classification": "CLASS-002",
        "audit_requirement": "Quantity cuts by central warehouse logged with reason code",
        "source_reqs": "FR-025, OR-009",
        "workflows": "WF-009",
        "api_consumers": "Warehouse Picking Service, Clinic Receiving Dock",
        "reporting_consumers": "Indent Fulfillment Ratio & Cut-Ratio Report",
        "analytics_consumers": "Procurement Demand Aggregation Model",
        "ai_consumers": "Automated Stock Rationing Algorithm",
        "sync_behavior": "Cloud-authoritative with edge sync",
        "backup_priority": "HIGH",
        "recovery_priority": "Tier 2",
        "migration_sensitivity": "MEDIUM",
        "dq_rules": "DQ-032",
        "lineage_refs": "LINEAGE-016"
    },
    {
        "id": "TABLE-041",
        "name": "cold_chain_devices",
        "schema": "pharmacy",
        "domain": "Cold Chain & IoT",
        "business_purpose": "Master directory of temperature-controlled storage equipment (Ice-Lined Refrigerators, Deep Freezers, Vaccine Carriers) and IoT loggers.",
        "owner": "State Immunization Officer",
        "description": "Stores device serial number, model, manufacturer, installation date, clinic room linkage, min/max safe temperature thresholds (+2C to +8C), and IoT telemetry gateway MAC address.",
        "lifecycle": "Registered on installation; calibrated annually; decommissioned on replacement; retained 3 years.",
        "estimated_volume": "1,800 devices across clinics and storage points",
        "growth_rate": "Low",
        "pk": "id",
        "pk_type": "UUIDv7",
        "partition_strategy": "None",
        "retention": "RETENTION-008",
        "classification": "CLASS-002",
        "audit_requirement": "Threshold configuration and calibration certificates audited",
        "source_reqs": "FR-026, OR-010",
        "workflows": "WF-010",
        "api_consumers": "IoT Ingestion Gateway, Cold Chain Monitoring Dashboard",
        "reporting_consumers": "UIP Vaccine Cold Chain Integrity Report",
        "analytics_consumers": "Equipment Failure Prediction Model",
        "ai_consumers": "Thermal Anomaly & Compressor Degradation Predictor",
        "sync_behavior": "Global edge broadcast to local telemetry collector",
        "backup_priority": "HIGH",
        "recovery_priority": "Tier 2",
        "migration_sensitivity": "MEDIUM",
        "dq_rules": "DQ-033",
        "lineage_refs": "LINEAGE-017"
    },
    {
        "id": "TABLE-042",
        "name": "cold_chain_telemetry",
        "schema": "pharmacy",
        "domain": "Cold Chain & IoT",
        "business_purpose": "Time-series IoT sensor readings capturing refrigerator internal temperatures, ambient temperatures, door openings, and power status.",
        "owner": "Immunization Cold Chain Technician",
        "description": "High-frequency telemetry (60-second intervals) recording temperature_celsius, humidity_percent, battery_level, door_open_flag, and alert_status.",
        "lifecycle": "Ingested continuously; active raw readings retained 180 days; hourly aggregates retained 3 years.",
        "estimated_volume": "250,000,000 sensor observations annually",
        "growth_rate": "700,000 readings/day",
        "pk": "id",
        "pk_type": "UUIDv7",
        "partition_strategy": "Range partitioned by recorded_at (Monthly)",
        "retention": "RETENTION-008",
        "classification": "CLASS-002",
        "audit_requirement": "Temperature breach (> +8C or < +2C for > 15m) triggers critical incident escalation",
        "source_reqs": "FR-026, OR-010",
        "workflows": "WF-010",
        "api_consumers": "Real-time Telemetry Stream Processor (Kafka / Flink), SMS Alert Dispatcher",
        "reporting_consumers": "Hourly Cold Chain Excursion Dashboard",
        "analytics_consumers": "Vaccine Thermal Exposure Risk Score",
        "ai_consumers": "Early Power Outage & Door Left Open Predictor",
        "sync_behavior": "Edge-buffered via MQTT; batched to cloud time-series store",
        "backup_priority": "STANDARD",
        "recovery_priority": "Tier 3",
        "migration_sensitivity": "LOW (High-volume time series)",
        "dq_rules": "DQ-034",
        "lineage_refs": "LINEAGE-017"
    },

    # -------------------------------------------------------------------------
    # DOMAIN 5: CONTINUITY OF CARE & CITIZEN ENGAGEMENT (TABLE-043 to TABLE-049)
    # -------------------------------------------------------------------------
    {
        "id": "TABLE-043",
        "name": "referrals",
        "schema": "continuity",
        "domain": "Continuity of Care",
        "business_purpose": "Outbound patient referral dossiers routing complex cases to secondary/tertiary hospitals (e.g., Bowring, Victoria, KC General).",
        "owner": "District Health Officer (DHO)",
        "description": "Stores referral number, reason, provisional diagnosis, target hospital specialty, urgency level (ROUTINE, URGENT, EMERGENCY), and transfer summary.",
        "lifecycle": "Created by Namma Clinic doctor; updated on receiving hospital triage; completed on discharge/counter-referral; retained 10 years.",
        "estimated_volume": "1,200,000 referrals",
        "growth_rate": "3,500 referrals/day",
        "pk": "id",
        "pk_type": "UUIDv7",
        "partition_strategy": "Range partitioned by referred_at (Quarterly)",
        "retention": "RETENTION-010",
        "classification": "CLASS-003",
        "audit_requirement": "Emergency referrals trigger instant SMS notification to ambulance & destination hospital",
        "source_reqs": "FR-027, CR-013, INT-005",
        "workflows": "WF-011",
        "api_consumers": "Referral Exchange Service, Secondary Hospital EMR, ABDM Health Document Bridge",
        "reporting_consumers": "Referral Closure Rate & Destination Hospital Congestion Dashboard",
        "analytics_consumers": "Referral Leakage & Non-Adherence Model",
        "ai_consumers": "Specialty Recommendation Advisor",
        "sync_behavior": "Cloud-authoritative exchange with edge clinic synchronization",
        "backup_priority": "CRITICAL",
        "recovery_priority": "Tier 1",
        "migration_sensitivity": "HIGH",
        "dq_rules": "DQ-035",
        "lineage_refs": "LINEAGE-018"
    },
    {
        "id": "TABLE-044",
        "name": "referral_counter_notes",
        "schema": "continuity",
        "domain": "Continuity of Care",
        "business_purpose": "Counter-referral clinical feedback returned by secondary hospital specialists to the referring Namma Clinic doctor.",
        "owner": "District Health Officer",
        "description": "Stores specialist final diagnosis, operative procedures performed, discharge medication plan, and recommended local follow-up protocol.",
        "lifecycle": "Created by hospital specialist; received by primary care clinic; integrated into patient health record; retained 10 years.",
        "estimated_volume": "800,000 feedback notes",
        "growth_rate": "2,200 notes/day",
        "pk": "id",
        "pk_type": "UUIDv7",
        "partition_strategy": "Range partitioned by created_at (Quarterly)",
        "retention": "RETENTION-010",
        "classification": "CLASS-003",
        "audit_requirement": "Reception and doctor review of counter-note audited",
        "source_reqs": "FR-027, CR-013",
        "workflows": "WF-011",
        "api_consumers": "Doctor Consultation EMR, Longitudinal Care Plan Service",
        "reporting_consumers": "Two-Way Referral Loop Closure Efficiency",
        "analytics_consumers": "Primary Care Diagnostic Concordance Analysis",
        "ai_consumers": "None",
        "sync_behavior": "Cloud-replicated to referring clinic",
        "backup_priority": "HIGH",
        "recovery_priority": "Tier 2",
        "migration_sensitivity": "HIGH",
        "dq_rules": "DQ-035",
        "lineage_refs": "LINEAGE-018"
    },
    {
        "id": "TABLE-045",
        "name": "ncd_episodes",
        "schema": "continuity",
        "domain": "Chronic Disease Management",
        "business_purpose": "Longitudinal episode management records for citizens with Non-Communicable Diseases (Diabetes, Hypertension, COPD, Cancer).",
        "owner": "NCD Program Officer",
        "description": "Tracks diagnosis date, disease staging, treatment target goals (e.g., HbA1c < 7.0%, BP < 130/80), lifestyle counseling status, and assigned ASHA worker.",
        "lifecycle": "Enrolled on confirmed diagnosis; actively maintained for citizen lifespan; retained 15 years.",
        "estimated_volume": "1,500,000 registered NCD patients",
        "growth_rate": "15,000 new enrollments/month",
        "pk": "id",
        "pk_type": "UUIDv7",
        "partition_strategy": "None",
        "retention": "RETENTION-013",
        "classification": "CLASS-003",
        "audit_requirement": "Target goal adjustments and risk tier transitions audited",
        "source_reqs": "FR-028, CR-014",
        "workflows": "WF-012",
        "api_consumers": "NCD Registry Portal, ASHA Mobile Tablet App, NP-NCD National Portal Sync",
        "reporting_consumers": "Ward-wise Hypertension/Diabetes Control Rate Dashboard",
        "analytics_consumers": "Cardiovascular 10-Year Risk Score (Framingham / WHO)",
        "ai_consumers": "NCD Disease Complication Early Warning Model",
        "sync_behavior": "Edge-replicated for enrolled patient catchment area",
        "backup_priority": "CRITICAL",
        "recovery_priority": "Tier 1",
        "migration_sensitivity": "HIGH",
        "dq_rules": "DQ-036",
        "lineage_refs": "LINEAGE-019"
    },
    {
        "id": "TABLE-046",
        "name": "follow_up_schedules",
        "schema": "continuity",
        "domain": "Continuity of Care",
        "business_purpose": "Scheduled follow-up dates and reminder triggers for chronic disease review, antenatal checks, and post-referral monitoring.",
        "owner": "Clinic Operations Lead",
        "description": "Maintains scheduled review date, clinical purpose, notification delivery status, attendance outcome (ATTENDED, MISSED, RESCHEDULED), and overdue flags.",
        "lifecycle": "Created at encounter discharge; updated on patient visit; archived after 3 years.",
        "estimated_volume": "18,000,000 schedules",
        "growth_rate": "50,000 schedules/day",
        "pk": "id",
        "pk_type": "UUIDv7",
        "partition_strategy": "Range partitioned by scheduled_date (Monthly)",
        "retention": "RETENTION-001",
        "classification": "CLASS-003",
        "audit_requirement": "Missed follow-up escalation to ASHA worker logged",
        "source_reqs": "FR-029, OR-011",
        "workflows": "WF-012, WF-013",
        "api_consumers": "Notification Dispatcher, Clinic Daily Appointment Calendar, ASHA Line-List",
        "reporting_consumers": "Patient Follow-up Adherence & Retention Dashboard",
        "analytics_consumers": "Care Continuity Dropout Predictor",
        "ai_consumers": "Predictive Appointment No-Show Model",
        "sync_behavior": "Edge-local view synchronized with cloud scheduler",
        "backup_priority": "HIGH",
        "recovery_priority": "Tier 2",
        "migration_sensitivity": "MEDIUM",
        "dq_rules": "DQ-037",
        "lineage_refs": "LINEAGE-020"
    },
    {
        "id": "TABLE-047",
        "name": "notifications",
        "schema": "continuity",
        "domain": "Citizen Engagement",
        "business_purpose": "Outbound citizen communications: appointment reminders, prescription links, lab ready notifications, and public health advisories.",
        "owner": "Citizen Communication Lead",
        "description": "Stores channel (SMS, WHATSAPP, VOICE_CALL), recipient mobile, template ID, message text, dispatch status (SENT, DELIVERED, FAILED), and telecom gateway DLR reference.",
        "lifecycle": "Created by triggering event; dispatched via telecom gateway; retained 12 months per TRAI regulations.",
        "estimated_volume": "40,000,000 notifications annually",
        "growth_rate": "120,000 messages/day",
        "pk": "id",
        "pk_type": "UUIDv7",
        "partition_strategy": "Range partitioned by created_at (Monthly)",
        "retention": "RETENTION-015",
        "classification": "CLASS-003",
        "audit_requirement": "Citizen opt-out preferences strictly enforced; delivery timestamps audited",
        "source_reqs": "FR-030, OR-012",
        "workflows": "WF-013",
        "api_consumers": "Telecom Aggregator Gateway (Karix / ValueFirst), Citizen App Push Service",
        "reporting_consumers": "Message Delivery Rate & Telecom Cost SLA Report",
        "analytics_consumers": "Communication Channel Effectiveness Model",
        "ai_consumers": "Optimal Notification Send-Time Optimizer",
        "sync_behavior": "Cloud-authoritative dispatch pipeline",
        "backup_priority": "STANDARD",
        "recovery_priority": "Tier 3",
        "migration_sensitivity": "LOW",
        "dq_rules": "DQ-038",
        "lineage_refs": "LINEAGE-021"
    },
    {
        "id": "TABLE-048",
        "name": "grievances",
        "schema": "continuity",
        "domain": "Citizen Grievance & Feedback",
        "business_purpose": "Citizen complaints, service feedback, and Sakala statutory grievance tickets regarding clinic services.",
        "owner": "BBMP Public Grievance Officer",
        "description": "Records Sakala grievance number, clinic linkage, category (STAFF_BEHAVIOR, DRUG_UNAVAILABLE, WAIT_TIME, FACILITY_CLEANLINESS), SLA deadline, and resolution details.",
        "lifecycle": "Filed by citizen/helpdesk; assigned to MOIC/DHO; resolved with citizen sign-off; retained 5 years.",
        "estimated_volume": "250,000 grievances",
        "growth_rate": "8,000 grievances/month",
        "pk": "id",
        "pk_type": "UUIDv7",
        "partition_strategy": "Range partitioned by filed_at (Semi-annual)",
        "retention": "RETENTION-014",
        "classification": "CLASS-002",
        "audit_requirement": "SLA breach automatically escalates to Commissioner with immutable timestamp",
        "source_reqs": "FR-031, OR-013",
        "workflows": "WF-014",
        "api_consumers": "Sakala Portal Gateway, Citizen Grievance App, DHO Review Portal",
        "reporting_consumers": "Sakala SLA Compliance & Ward Grievance Heatmap",
        "analytics_consumers": "Clinic Dissatisfaction Root Cause Analyzer",
        "ai_consumers": "Automated Grievance Classification & Priority Tagger",
        "sync_behavior": "Cloud-authoritative with edge-local complaint capture",
        "backup_priority": "HIGH",
        "recovery_priority": "Tier 2",
        "migration_sensitivity": "MEDIUM",
        "dq_rules": "DQ-039",
        "lineage_refs": "LINEAGE-022"
    },
    {
        "id": "TABLE-049",
        "name": "helpdesk_tickets",
        "schema": "continuity",
        "domain": "IT & Infrastructure Support",
        "business_purpose": "Internal facility equipment breakdowns, IT hardware tickets, solar inverter faults, and peripheral maintenance requests.",
        "owner": "IT Infrastructure Lead",
        "description": "Maintains ticket ID, facility linkage, asset type (TABLET, THERMAL_PRINTER, POWER_BACKUP, IOT_GATEWAY), vendor SLA deadline, and technician fix notes.",
        "lifecycle": "Opened by clinic staff; serviced by vendor; closed upon verification; retained 3 years.",
        "estimated_volume": "150,000 tickets",
        "growth_rate": "4,000 tickets/month",
        "pk": "id",
        "pk_type": "UUIDv7",
        "partition_strategy": "None",
        "retention": "RETENTION-019",
        "classification": "CLASS-002",
        "audit_requirement": "Hardware replacement serial numbers and vendor penalty credits audited",
        "source_reqs": "OR-014",
        "workflows": "WF-014",
        "api_consumers": "IT Service Management (ITSM) Portal, Field Technician Mobile App",
        "reporting_consumers": "Hardware Uptime SLA & Vendor Performance Dashboard",
        "analytics_consumers": "Equipment Mean Time Between Failures (MTBF)",
        "ai_consumers": "Predictive Hardware Maintenance Model",
        "sync_behavior": "Cloud-hosted with edge-local reporting form",
        "backup_priority": "STANDARD",
        "recovery_priority": "Tier 3",
        "migration_sensitivity": "LOW",
        "dq_rules": "DQ-040",
        "lineage_refs": "LINEAGE-023"
    },

    # -------------------------------------------------------------------------
    # DOMAIN 6: ENTERPRISE AUDIT, OFFLINE SYNC & INTEROPERABILITY (TABLE-050 to TABLE-052)
    # -------------------------------------------------------------------------
    {
        "id": "TABLE-050",
        "name": "audit_events",
        "schema": "audit",
        "domain": "Compliance & Security",
        "business_purpose": "Master append-only tamper-evident audit ledger capturing every critical data access, state mutation, and security event.",
        "owner": "Chief Information Security Officer",
        "description": "Cryptographically chained log storing actor ID, event category, resource URI, previous state hash, new state hash, SHA-256 HMAC chain link, and client TLS metadata.",
        "lifecycle": "Append-only immutable; written in real-time; never updated or deleted; retained 10 years in WORM storage.",
        "estimated_volume": "500,000,000 audit events",
        "growth_rate": "1,500,000 events/day",
        "pk": "id",
        "pk_type": "UUIDv7",
        "partition_strategy": "Range partitioned by event_timestamp (Monthly)",
        "retention": "RETENTION-006",
        "classification": "CLASS-004",
        "audit_requirement": "Absolute immutability; cryptographic chain break triggers emergency SOC security alert",
        "source_reqs": "SECR-008, SECR-009, PRIV-006",
        "workflows": "WF-001 through WF-025",
        "api_consumers": "Security Information and Event Management (SIEM), Forensic Query Engine",
        "reporting_consumers": "Statutory DPDP & ISO 27001 Audit Compliance Ledger",
        "analytics_consumers": "User Behavior Analytics (UBA) for Insider Threat Detection",
        "ai_consumers": "Anomalous Data Access Detection Model",
        "sync_behavior": "Edge-local append; guaranteed delivery push to central SIEM via encrypted queue",
        "backup_priority": "CRITICAL (WORM replication to S3 Object Lock)",
        "recovery_priority": "Tier 1",
        "migration_sensitivity": "CRITICAL (Zero truncation policy)",
        "dq_rules": "DQ-041",
        "lineage_refs": "LINEAGE-024"
    },
    {
        "id": "TABLE-051",
        "name": "offline_mutation_log",
        "schema": "sync",
        "domain": "Edge Offline Synchronization",
        "business_purpose": "Ordered journal of database mutations performed on clinic edge appliances during wide-area network outages.",
        "owner": "Edge Architecture Team",
        "description": "Stores transaction sequence number, mutation payload JSONB, table name, operation (INSERT, UPDATE), conflict resolution vector, and cloud acknowledgment status.",
        "lifecycle": "Appended during offline operations; replayed to cloud upon connectivity restoration; purged after 180 days.",
        "estimated_volume": "15,000,000 offline mutations",
        "growth_rate": "45,000 mutations/day across intermittent connections",
        "pk": "id",
        "pk_type": "UUIDv7",
        "partition_strategy": "Range partitioned by created_at (Monthly)",
        "retention": "RETENTION-012",
        "classification": "CLASS-003",
        "audit_requirement": "Sync conflict resolutions strictly logged with winning vector justification",
        "source_reqs": "NFR-006, NFR-007, ARCH-OFF-01",
        "workflows": "WF-025",
        "api_consumers": "Edge Synchronization Worker, Conflict Resolution Engine",
        "reporting_consumers": "Clinic Network Connectivity & Sync Health Dashboard",
        "analytics_consumers": "Edge Network Outage Duration Heatmap",
        "ai_consumers": "None",
        "sync_behavior": "Authoritative local edge journal; replicated to cloud reconciliation processor",
        "backup_priority": "HIGH",
        "recovery_priority": "Tier 1",
        "migration_sensitivity": "HIGH",
        "dq_rules": "DQ-042",
        "lineage_refs": "LINEAGE-025"
    },
    {
        "id": "TABLE-052",
        "name": "abdm_artifacts",
        "schema": "sync",
        "domain": "National Interoperability",
        "business_purpose": "Ayushman Bharat Digital Mission (ABDM) integration payloads, FHIR R4 document bundles, linking tokens, and consent transaction references.",
        "owner": "ABDM Integration Lead",
        "description": "Stores ABDM transaction ID, ABHA number linkage, FHIR Bundle JSONB, health information type (OPConsultation, Prescription, DiagnosticReport), and encryption key wrap.",
        "lifecycle": "Created upon ABDM push/pull; retained 7 years per National Digital Health Mission standards.",
        "estimated_volume": "12,000,000 FHIR bundles",
        "growth_rate": "35,000 artifacts/day",
        "pk": "id",
        "pk_type": "UUIDv7",
        "partition_strategy": "Range partitioned by created_at (Quarterly)",
        "retention": "RETENTION-005",
        "classification": "CLASS-003",
        "audit_requirement": "ABDM gateway request/response exchange logged with cryptographic proof",
        "source_reqs": "INT-006, INT-007, FR-032",
        "workflows": "WF-015",
        "api_consumers": "ABDM Milestone 1/2/3 Gateway, FHIR Bundle Converter",
        "reporting_consumers": "National ABDM Integration Scorecard",
        "analytics_consumers": "Inter-System Clinical Data Exchange Volume",
        "ai_consumers": "FHIR Structural Validation Engine",
        "sync_behavior": "Cloud-authoritative interoperability gateway",
        "backup_priority": "CRITICAL",
        "recovery_priority": "Tier 1",
        "migration_sensitivity": "HIGH",
        "dq_rules": "DQ-043",
        "lineage_refs": "LINEAGE-005"
    }
]

TABLE_MAP = {t["id"]: t for t in TABLES}
TABLE_NAME_MAP = {t["name"]: t for t in TABLES}

# -----------------------------------------------------------------------------
# 52 CONCEPTUAL ENTITIES (ENTITY-001 to ENTITY-052)
# Mapped 1-to-1 to domain conceptual models
# -----------------------------------------------------------------------------
ENTITIES = []
for idx, tbl in enumerate(TABLES, start=1):
    entity_id = f"ENTITY-{idx:03d}"
    ENTITIES.append({
        "id": entity_id,
        "name": tbl["name"].replace("_", " ").title(),
        "table_id": tbl["id"],
        "table_name": tbl["name"],
        "schema": tbl["schema"],
        "domain": tbl["domain"],
        "business_meaning": tbl["business_purpose"],
        "purpose": tbl["description"],
        "owner": tbl["owner"],
        "lifecycle": tbl["lifecycle"],
        "cardinality": "1:N with dependent child entities",
        "relationships": f"Associated with {tbl['domain']} domain entities",
        "business_identifiers": f"Natural domain identifiers and UUIDv7 surrogate key ({tbl['pk']})",
        "sensitive_attributes": "Demographic, Clinical, Credential, or Operational payload",
        "source_reqs": tbl["source_reqs"],
        "workflows": tbl["workflows"],
        "downstream_consumers": f"{tbl['api_consumers']}; {tbl['reporting_consumers']}",
        "retention_considerations": f"Governed by {tbl['retention']} ({tbl['classification']})"
    })

ENTITY_MAP = {e["id"]: e for e in ENTITIES}
ENTITY_NAME_MAP = {e["name"]: e for e in ENTITIES}

if __name__ == "__main__":
    print(f"Loaded {len(TABLES)} Tables (TABLE-001..TABLE-052) and {len(ENTITIES)} Conceptual Entities (ENTITY-001..ENTITY-052).")
