#!/usr/bin/env python3
"""
build_data_07_to_12.py
Builds datasets and generators for:
- 07-security-requirements.md (SECR-001 to SECR-050)
- 08-privacy-requirements.md (PRIV-001 to PRIV-050)
- 09-performance-requirements.md (PERF-001 to PERF-040)
- 10-availability-requirements.md (AVAIL-001 to AVAIL-040)
- 11-localization-requirements.md (LOC-001 to LOC-040)
- 12-accessibility-requirements.md (A11Y-001 to A11Y-040)
"""

import os

# Definition lists for SECR, PRIV, PERF, AVAIL, LOC, A11Y
from build_defs_07_12 import (
    SECR_ITEMS, PRIV_ITEMS, PERF_ITEMS, AVAIL_ITEMS, LOC_ITEMS, A11Y_ITEMS
)

def build_data_files():
    dir_path = os.path.dirname(__file__)

    # 1. data_secr.py
    with open(os.path.join(dir_path, "data_secr.py"), "w", encoding="utf-8") as f:
        f.write('#!/usr/bin/env python3\n"""data_secr.py: 50 Security Requirements (SECR-001 to SECR-050)"""\n\nSECR_REQUIREMENTS = [\n')
        for i, item in enumerate(SECR_ITEMS, 1):
            (req_id, title, threat, attack, control, impl, vmethod, stest, aevidence) = item
            statement = f"The platform SHALL enforce {title.lower()} by implementing {control.lower()} to prevent {threat.lower()}."
            f.write("    {\n")
            f.write(f'        "id": "{req_id}",\n')
            f.write(f'        "title": "{title}",\n')
            f.write(f'        "statement": "{statement}",\n')
            f.write(f'        "domain": "Application & Infrastructure Security",\n')
            f.write(f'        "type": "Security Requirement",\n')
            f.write(f'        "priority": "MUST",\n')
            f.write(f'        "priority_rationale": "Mandatory security control protecting municipal healthcare systems against cyber threats.",\n')
            f.write(f'        "business_value": "Protects patient confidentiality, prevents ransomware, and ensures regulatory compliance.",\n')
            f.write(f'        "rationale": "Mitigates threat: {threat}.",\n')
            f.write(f'        "threat_description": "{threat}",\n')
            f.write(f'        "attack_scenario": "{attack}",\n')
            f.write(f'        "security_control": "{control}",\n')
            f.write(f'        "implementation_expectation": "{impl}",\n')
            f.write(f'        "verification_method": "{vmethod}",\n')
            f.write(f'        "security_test": "{stest}",\n')
            f.write(f'        "audit_evidence": "{aevidence}",\n')
            f.write(f'        "actor": "Security Subsystem",\n')
            f.write(f'        "persona": "PERSONA-{((i - 1) % 35) + 1:03d}",\n')
            f.write(f'        "role": "ROLE-009",\n')
            f.write(f'        "stakeholder": "STAKEHOLDER-015",\n')
            f.write(f'        "trigger": "Incoming network traffic, user authentication, or data persistence operation.",\n')
            f.write(f'        "preconditions": "Security gateway and encryption services active.",\n')
            f.write(f'        "inputs": "Network packets, authorization headers, credentials, or SQL parameters.",\n')
            f.write(f'        "validation": "Evaluated against OWASP ASVS Level 2 and CIS Benchmarks.",\n')
            f.write(f'        "main_flow": [\n')
            f.write(f'            "Incoming request reaches security boundary.",\n')
            f.write(f'            "Security filter evaluates control: {control}.",\n')
            f.write(f'            "Request verified compliant with security policy.",\n')
            f.write(f'            "Execution permitted and routed to downstream handler.",\n')
            f.write(f'            "Audit evidence emitted: {aevidence}."\n')
            f.write(f'        ],\n')
            f.write(f'        "alternate_flow": "If request exhibits anomalous rate or payload, trigger secondary MFA or CAPTCHA challenge.",\n')
            f.write(f'        "exception_flow": "If attack pattern detected ({threat}), request blocked with HTTP 403 and IP blacklisted in firewall.",\n')
            f.write(f'        "postconditions": "System state protected from unauthorized access or modification.",\n')
            f.write(f'        "state_changes": "Emits security telemetry alert and increments threat counter.",\n')
            f.write(f'        "business_rules": "BRULE-{((i - 1) % 50) + 1:03d}",\n')
            f.write(f'        "clinical_rules": "N/A — not applicable to core security transport controls",\n')
            f.write(f'        "operational_rules": "OR-{((i - 1) % 50) + 1:03d}",\n')
            f.write(f'        "security_implications": "Core security control `{req_id}`.",\n')
            f.write(f'        "privacy_implications": "Prevents unauthorized citizen data exposure under DPDP Act.",\n')
            f.write(f'        "data_implications": "Ensures cryptographic protection at rest and in transit.",\n')
            f.write(f'        "audit_requirements": "{aevidence}",\n')
            f.write(f'        "offline_behavior": "Enforced locally on workstation browser via Web Cryptography API.",\n')
            f.write(f'        "synchronization_implications": "Sync payloads signed with HMAC-SHA256 and authenticated.",\n')
            f.write(f'        "integration_implications": "All third-party integrations enforce mTLS and token authorization.",\n')
            f.write(f'        "performance_expectations": "Security filter overhead latency < 5ms.",\n')
            f.write(f'        "availability_expectations": "100% security inspection across all production endpoints.",\n')
            f.write(f'        "localization_expectations": "Security rejection error messages localized in Kannada and English.",\n')
            f.write(f'        "accessibility_expectations": "Accessible error display adhering to WCAG 2.1 AA.",\n')
            f.write(f'        "failure_behavior": "Fail-closed; reject request if security verification cannot be completed.",\n')
            f.write(f'        "recovery_behavior": "Automated security alert dispatch and administrator session review.",\n')
            f.write(f'        "observability_requirements": "OpenTelemetry security span `namma.clinic.secr.{req_id.lower()}`.",\n')
            f.write(f'        "logging_requirements": "Structured JSON security log with source_ip, user_id, and threat_type.",\n')
            f.write(f'        "metrics": "Prometheus counter `namma_clinic_secr_blocks_total{{req_id=\\"{req_id}\\"}}`.",\n')
            f.write(f'        "acceptance_criteria": [\n')
            f.write(f'            "System enforces {title.lower()} against attack scenario: {attack[:40]}...",\n')
            f.write(f'            "Security control ({control[:35]}...) blocks unauthorized access.",\n')
            f.write(f'            "Passes automated security test: {stest[:40]}...",\n')
            f.write(f'            "Produces verifiable audit evidence: {aevidence}."\n')
            f.write(f'        ],\n')
            f.write(f'        "test_type": "Automated Security Penetration & SAST Test",\n')
            f.write(f'        "test_id": "PLANNED-TEST-{600 + i:03d}",\n')
            f.write(f'        "objective_ref": "OBJECTIVE-{((i - 1) % 40) + 1:03d}",\n')
            f.write(f'        "scope_ref": "INSCOPE-{((i - 1) % 80) + 1:03d}",\n')
            f.write(f'        "stakeholder_ref": "STAKEHOLDER-015",\n')
            f.write(f'        "persona_ref": "PERSONA-{((i - 1) % 35) + 1:03d}",\n')
            f.write(f'        "risk_ref": "RISK-{((i - 1) % 60) + 1:03d}",\n')
            f.write(f'        "dependency_ref": "DEPENDENCY-{((i - 1) % 50) + 1:03d}",\n')
            f.write(f'        "milestone_ref": "MILESTONE-{((i - 1) % 40) + 1:03d}",\n')
            f.write(f'        "release_ref": "RELEASE-{((i - 1) % 20) + 1:03d}",\n')
            f.write(f'        "planned_epic": "PLANNED-EPIC-{((i - 1) % 30) + 1:03d}",\n')
            f.write(f'        "planned_feature": "PLANNED-FEATURE-{((i - 1) % 60) + 1:03d}",\n')
            f.write(f'        "planned_api": "PLANNED-API-{((i - 1) % 50) + 1:03d}",\n')
            f.write(f'        "planned_db": "PLANNED-DB-{((i - 1) % 40) + 1:03d}",\n')
            f.write(f'        "planned_ui": "PLANNED-UI-{((i - 1) % 40) + 1:03d}",\n')
            f.write(f'        "planned_test": "PLANNED-TEST-{600 + i:03d}",\n')
            f.write(f'        "related_requirements": ["PRIV-{((i - 1) % 50) + 1:03d}", "NFR-{((i - 1) % 50) + 1:03d}"],\n')
            f.write(f'        "conflicts": "None identified; balances tight security against low-bandwidth usability.",\n')
            f.write(f'        "dependencies": ["NFR-013", "NFR-014"],\n')
            f.write(f'        "open_questions": "Confirm annual third-party CERT-In security audit schedule.",\n')
            f.write(f'        "assumptions": "Underlying cloud infrastructure certified to ISO 27001 and SOC 2 Type II.",\n')
            f.write(f'        "constraints": "Security controls must not degrade client performance on 4GB RAM terminals."\n')
            f.write("    },\n")
        f.write("]\n")

    # 2. data_priv.py
    with open(os.path.join(dir_path, "data_priv.py"), "w", encoding="utf-8") as f:
        f.write('#!/usr/bin/env python3\n"""data_priv.py: 50 Privacy Requirements (PRIV-001 to PRIV-050)"""\n\nPRIV_REQUIREMENTS = [\n')
        for i, item in enumerate(PRIV_ITEMS, 1):
            (req_id, title, principle, classification, control, lawful_basis, rights_impact, aevidence) = item
            statement = f"The platform SHALL enforce {title.lower()} under the {principle.lower()} principle ({classification}) by {control.lower()}."
            f.write("    {\n")
            f.write(f'        "id": "{req_id}",\n')
            f.write(f'        "title": "{title}",\n')
            f.write(f'        "statement": "{statement}",\n')
            f.write(f'        "domain": "Digital Personal Data Protection (DPDP)",\n')
            f.write(f'        "type": "Privacy Requirement",\n')
            f.write(f'        "priority": "MUST",\n')
            f.write(f'        "priority_rationale": "Statutory privacy requirement under India Digital Personal Data Protection Act 2023.",\n')
            f.write(f'        "business_value": "Ensures citizen trust, legal protection, and constitutional privacy rights.",\n')
            f.write(f'        "rationale": "Upholds {principle} per DPDP Act 2023.",\n')
            f.write(f'        "dpdp_principle": "{principle}",\n')
            f.write(f'        "legal_classification": "{classification}",\n')
            f.write(f'        "privacy_control": "{control}",\n')
            f.write(f'        "lawful_basis": "{lawful_basis}",\n')
            f.write(f'        "data_subject_rights_impact": "{rights_impact}",\n')
            f.write(f'        "audit_evidence": "{aevidence}",\n')
            f.write(f'        "actor": "Data Protection Officer",\n')
            f.write(f'        "persona": "PERSONA-{((i - 1) % 35) + 1:03d}",\n')
            f.write(f'        "role": "ROLE-008",\n')
            f.write(f'        "stakeholder": "STAKEHOLDER-008",\n')
            f.write(f'        "trigger": "Collection, processing, sharing, or retrieval of citizen personal data.",\n')
            f.write(f'        "preconditions": "Patient registration or encounter workflow active.",\n')
            f.write(f'        "inputs": "Citizen demographic details, medical history, or consent artifacts.",\n')
            f.write(f'        "validation": "Evaluated against DPDP Act 2023 statutory guidelines and BBMP legal policy.",\n')
            f.write(f'        "main_flow": [\n')
            f.write(f'            "Citizen interacts with health service touchpoint.",\n')
            f.write(f'            "Privacy notice presented in clear Kannada and English.",\n')
            f.write(f'            "Explicit consent recorded with purpose limitation: {control}.",\n')
            f.write(f'            "Data encrypted and restricted strictly to authorized clinical roles.",\n')
            f.write(f'            "Compliance audit artifact committed: {aevidence}."\n')
            f.write(f'        ],\n')
            f.write(f'        "alternate_flow": "If citizen requests consent withdrawal or data correction, execute statutory rights workflow.",\n')
            f.write(f'        "exception_flow": "If unlawful processing attempt detected, system blocks data export and notifies BBMP DPO.",\n')
            f.write(f'        "postconditions": "Citizen health data processed strictly within lawful consent boundaries.",\n')
            f.write(f'        "state_changes": "Updates consent ledger and privacy audit records.",\n')
            f.write(f'        "business_rules": "BRULE-{((i - 1) % 50) + 1:03d}",\n')
            f.write(f'        "clinical_rules": "N/A — privacy governance requirement",\n')
            f.write(f'        "operational_rules": "OR-{((i - 1) % 50) + 1:03d}",\n')
            f.write(f'        "security_implications": "SECR-014: AES-256 field encryption and access control.",\n')
            f.write(f'        "privacy_implications": "Core privacy requirement `{req_id}` under DPDP Act 2023.",\n')
            f.write(f'        "data_implications": "Data minimization and retention limits enforced.",\n')
            f.write(f'        "audit_requirements": "{aevidence}",\n')
            f.write(f'        "offline_behavior": "Consent captured offline in IndexedDB and replayed to central DPO registry.",\n')
            f.write(f'        "synchronization_implications": "Encrypted sync payloads preserve privacy tags during transit.",\n')
            f.write(f'        "integration_implications": "Third-party ABDM data sharing gated by explicit patient consent.",\n')
            f.write(f'        "performance_expectations": "Privacy validation adds < 5ms to form processing.",\n')
            f.write(f'        "availability_expectations": "Privacy controls active on 100% of citizen-facing touchpoints.",\n')
            f.write(f'        "localization_expectations": "All consent notices fully rendered in Kannada and English.",\n')
            f.write(f'        "accessibility_expectations": "Audio and visual presentation of privacy terms for low-literacy citizens.",\n')
            f.write(f'        "failure_behavior": "Fail-closed; withhold data processing if valid consent cannot be verified.",\n')
            f.write(f'        "recovery_behavior": "Prompt staff to re-present bilingual consent notice to citizen.",\n')
            f.write(f'        "observability_requirements": "OpenTelemetry span `namma.clinic.priv.{req_id.lower()}`.",\n')
            f.write(f'        "logging_requirements": "Structured JSON log with consent_id, purpose, and timestamp.",\n')
            f.write(f'        "metrics": "Prometheus counter `namma_clinic_priv_consents_total{{req_id=\\"{req_id}\\"}}`.",\n')
            f.write(f'        "acceptance_criteria": [\n')
            f.write(f'            "System enforces {title.lower()} under principle: {principle}.",\n')
            f.write(f'            "Classified as: {classification}.",\n')
            f.write(f'            "Enforces privacy control: {control[:40]}...",\n')
            f.write(f'            "Provides verifiable compliance evidence: {aevidence}."\n')
            f.write(f'        ],\n')
            f.write(f'        "verification_method": "Automated Privacy Compliance Audit & Legal Review",\n')
            f.write(f'        "test_type": "Privacy & Data Protection Test",\n')
            f.write(f'        "test_id": "PLANNED-TEST-{700 + i:03d}",\n')
            f.write(f'        "objective_ref": "OBJECTIVE-{((i - 1) % 40) + 1:03d}",\n')
            f.write(f'        "scope_ref": "INSCOPE-{((i - 1) % 80) + 1:03d}",\n')
            f.write(f'        "stakeholder_ref": "STAKEHOLDER-008",\n')
            f.write(f'        "persona_ref": "PERSONA-{((i - 1) % 35) + 1:03d}",\n')
            f.write(f'        "risk_ref": "RISK-{((i - 1) % 60) + 1:03d}",\n')
            f.write(f'        "dependency_ref": "DEPENDENCY-{((i - 1) % 50) + 1:03d}",\n')
            f.write(f'        "milestone_ref": "MILESTONE-{((i - 1) % 40) + 1:03d}",\n')
            f.write(f'        "release_ref": "RELEASE-{((i - 1) % 20) + 1:03d}",\n')
            f.write(f'        "planned_epic": "PLANNED-EPIC-{((i - 1) % 30) + 1:03d}",\n')
            f.write(f'        "planned_feature": "PLANNED-FEATURE-{((i - 1) % 60) + 1:03d}",\n')
            f.write(f'        "planned_api": "PLANNED-API-{((i - 1) % 50) + 1:03d}",\n')
            f.write(f'        "planned_db": "PLANNED-DB-{((i - 1) % 40) + 1:03d}",\n')
            f.write(f'        "planned_ui": "PLANNED-UI-{((i - 1) % 40) + 1:03d}",\n')
            f.write(f'        "planned_test": "PLANNED-TEST-{700 + i:03d}",\n')
            f.write(f'        "related_requirements": ["SECR-{((i - 1) % 50) + 1:03d}", "BRULE-{((i - 1) % 50) + 1:03d}"],\n')
            f.write(f'        "conflicts": "None identified; balances privacy rights with public health statutory reporting.",\n')
            f.write(f'        "dependencies": ["SECR-014"],\n')
            f.write(f'        "open_questions": "Awaiting final rules notification under DPDP Act from Ministry of Electronics and IT.",\n')
            f.write(f'        "assumptions": "BBMP Health Department appointed certified Data Protection Officer.",\n')
            f.write(f'        "constraints": "Clinical care retention laws supersede citizen deletion requests."\n')
            f.write("    },\n")
        f.write("]\n")

    # 3. data_perf.py (40 items)
    with open(os.path.join(dir_path, "data_perf.py"), "w", encoding="utf-8") as f:
        f.write('#!/usr/bin/env python3\n"""data_perf.py: 40 Performance Requirements (PERF-001 to PERF-040)"""\n\nPERF_REQUIREMENTS = [\n')
        for i, item in enumerate(PERF_ITEMS, 1):
            (req_id, title, metric_type, threshold, workload, classification, vmethod, owner) = item
            statement = f"The platform SHALL achieve {title.lower()} of {threshold} under {workload} ({classification})."
            f.write("    {\n")
            f.write(f'        "id": "{req_id}",\n')
            f.write(f'        "title": "{title}",\n')
            f.write(f'        "statement": "{statement}",\n')
            f.write(f'        "domain": "System Performance & Scalability",\n')
            f.write(f'        "type": "Performance Requirement",\n')
            f.write(f'        "priority": "MUST",\n')
            f.write(f'        "priority_rationale": "Essential performance standard ensuring fluid clinic operations under heavy footfall.",\n')
            f.write(f'        "business_value": "Eliminates operator waiting time and prevents clinic bottlenecks.",\n')
            f.write(f'        "rationale": "Maintains responsiveness: {threshold}.",\n')
            f.write(f'        "performance_metric": "{metric_type}",\n')
            f.write(f'        "target_threshold": "{threshold}",\n')
            f.write(f'        "test_workload": "{workload}",\n')
            f.write(f'        "metric_classification": "{classification}",\n')
            f.write(f'        "verification_method": "{vmethod}",\n')
            f.write(f'        "owner": "{owner}",\n')
            f.write(f'        "actor": "System Platform",\n')
            f.write(f'        "persona": "PERSONA-{((i - 1) % 35) + 1:03d}",\n')
            f.write(f'        "role": "ROLE-001",\n')
            f.write(f'        "stakeholder": "STAKEHOLDER-003",\n')
            f.write(f'        "trigger": "Active concurrent requests or batch data processing.",\n')
            f.write(f'        "preconditions": "Standard clinic operating environment.",\n')
            f.write(f'        "inputs": "Synthetic or real transaction load matching {workload}.",\n')
            f.write(f'        "validation": "Evaluated continuously via Prometheus metrics and k6 performance tests.",\n')
            f.write(f'        "main_flow": [\n')
            f.write(f'            "Workload dispatched against subsystem: {workload}.",\n')
            f.write(f'            "Subsystem processes requests concurrently.",\n')
            f.write(f'            "Latency and resource utilization measured at p95 and p99 percentiles.",\n')
            f.write(f'            "Performance confirmed strictly within SLA: {threshold}.",\n')
            f.write(f'            "Telemetry published to Grafana performance dashboard."\n')
            f.write(f'        ],\n')
            f.write(f'        "alternate_flow": "If load spikes beyond capacity, horizontal pod auto-scaler provisions additional pods.",\n')
            f.write(f'        "exception_flow": "If threshold is breached, system alerts on-call SRE and triggers rate limiting.",\n')
            f.write(f'        "postconditions": "Performance maintained conforming to {threshold}.",\n')
            f.write(f'        "state_changes": "Updates Prometheus latency histogram and counter metrics.",\n')
            f.write(f'        "business_rules": "BRULE-{((i - 1) % 50) + 1:03d}",\n')
            f.write(f'        "clinical_rules": "N/A — performance infrastructure requirement",\n')
            f.write(f'        "operational_rules": "OR-{((i - 1) % 50) + 1:03d}",\n')
            f.write(f'        "security_implications": "Rate limiting and DDoS mitigation protect performance.",\n')
            f.write(f'        "privacy_implications": "Performance testing uses synthetic, de-identified datasets.",\n')
            f.write(f'        "data_implications": "Database indexes optimized for low-latency queries.",\n')
            f.write(f'        "audit_requirements": "Continuous Prometheus histogram telemetry.",\n')
            f.write(f'        "offline_behavior": "IndexedDB read/write operations execute in <10ms on client.",\n')
            f.write(f'        "synchronization_implications": "Sync throughput maintained >=50 records/second.",\n')
            f.write(f'        "integration_implications": "External integration timeouts capped at 3000ms with circuit breakers.",\n')
            f.write(f'        "performance_expectations": "{threshold}",\n')
            f.write(f'        "availability_expectations": "Maintained across 99.5% of operating window.",\n')
            f.write(f'        "localization_expectations": "Zero latency degradation when rendering Kannada typography.",\n')
            f.write(f'        "accessibility_expectations": "Smooth 60 FPS UI transitions for accessible navigation.",\n')
            f.write(f'        "failure_behavior": "Graceful queuing of requests during temporary traffic spikes.",\n')
            f.write(f'        "recovery_behavior": "Automated queue drain and resource reclamation.",\n')
            f.write(f'        "observability_requirements": "OpenTelemetry span `namma.clinic.perf.{req_id.lower()}`.",\n')
            f.write(f'        "logging_requirements": "Structured JSON log with duration_ms and status.",\n')
            f.write(f'        "metrics": "Prometheus histogram `namma_clinic_perf_duration_seconds{{req_id=\\"{req_id}\\"}}`.",\n')
            f.write(f'        "acceptance_criteria": [\n')
            f.write(f'            "System achieves {title.lower()} conforming to {threshold}.",\n')
            f.write(f'            "Tested under workload: {workload}.",\n')
            f.write(f'            "Classified as: {classification}.",\n')
            f.write(f'            "Verified via: {vmethod[:40]}..."\n')
            f.write(f'        ],\n')
            f.write(f'        "test_type": "Automated Performance Load Test",\n')
            f.write(f'        "test_id": "PLANNED-TEST-{800 + i:03d}",\n')
            f.write(f'        "objective_ref": "OBJECTIVE-{((i - 1) % 40) + 1:03d}",\n')
            f.write(f'        "scope_ref": "INSCOPE-{((i - 1) % 80) + 1:03d}",\n')
            f.write(f'        "stakeholder_ref": "STAKEHOLDER-003",\n')
            f.write(f'        "persona_ref": "PERSONA-{((i - 1) % 35) + 1:03d}",\n')
            f.write(f'        "risk_ref": "RISK-{((i - 1) % 60) + 1:03d}",\n')
            f.write(f'        "dependency_ref": "DEPENDENCY-{((i - 1) % 50) + 1:03d}",\n')
            f.write(f'        "milestone_ref": "MILESTONE-{((i - 1) % 40) + 1:03d}",\n')
            f.write(f'        "release_ref": "RELEASE-{((i - 1) % 20) + 1:03d}",\n')
            f.write(f'        "planned_epic": "PLANNED-EPIC-{((i - 1) % 30) + 1:03d}",\n')
            f.write(f'        "planned_feature": "PLANNED-FEATURE-{((i - 1) % 60) + 1:03d}",\n')
            f.write(f'        "planned_api": "PLANNED-API-{((i - 1) % 50) + 1:03d}",\n')
            f.write(f'        "planned_db": "PLANNED-DB-{((i - 1) % 40) + 1:03d}",\n')
            f.write(f'        "planned_ui": "PLANNED-UI-{((i - 1) % 40) + 1:03d}",\n')
            f.write(f'        "planned_test": "PLANNED-TEST-{800 + i:03d}",\n')
            f.write(f'        "related_requirements": ["NFR-001", "NFR-002", "AVAIL-{((i - 1) % 40) + 1:03d}"],\n')
            f.write(f'        "conflicts": "None identified; balances high throughput with minimal RAM usage.",\n')
            f.write(f'        "dependencies": ["NFR-001"],\n')
            f.write(f'        "open_questions": "Field validation on remote clinic 4G tethered connections.",\n')
            f.write(f'        "assumptions": "Server infrastructure provisioned in AWS Mumbai with auto-scaling.",\n')
            f.write(f'        "constraints": "Workstation memory footprint must not exceed 150MB."\n')
            f.write("    },\n")
        f.write("]\n")

    # 4. data_avail.py (40 items)
    with open(os.path.join(dir_path, "data_avail.py"), "w", encoding="utf-8") as f:
        f.write('#!/usr/bin/env python3\n"""data_avail.py: 40 Availability Requirements (AVAIL-001 to AVAIL-040)"""\n\nAVAIL_REQUIREMENTS = [\n')
        for i, item in enumerate(AVAIL_ITEMS, 1):
            (req_id, title, failure_cond, detection, response, fallback, recovery, vmethod) = item
            statement = f"The platform SHALL ensure {title.lower()} during {failure_cond.lower()} by detecting failure within {detection.lower()} and executing {fallback.lower()}."
            f.write("    {\n")
            f.write(f'        "id": "{req_id}",\n')
            f.write(f'        "title": "{title}",\n')
            f.write(f'        "statement": "{statement}",\n')
            f.write(f'        "domain": "High Availability & Business Continuity",\n')
            f.write(f'        "type": "Availability Requirement",\n')
            f.write(f'        "priority": "MUST",\n')
            f.write(f'        "priority_rationale": "Guarantees uninterrupted primary healthcare delivery across Greater Bengaluru.",\n')
            f.write(f'        "business_value": "Prevents citizen service denial during municipal infrastructure disruptions.",\n')
            f.write(f'        "rationale": "Addresses failure condition: {failure_cond}.",\n')
            f.write(f'        "failure_condition": "{failure_cond}",\n')
            f.write(f'        "detection_mechanism": "{detection}",\n')
            f.write(f'        "system_response": "{response}",\n')
            f.write(f'        "fallback_protocol": "{fallback}",\n')
            f.write(f'        "recovery_protocol": "{recovery}",\n')
            f.write(f'        "verification_method": "{vmethod}",\n')
            f.write(f'        "actor": "Site Reliability Engineer",\n')
            f.write(f'        "persona": "PERSONA-{((i - 1) % 35) + 1:03d}",\n')
            f.write(f'        "role": "ROLE-009",\n')
            f.write(f'        "stakeholder": "STAKEHOLDER-016",\n')
            f.write(f'        "trigger": "Component fault, infrastructure failure, or operational milestone.",\n')
            f.write(f'        "preconditions": "Platform deployed across multi-AZ architecture with offline clients.",\n')
            f.write(f'        "inputs": "Heartbeat probes, health check pings, or environmental telemetry.",\n')
            f.write(f'        "validation": "Evaluated via automated chaos engineering drills and synthetic monitoring.",\n')
            f.write(f'        "main_flow": [\n')
            f.write(f'            "Failure condition occurs: {failure_cond}.",\n')
            f.write(f'            "Detection mechanism alerts system: {detection}.",\n')
            f.write(f'            "System response executed: {response}.",\n')
            f.write(f'            "Fallback protocol active: {fallback}.",\n')
            f.write(f'            "Recovery completed: {recovery}."\n')
            f.write(f'        ],\n')
            f.write(f'        "alternate_flow": "If automated recovery stalls, trigger manual SRE incident response runbook.",\n')
            f.write(f'        "exception_flow": "If disaster is unrecoverable in primary region, initiate DNS failover to secondary DR region.",\n')
            f.write(f'        "postconditions": "Service restored to normal operational state conforming to 99.5% uptime SLA.",\n')
            f.write(f'        "state_changes": "Emits incident telemetry and updates service health status.",\n')
            f.write(f'        "business_rules": "BRULE-{((i - 1) % 50) + 1:03d}",\n')
            f.write(f'        "clinical_rules": "N/A — availability infrastructure requirement",\n')
            f.write(f'        "operational_rules": "OR-{((i - 1) % 50) + 1:03d}",\n')
            f.write(f'        "security_implications": "Failover maintains encrypted channels and auth boundaries.",\n')
            f.write(f'        "privacy_implications": "Zero data loss during failover preserves data subject records.",\n')
            f.write(f'        "data_implications": "RPO <5 minutes and RTO <30 minutes enforced.",\n')
            f.write(f'        "audit_requirements": "Continuous health probe logging and incident post-mortem records.",\n')
            f.write(f'        "offline_behavior": "8 hours autonomous local clinic continuity via Dexie.js.",\n')
            f.write(f'        "synchronization_implications": "Deterministic sync replay catches up once network returns.",\n')
            f.write(f'        "integration_implications": "Circuit breakers protect against cascading integration failures.",\n')
            f.write(f'        "performance_expectations": "Sub-minute failure detection and transparent fallback.",\n')
            f.write(f'        "availability_expectations": "Target 99.5% availability across all 183 clinics.",\n')
            f.write(f'        "localization_expectations": "Bilingual visual status indicators during degradation.",\n')
            f.write(f'        "accessibility_expectations": "High-contrast visual fallback banners and screen reader alerts.",\n')
            f.write(f'        "failure_behavior": "{fallback}",\n')
            f.write(f'        "recovery_behavior": "{recovery}",\n')
            f.write(f'        "observability_requirements": "OpenTelemetry span `namma.clinic.avail.{req_id.lower()}`.",\n')
            f.write(f'        "logging_requirements": "Structured JSON log with outage_id, duration_s, and cause.",\n')
            f.write(f'        "metrics": "Prometheus gauge `namma_clinic_service_availability{{component=\\"...\\"}}`.",\n')
            f.write(f'        "acceptance_criteria": [\n')
            f.write(f'            "System handles {failure_cond} with detection via {detection}.",\n')
            f.write(f'            "Executes fallback protocol: {fallback[:40]}...",\n')
            f.write(f'            "Completes recovery: {recovery[:40]}...",\n')
            f.write(f'            "Validated via: {vmethod[:40]}..."\n')
            f.write(f'        ],\n')
            f.write(f'        "test_type": "Chaos Engineering & Disaster Recovery Drill",\n')
            f.write(f'        "test_id": "PLANNED-TEST-{900 + i:03d}",\n')
            f.write(f'        "objective_ref": "OBJECTIVE-{((i - 1) % 40) + 1:03d}",\n')
            f.write(f'        "scope_ref": "INSCOPE-{((i - 1) % 80) + 1:03d}",\n')
            f.write(f'        "stakeholder_ref": "STAKEHOLDER-016",\n')
            f.write(f'        "persona_ref": "PERSONA-{((i - 1) % 35) + 1:03d}",\n')
            f.write(f'        "risk_ref": "RISK-{((i - 1) % 60) + 1:03d}",\n')
            f.write(f'        "dependency_ref": "DEPENDENCY-{((i - 1) % 50) + 1:03d}",\n')
            f.write(f'        "milestone_ref": "MILESTONE-{((i - 1) % 40) + 1:03d}",\n')
            f.write(f'        "release_ref": "RELEASE-{((i - 1) % 20) + 1:03d}",\n')
            f.write(f'        "planned_epic": "PLANNED-EPIC-{((i - 1) % 30) + 1:03d}",\n')
            f.write(f'        "planned_feature": "PLANNED-FEATURE-{((i - 1) % 60) + 1:03d}",\n')
            f.write(f'        "planned_api": "PLANNED-API-{((i - 1) % 50) + 1:03d}",\n')
            f.write(f'        "planned_db": "PLANNED-DB-{((i - 1) % 40) + 1:03d}",\n')
            f.write(f'        "planned_ui": "PLANNED-UI-{((i - 1) % 40) + 1:03d}",\n')
            f.write(f'        "planned_test": "PLANNED-TEST-{900 + i:03d}",\n')
            f.write(f'        "related_requirements": ["NFR-008", "NFR-009", "OFF-001"],\n')
            f.write(f'        "conflicts": "None identified; maximizes autonomy during network isolation.",\n')
            f.write(f'        "dependencies": ["NFR-008"],\n')
            f.write(f'        "open_questions": "Semi-annual chaos drill approval by BBMP IT Directorate.",\n')
            f.write(f'        "assumptions": "Clinic workstations equipped with functional UPS power backup.",\n')
            f.write(f'        "constraints": "Disaster recovery RTO must remain strictly under 30 minutes."\n')
            f.write("    },\n")
        f.write("]\n")

    # 5. data_loc.py (40 items)
    with open(os.path.join(dir_path, "data_loc.py"), "w", encoding="utf-8") as f:
        f.write('#!/usr/bin/env python3\n"""data_loc.py: 40 Localization Requirements (LOC-001 to LOC-040)"""\n\nLOC_REQUIREMENTS = [\n')
        for i, item in enumerate(LOC_ITEMS, 1):
            (req_id, title, context, standard, kn_sample, en_sample, vmethod, owner) = item
            statement = f"The platform SHALL support {title.lower()} across {context.lower()} adhering to {standard}, rendering e.g. '{kn_sample}' / '{en_sample}'."
            f.write("    {\n")
            f.write(f'        "id": "{req_id}",\n')
            f.write(f'        "title": "{title}",\n')
            f.write(f'        "statement": "{statement}",\n')
            f.write(f'        "domain": "Localization & Language Equity",\n')
            f.write(f'        "type": "Localization Requirement",\n')
            f.write(f'        "priority": "MUST",\n')
            f.write(f'        "priority_rationale": "Mandatory language equity ensuring Kannada-speaking frontline staff operate seamlessly.",\n')
            f.write(f'        "business_value": "Empowers local auxiliary healthcare workers and prevents data entry misunderstandings.",\n')
            f.write(f'        "rationale": "Context: {context} per {standard}.",\n')
            f.write(f'        "ui_context": "{context}",\n')
            f.write(f'        "standard_applied": "{standard}",\n')
            f.write(f'        "kannada_sample": "{kn_sample}",\n')
            f.write(f'        "english_sample": "{en_sample}",\n')
            f.write(f'        "verification_method": "{vmethod}",\n')
            f.write(f'        "translation_owner": "{owner}",\n')
            f.write(f'        "actor": "Localization Coordinator",\n')
            f.write(f'        "persona": "PERSONA-{((i - 1) % 35) + 1:03d}",\n')
            f.write(f'        "role": "ROLE-003",\n')
            f.write(f'        "stakeholder": "STAKEHOLDER-010",\n')
            f.write(f'        "trigger": "UI rendering, language toggle, printing, or report export.",\n')
            f.write(f'        "preconditions": "Supported browser loaded with Unicode Noto Sans Kannada fonts.",\n')
            f.write(f'        "inputs": "Locale selection code (kn or en), dynamic patient strings, or static keys.",\n')
            f.write(f'        "validation": "Evaluated against Unicode 15.0 NFC normalization and translation catalog.",\n')
            f.write(f'        "main_flow": [\n')
            f.write(f'            "User selects locale or application loads clinic default (kn).",\n')
            f.write(f'            "i18n engine resolves translation keys from localized bundle.",\n')
            f.write(f'            "Kannada typography rendered using Noto Sans Kannada: {kn_sample}.",\n')
            f.write(f'            "English parallel available instantly via runtime toggle: {en_sample}.",\n')
            f.write(f'            "Thermal printer formats bitmap font commands for ESC/POS output."\n')
            f.write(f'        ],\n')
            f.write(f'        "alternate_flow": "If specific medical term lacks direct Kannada equivalent, render codified English with Kannada phonetic chip.",\n')
            f.write(f'        "exception_flow": "If missing key detected, fallback to English with localized missing-key warning in development.",\n')
            f.write(f'        "postconditions": "User interface displays 100% grammatically correct localized strings.",\n')
            f.write(f'        "state_changes": "Updates user locale preference cookie and re-renders active UI views.",\n')
            f.write(f'        "business_rules": "BRULE-{((i - 1) % 50) + 1:03d}",\n')
            f.write(f'        "clinical_rules": "N/A — localization presentation requirement",\n')
            f.write(f'        "operational_rules": "OR-{((i - 1) % 50) + 1:03d}",\n')
            f.write(f'        "security_implications": "Input sanitization prevents Unicode homograph attacks.",\n')
            f.write(f'        "privacy_implications": "Consent notices fully rendered in verified Kannada text.",\n')
            f.write(f'        "data_implications": "UTF-8 encoding enforced across all database tables.",\n')
            f.write(f'        "audit_requirements": "Static key translation completeness audits.",\n')
            f.write(f'        "offline_behavior": "Translation dictionaries bundled client-side in PWA for full offline use.",\n')
            f.write(f'        "synchronization_implications": "Database stores canonical UTF-8 text with language tags.",\n')
            f.write(f'        "integration_implications": "Thermal printers render Kannada via raster graphics bitmap mode.",\n')
            f.write(f'        "performance_expectations": "Instant locale toggle in < 50ms with zero network request.",\n')
            f.write(f'        "availability_expectations": "100% bilingual availability across all 17 clinic workflows.",\n')
            f.write(f'        "localization_expectations": "100% complete Kannada localization.",\n')
            f.write(f'        "accessibility_expectations": "Compatible with Kannada screen reader synthesizers.",\n')
            f.write(f'        "failure_behavior": "Fallback to standard English terms with zero application crash.",\n')
            f.write(f'        "recovery_behavior": "Reload translation catalog bundle on next app startup.",\n')
            f.write(f'        "observability_requirements": "OpenTelemetry span `namma.clinic.loc.{req_id.lower()}`.",\n')
            f.write(f'        "logging_requirements": "Structured JSON log with locale, missing_keys_count, and screen.",\n')
            f.write(f'        "metrics": "Prometheus counter `namma_clinic_loc_toggles_total{{locale=\\"kn\\"|\\"en\\"}}`.",\n')
            f.write(f'        "acceptance_criteria": [\n')
            f.write(f'            "System enforces {title.lower()} adhering to {standard}.",\n')
            f.write(f'            "Renders verified Kannada sample: {kn_sample}.",\n')
            f.write(f'            "Renders verified English sample: {en_sample}.",\n')
            f.write(f'            "Verified via: {vmethod[:40]}..."\n')
            f.write(f'        ],\n')
            f.write(f'        "test_type": "Automated i18n Key Coverage & Visual Regression Test",\n')
            f.write(f'        "test_id": "PLANNED-TEST-{1000 + i:03d}",\n')
            f.write(f'        "objective_ref": "OBJECTIVE-{((i - 1) % 40) + 1:03d}",\n')
            f.write(f'        "scope_ref": "INSCOPE-{((i - 1) % 80) + 1:03d}",\n')
            f.write(f'        "stakeholder_ref": "STAKEHOLDER-010",\n')
            f.write(f'        "persona_ref": "PERSONA-{((i - 1) % 35) + 1:03d}",\n')
            f.write(f'        "risk_ref": "RISK-{((i - 1) % 60) + 1:03d}",\n')
            f.write(f'        "dependency_ref": "DEPENDENCY-{((i - 1) % 50) + 1:03d}",\n')
            f.write(f'        "milestone_ref": "MILESTONE-{((i - 1) % 40) + 1:03d}",\n')
            f.write(f'        "release_ref": "RELEASE-{((i - 1) % 20) + 1:03d}",\n')
            f.write(f'        "planned_epic": "PLANNED-EPIC-{((i - 1) % 30) + 1:03d}",\n')
            f.write(f'        "planned_feature": "PLANNED-FEATURE-{((i - 1) % 60) + 1:03d}",\n')
            f.write(f'        "planned_api": "PLANNED-API-{((i - 1) % 50) + 1:03d}",\n')
            f.write(f'        "planned_db": "PLANNED-DB-{((i - 1) % 40) + 1:03d}",\n')
            f.write(f'        "planned_ui": "PLANNED-UI-{((i - 1) % 40) + 1:03d}",\n')
            f.write(f'        "planned_test": "PLANNED-TEST-{1000 + i:03d}",\n')
            f.write(f'        "related_requirements": ["NFR-023", "NFR-024", "A11Y-{((i - 1) % 40) + 1:03d}"],\n')
            f.write(f'        "conflicts": "None identified; balances cultural vernacular with clinical terminology.",\n')
            f.write(f'        "dependencies": ["NFR-023"],\n')
            f.write(f'        "open_questions": "Validation of Kannada medical terms by Kannada Development Authority panel.",\n')
            f.write(f'        "assumptions": "Noto Sans Kannada font loaded locally in PWA service worker cache.",\n')
            f.write(f'        "constraints": "No hardcoded English strings permitted anywhere in source code."\n')
            f.write("    },\n")
        f.write("]\n")

    # 6. data_a11y.py (40 items)
    with open(os.path.join(dir_path, "data_a11y.py"), "w", encoding="utf-8") as f:
        f.write('#!/usr/bin/env python3\n"""data_a11y.py: 40 Accessibility Requirements (A11Y-001 to A11Y-040)"""\n\nA11Y_REQUIREMENTS = [\n')
        for i, item in enumerate(A11Y_ITEMS, 1):
            (req_id, title, wcag_sc, criterion, target_users, design_impl, vmethod, owner) = item
            statement = f"The platform SHALL enforce {title.lower()} adhering to {wcag_sc} ({criterion}) by {design_impl.lower()}."
            f.write("    {\n")
            f.write(f'        "id": "{req_id}",\n')
            f.write(f'        "title": "{title}",\n')
            f.write(f'        "statement": "{statement}",\n')
            f.write(f'        "domain": "Accessibility & Inclusive Usability",\n')
            f.write(f'        "type": "Accessibility Requirement",\n')
            f.write(f'        "priority": "MUST",\n')
            f.write(f'        "priority_rationale": "Mandatory accessibility compliance under WCAG 2.1 Level AA and Indian RPwD Act 2016.",\n')
            f.write(f'        "business_value": "Ensures full usability for disabled healthcare workers and frail citizens.",\n')
            f.write(f'        "rationale": "Conforms to {wcag_sc}: {criterion}.",\n')
            f.write(f'        "wcag_success_criteria": "{wcag_sc}",\n')
            f.write(f'        "accessibility_criterion": "{criterion}",\n')
            f.write(f'        "target_user_group": "{target_users}",\n')
            f.write(f'        "design_implementation": "{design_impl}",\n')
            f.write(f'        "verification_method": "{vmethod}",\n')
            f.write(f'        "owner": "{owner}",\n')
            f.write(f'        "actor": "Frontline Staff with Assistive Needs",\n')
            f.write(f'        "persona": "PERSONA-{((i - 1) % 35) + 1:03d}",\n')
            f.write(f'        "role": "ROLE-002",\n')
            f.write(f'        "stakeholder": "STAKEHOLDER-010",\n')
            f.write(f'        "trigger": "User navigation, screen reader interaction, or low-vision display scaling.",\n')
            f.write(f'        "preconditions": "UI loaded in modern browser with keyboard or assistive technology.",\n')
            f.write(f'        "inputs": "Keyboard keystrokes (Tab, Enter, Space), screen reader virtual cursor, touch events.",\n')
            f.write(f'        "validation": "Evaluated using axe-core automated audit and manual assistive technology testing.",\n')
            f.write(f'        "main_flow": [\n')
            f.write(f'            "User navigates interactive workflow using keyboard or assistive tech.",\n')
            f.write(f'            "System displays high-contrast visible focus ring: {design_impl}.",\n')
            f.write(f'            "Screen reader announces semantic roles, states, and emergency alerts.",\n')
            f.write(f'            "Interactive hit targets maintain minimum 48x48px touch boundaries.",\n')
            f.write(f'            "Workflow completed with zero reliance on mouse or fine motor skills."\n')
            f.write(f'        ],\n')
            f.write(f'        "alternate_flow": "If high-contrast theme selected, apply maximum contrast color tokens (>=7:1 ratio).",\n')
            f.write(f'        "exception_flow": "If accessibility violation detected during CI build, axe-core blocks deployment.",\n')
            f.write(f'        "postconditions": "User interface operable by individuals with diverse visual, motor, and cognitive abilities.",\n')
            f.write(f'        "state_changes": "Updates client accessibility preferences (contrast mode, font scale).",\n')
            f.write(f'        "business_rules": "BRULE-{((i - 1) % 50) + 1:03d}",\n')
            f.write(f'        "clinical_rules": "N/A — accessibility usability requirement",\n')
            f.write(f'        "operational_rules": "OR-{((i - 1) % 50) + 1:03d}",\n')
            f.write(f'        "security_implications": "Accessibility features do not bypass authentication or session locks.",\n')
            f.write(f'        "privacy_implications": "Screen reader audio output does not announce sensitive PII across public rooms.",\n')
            f.write(f'        "data_implications": "Accessibility preferences saved locally in browser localStorage.",\n')
            f.write(f'        "audit_requirements": "Automated axe-core compliance test reports.",\n')
            f.write(f'        "offline_behavior": "Accessibility styles and keyboard handlers bundled client-side for full offline use.",\n')
            f.write(f'        "synchronization_implications": "Zero network impact; entirely client-side CSS and DOM structure.",\n')
            f.write(f'        "integration_implications": "Compatible with standard Windows Narrator and NVDA screen readers.",\n')
            f.write(f'        "performance_expectations": "Accessible DOM traversal executes at 60 FPS.",\n')
            f.write(f'        "availability_expectations": "100% accessible interface across all 183 clinic installations.",\n')
            f.write(f'        "localization_expectations": "ARIA labels translated accurately into Kannada and English.",\n')
            f.write(f'        "accessibility_expectations": "WCAG 2.1 Level AA conformance.",\n')
            f.write(f'        "failure_behavior": "Graceful fallback to standard browser keyboard navigation.",\n')
            f.write(f'        "recovery_behavior": "Reset focus to document body if focused element unmounts.",\n')
            f.write(f'        "observability_requirements": "OpenTelemetry span `namma.clinic.a11y.{req_id.lower()}`.",\n')
            f.write(f'        "logging_requirements": "Structured JSON log with accessibility_mode and client_agent.",\n')
            f.write(f'        "metrics": "Prometheus counter `namma_clinic_a11y_violations_total{{req_id=\\"{req_id}\\"}}`.",\n')
            f.write(f'        "acceptance_criteria": [\n')
            f.write(f'            "System satisfies {wcag_sc}: {criterion}.",\n')
            f.write(f'            "Implements design pattern: {design_impl[:40]}...",\n')
            f.write(f'            "Zero axe-core accessibility violations.",\n')
            f.write(f'            "Verified via: {vmethod[:40]}..."\n')
            f.write(f'        ],\n')
            f.write(f'        "test_type": "Automated axe-core Accessibility Audit & NVDA Screen Reader Test",\n')
            f.write(f'        "test_id": "PLANNED-TEST-{1100 + i:03d}",\n')
            f.write(f'        "objective_ref": "OBJECTIVE-{((i - 1) % 40) + 1:03d}",\n')
            f.write(f'        "scope_ref": "INSCOPE-{((i - 1) % 80) + 1:03d}",\n')
            f.write(f'        "stakeholder_ref": "STAKEHOLDER-010",\n')
            f.write(f'        "persona_ref": "PERSONA-{((i - 1) % 35) + 1:03d}",\n')
            f.write(f'        "risk_ref": "RISK-{((i - 1) % 60) + 1:03d}",\n')
            f.write(f'        "dependency_ref": "DEPENDENCY-{((i - 1) % 50) + 1:03d}",\n')
            f.write(f'        "milestone_ref": "MILESTONE-{((i - 1) % 40) + 1:03d}",\n')
            f.write(f'        "release_ref": "RELEASE-{((i - 1) % 20) + 1:03d}",\n')
            f.write(f'        "planned_epic": "PLANNED-EPIC-{((i - 1) % 30) + 1:03d}",\n')
            f.write(f'        "planned_feature": "PLANNED-FEATURE-{((i - 1) % 60) + 1:03d}",\n')
            f.write(f'        "planned_api": "PLANNED-API-{((i - 1) % 50) + 1:03d}",\n')
            f.write(f'        "planned_db": "PLANNED-DB-{((i - 1) % 40) + 1:03d}",\n')
            f.write(f'        "planned_ui": "PLANNED-UI-{((i - 1) % 40) + 1:03d}",\n')
            f.write(f'        "planned_test": "PLANNED-TEST-{1100 + i:03d}",\n')
            f.write(f'        "related_requirements": ["NFR-026", "NFR-027", "LOC-{((i - 1) % 40) + 1:03d}"],\n')
            f.write(f'        "conflicts": "None identified; balances high information density with accessibility hit targets.",\n')
            f.write(f'        "dependencies": ["NFR-026"],\n')
            f.write(f'        "open_questions": "Dry-run evaluation with BBMP Disabled Welfare Association representatives.",\n')
            f.write(f'        "assumptions": "Clinic workstations equipped with functional audio speakers for chime alerts.",\n')
            f.write(f'        "constraints": "Focus indicator rings must not be suppressed via `outline: none` CSS rules."\n')
            f.write("    },\n")
        f.write("]\n")

    print("Created data_secr.py, data_priv.py, data_perf.py, data_avail.py, data_loc.py, data_a11y.py successfully.")

if __name__ == "__main__":
    build_data_files()
