#!/usr/bin/env python3
"""
build_data_brule_cr_or_defs.py
Contains definition tuples for:
- BRULE_ITEMS (50 items)
- CR_ITEMS (50 items)
- OR_ITEMS (50 items)
"""

from data_brule_items import BRULE_ITEMS

CR_ITEMS = [
    ("CR-001", "Hypertensive Crisis Emergency Alert", "CRITICAL_ALERT",
     "Triage vitals record SBP >= 180 mmHg or DBP >= 120 mmHg in adult patient.",
     "Severe acute elevation of blood pressure risks encephalopathy, intracranial hemorrhage, or aortic dissection.",
     "Repeat blood pressure after 5 minutes of quiet rest; if sustained, evaluate for acute target organ damage and arrange urgent secondary hospital transfer.",
     "Clinician may override if chronic stable elevation under specialist care or white-coat hypertension with documented plan.",
     "Mandatory documented clinical justification note (>=15 chars)", "Logs CRITICAL_CDS_ALERT with override justification to WORM audit store"),

    ("CR-002", "Severe Hypoxemia Emergency Alert", "CRITICAL_ALERT",
     "Pulse oximeter records SpO2 < 90% on room air in non-COPD patient.",
     "Severe hypoxemia indicates imminent respiratory failure, acute pulmonary edema, or severe pneumonia.",
     "Initiate high-flow supplemental oxygen via face mask immediately; check airway patency; summon secondary ambulance transit.",
     "Clinician override allowed only if verified artifactual reading (e.g. cold extremities, dark nail polish) after physical re-check.",
     "Mandatory documented note and re-measured SpO2 value", "Logs HYPOXEMIA_CRITICAL_ALERT and clinician action to WORM store"),

    ("CR-003", "Severe Adult Tachycardia Alert", "CRITICAL_ALERT",
     "Triage vitals record resting Heart Rate > 140 bpm in adult patient.",
     "Severe tachycardia risks hemodynamic instability, supraventricular tachycardia, or severe systemic sepsis.",
     "Assess hemodynamic stability and blood pressure immediately; check capillary glucose; prepare secondary referral.",
     "Clinician may override if acute anxiety, severe pain, or post-exertional tachycardia with clinical re-assessment.",
     "Mandatory documented clinical reason note (>=15 chars)", "Logs TACHYCARDIA_ALERT to clinical audit ledger"),

    ("CR-004", "Severe Adult Bradycardia Alert", "CRITICAL_ALERT",
     "Triage vitals record resting Heart Rate < 45 bpm in adult patient.",
     "Severe bradycardia risks complete heart block, syncope, or fatal cardiogenic shock.",
     "Assess peripheral perfusion and mental status; review current medications (beta-blockers, digoxin); prepare IV Atropine.",
     "Clinician may override if asymptomatic athletic conditioning with verified normal blood pressure.",
     "Mandatory documented clinical justification note", "Logs BRADYCARDIA_ALERT to clinical audit ledger"),

    ("CR-005", "Neonatal & Young Infant High Fever Alert", "CRITICAL_ALERT",
     "Infant aged under 3 months presents with body temperature >= 38.5C (101.3F).",
     "Young infants have immature immune systems; fever is frequently the sole presentation of life-threatening neonatal sepsis or meningitis.",
     "Do not treat as simple viral infection; arrange immediate tertiary pediatric admission; avoid outpatient oral antipyretics without sepsis workup.",
     "Clinician override permitted only if fever resolved on re-check and alternative documented clinical diagnosis confirmed.",
     "Mandatory pediatric evaluation note and referral status", "Logs NEONATAL_FEVER_CRITICAL_ALERT to WORM audit store"),

    ("CR-006", "Severe Hypoglycemia Emergency Alert", "CRITICAL_ALERT",
     "Capillary fingerstick blood glucose reads < 50 mg/dL.",
     "Severe neuroglycopenia causes irreversible brain injury, seizures, and death within minutes.",
     "Administer oral glucose powder, fruit juice, or oral sugar solution if conscious; start IV 25% Dextrose infusion if unconscious; re-check glucose in 15 mins.",
     "Clinician override permitted only if verified lab artifact and patient is completely asymptomatic with normal re-test.",
     "Mandatory documented intervention note and re-measured glucose value", "Logs HYPOGLYCEMIA_EMERGENCY_ALERT to WORM store"),

    ("CR-007", "Severe Hyperglycemia & DKA Risk Alert", "CRITICAL_ALERT",
     "Capillary blood glucose reads > 400 mg/dL (or glucometer reads 'HI').",
     "Extreme hyperglycemia risks fatal Diabetic Ketoacidosis (DKA) or Hyperosmolar Hyperglycemic State (HHS).",
     "Check urine dipstick for ketones immediately; assess hydration status; initiate normal saline IV infusion; arrange secondary hospital transfer.",
     "Clinician may override if known chronic diabetic receiving adjusted basal insulin with clear outpatient management plan.",
     "Mandatory documented management plan and ketone status note", "Logs HYPERGLYCEMIA_ALERT to clinical audit store"),

    ("CR-008", "Pediatric Severe Tachypnea Alert", "HIGH_WARNING",
     "Respiratory rate > 50/min in infant (2-11 months) or > 40/min in child (1-5 years).",
     "Tachypnea is the primary clinical sign of lower respiratory tract infection (pneumonia) in young children per WHO IMNCI.",
     "Examine child for lower chest wall indrawing and stridor; administer first dose oral Amoxicillin; arrange immediate hospital referral if indrawing present.",
     "Clinician override permitted if child was crying or agitated during counting; must re-count during calm state.",
     "Mandatory documented re-count or clinical justification", "Logs PEDIATRIC_TACHYPNEA_WARNING to clinical audit store"),

    ("CR-009", "Neonatal Hypothermia Alert", "CRITICAL_ALERT",
     "Axillary temperature reads < 35.5C (95.9F) in infant aged under 28 days.",
     "Neonatal hypothermia increases metabolic acidosis, sepsis mortality, and hypoglycemia.",
     "Initiate immediate skin-to-skin Kangaroo Mother Care; wrap baby in warm dry clothes; assess for neonatal sepsis.",
     "Clinician override allowed only if verified measurement error with normal re-check under warm ambient room.",
     "Mandatory documented re-check temperature value", "Logs NEONATAL_HYPOTHERMIA_ALERT to WORM audit store"),

    ("CR-010", "Severe Acute Malnutrition (SAM) Screening Alert", "HIGH_WARNING",
     "Mid-Upper Arm Circumference (MUAC) reads < 115 mm in child aged 6-59 months.",
     "Children with severe acute malnutrition have a 9-fold increased risk of mortality from common childhood infections.",
     "Examine child for bilateral pedal edema; perform appetite test; issue urgent referral to BBMP Nutritional Rehabilitation Center (NRC).",
     "Clinician override permitted only if child is already enrolled in active NRC follow-up with documented card.",
     "Mandatory documented nutritional referral or card number", "Logs PEDIATRIC_SAM_ALERT to child health registry"),

    ("CR-011", "Gestational Hypertension Screening Alert", "HIGH_WARNING",
     "Pregnant patient presents with SBP >= 140 mmHg or DBP >= 90 mmHg on two separate readings.",
     "Gestational hypertension increases risk of placental abruption, fetal growth restriction, and progression to pre-eclampsia.",
     "Test urine for albumin immediately; prescribe oral Labetalol or Methyldopa per national guidelines; schedule weekly ANC monitoring.",
     "Clinician override allowed if transient white-coat hypertension with documented normal home blood pressure logs.",
     "Mandatory documented obstetric plan and urine albumin status", "Logs GESTATIONAL_HTN_ALERT to maternal health registry"),

    ("CR-012", "Pre-Eclampsia with Imminent Eclampsia Red-Flags", "CRITICAL_ALERT",
     "Pregnant patient with HTN presents with severe headache, visual blurring, epigastric pain, or urine protein >= 2+.",
     "Impending eclampsia carries high risk of maternal and fetal death from generalized tonic-clonic convulsions and stroke.",
     "Administer loading dose Magnesium Sulfate (Pritchard regimen) immediately; secure IV access; arrange urgent ambulance transfer to tertiary maternity hospital.",
     "Zero override permitted without documented specialist obstetrician on-site consultation.",
     "Mandatory emergency obstetric referral documentation", "Logs PREECLAMPSIA_CRITICAL_ALERT to WORM audit store"),

    ("CR-013", "Severe Anemia in Pregnancy Alert", "CRITICAL_ALERT",
     "Hemoglobin reads < 7.0 g/dL in pregnant woman at any gestational age.",
     "Severe maternal anemia causes high risk of heart failure, postpartum hemorrhage mortality, and low birth weight.",
     "Do not rely solely on oral iron; arrange secondary maternity admission for parenteral iron sucrose or packed red cell transfusion.",
     "Clinician may override if patient is already receiving specialized parenteral iron under hospital supervision.",
     "Mandatory documented hospital admission or specialist plan", "Logs SEVERE_MATERNAL_ANEMIA_ALERT to maternal registry"),

    ("CR-014", "Suspected Postpartum Hemorrhage (PPH) Alert", "CRITICAL_ALERT",
     "Postnatal mother presents with severe vaginal bleeding (soaking >= 2 sanitary pads in 1 hour) or hypotension.",
     "Postpartum hemorrhage is the leading preventable cause of maternal death globally.",
     "Perform bimanual uterine massage immediately; administer IM Oxytocin 10 IU; insert two large-bore IV cannulae; arrange emergency ambulance transfer.",
     "Zero override; life-threatening obstetric emergency requiring immediate intervention.",
     "Mandatory emergency resuscitation and referral note", "Logs PPH_EMERGENCY_ALERT to WORM audit store"),

    ("CR-015", "Suspected Ectopic Pregnancy Rupture Alert", "CRITICAL_ALERT",
     "Woman of reproductive age presents with amenorrhea, acute severe lower abdominal pain, and cervical motion tenderness or syncope.",
     "Ruptured ectopic pregnancy causes catastrophic intra-abdominal hemorrhage within hours.",
     "Do not perform vigorous bimanual pelvic examination; establish IV line; arrange immediate emergency transfer to OBG surgical center.",
     "Clinician override allowed only if intrauterine pregnancy confirmed by recent documented ultrasound.",
     "Mandatory documented surgical referral or ultrasound confirmation", "Logs ECTOPIC_PREGNANCY_ALERT to clinical audit store"),

    ("CR-016", "Adolescent Pregnancy High-Risk Monitoring Alert", "MODERATE_ADVISORY",
     "Pregnant female aged under 18 years registered in antenatal care.",
     "Adolescent pregnancies carry elevated risks of cephalopelvic disproportion, anemia, pre-eclampsia, and premature delivery.",
     "Provide intensive nutritional supplementation, adolescent psychological counseling, and plan institutional delivery at secondary hospital.",
     "Clinician acknowledges advisory and documents birth preparedness plan.",
     "Mandatory birth preparedness note", "Logs ADOLESCENT_PREGNANCY_ADVISORY to maternal registry"),

    ("CR-017", "Advanced Maternal Age Screening Alert", "MODERATE_ADVISORY",
     "Pregnant female aged >= 35 years registered in antenatal care.",
     "Advanced maternal age increases incidence of gestational diabetes, chromosomal anomalies, and hypertensive disorders.",
     "Schedule early 75g oral glucose tolerance test and refer for first-trimester anomaly ultrasound screening.",
     "Clinician acknowledges advisory and schedules recommended screening tests.",
     "Mandatory screening plan note", "Logs ADVANCED_MATERNAL_AGE_ADVISORY to maternal registry"),

    ("CR-018", "Maternal Syphilis Rapid Test Positive Alert", "HIGH_WARNING",
     "Rapid plasma reagin (RPR) or Treponema rapid strip reads POSITIVE in pregnant patient.",
     "Untreated maternal syphilis results in 50% fetal loss, stillbirth, or severe congenital syphilis.",
     "Prescribe Benzathine Penicillin G 2.4 million units IM single dose immediately; initiate partner tracing and treatment; confirm with RPR titer.",
     "Clinician override allowed only if previously fully treated with documented non-reactive or low stable titer.",
     "Mandatory documented treatment history or injection administration note", "Logs MATERNAL_SYPHILIS_ALERT to maternal registry"),

    ("CR-019", "Gestational Diabetes Mellitus (GDM) Screening Trigger", "MODERATE_ADVISORY",
     "Pregnant patient reaches 24-28 weeks gestation without documented oral glucose challenge.",
     "Undetected GDM causes fetal macrosomia, birth trauma, and neonatal hypoglycemia.",
     "Perform single-step 75g oral glucose challenge test; threshold >= 140 mg/dL indicates gestational diabetes requiring dietary or insulin therapy.",
     "Clinician acknowledges advisory and orders glucose challenge test.",
     "Mandatory glucose test order ID", "Logs GDM_SCREENING_TRIGGER to maternal registry"),

    ("CR-020", "Postpartum Sepsis Red-Flag Alert", "CRITICAL_ALERT",
     "Postnatal patient presents with body temperature >= 38.0C (100.4F) and foul-smelling lochia or uterine subinvolution.",
     "Puerperal sepsis is a rapidly progressing, life-threatening infection of the genital tract.",
     "Administer first dose broad-spectrum IV antibiotics (Ampicillin + Gentamicin + Metronidazole); arrange immediate hospital admission.",
     "Clinician override allowed only if non-gynecological cause (e.g. simple mastitis or UTI) confirmed on examination.",
     "Mandatory documented diagnosis and antibiotic treatment plan", "Logs PUERPERAL_SEPSIS_ALERT to maternal registry"),

    ("CR-021", "ACE Inhibitor + ARB Contraindication Alert", "HIGH_WARNING",
     "Simultaneous prescribing of an ACE Inhibitor (e.g. Enalapril) and an Angiotensin Receptor Blocker (e.g. Telmisartan, Losartan).",
     "Dual renin-angiotensin-aldosterone blockade significantly increases risk of acute kidney injury, severe hyperkalemia, and syncope without added benefit.",
     "Discontinue one of the agents; maintain single-agent renin-angiotensin blockade.",
     "Clinician override permitted with mandatory justification note and documented potassium monitoring plan.",
     "Mandatory documented justification note (>=15 chars)", "Logs DUAL_RAAS_BLOCKADE_ALERT to WORM audit store"),

    ("CR-022", "Metformin in Severe Renal Impairment Contraindication", "CRITICAL_ALERT",
     "Metformin prescribed to a patient with documented eGFR < 30 ml/min/1.73m2 or serum creatinine > 2.0 mg/dL.",
     "Metformin accumulates in renal failure, precipitating fatal Metformin-Associated Lactic Acidosis (MALA) with >40% mortality.",
     "Discontinue Metformin immediately; transition to renal-safe antidiabetic therapy (e.g. Insulin, Teneligliptin) under physician supervision.",
     "Clinician override blocked unless recent repeated laboratory renal function demonstrates eGFR >= 45 ml/min.",
     "Mandatory documented eGFR value and clinical rationale", "Logs METFORMIN_RENAL_CONTRAINDICATION to WORM audit store"),

    ("CR-023", "Penicillin Allergy & Cephalosporin Cross-Reactivity Guard", "HIGH_WARNING",
     "Prescription of a cephalosporin antibiotic (e.g. Cephalexin, Cefixime) to a patient with documented Penicillin allergy.",
     "Cephalosporins share beta-lactam chemical structures, carrying up to 10% cross-allergy risk including anaphylaxis.",
     "Select an alternative non-beta-lactam antibiotic class (e.g. Macrolides, Doxycycline) based on infection type.",
     "Clinician may override if prior penicillin reaction was minor non-allergic gastrointestinal upset, not IgE-mediated anaphylaxis.",
     "Mandatory documented allergy severity characterization note", "Logs PENICILLIN_CEPHALOSPORIN_CROSS_ALERT to WORM store"),

    ("CR-024", "NSAID in Active Peptic Ulcer / CKD Contraindication", "HIGH_WARNING",
     "Prescription of systemic NSAIDs (e.g. Diclofenac, Ibuprofen) in patient with active peptic ulcer disease or CKD Stage 4-5.",
     "NSAIDs inhibit gastroprotective prostaglandins and renal hemodynamics, causing massive GI bleeding or acute anuric renal shutdown.",
     "Discontinue NSAID; substitute Paracetamol for analgesia; prescribe proton pump inhibitor gastroprotection if indicated.",
     "Clinician override permitted with documented co-prescription of PPI and short-course (<3 days) justification.",
     "Mandatory documented gastroprotection and short duration note", "Logs NSAID_CONTRAINDICATION_ALERT to WORM audit store"),

    ("CR-025", "Dual Antiplatelet Therapy Bleeding Risk Advisory", "MODERATE_ADVISORY",
     "Co-prescribing of Aspirin and Clopidogrel without documented indication.",
     "Dual antiplatelet therapy significantly elevates major gastrointestinal and intracranial hemorrhage risks.",
     "Verify indication (recent acute coronary syndrome or coronary stent within 12 months); ensure gastroprotection with PPI.",
     "Clinician confirms documented cardiovascular indication.",
     "Mandatory cardiovascular indication note", "Logs DUAL_ANTIPLATELET_ADVISORY to clinical audit store"),

    ("CR-026", "Pediatric Aspirin Reye Syndrome Absolute Contraindication", "CRITICAL_ALERT",
     "Prescription of Aspirin to a child aged under 16 years presenting with fever or viral illness.",
     "Aspirin administration during viral infections in children causes Reye Syndrome (acute encephalopathy and fatty liver failure with 30-50% mortality).",
     "Absolute contraindication; substitute Paracetamol or Ibuprofen for pediatric fever and analgesia.",
     "Clinician override permitted ONLY for Kawasaki Disease under specialized pediatric cardiologist management.",
     "Mandatory documented Kawasaki Disease diagnosis note", "Logs REYE_SYNDROME_CRITICAL_BLOCK to WORM audit store"),

    ("CR-027", "Statin in Active Liver Disease Warning", "HIGH_WARNING",
     "Prescription of statin (Atorvastatin) in patient with documented acute hepatitis or serum transaminases > 3x Upper Limit of Normal.",
     "Statins undergo extensive hepatic metabolism and may exacerbate severe acute hepatocellular injury.",
     "Hold statin therapy until transaminases normalize; evaluate underlying hepatic etiology.",
     "Clinician override permitted if mild chronic transaminitis associated with non-alcoholic fatty liver disease (NAFLD).",
     "Mandatory documented NAFLD / liver function note", "Logs STATIN_HEPATOTOXICITY_ALERT to clinical audit store"),

    ("CR-028", "Fluoroquinolone QT Prolongation & Tendonitis Alert", "MODERATE_ADVISORY",
     "Prescription of Ciprofloxacin or Levofloxacin in elderly patient or patient receiving antiarrhythmic therapy.",
     "Fluoroquinolones cause Achilles tendonitis/rupture and prolong cardiac QTc interval, risking Torsades de Pointes.",
     "Consider alternative antibiotic class; warn patient to discontinue if joint or tendon pain develops.",
     "Clinician acknowledges advisory and documents patient counseling.",
     "Mandatory patient counseling note", "Logs FLUOROQUINOLONE_ADVISORY to clinical audit store"),

    ("CR-029", "Maximum Daily Paracetamol Dosage Boundary Guard", "HIGH_WARNING",
     "Cumulative daily prescribed dose of Paracetamol exceeds 4,000 mg in adult or 60 mg/kg in child.",
     "Paracetamol overdose saturates glutathione pathways, producing toxic NAPQI metabolite and fatal acute hepatic necrosis.",
     "Reduce prescribed daily dose below maximum safety ceiling; check for duplicate Paracetamol in combination syrups.",
     "Clinician override permitted up to 4g/day only in verified normal-weight adults without hepatic impairment.",
     "Mandatory documented dosage verification note", "Logs PARACETAMOL_MAX_DOSE_WARNING to WORM audit store"),

    ("CR-030", "Potassium Supplement + Potassium-Sparing Diuretic Contraindication", "HIGH_WARNING",
     "Co-prescribing of oral Potassium chloride with Spironolactone or Triamterene.",
     "Synergistic potassium retention causes acute life-threatening hyperkalemia and fatal cardiac ventricular fibrillation.",
     "Discontinue potassium supplement; monitor serum potassium within 7 days.",
     "Clinician override permitted only if severe refractory hypokalemia documented on laboratory panel.",
     "Mandatory documented serum potassium value (<3.0 mEq/L)", "Logs HYPERKALEMIA_RISK_ALERT to WORM audit store"),

    ("CR-031", "Critical Lab Panic: Severe Anemia Alert", "CRITICAL_ALERT",
     "Point-of-care hemoglobin reads < 6.0 g/dL in non-pregnant adult or child.",
     "Severe anemia causes high-output congestive heart failure and cerebral ischemia.",
     "Evaluate for active occult GI bleeding or acute hemolysis; initiate urgent referral to secondary hospital for blood transfusion.",
     "Clinician override allowed if chronic stable nutritional anemia receiving specialized hematological management.",
     "Mandatory documented transfusion referral or hematology plan", "Logs PANIC_VALUE_ANEMIA_ALERT to WORM audit store"),

    ("CR-032", "Critical Lab Panic: Severe Thrombocytopenia Alert", "CRITICAL_ALERT",
     "Platelet count reads < 20,000 /uL on laboratory diagnostic panel.",
     "Extreme thrombocytopenia carries severe spontaneous mucosal, gastrointestinal, and intracranial hemorrhage risk.",
     "Avoid intramuscular injections and NSAIDs; examine for petechiae and bleeding; arrange emergency tertiary hospital admission.",
     "Zero override without documented hospital admission order.",
     "Mandatory emergency hospital referral documentation", "Logs PANIC_THROMBOCYTOPENIA_ALERT to WORM audit store"),

    ("CR-033", "Critical Lab Panic: Dengue NS1 Positive with Warning Signs", "CRITICAL_ALERT",
     "Positive rapid Dengue NS1 or IgM in patient with abdominal pain, persistent vomiting, mucosal bleeding, or SBP < 90 mmHg.",
     "Dengue shock syndrome and severe plasma leakage carry high mortality without aggressive protocolized IV fluid management.",
     "Administer isotonic crystalloid IV fluid bolus; arrange immediate ambulance transfer to secondary hospital dengue ward.",
     "Zero override; life-threatening epidemic complication.",
     "Mandatory documented fluid protocol and transfer note", "Logs PANIC_DENGUE_SHOCK_ALERT to WORM audit store"),

    ("CR-034", "Critical Lab Panic: Falciparum Malaria Positive Alert", "CRITICAL_ALERT",
     "Rapid diagnostic test reads POSITIVE for Plasmodium falciparum antigen.",
     "P. falciparum malaria carries high risk of cerebral malaria, acute renal failure, and death within 24-48 hours.",
     "Initiate full course Artemisinin-based Combination Therapy (ACT) immediately per NVBDCP guidelines; admit if complicated.",
     "Clinician confirms initiation of mandatory ACT regimen.",
     "Mandatory ACT prescription record ID", "Logs PANIC_FALCIPARUM_ALERT to epidemiology registry"),

    ("CR-035", "Urine Dipstick: Massive Proteinuria (4+ Albumin) Alert", "HIGH_WARNING",
     "Rapid urine dipstick shows 4+ Albumin (>= 500 mg/dL protein).",
     "Massive proteinuria indicates nephrotic syndrome, acute glomerulonephritis, or severe pre-eclampsia.",
     "Assess for generalized anasarca and blood pressure; schedule secondary nephrology referral and 24-hour urine protein check.",
     "Clinician acknowledges advisory and documents renal referral plan.",
     "Mandatory renal referral note", "Logs MASSIVE_PROTEINURIA_ALERT to clinical audit store"),

    ("CR-036", "Urine Dipstick: Heavy Glycosuria + Ketonuria Alert", "CRITICAL_ALERT",
     "Urine dipstick shows Glucose >= 3+ combined with Ketones >= 2+.",
     "Combination of heavy glycosuria and ketonuria strongly suggests acute Diabetic Ketoacidosis (DKA).",
     "Check capillary blood glucose immediately; assess for Kussmaul breathing and dehydration; start normal saline IV line; transfer to hospital.",
     "Clinician override allowed only if patient is completely stable with verified blood glucose < 180 and starvation ketosis.",
     "Mandatory documented blood glucose and clinical evaluation note", "Logs DKA_URINE_ALERT to WORM audit store"),

    ("CR-037", "Confirmatory Peripheral Blood Smear Prompt for Malaria", "MODERATE_ADVISORY",
     "Rapid malaria antigen test reads POSITIVE or clinical suspicion is high.",
     "National Vector Borne Disease Control Programme mandates microscopic confirmation of parasite density.",
     "Prepare thick and thin peripheral blood smears for laboratory technician microscopy.",
     "Clinician confirms preparation of laboratory smear order.",
     "Mandatory smear order ID", "Logs MALARIA_CONFIRMATORY_SMEAR_PROMPT to lab registry"),

    ("CR-038", "High-Risk Syphilis Rapid Test Confirmation Prompt", "HIGH_WARNING",
     "Rapid Treponema test reads POSITIVE in non-pregnant adult.",
     "Positive rapid treponemal test requires quantitative RPR/VDRL titer to distinguish active infection from past treated syphilis.",
     "Order quantitative RPR titer; prescribe Benzathine Penicillin if active; initiate partner notification.",
     "Clinician documents confirmation and partner notification plan.",
     "Mandatory partner notification note", "Logs SYPHILIS_CONFIRMATION_PROMPT to clinical audit store"),

    ("CR-039", "Diagnostic Reagent Expiration Hard-Stop Rule", "HIGH_WARNING",
     "Lab technician attempts to enter result using a reagent kit lot that has passed its manufacturer expiry date.",
     "Expired reagents produce false negative and false positive diagnostic errors, compromising clinical decision-making.",
     "Absolute hard-stop; discard expired kit; open a new verified reagent lot with current expiry date.",
     "Zero clinician or technician override; system strictly blocks result entry.",
     "None (Hard Block)", "Logs EXPIRED_REAGENT_BLOCKED_AUDIT to laboratory audit store"),

    ("CR-040", "Discordant Rapid Diagnostic Result Flagging", "MODERATE_ADVISORY",
     "Entered rapid test result directly conflicts with objective physical findings (e.g. Dengue NS1 negative in patient with acute petechial rash and SBP 80).",
     "Rapid lateral flow tests have recognized false-negative rates; clinical presentation must supersede negative screening tests.",
     "Repeat diagnostic test using alternative lot or refer specimen to central municipal reference laboratory.",
     "Clinician documents rationale for repeat testing or clinical management.",
     "Mandatory clinical correlation note", "Logs DISCORDANT_DIAGNOSTIC_ADVISORY to clinical audit store"),

    ("CR-041", "Suspected Acute Coronary Syndrome (ACS) Immediate Referral", "CRITICAL_ALERT",
     "Adult patient presents with retrosternal chest pressure radiating to left arm/jaw, diaphoresis, or dyspnea.",
     "Acute myocardial infarction carries high mortality within the first 60 minutes ('Golden Hour').",
     "Administer Dispersible Aspirin 300 mg orally immediately; summon 108 emergency ambulance; transfer directly to PCI-capable tertiary hospital.",
     "Clinician override allowed only if alternative non-cardiac etiology definitively confirmed with normal ECG.",
     "Mandatory documented ECG / clinical evaluation note", "Logs ACS_EMERGENCY_TRANSFER_ALERT to WORM audit store"),

    ("CR-042", "Suspected Acute Stroke (FAST Signs) Immediate Referral", "CRITICAL_ALERT",
     "Patient presents with sudden Facial droop, Arm drift weakness, or Slurred Speech within 4.5 hours of onset.",
     "Acute ischemic stroke requires immediate thrombolysis or thrombectomy within the narrow 4.5-hour therapeutic window.",
     "Record exact time of symptom onset; check capillary blood glucose to rule out hypoglycemia; summon 108 ambulance transfer to stroke center.",
     "Clinician confirms documented symptom onset time and tertiary hospital dispatch.",
     "Mandatory documented onset timestamp and hospital destination", "Logs STROKE_FAST_ALERT to WORM audit store"),

    ("CR-043", "Anaphylactic Shock Resuscitation & Adrenaline Prompt", "CRITICAL_ALERT",
     "Patient develops acute stridor, wheezing, diffuse urticaria, and hypotension following medication injection or insect sting.",
     "Anaphylaxis causes fatal asphyxiation or cardiovascular collapse within minutes without immediate epinephrine.",
     "Administer IM Adrenaline 1:1000 (0.5 ml adult, 0.01 ml/kg child) into mid-anterolateral thigh immediately; repeat after 5 mins if needed; start high-flow oxygen.",
     "Zero override; life-saving first-line emergency intervention.",
     "Mandatory documented adrenaline administration record", "Logs ANAPHYLAXIS_EMERGENCY_ALERT to WORM audit store"),

    ("CR-044", "Status Epilepticus Emergency Anticonvulsant Prompt", "CRITICAL_ALERT",
     "Active generalized convulsive seizure persisting for >= 5 minutes or recurrent seizures without regaining consciousness.",
     "Status epilepticus produces neuronal necrosis, hyperthermia, and respiratory arrest without rapid pharmacologic termination.",
     "Maintain clear airway and administer high-flow oxygen; administer IV Lorazepam 4 mg or Rectal Diazepam 10 mg; prepare secondary transfer.",
     "Clinician confirms administration of emergency anticonvulsant.",
     "Mandatory anticonvulsant administration note", "Logs STATUS_EPILEPTICUS_ALERT to WORM audit store"),

    ("CR-045", "Acute Severe Asthma Nebulization & Referral Protocol", "HIGH_WARNING",
     "Patient with acute dyspnea unable to speak in full sentences, respiratory rate > 30/min, or PEFR < 50% predicted.",
     "Severe bronchospasm risks acute respiratory muscle exhaustion and fatal hypercapnic arrest.",
     "Administer oxygen-driven Salbutamol + Ipratropium nebulization immediately; give oral Prednisolone 40 mg; arrange transfer if refractory.",
     "Clinician documents nebulization response and post-treatment peak flow.",
     "Mandatory post-nebulization assessment note", "Logs SEVERE_ASTHMA_ALERT to clinical audit store"),

    ("CR-046", "Snakebite Envenomation Red-Flag & ASV Referral Alert", "CRITICAL_ALERT",
     "Patient presents with confirmed or suspected snakebite with rapid local swelling, ptosis, bleeding, or hematuria.",
     "Neurotoxic and hemotoxic snake venom causes rapid fatal respiratory paralysis or acute coagulopathy.",
     "Immobilize affected limb with splint; avoid arterial tourniquets or incising wound; summon emergency transfer to hospital stocked with Anti-Snake Venom.",
     "Zero override without documented specialized antivenom administration.",
     "Mandatory emergency hospital referral record", "Logs SNAKEBITE_EMERGENCY_ALERT to WORM audit store"),

    ("CR-047", "Rabies Category III Animal Bite Prophylaxis Prompt", "HIGH_WARNING",
     "Patient presents with transdermal bite, scratch with bleeding, or mucous membrane contamination by stray dog or wild animal.",
     "Rabies has 100% case fatality once clinical symptoms appear; complete post-exposure prophylaxis is mandatory.",
     "Wash wound immediately under running tap water with soap for at least 15 minutes; administer Anti-Rabies Vaccine (ARV); refer for Rabies Immunoglobulin (RIG).",
     "Clinician confirms documented wound washing and first-dose ARV vaccination.",
     "Mandatory ARV lot number and RIG referral documentation", "Logs RABIES_PEP_MANDATORY_PROMPT to clinical audit store"),

    ("CR-048", "Presumptive Pulmonary Tuberculosis (Cough >= 2 Weeks)", "HIGH_WARNING",
     "Patient presents with persistent productive cough for 2 weeks or more, accompanied by fever, night sweats, or weight loss.",
     "Early diagnosis of pulmonary tuberculosis arrests household transmission and prevents permanent cavitary lung damage.",
     "Order sputum microscopy / NAAT testing immediately; enroll patient into national Nikshay presumptive TB register.",
     "Clinician confirms documented sputum test order or Nikshay enrollment ID.",
     "Mandatory Nikshay presumptive ID or sputum order ID", "Logs PRESUMPTIVE_TB_WARNING to TB surveillance registry"),

    ("CR-049", "Acute Bacterial Meningitis Triad Alert", "CRITICAL_ALERT",
     "Patient presents with acute onset of fever, neck stiffness (nuchal rigidity), and altered sensorium.",
     "Acute pyogenic meningitis carries high risk of death or permanent neurological deficit within 24 hours.",
     "Administer first dose parenteral Ceftriaxone 2g IV if ambulance transfer will exceed 30 minutes; arrange immediate tertiary hospital admission.",
     "Zero override; life-threatening neuro-infectious emergency.",
     "Mandatory emergency admission documentation and antibiotic note", "Logs MENINGITIS_TRIAD_ALERT to WORM audit store"),

    ("CR-050", "Mandatory Free-Text Justification on Critical Alert Override", "HIGH_WARNING",
     "Clinician attempts to dismiss or override any CRITICAL_ALERT or HIGH_WARNING clinical decision support prompt.",
     "Ensures clinician reflects on clinical risk and provides documented legal rationale for departing from safety protocols.",
     "System requires entry of meaningful clinical justification text (minimum 15 characters) before alert dismissal is permitted.",
     "Clinician types valid clinical justification note; system unlocks consultation workflow.",
     "Dismissal blocked if text is missing, gibberish, or shorter than 15 characters", "Logs CLINICAL_OVERRIDE_AUDIT with full text, timestamp, and practitioner ID to WORM store")
]

OR_ITEMS = [
    ("OR-001", "Morning Clinic Facility Opening Protocol (08:30 IST)", "08:30 IST scheduled opening",
     "First arriving staff member unlocks facility, inspects physical premises, switches on mains power, and boots workstations.",
     "Workstations, thermal printers, and network routers powered and verified.",
     "Workstation operates in local Dexie.js offline mode if broadband modem is down.",
     "Handover key retrieved from facility secure lockbox.",
     "Verifies zero unfinalized tokens remaining from prior calendar day.",
     "Facility Medical Officer signs morning facility opening log.",
     "Logs FACILITY_OPENING_VERIFIED to operational audit journal"),

    ("OR-002", "Emergency Resuscitation Tray Daily Inspection", "08:45 IST daily pre-clinic inspection",
     "Staff nurse physically verifies emergency drugs (Adrenaline, Atropine, Hydrocortisone) and oxygen cylinder pressure.",
     "Oxygen cylinder pressure reads >= 1500 psi; suction apparatus tested.",
     "Offline inspection checklist completed on local terminal.",
     "Nurse inspects drug ampoule seals and lot expiry dates.",
     "Reconciles used emergency ampoules against replacement stock.",
     "Staff Nurse and Medical Officer dual sign-off.",
     "Logs EMERGENCY_TRAY_VERIFIED with oxygen pressure reading"),

    ("OR-003", "Cold Chain Refrigerator Morning Temperature Check", "09:00 IST morning temperature audit",
     "Nurse reads digital/stem thermometer inside ILR vaccine refrigerator, verifying temperature between +2C and +8C.",
     "Thermometer calibrated; ILR mains power indicator verified active.",
     "Temperature recorded locally in Dexie.js if network connection is absent.",
     "Nurse notes any overnight temperature excursions on physical card.",
     "Reconciles physical dial reading against digital telemetry sensor.",
     "Zonal Immunization Officer notified automatically if temperature breaches +8C.",
     "Logs COLD_CHAIN_TEMPERATURE_LOGGED with exact Celsius reading"),

    ("OR-004", "Thermal Printer Paper Roll & Print Test Verification", "08:45 IST terminal startup",
     "Data entry operator inspects paper roll in thermal receipt printer and executes diagnostic self-test print.",
     "Thermal printer connected via USB; green ready LED illuminated.",
     "Prints local test slip without central cloud connection via Web Serial.",
     "Operator replaces paper roll if remaining diameter < 15mm.",
     "Reconciles paper roll inventory count in clinic utility store.",
     "Facility Administrator.",
     "Logs PRINTER_READINESS_VERIFIED with terminal hardware ID"),

    ("OR-005", "Dual-Desk Workstation Hardware Health Verification", "08:45 IST terminal boot",
     "Front desk and doctor desk workstations booted, verified free of disk space warnings, and display calibrated.",
     "Available disk storage >= 10GB; RAM utilization < 50% at startup.",
     "Terminal operates fully functional in local offline browser profile.",
     "Hardware inventory tags verified against municipal asset register.",
     "System telemetry health ping dispatched to IT operations portal.",
     "Clinic IT Focal Point.",
     "Logs WORKSTATION_HEALTH_VERIFIED to central telemetry mart"),

    ("OR-006", "Local IndexedDB Database Integrity Check", "Browser application initialization",
     "PWA service worker runs automated Dexie.js schema and transaction integrity check during startup.",
     "Local IndexedDB database opens cleanly without corruption errors.",
     "Validates presence of cached master catalogs and mutation queue.",
     "Terminal retains prior session state and pending mutations.",
     "Reconciles local mutation sequence numbers against central server sync pointer.",
     "Automated PWA engine.",
     "Logs CLIENT_STORAGE_INTEGRITY_CHECK to client diagnostic log"),

    ("OR-007", "Pending Offline Mutation Queue Backlog Verification", "08:50 IST pre-flight check",
     "Operator checks pending mutation queue depth; if >50 items pending from prior day, trigger manual sync flush.",
     "Network connection verified active; sync bridge operational.",
     "Displays yellow warning badge if queue > 50 items during offline mode.",
     "Outgoing staff flags pending sync backlog to incoming shift.",
     "Reconciles pending local transactions against committed cloud journal.",
     "Facility IT Administrator.",
     "Logs SYNC_QUEUE_BACKLOG_AUDIT with count of uncommitted mutations"),

    ("OR-008", "1D/2D Barcode Scanner Calibration Verification", "08:50 IST registration desk setup",
     "Operator scans standard test barcode on desk placard to verify scanner decoding and keyboard wedge input.",
     "USB barcode scanner connected and beeps upon test decode.",
     "Scanner inputs decoded alphanumeric string directly into local browser form.",
     "Scanner wiped with disinfectant cloth between shifts.",
     "Reconciles scanner serial number with clinic asset record.",
     "Data Entry Operator.",
     "Logs SCANNER_READINESS_VERIFIED to operational journal"),

    ("OR-009", "Facility Potable Water & Hand Hygiene Inspection", "08:45 IST facility sanitation round",
     "Auxiliary staff verifies running water at scrub sinks, liquid soap dispensers filled, and clean drinking water available for patients.",
     "Water taps functional; liquid soap and alcohol hand rub present at all desks.",
     "Sanitation checklist logged on mobile or terminal offline form.",
     "Sanitation log signed off by cleaning supervisor.",
     "Reconciles water filter cartridge replacement date against municipal schedule.",
     "Facility In-Charge.",
     "Logs SANITATION_READINESS_VERIFIED to facility maintenance journal"),

    ("OR-010", "Frontline Staff Attendance & Morning Roster Verification", "09:00 IST clinic operational kickoff",
     "All rostered staff members (MO, Nurse, Pharmacist, Lab Tech, DEO) log into clinic terminals with biometric/PIN authentication.",
     "Geofence verified; staff profiles authenticated on terminal.",
     "Offline biometric login validated against cached local credentials.",
     "Absence of any rostered staff immediately reported to Zonal Health Officer.",
     "Reconciles physical presence with BBMP HRMS biometric attendance.",
     "Medical Officer in-charge.",
     "Logs ROSTER_ATTENDANCE_COMMITTED to municipal HRMS database"),

    ("OR-011", "Registration Counter Daily Token Pool Initialization", "09:00 IST OPD opening",
     "Data entry operator initializes daily token dispensing engine, confirming sequence starts at 001.",
     "Token printer paper loaded; sequence counter verified reset.",
     "Tokens issue sequentially in offline mode using local sequence counter.",
     "Registration counter desk handover checklist verified.",
     "Reconciles token issuance counts with end-of-day register.",
     "Data Entry Operator.",
     "Logs TOKEN_POOL_INITIALIZED with start sequence number 001"),

    ("OR-012", "Nursing Triage Station Diagnostic Kit Preparation", "08:50 IST nursing station setup",
     "Staff nurse calibrates digital BP monitor, replaces glucometer strip drum, and prepares disposable lancets and alcohol swabs.",
     "Digital BP monitor battery tested; glucometer code chip verified.",
     "Triage station functional in offline mode with paper backup available.",
     "Nurse stocks disposable gloves and surgical masks for shift.",
     "Reconciles glucometer test strip count with pharmacy stock balance.",
     "Staff Nurse.",
     "Logs TRIAGE_STATION_PREPARED with diagnostic kit batch IDs"),

    ("OR-013", "Doctor Consultation Desk Digital Certificate Validation", "08:55 IST doctor room startup",
     "Medical Officer verifies active digital signature certificate and Karnataka Medical Council (KMC) credential status.",
     "KMC registration active; digital signature token accessible.",
     "Doctor can sign prescriptions offline using local cryptographic keys.",
     "Doctor reviews pending lab results from prior day shift.",
     "Reconciles assigned patient queue with nursing triage flow.",
     "Medical Officer.",
     "Logs CLINICIAN_CREDENTIAL_VERIFIED to security audit store"),

    ("OR-014", "Laboratory Diagnostic Reagent Temperature Verification", "08:50 IST laboratory bench setup",
     "Lab technician verifies rapid diagnostic test kits (Dengue, Malaria, Urine strips) are stored between +15C and +30C.",
     "Room thermometer reads within safe storage range; air conditioning active.",
     "Lab result entry available in local Dexie store without internet.",
     "Technician inspects desiccant indicators in test strip canisters.",
     "Reconciles opened kit counts with laboratory daily consumption ledger.",
     "Lab Technician.",
     "Logs LAB_REAGENT_ENVIRONMENT_VERIFIED to diagnostic journal"),

    ("OR-015", "Pharmacy Dispensing Counter Barcode Scanner Activation", "08:55 IST pharmacy setup",
     "Pharmacist activates 2D barcode scanner, opens electronic prescription retrieval queue, and tests FEFO recommendation view.",
     "Barcode scanner functional; dispensing display active.",
     "Pharmacy operates offline using cached inventory balances and local batches.",
     "Pharmacist reviews near-expiry alerts flagged by overnight audit.",
     "Reconciles physical cash/exemption receipts from prior operating day.",
     "Pharmacist.",
     "Logs PHARMACY_COUNTER_ACTIVATED with hardware device serial"),

    ("OR-016", "Workstation Battery & UPS Inverter Status Inspection", "09:00 IST electrical check",
     "Facility staff inspects clinic solar/inverter battery levels and verifies UPS provides at least 30 minutes runtime.",
     "UPS battery indicator green; inverter voltage reads >= 220V AC.",
     "Battery conservation mode dims screen if AC mains power drops.",
     "Inverter maintenance log updated with water levels and battery health.",
     "Reconciles power outage duration logs against municipal electricity bills.",
     "Facility In-Charge.",
     "Logs POWER_BACKUP_STATUS_VERIFIED with battery voltage readings"),

    ("OR-017", "Network Connectivity & DNS Probe Baseline Test", "08:45 IST network verification",
     "Clinic terminal executes automated HTTP ping and DNS resolution test to BBMP health cloud gateway.",
     "Round-trip latency < 150ms; packet loss < 2%.",
     "Transitions to OFFLINE mode if ping fails for 3 consecutive probes.",
     "Modem reboot protocol executed if latency exceeds 1000ms.",
     "Reconciles monthly broadband data usage against municipal plan limit.",
     "Facility IT Focal Point.",
     "Logs NETWORK_BASELINE_PROBE with RTT latency and packet loss"),

    ("OR-018", "Master Formulary Cache Differential Synchronization", "08:40 IST background sync",
     "Terminal sync daemon checks for updated Karnataka 120 EDL drug catalogs and ICD-10 sets, pulling delta JSON payloads.",
     "ETag compared against central cloud master version.",
     "Retains existing cached formulary if network is unavailable during boot.",
     "Updated formulary changes highlighted on doctor terminal.",
     "Reconciles local catalog version checksum against central release manifest.",
     "Automated Cache Engine.",
     "Logs CATALOG_DIFFERENTIAL_SYNC with new entity version tag"),

    ("OR-019", "Daily Queue Ceiling & Token Pool Allocation", "09:00 IST queue configuration",
     "Medical Officer verifies clinic daily token capacity ceiling based on available staffing (standard 120 tokens per doctor).",
     "Token pool configured in queue management settings.",
     "Queue engine maintains token limit locally in IndexedDB.",
     "Token ceiling adjustments communicated to front desk operator.",
     "Reconciles issued tokens against physician consultation throughput.",
     "Medical Officer.",
     "Logs TOKEN_CEILING_CONFIGURED with maximum token allocation"),

    ("OR-020", "Priority Seating & Wheelchair Access Verification", "08:45 IST waiting hall inspection",
     "Front desk staff verifies dedicated priority seating benches for pregnant, elderly, and disabled patients are clean and accessible.",
     "Wheelchair ramp clear of obstructions; clinic wheelchair operational.",
     "Priority patient check-in accessible via mobile tablet if patient cannot walk.",
     "Staff assists frail patients directly from entrance to triage room.",
     "Reconciles accessibility complaints logged in Sahaaya feedback portal.",
     "Auxiliary Health Staff.",
     "Logs ACCESSIBILITY_INSPECTION_COMPLETED to facility journal"),

    ("OR-021", "Midday Queue Load Balancing Protocol (13:00 IST)", "13:00 IST midday operational review",
     "Medical Officer reviews waiting queue length; if >30 patients waiting, reallocates triage nurse to assist with rapid consultations.",
     "Waiting room display updated; estimated wait times recalculated.",
     "Queue state visible across all desks in local offline mesh.",
     "Doctor coordinates short staggered lunch breaks without closing rooms.",
     "Reconciles morning throughput against daily target.",
     "Medical Officer.",
     "Logs MIDDAY_QUEUE_REVIEW with current queue depth and wait times"),

    ("OR-022", "Midday Pharmacy Stock Tally for High-Velocity Drugs", "13:30 IST pharmacy check",
     "Pharmacist conducts spot count of Top 5 fast-moving drugs (Paracetamol, Amlodipine, Metformin, ORS, Cetirizine).",
     "Physical count verified against current digital stock ledger.",
     "Tally recorded in local Dexie pharmacy store.",
     "Discrepancies investigated immediately before afternoon rush.",
     "Reconciles morning prescriptions dispensed against shelf bottle deductions.",
     "Pharmacist.",
     "Logs MIDDAY_STOCK_SPOTCHECK with counts of Top 5 medications"),

    ("OR-023", "Staggered Lunch Rotation & Continuous Desk Coverage", "13:00 - 14:30 IST lunch window",
     "Staff rotates for 30-minute lunch breaks ensuring registration, nursing triage, and doctor desks remain continuously manned.",
     "Designated cross-covering staff member logged into terminal.",
     "Temporary role delegation active per BRULE-006 / FR-006.",
     "Staff hands over active tokens and open charts before departure.",
     "Reconciles patient continuous flow; zero queue stoppage permitted.",
     "Medical Officer.",
     "Logs LUNCH_ROTATION_STAGGERED with active coverage assignments"),

    ("OR-024", "Sudden Network Outage Offline Mode Activation", "Instantaneous upon WAN loss",
     "Terminal network monitor detects WAN failure, prompts visual orange OFFLINE badge, and redirects queries to IndexedDB.",
     "Local storage active; zero modal error popups or software freezes.",
     "Full read/write functionality maintained using local cached data.",
     "Staff notified to continue normal registrations and consultations.",
     "Reconciles offline mutation queue upon subsequent network reconnection.",
     "Client Network Daemon.",
     "Logs OFFLINE_MODE_TRANSITION with timestamp and disconnection cause"),

    ("OR-025", "Extended Power Outage Inverter Conservation Protocol", "Power outage exceeding 60 minutes",
     "Facility staff switches off non-critical ceiling fans and secondary lights, preserving battery for ILR refrigerator and workstations.",
     "Inverter voltage monitored every 30 minutes; non-essential loads severed.",
     "Workstation screen brightness dimmed to 40% to extend battery life.",
     "Staff prepares manual cold packs if ILR power backup is threatened.",
     "Reconciles generator/inverter fuel and power availability logs.",
     "Facility Administrator.",
     "Logs POWER_CONSERVATION_ACTIVE with battery reserve percentage"),

    ("OR-026", "Emergency Patient Rapid Triage Fast-Track Protocol", "Immediate upon acute patient arrival",
     "Frontline staff escorts collapsing or seizing patient past registration queue directly to doctor or procedure room.",
     "Crash cart and oxygen mask placed at bedside; vital signs taken immediately.",
     "Emergency encounter created locally without waiting for demographic details.",
     "Nurse coordinates emergency ambulance dispatch via 108 helpline.",
     "Reconciles emergency patient demographic records retrospectively.",
     "Medical Officer and Staff Nurse.",
     "Logs EMERGENCY_FASTTRACK_ACTIVATED with clinical disposition"),

    ("OR-027", "Hazardous Biomedical Waste Segregation Verification", "14:00 IST waste audit",
     "Staff nurse inspects color-coded biomedical waste bins (Yellow, Red, White sharps, Blue glassware) for correct segregation.",
     "Bins lined with non-chlorinated color-coded plastic bags with biohazard symbol.",
     "Waste log updated on clinic sanitation mobile form.",
     "Barcoded waste bags sealed when 3/4th full per BMW Rules 2016.",
     "Reconciles daily biomedical waste weights with municipal collection agency.",
     "Staff Nurse.",
     "Logs BIOMEDICAL_WASTE_VERIFIED with bag barcode IDs"),

    ("OR-028", "Sharps Container Replacement at 3/4th Full Capacity", "Sharps container reaches fill line",
     "Staff nurse permanently seals puncture-proof translucent sharps container when needles and scalpels reach 75% volume.",
     "Replacement puncture-proof sharps container deployed immediately at nursing desk.",
     "Sharps replacement event logged in facility safety journal.",
     "Used sharps container locked with tamper-evident seal.",
     "Reconciles sharps container serial numbers with hazardous waste manifest.",
     "Staff Nurse.",
     "Logs SHARPS_CONTAINER_SEALED with unique container barcode"),

    ("OR-029", "Point-of-Care Laboratory Waste Disposal Protocol", "End of morning testing run (13:30 IST)",
     "Lab technician immerses used lancets, test strips, and capillary tubes in 0.5% sodium hypochlorite solution for 30 minutes before bagging.",
     "Chemical disinfectant fresh (<24 hours old); biohazard yellow bag ready.",
     "Disinfection protocol recorded in laboratory decontamination register.",
     "Decontaminated waste transferred to sealed yellow biohazard bin.",
     "Reconciles chemical disinfectant usage against laboratory supply ledger.",
     "Lab Technician.",
     "Logs LAB_WASTE_DECONTAMINATED with disinfectant concentration check"),

    ("OR-030", "Midday Facility Sanitation & Disinfection Inspection", "14:00 IST midday cleaning round",
     "Sanitation worker mops waiting hall and consultation rooms with 1% sodium hypochlorite; surfaces wiped with alcohol disinfectant.",
     "Floor clean and dry; hand contact surfaces (door handles, desk surfaces) sanitized.",
     "Sanitation sign-off card updated on facility entrance notice board.",
     "Cleaning worker signs digital checklist on facility terminal.",
     "Reconciles sanitation supply consumption with municipal store ledger.",
     "Facility Supervisor.",
     "Logs MIDDAY_SANITATION_COMPLETED to facility operational journal"),

    ("OR-031", "Evening Clinic Facility Closure Protocol (17:30 IST)", "17:30 IST scheduled closing",
     "Medical Officer initiates daily clinic closure checklist, verifying all rooms are cleared and patients served.",
     "OPD registration window closed; entrance gate transitioned to exit-only.",
     "Offline mutations flushed to cloud before terminal shutdown.",
     "All staff complete desk-specific end-of-day reconciliation logs.",
     "Reconciles daily operational achievements against municipal standards.",
     "Medical Officer.",
     "Logs EVENING_CLOSURE_INITIATED with daily attendance summary"),

    ("OR-032", "Open Patient Token End-of-Day Reconciliation", "17:35 IST closure workflow",
     "Registration operator reviews queue dashboard, confirming zero tokens remain in QUEUED, CALLING, or CONSULTING states.",
     "All issued tokens marked COMPLETED, NO_SHOW, or CANCELLED.",
     "Token status changes committed locally in Dexie database.",
     "Any uncalled patient accounted for and contacted or rescheduled.",
     "Reconciles total tokens issued against total doctor consultations completed.",
     "Data Entry Operator and MO.",
     "Logs OPEN_TOKENS_RECONCILED with final count of served patients"),

    ("OR-033", "Unfulfilled Prescription Review & Patient Follow-up", "17:40 IST pharmacy closing",
     "Pharmacist reviews prescriptions marked PARTIALLY_FULFILLED or OUT_OF_STOCK, noting urgent items requiring emergency replenishment.",
     "Out-of-stock items compiled into emergency warehouse indent request.",
     "Patient contact phone numbers flagged for SMS notification upon stock arrival.",
     "Pharmacist communicates critical stockouts to Medical Officer.",
     "Reconciles unfulfilled prescriptions against clinic stock balances.",
     "Pharmacist.",
     "Logs UNFULFILLED_RX_REVIEW with list of pending medicine items"),

    ("OR-034", "Physical Pharmacy Stock Count vs System Ledger Audit", "17:45 IST pharmacy closing",
     "Pharmacist reconciles physical counts of high-value and controlled antibiotics against end-of-day system ledger balances.",
     "Physical blister packs and bottles match exact digital balance within 0 variance.",
     "Stock ledger balance locked for current calendar date in database.",
     "Any variance >1 unit documented with incident investigation report.",
     "Reconciles daily medicine consumption against total dispensed prescriptions.",
     "Pharmacist and MO.",
     "Logs DAILY_STOCK_LEDGER_CERTIFIED with zero variance sign-off"),

    ("OR-035", "Near-Expiry Stock Flagging & Quarantine Action", "17:50 IST pharmacy closing",
     "Pharmacist inspects quarantine shelf, verifying all batches within 60 days of expiry are physically isolated from dispensing racks.",
     "Quarantined batches marked with red warning tape and locked in separate cupboard.",
     "Batch status updated to QUARANTINED in digital pharmacy inventory.",
     "Quarantine transfer documentation prepared for zonal warehouse pickup.",
     "Reconciles quarantined stock value against municipal loss prevention ledger.",
     "Pharmacist.",
     "Logs QUARANTINE_SHELF_VERIFIED with list of isolated batch IDs"),

    ("OR-036", "Laboratory Specimen Clearance & Reagent Restock", "17:35 IST lab closing",
     "Lab technician verifies all blood and urine specimens have been processed, results signed off, and reagents restocked in refrigerator.",
     "Zero pending specimens remaining in accessioning rack; workspace disinfected.",
     "All lab orders updated to VERIFIED status in local Dexie database.",
     "Technician powers down diagnostic glucometers and centrifuges.",
     "Reconciles daily test counts against diagnostic reagent consumption.",
     "Lab Technician.",
     "Logs LAB_SPECIMENS_CLEARED with total daily test count"),

    ("OR-037", "Daily OPD Census Reconciliation & Supervisor Sign-Off", "17:50 IST administrative closing",
     "Medical Officer reviews aggregated daily census (total footfall, demographics, top diagnoses, referrals) and provides digital sign-off.",
     "Daily census figures verified against individual consultation records.",
     "Daily census summary exported as cryptographically signed PDF artifact.",
     "Summary submitted electronically to BBMP Central Command Center.",
     "Reconciles clinical diagnoses against ICD-10 codification standards.",
     "Medical Officer.",
     "Logs DAILY_CENSUS_CERTIFIED with doctor digital signature"),

    ("OR-038", "Daily Disease Surveillance (IHIP Form P) Generation", "17:55 IST surveillance closing",
     "Medical Officer reviews auto-populated IHIP Form P presumptive fever and disease syndromic returns and authorizes transmission.",
     "Aggregated syndrome cases (fever, acute diarrhea, jaundice, ARI) verified.",
     "Form P payload transmitted directly to Karnataka State IHIP API.",
     "Confirms transmission receipt from state health portal.",
     "Reconciles presumptive syndromic cases with confirmed rapid test results.",
     "Medical Officer.",
     "Logs IHIP_FORM_P_TRANSMITTED with state transaction confirmation ID"),

    ("OR-039", "Final Mutation Sync Queue Flushing to Central Cloud", "18:00 IST final sync deadline",
     "Background sync daemon executes final blocking sync flush, transmitting all pending Dexie mutations to central PostgreSQL cluster.",
     "Broadband modem active; sync daemon displays GREEN status.",
     "Sync queue depth reaches 0; all local mutations acknowledged by server.",
     "Flashing red alert displayed if mutations remain uncommitted past 18:05.",
     "Reconciles local workstation transaction counter with cloud transaction journal.",
     "Facility IT Focal Point.",
     "Logs FINAL_SYNC_FLUSH_COMPLETED with zero remaining queue depth"),

    ("OR-040", "End-of-Day Terminal Power Down & Security Lockdown", "18:05 IST final facility lockdown",
     "All workstation terminals safely powered down, peripheral USB cables secured, examination lights switched off, and facility locked.",
     "AC mains switches turned off; UPS power maintained for ILR refrigerator.",
     "Terminals locked with physical cable locks; windows latched.",
     "Keys returned to facility lockbox; burglar alarm armed.",
     "Reconciles facility physical security checklist.",
     "Medical Officer and Security Guard.",
     "Logs FACILITY_LOCKDOWN_COMPLETED with departure timestamp"),

    ("OR-041", "IT Helpdesk Breakdown Escalation Protocol (<30 Mins)", "Hardware or software breakdown",
     "Staff logs critical failure ticket via mobile app or telephone to BBMP IT Helpdesk; SLA mandates technician response in 30 mins.",
     "Ticket number generated; remote support technician assigned.",
     "Clinic switches to offline mode or backup laptop during workstation failure.",
     "Doctor notifies Zonal Health Officer if clinic operations are compromised.",
     "Reconciles technician arrival time and resolution timestamp.",
     "Facility In-Charge.",
     "Logs IT_HELP_DESK_TICKET_RAISED with ticket ID and priority"),

    ("OR-042", "Cold Chain Temperature Breach Urgent Escalation (<15 Mins)", "ILR temperature breaches +8C or falls below +2C",
     "Nurse immediately reports breach to Zonal Immunization Officer and transfers vaccines to pre-conditioned ice packs in vaccine carrier.",
     "Vaccine carriers with conditioned ice packs deployed within 10 minutes.",
     "Temperature excursion logged on local terminal and physical chart.",
     "Technician dispatched to inspect refrigerator compressor within 60 mins.",
     "Reconciles vaccine vials transferred against cold chain inventory.",
     "Staff Nurse and ZIO.",
     "Logs COLD_CHAIN_ESCALATION_ACTIVE with notification timestamp"),

    ("OR-043", "Municipal Drug Stockout Emergency Indent Protocol", "Critical EDL medicine balance reaches zero",
     "Pharmacist files emergency requisition on BBMP logistics portal; zonal warehouse dispatches buffer supply within 24 hours.",
     "Emergency indent flagged with URGENT priority in supply chain system.",
     "Pharmacist directs patients to nearest neighboring Namma Clinic in interim.",
     "Medical Officer informed to prescribe alternative formulary antibiotic.",
     "Reconciles emergency delivery receipt against stock ledger upon arrival.",
     "Pharmacist and Zonal Logistics Lead.",
     "Logs EMERGENCY_INDENT_RAISED with drug code and requested quantity"),

    ("OR-044", "Frontline Staff Conflict & De-Escalation Protocol", "Agitated or disruptive patient in clinic",
     "Staff executes verbal de-escalation; moves patient to private counseling room; summons security guard if physical safety threatened.",
     "Security guard present in waiting hall; panic button accessible at desk.",
     "Incident documented in clinic administrative safety journal.",
     "Medical Officer evaluates if psychiatric distress or hypoxia is present.",
     "Reconciles incident report with local jurisdictional police station if violence occurs.",
     "Medical Officer.",
     "Logs SECURITY_INCIDENT_REPORTED with detailed narrative"),

    ("OR-045", "Critical Infrastructure Failure Hospital Divert Protocol", "Catastrophic power cut, flooding, or structure damage",
     "Medical Officer declares temporary clinic divert; patients redirected to designated secondary municipal referral hospital.",
     "Divert notice posted at entrance and transmitted to BBMP Command Center.",
     "Active appointments notified via automated emergency SMS blast.",
     "Emergency equipment secured and biologicals transferred to mobile carrier.",
     "Reconciles facility restoration timeline with municipal engineering division.",
     "Chief Health Officer (BBMP).",
     "Logs CLINIC_DIVERT_DECLARED with authorized closure order ID"),

    ("OR-046", "Periodic Weekly Deep Cleaning & Disinfection Day", "Every Saturday 14:00 - 17:00 IST",
     "Comprehensive deep cleaning of facility including autoclave sterilization of surgical trays, window washing, and pest barrier check.",
     "Autoclave chemical indicator strips turn black, confirming sterilization.",
     "Sterilization log signed by staff nurse and filed in quality binder.",
     "Instruments stored in sterile double-wrap packs with 7-day shelf life.",
     "Reconciles autoclave cycle temperature (121C at 15 psi for 20 mins).",
     "Staff Nurse and Facility Admin.",
     "Logs WEEKLY_DEEP_CLEAN_COMPLETED with autoclave cycle records"),

    ("OR-047", "Bi-Weekly Fire Extinguisher & Safety Inspection", "1st and 15th of every month",
     "Facility in-charge inspects ABC dry chemical fire extinguishers, verifying pressure gauge in green zone and nozzle unblocked.",
     "Fire extinguisher pressure gauge green; safety pin and seal intact.",
     "Inspection tag signed and dated on extinguisher cylinder.",
     "Fire exit door checked for unhindered emergency egress.",
     "Reconciles extinguisher annual refilling schedule with BBMP Fire Cell.",
     "Facility In-Charge.",
     "Logs FIRE_SAFETY_INSPECTION_CERTIFIED with extinguisher serial numbers"),

    ("OR-048", "Monthly Backup Restoration & Offline Drill Execution", "Last Friday of every month at 16:00 IST",
     "Facility IT focal point disconnects WAN router, executes full mock patient registration and consultation, and verifies sync upon reconnection.",
     "Offline drill executes with zero data loss; transaction syncs in <30 seconds.",
     "Drill findings documented in municipal IT quality report.",
     "Staff refreshed on offline emergency procedures.",
     "Reconciles mock patient records; cancels test tokens cleanly.",
     "Zonal IT Supervisor.",
     "Logs OFFLINE_DRILL_EXECUTED with simulation metrics and sync latency"),

    ("OR-049", "Zonal Supervisory Facility Inspection Readiness", "Quarterly scheduled or unannounced audit",
     "Clinic maintains operational registers, quality checklists, and drug logs in continuous inspection-ready state for ZHO inspection.",
     "All digital dashboards up to date; physical clinic clean and compliant.",
     "ZHO accesses supervisory audit view on municipal tablet.",
     "Inspector executes random audit of 5 clinical charts and 5 stock batches.",
     "Reconciles inspection score against Indian Public Health Standards (IPHS).",
     "Zonal Health Officer (ZHO).",
     "Logs ZONAL_INSPECTION_COMPLETED with audit score and action items"),

    ("OR-050", "Mandatory Archival of Daily Reconciliation Slips", "Daily end-of-day operational closure",
     "Printed daily reconciliation summary slip signed by Medical Officer is filed in chronological physical audit binder and stored for 3 years.",
     "Physical binder stored in locked administrative cabinet.",
     "Digital scan of signed slip uploaded to municipal administrative portal.",
     "Reconciliation slips audited annually by BBMP Principal Auditor.",
     "Reconciles physical slips against digital database session archives.",
     "Medical Officer and Facility Administrator.",
     "Logs RECONCILIATION_SLIP_ARCHIVED with physical binder index number")
]
