#!/usr/bin/env python3
"""
build_data_brule_cr_or.py
Builds canonical datasets for:
- data_brule.py (BRULE-001 through BRULE-050)
- data_cr.py (CR-001 through CR-050)
- data_or.py (OR-001 through OR-050)
"""

import os
from build_data_brule_cr_or_defs import BRULE_ITEMS, CR_ITEMS, OR_ITEMS

def build_data_brule():
    target_path = os.path.join(os.path.dirname(__file__), "data_brule.py")
    lines = []
    lines.append("#!/usr/bin/env python3")
    lines.append('"""')
    lines.append("data_brule.py")
    lines.append("Canonical dataset for Business Rules (BRULE-001 through BRULE-050).")
    lines.append("Exhaustive municipal healthcare operational logic for Namma Clinic.")
    lines.append('"""')
    lines.append("")
    lines.append("BRULE_RULES = [")

    for i, item in enumerate(BRULE_ITEMS, 1):
        (rule_id, title, statement, reason, trigger, inputs, logic,
         allowed, rejected, exception, actor, approval, audit) = item
        obj_idx = ((i - 1) % 40) + 1
        sc_idx = ((i - 1) % 40) + 1
        insc_idx = ((i - 1) % 80) + 1
        risk_idx = ((i - 1) % 60) + 1
        dep_idx = ((i - 1) % 50) + 1
        m_idx = ((i - 1) % 40) + 1
        rel_idx = ((i - 1) % 20) + 1

        lines.append("    {")
        lines.append(f'        "id": "{rule_id}",')
        lines.append(f'        "title": "{title}",')
        lines.append(f'        "statement": "{statement}",')
        lines.append(f'        "domain": "Business Rule Governance",')
        lines.append(f'        "type": "Business Rule",')
        lines.append(f'        "priority": "MUST",')
        lines.append(f'        "priority_rationale": "Mandatory operational constraint for municipal clinic workflow integrity.",')
        lines.append(f'        "business_value": "Ensures policy compliance, fairness, fraud prevention, and clinical safety.",')
        lines.append(f'        "rationale": "{reason}",')
        lines.append(f'        "actor": "{actor}",')
        lines.append(f'        "persona": "PERSONA-{((i - 1) % 35) + 1:03d}",')
        lines.append(f'        "role": "ROLE-{((i - 1) % 30) + 1:03d}",')
        lines.append(f'        "stakeholder": "STAKEHOLDER-{((i - 1) % 50) + 1:03d}",')
        lines.append(f'        "trigger": "{trigger}",')
        lines.append(f'        "preconditions": "Relevant clinic workflow active on workstation terminal.",')
        lines.append(f'        "inputs": "{inputs}",')
        lines.append(f'        "decision_logic": "{logic}",')
        lines.append(f'        "allowed_outcome": "{allowed}",')
        lines.append(f'        "rejected_outcome": "{rejected}",')
        lines.append(f'        "exception_condition": "{exception}",')
        lines.append(f'        "approval_requirement": "{approval}",')
        lines.append(f'        "audit_requirement": "{audit}",')
        lines.append(f'        "validation": "Evaluated in Fastify middleware and client TypeBox schema validators.",')
        lines.append(f'        "main_flow": [')
        lines.append(f'            "Actor triggers operational action: {trigger.lower()}.",')
        lines.append(f'            "System evaluates business rule logic: {logic}.",')
        lines.append(f'            "IF logic passes: {allowed}.",')
        lines.append(f'            "IF logic fails: {rejected}.",')
        lines.append(f'            "Audit event emitted to tamper-evident WORM log: {audit}."')
        lines.append(f'        ],')
        lines.append(f'        "alternate_flow": "If rule condition permits exception ({exception}), secondary authorization is prompted.",')
        lines.append(f'        "exception_flow": "If rule is violated without approved exception, operation is rejected with HTTP 422 Unprocessable Entity.",')
        lines.append(f'        "postconditions": "State updated strictly conforming to business rule boundaries.",')
        lines.append(f'        "state_changes": "Applies business constraint state mutation in database.",')
        lines.append(f'        "business_rules": "{rule_id}",')
        lines.append(f'        "clinical_rules": "CR-{((i - 1) % 50) + 1:03d}",')
        lines.append(f'        "operational_rules": "OR-{((i - 1) % 50) + 1:03d}",')
        lines.append(f'        "security_implications": "Enforces authorization boundaries and prevents bypass.",')
        lines.append(f'        "privacy_implications": "Ensures lawful data processing and consent adherence.",')
        lines.append(f'        "data_implications": "Preserves relational integrity and audit trail.",')
        lines.append(f'        "audit_requirements": "{audit}",')
        lines.append(f'        "offline_behavior": "Enforced identically in local Dexie.js offline engine.",')
        lines.append(f'        "synchronization_implications": "Validated during central replay before database commit.",')
        lines.append(f'        "integration_implications": "Enforced across all external API endpoints.",')
        lines.append(f'        "performance_expectations": "Rule evaluation execution latency < 5ms.",')
        lines.append(f'        "availability_expectations": "Continuous enforcement across 100% of transactions.",')
        lines.append(f'        "localization_expectations": "Localized rejection error banners in Kannada and English.",')
        lines.append(f'        "accessibility_expectations": "WCAG 2.1 AA compliant visual error presentation.",')
        lines.append(f'        "failure_behavior": "Fail-closed; reject mutation if rule cannot be evaluated.",')
        lines.append(f'        "recovery_behavior": "Prompt operator to correct invalid inputs or seek supervisor approval.",')
        lines.append(f'        "observability_requirements": "OpenTelemetry span `namma.clinic.brule.{rule_id.lower()}`.",')
        lines.append(f'        "logging_requirements": "Emits structured JSON log with rule_id, outcome, and actor.",')
        lines.append(f'        "metrics": "Prometheus counter `namma_clinic_brule_evaluations_total{{rule_id=\\"{rule_id}\\"}}`.",')
        lines.append(f'        "acceptance_criteria": [')
        lines.append(f'            "System enforces {title.lower()} under all standard conditions.",')
        lines.append(f'            "Correctly permits allowed outcome: {allowed[:40]}...",')
        lines.append(f'            "Correctly blocks rejected outcome: {rejected[:40]}...",')
        lines.append(f'            "Emits mandatory audit event: {audit}."')
        lines.append(f'        ],')
        lines.append(f'        "verification_method": "Automated Vitest Business Logic & Unit Test",')
        lines.append(f'        "test_type": "Unit & Integration Rule Test",')
        lines.append(f'        "test_id": "PLANNED-TEST-{300 + i:03d}",')
        lines.append(f'        "objective_ref": "OBJECTIVE-{obj_idx:03d}",')
        lines.append(f'        "scope_ref": "INSCOPE-{insc_idx:03d}",')
        lines.append(f'        "stakeholder_ref": "STAKEHOLDER-{((i - 1) % 50) + 1:03d}",')
        lines.append(f'        "persona_ref": "PERSONA-{((i - 1) % 35) + 1:03d}",')
        lines.append(f'        "risk_ref": "RISK-{risk_idx:03d}",')
        lines.append(f'        "dependency_ref": "DEPENDENCY-{dep_idx:03d}",')
        lines.append(f'        "milestone_ref": "MILESTONE-{m_idx:03d}",')
        lines.append(f'        "release_ref": "RELEASE-{rel_idx:03d}",')
        lines.append(f'        "planned_epic": "PLANNED-EPIC-{((i - 1) % 30) + 1:03d}",')
        lines.append(f'        "planned_feature": "PLANNED-FEATURE-{((i - 1) % 60) + 1:03d}",')
        lines.append(f'        "planned_api": "PLANNED-API-{((i - 1) % 50) + 1:03d}",')
        lines.append(f'        "planned_db": "PLANNED-DB-{((i - 1) % 40) + 1:03d}",')
        lines.append(f'        "planned_ui": "PLANNED-UI-{((i - 1) % 40) + 1:03d}",')
        lines.append(f'        "planned_test": "PLANNED-TEST-{300 + i:03d}",')
        lines.append(f'        "related_requirements": ["FR-{((i - 1) % 80) + 1:03d}", "OR-{((i - 1) % 50) + 1:03d}"],')
        lines.append(f'        "conflicts": "None identified; aligned with municipal operational bylaws.",')
        lines.append(f'        "dependencies": ["BR-{((i - 1) % 50) + 1:03d}"],')
        lines.append(f'        "open_questions": "Confirm seasonal policy exceptions with BBMP Legal Division.",')
        lines.append(f'        "assumptions": "Clinic staff trained in standard municipal operational procedures.",')
        lines.append(f'        "constraints": "Rule evaluation logic must be synchronous and sub-millisecond."')
        lines.append("    },")

    lines.append("]")
    lines.append("")

    with open(target_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"Generated {target_path} with {len(BRULE_ITEMS)} business rules.")

def build_data_cr():
    target_path = os.path.join(os.path.dirname(__file__), "data_cr.py")
    lines = []
    lines.append("#!/usr/bin/env python3")
    lines.append('"""')
    lines.append("data_cr.py")
    lines.append("Canonical dataset for Clinical Rules (CR-001 through CR-050).")
    lines.append("CRITICAL PRINCIPLE: Decision-support only. Platform NEVER replaces qualified clinical judgment.")
    lines.append("Clinician remains fully responsible for diagnosis, treatment, and decisions.")
    lines.append('"""')
    lines.append("")
    lines.append("CR_RULES = [")

    for i, item in enumerate(CR_ITEMS, 1):
        (cr_id, title, severity, trigger, rationale, action, override_mech, override_reason, audit) = item
        statement = f"The platform SHALL alert the clinician to {title.lower()} when {trigger.lower()}, recommending that the doctor {action.lower()}."
        obj_idx = ((i - 1) % 40) + 1
        sc_idx = ((i - 1) % 40) + 1
        insc_idx = ((i - 1) % 80) + 1
        risk_idx = ((i - 1) % 60) + 1
        dep_idx = ((i - 1) % 50) + 1
        m_idx = ((i - 1) % 40) + 1
        rel_idx = ((i - 1) % 20) + 1

        lines.append("    {")
        lines.append(f'        "id": "{cr_id}",')
        lines.append(f'        "title": "{title}",')
        lines.append(f'        "statement": "{statement}",')
        lines.append(f'        "domain": "Clinical Decision Support",')
        lines.append(f'        "type": "Clinical Rule (Decision Support Only)",')
        lines.append(f'        "priority": "MUST",')
        lines.append(f'        "priority_rationale": "Non-negotiable patient safety boundary and clinical decision support prompt.",')
        lines.append(f'        "business_value": "Mitigates preventable clinical morbidity and adverse drug events.",')
        lines.append(f'        "rationale": "{rationale} (CRITICAL: System is advisory only; clinician maintains ultimate responsibility).",')
        lines.append(f'        "severity": "{severity}",')
        lines.append(f'        "actor": "Medical Officer",')
        lines.append(f'        "persona": "PERSONA-001",')
        lines.append(f'        "role": "ROLE-001",')
        lines.append(f'        "stakeholder": "STAKEHOLDER-002",')
        lines.append(f'        "trigger": "{trigger}",')
        lines.append(f'        "preconditions": "Active clinical encounter with patient physiological vitals or orders recorded.",')
        lines.append(f'        "inputs": "Measured vital signs, diagnostic results, patient age/weight, or candidate prescription drugs.",')
        lines.append(f'        "clinical_rationale": "{rationale}",')
        lines.append(f'        "recommended_action": "{action}",')
        lines.append(f'        "override_mechanism": "{override_mech}",')
        lines.append(f'        "override_reason_required": "{override_reason}",')
        lines.append(f'        "audit_requirement": "{audit}",')
        lines.append(f'        "validation": "Evaluated against standardized ICMR, WHO, and National Health Mission clinical guidelines.",')
        lines.append(f'        "main_flow": [')
        lines.append(f'            "Clinical data entered into encounter: {trigger.lower()}.",')
        lines.append(f'            "CDS rules engine evaluates clinical safety logic.",')
        lines.append(f'            "System triggers {severity} modal banner: {title}.",')
        lines.append(f'            "Clinician reviews advisory recommendation: {action}.",')
        lines.append(f'            "Clinician adopts recommendation OR executes documented override: {override_mech}."')
        lines.append(f'        ],')
        lines.append(f'        "alternate_flow": "If clinician overrides advisory, system requires documented justification note ({override_reason}).",')
        lines.append(f'        "exception_flow": "If critical emergency condition is flagged, system provides 1-click tertiary referral order slip.",')
        lines.append(f'        "postconditions": "Clinical decision committed with full practitioner acknowledgment and audit trail.",')
        lines.append(f'        "state_changes": "Logs clinical alert status and any associated override justification.",')
        lines.append(f'        "business_rules": "BRULE-{((i - 1) % 50) + 1:03d}",')
        lines.append(f'        "clinical_rules": "{cr_id}",')
        lines.append(f'        "operational_rules": "OR-{((i - 1) % 50) + 1:03d}",')
        lines.append(f'        "security_implications": "Requires authenticated Medical Officer session to override.",')
        lines.append(f'        "privacy_implications": "All physiological and diagnostic data encrypted per DPDP Act.",')
        lines.append(f'        "data_implications": "Emits audit record to `cds_alerts` and `cds_overrides` tables.",')
        lines.append(f'        "audit_requirements": "{audit}",')
        lines.append(f'        "offline_behavior": "Evaluated client-side in browser Web Worker without network dependency.",')
        lines.append(f'        "synchronization_implications": "Alert acknowledgments and override notes synced to central Loki store.",')
        lines.append(f'        "integration_implications": "Integrates with central clinical safety rules repository.",')
        lines.append(f'        "performance_expectations": "Clinical rule evaluation latency < 15ms.",')
        lines.append(f'        "availability_expectations": "100% active during doctor consultation workflow.",')
        lines.append(f'        "localization_expectations": "Advisory text rendered in English with Kannada clinical context summary.",')
        lines.append(f'        "accessibility_expectations": "High-contrast visual alert badge and screen reader audible chime.",')
        lines.append(f'        "failure_behavior": "Fail-safe; if CDS engine fails, allow consultation with warning banner.",')
        lines.append(f'        "recovery_behavior": "Restart client-side rule evaluation worker upon next input change.",')
        lines.append(f'        "observability_requirements": "OpenTelemetry span `namma.clinic.cr.{cr_id.lower()}`.",')
        lines.append(f'        "logging_requirements": "Structured JSON log with alert_id, severity, doctor_id, and action.",')
        lines.append(f'        "metrics": "Prometheus counter `namma_clinic_cr_alerts_total{{cr_id=\\"{cr_id}\\",severity=\\"{severity}\\"}}`.",')
        lines.append(f'        "acceptance_criteria": [')
        lines.append(f'            "System triggers {severity} alert upon detecting {title.lower()}.",')
        lines.append(f'            "Displays clear clinical rationale and recommended action: {action[:40]}...",')
        lines.append(f'            "Allows clinician override with mandatory documented reason.",')
        lines.append(f'            "Emits immutable audit event logging doctor response: {audit}."')
        lines.append(f'        ],')
        lines.append(f'        "verification_method": "Clinical Simulation & Automated Rule Verification Test",')
        lines.append(f'        "test_type": "Clinical Decision Support Rule Test",')
        lines.append(f'        "test_id": "PLANNED-TEST-{400 + i:03d}",')
        lines.append(f'        "objective_ref": "OBJECTIVE-{obj_idx:03d}",')
        lines.append(f'        "scope_ref": "INSCOPE-{insc_idx:03d}",')
        lines.append(f'        "stakeholder_ref": "STAKEHOLDER-002",')
        lines.append(f'        "persona_ref": "PERSONA-001",')
        lines.append(f'        "risk_ref": "RISK-{risk_idx:03d}",')
        lines.append(f'        "dependency_ref": "DEPENDENCY-{dep_idx:03d}",')
        lines.append(f'        "milestone_ref": "MILESTONE-{m_idx:03d}",')
        lines.append(f'        "release_ref": "RELEASE-{rel_idx:03d}",')
        lines.append(f'        "planned_epic": "PLANNED-EPIC-{((i - 1) % 30) + 1:03d}",')
        lines.append(f'        "planned_feature": "PLANNED-FEATURE-{((i - 1) % 60) + 1:03d}",')
        lines.append(f'        "planned_api": "PLANNED-API-{((i - 1) % 50) + 1:03d}",')
        lines.append(f'        "planned_db": "PLANNED-DB-{((i - 1) % 40) + 1:03d}",')
        lines.append(f'        "planned_ui": "PLANNED-UI-{((i - 1) % 40) + 1:03d}",')
        lines.append(f'        "planned_test": "PLANNED-TEST-{400 + i:03d}",')
        lines.append(f'        "related_requirements": ["FR-{((i - 1) % 80) + 1:03d}", "BRULE-{((i - 1) % 50) + 1:03d}"],')
        lines.append(f'        "conflicts": "None; strictly maintains clinician primacy and autonomy.",')
        lines.append(f'        "dependencies": ["BR-{((i - 1) % 50) + 1:03d}"],')
        lines.append(f'        "open_questions": "Annual clinical review of guideline thresholds by BBMP Medical Board.",')
        lines.append(f'        "assumptions": "Medical Officers hold recognized MBBS qualification and clinical judgment.",')
        lines.append(f'        "constraints": "System must NEVER autonomously block treatment or alter prescriptions."')
        lines.append("    },")

    lines.append("]")
    lines.append("")

    with open(target_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"Generated {target_path} with {len(CR_ITEMS)} clinical rules.")

def build_data_or():
    target_path = os.path.join(os.path.dirname(__file__), "data_or.py")
    lines = []
    lines.append("#!/usr/bin/env python3")
    lines.append('"""')
    lines.append("data_or.py")
    lines.append("Canonical dataset for Operational Rules (OR-001 through OR-050).")
    lines.append("Standard operating procedures, readiness protocols, and facility governance for Namma Clinic.")
    lines.append('"""')
    lines.append("")
    lines.append("OR_RULES = [")

    for i, item in enumerate(OR_ITEMS, 1):
        (or_id, title, trigger, protocol, hw_readiness, off_mode, handover, reconcil, approval, audit) = item
        statement = f"The clinic facility SHALL enforce {title.lower()} whenever {trigger.lower()}, executing standard operational protocol: {protocol}."
        obj_idx = ((i - 1) % 40) + 1
        sc_idx = ((i - 1) % 40) + 1
        insc_idx = ((i - 1) % 80) + 1
        risk_idx = ((i - 1) % 60) + 1
        dep_idx = ((i - 1) % 50) + 1
        m_idx = ((i - 1) % 40) + 1
        rel_idx = ((i - 1) % 20) + 1

        lines.append("    {")
        lines.append(f'        "id": "{or_id}",')
        lines.append(f'        "title": "{title}",')
        lines.append(f'        "statement": "{statement}",')
        lines.append(f'        "domain": "Operational Facility Governance",')
        lines.append(f'        "type": "Operational Rule",')
        lines.append(f'        "priority": "MUST",')
        lines.append(f'        "priority_rationale": "Mandatory standard operating procedure for facility safety and municipal accountability.",')
        lines.append(f'        "business_value": "Ensures uninterrupted facility readiness, supply chain continuity, and staff discipline.",')
        lines.append(f'        "rationale": "Standardizes clinic day-to-day operations and prevents infrastructure degradation.",')
        lines.append(f'        "actor": "Clinic Operational Staff",')
        lines.append(f'        "persona": "PERSONA-{((i - 1) % 35) + 1:03d}",')
        lines.append(f'        "role": "ROLE-{((i - 1) % 30) + 1:03d}",')
        lines.append(f'        "stakeholder": "STAKEHOLDER-003",')
        lines.append(f'        "trigger": "{trigger}",')
        lines.append(f'        "preconditions": "Clinic facility active during designated operational hours.",')
        lines.append(f'        "inputs": "Operational checklist responses, physical inspection findings, or equipment telemetry.",')
        lines.append(f'        "operational_protocol": "{protocol}",')
        lines.append(f'        "hardware_readiness": "{hw_readiness}",')
        lines.append(f'        "offline_behavior": "{off_mode}",')
        lines.append(f'        "shift_handover": "{handover}",')
        lines.append(f'        "daily_reconciliation": "{reconcil}",')
        lines.append(f'        "supervisor_approval": "{approval}",')
        lines.append(f'        "audit_requirement": "{audit}",')
        lines.append(f'        "validation": "Evaluated against BBMP Urban Primary Health Center Standard Operating Procedures.",')
        lines.append(f'        "main_flow": [')
        lines.append(f'            "Operational milestone triggered: {trigger.lower()}.",')
        lines.append(f'            "Staff executes protocol: {protocol}.",')
        lines.append(f'            "Hardware readiness verified: {hw_readiness}.",')
        lines.append(f'            "Reconciliation and supervisor sign-off logged: {approval}.",')
        lines.append(f'            "Immutable operational audit event recorded: {audit}."')
        lines.append(f'        ],')
        lines.append(f'        "alternate_flow": "If equipment or network failure occurs, execute offline fallback: {off_mode}.",')
        lines.append(f'        "exception_flow": "If operational protocol fails or breaches threshold, escalate to Zonal Health Officer within 30 mins.",')
        lines.append(f'        "postconditions": "Facility state conforms to operational readiness standards.",')
        lines.append(f'        "state_changes": "Updates clinic facility operational status and checklist journal.",')
        lines.append(f'        "business_rules": "BRULE-{((i - 1) % 50) + 1:03d}",')
        lines.append(f'        "clinical_rules": "CR-{((i - 1) % 50) + 1:03d}",')
        lines.append(f'        "operational_rules": "{or_id}",')
        lines.append(f'        "security_implications": "Staff must authenticate with verified personal credentials.",')
        lines.append(f'        "privacy_implications": "Physical facility logs must not expose patient names to waiting room visitors.",')
        lines.append(f'        "data_implications": "Checklists and telemetry persisted in `clinic_operations` schema.",')
        lines.append(f'        "audit_requirements": "{audit}",')
        lines.append(f'        "offline_behavior": "{off_mode}",')
        lines.append(f'        "synchronization_implications": "Operational logs buffered in Dexie.js and synced upon connection.",')
        lines.append(f'        "integration_implications": "Integrates with BBMP Facility Management Dashboard.",')
        lines.append(f'        "performance_expectations": "Checklist submission completes in < 500ms.",')
        lines.append(f'        "availability_expectations": "Facility operational rules enforced daily across all 183 clinics.",')
        lines.append(f'        "localization_expectations": "Checklist forms fully available in Kannada and English.",')
        lines.append(f'        "accessibility_expectations": "Touch-friendly check controls (>=48x48px hit targets).",')
        lines.append(f'        "failure_behavior": "Display visual warning; flag operational deficiency on supervisor dashboard.",')
        lines.append(f'        "recovery_behavior": "Execute corrective maintenance and log resolution timestamp.",')
        lines.append(f'        "observability_requirements": "OpenTelemetry span `namma.clinic.or.{or_id.lower()}`.",')
        lines.append(f'        "logging_requirements": "Structured JSON log with facility_id, rule_id, status, and operator.",')
        lines.append(f'        "metrics": "Prometheus gauge `namma_clinic_operational_readiness{{clinic_id=\\"...\\"}}`.",')
        lines.append(f'        "acceptance_criteria": [')
        lines.append(f'            "System enforces {title.lower()} during standard clinic shifts.",')
        lines.append(f'            "Records operational protocol verification: {protocol[:40]}...",')
        lines.append(f'            "Enforces offline fallback protocol: {off_mode[:40]}...",')
        lines.append(f'            "Logs supervisory approval: {approval}."')
        lines.append(f'        ],')
        lines.append(f'        "verification_method": "Facility Operational Audit & Daily Checklist Review",')
        lines.append(f'        "test_type": "Operational Workflow & Integration Test",')
        lines.append(f'        "test_id": "PLANNED-TEST-{500 + i:03d}",')
        lines.append(f'        "objective_ref": "OBJECTIVE-{obj_idx:03d}",')
        lines.append(f'        "scope_ref": "INSCOPE-{insc_idx:03d}",')
        lines.append(f'        "stakeholder_ref": "STAKEHOLDER-003",')
        lines.append(f'        "persona_ref": "PERSONA-{((i - 1) % 35) + 1:03d}",')
        lines.append(f'        "risk_ref": "RISK-{risk_idx:03d}",')
        lines.append(f'        "dependency_ref": "DEPENDENCY-{dep_idx:03d}",')
        lines.append(f'        "milestone_ref": "MILESTONE-{m_idx:03d}",')
        lines.append(f'        "release_ref": "RELEASE-{rel_idx:03d}",')
        lines.append(f'        "planned_epic": "PLANNED-EPIC-{((i - 1) % 30) + 1:03d}",')
        lines.append(f'        "planned_feature": "PLANNED-FEATURE-{((i - 1) % 60) + 1:03d}",')
        lines.append(f'        "planned_api": "PLANNED-API-{((i - 1) % 50) + 1:03d}",')
        lines.append(f'        "planned_db": "PLANNED-DB-{((i - 1) % 40) + 1:03d}",')
        lines.append(f'        "planned_ui": "PLANNED-UI-{((i - 1) % 40) + 1:03d}",')
        lines.append(f'        "planned_test": "PLANNED-TEST-{500 + i:03d}",')
        lines.append(f'        "related_requirements": ["FR-{((i - 1) % 80) + 1:03d}", "BRULE-{((i - 1) % 50) + 1:03d}"],')
        lines.append(f'        "conflicts": "None identified; aligned with municipal health operating protocols.",')
        lines.append(f'        "dependencies": ["BR-{((i - 1) % 50) + 1:03d}"],')
        lines.append(f'        "open_questions": "Quarterly review of facility checklist items by BBMP Quality Assurance Cell.",')
        lines.append(f'        "assumptions": "Clinic facilities equipped with functional power backup and internet dongles.",')
        lines.append(f'        "constraints": "Checklist execution must not delay emergency patient care."')
        lines.append("    },")

    lines.append("]")
    lines.append("")

    with open(target_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"Generated {target_path} with {len(OR_ITEMS)} operational rules.")

if __name__ == "__main__":
    build_data_brule()
    build_data_cr()
    build_data_or()
