#!/usr/bin/env python3
"""
build_data_13_to_17.py
Builds dataset files for documents 13 to 17:
  - data_off.py (OFF-001 to OFF-050)
  - data_rep.py (REP-001 to REP-050)
  - data_anl.py (ANL-001 to ANL-040)
  - data_air.py (AIR-001 to AIR-040)
  - data_int.py (INT-001 to INT-050)
"""

import os
import sys

sys.path.append(os.path.dirname(__file__))
from build_defs_13_17 import OFF_ITEMS, REP_ITEMS, ANL_ITEMS, AIR_ITEMS, INT_ITEMS

DIR_PATH = os.path.dirname(os.path.abspath(__file__))

def build_data_files():
    # -------------------------------------------------------------------------
    # 1. data_off.py (50 items)
    # -------------------------------------------------------------------------
    with open(os.path.join(DIR_PATH, "data_off.py"), "w", encoding="utf-8") as f:
        f.write('#!/usr/bin/env python3\n"""data_off.py: 50 Offline Autonomy Requirements (OFF-001 to OFF-050)"""\n\nOFF_REQUIREMENTS = [\n')
        for i, item in enumerate(OFF_ITEMS, 1):
            (req_id, title, state, store_schema, conflict_strategy, vmethod, owner) = item
            statement = f"The platform SHALL enforce {title.lower()} during {state.lower()} utilizing {store_schema} and resolving conflicts via {conflict_strategy}."
            f.write("    {\n")
            f.write(f'        "id": "{req_id}",\n')
            f.write(f'        "title": "{title}",\n')
            f.write(f'        "statement": "{statement}",\n')
            f.write(f'        "domain": "{state}",\n')
            f.write(f'        "type": "Offline Autonomy Requirement",\n')
            f.write(f'        "priority": "MUST",\n')
            f.write(f'        "priority_rationale": "Mandatory clinic operational continuity guaranteeing zero stoppage during fiber or cellular outages.",\n')
            f.write(f'        "business_value": "Guarantees 100% uninterrupted healthcare delivery for citizens regardless of connectivity.",\n')
            f.write(f'        "rationale": "Ensures {title.lower()} using local IndexedDB Dexie.js store: {store_schema}.",\n')
            f.write(f'        "offline_mode_state": "{state}",\n')
            f.write(f'        "local_store_schema": "{store_schema}",\n')
            f.write(f'        "conflict_resolution_strategy": "{conflict_strategy}",\n')
            f.write(f'        "verification_method": "{vmethod}",\n')
            f.write(f'        "owner": "{owner}",\n')
            f.write(f'        "actor": "Clinic Workstation PWA Client",\n')
            f.write(f'        "persona": "PERSONA-{((i - 1) % 35) + 1:03d}",\n')
            f.write(f'        "role": "ROLE-002",\n')
            f.write(f'        "stakeholder": "STAKEHOLDER-008",\n')
            f.write(f'        "trigger": "Network disconnection, offline write mutation, or sync window reconnection.",\n')
            f.write(f'        "preconditions": "Local browser initialized with Dexie.js database and valid cryptographic salt.",\n')
            f.write(f'        "inputs": "Clinical mutation payload, timestamp, local UUIDv7, and state transition flags.",\n')
            f.write(f'        "validation": "Evaluated against local schema constraints and idempotency hashes before queue commit.",\n')
            f.write(f'        "main_flow": [\n')
            f.write(f'            "Client detects operational mode: {state}.",\n')
            f.write(f'            "Mutation written locally to Dexie.js store: {store_schema}.",\n')
            f.write(f'            "Offline mutation queue buffers payload with monotonic sequence ordering.",\n')
            f.write(f'            "Conflict engine applies resolution strategy: {conflict_strategy}.",\n')
            f.write(f'            "On network restoration, background worker flushes queued transactions with zero data loss."\n')
            f.write(f'        ],\n')
            f.write(f'        "alternate_flow": "If network flickers intermittently, buffer mutations in memory and retry IndexedDB batch flush.",\n')
            f.write(f'        "exception_flow": "If local IndexedDB storage reaches 90% quota, evict non-essential read caches and alert operator.",\n')
            f.write(f'        "postconditions": "Local database state consistent; zero uncommitted mutations lost across restarts.",\n')
            f.write(f'        "state_changes": "Updates Dexie.js local mutation queue and increments pending sync counter.",\n')
            f.write(f'        "business_rules": "BRULE-{((i - 1) % 50) + 1:03d}",\n')
            f.write(f'        "clinical_rules": "CR-{((i - 1) % 50) + 1:03d}",\n')
            f.write(f'        "operational_rules": "OR-{((i - 1) % 50) + 1:03d}",\n')
            f.write(f'        "security_implications": "Local IndexedDB stores encrypted via AES-256-GCM Web Cryptography API.",\n')
            f.write(f'        "privacy_implications": "Sensitive patient PII cached locally is purged upon workstation user logout.",\n')
            f.write(f'        "data_implications": "UUIDv7 monotonic primary keys prevent ID collisions across 183 clinics.",\n')
            f.write(f'        "audit_requirements": "Offline mutation timestamps and sync telemetry logged to WORM vault.",\n')
            f.write(f'        "offline_behavior": "Autonomous offline execution with zero dependency on central cloud connectivity.",\n')
            f.write(f'        "synchronization_implications": "Server endpoint enforces idempotency keys and delta merge verification.",\n')
            f.write(f'        "integration_implications": "Local ESC/POS thermal printer jobs spooled offline and printed without server lag.",\n')
            f.write(f'        "performance_expectations": "Local IndexedDB commit latency under 10ms for 99% of mutations.",\n')
            f.write(f'        "availability_expectations": "Guaranteed 8 hours autonomous offline operation without network connectivity.",\n')
            f.write(f'        "localization_expectations": "Offline translation bundles cached locally in PWA service worker.",\n')
            f.write(f'        "accessibility_expectations": "Accessible offline status indicator banner visible on all clinic screens.",\n')
            f.write(f'        "failure_behavior": "Isolate conflicting records to quarantine table without blocking remaining queue.",\n')
            f.write(f'        "recovery_behavior": "Automated exponential backoff reconnect with jitter upon network restoration.",\n')
            f.write(f'        "observability_requirements": "OpenTelemetry span `namma.clinic.off.{req_id.lower()}`.",\n')
            f.write(f'        "logging_requirements": "Structured JSON client log with queue_depth, sync_state, and mutation_id.",\n')
            f.write(f'        "metrics": "Prometheus gauge `namma_clinic_offline_queue_depth{{clinic_id=\\"BLR-001\\"}}`.",\n')
            f.write(f'        "acceptance_criteria": [\n')
            f.write(f'            "System enforces {title.lower()} during {state.lower()}.",\n')
            f.write(f'            "Local store adheres to schema: {store_schema}.",\n')
            f.write(f'            "Resolves conflicts using: {conflict_strategy}.",\n')
            f.write(f'            "Verified via: {vmethod}."\n')
            f.write(f'        ],\n')
            f.write(f'        "test_type": "Automated Offline Disconnection & Reconciliation Test",\n')
            f.write(f'        "test_id": "PLANNED-TEST-{1200 + i:03d}",\n')
            f.write(f'        "objective_ref": "OBJECTIVE-{((i - 1) % 40) + 1:03d}",\n')
            f.write(f'        "scope_ref": "INSCOPE-{((i - 1) % 80) + 1:03d}",\n')
            f.write(f'        "stakeholder_ref": "STAKEHOLDER-008",\n')
            f.write(f'        "persona_ref": "PERSONA-{((i - 1) % 35) + 1:03d}",\n')
            f.write(f'        "risk_ref": "RISK-{((i - 1) % 60) + 1:03d}",\n')
            f.write(f'        "dependency_ref": "DEPENDENCY-{((i - 1) % 50) + 1:03d}",\n')
            f.write(f'        "milestone_ref": "MILESTONE-{((i - 1) % 40) + 1:03d}",\n')
            f.write(f'        "release_ref": "RELEASE-{((i - 1) % 20) + 1:03d}",\n')
            f.write(f'        "planned_epic": "PLANNED-EPIC-{((i - 1) % 30) + 1:03d}",\n')
            f.write(f'        "planned_feature": "PLANNED-FEATURE-{((i - 1) % 60) + 1:03d}",\n')
            f.write(f'        "planned_api": "PLANNED-API-{((i - 1) % 50) + 1:03d}",\n')
            f.write(f'        "planned_db": "PLANNED-DB-{((i - 1) % 40) + 1:03d}",\n')
            f.write(f'        "planned_ui": "PLANNED-UI-{((i - 1) % 40) + 1:03d}",\n')
            f.write(f'        "planned_test": "PLANNED-TEST-{1200 + i:03d}",\n')
            f.write(f'        "related_requirements": ["NFR-009", "NFR-010", "AVAIL-002"],\n')
            f.write(f'        "conflicts": "None identified; maximizes local autonomy during network isolation.",\n')
            f.write(f'        "dependencies": ["NFR-009"],\n')
            f.write(f'        "open_questions": "Validation of IndexedDB eviction policies across legacy Chromium releases.",\n')
            f.write(f'        "assumptions": "Clinic workstations equipped with modern Chromium-based browser supporting IndexedDB.",\n')
            f.write(f'        "constraints": "Workstation memory footprint must remain strictly under 150MB."\n')
            f.write("    },\n")
        f.write("]\n")

    # -------------------------------------------------------------------------
    # 2. data_rep.py (50 items)
    # -------------------------------------------------------------------------
    with open(os.path.join(DIR_PATH, "data_rep.py"), "w", encoding="utf-8") as f:
        f.write('#!/usr/bin/env python3\n"""data_rep.py: 50 Reporting Requirements (REP-001 to REP-050)"""\n\nREP_REQUIREMENTS = [\n')
        for i, item in enumerate(REP_ITEMS, 1):
            (req_id, title, freq, audience, sources, formats, owner) = item
            statement = f"The platform SHALL generate {title.lower()} on a {freq.lower()} cadence for {audience}, aggregating data from {sources}, exportable as {formats}."
            f.write("    {\n")
            f.write(f'        "id": "{req_id}",\n')
            f.write(f'        "title": "{title}",\n')
            f.write(f'        "statement": "{statement}",\n')
            f.write(f'        "domain": "Operational Reporting",\n')
            f.write(f'        "type": "Reporting Requirement",\n')
            f.write(f'        "priority": "MUST",\n')
            f.write(f'        "priority_rationale": "Essential operational and statutory reporting mandated by municipal health authorities.",\n')
            f.write(f'        "business_value": "Ensures administrative accountability, clinical auditability, and regulatory compliance.",\n')
            f.write(f'        "rationale": "Cadence: {freq}; Target Audience: {audience}; Data Sources: {sources}.",\n')
            f.write(f'        "report_frequency": "{freq}",\n')
            f.write(f'        "target_audience": "{audience}",\n')
            f.write(f'        "data_sources": "{sources}",\n')
            f.write(f'        "export_formats": "{formats}",\n')
            f.write(f'        "verification_method": "Automated Report Output & Data Reconciliation Test",\n')
            f.write(f'        "owner": "{owner}",\n')
            f.write(f'        "actor": "{owner}",\n')
            f.write(f'        "persona": "PERSONA-{((i - 1) % 35) + 1:03d}",\n')
            f.write(f'        "role": "ROLE-001",\n')
            f.write(f'        "stakeholder": "STAKEHOLDER-004",\n')
            f.write(f'        "trigger": "Scheduled cron job, end-of-day trigger, or authorized supervisor export request.",\n')
            f.write(f'        "preconditions": "Relevant transactional tables populated; user possesses authenticated reporting role.",\n')
            f.write(f'        "inputs": "Date range filter, clinic identifier, ward boundaries, and export format parameter.",\n')
            f.write(f'        "validation": "Evaluated against query date bounds and RBAC reporting permission scope.",\n')
            f.write(f'        "main_flow": [\n')
            f.write(f'            "User or scheduled cron triggers report generation: {title}.",\n')
            f.write(f'            "Report engine queries data sources: {sources}.",\n')
            f.write(f'            "Applies calculation formulas and aggregation rules across date range.",\n')
            f.write(f'            "Formats structured document according to selected format: {formats}.",\n')
            f.write(f'            "Dispatches output to user interface or persists to secure report repository."\n')
            f.write(f'        ],\n')
            f.write(f'        "alternate_flow": "If report exceeds 10,000 rows, stream CSV chunked download to prevent memory spikes.",\n')
            f.write(f'        "exception_flow": "If source database unavailable, return cached previous-day report with explicit staleness banner.",\n')
            f.write(f'        "postconditions": "Report successfully generated, checksum validated, and access event logged to audit vault.",\n')
            f.write(f'        "state_changes": "Records report export event in audit log with user_id, report_id, and row_count.",\n')
            f.write(f'        "business_rules": "BRULE-{((i - 1) % 50) + 1:03d}",\n')
            f.write(f'        "clinical_rules": "CR-{((i - 1) % 50) + 1:03d}",\n')
            f.write(f'        "operational_rules": "OR-{((i - 1) % 50) + 1:03d}",\n')
            f.write(f'        "security_implications": "RBAC restricts patient-level identifiable exports to authorized Medical Officers.",\n')
            f.write(f'        "privacy_implications": "Publicly shared reports automatically apply k-anonymity (k>=5) suppression.",\n')
            f.write(f'        "data_implications": "Queries execute against read-replica or DuckDB mart to protect OLTP performance.",\n')
            f.write(f'        "audit_requirements": "All report generation and export events recorded in immutable WORM audit log.",\n')
            f.write(f'        "offline_behavior": "Local daily summary reports generated from IndexedDB store during offline periods.",\n')
            f.write(f'        "synchronization_implications": "Central reports reflect consolidated municipal data upon clinic sync completion.",\n')
            f.write(f'        "integration_implications": "Exports compatible with State Health Portal and IHIP ingestion formats.",\n')
            f.write(f'        "performance_expectations": "Standard daily report generation completed in < 2.0 seconds.",\n')
            f.write(f'        "availability_expectations": "100% daily reporting availability across all operational clinics.",\n')
            f.write(f'        "localization_expectations": "Report headers and numerical summaries fully localized in Kannada and English.",\n')
            f.write(f'        "accessibility_expectations": "Generated HTML reports conform to WCAG 2.1 Level AA table structure.",\n')
            f.write(f'        "failure_behavior": "Display localized error message with retry button if query times out.",\n')
            f.write(f'        "recovery_behavior": "Resume aborted PDF generation from background worker task queue.",\n')
            f.write(f'        "observability_requirements": "OpenTelemetry span `namma.clinic.rep.{req_id.lower()}`.",\n')
            f.write(f'        "logging_requirements": "Structured JSON log with report_id, execution_time_ms, and row_count.",\n')
            f.write(f'        "metrics": "Prometheus counter `namma_clinic_reports_generated_total{{report=\\"{req_id}\\"}}`.",\n')
            f.write(f'        "acceptance_criteria": [\n')
            f.write(f'            "System enforces {title.lower()} on {freq.lower()} cadence.",\n')
            f.write(f'            "Delivered to target audience: {audience}.",\n')
            f.write(f'            "Aggregates data sources: {sources}.",\n')
            f.write(f'            "Produces valid formats: {formats}."\n')
            f.write(f'        ],\n')
            f.write(f'        "test_type": "Automated Report Generation & Data Integrity Test",\n')
            f.write(f'        "test_id": "PLANNED-TEST-{1300 + i:03d}",\n')
            f.write(f'        "objective_ref": "OBJECTIVE-{((i - 1) % 40) + 1:03d}",\n')
            f.write(f'        "scope_ref": "INSCOPE-{((i - 1) % 80) + 1:03d}",\n')
            f.write(f'        "stakeholder_ref": "STAKEHOLDER-004",\n')
            f.write(f'        "persona_ref": "PERSONA-{((i - 1) % 35) + 1:03d}",\n')
            f.write(f'        "risk_ref": "RISK-{((i - 1) % 60) + 1:03d}",\n')
            f.write(f'        "dependency_ref": "DEPENDENCY-{((i - 1) % 50) + 1:03d}",\n')
            f.write(f'        "milestone_ref": "MILESTONE-{((i - 1) % 40) + 1:03d}",\n')
            f.write(f'        "release_ref": "RELEASE-{((i - 1) % 20) + 1:03d}",\n')
            f.write(f'        "planned_epic": "PLANNED-EPIC-{((i - 1) % 30) + 1:03d}",\n')
            f.write(f'        "planned_feature": "PLANNED-FEATURE-{((i - 1) % 60) + 1:03d}",\n')
            f.write(f'        "planned_api": "PLANNED-API-{((i - 1) % 50) + 1:03d}",\n')
            f.write(f'        "planned_db": "PLANNED-DB-{((i - 1) % 40) + 1:03d}",\n')
            f.write(f'        "planned_ui": "PLANNED-UI-{((i - 1) % 40) + 1:03d}",\n')
            f.write(f'        "planned_test": "PLANNED-TEST-{1300 + i:03d}",\n')
            f.write(f'        "related_requirements": ["FR-035", "NFR-031", "ANL-001"],\n')
            f.write(f'        "conflicts": "None identified; balances analytical reporting with operational database isolation.",\n')
            f.write(f'        "dependencies": ["FR-035"],\n')
            f.write(f'        "open_questions": "Final approval of municipal Form M template fields by BBMP Health Department.",\n')
            f.write(f'        "assumptions": "Clinic workstations equipped with standard PDF reader and printer drivers.",\n')
            f.write(f'        "constraints": "Heavy reporting queries must never degrade frontline consultation responsiveness."\n')
            f.write("    },\n")
        f.write("]\n")

    # -------------------------------------------------------------------------
    # 3. data_anl.py (40 items)
    # -------------------------------------------------------------------------
    with open(os.path.join(DIR_PATH, "data_anl.py"), "w", encoding="utf-8") as f:
        f.write('#!/usr/bin/env python3\n"""data_anl.py: 40 Analytics & Data Platform Requirements (ANL-001 to ANL-040)"""\n\nANL_REQUIREMENTS = [\n')
        for i, item in enumerate(ANL_ITEMS, 1):
            (req_id, title, dim, cadence, target_store, vmethod, owner) = item
            statement = f"The platform SHALL implement {title.lower()} across the {dim.lower()} dimension on a {cadence.lower()} cadence targeting {target_store}."
            f.write("    {\n")
            f.write(f'        "id": "{req_id}",\n')
            f.write(f'        "title": "{title}",\n')
            f.write(f'        "statement": "{statement}",\n')
            f.write(f'        "domain": "{dim}",\n')
            f.write(f'        "type": "Analytics & Data Platform Requirement",\n')
            f.write(f'        "priority": "MUST",\n')
            f.write(f'        "priority_rationale": "Foundational data intelligence enabling municipal epidemiological surveillance and resource optimization.",\n')
            f.write(f'        "business_value": "Transforms raw clinic transaction data into actionable public health insights.",\n')
            f.write(f'        "rationale": "Dimension: {dim}; Cadence: {cadence}; Analytical Target: {target_store}.",\n')
            f.write(f'        "analytical_dimension": "{dim}",\n')
            f.write(f'        "aggregation_cadence": "{cadence}",\n')
            f.write(f'        "duckdb_query_target": "{target_store}",\n')
            f.write(f'        "verification_method": "{vmethod}",\n')
            f.write(f'        "owner": "{owner}",\n')
            f.write(f'        "actor": "Data Platform Pipeline",\n')
            f.write(f'        "persona": "PERSONA-{((i - 1) % 35) + 1:03d}",\n')
            f.write(f'        "role": "ROLE-004",\n')
            f.write(f'        "stakeholder": "STAKEHOLDER-006",\n')
            f.write(f'        "trigger": "Scheduled ETL batch, CDC change event, or analytical dashboard query execution.",\n')
            f.write(f'        "preconditions": "Source OLTP database healthy; DuckDB engine initialized with valid schema.",\n')
            f.write(f'        "inputs": "Transactional CDC logs, dimensional foreign keys, and temporal window parameters.",\n')
            f.write(f'        "validation": "Evaluated against schema integrity constraints, null-check thresholds, and foreign key references.",\n')
            f.write(f'        "main_flow": [\n')
            f.write(f'            "Data pipeline extracts change records for dimension: {dim}.",\n')
            f.write(f'            "Transforms records into star-schema fact/dimension format.",\n')
            f.write(f'            "Loads processed dataset into target store: {target_store}.",\n')
            f.write(f'            "Executes quality verification and freshness checks: {vmethod}.",\n')
            f.write(f'            "Refreshes analytical dashboard views with sub-second response times."\n')
            f.write(f'        ],\n')
            f.write(f'        "alternate_flow": "If DuckDB query memory exceeds 1GB cap, spill temporary intermediate arrays to disk.",\n')
            f.write(f'        "exception_flow": "If CDC ingestion lags by >2 hours, trigger automated alert to Data Platform Lead.",\n')
            f.write(f'        "postconditions": "Analytical datamart refreshed; data lineage metadata recorded in catalog.",\n')
            f.write(f'        "state_changes": "Updates analytical watermark timestamp and inserts aggregated fact records.",\n')
            f.write(f'        "business_rules": "BRULE-{((i - 1) % 50) + 1:03d}",\n')
            f.write(f'        "clinical_rules": "CR-{((i - 1) % 50) + 1:03d}",\n')
            f.write(f'        "operational_rules": "OR-{((i - 1) % 50) + 1:03d}",\n')
            f.write(f'        "security_implications": "Analytical views enforce column-level PII masking for non-clinical analytical users.",\n')
            f.write(f'        "privacy_implications": "All exported analytical datasets enforce k-anonymity (k>=5) and l-diversity.",\n')
            f.write(f'        "data_implications": "Zero mutation locks on transactional PostgreSQL tables; uses logical replication.",\n')
            f.write(f'        "audit_requirements": "Analytical query logs and export metadata tracked in compliance ledger.",\n')
            f.write(f'        "offline_behavior": "Clinic-level DuckDB instances execute analytical queries locally without server access.",\n')
            f.write(f'        "synchronization_implications": "Central cloud lakehouse consolidates daily Parquet partitions from 183 clinics.",\n')
            f.write(f'        "integration_implications": "Exposes standard Parquet and Arrow flight endpoints for municipal BI tools.",\n')
            f.write(f'        "performance_expectations": "Analytical aggregations across 500k rows execute in < 1.5 seconds on DuckDB.",\n')
            f.write(f'        "availability_expectations": "99.5% availability for executive dashboards and municipal health feeds.",\n')
            f.write(f'        "localization_expectations": "Analytical dimension labels support bilingual Kannada and English metadata.",\n')
            f.write(f'        "accessibility_expectations": "Analytical charts paired with accessible data tables for screen readers.",\n')
            f.write(f'        "failure_behavior": "Fall back to previous snapshot partition if ETL pipeline job fails.",\n')
            f.write(f'        "recovery_behavior": "Automated pipeline re-run from last validated CDC checkpoint.",\n')
            f.write(f'        "observability_requirements": "OpenTelemetry span `namma.clinic.anl.{req_id.lower()}`.",\n')
            f.write(f'        "logging_requirements": "Structured JSON log with query_duration_ms, memory_used_mb, and rows_processed.",\n')
            f.write(f'        "metrics": "Prometheus histogram `namma_clinic_analytics_query_duration_seconds{{dim=\\"{dim}\\"}}`.",\n')
            f.write(f'        "acceptance_criteria": [\n')
            f.write(f'            "System enforces {title.lower()} for {dim.lower()}.",\n')
            f.write(f'            "Executes on cadence: {cadence}.",\n')
            f.write(f'            "Targets analytical store: {target_store}.",\n')
            f.write(f'            "Verified via: {vmethod}."\n')
            f.write(f'        ],\n')
            f.write(f'        "test_type": "Automated Analytical Data Pipeline & Query Benchmark Test",\n')
            f.write(f'        "test_id": "PLANNED-TEST-{1400 + i:03d}",\n')
            f.write(f'        "objective_ref": "OBJECTIVE-{((i - 1) % 40) + 1:03d}",\n')
            f.write(f'        "scope_ref": "INSCOPE-{((i - 1) % 80) + 1:03d}",\n')
            f.write(f'        "stakeholder_ref": "STAKEHOLDER-006",\n')
            f.write(f'        "persona_ref": "PERSONA-{((i - 1) % 35) + 1:03d}",\n')
            f.write(f'        "risk_ref": "RISK-{((i - 1) % 60) + 1:03d}",\n')
            f.write(f'        "dependency_ref": "DEPENDENCY-{((i - 1) % 50) + 1:03d}",\n')
            f.write(f'        "milestone_ref": "MILESTONE-{((i - 1) % 40) + 1:03d}",\n')
            f.write(f'        "release_ref": "RELEASE-{((i - 1) % 20) + 1:03d}",\n')
            f.write(f'        "planned_epic": "PLANNED-EPIC-{((i - 1) % 30) + 1:03d}",\n')
            f.write(f'        "planned_feature": "PLANNED-FEATURE-{((i - 1) % 60) + 1:03d}",\n')
            f.write(f'        "planned_api": "PLANNED-API-{((i - 1) % 50) + 1:03d}",\n')
            f.write(f'        "planned_db": "PLANNED-DB-{((i - 1) % 40) + 1:03d}",\n')
            f.write(f'        "planned_ui": "PLANNED-UI-{((i - 1) % 40) + 1:03d}",\n')
            f.write(f'        "planned_test": "PLANNED-TEST-{1400 + i:03d}",\n')
            f.write(f'        "related_requirements": ["NFR-038", "REP-035", "INT-029"],\n')
            f.write(f'        "conflicts": "None identified; enforces strict read/write database isolation.",\n')
            f.write(f'        "dependencies": ["NFR-038"],\n')
            f.write(f'        "open_questions": "Integration testing with BBMP GIS shapefile coordinates.",\n')
            f.write(f'        "assumptions": "Workstation browsers have sufficient memory to allocate DuckDB WebAssembly workers.",\n')
            f.write(f'        "constraints": "DuckDB local memory allocation capped strictly at 1GB."\n')
            f.write("    },\n")
        f.write("]\n")

    # -------------------------------------------------------------------------
    # 4. data_air.py (40 items)
    # -------------------------------------------------------------------------
    with open(os.path.join(DIR_PATH, "data_air.py"), "w", encoding="utf-8") as f:
        f.write('#!/usr/bin/env python3\n"""data_air.py: 40 AI & Clinical Decision-Support Requirements (AIR-001 to AIR-040)"""\n\nAIR_REQUIREMENTS = [\n')
        for i, item in enumerate(AIR_ITEMS, 1):
            (req_id, title, scope, model, override_protocol, vmethod, owner) = item
            statement = f"The platform SHALL provide advisory {title.lower()} within {scope.lower()} utilizing {model}, with mandatory human oversight enforced via {override_protocol}."
            f.write("    {\n")
            f.write(f'        "id": "{req_id}",\n')
            f.write(f'        "title": "{title}",\n')
            f.write(f'        "statement": "{statement}",\n')
            f.write(f'        "domain": "{scope}",\n')
            f.write(f'        "type": "AI Decision-Support Requirement",\n')
            f.write(f'        "priority": "MUST",\n')
            f.write(f'        "priority_rationale": "High clinical safety and diagnostic support value with mandatory clinician decision primacy.",\n')
            f.write(f'        "business_value": "Augments clinical quality, prevents medical errors, and optimizes municipal drug inventory.",\n')
            f.write(f'        "rationale": "Advisory Scope: {scope}; Model Architecture: {model}; Human Oversight: {override_protocol}.",\n')
            f.write(f'        "clinical_advisory_scope": "{scope}",\n')
            f.write(f'        "ml_model_family": "{model}",\n')
            f.write(f'        "human_override_protocol": "{override_protocol}",\n')
            f.write(f'        "verification_method": "{vmethod}",\n')
            f.write(f'        "owner": "{owner}",\n')
            f.write(f'        "actor": "Clinical Decision Support System (Advisory)",\n')
            f.write(f'        "persona": "PERSONA-{((i - 1) % 35) + 1:03d}",\n')
            f.write(f'        "role": "ROLE-001",\n')
            f.write(f'        "stakeholder": "STAKEHOLDER-002",\n')
            f.write(f'        "trigger": "Clinical consultation data entry, prescription selection, lab order, or inventory projection.",\n')
            f.write(f'        "preconditions": "Licensed clinician active in consultation session; patient context loaded in memory.",\n')
            f.write(f'        "inputs": "Patient symptoms, vitals, active prescription list, lab results, and demographic attributes.",\n')
            f.write(f'        "validation": "Evaluated against clinical guideline safety bounds and confidence threshold (>70%).",\n')
            f.write(f'        "main_flow": [\n')
            f.write(f'            "User enters clinical or operational parameters for scope: {scope}.",\n')
            f.write(f'            "Advisory model executes inference: {model}.",\n')
            f.write(f'            "Evaluates confidence score against calibration thresholds (suppresses if <70%).",\n')
            f.write(f'            "Presents non-intrusive advisory recommendation with top feature attributions.",\n')
            f.write(f'            "Clinician reviews recommendation and confirms or overrides: {override_protocol}."\n')
            f.write(f'        ],\n')
            f.write(f'        "alternate_flow": "If clinician overrides advisory prompt, display mandatory reason dropdown and proceed immediately.",\n')
            f.write(f'        "exception_flow": "If AI inference service times out (>200ms), silently fall back to standard clinical entry without blocking.",\n')
            f.write(f'        "postconditions": "Clinician retains full decision authority; advisory event and clinician action recorded in audit vault.",\n')
            f.write(f'        "state_changes": "Logs inference ID, model version, confidence score, and clinician acceptance/override status.",\n')
            f.write(f'        "business_rules": "BRULE-{((i - 1) % 50) + 1:03d}",\n')
            f.write(f'        "clinical_rules": "CR-{((i - 1) % 50) + 1:03d}",\n')
            f.write(f'        "operational_rules": "OR-{((i - 1) % 50) + 1:03d}",\n')
            f.write(f'        "security_implications": "AI models execute in hardened sandbox with zero internet-facing telemetry leakage.",\n')
            f.write(f'        "privacy_implications": "Zero patient PII used in real-time inference; features tokenized or anonymized.",\n')
            f.write(f'        "data_implications": "Training datasets derived exclusively from de-identified retrospective clinical data.",\n')
            f.write(f'        "audit_requirements": "All AI recommendations, confidence scores, and doctor overrides stored in WORM vault.",\n')
            f.write(f'        "offline_behavior": "Deterministic rule-based clinical safety checks execute client-side during offline mode.",\n')
            f.write(f'        "synchronization_implications": "Model inference telemetry synced asynchronously to cloud monitoring lakehouse.",\n')
            f.write(f'        "integration_implications": "Integrates via standard HL7 CDS Hooks JSON protocol (`OrderSelect`, `PatientView`).",\n')
            f.write(f'        "performance_expectations": "Advisory recommendation rendered in < 200ms with zero user workflow interruption.",\n')
            f.write(f'        "availability_expectations": "Graceful degradation ensures 100% clinic EHR uptime even if AI service is offline.",\n')
            f.write(f'        "localization_expectations": "Advisory prompts and explanation tooltips fully bilingual in Kannada and English.",\n')
            f.write(f'        "accessibility_expectations": "Advisory warning toasts announce politely to screen readers via ARIA live regions.",\n')
            f.write(f'        "failure_behavior": "Completely silent degradation to manual entry; system never halts clinical workflows.",\n')
            f.write(f'        "recovery_behavior": "Automated model health check probes re-enable advisory service when backend recovers.",\n')
            f.write(f'        "observability_requirements": "OpenTelemetry span `namma.clinic.air.{req_id.lower()}`.",\n')
            f.write(f'        "logging_requirements": "Structured JSON log with model_version, confidence_score, and override_reason.",\n')
            f.write(f'        "metrics": "Prometheus counter `namma_clinic_ai_overrides_total{{model=\\"{req_id}\\"}}`.",\n')
            f.write(f'        "acceptance_criteria": [\n')
            f.write(f'            "System enforces advisory {title.lower()}.",\n')
            f.write(f'            "Model adheres to family: {model}.",\n')
            f.write(f'            "Human override strictly enforced: {override_protocol}.",\n')
            f.write(f'            "Verified via: {vmethod}."\n')
            f.write(f'        ],\n')
            f.write(f'        "test_type": "Automated AI Model Safety & Override Workflow Test",\n')
            f.write(f'        "test_id": "PLANNED-TEST-{1500 + i:03d}",\n')
            f.write(f'        "objective_ref": "OBJECTIVE-{((i - 1) % 40) + 1:03d}",\n')
            f.write(f'        "scope_ref": "INSCOPE-{((i - 1) % 80) + 1:03d}",\n')
            f.write(f'        "stakeholder_ref": "STAKEHOLDER-002",\n')
            f.write(f'        "persona_ref": "PERSONA-{((i - 1) % 35) + 1:03d}",\n')
            f.write(f'        "risk_ref": "RISK-{((i - 1) % 60) + 1:03d}",\n')
            f.write(f'        "dependency_ref": "DEPENDENCY-{((i - 1) % 50) + 1:03d}",\n')
            f.write(f'        "milestone_ref": "MILESTONE-{((i - 1) % 40) + 1:03d}",\n')
            f.write(f'        "release_ref": "RELEASE-{((i - 1) % 20) + 1:03d}",\n')
            f.write(f'        "planned_epic": "PLANNED-EPIC-{((i - 1) % 30) + 1:03d}",\n')
            f.write(f'        "planned_feature": "PLANNED-FEATURE-{((i - 1) % 60) + 1:03d}",\n')
            f.write(f'        "planned_api": "PLANNED-API-{((i - 1) % 50) + 1:03d}",\n')
            f.write(f'        "planned_db": "PLANNED-DB-{((i - 1) % 40) + 1:03d}",\n')
            f.write(f'        "planned_ui": "PLANNED-UI-{((i - 1) % 40) + 1:03d}",\n')
            f.write(f'        "planned_test": "PLANNED-TEST-{1500 + i:03d}",\n')
            f.write(f'        "related_requirements": ["CR-007", "CR-008", "SECR-043"],\n')
            f.write(f'        "conflicts": "None identified; strictly upholds clinician primacy over algorithmic suggestions.",\n')
            f.write(f'        "dependencies": ["CR-007"],\n')
            f.write(f'        "open_questions": "Validation of Kannada biomedical vocabulary by state clinical advisory panel.",\n')
            f.write(f'        "assumptions": "Medical Officers hold legal responsibility for all finalized patient prescriptions.",\n')
            f.write(f'        "constraints": "AI suggestions must NEVER make irreversible clinical or diagnostic decisions."\n')
            f.write("    },\n")
        f.write("]\n")

    # -------------------------------------------------------------------------
    # 5. data_int.py (50 items)
    # -------------------------------------------------------------------------
    with open(os.path.join(DIR_PATH, "data_int.py"), "w", encoding="utf-8") as f:
        f.write('#!/usr/bin/env python3\n"""data_int.py: 50 Integration Requirements (INT-001 to INT-050)"""\n\nINT_REQUIREMENTS = [\n')
        for i, item in enumerate(INT_ITEMS, 1):
            (req_id, title, system, protocol, payload, vmethod, owner) = item
            statement = f"The platform SHALL implement integration for {title.lower()} with {system} over {protocol}, transmitting {payload}."
            f.write("    {\n")
            f.write(f'        "id": "{req_id}",\n')
            f.write(f'        "title": "{title}",\n')
            f.write(f'        "statement": "{statement}",\n')
            f.write(f'        "domain": "External & Hardware Integration",\n')
            f.write(f'        "type": "Integration Requirement",\n')
            f.write(f'        "priority": "MUST",\n')
            f.write(f'        "priority_rationale": "Mandatory national healthcare interoperability (ABDM) and clinic hardware connectivity.",\n')
            f.write(f'        "business_value": "Enables seamless national digital health exchange and frictionless frontline clinical peripherals.",\n')
            f.write(f'        "rationale": "Target System: {system}; Protocol: {protocol}; Payload Specification: {payload}.",\n')
            f.write(f'        "external_system": "{system}",\n')
            f.write(f'        "integration_protocol": "{protocol}",\n')
            f.write(f'        "payload_standard": "{payload}",\n')
            f.write(f'        "verification_method": "{vmethod}",\n')
            f.write(f'        "owner": "{owner}",\n')
            f.write(f'        "actor": "Integration Gateway Adapter",\n')
            f.write(f'        "persona": "PERSONA-{((i - 1) % 35) + 1:03d}",\n')
            f.write(f'        "role": "ROLE-004",\n')
            f.write(f'        "stakeholder": "STAKEHOLDER-009",\n')
            f.write(f'        "trigger": "ABHA creation request, FHIR bundle push, peripheral scan, or scheduled telemetry dispatch.",\n')
            f.write(f'        "preconditions": "External gateway reachable or hardware device connected via USB/Bluetooth; valid credentials.",\n')
            f.write(f'        "inputs": "Patient identification, FHIR bundle, raw ESC/POS byte stream, or barcode scanner string.",\n')
            f.write(f'        "validation": "Evaluated against schema contracts, ABDM payload validators, or device handshake protocol.",\n')
            f.write(f'        "main_flow": [\n')
            f.write(f'            "Trigger initiates integration request: {title}.",\n')
            f.write(f'            "Integration gateway transforms internal entity into contract payload: {payload}.",\n')
            f.write(f'            "Transmits payload to destination system over: {protocol}.",\n')
            f.write(f'            "Validates response status, handles cryptographic handshake, and parses acknowledgment.",\n')
            f.write(f'            "Updates local transaction status and logs integration event to audit vault."\n')
            f.write(f'        ],\n')
            f.write(f'        "alternate_flow": "If external endpoint returns 503 or network drops, buffer payload in retry queue with backoff.",\n')
            f.write(f'        "exception_flow": "If external authentication fails repeatedly, trip circuit breaker and notify Integration Lead.",\n')
            f.write(f'        "postconditions": "Integration payload successfully transmitted and acknowledged by recipient system.",\n')
            f.write(f'        "state_changes": "Records outbound integration transmission status, correlation ID, and latency.",\n')
            f.write(f'        "business_rules": "BRULE-{((i - 1) % 50) + 1:03d}",\n')
            f.write(f'        "clinical_rules": "CR-{((i - 1) % 50) + 1:03d}",\n')
            f.write(f'        "operational_rules": "OR-{((i - 1) % 50) + 1:03d}",\n')
            f.write(f'        "security_implications": "All external API transmissions protected via TLS 1.3 mutual authentication.",\n')
            f.write(f'        "privacy_implications": "Patient records shared via ABDM require explicit DPDP / ABDM consent artifact.",\n')
            f.write(f'        "data_implications": "External schema transformations adhere to standard FHIR R4 resource definitions.",\n')
            f.write(f'        "audit_requirements": "Outbound payloads, timestamps, response codes, and hashes recorded in audit vault.",\n')
            f.write(f'        "offline_behavior": "Integration requests spooled in IndexedDB queue and dispatched automatically upon reconnection.",\n')
            f.write(f'        "synchronization_implications": "Hardware peripheral inputs (barcode, serial) function 100% autonomously offline.",\n')
            f.write(f'        "integration_implications": "Direct hardware interface utilizes Web Serial API and USB HID emulation.",\n')
            f.write(f'        "performance_expectations": "Peripheral barcode scan decoded and populated in UI in < 50ms.",\n')
            f.write(f'        "availability_expectations": "99.5% availability for internal integration gateways and queues.",\n')
            f.write(f'        "localization_expectations": "SMS and WhatsApp notification templates fully localized in Kannada and English.",\n')
            f.write(f'        "accessibility_expectations": "Hardware error alerts (e.g. printer offline) provide accessible screen reader toasts.",\n')
            f.write(f'        "failure_behavior": "Spool failed payloads to dead letter queue without halting frontline clinical screens.",\n')
            f.write(f'        "recovery_behavior": "Automatic retry with exponential backoff and idempotency protection.",\n')
            f.write(f'        "observability_requirements": "OpenTelemetry span `namma.clinic.int.{req_id.lower()}`.",\n')
            f.write(f'        "logging_requirements": "Structured JSON log with correlation_id, external_endpoint, and status_code.",\n')
            f.write(f'        "metrics": "Prometheus counter `namma_clinic_integration_requests_total{{target=\\"{system[:15]}\\"}}`.",\n')
            f.write(f'        "acceptance_criteria": [\n')
            f.write(f'            "System enforces {title.lower()}.",\n')
            f.write(f'            "Integrates with system: {system}.",\n')
            f.write(f'            "Communicates via protocol: {protocol}.",\n')
            f.write(f'            "Payload conforms to: {payload}.",\n')
            f.write(f'            "Verified via: {vmethod}."\n')
            f.write(f'        ],\n')
            f.write(f'        "test_type": "Automated Gateway Contract & Hardware Simulation Test",\n')
            f.write(f'        "test_id": "PLANNED-TEST-{1600 + i:03d}",\n')
            f.write(f'        "objective_ref": "OBJECTIVE-{((i - 1) % 40) + 1:03d}",\n')
            f.write(f'        "scope_ref": "INSCOPE-{((i - 1) % 80) + 1:03d}",\n')
            f.write(f'        "stakeholder_ref": "STAKEHOLDER-009",\n')
            f.write(f'        "persona_ref": "PERSONA-{((i - 1) % 35) + 1:03d}",\n')
            f.write(f'        "risk_ref": "RISK-{((i - 1) % 60) + 1:03d}",\n')
            f.write(f'        "dependency_ref": "DEPENDENCY-{((i - 1) % 50) + 1:03d}",\n')
            f.write(f'        "milestone_ref": "MILESTONE-{((i - 1) % 40) + 1:03d}",\n')
            f.write(f'        "release_ref": "RELEASE-{((i - 1) % 20) + 1:03d}",\n')
            f.write(f'        "planned_epic": "PLANNED-EPIC-{((i - 1) % 30) + 1:03d}",\n')
            f.write(f'        "planned_feature": "PLANNED-FEATURE-{((i - 1) % 60) + 1:03d}",\n')
            f.write(f'        "planned_api": "PLANNED-API-{((i - 1) % 50) + 1:03d}",\n')
            f.write(f'        "planned_db": "PLANNED-DB-{((i - 1) % 40) + 1:03d}",\n')
            f.write(f'        "planned_ui": "PLANNED-UI-{((i - 1) % 40) + 1:03d}",\n')
            f.write(f'        "planned_test": "PLANNED-TEST-{1600 + i:03d}",\n')
            f.write(f'        "related_requirements": ["FR-006", "NFR-014", "SECR-001"],\n')
            f.write(f'        "conflicts": "None identified; respects external ABDM and hardware standards.",\n')
            f.write(f'        "dependencies": ["FR-006"],\n')
            f.write(f'        "open_questions": "NHA Sandbox certification window scheduling for ABDM M2/M3 profiles.",\n')
            f.write(f'        "assumptions": "Clinic workstations support Web Serial API in Chromium for thermal printer access.",\n')
            f.write(f'        "constraints": "External API latency must not block local clinic UI responsiveness."\n')
            f.write("    },\n")
        f.write("]\n")

    print("Created data_off.py, data_rep.py, data_anl.py, data_air.py, data_int.py successfully.")

if __name__ == "__main__":
    build_data_files()
