#!/usr/bin/env python3
"""
build_defs_13_17.py
Item definitions for documents 13 to 17:
  - OFF_ITEMS: 50 offline items (OFF-001 to OFF-050)
  - REP_ITEMS: 50 reporting items (REP-001 to REP-050)
  - ANL_ITEMS: 40 analytics items (ANL-001 to ANL-040)
  - AIR_ITEMS: 40 AI/decision-support items (AIR-001 to AIR-040)
  - INT_ITEMS: 50 integration items (INT-001 to INT-050)
"""

# -------------------------------------------------------------------------
# OFF_ITEMS: 50 Offline Autonomy & Sync Items (OFF-001 to OFF-050)
# (id, title, state, store_schema, conflict_strategy, vmethod, owner)
# -------------------------------------------------------------------------
OFF_ITEMS = [
    ("OFF-001", "Network Online to Offline State Transition Detection", "Offline Transition", "system_state (key, status, timestamp)", "Client Event Listeners (navigator.onLine + Heartbeat)", "Network Simulation Test", "Mobile/Offline Lead"),
    ("OFF-002", "Dexie.js IndexedDB Schema Initialization and Versioning", "Offline Storage", "schema_migrations (version, applied_at)", "Deterministic Schema Upgrades with Dexie.version", "Storage Migration Test", "Database Engineer"),
    ("OFF-003", "Client Mutation Queue FIFO Persistence", "Mutation Queue", "mutation_queue (id, entity, op, payload, status)", "FIFO Queue with Priority Precedence", "Queue Persistence Verification", "Frontend Tech Lead"),
    ("OFF-004", "UUID v7 Client-Side Primary Key Generation", "Local Identity", "all_tables (id: uuid_v7, created_at)", "Monotonic Time-Ordered UUIDv7 Collision Free", "ID Collision Chaos Test", "Solution Architect"),
    ("OFF-005", "Idempotency Key Injection for Offline Writes", "Write Pipeline", "mutation_queue (idempotency_key: hash, attempts)", "Server-Side Token Deduplication Cache", "Idempotency Replay Test", "Backend Tech Lead"),
    ("OFF-006", "Priority Queuing for Clinical vs Administrative Mutations", "Queue Management", "mutation_queue (priority: HIGH|MED|LOW)", "Strict Clinical Precedence Dispatch", "Priority Inversion Test", "Frontend Tech Lead"),
    ("OFF-007", "Exponential Backoff and Jitter Reconnection Protocol", "Reconnection", "sync_telemetry (retry_count, next_retry_at)", "Exponential Backoff (2s to 60s) with Full Jitter", "Network Jitter Chaos Test", "SRE Lead"),
    ("OFF-008", "Three-Way Merge Engine for Clinical Consultations", "Conflict Resolution", "conflict_log (entity_id, client_v, server_v)", "Field-Level Merging with Clinician Authority", "Concurrent Conflict Test", "Clinical Reviewer"),
    ("OFF-009", "Last-Write-Wins Resolution for Administrative Metadata", "Conflict Resolution", "admin_metadata (key, val, updated_at)", "Server Timestamp Last-Write-Wins (LWW)", "Timestamp Skew Test", "Solution Architect"),
    ("OFF-010", "Deterministic Deduplication of Offline Patient Registrations", "Deduplication", "patients (abha_id, phone, name, dob_hash)", "Fuzzy Phone + Name Match with Supervisor Alert", "Duplicate Injection Test", "Data Engineer"),
    ("OFF-011", "Partial Sync and Chunked Batch Processing", "Sync Pipeline", "sync_batches (batch_id, chunk_index, total_chunks)", "50-Record Micro-Batches with Partial Commit", "Packet Loss Chunk Test", "Backend Tech Lead"),
    ("OFF-012", "Sync Failure Quarantine and Manual Review Escalation", "Failure Handling", "sync_quarantine (id, mutation_id, error_reason)", "Quarantine Isolation with Supervisor Dashboard", "Dead Letter Queue Test", "Frontend Tech Lead"),
    ("OFF-013", "Delta Synchronization and Incremental Cache Hydration", "Sync Pipeline", "sync_cursors (entity, last_sync_timestamp)", "High-Watermark Delta Sync via Timestamp Cursors", "Delta Sync Verification", "Backend Tech Lead"),
    ("OFF-014", "Web Cryptography Client Storage AES-GCM Encryption", "Data Security", "secure_vault (salt, iv, ciphertext)", "SubtleCrypto AES-256-GCM Session Key Derivation", "Cryptographic Leak Audit", "Security Lead"),
    ("OFF-015", "Offline Workstation Session Timeout and Re-Authentication", "Session Security", "offline_auth (user_hash, salt, expires_at)", "Argon2id Hash Verification Against Local Salt", "Offline Session Security Test", "Security Lead"),
    ("OFF-016", "Emergency PIN Fallback for Offline Clinician Login", "Emergency Access", "emergency_creds (role, hashed_pin, authorized_by)", "Supervisor-Delegated 6-Digit Rotating PIN", "Emergency PIN Access Test", "Security Lead"),
    ("OFF-017", "Workstation Replacement and Local Database Eviction", "Device Lifecycle", "device_binding (device_id, clinic_id, status)", "Cryptographic Wipe on Device De-Registration", "Device Retirement Audit", "SRE Lead"),
    ("OFF-018", "Storage Quota Monitoring and Eviction Defense", "Storage Management", "storage_telemetry (used_bytes, quota_bytes)", "navigator.storage.persist() Lockout Defense", "Storage Exhaustion Test", "Frontend Tech Lead"),
    ("OFF-019", "Multi-Tab Synchronization via BroadcastChannel API", "Browser Concurrency", "active_tabs (tab_id, last_heartbeat)", "BroadcastChannel Real-Time Cross-Tab State Sync", "Multi-Tab Race Condition Test", "Frontend Tech Lead"),
    ("OFF-020", "Offline Thermal Printer Queue and ESC/POS Spooling", "Hardware Queue", "print_spool (job_id, raw_bytes, status)", "IndexedDB ESC/POS Byte Buffer Spooler", "Printer Disconnection Test", "Hardware Integration Lead"),
    ("OFF-021", "Offline Doctor Consultation Note Autosave", "Clinical Care", "draft_consultations (patient_id, draft_soap)", "Debounced 500ms Local Autosave to Dexie.js", "Browser Crash Recovery Test", "Medical Officer"),
    ("OFF-022", "Offline Prescription Issuance and Stock Reservation", "Pharmacy", "draft_prescriptions (rx_id, drug_id, qty)", "Optimistic Local Stock Decrement with Reconciler", "Offline Stock Overdraw Test", "Pharmacist"),
    ("OFF-023", "Offline Point-of-Care Lab Order Generation", "Laboratory", "draft_lab_orders (order_id, test_id, sample_id)", "Deterministic Specimen Barcode Pre-Allocation", "Specimen Barcode Audit", "Lab Technician"),
    ("OFF-024", "Offline OPD Queue Token Generation and Sequencing", "Registration", "local_tokens (token_num, patient_id, clinic_date)", "Pre-Allocated Clinic Daily Token Range", "Token Sequence Integrity Test", "Registration Clerk"),
    ("OFF-025", "Offline Triage Vital Signs Recording and Scoring", "Triage", "triage_vitals (patient_id, sbp, dbp, spo2, acuity)", "Local MEWS / Urgency Score Calculator", "Acuity Scoring Accuracy Test", "Staff Nurse"),
    ("OFF-026", "Offline Essential Drug List (EDL) Formulary Cache", "Formulary", "cached_edl (drug_code, generic_name, dosage_form)", "Read-Only 120 EDL Master Cache in IndexedDB", "Cache Invalidation Test", "Pharmacist"),
    ("OFF-027", "Offline ICD-11 Common Symptom Code Search Index", "Diagnostics", "cached_icd11 (code, title, search_trie)", "Client-Side In-Memory Trie Search (<50ms)", "Diagnostic Search Speed Test", "Medical Officer"),
    ("OFF-028", "Offline Maternal Care ANC Visit Scheduling", "Maternal Care", "anc_schedule (mother_id, edd, visit_num, due_date)", "Local Rule-Based ANC Visit Calculator", "ANC Schedule Accuracy Test", "Staff Nurse"),
    ("OFF-029", "Offline Child Immunization Schedule Calculation", "Immunization", "immunization_tracker (child_id, vaccine_id, due_date)", "National Immunization Schedule Calculation Engine", "Vaccine Due Date Test", "Staff Nurse"),
    ("OFF-030", "Offline NCD Patient Risk Scoring and Screening", "NCD Screening", "ncd_screenings (patient_id, cbac_score, risk_tier)", "Automated CBAC Risk Assessment Matrix", "NCD Risk Tiering Test", "Staff Nurse"),
    ("OFF-031", "Offline Lab Test Reference Range Validator", "Laboratory", "lab_reference (test_code, min_val, max_val, unit)", "Local Normal Range Evaluation Engine", "Abnormal Lab Flag Test", "Lab Technician"),
    ("OFF-032", "Offline Medicine Expiry Warning Engine", "Pharmacy", "batch_inventory (batch_num, drug_id, exp_date)", "Client-Side 30/60/90 Day Expiry Alert Engine", "Expiry Warning Accuracy Test", "Pharmacist"),
    ("OFF-033", "Offline Cold Chain Temperature Anomaly Logging", "Cold Chain", "temp_logs (fridge_id, recorded_at, temp_c)", "Local Out-of-Range (<2C or >8C) Audio/Visual Alert", "Cold Chain Breach Test", "Pharmacist"),
    ("OFF-034", "Offline Biomedical Waste Bag Barcode Dispatch", "Operations", "waste_dispatches (bag_barcode, category, weight)", "Local Waste Log Persistence with USB Scale Input", "Waste Barcode Dispatch Test", "Administrative Assistant"),
    ("OFF-035", "Offline Supervisor Audit Trail Buffering", "Audit Vault", "offline_audit (event_id, actor, event_type, hmac)", "HMAC-SHA256 Chained Immutable Local Event Log", "Audit Tamper Detection Test", "Security Lead"),
    ("OFF-036", "Background Sync via Service Worker SyncManager", "Background Sync", "sync_registrations (tag, registered_at)", "Periodic and Event-Driven SyncManager Triggers", "Service Worker Lifecycle Test", "Frontend Tech Lead"),
    ("OFF-037", "Bandwidth-Adaptive Payload Compression for Sync", "Network Adaptation", "sync_compression (algo: gzip|brotli, ratio)", "Dynamic Gzip Compression on 2G/3G Cellular Dongles", "Bandwidth Throttling Test", "Backend Tech Lead"),
    ("OFF-038", "Sync Progress Visual Indicator and Status Bar", "User Experience", "sync_ui_state (pending_count, sync_status)", "Real-Time Sync Status Badge (Synced, Syncing, Offline)", "UI State Reactivity Test", "Frontend Tech Lead"),
    ("OFF-039", "Manual Force-Sync Trigger with Admin Override", "Sync Control", "force_sync_events (triggered_by, trigger_time)", "Instant Mutation Dispatch Trigger with Debounce", "Manual Trigger Stress Test", "Frontend Tech Lead"),
    ("OFF-040", "Differential Change Data Capture (CDC) Sync Protocol", "Database Sync", "server_cdc (tx_id, entity, row_id, diff_json)", "Server-Side JSON Patch Dispatch to Client Stores", "CDC Patch Application Test", "Database Engineer"),
    ("OFF-041", "Client-Side Cache Warmup Protocol on First Login", "Initialization", "warmup_manifest (table_name, total_records)", "Chunked Initial Download of Clinic Master Data", "Fresh Workstation Bootstrap Test", "Frontend Tech Lead"),
    ("OFF-042", "Offline Patient Demographics Search via Inverted Index", "Patient Search", "patient_search_index (token, patient_id_set)", "Prefix-Trie Token Search Across 5,000 Clinic Patients", "Local Search Speed Test", "Frontend Tech Lead"),
    ("OFF-043", "Patient Photo Compression and Offline Storage", "Demographics", "patient_photos (patient_id, webp_thumbnail)", "Client-Side WebP Canvas Resizing to <30KB", "Photo Compression Ratio Test", "Frontend Tech Lead"),
    ("OFF-044", "Offline Document and Prescription Template Caching", "Templates", "document_templates (template_id, html_layout)", "Pre-Cached Mustache/Handlebars Printable Templates", "Template Rendering Offline Test", "Frontend Tech Lead"),
    ("OFF-045", "Battery-Aware Sync Throttling on Workstation Laptop", "Hardware Awareness", "battery_telemetry (level, charging, throttle_mode)", "navigator.getBattery() Low-Power Sync Throttling", "Battery Drain Simulation Test", "Mobile/Offline Lead"),
    ("OFF-046", "Graceful Degradation During IndexedDB Quota Warnings", "Storage Management", "quota_warnings (timestamp, percentage_used)", "Eviction of Stale Read Caches while Preserving Queue", "Quota Pressure Recovery Test", "Frontend Tech Lead"),
    ("OFF-047", "Workstation Clock Drift Detection and Compensation", "Time Integrity", "clock_offset (client_time, server_time, drift_ms)", "NTP / Server-Header Drift Calculation (<1000ms)", "Clock Drift Skew Test", "Solution Architect"),
    ("OFF-048", "End-of-Day Offline Reconciliation Report Generation", "Daily Closing", "eod_reconciliation (date, pending_mutations, status)", "Local Daily Tally of Tokens, Prescriptions, Lab Tests", "EOD Reconciliation Audit Test", "Administrative Assistant"),
    ("OFF-049", "Offline Emergency Patient Triage Override Bypass", "Emergency Care", "emergency_overrides (patient_id, override_code)", "Immediate Unverified Token Allocation for Critical Patients", "Emergency Bypass Stress Test", "Staff Nurse"),
    ("OFF-050", "Disaster Recovery Workstation Sync State Dump and Restore", "Disaster Recovery", "sync_state_dump (clinic_id, dump_json, checksum)", "Encrypted USB JSON Export of Pending Mutation Queue", "Disaster USB Recovery Test", "SRE Lead"),
]

# -------------------------------------------------------------------------
# REP_ITEMS: 50 Reporting Requirements Items (REP-001 to REP-050)
# (id, title, frequency, audience, data_sources, formats, owner)
# -------------------------------------------------------------------------
REP_ITEMS = [
    ("REP-001", "Daily OPD Registration and Patient Footfall Census", "Daily (End-of-Day)", "Clinic Supervisor & MO", "patients, opd_tokens, triage_vitals", "PDF, CSV, On-Screen", "Registration Clerk"),
    ("REP-002", "OPD Token Turnaround Time and Patient Wait Times", "Daily & Monthly", "Medical Officer & BBMP Health Directorate", "opd_tokens, consultation_records", "PDF, CSV, On-Screen", "Administrative Assistant"),
    ("REP-003", "Triage Acuity Distribution and Emergency Escalation Log", "Daily", "Staff Nurse & Medical Officer", "triage_vitals, clinical_escalations", "PDF, CSV", "Staff Nurse"),
    ("REP-004", "Doctor Consultation Workload and Daily Throughput", "Daily & Weekly", "Chief Medical Officer & BBMP Health Officer", "consultation_records, doctor_roster", "PDF, CSV", "Medical Officer"),
    ("REP-005", "Prescription Pattern and Rational Drug Use Adherence", "Monthly", "Medical Officer & State Formulary Board", "prescriptions, edl_formulary", "PDF, CSV", "Pharmacist"),
    ("REP-006", "120 Essential Drug List (EDL) Daily Consumption Ledger", "Daily (Automated 17:00)", "Pharmacist & Central Medical Stores", "stock_dispensations, edl_inventory", "PDF, CSV, Excel", "Pharmacist"),
    ("REP-007", "Stockout and Critical Buffer Depletion Alert Report", "Real-Time / Daily", "Pharmacist & District Health Officer", "inventory_balances, buffer_thresholds", "PDF, CSV, SMS Alert", "Pharmacist"),
    ("REP-008", "Medicine Batch Expiry Trajectory (30, 60, 90 Days)", "Weekly", "Pharmacist & Warehouse Manager", "batch_inventory, procurement_orders", "PDF, CSV", "Pharmacist"),
    ("REP-009", "Pharmacy Stock Adjustment and Discrepancy Reconciliation", "Monthly", "Auditor & Clinic In-Charge MO", "stock_adjustments, physical_audit_logs", "PDF, CSV", "Pharmacist"),
    ("REP-010", "Point-of-Care Lab Diagnostic Test Order Volume", "Daily & Monthly", "Lab Technician & Pathologist", "lab_orders, diagnostic_catalog", "PDF, CSV", "Lab Technician"),
    ("REP-011", "Critical Abnormal Lab Value Escalation and Turnaround Log", "Daily", "Medical Officer & Lab Technician", "lab_results, critical_alerts", "PDF, CSV", "Lab Technician"),
    ("REP-012", "Diagnostic Reagent Consumption and Wastage Ledger", "Weekly", "Lab Technician & Central Procurement", "reagent_stocks, lab_orders", "PDF, CSV", "Lab Technician"),
    ("REP-013", "Specialist Referral Outward Dispatch and Destination Roster", "Weekly & Monthly", "Medical Officer & Secondary Hospital Liaison", "referrals, referral_facilities", "PDF, CSV", "Medical Officer"),
    ("REP-014", "Referral Closure Rate and Patient Feedback Summary", "Monthly", "BBMP Health Directorate", "referrals, referral_feedback", "PDF, CSV", "Administrative Assistant"),
    ("REP-015", "High-Risk Antenatal Care (ANC) Tracking Register", "Weekly", "Staff Nurse & RCH Officer", "anc_registrations, maternal_risk_logs", "PDF, CSV", "Staff Nurse"),
    ("REP-016", "Childhood Immunization Coverage and Dropout Defaulter List", "Monthly", "Staff Nurse & Urban Immunization Officer", "immunization_records, defaulter_tracking", "PDF, CSV", "Staff Nurse"),
    ("REP-017", "Hypertension Screening and Longitudinal Care Continuum", "Monthly", "Medical Officer & NCD Program Officer", "ncd_screenings, blood_pressure_logs", "PDF, CSV", "Staff Nurse"),
    ("REP-018", "Type 2 Diabetes Glycemic Control and Follow-Up Register", "Monthly", "Medical Officer & NCD Program Officer", "ncd_screenings, glucose_logs, prescriptions", "PDF, CSV", "Staff Nurse"),
    ("REP-019", "Chronic Kidney Disease (CKD) Urine Protein Screening Census", "Quarterly", "NCD Specialist & State Epidemiologist", "lab_results, ncd_screenings", "PDF, CSV", "Medical Officer"),
    ("REP-020", "Integrated Disease Surveillance Programme (IHIP Form P Daily)", "Daily (Automated 18:00)", "District Surveillance Officer & NCDC", "consultation_records, icd11_diagnoses", "CSV, XML, JSON", "Epidemiologist"),
    ("REP-021", "Acute Diarrheal Disease (ADD) Spatial Cluster Alert Report", "Real-Time / Daily", "BBMP Chief Health Officer & Water Board", "consultation_records, patient_addresses", "PDF, CSV, GIS Map", "Epidemiologist"),
    ("REP-022", "Acute Respiratory Infection (ARI) and Influenza-Like Illness Log", "Daily", "District Surveillance Officer", "consultation_records, triage_vitals", "PDF, CSV", "Epidemiologist"),
    ("REP-023", "Animal Bite and Anti-Rabies Vaccine (ARV) Regimen Tracker", "Weekly", "Public Health Inspector & State Epidemiologist", "bite_registrations, arv_dispensations", "PDF, CSV", "Pharmacist"),
    ("REP-024", "Adverse Events Following Immunization (AEFI) Rapid Report", "Immediate (<2 Hours)", "State AEFI Committee & WHO Liaison", "aefi_reports, vaccine_batches", "PDF, Secure Email", "Medical Officer"),
    ("REP-025", "Clinic Staff Attendance and Shift Roster Adherence Log", "Monthly", "Clinic In-Charge MO & BBMP Admin", "staff_attendance, roster_schedules", "PDF, CSV", "Administrative Assistant"),
    ("REP-026", "Clinic Operating Hours and Service Continuity Audit", "Monthly", "BBMP Vigilance Directorate", "audit_events, system_start_stop_logs", "PDF, CSV", "SRE Lead"),
    ("REP-027", "Patient Queue Waiting Time Distribution by Ward Percentile", "Monthly", "Urban Health Planning Directorate", "opd_tokens, clinic_demographics", "PDF, CSV", "Data Analyst"),
    ("REP-028", "Vaccine Cold Chain Temperature Excursion Log (ILR/Freezer)", "Weekly", "Cold Chain Handler & Logistics Officer", "cold_chain_sensors, manual_temp_logs", "PDF, CSV", "Pharmacist"),
    ("REP-029", "Biomedical Waste Category-Wise Daily Disposal Log", "Daily & Monthly", "Pollution Control Board & Health Officer", "waste_dispatches, barcode_scans", "PDF, CSV", "Administrative Assistant"),
    ("REP-030", "Patient Satisfaction and Citizen Grievance Census", "Monthly", "Quality Assurance Cell & Municipal Commissioner", "patient_feedback, grievance_tickets", "PDF, CSV", "Administrative Assistant"),
    ("REP-031", "Teleconsultation Case Roster and Specialist Recommendation Log", "Weekly", "Medical Officer & e-Sanjeevani Coordinator", "teleconsultations, specialist_notes", "PDF, CSV", "Medical Officer"),
    ("REP-032", "e-Manas Community Mental Health Screening and Referral Census", "Monthly", "State Mental Health Authority", "mental_health_screenings, referrals", "PDF, CSV", "Medical Officer"),
    ("REP-033", "Janani Suraksha Yojana (JSY) Institutional Incentive Register", "Monthly", "RCH Program Officer & Accounts Lead", "anc_registrations, bank_account_hashes", "PDF, CSV", "Staff Nurse"),
    ("REP-034", "Monthly Municipal Health Department Form M Aggregated Report", "Monthly (3rd of Month)", "BBMP Health Directorate & NHM Directorate", "opd_census, disease_mortality, stock_summary", "PDF, CSV, Excel", "Medical Officer"),
    ("REP-035", "Ward-Level Primary Healthcare Equity and Vulnerability Index", "Quarterly", "Municipal Commissioner & Urban Planners", "patient_footfall, ward_demographics", "PDF, CSV, GIS Layer", "Data Analyst"),
    ("REP-036", "Clinic Consumables and Diagnostic Kits Utilization Report", "Monthly", "Central Stores & Clinic In-Charge", "consumable_stocks, lab_orders", "PDF, CSV", "Lab Technician"),
    ("REP-037", "Emergency Life-Saving Drug Stockout Immediate Escalation", "Real-Time", "Zonal Health Officer & Central Drug Depot", "stock_balances, emergency_formulary", "PDF, SMS, Email", "Pharmacist"),
    ("REP-038", "Offline Mutation Queue Sync Latency and Backlog Audit", "Daily", "SRE Lead & IT Directorate", "mutation_queue, sync_telemetry", "PDF, CSV", "SRE Lead"),
    ("REP-039", "System User Access Audit and Privileged Role Action Log", "Monthly", "Information Security Officer (CISO)", "audit_vault, user_sessions", "PDF, Encrypted CSV", "Security Lead"),
    ("REP-040", "Security Incident, Failed Login, and Threat Block Report", "Weekly", "CERT-In Coordinator & CISO", "security_events, firewall_logs", "PDF, Encrypted CSV", "Security Lead"),
    ("REP-041", "DPDP Act Patient Consent Revocation and Erasure Audit", "Monthly", "Data Protection Officer (DPO)", "consent_audit_vault, erasure_tickets", "PDF, Encrypted CSV", "Privacy Lead / DPO"),
    ("REP-042", "Pharmacy Dispensation vs Doctor Prescription Variance Audit", "Monthly", "Drug Inspector & Medical Officer", "prescriptions, dispensations", "PDF, CSV", "Pharmacist"),
    ("REP-043", "Tuberculosis Presumptive Case Referral and Nikshay Sync Report", "Weekly", "District TB Officer (DTO)", "tb_screenings, nikshay_sync_logs", "PDF, CSV", "Staff Nurse"),
    ("REP-044", "Dengue and Chikungunya Vector-Borne Serology Log", "Weekly", "Vector-Borne Disease Control Officer", "lab_orders, serology_results", "PDF, CSV", "Lab Technician"),
    ("REP-045", "Oral, Cervical, and Breast Cancer Early Detection Census", "Monthly", "Non-Communicable Disease Cell", "cancer_screenings, biopsy_referrals", "PDF, CSV", "Staff Nurse"),
    ("REP-046", "Geriatric Vulnerability and Bedridden Patient Home Care Log", "Monthly", "Elderly Welfare Directorate", "geriatric_assessments, asha_home_visits", "PDF, CSV", "Staff Nurse"),
    ("REP-047", "Community-Based Assessment Checklist (CBAC) Ward Census", "Monthly", "ASHA Coordinator & Staff Nurse", "cbac_forms, ncd_risk_scores", "PDF, CSV", "Staff Nurse"),
    ("REP-048", "BBMP Health Commissioner Executive Key Indicator Summary", "Weekly (Monday 08:00)", "Municipal Health Commissioner", "kpi_snapshots, municipal_totals", "PDF, Executive One-Pager", "Solution Architect"),
    ("REP-049", "De-Identified Public Health Research Open Data Extract", "Monthly", "Public Health Researchers & ICMR", "deidentified_consultations (k>=5)", "CSV, JSON, Parquet", "Data Protection Officer"),
    ("REP-050", "Comprehensive Annual Health Platform Operations Audit", "Annual", "State Health Department & Comptroller", "annual_aggregate_tables, fiscal_ledgers", "PDF Bound Report, CSV", "Project Director"),
]

# -------------------------------------------------------------------------
# ANL_ITEMS: 40 Analytics & Data Platform Items (ANL-001 to ANL-040)
# (id, title, dimension, cadence, duckdb_target, vmethod, owner)
# -------------------------------------------------------------------------
ANL_ITEMS = [
    ("ANL-001", "OLTP and OLAP Architectural Decoupling Pipeline", "System Architecture", "Continuous CDC", "DuckDB Replicated Analytical Store", "Data Pipeline Integrity Test", "Data Platform Lead"),
    ("ANL-002", "Embedded DuckDB Local Clinic Analytics Execution Engine", "Local Analytical Mart", "Sub-Second Query", "Local clinic_mart.duckdb File", "Local Query Benchmark", "Data Platform Lead"),
    ("ANL-003", "Daily Change Data Capture (CDC) Pipeline to Cloud Warehouse", "Data Ingestion", "Daily Delta Batch", "Cloud Analytical Lakehouse Parquet Tables", "CDC Sync Completeness Test", "Data Engineer"),
    ("ANL-004", "Star Schema Dimensional Data Model Conformance", "Dimensional Modeling", "Static Architecture", "Dim_Date, Dim_Clinic, Dim_Doctor, Dim_Patient", "Schema Validation Test", "Data Architect"),
    ("ANL-005", "Fact Table Fact_Consultation Granular Event Storage", "Fact Engine", "Real-Time / Micro-Batch", "Fact_Consultation (patient_key, doctor_key, cost)", "Fact Consistency Audit", "Data Architect"),
    ("ANL-006", "Fact Table Fact_Dispensation Pharmacy Analytics Ledger", "Fact Engine", "Batch Hourly", "Fact_Dispensation (drug_key, qty, cost, stockout)", "Dispensation Aggregation Test", "Data Architect"),
    ("ANL-007", "Fact Table Fact_LabOrder Diagnostic Throughput Metrics", "Fact Engine", "Batch Hourly", "Fact_LabOrder (test_key, turnaround_sec, abnormal)", "Diagnostic Fact Audit", "Data Architect"),
    ("ANL-008", "Fact Table Fact_Triage Vital Signs and Acuity Trends", "Fact Engine", "Batch Hourly", "Fact_Triage (acuity_key, sbp, dbp, spo2, wait_sec)", "Triage Metric Test", "Data Architect"),
    ("ANL-009", "Clinic Operational Efficiency and Patient Throughput KPI", "Operational KPI", "Daily Snapshot", "Agg_Clinic_Daily_Throughput Table", "KPI Accuracy Test", "Data Analyst"),
    ("ANL-010", "Doctor Consultation Duration Distribution Modeling", "Workload Analytics", "Weekly Aggregation", "Histogram_Consultation_Durations View", "Distribution Curve Validation", "Data Analyst"),
    ("ANL-011", "120 Essential Drug Velocity and Depletion Curve Modeling", "Pharmacy Analytics", "Daily Aggregation", "Model_Drug_Consumption_Velocity Table", "Consumption Forecasting Test", "Data Scientist"),
    ("ANL-012", "Stockout Probability Scoring for Primary Care Drugs", "Predictive Analytics", "Weekly Scoring", "Score_Stockout_Risk (drug_id, p_stockout_7d)", "Stockout Prediction Accuracy Test", "Data Scientist"),
    ("ANL-013", "Spatial GIS Clustering of Fever and Syndromic Symptoms", "Epidemiology", "Daily Geocoding", "Spatial_Fever_Clusters (ward_id, lat, lon, cases)", "Spatial Clustering Cluster Test", "GIS / Epidemiologist"),
    ("ANL-014", "Dengue and Waterborne Outbreak Early Warning Indices", "Surveillance", "Daily Calculation", "Index_Outbreak_Early_Warning (ward, risk_level)", "Outbreak Sensitivity Test", "Epidemiologist"),
    ("ANL-015", "Maternal Care Antenatal Dropout and Missed Visit Leakage", "Maternal Analytics", "Weekly Cohort", "Cohort_ANC_Retention_Funnel Table", "Funnel Conversion Test", "Data Analyst"),
    ("ANL-016", "High-Risk Pregnancy Clustering by Socio-Economic Ward", "Maternal Analytics", "Monthly Spatial", "Map_HighRisk_Pregnancies View", "Maternal Cluster Audit", "Epidemiologist"),
    ("ANL-017", "Hypertension Control Cohort Progression Analytics", "NCD Analytics", "Monthly Cohort", "Cohort_Hypertension_Control_Rate Table", "Clinical Cohort Progression Test", "Data Analyst"),
    ("ANL-018", "Type 2 Diabetes HbA1c and Fasting Glucose Trajectory", "NCD Analytics", "Quarterly Cohort", "Trajectory_Diabetes_Glycemic_Control Table", "Glycemic Trend Validation", "Data Analyst"),
    ("ANL-019", "Prescription Polypharmacy and High-Risk Drug Combination", "Clinical Safety", "Monthly Audit", "Audit_Polypharmacy_Events (patient_id, count)", "Polypharmacy Identification Test", "Clinical Data Lead"),
    ("ANL-020", "Antibiotic Prescription Proportion Adherence Analytics", "Antimicrobial Resistance", "Monthly AWaRe Audit", "AWaRe_Antibiotic_Proportions (Access, Watch)", "AMR Compliance Metric Test", "Clinical Data Lead"),
    ("ANL-021", "Referral Completion and Specialist Loop Closure Funnel", "Care Continuity", "Monthly Funnel", "Funnel_Referral_Completion (sent, reached, closed)", "Referral Leakage Audit", "Data Analyst"),
    ("ANL-022", "Patient Retention and Longitudinal Visit Cadence Modeling", "Patient Analytics", "Quarterly RFM", "Model_Patient_Care_Cadence (retention_rate)", "Retention Curve Validation", "Data Analyst"),
    ("ANL-023", "Point-of-Care Laboratory Abnormal Test Result Prevalence", "Diagnostic Analytics", "Weekly Prevalence", "Prevalence_Abnormal_Labs (test_id, pct_abnormal)", "Lab Distribution Metric Test", "Data Analyst"),
    ("ANL-024", "Clinic Equipment Downtime and Maintenance Analytics", "Asset Management", "Monthly Aggregate", "Log_Equipment_Reliability (device_type, mttr_hr)", "Equipment MTTR Metric Test", "Operations Analyst"),
    ("ANL-025", "Cold Chain Refrigerator Mean Kinetic Temperature (MKT)", "Cold Chain Analytics", "Monthly MKT Calculation", "Metric_ColdChain_MKT (fridge_id, mkt_celsius)", "MKT Formula Verification Test", "Data Engineer"),
    ("ANL-026", "Analytical Query Response Time SLA (<1.5s on DuckDB)", "SLA & Performance", "Per Query Benchmark", "DuckDB Analytical Benchmark Suite", "Analytical Query Stress Test", "Data Platform Lead"),
    ("ANL-027", "Data Freshness Latency Bounds (<2 Hours for Ingestion)", "Data Quality SLA", "Continuous Monitor", "Monitor_Data_Freshness (source_lag_seconds)", "Freshness Latency Alert Test", "Data Engineer"),
    ("ANL-028", "Automated Data Lineage and Metadata Provenance Graph", "Governance", "CI/CD Deployment", "OpenLineage / DataHub Metadata Registry", "Lineage Graph Integrity Test", "Data Architect"),
    ("ANL-029", "Automated Anomaly Detection in Daily OPD Census Metrics", "Quality Assurance", "Daily Evaluation", "Alert_Census_Anomalies (clinic_id, z_score)", "Census Anomaly Injection Test", "Data Scientist"),
    ("ANL-030", "Null Value and Foreign Key Referential Quality Scoring", "Data Quality", "Daily Pipeline Gate", "Score_Data_Quality (table_name, dq_score_pct)", "Data Quality Gate Test", "Data Engineer"),
    ("ANL-031", "Differential Privacy (k>=5) for Analytical Aggregations", "Privacy Engineering", "Query Runtime", "Engine_k_Anonymity (min_cohort_size=5)", "Re-Identification Resistance Test", "Privacy Lead / DPO"),
    ("ANL-032", "Role-Based Analytical Access Control and Data Masking", "Security & Governance", "Query Runtime", "RBAC_Column_Masking_Policy (role, pii_mask)", "Analytical Access Control Test", "Security Lead"),
    ("ANL-033", "Automated Daily Snapshot Partitioning and Parquet Compaction", "Storage Optimization", "Daily 02:00 Cron", "S3 Parquet Partitions (/year=YYYY/month=MM/)", "Parquet Compaction Benchmark", "Data Engineer"),
    ("ANL-034", "DuckDB Query Resource Consumption and Memory Throttling", "System Resilience", "Query Runtime", "DuckDB Memory Limit Configuration (max_memory=1GB)", "OOM Protection Chaos Test", "Data Platform Lead"),
    ("ANL-035", "Municipal Ward Health Equity Dashboard Analytical Feed", "Public Health", "Hourly Refresh", "Feed_Ward_Health_Equity (ward_id, equity_index)", "Dashboard Feed Freshness Test", "Data Analyst"),
    ("ANL-036", "Seasonal Epidemiology Wave Decomposition Analysis", "Epidemiology", "Monthly Seasonal", "Decomposition_Disease_Seasonality (trend, seasonal)", "Seasonal Wave Detection Test", "Data Scientist"),
    ("ANL-037", "Vaccine Wastage Rate and Vial Open Utilization Analytics", "Immunization", "Monthly Aggregate", "Metric_Vaccine_Wastage_Pct (vaccine_id, wastage)", "Vaccine Wastage Formula Audit", "Data Analyst"),
    ("ANL-038", "Teleconsultation Conversion and Doctor Acceptance Metrics", "Telehealth", "Monthly Aggregate", "Conversion_Teleconsultation (requested, accepted)", "Telehealth Metric Validation", "Operations Analyst"),
    ("ANL-039", "Biomedical Waste Generation per OPD Footfall Ratio", "Environmental Health", "Monthly Aggregate", "Ratio_Waste_Per_Patient (clinic_id, kg_per_opd)", "Waste Ratio Benchmark Test", "Operations Analyst"),
    ("ANL-040", "Open Data Health Bulletin Aggregation and Export Engine", "Public Health", "Monthly Release", "Public_Health_Bulletin_Dataset.parquet", "Public Data Release Verification", "Data Protection Officer"),
]

# -------------------------------------------------------------------------
# AIR_ITEMS: 40 AI & Decision-Support Items (AIR-001 to AIR-040)
# (id, title, advisory_scope, model_family, override_protocol, vmethod, owner)
# -------------------------------------------------------------------------
AIR_ITEMS = [
    ("AIR-001", "Clinical Advisory Decision Support Primacy Doctrine", "Core AI Principle", "Advisory Expert System", "Clinician Retains 100% Final Responsibility", "Doctrine Conformance Audit", "Chief Medical Officer"),
    ("AIR-002", "Syndromic Outbreak Spike Anomaly Detection Advisor", "Public Health", "Isolation Forest / Poisson EARS Algorithm", "Epidemiologist Reviews and Confirms Alert", "Synthetic Spike Detection Test", "Epidemiologist"),
    ("AIR-003", "Essential Drug List (EDL) Demand Forecasting Engine", "Supply Chain", "ARIMA / Prophet Time-Series Regression", "Pharmacist Overrides Indent Quantities", "Forecast Accuracy Backtesting", "Data Scientist"),
    ("AIR-004", "High-Risk Pregnancy Antenatal Prioritization Advisor", "Maternal Health", "Rule-Based Expert Score + Logistic Regression", "Medical Officer Validates ANC Risk Classification", "Clinical Cohort Sensitivity Test", "Medical Officer"),
    ("AIR-005", "Hypertension Escalation and Follow-Up Decision Support", "NCD Care", "Clinical Guideline Rule Engine (JNC 8 / ICMR)", "Medical Officer Determines Drug Titration", "Guideline Compliance Test", "Medical Officer"),
    ("AIR-006", "Type 2 Diabetes Complication Risk Stratification", "NCD Care", "Random Forest / ADA Risk Engine", "Medical Officer Validates Lifestyle / Drug Plan", "Diabetes Risk Precision Test", "Medical Officer"),
    ("AIR-007", "Drug-Drug Interaction (DDI) Real-Time Prescription Check", "Clinical Safety", "Deterministic Lexicon Matrix across 120 EDL", "Doctor Mandatory Override Reason Entry", "Contraindication Matrix Test", "Chief Pharmacist"),
    ("AIR-008", "Drug Allergy and Adverse Reaction Pre-Prescription Check", "Clinical Safety", "Cross-Referencing Patient Allergies vs Drug Class", "Doctor Mandatory Override Reason Entry", "Allergy Alert Accuracy Test", "Medical Officer"),
    ("AIR-009", "Pediatric Weight-Based Dosage Calculation Assistant", "Pediatrics", "Standard Pediatric Milligram/Kilogram Formulary", "Doctor Modifies or Accepts Proposed Dosage", "Dosage Formula Precision Test", "Medical Officer"),
    ("AIR-010", "Renal Impairment Dosage Adjustment Guidance Advisor", "Clinical Safety", "eGFR-Based Dose Reduction Matrix", "Doctor Selects Adjusted or Standard Dose", "Renal Dose Adjustment Test", "Medical Officer"),
    ("AIR-011", "Critical Laboratory Abnormal Flagging and Clinical Context", "Laboratory", "Age/Sex Specific Reference Range Decision Engine", "Doctor Reviews Abnormal Flag with Clinical Signs", "Lab Flagging Sensitivity Test", "Medical Officer"),
    ("AIR-012", "Clinical Note Entity Extraction for ICD-11 Suggestion", "Clinical Coding", "Biomedical NER / Fuzzy String Matcher", "Doctor Actively Selects or Rejects ICD-11 Code", "NER Precision and Recall Test", "Medical Officer"),
    ("AIR-013", "Duplicate Patient Identity Matching and Merging Assistant", "Identity Management", "Levenshtein Distance + Double Metaphone Soundex", "Registration Clerk / Supervisor Approves Merge", "Fuzzy Match Accuracy Test", "Data Platform Lead"),
    ("AIR-014", "Model Versioning, Provenance, and Registry Governance", "MLOps Governance", "MLflow / DVC Artifact Version Registry", "Automated Hash Verification Before Deployment", "Model Registry Audit", "MLOps Lead"),
    ("AIR-015", "Training Data Lineage, Curation, and Consent Verification", "Data Governance", "DPDP-Compliant De-Identified Training Sets", "Data Protection Officer Formal Release Sign-Off", "Training Dataset Privacy Audit", "Data Protection Officer"),
    ("AIR-016", "Algorithmic Bias and Demographic Subgroup Equity Audit", "AI Ethics", "Disparate Impact & Equalized Odds Auditing", "Annual AI Ethics Committee Independent Review", "Bias Metric Regression Test", "AI Ethics Officer"),
    ("AIR-017", "Concept Drift Detection in Syndromic Symptom Distributions", "Model Monitoring", "Kolmogorov-Smirnov Test on Clinical Features", "Automated Flag to Retrain Model on Drift Alert", "Drift Injection Simulation Test", "MLOps Lead"),
    ("AIR-018", "Covariate Shift Monitoring in Prescription Inflow Streams", "Model Monitoring", "Population Stability Index (PSI > 0.2 Trigger)", "Automated Pipeline Alert to Machine Learning Team", "Covariate Shift Audit Test", "MLOps Lead"),
    ("AIR-019", "Human-in-the-Loop Override Capture and Reason Taxonomy", "Human Oversight", "Structured Dropdown + Free Text Override Capture", "System Records Doctor Name, Timestamp, Reason", "Override Logging Verification", "Medical Officer"),
    ("AIR-020", "Model Explainability and Local Feature Attribution (SHAP)", "Explainable AI", "TreeSHAP / Linear Attribution Visualizer", "Clinician Views Top 3 Contributing Risk Factors", "Attribution Consistency Test", "Data Scientist"),
    ("AIR-021", "Confidence Score Thresholding and Low-Confidence Suppression", "Model Safety", "Softmax Calibration (<70% Suppresses Prompt)", "System Suppresses Vague Hints if Confidence Low", "Confidence Calibration Test", "Data Scientist"),
    ("AIR-022", "Zero-Latency Client-Side Fallback on Inference Failure", "Fault Tolerance", "Local Deterministic Rule Fallback (Regex/Rules)", "Silent Degradation to Standard Manual Entry", "Inference Failure Chaos Test", "Frontend Tech Lead"),
    ("AIR-023", "Immutable Audit Vault for Clinical AI Inferences and Prompts", "Auditability", "WORM Storage with Model Version, Input, Output", "System Logs Every Advisory Prompt Shown to Doctor", "AI Audit Vault Integrity Test", "Security Lead"),
    ("AIR-024", "Advisory Warning Non-Intrusive Banner UI Design Pattern", "User Experience", "Yellow/Orange Informational Toast (Non-Modal)", "Doctor Can Dismiss or Review Without Screen Lock", "UI Usability A/B Test", "Frontend Tech Lead"),
    ("AIR-025", "Critical Safety Interruption Modal for Fatal Contraindications", "Clinical Safety", "High-Urgency Red Modal for Severe DDI/Allergies", "Doctor Must Actively Select 'Override' or 'Change'", "Safety Modal Trigger Test", "Chief Medical Officer"),
    ("AIR-026", "Triage Patient Acuity Scoring Support (Modified MEWS)", "Triage", "Modified Early Warning Score (MEWS) Algorithm", "Staff Nurse Confirms Acuity Tier (Red/Yellow/Green)", "Acuity Scoring Accuracy Test", "Staff Nurse"),
    ("AIR-027", "Prescription Completeness and Missing Duration Validator", "Prescription Safety", "Deterministic Clinical Completeness Rules", "Doctor Prompted to Enter Duration or Quantity", "Prescription Linter Test", "Pharmacist"),
    ("AIR-028", "Childhood Immunization Delay and Defaulter Prediction", "Immunization", "Survival Analysis / Logistic Regression", "ANM / Staff Nurse Prioritizes Home Visit Outreach", "Defaulter Prediction Test", "Staff Nurse"),
    ("AIR-029", "Tuberculosis Symptom Cluster Risk Scoring", "Disease Surveillance", "ICMR Presumptive TB Risk Matrix", "Doctor Prompts Sputum / CBNAAT Lab Order", "TB Scoring Precision Test", "Medical Officer"),
    ("AIR-030", "Seasonal Vector-Borne Fever Risk Probability Estimation", "Disease Surveillance", "Rainfall / Temperature Paired Poisson Model", "Epidemiologist Reviews Seasonal Alert", "Vector Risk Correlation Test", "Epidemiologist"),
    ("AIR-031", "Geriatric Fall Risk and Frailty Assessment Support", "Geriatric Care", "Timed Up and Go (TUG) Rule Evaluator", "Staff Nurse Validates Geriatric Support Plan", "Frailty Score Test", "Staff Nurse"),
    ("AIR-032", "Mental Health Screening (PHQ-9) Advisory Score Interpretation", "Mental Health", "Standardized PHQ-9 Depression Severity Scoring", "Doctor Validates e-Manas Counseling Referral", "PHQ-9 Evaluation Test", "Medical Officer"),
    ("AIR-033", "Medicine Batch Expiry Waste Minimization Suggestion", "Inventory", "FIFO / FEFO Optimization Dispatch Algorithm", "Pharmacist Confirms Batch Dispensing Sequence", "FEFO Optimization Test", "Pharmacist"),
    ("AIR-034", "Point-of-Care Lab Quality Control Trend Advisor (Levey-Jennings)", "Quality Control", "Westgard Rules Statistical Process Control", "Lab Technician Runs Machine Calibration", "QC Anomaly Detection Test", "Lab Technician"),
    ("AIR-035", "Clinic Daily Patient Volume Forecasting for Staff Roster", "Operations", "SARIMA / Seasonal Decomposition on Footfall", "Medical Officer Schedules Auxiliary Nursing Staff", "Roster Forecasting Test", "Administrative Assistant"),
    ("AIR-036", "Automated Patient Language Detection for Bilingual Intake", "Localization AI", "FastText / Unicode Script Classifier (kn vs en)", "Clerk Confirms Preferred Language with Patient", "Language Detection Accuracy Test", "Registration Clerk"),
    ("AIR-037", "Speech-to-Text Clinical Note Transcription Assistant", "Clinical Entry", "Whisper Small Fine-Tuned on Kannada/Indian English", "Doctor Edits and Confirms Transcribed Text", "Word Error Rate (WER) Benchmark", "Medical Officer"),
    ("AIR-038", "Advisory Model Latency Budget (<200ms Client Response)", "Performance", "ONNX Runtime / TensorRT Optimized Graph", "Zero Perceptible Lag in Doctor EHR Workflow", "Inference Latency Stress Test", "MLOps Lead"),
    ("AIR-039", "Model Retraining Trigger and Human Evaluation Gateway", "Continuous Learning", "Monthly Offline Retraining Pipeline", "State Clinical Committee Signs Off Before Deploy", "Model Promotion Gate Test", "Chief Medical Officer"),
    ("AIR-040", "Annual Clinical Safety and Diagnostic Accuracy Review", "Governance", "Independent Retrospective Clinical Audit", "Ethics Board and Health Directorate Review", "Annual Clinical Safety Audit", "Project Director"),
]

# -------------------------------------------------------------------------
# INT_ITEMS: 50 Integration Requirements Items (INT-001 to INT-050)
# (id, title, system, protocol, payload, vmethod, owner)
# -------------------------------------------------------------------------
INT_ITEMS = [
    ("INT-001", "ABDM Milestone 1: ABHA Number Generation via Aadhaar OTP", "ABDM Sandbox / NHA", "REST HTTPS / OAuth 2.0", "JSON (Aadhaar OTP Request/Verify)", "ABDM Sandbox M1 Certification", "Integration Lead"),
    ("INT-002", "ABDM Milestone 1: ABHA Number Generation via Mobile OTP", "ABDM Sandbox / NHA", "REST HTTPS / OAuth 2.0", "JSON (Mobile OTP Request/Verify)", "ABDM Sandbox M1 Certification", "Integration Lead"),
    ("INT-003", "ABDM Milestone 1: ABHA Address (PHR Address) Linkage", "ABDM Sandbox / NHA", "REST HTTPS / OAuth 2.0", "JSON (ABHA Profile Update)", "ABDM Address Linkage Test", "Integration Lead"),
    ("INT-004", "ABDM Milestone 2: Health Information Provider (HIP) Registration", "ABDM Gateway / NHA", "REST HTTPS / Mutual TLS", "JSON (Facility Context Registration)", "HIP Facility Registration Test", "Integration Lead"),
    ("INT-005", "ABDM Milestone 2: FHIR R4 Bundle Composition (OPD Consultation)", "ABDM Gateway / NHA", "FHIR R4 over HTTPS", "FHIR Bundle (Composition, Patient, Condition, MedicationRequest)", "FHIR R4 Validation Suite", "FHIR / Health Informatics Lead"),
    ("INT-011", "Integrated Health Information Platform (IHIP Form P Daily Sync)", "IHIP / NCDC Gateway", "REST HTTPS / API Key", "JSON / XML (Form P Syndromic Daily Case Counts)", "IHIP Gateway Conformance Test", "Epidemiologist"),
    ("INT-012", "Nikshay Tuberculosis Surveillance Notification and Sync", "Central TB Division / NIC", "REST HTTPS / OAuth 2.0", "JSON (Nikshay Patient Notification)", "Nikshay Sandbox Test", "Integration Lead"),
    ("INT-013", "e-Vin Vaccine Cold Chain Logistics Information Sync", "e-Vin / State Health", "REST HTTPS / API Key", "JSON (Vaccine Consumption & Stock Balance)", "e-Vin Integration Test", "Pharmacist"),
    ("INT-014", "e-RaktKosh Zonal Blood Bank Stock Availability Query", "e-RaktKosh / CDAC", "REST HTTPS / API Key", "JSON (Blood Group Availability Query)", "e-RaktKosh Query Test", "Medical Officer"),
    ("INT-015", "e-Manas Mental Health Portal Referral and Registration Sync", "State Mental Health Authority", "REST HTTPS / Token Auth", "JSON (e-Manas Patient Referral Summary)", "e-Manas Sync Test", "Medical Officer"),
    ("INT-016", "CDAC SMS-Seva Gateway for Patient Notification and OTP", "CDAC Mobile Seva Gateway", "HTTPS POST / XML Payload", "XML (DLT Approved Template SMS Payload)", "SMS Gateway Delivery Test", "Integration Lead"),
    ("INT-017", "ESC/POS Thermal Receipt Printer via Web Serial API", "Thermal Receipt Printer (58mm/80mm)", "Web Serial API / Raw USB", "Raw ESC/POS Binary Byte Stream", "Hardware Loopback Test", "Hardware Integration Lead"),
    ("INT-018", "USB HID 1D/2D Barcode Scanner Keyboard Emulation Input", "Handheld Barcode Scanner", "USB HID Keyboard Emulation", "Standard ASCII / QR Code Text Stream", "Scanner Input Emulation Test", "Hardware Integration Lead"),
    ("INT-019", "Digital Blood Pressure Monitor Serial Data Ingestion", "Digital Omron / NIBP Monitor", "Web Serial API / Web Bluetooth", "Binary / ASCII Hex NIBP Data Stream", "NIBP Data Packet Validation", "Hardware Integration Lead"),
    ("INT-020", "Point-of-Care Digital Glucometer USB/Bluetooth Sync", "Accu-Chek / POC Glucometer", "Web Bluetooth / USB Serial", "IEEE 11073 Personal Health Device Data", "POC Glucometer Packet Test", "Hardware Integration Lead"),
    ("INT-021", "Point-of-Care Hemoglobinometer Serial Data Ingestion", "HemoCue / Digital Hb Meter", "Web Serial API / USB", "Standard Serial Hex ASCII Protocol", "Hb Packet Validation Test", "Hardware Integration Lead"),
    ("INT-022", "Infrared Non-Contact Digital Thermometer Sync", "Infrared Thermometer", "Web Bluetooth API", "Bluetooth GATT Health Thermometer Profile", "GATT Temperature Stream Test", "Hardware Integration Lead"),
    ("INT-023", "Karnataka Arogya Sanjeevani Tertiary Care Referral Gateway", "State Health Department Gateway", "REST HTTPS / Mutual TLS", "JSON (Referral Bundle with Clinical Vitals)", "Referral Gateway Integration Test", "Integration Lead"),
    ("INT-024", "OpenTelemetry Collector Telemetry Metric and Trace Export", "OpenTelemetry Daemon", "gRPC over HTTP/2", "OpenTelemetry Protocol (OTLP) Protobuf", "Telemetry Flow Integrity Test", "SRE Lead"),
    ("INT-025", "Prometheus Telemetry Metrics Scrape Endpoint", "Prometheus Server", "HTTP GET /metrics", "Standard Prometheus Text Format", "Prometheus Metric Scrape Test", "SRE Lead"),
    ("INT-026", "Syslog and Grafana Loki Structured Audit Log Ingestion", "Grafana Loki Ingestion Node", "REST HTTPS / POST /loki/api/v1/push", "Snappy-Compressed Protobuf / JSON", "Log Ingestion Pipeline Test", "Security Lead"),
    ("INT-027", "AWS S3 / MinIO Encrypted Database Backup Storage API", "Cloud Object Storage", "Amazon S3 REST API / AWS SDK", "AES-256 Encrypted Tarball Chunk Stream", "S3 Upload / Restore Verification Test", "SRE Lead"),
    ("INT-028", "Twilio / Gupshup WhatsApp Citizen Notification Fallback", "Gupshup / Twilio API", "REST HTTPS / OAuth 2.0", "JSON (Meta-Approved WhatsApp Business Template)", "WhatsApp Notification Delivery Test", "Integration Lead"),
    ("INT-029", "Embedded DuckDB Parquet Data Export Interface", "Local File System", "Local File I/O", "Snappy-Compressed Apache Parquet Binary", "Parquet Schema Conformity Test", "Data Platform Lead"),
    ("INT-030", "BBMP Ward-Level GIS Spatial Boundary Mapping API", "Municipal GIS Portal", "GeoJSON over HTTPS", "GeoJSON (Ward Boundary Polygons & Shapefiles)", "GIS Layer Rendering Test", "GIS / Epidemiologist"),
    ("INT-031", "Keycloak / OpenID Connect Enterprise Authentication", "BBMP IAM Gateway", "OAuth 2.0 / OpenID Connect", "JSON Web Tokens (JWT) / Authorization Codes", "OIDC Login & Token Refresh Test", "Security Lead"),
    ("INT-032", "CERT-In Automated Cybersecurity Incident Notification API", "CERT-In Incident Portal", "REST HTTPS / Client Certificate", "JSON (Standard CERT-In Incident Report Schema)", "CERT-In Notification Test", "Security Lead"),
    ("INT-033", "National Digital Health Mission (NDHM) Sandbox Validator", "NDHM Compliance Engine", "REST HTTPS / Mutual TLS", "FHIR R4 Diagnostic Bundles", "NDHM Compliance Test", "Integration Lead"),
    ("INT-034", "Aadhaar e-KYC Offline XML Verification Engine", "UIDAI Offline Gateway", "Local Cryptographic Engine", "Digitally Signed UIDAI XML / Share Code", "UIDAI Signature Validation Test", "Security Lead"),
    ("INT-035", "e-Sanjeevani National Teleconsultation Platform Gateway", "e-Sanjeevani 2.0 Gateway", "REST HTTPS / Token Auth", "JSON (Teleconsultation Appointment & Rx)", "e-Sanjeevani Gateway Test", "Medical Officer"),
    ("INT-036", "Janani Suraksha Yojana (JSY) Direct Benefit Transfer Sync", "Public Financial Management System", "SFTP / Encrypted PGP REST", "Encrypted XML (PFMS Payment Advice)", "DBT Payment File Integrity Test", "Administrative Assistant"),
    ("INT-037", "Urban Primary Health Center (UPHC) Referral Roster Sync", "District Health Office", "REST HTTPS / OAuth 2.0", "JSON (Inter-Clinic Referral Manifest)", "UPHC Roster Sync Test", "Integration Lead"),
    ("INT-038", "Central Medicine Warehouse Procurement and Inward PO Sync", "Karnataka State Drug Logistics Society", "REST HTTPS / SOAP Web Service", "XML (Inward Drug Consignment Manifest)", "Drug Consignment Inward Test", "Pharmacist"),
    ("INT-039", "Biomedical Waste Barcode Tracking Server Interface", "State Pollution Control Board Portal", "REST HTTPS / API Key", "JSON (Waste Consignment Barcode Manifest)", "Waste Tracking API Test", "Administrative Assistant"),
    ("INT-040", "Public Health Research Data Hub (ICMR) De-Identified Sink", "ICMR Research Server", "SFTP / Secure HTTPS", "Gzip-Compressed Parquet (k>=5 De-Identified)", "Research Sink Transmission Test", "Data Protection Officer"),
    ("INT-041", "Thermal Paper Low-Level Sensor Detection via Web Serial", "Thermal Receipt Printer", "Web Serial Low-Level Command", "ESC/POS Real-Time Status Byte (DLE EOT 1)", "Paper Out Detection Test", "Hardware Integration Lead"),
    ("INT-042", "USB Scale Gross Weight Ingestion for Biomedical Waste", "Digital Precision Bench Scale", "Web Serial API / USB CDC", "Continuous ASCII Weight Stream (ST, GS, +00.45kg)", "Weight Stream Parser Test", "Hardware Integration Lead"),
    ("INT-043", "Clinical Decision Support Rule Engine Hook Interface (CDS Hooks)", "Internal CDS Engine", "HTTP POST /cds-services/", "CDS Hooks JSON (PatientView, OrderSelect, OrderSign)", "CDS Hooks Contract Test", "Solution Architect"),
    ("INT-044", "FHIR R4 DiagnosticReport Profile Generation Interface", "Local EHR Store", "Internal Object Mapping", "FHIR R4 DiagnosticReport Resource", "DiagnosticReport Schema Test", "FHIR / Health Informatics Lead"),
    ("INT-045", "FHIR R4 MedicationRequest Profile Generation Interface", "Local EHR Store", "Internal Object Mapping", "FHIR R4 MedicationRequest Resource", "MedicationRequest Schema Test", "FHIR / Health Informatics Lead"),
    ("INT-046", "FHIR R4 ImmunizationRecommendation Profile Interface", "Local EHR Store", "Internal Object Mapping", "FHIR R4 ImmunizationRecommendation Resource", "Immunization Schema Test", "FHIR / Health Informatics Lead"),
    ("INT-047", "FHIR R4 Encounter and Condition Profile Interface", "Local EHR Store", "Internal Object Mapping", "FHIR R4 Encounter & Condition Resources", "Encounter Schema Test", "FHIR / Health Informatics Lead"),
    ("INT-048", "FHIR R4 Observation (Vitals and Lab) Profile Interface", "Local EHR Store", "Internal Object Mapping", "FHIR R4 Observation Resource", "Observation Schema Test", "FHIR / Health Informatics Lead"),
    ("INT-049", "ABDM Care-Context Linking and OTP Confirmation Gateway", "ABDM Gateway / NHA", "REST HTTPS / OAuth 2.0", "JSON (Care-Context Linking Notification)", "Care-Context Confirmation Test", "Integration Lead"),
    ("INT-050", "Comprehensive Interoperability Contract Test Suite", "All Connected Gateways", "Automated Pact / WireMock", "Contract Test Manifest (JSON/YAML)", "End-to-End Interoperability Suite", "Integration Lead"),
]
# Ensure INT has exactly 50 items (check IDs from 006 to 010)
# Let's insert missing 006-010 to make it exactly 50 items
_int_missing = [
    ("INT-006", "ABDM Milestone 2: Care-Context Linkage Notification", "ABDM Gateway / NHA", "REST HTTPS / Mutual TLS", "JSON (Care-Context Linkage Payload)", "Linkage Notification Test", "Integration Lead"),
    ("INT-007", "ABDM Milestone 3: Health Information User (HIU) Consent Request", "ABDM Gateway / NHA", "REST HTTPS / Mutual TLS", "JSON (Consent Request Initiation)", "Consent Request Test", "Integration Lead"),
    ("INT-008", "ABDM Milestone 3: Encrypted Health Data Flow (ECDH Transfer)", "ABDM Gateway / NHA", "HTTPS / ECDH Key Exchange", "Encrypted FHIR Payload over TLS", "ECDH Decryption Test", "Security Lead"),
    ("INT-009", "ABDM Health Facility Registry (HFR) Dynamic Directory Sync", "ABDM HFR / NHA", "REST HTTPS / API Key", "JSON (HFR Facility Directory Query)", "HFR Directory Sync Test", "Integration Lead"),
    ("INT-010", "ABDM Healthcare Professionals Registry (HPR) Practitioner Verification", "ABDM HPR / NHA", "REST HTTPS / API Key", "JSON (HPR Doctor Credentials Query)", "HPR Doctor Verification Test", "Integration Lead"),
]
INT_ITEMS = sorted(INT_ITEMS + _int_missing, key=lambda x: x[0])
