#!/usr/bin/env python3
"""
data_brule_items.py
Canonical list of 50 business rule definitions (BRULE-001 to BRULE-050).
"""

BRULE_ITEMS = [
    ("BRULE-001", "Universal Patient Registration Eligibility",
     "Any citizen presenting at a Namma Clinic counter is eligible for primary care registration regardless of municipal ward of residence.",
     "Municipal health charter guarantees universal access without territorial exclusion.",
     "Citizen presents at registration desk", "Full name, age/DOB, gender, mobile number, ward of residence",
     "IF citizen provides name and valid gender THEN allow registration ELSE prompt for missing mandatory attributes",
     "Patient master record created and municipal UHID minted", "Registration blocked until mandatory fields completed",
     "Emergency trauma or unconscious patients registered under emergency placeholder UHID",
     "Data Entry Operator", "None (Direct registration)", "Emits REGISTRATION_COMMITTED audit event"),

    ("BRULE-002", "Shared Family Mobile Number Permissibility",
     "Up to 8 individual family members may share the same primary mobile phone number under household linking rules.",
     "Low-income urban slum households frequently share a single mobile phone handset.",
     "Registration operator enters existing phone number", "Patient demographics, existing mobile number in database",
     "IF mobile exists AND relation confirmed (Spouse, Child, Parent) AND count < 8 THEN link ELSE prompt duplicate review",
     "New UHID created and linked to shared household phone group", "Phone rejected if shared across >8 distinct individuals without admin override",
     "Hostel or orphanage group registrations may exceed 8 with Medical Officer sign-off",
     "Data Entry Operator", "Facility Supervisor if count exceeds 8", "Logs HOUSEHOLD_PHONE_SHARED event"),

    ("BRULE-003", "Mandatory Demographic Attributes Verification",
     "Patient registration cannot be finalized without full name, biological gender, and either age or verified date of birth.",
     "Prevents anonymous or corrupted patient indices in municipal registry.",
     "Operator clicks 'Save Patient'", "Name string, gender enum, age integer or DOB date",
     "IF length(name) >= 2 AND gender IN ('M', 'F', 'T') AND (age > 0 OR dob != NULL) THEN PASS ELSE FAIL",
     "Patient demographic record committed to database", "Form submission blocked; missing fields highlighted in red",
     "Unidentified emergency patients registered under `UNKNOWN-MALE/FEMALE-TIMESTAMP`",
     "Data Entry Operator", "None", "Logs VALIDATION_FAILURE event if rejected"),

    ("BRULE-004", "Emergency Care Unconditional Bypass of ABHA/ID",
     "Emergency patients experiencing acute distress shall never be denied triage or care due to lack of Aadhaar, ABHA, or identification.",
     "Preservation of human life strictly supersedes administrative data collection.",
     "Patient arrives with emergency condition (shock, acute trauma, dyspnea)", "Emergency triage flag toggled by nurse or doctor",
     "IF emergency_flag == TRUE THEN bypass ABHA, phone verification, and address capture",
     "Immediate emergency token issued; routed directly to Medical Officer desk", "Care cannot be blocked or delayed for paperwork",
     "Standard demographics must be collected retrospectively upon clinical stabilization",
     "Staff Nurse", "Medical Officer immediate sign-off", "Emits EMERGENCY_BYPASS_AUDIT with doctor ID"),

    ("BRULE-005", "Automated Age Derivation from Date of Birth",
     "When exact date of birth is supplied, age in years, months, and days shall be derived dynamically at runtime.",
     "Prevents static age staleness in pediatric and maternal registries.",
     "Operator enters DOB or changes birth date", "Date of birth value (YYYY-MM-DD)",
     "derived_age = current_date - date_of_birth; IF derived_age < 0 THEN FAIL",
     "Calculates exact age; auto-populates pediatric growth or geriatric flags", "Rejects future dates of birth with HTTP 400",
     "Approximate age accepted when exact birth date is unknown to illiterate citizens",
     "Data Entry Operator", "None", "Logs DEMOGRAPHIC_AGE_DERIVED"),

    ("BRULE-006", "Temporary Offline UHID 72-Hour Reconciliation Window",
     "Temporary UHIDs minted during offline network operation must be reconciled with central cloud registry within 72 hours.",
     "Prevents unmerged duplicate patient records from diverging across clinics.",
     "Clinic terminal reconnects to municipal WAN", "List of locally generated `TEMP-` UHIDs in Dexie.js",
     "IF central record matches mobile and name THEN merge to existing UHID ELSE mint permanent UHID",
     "Temporary UHID mapped to permanent central UHID; clinical records repointed", "Unreconciled after 72h triggers supervisory audit alert",
     "Extended offline period (>72h) preserves temporary UHID until manual zonal review",
     "Background Sync Daemon", "Zonal IT Administrator if conflict unresolved", "Emits UHID_RECONCILIATION_LOG"),

    ("BRULE-007", "Demographic Modification Mandatory Reason Logging",
     "Any amendment to a patient's name, gender, or date of birth requires a mandatory justification note (>10 characters).",
     "Prevents fraudulent identity swapping and accidental record corruption.",
     "Staff submits edit to existing patient demographic profile", "Patient UHID, modified fields, justification text string",
     "IF length(justification_text) >= 10 AND user_role IN ('MO', 'FACILITY_ADMIN') THEN ALLOW",
     "Demographics updated; prior snapshot archived in `patient_history` table", "Submission blocked if justification note is missing or too short",
     "Minor spelling typo corrections (<2 characters) permitted by DEO within 2 hours of registration",
     "Medical Officer", "Medical Officer or Facility Admin", "Emits DEMOGRAPHIC_AMENDMENT_AUDIT"),

    ("BRULE-008", "Household Linking Consent & Authorization",
     "Linking a patient to an existing family head requires confirmation from the head or verified ration card documentation.",
     "Protects citizen privacy and prevents unauthorized aggregation of health records.",
     "Staff attempts to link secondary patient to household head", "Head UHID, member UHID, relationship documentation",
     "IF relationship verified AND head consent logged THEN commit household edge",
     "Household graph updated; shared phone alerts enabled for appointment reminders", "Linking rejected; patient remains independent record",
     "Immediate biological children under 12 years linked without separate documentation",
     "Data Entry Operator", "Staff Nurse or MO review", "Logs HOUSEHOLD_LINK_CREATED"),

    ("BRULE-009", "DPDP Act Consent Withdrawal Right Enforcement",
     "A citizen may withdraw consent for data processing at any time, halting non-essential communications while retaining clinical records.",
     "Mandated under India Digital Personal Data Protection Act 2023.",
     "Citizen requests consent revocation at registration desk", "Patient UHID, withdrawal form, citizen signature/OTP",
     "IF consent_withdrawn == TRUE THEN disable SMS, research exports, and ABHA sync; RETAIN clinical care archive per medical laws",
     "Consent status updated to WITHDRAWN; external data sharing halted", "Cannot delete historical medical treatment records mandated by NMC regulations",
     "Medical treatment records retained for 10-year statutory period despite consent revocation",
     "Data Entry Operator", "Data Protection Officer (DPO)", "Emits DPDP_CONSENT_WITHDRAWN_AUDIT"),

    ("BRULE-010", "Patient Record Archiving vs Deletion Boundary",
     "Clinical records in the Namma Clinic platform shall never be permanently hard-deleted; soft-deletion with tombstoning is enforced.",
     "Ensures medicolegal accountability and compliance with National Medical Commission rules.",
     "Administrator submits record deletion request", "Target record ID, table name, deletion justification",
     "IF request_type == 'DELETE' THEN set is_deleted=TRUE, deleted_at=NOW(), preserve raw row payload",
     "Record hidden from routine clinic searches; preserved in forensic database audit tables", "Hard DELETE query rejected by PostgreSQL row-level security policy",
     "Zero exceptions; hard database deletion strictly prohibited in production",
     "System Administrator", "BBMP Legal Advisor & Chief Health Officer", "Emits SECURITY_WORM_TOMBSTONE_LOG"),

    ("BRULE-011", "OPD Token Daily Numbering Reset at Midnight",
     "OPD visit tokens shall reset to sequence number 001 at exactly 00:00:00 IST for every clinic facility.",
     "Provides intuitive daily token numbers (1, 2, 3...) for clinic staff and patients.",
     "Midnight chron trigger or first token request of new calendar date", "Current facility ID, system date boundary",
     "IF current_date > last_token_date THEN current_sequence = 1",
     "New daily sequence initialized at 001; prior day tokens archived as COMPLETED/EXPIRED", "Cannot issue yesterday's token numbers",
     "Clinics operating emergency night shifts continue sequential sequence until morning handover",
     "Queue Management Subsystem", "None (Automated engine)", "Logs QUEUE_DAILY_RESET_EVENT"),

    ("BRULE-012", "Priority Queue Slot Allocation Ratio (2:1 Regular-to-Priority)",
     "The automated calling engine shall interleave priority tokens at a maximum ratio of 2 regular tokens per 1 priority token.",
     "Balances urgent needs of frail patients with fair waiting times for regular attendees.",
     "Doctor or nurse clicks 'Call Next Patient'", "Active regular token queue, active priority token queue",
     "IF priority_queue.count > 0 AND regular_served_counter >= 2 THEN call priority ELSE call regular",
     "Calls next priority patient; resets regular served counter", "Priority tokens cannot completely starve regular queue unless marked EMERGENCY",
     "Emergency red-flag tokens immediately take top slot (0 wait)",
     "Queue Calling Engine", "Medical Officer override", "Logs QUEUE_CALL_DISPATCHED"),

    ("BRULE-013", "OPD Token Automatic Expiration After 24 Hours",
     "Any token remaining in QUEUED or CALLING state after 24 hours shall be automatically transitioned to EXPIRED status.",
     "Prevents abandoned or ghost tokens from cluttering subsequent day queues.",
     "Daily midnight maintenance worker runs", "List of active tokens created >24 hours prior",
     "IF token.status IN ('QUEUED', 'CALLING') AND token.created_at < NOW() - INTERVAL '24 HOURS' THEN status = 'EXPIRED'",
     "Token status set to EXPIRED; removed from active waiting displays", "Expired tokens cannot be called by doctors without re-checkin",
     "Patients returning next morning issued fresh token linked to prior encounter",
     "Background Queue Daemon", "None", "Logs TOKEN_AUTO_EXPIRED_EVENT"),

    ("BRULE-014", "Multi-Doctor Consultation Queue Load Balancing",
     "In multi-doctor clinics, triaged patients shall be routed to the doctor room with the shortest estimated waiting dwell time.",
     "Optimizes clinic throughput and prevents uneven doctor workloads.",
     "Nurse completes patient triage vitals", "Active doctor rooms, current queue length per doctor",
     "target_doctor = doctor_with_min(active_tokens + estimated_consultation_time)",
     "Token assigned to specific doctor queue; patient directed to corresponding door", "Cannot assign to doctor marked ON_BREAK or LOGGED_OUT",
     "Patient requesting specific gender physician honored where clinically feasible",
     "Queue Routing Engine", "Medical Officer / Nurse manual re-routing", "Logs QUEUE_LOAD_BALANCED_EVENT"),

    ("BRULE-015", "Maximum Active Clinic Waiting Room Capacity Cap",
     "A clinic queue shall not exceed 150 active uncalled tokens simultaneously without triggering supervisory crowd alerts.",
     "Maintains waiting room physical safety and prevents dangerous overcrowding.",
     "Token generation requested at front desk", "Count of active tokens in QUEUED state",
     "IF active_tokens >= 150 THEN trigger CROWD_ALERT; prompt operator to notify Medical Officer",
     "Issues token but alerts Zonal Health Officer of high clinic surge", "Does not deny patient care; escalates operational support",
     "Mass casualty or epidemic surge mode disables crowd cap with ZHO authorization",
     "Registration Engine", "Medical Officer & Zonal Health Officer", "Logs FACILITY_OVERCROWDING_ALERT"),

    ("BRULE-016", "Uncalled Token Cancellation Protocol",
     "Tokens called 3 consecutive times with no patient response after 45 minutes shall transition to NO_SHOW status.",
     "Clears queue of patients who departed clinic without notifying staff.",
     "Doctor or nurse calls token for 3rd time with zero response", "Token call timestamps, current time delta > 45 minutes",
     "IF call_count >= 3 AND elapsed_time >= 45m THEN status = 'NO_SHOW'",
     "Token marked NO_SHOW; next patient called immediately", "Patient cannot reclaim old queue slot without re-queuing at front desk",
     "Patient returning within same operating shift may be reinstated to priority queue by nurse",
     "Medical Officer / Nurse", "Staff Nurse confirmation", "Logs TOKEN_NO_SHOW_EVENT"),

    ("BRULE-017", "Mandatory Triage Vitals Prior to Doctor Consultation",
     "Patients must complete nursing triage vitals (BP, Pulse, Temp) before their token becomes visible on the doctor consultation list.",
     "Guarantees clinician has objective vital signs before initiating diagnosis.",
     "Doctor consultation list refreshed", "Token status, associated vitals record",
     "IF vitals.recorded == TRUE THEN token.status = 'TRIAGED' (visible to doctor) ELSE status = 'WAITING_TRIAGE'",
     "Patient appears on doctor consultation screen", "Doctor cannot select un-triaged patient from standard queue",
     "Emergency trauma bypass allows doctor to enter vitals retrospectively",
     "Triage Engine", "Medical Officer emergency override", "Logs TRIAGE_GATE_ENFORCED"),

    ("BRULE-018", "Red-Flag Triage Vitals Immediate Priority Escalation",
     "Any patient whose triage vitals trigger red-flag emergency criteria shall be automatically elevated to top priority.",
     "Prevents patient deterioration or cardiac arrest in the waiting hall.",
     "Nurse saves vital signs", "Measured SBP, DBP, SpO2, Pulse, Temp, Glucose",
     "IF SBP>=180 OR DBP>=120 OR SpO2<90% OR Pulse>140 THEN escalate token to EMERGENCY",
     "Token moves to #1 queue position; audible alert chimes on doctor workstation", "Cannot be deprioritized by regular tokens",
     "Zero exceptions for red-flag vital triggers",
     "Clinical Triage Subsystem", "Medical Officer immediate evaluation", "Logs RED_FLAG_ESCALATION_EVENT"),

    ("BRULE-019", "Registration Counter Queue Bypass for Resuscitation",
     "Staff members escorting actively collapsing patients may bypass registration directly into the doctor or procedure room.",
     "Preserves the golden hour in acute medical emergencies.",
     "Staff identifies collapsing, seizing, or unconscious patient", "Patient physical arrival at clinic",
     "IF patient.condition == 'COLLAPSED' THEN direct entry to resuscitation bed",
     "Clinical care starts immediately; temporary emergency token generated by nurse", "Front desk registration deferred until stabilization",
     "Mandatory retrospective documentation within 2 hours of stabilization",
     "Any Clinic Staff", "Medical Officer", "Logs EMERGENCY_RESUSCITATION_BYPASS"),

    ("BRULE-020", "Doctor Patient Recall Limit within Same Shift",
     "A doctor may recall a previously consulted patient (e.g. to review lab results) up to 2 times within the same operating shift.",
     "Facilitates lab result review without requiring the patient to re-register.",
     "Doctor clicks 'Recall Patient for Lab Review'", "Encounter ID, finalized within current date shift",
     "IF recall_count < 2 AND encounter.date == TODAY THEN place in doctor recall queue",
     "Token called back into consultation room; past encounter opened in edit/append mode", "Recall blocked if patient visit was on a prior calendar date",
     "Subsequent date visits require fresh registration and consultation encounter",
     "Medical Officer", "Medical Officer", "Logs PATIENT_RECALL_EVENT"),

    ("BRULE-021", "Strict FEFO (First-Expired, First-Out) Pharmacy Allocation",
     "The dispensing system shall mandate allocation of medicine batches with the earliest expiry date; newer batches cannot be picked.",
     "Eliminates medicine expiration on clinic shelves and enforces municipal drug policy.",
     "Pharmacist opens prescription line item for dispensing", "Inventory batches for prescribed drug with balance > 0",
     "allocated_batch = batch_with_min(expiry_date); IF scanned_batch != allocated_batch THEN BLOCK",
     "Earliest batch dispensed; stock ledger decremented", "Dispensing of newer batch rejected with error banner",
     "Pharmacist may override FEFO only if earliest batch is damaged/recalled with mandatory justification",
     "Pharmacist", "Medical Officer dual sign-off for FEFO override", "Logs FEFO_VIOLATION_OVERRIDE"),

    ("BRULE-022", "Emergency Stock Adjustment Limit (Max 10 Units)",
     "A pharmacist may adjust stock downwards for broken or contaminated ampoules/tablets up to a maximum of 10 units without supervisor approval.",
     "Allows routine loss write-offs while preventing large-scale inventory diversion.",
     "Pharmacist submits stock adjustment for broken vial", "Drug ID, batch number, adjustment quantity, reason code",
     "IF quantity <= 10 AND reason IN ('BROKEN', 'SPILLED') THEN auto-approve ELSE require supervisor",
     "Inventory ledger adjusted by requested units", "Adjustments > 10 units blocked pending Medical Officer approval",
     "Total cumulative daily unapproved adjustments across clinic cannot exceed 25 units",
     "Pharmacist", "Medical Officer for adjustments > 10 units", "Logs STOCK_ADJUSTMENT_EXECUTED"),

    ("BRULE-023", "Near-Expiry Drug Mandatory Quarantine at T-60 Days",
     "Medicine batches expiring within 60 calendar days shall be automatically quarantined and barred from routine prescription dispensing.",
     "Prevents patients from receiving medications that expire mid-treatment.",
     "Daily midnight inventory audit worker runs", "All active inventory batches in clinic pharmacy",
     "IF batch.expiry_date <= NOW() + INTERVAL '60 DAYS' THEN batch.status = 'QUARANTINED'",
     "Batch status set to QUARANTINED; removed from doctor prescribing and pharmacy picking search", "Cannot be dispensed to patients",
     "Batch may be transferred back to central warehouse or utilized in high-volume camp with ZHO approval",
     "Inventory Subsystem", "Chief Pharmacist & Medical Officer", "Logs BATCH_QUARANTINE_AUTO_EVENT"),

    ("BRULE-024", "Zero Dispensing Without Verified Electronic Prescription",
     "No medication from the Karnataka 120 EDL shall be dispensed without a cryptographically signed electronic prescription in the system.",
     "Prevents unauthorized medicine leakage, informal dispensing, and drug abuse.",
     "Citizen presents at pharmacy window requesting medicines", "Scanned token barcode or UHID",
     "IF valid_electronic_prescription_exists(token_id) == TRUE THEN display items ELSE reject",
     "Dispensing workflow enabled for pharmacist", "Dispensing completely blocked; citizen directed to consultation desk",
     "Emergency resuscitation drugs administered under doctor verbal order documented within 30 mins",
     "Pharmacist", "Medical Officer", "Logs UNAUTHORIZED_DISPENSE_BLOCKED"),

    ("BRULE-025", "Partial Prescription Dispensing Ledger Integrity",
     "When stock is insufficient for a full 30-day course, pharmacist must record exact dispensed quantity; balance cannot be dispensed later.",
     "Maintains exact accounting; prevents phantom claims for unsupplied medicines.",
     "Pharmacist enters dispensed quantity less than prescribed", "Prescribed quantity, available batch stock balance",
     "IF dispensed_qty < prescribed_qty THEN record partial_dispense; set prescription.status = 'PARTIALLY_FULFILLED'",
     "Patient given partial supply with clear label; stock decremented by exact dispensed amount", "Patient cannot return days later for remaining balance without re-evaluation",
     "Follow-up refill date adjusted earlier based on partial days of supply provided",
     "Pharmacist", "None", "Logs PARTIAL_DISPENSE_EVENT"),

    ("BRULE-026", "Controlled Antibiotic Dispensing Duration Boundary",
     "Broad-spectrum Tier-2 antibiotics (e.g. Amoxiclav, Ciprofloxacin, Cefixime) shall not be prescribed for duration exceeding 7 days.",
     "Enforces national antimicrobial stewardship and combats antibiotic resistance.",
     "Doctor enters antibiotic prescription item", "Drug code, prescribed duration in days",
     "IF drug.category == 'RESTRICTED_ANTIBIOTIC' AND duration > 7 THEN BLOCK prescription",
     "Prescription approved if duration <= 7 days", "Prescription blocked; doctor prompted to reduce duration or refer",
     "Chronic osteomyelitis or specialized infections require documented specialist recommendation note",
     "Medical Officer", "Medical Officer", "Logs ANTIBIOTIC_STEWARDSHIP_WARNING"),

    ("BRULE-027", "Discrepancy Stock Adjustment Dual Authorization",
     "Any negative stock adjustment exceeding 50 units or value > ₹500 requires dual biometric/password approval from MO and Zonal Pharmacist.",
     "Protects municipal assets against systematic pharmaceutical diversion.",
     "Stock audit reveals large inventory variance", "Drug ID, batch, discrepancy quantity, estimated value",
     "IF discrepancy_quantity > 50 OR value > 500 THEN require dual authentication",
     "Stock reconciled in database; formal incident report generated for BBMP Audit", "Adjustment blocked until secondary supervisor signs off",
     "Zero exceptions; unapproved variances remain open investigation items",
     "Pharmacist & Medical Officer", "Zonal Supervisory Pharmacist", "Logs MAJOR_STOCK_DISCREPANCY_AUDIT"),

    ("BRULE-028", "Mandatory Weekly Physical Inventory Reconciliation",
     "Clinics must complete a physical inventory count of all 120 EDL medicines every Saturday before 14:00 IST.",
     "Maintains high data fidelity between physical shelf stock and digital ledger.",
     "Saturday 12:00 IST operational trigger", "Physical count inputs for all active drug batches",
     "IF physical_count == system_balance THEN ledger verified ELSE log variance",
     "Weekly stock audit certified; inventory snapshot archived", "Clinic cannot finalize Saturday session without completing audit",
     "Public health emergency camp allows 24-hour extension with ZHO approval",
     "Pharmacist", "Medical Officer sign-off", "Logs WEEKLY_STOCK_AUDIT_CERTIFIED"),

    ("BRULE-029", "Minimum Buffer Stock Automated Reorder Threshold",
     "An automated replenishment indent shall be generated whenever total clinic stock falls below 7 days of Average Daily Consumption.",
     "Guarantees proactive municipal supply chain replenishment before stockouts occur.",
     "Daily closing stock tally calculated", "Current batch balances, 30-day Average Daily Consumption (ADC)",
     "IF current_stock < (ADC * 7) THEN add item to weekly warehouse indent list",
     "Item flagged LOW_STOCK; auto-populated on indent submission screen", "Items above buffer threshold excluded from routine indents",
     "Pharmacist may add emergency items to indent with documented surge rationale",
     "Inventory Subsystem", "Pharmacist confirmation", "Logs INDENT_BUFFER_TRIGGERED"),

    ("BRULE-030", "Stock Delivery Challan Barcode Verification",
     "Incoming stock deliveries from BBMP warehouse must have at least 20% of received boxes scanned via barcode before acceptance.",
     "Ensures correct batch numbers and expiry dates are committed to local inventory.",
     "Pharmacist ingests electronic delivery challan", "Scanned barcodes from delivery boxes",
     "IF verified_barcode_count >= (total_boxes * 0.20) THEN allow challan receipt ELSE block",
     "Stock committed to local dispensing ledger; receipt acknowledged to warehouse", "Challan receipt blocked until physical scanning quota is met",
     "Emergency single-item deliveries allow 100% manual entry with MO sign-off",
     "Pharmacist", "Medical Officer confirmation", "Logs STOCK_DELIVERY_ACCEPTED"),

    ("BRULE-031", "Mandatory Diagnosis Before Consultation Finalization",
     "A clinical encounter cannot be signed or finalized without at least one primary ICD-10 diagnostic code or codified symptom.",
     "Ensures medicolegal documentation completeness and epidemiological visibility.",
     "Doctor clicks 'Sign & Finalize Consultation'", "Encounter diagnostic entity list",
     "IF count(encounter.diagnoses) >= 1 THEN allow finalization ELSE block",
     "Encounter signed; prescription transmitted to pharmacy; token moved to PHARMACY queue", "Finalization blocked; doctor prompted to select diagnosis",
     "Zero exceptions; every consultation must have at least one diagnostic classification",
     "Medical Officer", "Medical Officer", "Logs ENCOUNTER_FINALIZATION_ATTEMPT"),

    ("BRULE-032", "Restricted Non-Formulary Commercial Drug Blocking",
     "Doctors shall not prescribe commercial trade brand names not included in the approved Karnataka 120 EDL catalog.",
     "Eliminates out-of-pocket patient expenditures at private commercial pharmacies.",
     "Doctor searches for drug in prescription pane", "Search query string",
     "IF candidate_drug NOT IN karnataka_120_edl_catalog THEN block from prescription builder",
     "Formulary drug added with generic name and strength", "Commercial non-EDL drug blocked; alert displays stocked therapeutic alternative",
     "Specialist referral hospitals may prescribe specialized non-EDL drugs upon counter-referral",
     "Medical Officer", "None (System formulary lock)", "Logs NON_FORMULARY_PRESCRIBE_BLOCKED"),

    ("BRULE-033", "Single Encounter Prescription Item Limit (Max 6 Medications)",
     "A single primary care consultation prescription shall contain a maximum of 6 distinct pharmaceutical line items.",
     "Prevents dangerous polypharmacy and excessive drug burden in primary care patients.",
     "Doctor adds medication to prescription list", "Count of active line items on prescription",
     "IF count(prescription.items) > 6 THEN block addition; require clinical justification",
     "Medication added if count <= 6", "7th medication blocked; alert prompts review for polypharmacy",
     "Complex multimorbid elderly patients may prescribe up to 8 items with documented note",
     "Medical Officer", "Medical Officer", "Logs POLYPHARMACY_LIMIT_WARNING"),

    ("BRULE-034", "High-Severity Drug-Drug Interaction Mandatory Override Note",
     "Bypassing a high-severity contraindication alert requires a documented clinical override reason of at least 15 characters.",
     "Ensures clinician actively deliberates life-threatening drug contraindications.",
     "Doctor clicks 'Override Warning' on severe DDI alert", "Override category selection, clinical justification text",
     "IF length(override_text) >= 15 AND category IN ('BENEFIT_EXCEEDS_RISK', 'MONITORED_TOLERATED') THEN ALLOW",
     "Alert dismissed; override event written to immutable WORM audit store", "Override blocked until meaningful justification is typed",
     "Zero exceptions for Level-1 severe contraindications",
     "Medical Officer", "Medical Officer", "Logs CLINICAL_OVERRIDE_RECORDED"),

    ("BRULE-035", "Documented Patient Drug Allergy Absolute Block",
     "The system shall completely block prescribing of a medication to which the patient has a documented severe anaphylactic allergy.",
     "Prevents fatal in-clinic anaphylactic shock events.",
     "Doctor selects medication for prescription", "Patient documented allergy list, candidate drug chemical class",
     "IF candidate_drug.class IN patient.severe_allergies THEN HARD_BLOCK",
     "Prescription rejected; prominent red alert displays allergic reaction history", "Cannot be bypassed via routine override; requires allergy deletion",
     "If documented allergy was misdiagnosed, allergy record must be formally revoked by MO",
     "Prescription Subsystem", "Medical Officer formal allergy revocation", "Logs ALLERGY_HARD_BLOCK_EVENT"),

    ("BRULE-036", "Chronic Disease Prescription Maximum Duration (30 Days)",
     "Prescriptions for chronic NCD medications (antihypertensives, antidiabetics) shall not exceed a 30-day supply per encounter.",
     "Enforces mandatory monthly clinical monitoring of blood pressure and blood sugar.",
     "Doctor enters duration for chronic medication", "Drug therapeutic class, duration integer",
     "IF drug.is_chronic == TRUE AND duration > 30 THEN cap duration at 30 days",
     "Duration set to 30 days; follow-up scheduled for Day 28", "Durations >30 days rejected with clinical guideline prompt",
     "Patients traveling outside state may receive 60-day supply with MO documented note",
     "Medical Officer", "Medical Officer", "Logs CHRONIC_DURATION_CAPPED"),

    ("BRULE-037", "Mandatory Pediatric Weight for Liquid Formulations",
     "Liquid suspensions and syrups cannot be prescribed for children under 12 years without a recorded weight in the current visit.",
     "Prevents dangerous pediatric under-dosing or toxic overdosing.",
     "Doctor prescribes pediatric syrup to child", "Patient age, current visit triage weight in kg",
     "IF patient.age < 12 AND triage.weight == NULL THEN BLOCK prescription line",
     "Prescription item enabled once nurse or doctor enters measured weight", "Blocked until weight entered; prompts user to record weight",
     "If child is uncooperative for scale, approximate weight estimation flag requires MO sign-off",
     "Prescription Engine", "Staff Nurse / MO weight entry", "Logs PEDIATRIC_WEIGHT_GATE_ENFORCED"),

    ("BRULE-038", "Follow-Up Appointment Date Horizon Limit (90 Days)",
     "Scheduled follow-up appointment dates shall not exceed 90 calendar days from the date of the current consultation encounter.",
     "Ensures primary care patients remain actively linked to municipal health monitoring.",
     "Doctor selects future follow-up date", "Current encounter date, selected follow-up date",
     "IF follow_up_date > (current_date + 90 days) THEN reject date selection",
     "Follow-up appointment registered; SMS reminder scheduled", "Date selection rejected; doctor prompted to select date within 90 days",
     "Annual cancer screening follow-ups logged in specialized screening registry, not OPD appointments",
     "Medical Officer", "Medical Officer", "Logs FOLLOW_UP_HORIZON_VALIDATED"),

    ("BRULE-039", "Secondary Hospital Referral Clinical Justification Mandate",
     "Referrals to BBMP secondary hospitals (KC General, Bowring) must include a provisional diagnosis and clinical reason for transfer.",
     "Prevents unnecessary overcrowding of tertiary hospitals with routine primary conditions.",
     "Doctor initiates secondary hospital referral", "Target hospital, provisional diagnosis, referral reason string",
     "IF length(referral_reason) >= 15 AND target_hospital IN bbmp_hospital_registry THEN ALLOW",
     "Digital referral slip generated with secure QR code", "Referral blocked until clinical transfer justification is documented",
     "Emergency trauma transfers may select quick-action pre-set chips (e.g. 'ACUTE_CORONARY_SYNDROME')",
     "Medical Officer", "Medical Officer", "Logs SECONDARY_REFERRAL_CREATED"),

    ("BRULE-040", "Counter-Referral Note Doctor Verification Requirement",
     "Counter-referral clinical notes received from tertiary hospitals must be reviewed and verified by a Medical Officer before EMR filing.",
     "Guarantees that post-hospital discharge treatment plans are vetted by the neighborhood physician.",
     "Staff ingests discharge summary document", "Document payload, assigned Medical Officer ID",
     "IF doctor.reviews_and_signs == TRUE THEN status = 'COUNTER_REFERRAL_VERIFIED'",
     "Hospital discharge summary integrated into patient longitudinal timeline", "Notes remain in PENDING_REVIEW status; cannot alter active medication list",
     "Zero exceptions; clinical vetting mandatory before changing ongoing primary therapy",
     "Medical Officer", "Medical Officer", "Logs COUNTER_REFERRAL_VERIFIED"),

    ("BRULE-041", "Clinic Closure Blocked with Active Unfinalized Consultations",
     "Daily clinic closure (17:30 IST) cannot be finalized while patients remain in CALLING or CONSULTING states.",
     "Guarantees no patient is left abandoned in the doctor's room or waiting queue.",
     "Medical Officer initiates End-of-Day clinic closure", "Current facility token states",
     "IF count(tokens WHERE status IN ('CALLING', 'CONSULTING')) == 0 THEN ALLOW closure ELSE BLOCK",
     "Daily session locked; final census submitted to BBMP command center", "Closure blocked; lists unfinalized tokens requiring resolution",
     "Unresponsive patients can be marked NO_SHOW or CANCELLED to clear queue",
     "Medical Officer", "Medical Officer", "Logs EOD_CLOSURE_BLOCKED_ALERT"),

    ("BRULE-042", "Daily Data Sync Cutoff at 18:00 IST",
     "All clinic workstations must complete synchronization of daily mutation queues to central cloud by 18:00 IST daily.",
     "Provides accurate, consolidated daily health data for municipal executive dashboards.",
     "18:00 IST operational trigger", "Pending local mutation queues across all workstations",
     "IF pending_mutations == 0 THEN emit SYNC_RECONCILED ELSE trigger SYNC_LAG_ALERT",
     "Daily clinic sync certified; data reflected in municipal command center", "Workstations with pending sync highlight flashing red alert",
     "Prolonged network outage permits automatic sync catch-up upon network return",
     "Background Sync Subsystem", "Facility IT Administrator", "Logs DAILY_SYNC_CUTOFF_AUDIT"),

    ("BRULE-043", "Retrospective Encounter Amendment Supervisor Dual Approval",
     "Amending clinical encounter notes finalized more than 24 hours prior requires secondary authorization from Zonal Health Officer.",
     "Prevents post-hoc tampering with medicolegal patient records.",
     "Doctor submits addendum request for historic consultation", "Encounter finalized timestamp, amendment text, justification",
     "IF (NOW() - encounter.finalized_at) > 24 HOURS THEN require ZHO dual signature",
     "Addendum appended to encounter record with audit trail", "Amendment blocked pending zonal supervisor review",
     "Zero exceptions; medical notes locked after 24 hours without administrative approval",
     "Medical Officer & Zonal Health Officer", "Zonal Health Officer", "Logs HISTORIC_AMENDMENT_DUAL_AUTH"),

    ("BRULE-044", "Emergency Zonal Formulary Broadcast Mandatory Acknowledgment",
     "When the Chief Health Officer issues an emergency formulary alert (e.g. drug recall), clinic staff must acknowledge before proceeding.",
     "Ensures immediate frontline compliance with critical safety recalls and epidemic notices.",
     "Central administrative broadcast received on clinic terminal", "Terminal active session, broadcast ID",
     "IF broadcast.acknowledged == FALSE THEN display modal lock across all screens",
     "Modal dismissed and normal workflow restored once staff clicks 'Acknowledge'", "Terminal screens locked behind broadcast modal until acknowledged",
     "Zero exceptions; safety broadcasts take absolute precedence over routine workflows",
     "All Clinic Staff", "Frontline Staff acknowledgment", "Logs BROADCAST_ACKNOWLEDGED_EVENT"),

    ("BRULE-045", "Shift Handover Dual Staff Digital Signature Mandate",
     "Staff shift rotation cannot be finalized without mutual digital signature from both outgoing and incoming staff members.",
     "Eliminates lost patient tokens and undocumented medication counts across shifts.",
     "Outgoing staff initiates shift handover checklist", "Outgoing user ID, incoming user ID, handover summary",
     "IF outgoing_signed == TRUE AND incoming_signed == TRUE THEN transition shift",
     "Shift handover certified; terminal credentials switched to incoming staff", "Handover incomplete; prior staff session remains legally accountable",
     "Single-staff clinics execute solo EOD closure rather than shift handover",
     "Frontline Staff", "Incoming and Outgoing Staff", "Logs SHIFT_HANDOVER_CERTIFIED"),

    ("BRULE-046", "Biometric & Geofenced Terminal Attendance Enforcement",
     "Staff login is permitted only from verified clinic workstations located within the registered facility geofence.",
     "Prevents proxy attendance and ensures medical personnel are physically present.",
     "Staff submits login credentials", "Workstation MAC/UUID, browser geolocation coordinates, clinic profile",
     "IF distance(terminal_gps, clinic_gps) <= 100 meters THEN permit login ELSE reject",
     "User authenticated with clinic location verified", "Login rejected with 'Out of Bounds' security warning",
     "Remote administrative accounts (ZHO, IT) exempted from physical geofence check",
     "Authentication Subsystem", "Facility Administrator", "Logs ATTENDANCE_GEOFENCE_VERIFIED"),

    ("BRULE-047", "Automatic Workstation Session Lock at 15 Minutes Inactivity",
     "Terminals left unattended for 15 consecutive minutes shall automatically lock the screen, requiring staff PIN re-entry.",
     "Protects open medical charts from unauthorized viewing by patients or visitors.",
     "Inactivity timer reaches 900 seconds", "Last detected keyboard, mouse, or touch input timestamp",
     "IF (NOW() - last_activity) >= 15m THEN lock UI screen; require 4-digit PIN",
     "Screen locked behind PIN dialog; ongoing unsaved clinical inputs preserved", "User cannot interact with medical records until PIN is re-entered",
     "Active video or telemetry stream does not prevent inactivity lock",
     "Client Application Engine", "Authenticated User", "Logs SESSION_INACTIVITY_LOCK_EVENT"),

    ("BRULE-048", "Role Privilege Escalation Hard-Stop Prevention",
     "Under no circumstances shall a non-medical role (DEO, Pharmacist, Lab Tech) be granted prescription signing or diagnosis authority.",
     "Protects patient safety and enforces medical practitioner licensing boundaries.",
     "User session attempts invocation of clinical prescription API", "User authenticated role token",
     "IF user.role != 'MEDICAL_OFFICER' THEN return HTTP 403 Forbidden; log security event",
     "Execution permitted only for verified Medical Officers with valid KMC registration", "Execution blocked; security alert dispatched to CISO",
     "Zero exceptions; delegation cannot bridge across licensed clinical practice boundaries",
     "Application Gateway", "System Administrator", "Logs PRIVILEGE_ESCALATION_BLOCKED"),

    ("BRULE-049", "Cold Chain Refrigerator Temperature Excursion Mandatory Escalation",
     "Any ILR refrigerator temperature reading outside +2C to +8C shall trigger an urgent alert to the Zonal Immunization Officer within 15 minutes.",
     "Guarantees vaccine potency and prevents administration of denatured biologics.",
     "Nurse logs daily temperature or digital sensor telemetry updates", "Temperature reading in Celsius",
     "IF temp < 2.0 OR temp > 8.0 THEN status = 'BREACH'; dispatch SMS/Email escalation",
     "Visual flashing alert displayed on nursing desk; notification dispatched to ZIO", "Cannot clear alert without logging corrective action note",
     "Minor transient opening excursion (<10 mins during restocking) must be annotated",
     "Staff Nurse / IoT Daemon", "Zonal Immunization Officer", "Logs COLD_CHAIN_BREACH_ALERT"),

    ("BRULE-050", "Mandatory Cryptographic WORM Chaining for All State Mutations",
     "Every clinical, pharmacy, and queue state mutation must be chained into an append-only WORM log with a verifiable SHA-256 hash.",
     "Guarantees absolute tamper evidence for all municipal healthcare transactions.",
     "Any database INSERT, UPDATE, or SOFT_DELETE transaction commits", "Transaction payload, prior log hash, timestamp",
     "current_hash = SHA256(prior_hash + timestamp + transaction_payload); write to Loki",
     "Audit record committed; cryptographic chain extended monotonically", "Transaction aborted if audit logging pipe is unreachable or fails",
     "Offline mode caches audit chain locally in Dexie.js for batch verification upon reconnection",
     "Database Audit Subsystem", "Chief Information Security Officer (CISO)", "Logs WORM_AUDIT_CHAIN_EXTENDED")
]
