#!/usr/bin/env python3
"""
builder_base.py
Base constructors, schemas, and helper utilities for assembling comprehensive
workflow datasets across all 25 primary workflows in Namma Clinic Platform.
"""

from typing import Dict, Any, List


def create_base_workflow(
    wf_id: str,
    wf_num: str,
    wf_name: str,
    wf_domain: str,
    exec_summary: Dict[str, str],
    objectives: List[Dict[str, str]],
    in_scope: List[Dict[str, str]],
    out_of_scope: List[Dict[str, str]],
    actors: List[Dict[str, str]],
    personas: List[Dict[str, str]],
    rbac_matrix: List[Dict[str, str]],
    preconditions: List[Dict[str, str]],
    triggers: List[Dict[str, str]],
    inputs: List[Dict[str, str]],
    outputs: Dict[str, Any],
    happy_path: List[Dict[str, str]],
    alternate_flows: List[Dict[str, Any]],
    exception_flows: List[Dict[str, str]],
    emergency_flow: Dict[str, str],
    states: List[Dict[str, str]],
    transitions: List[Dict[str, str]],
    decision_tables: List[Dict[str, Any]],
    validation_rules: List[Dict[str, str]],
    business_rules: List[Dict[str, str]],
    clinical_rules: List[Dict[str, str]],
    operational_rules: List[Dict[str, str]],
    security_controls: List[Dict[str, str]],
    privacy_controls: List[Dict[str, str]],
    offline_behavior: Dict[str, str],
    diagrams: Dict[str, str],
    data_flow_nodes: List[Dict[str, str]],
    failure_tree: List[Dict[str, str]],
    recovery_procedures: List[Dict[str, Any]],
    audit_events: List[Dict[str, str]],
    notifications: List[Dict[str, str]],
    planned_apis: List[Dict[str, Any]],
    planned_db: List[Dict[str, Any]],
    planned_ui: List[Dict[str, str]],
    backend_reqs: Dict[str, str],
    integrations: List[Dict[str, str]],
    reports: List[Dict[str, str]],
    analytics: List[Dict[str, str]],
    ai_reqs: Dict[str, str],
    stride_threats: List[Dict[str, str]],
    linddun_threats: List[Dict[str, str]],
    performance: Dict[str, str],
    availability: Dict[str, str],
    accessibility: Dict[str, str],
    localization: Dict[str, str],
    test_gates: List[Dict[str, str]],
    bdd_scenarios: List[Dict[str, Any]],
    acceptance_criteria: List[Dict[str, str]],
    dependencies: List[Dict[str, str]],
    critical_path: Dict[str, str],
    rollback_strategy: Dict[str, str],
    idempotency: Dict[str, str],
    concurrency: Dict[str, str],
    invariants: List[Dict[str, str]],
    observability: List[Dict[str, str]],
    runbook: Dict[str, str],
    sla_slo: List[Dict[str, str]],
    traceability: List[Dict[str, str]],
    open_questions: List[Dict[str, str]],
    assumptions: List[Dict[str, str]],
    risks: List[Dict[str, str]],
    change_impact: List[Dict[str, str]],
    definition_of_ready: List[Dict[str, str]],
    definition_of_done: List[Dict[str, str]],
    quality_checklist: List[Dict[str, Any]],
    related_workflows: List[Dict[str, str]] = None,
) -> Dict[str, Any]:
    """Assembles and verifies a complete 67-section workflow data object."""
    return {
        "id": wf_id,
        "num": wf_num,
        "name": wf_name,
        "domain": wf_domain,
        "exec_summary": exec_summary,
        "objectives": objectives,
        "in_scope": in_scope,
        "out_of_scope": out_of_scope,
        "actors": actors,
        "personas": personas,
        "rbac_matrix": rbac_matrix,
        "preconditions": preconditions,
        "triggers": triggers,
        "inputs": inputs,
        "outputs": outputs,
        "happy_path": happy_path,
        "alternate_flows": alternate_flows,
        "exception_flows": exception_flows,
        "emergency_flow": emergency_flow,
        "states": states,
        "transitions": transitions,
        "decision_tables": decision_tables,
        "validation_rules": validation_rules,
        "business_rules": business_rules,
        "clinical_rules": clinical_rules,
        "operational_rules": operational_rules,
        "security_controls": security_controls,
        "privacy_controls": privacy_controls,
        "offline_behavior": offline_behavior,
        "diagrams": diagrams,
        "data_flow_nodes": data_flow_nodes,
        "failure_tree": failure_tree,
        "recovery_procedures": recovery_procedures,
        "audit_events": audit_events,
        "notifications": notifications,
        "planned_apis": planned_apis,
        "planned_db": planned_db,
        "planned_ui": planned_ui,
        "backend_reqs": backend_reqs,
        "integrations": integrations,
        "reports": reports,
        "analytics": analytics,
        "ai_reqs": ai_reqs,
        "stride_threats": stride_threats,
        "linddun_threats": linddun_threats,
        "performance": performance,
        "availability": availability,
        "accessibility": accessibility,
        "localization": localization,
        "test_gates": test_gates,
        "bdd_scenarios": bdd_scenarios,
        "acceptance_criteria": acceptance_criteria,
        "dependencies": dependencies,
        "critical_path": critical_path,
        "rollback_strategy": rollback_strategy,
        "idempotency": idempotency,
        "concurrency": concurrency,
        "invariants": invariants,
        "observability": observability,
        "runbook": runbook,
        "sla_slo": sla_slo,
        "traceability": traceability,
        "open_questions": open_questions,
        "assumptions": assumptions,
        "risks": risks,
        "change_impact": change_impact,
        "definition_of_ready": definition_of_ready,
        "definition_of_done": definition_of_done,
        "quality_checklist": quality_checklist,
        "related_workflows": related_workflows or [],
    }
