#!/usr/bin/env python3
"""
workflow_metadata.py
Metadata definition and registry for all 25 primary workflows in Namma Clinic Platform.
"""

WORKFLOW_SPECS = [
    {
        "id": "WF-001",
        "num": "01",
        "file": "01-master-clinic-workflow.md",
        "name": "Master Clinic Day Operational Workflow",
        "domain": "Clinic Operations & Daily Care Coordination",
        "summary": "Governs the complete daily operating cycle of a Namma Clinic from 07:30 facility unlock, staff muster, offline sync verification, queue initialization, continuous multi-stage patient throughput (Registration -> Triage -> Consultation -> Lab -> Pharmacy), midday shift handover, to 20:00 day-end financial/clinical reconciliation and cryptographic ledger synchronization.",
        "primary_actors": ["Clinic Coordinator", "Staff Nurse", "Medical Officer (Doctor)", "Pharmacist", "Lab Technician"],
        "criticality": "Mission Critical (P1)",
        "offline_tier": "Tier 1 - Full Autonomous Day Operations with Eventual Consistency",
        "abdm_role": "Master Orchestrator of ABDM Milestone 1, 2, and 3 Touchpoints",
        "upstream_objectives": ["OBJECTIVE-001", "OBJECTIVE-002", "OBJECTIVE-005", "OBJECTIVE-012"],
        "upstream_scopes": ["SCOPE-001", "SCOPE-003", "INSCOPE-001", "INSCOPE-002", "INSCOPE-005"],
        "upstream_personas": ["PERSONA-001", "PERSONA-002", "PERSONA-003", "PERSONA-004", "PERSONA-005"],
        "upstream_roles": ["ROLE-001", "ROLE-002", "ROLE-003", "ROLE-004", "ROLE-005"],
        "upstream_reqs": ["BR-001", "BR-002", "FR-001", "FR-010", "NFR-001", "BRULE-001", "CR-001", "OR-001", "SECR-001", "PRIV-001", "PERF-001", "AVAIL-001", "LOC-001", "A11Y-001", "OFF-001", "REP-001", "ANL-001"],
    },
    {
        "id": "WF-002",
        "num": "02",
        "file": "02-login-authentication-workflow.md",
        "name": "Staff Login, Multi-Factor Authentication & Session Management Workflow",
        "domain": "Identity, Access Management & Cryptographic Session Security",
        "summary": "Specifies user authentication for clinic personnel, covering RBAC credential validation, TOTP/SMS MFA challenge, emergency offline PIN verification using locally salted scrypt hashes, biometric token exchange, session inactivity timeout (15 min), concurrent device revocation, and brute-force lockout defenses.",
        "primary_actors": ["All Clinic Staff (Doctor, Nurse, Pharmacist, Lab Tech, Admin)"],
        "criticality": "Security Critical (P0)",
        "offline_tier": "Tier 1 - Cached Offline Public Key & Scrypt PIN Verification",
        "abdm_role": "HPR (Healthcare Professional Registry) Token Verification & Bridge Auth",
        "upstream_objectives": ["OBJECTIVE-003", "OBJECTIVE-009", "OBJECTIVE-014"],
        "upstream_scopes": ["SCOPE-002", "INSCOPE-003", "INSCOPE-015"],
        "upstream_personas": ["PERSONA-001", "PERSONA-002", "PERSONA-003", "PERSONA-004", "PERSONA-006"],
        "upstream_roles": ["ROLE-001", "ROLE-002", "ROLE-003", "ROLE-004", "ROLE-006"],
        "upstream_reqs": ["BR-003", "FR-002", "NFR-002", "BRULE-002", "CR-002", "OR-002", "SECR-002", "PRIV-002", "PERF-002", "AVAIL-002", "LOC-002", "A11Y-002", "OFF-002", "REP-002", "ANL-002"],
    },
    {
        "id": "WF-003",
        "num": "03",
        "file": "03-patient-registration-workflow.md",
        "name": "Patient Registration, ABHA Creation & Demographic Intake Workflow",
        "domain": "Citizen Identity, Demographics & Health ID Generation",
        "summary": "Drives the intake of new citizens into the Namma Clinic ecosystem, capturing bilingual demographics (English/Kannada), contact numbers, disability markers, Aadhaar/OTP or Demographics-based ABHA generation, local UHID minting, guardian linking for pediatric patients, and provisional registration during network dropouts.",
        "primary_actors": ["Registration Nurse", "Registration Clerk", "Citizen / Patient", "ASHA Worker"],
        "criticality": "Operationally Critical (P1)",
        "offline_tier": "Tier 1 - Local Provisional UHID Minting with Hierarchical Namespace Prefix",
        "abdm_role": "ABDM M1 - ABHA Number & Address Creation via UIDAI / CoWIN Bridges",
        "upstream_objectives": ["OBJECTIVE-001", "OBJECTIVE-004", "OBJECTIVE-011"],
        "upstream_scopes": ["SCOPE-001", "INSCOPE-002", "INSCOPE-006"],
        "upstream_personas": ["PERSONA-001", "PERSONA-007", "PERSONA-008", "PERSONA-009"],
        "upstream_roles": ["ROLE-001", "ROLE-007", "ROLE-008"],
        "upstream_reqs": ["BR-004", "FR-003", "NFR-003", "BRULE-003", "CR-003", "OR-003", "SECR-003", "PRIV-003", "PERF-003", "AVAIL-003", "LOC-003", "A11Y-003", "OFF-003", "REP-003", "ANL-003"],
    },
    {
        "id": "WF-004",
        "num": "04",
        "file": "04-patient-search-workflow.md",
        "name": "Patient Search, Multi-Parametric Lookup & Verification Workflow",
        "domain": "Patient Identification & Record Retrieval",
        "summary": "Establishes multi-factor search heuristics to rapidly locate patient records using Kannada/English phonetic match (Soundex/Metaphone), partial mobile number, ABHA ID QR scanning, barcoded physical clinic cards, and birth year range filters, eliminating duplicate registrations.",
        "primary_actors": ["Registration Nurse", "Staff Nurse", "Medical Officer", "Pharmacist"],
        "criticality": "Operationally Critical (P1)",
        "offline_tier": "Tier 1 - Search against Local SQLite/IndexedDB Full-Text Index with Trie Prefix",
        "abdm_role": "ABDM M1 - QR Code Scan & Share Callback Authentication",
        "upstream_objectives": ["OBJECTIVE-001", "OBJECTIVE-006"],
        "upstream_scopes": ["SCOPE-001", "INSCOPE-002"],
        "upstream_personas": ["PERSONA-001", "PERSONA-002", "PERSONA-007"],
        "upstream_roles": ["ROLE-001", "ROLE-002", "ROLE-007"],
        "upstream_reqs": ["BR-005", "FR-004", "NFR-004", "BRULE-004", "CR-004", "OR-004", "SECR-004", "PRIV-004", "PERF-004", "AVAIL-004", "LOC-004", "A11Y-004", "OFF-004", "REP-004", "ANL-004"],
    },
    {
        "id": "WF-005",
        "num": "05",
        "file": "05-repeat-patient-workflow.md",
        "name": "Repeat Patient Revisit & Longitudinal Episode Linking Workflow",
        "domain": "Continuity of Care & Chronic Disease Cohort Management",
        "summary": "Processes return visits of registered citizens, retrieving longitudinal clinical timelines, active NCD hypertension/diabetes treatment regimens, previous drug adverse reactions, linking new encounters to existing master episodes, and flagging overdue clinical investigations.",
        "primary_actors": ["Registration Nurse", "Triage Nurse", "Medical Officer"],
        "criticality": "Clinically Significant (P1)",
        "offline_tier": "Tier 1 - Retrieval of Locally Cached Historical Episodes (Last 90 Days)",
        "abdm_role": "ABDM M2 - Fetching External Records via ABDM Consent Manager",
        "upstream_objectives": ["OBJECTIVE-002", "OBJECTIVE-007"],
        "upstream_scopes": ["SCOPE-003", "INSCOPE-004"],
        "upstream_personas": ["PERSONA-001", "PERSONA-003", "PERSONA-007"],
        "upstream_roles": ["ROLE-001", "ROLE-003", "ROLE-007"],
        "upstream_reqs": ["BR-006", "FR-005", "NFR-005", "BRULE-005", "CR-005", "OR-005", "SECR-005", "PRIV-005", "PERF-005", "AVAIL-005", "LOC-005", "A11Y-005", "OFF-005", "REP-005", "ANL-005"],
    },
    {
        "id": "WF-006",
        "num": "06",
        "file": "06-consent-workflow.md",
        "name": "Informed Clinical & Digital Health Consent Workflow",
        "domain": "Consent Governance, DPDP Act Compliance & ABDM Consent Artifacts",
        "summary": "Governs the capture, verification, enforcement, and revocation of digital consent across all care stages. Enforces DPDP Act 2023 principles, purpose limitation, bilingual notice presentation (Kannada/English), emergency bypass exceptions, and ABDM Consent Manager integration for external health data exchange.",
        "primary_actors": ["Citizen / Patient", "Legal Guardian", "Staff Nurse", "Medical Officer"],
        "criticality": "Legal & Privacy Critical (P0)",
        "offline_tier": "Tier 2 - Local Digital Signature Capture & Queued Consent Artifact Sync",
        "abdm_role": "ABDM M2/M3 - HIU/HIP Consent Artefact Handling & Verification",
        "upstream_objectives": ["OBJECTIVE-009", "OBJECTIVE-014"],
        "upstream_scopes": ["SCOPE-005", "INSCOPE-012"],
        "upstream_personas": ["PERSONA-001", "PERSONA-007", "PERSONA-008"],
        "upstream_roles": ["ROLE-001", "ROLE-002", "ROLE-008"],
        "upstream_reqs": ["BR-007", "FR-006", "NFR-006", "BRULE-006", "CR-006", "OR-006", "SECR-006", "PRIV-006", "PERF-006", "AVAIL-006", "LOC-006", "A11Y-006", "OFF-006", "REP-006", "ANL-006"],
    },
    {
        "id": "WF-007",
        "num": "07",
        "file": "07-token-generation-workflow.md",
        "name": "Token Issuance, Priority Tagging & Queue Entry Workflow",
        "domain": "Patient Flow Management & Facility Load Balancing",
        "summary": "Handles the issuance of physical thermal print tokens and SMS-linked virtual tokens upon registration. Automatically tags priority categories (Emergency Red, Antenatal Care, Senior Citizen 65+, Pediatric <5, General), assigns department-specific prefix codes, and calculates dynamic estimated wait times.",
        "primary_actors": ["Registration Nurse", "Queue Kiosk Attendant", "Citizen / Patient"],
        "criticality": "Operationally Critical (P1)",
        "offline_tier": "Tier 1 - Deterministic Node-Prefix Token Generator with Collision-Free ID Space",
        "abdm_role": "ABDM M1 - Token Linking to Scan-and-Share Token Pools",
        "upstream_objectives": ["OBJECTIVE-001", "OBJECTIVE-005"],
        "upstream_scopes": ["SCOPE-001", "INSCOPE-002"],
        "upstream_personas": ["PERSONA-001", "PERSONA-007", "PERSONA-008"],
        "upstream_roles": ["ROLE-001", "ROLE-007"],
        "upstream_reqs": ["BR-008", "FR-007", "NFR-007", "BRULE-007", "CR-007", "OR-007", "SECR-007", "PRIV-007", "PERF-007", "AVAIL-007", "LOC-007", "A11Y-007", "OFF-007", "REP-007", "ANL-007"],
    },
    {
        "id": "WF-008",
        "num": "08",
        "file": "08-queue-workflow.md",
        "name": "Dynamic Multi-Room Queue Orchestration & Display Workflow",
        "domain": "Patient Flow, Display Boards & Station Handovers",
        "summary": "Orchestrates patient routing across Triage, Consultation Rooms, Point-of-Care Laboratory, and Pharmacy Dispensing windows. Powers real-time digital signage displays (WebSockets/SSE), audio chimes in Kannada/English, no-show/hold states, recall mechanics, and clinician load balancing.",
        "primary_actors": ["Staff Nurse", "Medical Officer", "Pharmacist", "Lab Tech", "Citizen"],
        "criticality": "Operationally Critical (P1)",
        "offline_tier": "Tier 1 - Local Area Network (mDNS/WebSocket) Queue Sync across Clinic Terminals",
        "abdm_role": "Syncs Encounter Progression Milestones with Central Portal",
        "upstream_objectives": ["OBJECTIVE-001", "OBJECTIVE-005"],
        "upstream_scopes": ["SCOPE-001", "INSCOPE-002"],
        "upstream_personas": ["PERSONA-001", "PERSONA-002", "PERSONA-003", "PERSONA-004", "PERSONA-007"],
        "upstream_roles": ["ROLE-001", "ROLE-002", "ROLE-003", "ROLE-004"],
        "upstream_reqs": ["BR-009", "FR-008", "NFR-008", "BRULE-008", "CR-008", "OR-008", "SECR-008", "PRIV-008", "PERF-008", "AVAIL-008", "LOC-008", "A11Y-008", "OFF-008", "REP-008", "ANL-008"],
    },
    {
        "id": "WF-009",
        "num": "09",
        "file": "09-triage-workflow.md",
        "name": "Nursing Triage, Vital Signs & Clinical Acuity Assessment Workflow",
        "domain": "Clinical Assessment, Triage Protocols & Early Deterioration Detection",
        "summary": "Governs the capture and validation of physiological vital signs (Pulse, Blood Pressure, SpO2, Respiratory Rate, Temperature, Blood Glucose, Height/Weight/BMI) and computes modified early warning scores (MEWS/PEWS). Categorizes patients into Green (Standard), Yellow (Urgent), or Red (Resuscitation/Emergency).",
        "primary_actors": ["Staff Nurse", "ANM (Auxiliary Nurse Midwife)", "Medical Officer"],
        "criticality": "Life Safety & Clinically Critical (P0)",
        "offline_tier": "Tier 1 - Complete Local Vital Sign Capture, Validation & Acuity Computation",
        "abdm_role": "ABDM M2 - Encapsulates Vitals in FHIR Observation Resources",
        "upstream_objectives": ["OBJECTIVE-002", "OBJECTIVE-008"],
        "upstream_scopes": ["SCOPE-003", "INSCOPE-005"],
        "upstream_personas": ["PERSONA-001", "PERSONA-002"],
        "upstream_roles": ["ROLE-001", "ROLE-002"],
        "upstream_reqs": ["BR-010", "FR-009", "NFR-009", "BRULE-009", "CR-009", "OR-009", "SECR-009", "PRIV-009", "PERF-009", "AVAIL-009", "LOC-009", "A11Y-009", "OFF-009", "REP-009", "ANL-009"],
    },
    {
        "id": "WF-010",
        "num": "10",
        "file": "10-danger-alert-workflow.md",
        "name": "Danger Sign Detection, Critical Value Alert & Emergency Escalation Workflow",
        "domain": "Emergency Clinical Alerting & Rapid Response Coordination",
        "summary": "Triggers immediate visual and audible broadcast alerts upon vital sign threshold violations, pediatric danger signs (convulsions, chest indrawing, inability to drink), maternal hemorrhage signs, or laboratory panic values. Preempts all queues, summons the Medical Officer, and prepares emergency stabilization trays.",
        "primary_actors": ["Staff Nurse", "Medical Officer", "Emergency Transport Driver (108)", "Pharmacist"],
        "criticality": "Life Safety Critical (P0)",
        "offline_tier": "Tier 1 - Instant Local Visual/Auditory Alarm on Clinic LAN Independent of Cloud",
        "abdm_role": "Flags Encounter as Emergency Episode in ABDM Metadata",
        "upstream_objectives": ["OBJECTIVE-002", "OBJECTIVE-008", "OBJECTIVE-013"],
        "upstream_scopes": ["SCOPE-003", "INSCOPE-005", "INSCOPE-014"],
        "upstream_personas": ["PERSONA-001", "PERSONA-002", "PERSONA-007"],
        "upstream_roles": ["ROLE-001", "ROLE-002"],
        "upstream_reqs": ["BR-011", "FR-010", "NFR-010", "BRULE-010", "CR-010", "OR-010", "SECR-010", "PRIV-010", "PERF-010", "AVAIL-010", "LOC-010", "A11Y-010", "OFF-010", "REP-010", "ANL-010"],
    },
    {
        "id": "WF-011",
        "num": "11",
        "file": "11-doctor-consultation-workflow.md",
        "name": "Doctor Clinical Consultation, SOAP Documentation & CDSS Advisory Workflow",
        "domain": "Outpatient Clinical Care, Diagnosis & Clinical Decision Support",
        "summary": "Governs the primary outpatient medical encounter. Provides structured SOAP (Subjective, Objective, Assessment, Plan) clinical entry, ICD-10 / SNOMED CT terminology assistance, advisory Clinical Decision Support (CDSS) alerts without overriding clinician autonomy, order entry, and encounter sign-off.",
        "primary_actors": ["Medical Officer (Doctor)", "Citizen / Patient", "Staff Nurse"],
        "criticality": "Clinically Critical (P0)",
        "offline_tier": "Tier 1 - Full Offline Clinical Documentation with Local Differential Cache",
        "abdm_role": "ABDM M2 - FHIR DiagnosticReport, Condition, and ClinicalEncounter Composition",
        "upstream_objectives": ["OBJECTIVE-002", "OBJECTIVE-006", "OBJECTIVE-010"],
        "upstream_scopes": ["SCOPE-003", "INSCOPE-004", "INSCOPE-007"],
        "upstream_personas": ["PERSONA-002", "PERSONA-007"],
        "upstream_roles": ["ROLE-002"],
        "upstream_reqs": ["BR-012", "FR-011", "NFR-011", "BRULE-011", "CR-011", "OR-011", "SECR-011", "PRIV-011", "PERF-011", "AVAIL-011", "LOC-011", "A11Y-011", "OFF-011", "REP-011", "ANL-011"],
    },
    {
        "id": "WF-012",
        "num": "12",
        "file": "12-prescription-workflow.md",
        "name": "Electronic Prescription, Drug Interaction & Safety Verification Workflow",
        "domain": "Pharmacotherapy, Clinical Safety & Digital Prescribing",
        "summary": "Drives the authoring of digital prescriptions against the Karnataka Essential Medicines List (EML). Validates dosage, frequency, route, duration, food relationships in Kannada/English, executes real-time drug-drug and drug-allergy interaction checks, prevents therapeutic duplication, and cryptographically signs orders.",
        "primary_actors": ["Medical Officer", "Pharmacist", "Citizen / Patient"],
        "criticality": "Clinically Critical (P0)",
        "offline_tier": "Tier 1 - Local EML Formulary Database with In-Memory Drug Interaction Matrix",
        "abdm_role": "ABDM M2 - FHIR MedicationRequest Resource Generation with SNOMED/WHO-DD Codes",
        "upstream_objectives": ["OBJECTIVE-002", "OBJECTIVE-006", "OBJECTIVE-010"],
        "upstream_scopes": ["SCOPE-003", "INSCOPE-007"],
        "upstream_personas": ["PERSONA-002", "PERSONA-003", "PERSONA-007"],
        "upstream_roles": ["ROLE-002", "ROLE-003"],
        "upstream_reqs": ["BR-013", "FR-012", "NFR-012", "BRULE-012", "CR-012", "OR-012", "SECR-012", "PRIV-012", "PERF-012", "AVAIL-012", "LOC-012", "A11Y-012", "OFF-012", "REP-012", "ANL-012"],
    },
    {
        "id": "WF-013",
        "num": "13",
        "file": "13-pharmacy-dispensing-workflow.md",
        "name": "Pharmacy Dispensing, FEFO Inventory Allocation & Patient Counseling Workflow",
        "domain": "Pharmacy Operations, Stock Decrement & Medication Adherence",
        "summary": "Governs the pharmacy counter operations: digital prescription receipt, First-Expiry First-Out (FEFO) batch allocation, barcoded verification of physical packs, partial dispensing handling during stock outs, bilingual verbal counseling in Kannada, physical printout generation, and atomic inventory decrements.",
        "primary_actors": ["Pharmacist", "Pharmacy Assistant", "Citizen / Patient"],
        "criticality": "Operationally & Clinically Critical (P1)",
        "offline_tier": "Tier 1 - Local Atomic Batch Reservation & Decrement with Optimistic Locking",
        "abdm_role": "ABDM M2 - FHIR MedicationDispense Event Generation",
        "upstream_objectives": ["OBJECTIVE-005", "OBJECTIVE-010"],
        "upstream_scopes": ["SCOPE-004", "INSCOPE-008"],
        "upstream_personas": ["PERSONA-003", "PERSONA-007"],
        "upstream_roles": ["ROLE-003"],
        "upstream_reqs": ["BR-014", "FR-013", "NFR-013", "BRULE-013", "CR-013", "OR-013", "SECR-013", "PRIV-013", "PERF-013", "AVAIL-013", "LOC-013", "A11Y-013", "OFF-013", "REP-013", "ANL-013"],
    },
    {
        "id": "WF-014",
        "num": "14",
        "file": "14-stock-replenishment-workflow.md",
        "name": "Pharmacy Stock Replenishment, Indenting & Cold-Chain Inventory Control Workflow",
        "domain": "Supply Chain, Inventory Auditing & Warehouse Logistics",
        "summary": "Controls pharmacy stock levels, reorder threshold triggers, electronic indent transmission to the BBMP Central Warehouse / KSDL, receipt verification, batch-level cold-chain tracking (2-8 C vaccines and insulins), discrepancy reporting, quarantine of damaged/expired medicines, and stock reconciliation.",
        "primary_actors": ["Pharmacist", "District Warehouse Logistics Officer", "Medical Officer"],
        "criticality": "Logistically Critical (P1)",
        "offline_tier": "Tier 2 - Offline Indent Staging & Local Physical Inventory Audit Ledger",
        "abdm_role": "Integrates with DVDMS (e-Aushadhi) Supply Chain Gateway",
        "upstream_objectives": ["OBJECTIVE-005", "OBJECTIVE-012"],
        "upstream_scopes": ["SCOPE-004", "INSCOPE-008"],
        "upstream_personas": ["PERSONA-003", "PERSONA-006"],
        "upstream_roles": ["ROLE-003", "ROLE-006"],
        "upstream_reqs": ["BR-015", "FR-014", "NFR-014", "BRULE-014", "CR-014", "OR-014", "SECR-014", "PRIV-014", "PERF-014", "AVAIL-014", "LOC-014", "A11Y-014", "OFF-014", "REP-014", "ANL-014"],
    },
    {
        "id": "WF-015",
        "num": "15",
        "file": "15-laboratory-workflow.md",
        "name": "Point-of-Care Laboratory Testing, Barcoding & Panic Value Alert Workflow",
        "domain": "Diagnostic Services, Specimen Tracking & Panic Escalation",
        "summary": "Covers point-of-care laboratory diagnostic workflows: test order reception, barcoded sample tube labeling, rapid diagnostic kit / dry chemistry analyzer execution, dual-entry result verification, automatic reference range checking, panic value critical alerting, and e-Signature delivery to the doctor's screen.",
        "primary_actors": ["Laboratory Technician", "Medical Officer", "Staff Nurse"],
        "criticality": "Clinically Critical (P1)",
        "offline_tier": "Tier 1 - Full Local Specimen Tracking & Device Result Entry",
        "abdm_role": "ABDM M2 - FHIR DiagnosticReport & Specimen Resource Bundling",
        "upstream_objectives": ["OBJECTIVE-002", "OBJECTIVE-008"],
        "upstream_scopes": ["SCOPE-003", "INSCOPE-009"],
        "upstream_personas": ["PERSONA-004", "PERSONA-002"],
        "upstream_roles": ["ROLE-004", "ROLE-002"],
        "upstream_reqs": ["BR-016", "FR-015", "NFR-015", "BRULE-015", "CR-015", "OR-015", "SECR-015", "PRIV-015", "PERF-015", "AVAIL-015", "LOC-015", "A11Y-015", "OFF-015", "REP-015", "ANL-015"],
    },
    {
        "id": "WF-016",
        "num": "16",
        "file": "16-referral-workflow.md",
        "name": "Clinical Referral, Higher Center Escalation & Ambulance Transfer Workflow",
        "domain": "Emergency Escalation, Inter-Facility Care Coordination & 108 Dispatch",
        "summary": "Coordinates patient referrals to secondary (Taluk Hospital/General Hospital) and tertiary medical centers (Bowring, Victoria, KC General). Generates standardized e-Referral summaries, dispatches 108 Emergency Ambulance with real-time GPS telemetry, transfers vital sign streams, and tracks referral loop closure.",
        "primary_actors": ["Medical Officer", "Staff Nurse", "108 Ambulance Paramedic", "Higher Center Receiving Doctor"],
        "criticality": "Life Safety Critical (P0)",
        "offline_tier": "Tier 2 - Offline Encrypted QR Code Referral Slip Printing for Manual Transport",
        "abdm_role": "ABDM M3 - Longitudinal Health Record Push via ABDM Health Information Exchange",
        "upstream_objectives": ["OBJECTIVE-002", "OBJECTIVE-013"],
        "upstream_scopes": ["SCOPE-003", "INSCOPE-010"],
        "upstream_personas": ["PERSONA-002", "PERSONA-007"],
        "upstream_roles": ["ROLE-002", "ROLE-001"],
        "upstream_reqs": ["BR-017", "FR-016", "NFR-016", "BRULE-016", "CR-016", "OR-016", "SECR-016", "PRIV-016", "PERF-016", "AVAIL-016", "LOC-016", "A11Y-016", "OFF-016", "REP-016", "ANL-016"],
    },
    {
        "id": "WF-017",
        "num": "17",
        "file": "17-follow-up-workflow.md",
        "name": "NCD Follow-Up Scheduling, Chronic Disease Recall & Defaulter Tracking Workflow",
        "domain": "Preventive Health, Chronic Disease Continuity & Community Outreach",
        "summary": "Manages appointment scheduling for chronic disease management (Hypertension, Diabetes Mellitus, Epilepsy, TB DOTS), generates automated multi-lingual reminders, tracks appointment defaulters (+7 days overdue), triggers ASHA worker community home visit tasks, and documents treatment adherence.",
        "primary_actors": ["Staff Nurse", "Medical Officer", "ASHA Worker", "Citizen / Patient"],
        "criticality": "Public Health Critical (P1)",
        "offline_tier": "Tier 1 - Local Follow-Up Ledger & Offline ASHA Task List Export",
        "abdm_role": "Integrates with National NCD Portal and Reproductive Child Health (RCH) Portals",
        "upstream_objectives": ["OBJECTIVE-002", "OBJECTIVE-007"],
        "upstream_scopes": ["SCOPE-003", "INSCOPE-011"],
        "upstream_personas": ["PERSONA-001", "PERSONA-007", "PERSONA-008"],
        "upstream_roles": ["ROLE-001", "ROLE-002"],
        "upstream_reqs": ["BR-018", "FR-017", "NFR-017", "BRULE-017", "CR-017", "OR-017", "SECR-017", "PRIV-017", "PERF-017", "AVAIL-017", "LOC-017", "A11Y-017", "OFF-017", "REP-017", "ANL-017"],
    },
    {
        "id": "WF-018",
        "num": "18",
        "file": "18-notification-workflow.md",
        "name": "Omnichannel Patient & Staff Notification, Alerting & Communication Workflow",
        "domain": "Multi-Channel Communication, SMS Gateways & Voice Announcements",
        "summary": "Controls transactional messaging pipelines: SMS gateway integration, WhatsApp Business API notifications, automated IVR calls in Kannada, and local clinic audio chimes. Enforces DND regulatory compliance, exponential backoff retries, failover channel routing, and delivery receipt auditing.",
        "primary_actors": ["Notification Service Worker", "Citizen / Patient", "Clinic Staff"],
        "criticality": "Operationally Significant (P2)",
        "offline_tier": "Tier 3 - Local Queueing with Cloud Gateway Execution upon Reconnection",
        "abdm_role": "Transmits ABHA OTP and Health Information Exchange Notice Notifications",
        "upstream_objectives": ["OBJECTIVE-001", "OBJECTIVE-005"],
        "upstream_scopes": ["SCOPE-001", "INSCOPE-013"],
        "upstream_personas": ["PERSONA-001", "PERSONA-007"],
        "upstream_roles": ["ROLE-001", "ROLE-006"],
        "upstream_reqs": ["BR-019", "FR-018", "NFR-018", "BRULE-018", "CR-018", "OR-018", "SECR-018", "PRIV-018", "PERF-018", "AVAIL-018", "LOC-018", "A11Y-018", "OFF-018", "REP-018", "ANL-018"],
    },
    {
        "id": "WF-019",
        "num": "19",
        "file": "19-grievance-workflow.md",
        "name": "Citizen Grievance Redressal, Feedback & SLA Escalation Workflow",
        "domain": "Citizen Charter, Public Accountability & Service Quality Assurance",
        "summary": "Provides multi-modal grievance lodging (Touchscreen Kiosk, QR code poster, Helpline, Desk Form), classifies complaints (wait times, medication stockout, staff demeanor, hygiene), routes tickets to the Medical Officer or BBMP Zonal Health Officer under strict SLAs (24h/72h), and reports resolution to the citizen.",
        "primary_actors": ["Citizen / Patient", "Clinic Coordinator", "Zonal Health Officer", "Chief Health Officer"],
        "criticality": "Governance & Accountability (P1)",
        "offline_tier": "Tier 2 - Offline Local Storage of Grievance Tickets with Signed Hash Verification",
        "abdm_role": "Integrates with BBMP Sahaaya Grievance Portal & National Health Portal",
        "upstream_objectives": ["OBJECTIVE-005", "OBJECTIVE-012"],
        "upstream_scopes": ["SCOPE-005", "INSCOPE-012"],
        "upstream_personas": ["PERSONA-007", "PERSONA-006"],
        "upstream_roles": ["ROLE-006", "ROLE-005"],
        "upstream_reqs": ["BR-020", "FR-019", "NFR-019", "BRULE-019", "CR-019", "OR-019", "SECR-019", "PRIV-019", "PERF-019", "AVAIL-019", "LOC-019", "A11Y-019", "OFF-019", "REP-019", "ANL-019"],
    },
    {
        "id": "WF-020",
        "num": "20",
        "file": "20-audit-workflow.md",
        "name": "Cryptographic Audit Trail, Immutable Logging & Tamper Detection Workflow",
        "domain": "Security Auditing, Non-Repudiation & Regulatory Compliance",
        "summary": "Implements an immutable, append-only cryptographic event ledger for every state transition, PHI view, prescription signature, and emergency override across the platform. Generates SHA-256 Merkle tree checkpoints, triggers tamper alarms upon hash breaks, and exports verifiable compliance bundles.",
        "primary_actors": ["Security Audit Daemon", "Data Protection Officer", "System Administrator"],
        "criticality": "Security & Legal Critical (P0)",
        "offline_tier": "Tier 1 - Local Append-Only SQLite Cryptographic Audit Chain with Pre-Shared HMAC",
        "abdm_role": "ABDM Security Baseline Compliance - WORM (Write Once Read Many) Audit Trails",
        "upstream_objectives": ["OBJECTIVE-009", "OBJECTIVE-014"],
        "upstream_scopes": ["SCOPE-005", "INSCOPE-015"],
        "upstream_personas": ["PERSONA-006"],
        "upstream_roles": ["ROLE-006"],
        "upstream_reqs": ["BR-021", "FR-020", "NFR-020", "BRULE-020", "CR-020", "OR-020", "SECR-020", "PRIV-020", "PERF-020", "AVAIL-020", "LOC-020", "A11Y-020", "OFF-020", "REP-020", "ANL-020"],
    },
    {
        "id": "WF-021",
        "num": "21",
        "file": "21-analytics-workflow.md",
        "name": "Clinical Analytics, Syndromic Surveillance & Population Health Reporting Workflow",
        "domain": "Public Health Intelligence, Epidemiology & Operational KPIs",
        "summary": "Aggregates de-identified clinical and operational event streams into real-time analytical cubes. Computes epidemiological syndromic surveillance spikes (fever clusters, acute diarrheal disease, dengue signals) for the Integrated Disease Surveillance Programme (IDSP), tracks clinic KPIs, and generates automated daily health bulletins.",
        "primary_actors": ["Zonal Epidemiologist", "Chief Health Officer", "Medical Officer", "Data Analyst"],
        "criticality": "Epidemiological & Operational Critical (P1)",
        "offline_tier": "Tier 2 - Local Daily Aggregation & Batch Telemetry Export upon Cloud Connection",
        "abdm_role": "Feeds Aggregated De-Identified Telemetry into National Health Surveillance Datasets",
        "upstream_objectives": ["OBJECTIVE-005", "OBJECTIVE-012"],
        "upstream_scopes": ["SCOPE-004", "INSCOPE-016"],
        "upstream_personas": ["PERSONA-005", "PERSONA-006"],
        "upstream_roles": ["ROLE-005", "ROLE-006"],
        "upstream_reqs": ["BR-022", "FR-021", "NFR-021", "BRULE-021", "CR-021", "OR-021", "SECR-021", "PRIV-021", "PERF-021", "AVAIL-021", "LOC-021", "A11Y-021", "OFF-021", "REP-021", "ANL-021"],
    },
    {
        "id": "WF-022",
        "num": "22",
        "file": "22-offline-workflow.md",
        "name": "Autonomous Offline Edge Operation, Local Storage & Network Resilience Workflow",
        "domain": "Edge Computing, Local-First Architecture & Network Fault Tolerance",
        "summary": "Establishes full operational autonomy when wide-area Internet connectivity is severed. Maintains local clinic LAN operations, authenticates users via locally salted cryptographic credentials, writes mutations to an encrypted persistent IndexedDB/SQLite queue, manages storage quotas, and provides seamless degraded mode indicators.",
        "primary_actors": ["Edge Sync Engine", "Staff Nurse", "Medical Officer", "Pharmacist"],
        "criticality": "Platform Resilience Critical (P0)",
        "offline_tier": "Tier 1 - Master Core Architecture for Entire Offline Operation Suite",
        "abdm_role": "Stages Outbound ABDM Transactions in Offline Cryptographic Envelope",
        "upstream_objectives": ["OBJECTIVE-003", "OBJECTIVE-011"],
        "upstream_scopes": ["SCOPE-002", "INSCOPE-017"],
        "upstream_personas": ["PERSONA-001", "PERSONA-002", "PERSONA-003", "PERSONA-006"],
        "upstream_roles": ["ROLE-001", "ROLE-002", "ROLE-003", "ROLE-006"],
        "upstream_reqs": ["BR-023", "FR-022", "NFR-022", "BRULE-022", "CR-022", "OR-022", "SECR-022", "PRIV-022", "PERF-022", "AVAIL-022", "LOC-022", "A11Y-022", "OFF-022", "REP-022", "ANL-022"],
    },
    {
        "id": "WF-023",
        "num": "23",
        "file": "23-sync-conflict-workflow.md",
        "name": "Bidirectional Synchronization, Conflict Resolution & Merkle Ledger Workflow",
        "domain": "Data Consistency, Distributed Replay & Conflict Arbitration",
        "summary": "Governs the deterministic replay and reconciliation of queued offline mutations upon connectivity restoration. Uses Lamport timestamps and vector clocks to detect concurrent edits, executes deterministic 3-way merge rules, enforces clinician authority invariants, isolates non-resolvable conflicts into dead-letter queues, and audits merges.",
        "primary_actors": ["Cloud Sync Coordinator", "Edge Replay Engine", "Medical Officer", "System Admin"],
        "criticality": "Data Integrity Critical (P0)",
        "offline_tier": "Tier 1 - Master Synchronization & Convergence Gateway",
        "abdm_role": "Reconciles Local Encounter Records with ABDM Central Repository",
        "upstream_objectives": ["OBJECTIVE-003", "OBJECTIVE-011"],
        "upstream_scopes": ["SCOPE-002", "INSCOPE-017"],
        "upstream_personas": ["PERSONA-002", "PERSONA-006"],
        "upstream_roles": ["ROLE-002", "ROLE-006"],
        "upstream_reqs": ["BR-024", "FR-023", "NFR-023", "BRULE-023", "CR-023", "OR-023", "SECR-023", "PRIV-023", "PERF-023", "AVAIL-023", "LOC-023", "A11Y-023", "OFF-023", "REP-023", "ANL-023"],
    },
    {
        "id": "WF-024",
        "num": "24",
        "file": "24-ABDM-workflow.md",
        "name": "Ayushman Bharat Digital Mission (ABDM) Gateway & FHIR Interoperability Workflow",
        "domain": "National Digital Health Interoperability & Health Information Exchange",
        "summary": "Specifies deep interoperability with India's Ayushman Bharat Digital Mission (ABDM). Implements M1 (ABHA verification, creation, QR Scan & Share), M2 (Health Information Provider/HIP push of FHIR R4 Bundles), and M3 (Health Information User/HIU pull of longitudinal records via digital consent manager) protocols.",
        "primary_actors": ["ABDM Gateway Connector", "Staff Nurse", "Medical Officer", "Citizen / Patient"],
        "criticality": "National Compliance & Strategic (P0)",
        "offline_tier": "Tier 2 - Queued ABDM Transactions with Asynchronous Callback Handling",
        "abdm_role": "Core Master Specification for All ABDM M1, M2, and M3 Workflows",
        "upstream_objectives": ["OBJECTIVE-004", "OBJECTIVE-011"],
        "upstream_scopes": ["SCOPE-001", "INSCOPE-006", "INSCOPE-018"],
        "upstream_personas": ["PERSONA-001", "PERSONA-002", "PERSONA-007"],
        "upstream_roles": ["ROLE-001", "ROLE-002"],
        "upstream_reqs": ["BR-025", "FR-024", "NFR-024", "BRULE-024", "CR-024", "OR-024", "SECR-024", "PRIV-024", "PERF-024", "AVAIL-024", "LOC-024", "A11Y-024", "OFF-024", "REP-024", "ANL-024"],
    },
    {
        "id": "WF-025",
        "num": "25",
        "file": "25-emergency-exception-workflow.md",
        "name": "Clinical Emergency Exception, Fast-Track Bypass & Resuscitation Protocol Workflow",
        "domain": "Trauma, Resuscitation & Emergency Clinical Governance",
        "summary": "Establishes rapid-response exception protocols for mass casualties, trauma, acute anaphylaxis, or unconscious unidentified citizens. Enables immediate queue and authentication bypass, creates provisional 'Unknown Citizen' records, unlocks emergency drug trays, permits verbal orders, and enforces post-stabilization reconciliation.",
        "primary_actors": ["Medical Officer", "Staff Nurse", "Pharmacist", "Emergency Transport Crew"],
        "criticality": "Life Safety & Legal Critical (P0)",
        "offline_tier": "Tier 1 - Immediate Zero-Latency Local Execution with Complete Audit Preservation",
        "abdm_role": "Emergency Implied Consent Exception under ABDM and DPDP Act Guidelines",
        "upstream_objectives": ["OBJECTIVE-002", "OBJECTIVE-008", "OBJECTIVE-013"],
        "upstream_scopes": ["SCOPE-003", "INSCOPE-014"],
        "upstream_personas": ["PERSONA-001", "PERSONA-002", "PERSONA-003"],
        "upstream_roles": ["ROLE-001", "ROLE-002", "ROLE-003"],
        "upstream_reqs": ["BR-026", "FR-025", "NFR-025", "BRULE-025", "CR-025", "OR-025", "SECR-025", "PRIV-025", "PERF-025", "AVAIL-025", "LOC-025", "A11Y-025", "OFF-025", "REP-025", "ANL-025"],
    },
]

WORKFLOW_MAP = {wf["id"]: wf for wf in WORKFLOW_SPECS}
